CHANGELOG.md
Purchases.podspec
Purchases/Classes/Public/Purchases.h
Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
Purchases/Classes/RCBackend.h
Purchases/Classes/RCBackend.m
Purchases/Classes/RCPurchases+Protected.h
PurchasesTests/BackendTests.swift
PurchasesTests/PurchasesTests.swift
README.md

API key helps to disambiguate from the App-Specific Shared Secret in iTunesConnect.
Note: This is not compatible with the current version of the backend. The backend will be updated when 0.2.0 is ready.

[FINAL] Rename shared secret to API key

---

Purchases.podspec
Purchases.xcodeproj/project.pbxproj
Purchases/Classes/NSLocale+RCExtensions.h
Purchases/Classes/NSLocale+RCExtensions.m
Purchases/Classes/Public/RCPurchases.m

This adds support for iOS 9.
The only change was adding a runtime check for the `-[NSLocal currencyCode]` method which was introduced in iOS 10.0

[FINAL] Add support for iOS 9

---

Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
Purchases/Classes/RCStoreKitWrapper.h
Purchases/Classes/RCStoreKitWrapper.m
PurchasesTests/PurchasesTests.swift
PurchasesTests/StoreKitWrapperTests.swift

Adds support for [promotional in-app purchases](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/PromotingIn-AppPurchases/PromotingIn-AppPurchases.html).
By default, `RCPurchases` will not allow promotional purchases to proceed. Developers will need to implement the `purchases:shouldPurchasePromoProduct:` `RCPurchasesDelegate` method to override this behavior.

[FINAL] Promotional Purchases

---

Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Apple is very specific about using the same payment object for deferring a promotional purchase:
Since `RCPurchases` only has an API for adding products, and not payments, I'm passing a defermentBlock to the delegate that clients can save and call when they are ready.

[FINAL] Add handling for deferring a promotional payment

---

Purchases/Classes/RCBackend.m
PurchasesTests/BackendTests.swift

I realized that we were using `appUserID`s in the URL for getting a subscribers status. This would have crashed if someone ever used an `appUserID` that had any non URL friendly characters in it. 
This fixes it by encoding the appUserID first.

[FIX] Encoding App User ID in the URL

---

Purchases/Classes/Public/RCPurchases.m

Simple fix to not assert delegate existence. 
This can happen when there are requests in flight when an `RCPurchases` object is torn down

[FINAL] Remove delegate param asserts.

---

CHANGELOG.md
Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Some API changes and clean up to make React Native integration a little easier.
- Change `restoreTransactionsForAppStoreAccount:` to take a completion block since it no long relies on the app store queue. Removed delegate methods.
- Added `updatedPurchaserInfo:` that allows force refreshing of `RCPurchaserInfo`. Useful if your app needs the latest purchaser info.
- Removed `makePurchase:quantity:`.

[FINAL] API Changes

---

CHANGELOG.md
Purchases.xcodeproj/project.pbxproj
Purchases/Classes/Public/RCPurchaserInfo.h
Purchases/Classes/Public/RCPurchaserInfo.m
PurchasesTests/PurchaserInfoTests.swift

- Add `nonConsumablePurchases` on `RCPurchaserInfo`. Non-consumable purchases will now Just Work (tm).

[FINAL] Support for Non-consumable Purchases

---

CHANGELOG.md
Purchases.xcodeproj/project.pbxproj
Purchases/Classes/Public/Purchases.h
Purchases/Classes/Public/RCIntroEligibility.h
Purchases/Classes/Public/RCIntroEligibility.m
Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
Purchases/Classes/RCBackend.h
Purchases/Classes/RCBackend.m
Purchases/Classes/RCHTTPClient.m
PurchasesTests/BackendTests.swift
PurchasesTests/PurchasesTests.swift

- Add support of checking eligibilty of introductory prices. RevenueCat will now be able to tell you definitively what version of a product you should present in your UI.

[FINAL] Eligibility Checking Support

---

Purchases/Classes/RCBackend.m
PurchasesTests/BackendTests.swift

If we request to send the same receipt while a previous send is in flight, we don't initiate a request but just attach the completion block to the current request.

[FINAL] Request Caching

---

Purchases/Classes/Public/RCPurchaserInfo.m
Purchases/Classes/Public/RCPurchases.m
Purchases/Classes/RCPurchaserInfo+Protected.h
PurchasesTests/PurchaserInfoTests.swift
PurchasesTests/PurchasesTests.swift

The latest RCPurchaserInfo will now be cached by RevenueCat so the client apps don't have to worry about caching it themselves.

[FINAL] Caching Purchaser Info

---

Purchases/Classes/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

- Adds a test for caching on purchase
- SDK now emits the cached version of the purchaser info when activating within throttle limit

[FINAL] Better Caching

---

Purchases/Classes/Public/RCOffering.h
Purchases/Classes/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Now, if a product is missing, it is nil, rather than nuking the whole entitlement.
This should be a more graceful failure mode.

[FINAL] Entitlements Don't Fail if Product Missing

---

Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

This is necessary to have optional protocol requirements. I saw that it was previously casting `self.delegate` to `id<NSObject>` but that isn't the best way to do it.

Conform RCPurchasesDelegate to NSObject

---

Purchases/Classes/Public/RCPurchaserInfo.h
Purchases/Classes/Public/RCPurchaserInfo.m
PurchasesTests/PurchaserInfoTests.swift

Before this PR, we are checking the validity of a subscription by comparing the current timestamp with the expiration date of the subscription.
It turns out that if we check that against a cached subscription, we could get into the edge case that the user could have renewed (extending the expiration date) and we would be checking against an older expiration date, which will lead to a returning subscription.
This PR makes a change in the way we check if a subscription is valid. We check now the expiration date against the date the version of the purchaser information we have available (remember, if it's a cached version, it could be really old, even older than a renewal date).
To avoid problems with older cached versions that use the next version of the SDK, if the request_date is not …

Adds requestDate to the purchaser info to avoid edge cases

---

Purchases/Classes/Public/RCPurchaserInfo.h
Purchases/Classes/Public/RCPurchaserInfo.m

Hey guys,
A few days ago we were talking on the forums about how to get purchase dates - as you suggested I've forked and added those methods. You can now get purchase dates by entitlement or product identifier
- (NSDate * _Nullable)purchaseDateForEntitlement:(NSString *)entitlementId;
- (NSDate * _Nullable)purchaseDateForProductIdentifier:(NSString *)productIdentifier;
For my use I only needed entitlement, but I thought it would be good to add product too.
I'm pretty sure this should be good to go, but have a check over and let me know.
Thanks for all the amazing work on this so far!
Emile

Added methods for getting purchase dates of products and entitlements

---

.gitignore
Purchases/Classes/Public/RCPurchases.h
Purchases/Classes/Public/RCPurchases.m
Purchases/Classes/RCBackend.h
Purchases/Classes/RCBackend.m
PurchasesTests/BackendTests.swift
PurchasesTests/PurchasesTests.swift

This PR creates configuration methods that create a singleton instance of Purchases. This instance can be accessed through `defaultInstance`.
This will ensure there is a single instance created for purchases and the SDK is not recreated multiple times, which is what is recommended in the documentation

Creates a configuration method that creates a singleton

---

.gitignore
Purchases/Classes/Public/RCPurchaserInfo.m
PurchasesTests/PurchaserInfoTests.swift

This is a followup of https://github.com/RevenueCat/purchases-ios/pull/56
I added a couple tests and extracted common logic into a method.

Adds test for Purchase Date

---

Cartfile.resolved
Purchases/Public/RCPurchases.m
Purchases/RCBackend.m
PurchasesTests/Info.plist
PurchasesTests/PurchasesTests.swift

- Identify and reset were not updating the cached purchaser info
- I fixed a bug that made create alias not work if not passing a completion block
- I also added appuserid as part of the cache key of the backend post receipt handlers

Forces update of caches on reset and identify

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Name is confusing, so renaming

Renames isUsingAnonymousID to allowSharingAppStoreAccount

---

Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Looking at https://docs.revenuecat.com/discuss/5c479f9f9c2c64013f2836a2 
> I've been using the auto generated ID, what's the best way to retroactively add the UID to the account without having them to restore transactions?
The solution is:
>You can use the .createAlias method to attach your User ID to the purchase history of a previous randomly generated App User ID. After you get your account UID you can check to see if it equals the current App User Id for the Purchases instance - if not, call .createAlias.
To make things easier, I added this check in the code so that users that are calling `createAlias` are not triggering useless backend calls.

Makes sure we don't create alias or identify over the same app user id

---

CHANGELOG.md
Cartfile.resolved
Examples/SwiftExample/Podfile.lock
Examples/SwiftExample/SwiftExample.xcodeproj/project.pbxproj
Examples/SwiftExample/SwiftExample/AppDelegate.swift
Examples/SwiftExample/SwiftExample/UpsellViewController.swift
Purchases.podspec
Purchases.xcodeproj/project.pbxproj
Purchases.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
Purchases/Info.plist
Purchases/Public/Purchases.h
Purchases/Public/RCIntroEligibility.m
Purchases/Public/RCOffering.h
Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
Purchases/Public/RCPurchasesErrorUtils.h
Purchases/Public/RCPurchasesErrorUtils.m
Purchases/Public/RCPurchasesErrors.h
Purchases/RCBackend.h
Purchases/RCBackend.m
Purchases/RCPurchases+Protected.h
Purchases/RCReceiptFetcher.h
Purchases/RCReceiptFetcher.m
Purchases/RCUtils.h
Purchases/RCUtils.m
PurchasesTests/BackendTests.swift
PurchasesTests/PurchaserInfoTests.swift
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/PurchasesTests.swift

Easier way to detect if user cancelled purchase
---
- Adds `userCancelled` as a parameter to the completion block of the makePurchase function
Avoid sending empty receipts to the backend
---
- Avoids posting empty receipts when restoring transactions and when making a purchase.  It will return a `RCMissingReceiptFileError` instead. 
- Avoid sending receipt when get intro eligibility if no receipt. It will just return an `RCIntroEligibilityStatusUnknown`.
Better error codes
---
- Creates `NSError+Purchases.h` that contain `RCPurchasesErrorCode`, `RCBackendErrorCode` and the UserInfo dictionary keys
- Unifies the Error domain to a single `RCPurchasesErrorDomain`. There is a `RCBackendErrorDomain` used in underlying backend errors.
- If there is an SKError it maps the error code to our own …

Error overhaul

---

Cartfile.resolved
Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
Purchases/RCPurchases+Protected.h
PurchasesTests/PurchasesTests.swift

- Adds an optional `observerMode` to configure function
- Treats SKPaymentTransactionStateRestored transactions same as purchases to offer observer mode for restores too

Adds observer mode as a boolean in configuration function

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

I deprecated `automaticAttributionCollection` to avoid breaking people's compilation and I created a new  `automaticAppleSearchAdsAttributionCollection` that has the same effect.

Renames automaticAttributionCollection to automaticAppleSearchAdsAttributionCollection

---

Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Removes fallback to `appUserID` if `networkUserId` is not provided when posting attribution. This will match Android's behavior and let the backend decide

Removes fallback to appUserID when posting attribution

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

- Added two error logs
- Fixed typo in the NS_SWIFT_NAME. This will break compilation but there's no way to deprecate it.

Error logs for AppsFlyer if missing networkUserID

---

Purchases/Public/RCEntitlementInfo.h
Purchases/Public/RCEntitlementInfo.m
Purchases/Public/RCEntitlementInfos.h
Purchases/Public/RCEntitlementInfos.m
Purchases/Public/RCPurchaserInfo.h
Purchases/Public/RCPurchaserInfo.m
Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
Purchases/Public/RCPurchasesErrorUtils.h
Purchases/Public/RCPurchasesErrorUtils.m
Purchases/RCAttributionData.h
Purchases/RCAttributionData.m
Purchases/RCAttributionFetcher.h
Purchases/RCAttributionFetcher.m
Purchases/RCBackend.h
Purchases/RCBackend.m
Purchases/RCHTTPClient.h
Purchases/RCHTTPClient.m
Purchases/RCPurchaserInfo+Protected.h
Purchases/RCPurchases+Protected.h
Purchases/RCStoreKitRequestFetcher.h
Purchases/RCStoreKitRequestFetcher.m
Purchases/RCStoreKitWrapper.h
Purchases/RCStoreKitWrapper.m

Changes existing `_Nullable` with `nullable` wherever it's possible because they are nicer. https://developer.apple.com/swift/blog/?id=25

Changes _Nullable to nullable and nonnull cleanup

---

Purchases/RCCrossPlatformSupport.h
Purchases/RCStoreKitWrapper.m

- TARGET_OS_UIKITFORMAC has been replaced with TARGET_OS_MACCATALYST (although they kept TARGET_OS_UIKITFORMAC for compatibility)
- `paymentQueue:shouldAddStorePayment` is marked as unavailable for Catalyst apps

Updates Catalyst conditionals

---

Purchases/Public/RCPurchaserInfo.h

Small improvement to the OG application version docs.

Clarify where the originalApplicationVersion string comes from.

---

Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

We got a crash report that showed either the product, payment or productIdentifier was nil. I added some protective measures to avoid the crash. Can't really add unit tests since Swift is smart and can't really pass a nil product to makePurchase, but I passed a product without product identifier to reproduce the crash.

Protects agains nil products or productIdentifiers

---

Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

Fixes https://github.com/RevenueCat/purchases-ios/issues/135
We were assuming the array of products is not empty but it's possible to get an empty array of SKProducts if the product that's in the transaction has been removed from App Store Connect

Crash when a removed product is still in a transaction in the queue

---

Examples/SwiftExample/SwiftExample/CatsViewController.swift
Examples/SwiftExample/SwiftExample/SwiftPaywall.swift
Purchases/Public/RCOfferings.h
Purchases/Public/RCOfferings.m
Purchases/RCOfferings+Protected.h

- I added visibility to `all` offerings. We already had the property in the class, so I just added it to the header and renamed it.
- Updated the sample with the `Purchases.` prefix of the Swift classes.

Adds access to "all" offerings

---

Purchases.xcodeproj/project.pbxproj

This silences a warning from Xcode and has no impact because this framework has no localised resources.

Enable base internationalisation

---

Purchases/Public/RCPurchases.m
Purchases/RCBackend.h
Purchases/RCBackend.m
PurchasesTests/BackendTests.swift
PurchasesTests/PurchasesTests.swift

Adds a new `observer_mode` parameter that will help us know if deverlopers have observer mode on or not.

Adds observer_mode to postReceipt calls

---

Purchases/Public/RCPurchases.m

Addresses https://trello.com/c/HlJygO8w, an issue where we would send apple search ads attribution info even if the value of `@"iad-attribution"` was false. 
The issue was that we were assuming that the value would come in as a boolean, but since it's part of a dictionary of NSString * -> NSObject *, it actually comes in as a string. 
using `boolValue` should address it and make the correct conversion back to bool.

[Final] Fix automaticAppleSearchAdsAttributionCollection on iOS SDK

---

RELEASING.md
fastlane/Fastfile
fastlane/README.md

Adds a quick lane to the fastfile to quickly bump versions. Will bump in the project file + podspec. 
I _think_ it can be expanded to also update RCPurchases... but we may have to do it manually.  
usage: 
```bash
fastlane bump version:x.y.z
```

[final] Feature/fastlane bump

---

Purchases.podspec
Purchases/Info.plist
Purchases/Public/RCPurchases.m
PurchasesTests/Info.plist

bumped to 3.1.0-SNAPSHOT using `fastlane increment_build_number` (the newest version updates RCPurchases.m as well)

[final] bump version to 3.1.0-SNAPSHOT

---

.gitignore
RELEASING.md
bin/release_version.sh
fastlane/Fastfile
fastlane/README.md

* Added fastlane lane that creates a github release and uploads the files. 
* Added a step to concatenate `CHANGELOG.latest.md` into `CHANGELOG.md`. The separate file makes it easy to use for the github release as well

[final] automate GitHub release

---

fastlane/Fastfile
fastlane/README.md

Added a convenience method for creating sandbox users, since going through app store connect is a giant PITA and sometimes you need multiple accounts. 
usage: 
```bash
fastlane create_sandbox_account email:<email> password:<password>
```
This will prompt for your developer portal credentials, 2fa code (if enabled). 
**Note:** if you get an error, make sure to follow the password requirements: at least one capital letter, one punctuation mark and one number. Also, the email can't take `+` signs.

[final] fastlane create_sandbox_user

---

.circleci/config.yml

follow-up to https://github.com/RevenueCat/purchases-ios/pull/166, updates 
`carthage update` -> `carthage bootstrap`, since `update` actually upgrades libraries and was causing tests to fail because it was using a different version of `OHHTTPStubs` than what the code uses.

[final] fix tests

---

Purchases/Public/RCPurchases.m
Purchases/RCBackend.h
Purchases/RCBackend.m
Purchases/RCHTTPClient.h
Purchases/RCHTTPClient.m
PurchasesTests/HTTPClientTests.swift

This PR adds a function to `RCPurchases` that will be used by the hybrid SDKs to indicate the platform. We don't have a way right now to know if a http request is coming from Cordova, ReactNative, Unity, etc. and we only know if the underlying SDK is Android or iOS. We should start sending a new header in the HTTP requests that indicate the platform flavor.
The idea would be to add a header to the Cordova, ReactNative, etc. SDKs that will expose this function and to call it in every setup call.

Adds platform flavor private configure method

---

Purchases/Caching/RCDeviceCache+Protected.h

Adds a missing nullability specifier that's tripping up pod trunk. 
```bash
pod trunk push Purchases.podspec
```
is failing on master due to: 
```
Validating podspec
-> Purchases (3.0.3)
- NOTE  | xcodebuild:  note: Using new build system
- NOTE  | xcodebuild:  note: Planning build
- NOTE  | xcodebuild:  note: Constructing build description
- NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
- WARN  | xcodebuild:  Purchases/Purchases/Caching/RCDeviceCache+Protected.h:16:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
- NOTE  | xcodebuild: …
```

fix: missing nullability specifier makes pod trunk fail

---

.jazzy.yaml
CHANGELOG.md
Gemfile.lock
Package.swift
Purchases.podspec
Purchases/Info.plist
Purchases/Public/RCPurchases.m
PurchasesTests/Info.plist

The `Caching` group hadn't been added to package.swift spec for Swift Package Manager, so you'd get an error saying "'RCDeviceCache.h' file not found". 
This was reported here: https://github.com/RevenueCat/purchases-ios/issues/176
This fixes the issue and bumps the version number to 3.0.4. I confirmed it's working by setting the version rules to the branch under Swift Packages.

[Final] Fix: build issue in Swift Package Manager

---

bin/release_version.sh

Fixed a couple of issues in the release script: 
- a fastlane command wasn't called correctly
- the result from cocoapods wasn't read correctly, so it would prevent the rest of the script from executing

[final] fix a couple of release script issues

---

Purchases/Public/RCPurchases.m

Fixes a couple of issues from https://github.com/RevenueCat/purchases-ios/pull/168, in `RCPurchases.h`:
- The completion block from `offeringsWithCompletionBlock` could be called more than once if outdated cached offerings exist
- removed redundant method `updateCacheAndSendUpdatedPurchaserInfoIfChanged`
- unified error handling for offerings update under `handleOfferingsUpdateError`

[final] cleanup after #168

---

.circleci/config.yml

I didn't like that master had all CI tests without completing (due to the nature of the approval job we have right now for deploying docs).

Changes trigger of docs-deploy to deploy when tagging

---

Package.swift
Purchases.podspec
Purchases.xcodeproj/project.pbxproj
Purchases/RCDateProvider.h
Purchases/RCDateProvider.m
Purchases/SubscriberAttributes/RCSpecialSubscriberAttributes.h
Purchases/SubscriberAttributes/RCSubscriberAttribute+Protected.h
Purchases/SubscriberAttributes/RCSubscriberAttribute.h
Purchases/SubscriberAttributes/RCSubscriberAttribute.m
PurchasesTests/Mocks/MockDateProvider.swift
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/SubscriberAttributes/SubscriberAttributeTests.swift

I split up https://github.com/RevenueCat/purchases-ios/pull/186 into 4 smaller, more focused PRs. 
Part 1 contains the `RCSubscriberAttributes` class, a simple data class that can hold info for subscriber attributes, and knows how to convert into NSUserDefaults format as well as backend format.

[Final] subscriber attributes part 1

---

Purchases.xcodeproj/project.pbxproj
Purchases/NSDate+RCExtensions.h
Purchases/NSDate+RCExtensions.m
Purchases/NSError+RCExtensions.h
Purchases/NSError+RCExtensions.m
Purchases/Public/RCPurchases.m
Purchases/Public/RCPurchasesErrorUtils.m
Purchases/Public/RCPurchasesErrors.h
Purchases/RCBackend.h
Purchases/RCBackend.m
Purchases/RCPurchasesErrorUtils+Protected.h
Purchases/SubscriberAttributes/RCSubscriberAttribute.m
PurchasesTests/BackendTests.swift
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/NSDate+RCExtensionsTests.swift
PurchasesTests/NSError+RCExtensionsTests.swift
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributeTests.swift

This is the second part of the subscriber attributes PR: 
It adds backend methods for posting to the subscriber attributes endpoint, as well as logic for sending in the unsynced attributes on the post receipt request.

[Final] Subscriber attributes Part 2: Backend

---

Purchases/Public/RCPurchaserInfo.h
Purchases/Public/RCPurchaserInfo.m
Purchases/RCPurchaserInfo+Protected.h
PurchasesTests/PurchaserInfoTests.swift
PurchasesTests/PurchasesTests.swift

For many apps using the originalApplicationVersion is no good since it returns the build number instead of the version number. The scope of this PR is to:
- Clearly indicate that **originalApplicationVersion** is the **build number**
- Expose **originalPurchaseDate** to be used as an alternative for migrating paid apps to freemium
Edit: Added tests
Edit 2: Fixed the naming mixup in the PR description

Expose original_purchase_date

---

Purchases.xcodeproj/project.pbxproj
Purchases/NSData+RCExtensions.h
Purchases/NSData+RCExtensions.m
Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.h
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.h
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m
PurchasesTests/Mocks/MockSubscriberAttributesManager.swift
PurchasesTests/NSData+RCExtensionsTests.swift
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/SusbcriberAttributesManagerTests.swift

Updated the `setPushToken` call to receive `NSData` instead of `NSString` to make it easier for developers to send us the value, since this way they won't have to do any form of conversion themselves.

[final] subscriber attributes part 5: push token as data

---

Purchases/NSData+RCExtensions.m
Purchases/NSError+RCExtensions.h
Purchases/NSError+RCExtensions.m
Purchases/Public/RCPurchases.m
Purchases/RCBackend.h
Purchases/RCBackend.m
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.h
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
PurchasesTests/NSError+RCExtensionsTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

Follow-up to comment in Part 4, @vegaro correctly pointed out that we're not printing out attributes errors on post receipt. 
https://github.com/RevenueCat/purchases-ios/pull/190#discussion_r389219164
This unifies the logic for attributes errors for post receipt and post subscriber attributes, and adds logging of the errors in the post receipt case.

[final] subscriber attributes: log errors on post receipt

---

Purchases/Public/RCPurchasesErrorUtils.m
Purchases/Public/RCPurchasesErrors.h

* updated invalid subscriber attributes error code: 7262 -> 7263
* added invalid subscriber attributes request body error code: 7264
* added a couple of error codes cases missing from a switch statement
✅  tested and working with a local khepri instance, forcing the error codes to appear on every request for test purposes.

[final] fix subscriber attributes error codes

---

Purchases/Public/RCPurchases.m
PurchasesTests/PurchasesTests.swift

The completion block for `purchaserInfoWithCompletionBlock` could be called more than once in the case where there was cached information, but it was outdated. 
This PR ensures that it gets called only once.

[final] Fix: completion called twice for get purchaser info

---

Examples/SwiftExample/SwiftExample/AppDelegate.swift
Purchases/Public/RCPurchases.h
README.md
bin/release_version.sh

Small fixes: 
- the release script was referencing a fastlane lane that was under the group `ios`, so it needs to be called with `ios` first
- the docs for `setPushToken` in `RCPurchases.m` say to pass an empty string or nil to erase data, however since the param is of type NSData, you can't pass in an empty string.

[final] fix: release script and docs

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Public/RCPurchases.m
PurchasesTests/Info.plist

- small fixes to docs and release scripts: 
- the release script was referencing a fastlane lane that was under the group ios, 
so it needs to be called with ios first
- the docs for setPushToken in RCPurchases.m say to pass an empty string or nil to erase data, 
however since the param is of type NSData, you can't pass in an empty string.
https://github.com/RevenueCat/purchases-ios/pull/203

[final] Version 3.1.1

---

Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.h
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.h
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m
PurchasesTests/Mocks/MockSubscriberAttributesManager.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/SusbcriberAttributesManagerTests.swift

SDKs like cordova don't have direct access to iOS push tokens. Instead, they go through libraries like [this one](https://github.com/phonegap/phonegap-plugin-push). Those libraries typically return the token as a string instead of the native `NSData *`. 
This PR adds an extra method, to be used by those libraries, so they can set push tokens. 
A follow-up PR on purchases-hybrid-common will expose the calls to the common repo, so the new method can be used solely by those SDKs, to avoid confusion.

[final] setPushTokenString

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Public/RCPurchases.m
PurchasesTests/Info.plist

- Added an extra method, `setPushTokenString`, to be used by multi-platform SDKs that don't 
have direct access to the push token as `NSData *`, but rather as `NSString *`.
https://github.com/RevenueCat/purchases-ios/pull/208

[final] Version 3.1.2

---

.circleci/config.yml
Purchases.xcodeproj/project.pbxproj
Purchases/NSLocale+RCExtensions.m
Purchases/Public/RCPackage.m
Purchases/Public/RCPurchases.m
Purchases/RCBackend.m
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m

there were a couple of build warnings on tvOS because we weren't checking for API availability on tvOS. 
This fixes them and sets the min deployment target for tvOS to 9.0

[final] fix build warnings on tvOS

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Public/RCPurchases.m
PurchasesTests/Info.plist

- Fixed build warnings on tvOS and API availability checks
https://github.com/RevenueCat/purchases-ios/pull/212

[final] version 3.2.1

---

.circleci/config.yml

Context: updating the xcode version to 11.4 updated the Circle CI docker image, which in turn updated the python version used for jazzy docs. 
This unfortunately broke the call to `pip install`. 
This attempt to fix jazzy docs process by updating the call to pip to `python -m pip`, which should get the right instance of `pip` for the python installation, independently of how `pip` is aliased. 
Note: I'm not sure whether `sudo` is still needed here.

[final] fix call to pip to update jazzy docs

---

Purchases/Public/RCPurchases.h

Invalidating the cache is simultaneously an advanced technique and attractive to beginners who might think they need to invalidate the cache on every app launch, so I added a link to our docs that explains how to work with the cache in normal circumstances.
If this update looks good I can open PRs for similar changes on the other SDKs as well.

Update invalidatePurchaserInfoCache docs

---

Purchases/Public/RCPurchases.m

Addresses #225, there was an issue where: 
- the productIdentifier in either payment or product can be nil
- we check which one we should use and assign it to `productIdentifier`
- but afterwards, we were using the ones in the payment and product directly, assuming them to be non-nil, instead of the `productIdentifier` we created previously.

fix crash when payment.productIdentifier is nil

---

Purchases/Caching/RCDeviceCache.m
PurchasesTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift

When all subscriber attributes had been synced for a user, we were still calling 
`RCBackend.postSubscriberAttributes` unnecessarily. 
This call was a no-op because the method checks if there are any attributes to sync and early-exists, so this is more of a cleanup. 
this was visible in the logs, where you'd see: `called post subscriber attributes with an empty attributes dict!`.

cleanup: remove unnecessary no-op call to RCBackend's postSubscriberAttributes

---

README.md

The Trello board has been removed since we weren’t doing a good job of keeping it up to date and have decided to sunset it for now.
https://github.com/RevenueCat/purchases-ios/issues/230

Removes old trello link

---

Purchases/Caching/RCDeviceCache+Protected.h
Purchases/Caching/RCDeviceCache.m
PurchasesTests/Caching/DeviceCacheTests.swift
PurchasesTests/Mocks/MockNotificationCenter.swift

To prevent cases where the appUserID is deleted accidentally, this adds observing changes to the userDefaults's appUserID, and crashes whenever the value gets deleted.

Autodetect appUserID deletion

---

Purchases.xcodeproj/project.pbxproj
Purchases/Caching/RCDeviceCache.h
Purchases/Caching/RCDeviceCache.m
Purchases/RCIdentityManager.m
Purchases/RCStoreKitRequestFetcher.m
PurchasesTests/IdentityManagerTests.swift
PurchasesTests/Mocks/MockDeviceCache.swift
PurchasesTests/Mocks/MockUserDefaults.swift
PurchasesTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift

This fixes edge cases in the subscriber attributes bug fixes: 
- Alice sets attributes and syncs
- Alice is aliased to Bob
- Bob syncs attributes, but never deletes attributes for Alice because they've already been successfully synced. 
- Attributes are set for more than 1 user before migrating to the new format
- Attributes are migrated to the new format only for the current user. 
- Upon initializing, we look for subscriber attributes in the old format for all users and migrate them. 
- After this step, we look for subscriber attributes for all users but the current one, that are already synced. We delete them. 
- more detailed tests for the edge cases described above 
- cleanup for readability

fix: subscriber attributes migration edge cases

---

Purchases.xcodeproj/project.pbxproj
Purchases/Public/RCPurchases.m
Purchases/RCBackend.h
Purchases/RCBackend.m
Purchases/RCHTTPClient.h
Purchases/RCHTTPClient.m
Purchases/RCHTTPStatusCodes.h
Purchases/RCPurchases+Protected.h
Purchases/RCSystemInfo.h
Purchases/RCSystemInfo.m
Purchases/RCUtils.h
Purchases/RCUtils.m
PurchasesTests/BackendTests.swift
PurchasesTests/HTTPClientTests.swift
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
fastlane/Fastfile

This adds the new `X-Observer-Mode-Enabled` header, and does quite a bit of refactoring: 
- Created new enum for http status codes: `HTTPStatusCodes`
- Clean up on RCHTTPClient: 
- Extract methods and clean up / modernize logic
- The class was violating SRP by including logic for system metadata, this was extracted into a separate data class, `RCSystemInfo`. 
- Move storage of the `finishTransactions` property and `platformFlavor` to `RCSystemInfo`
- Updated tests and added tests for the new header

Observer mode header + cleanup

---

Purchases/Caching/RCDeviceCache.h
Purchases/Caching/RCDeviceCache.m
Purchases/RCIdentityManager.m
PurchasesTests/Caching/DeviceCacheTests.swift
PurchasesTests/IdentityManagerTests.swift
PurchasesTests/Mocks/MockDeviceCache.swift

Fixes a bug in #232 that would cause identify and alias to crash. 
Also, fixes race conditions that we've had here forever, since you could potentially have a nil appUserID between clearing cache and saving a new appUserID
Missing tests but reviewable otherwise

fix crash after identify and alias

---

Purchases/Public/RCPurchases.m
Purchases/RCHTTPClient.m
Purchases/RCSystemInfo.h
Purchases/RCSystemInfo.m
PurchasesTests/BackendTests.swift
PurchasesTests/HTTPClientTests.swift
PurchasesTests/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

Adds new header, `X-Platform-Flavor-Version`, meant to indicate the version of the hybrid SDK, if any. 
For the native SDK, this header will not be passed.

Platform flavor version header

---

CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
PurchasesTests/Info.plist
fastlane/Fastfile

Bump version number, also updates `Fastfile`'s `bump_and_update_changelog` to reflect the new file system structure
- Reorganized file system structure for the project
https://github.com/RevenueCat/purchases-ios/pull/242
- New headers for observer mode and platform version
https://github.com/RevenueCat/purchases-ios/pull/237
https://github.com/RevenueCat/purchases-ios/pull/240
https://github.com/RevenueCat/purchases-ios/pull/241
- Fixes subscriber attributes migration edge cases
https://github.com/RevenueCat/purchases-ios/pull/233
- Autodetect appUserID deletion
https://github.com/RevenueCat/purchases-ios/pull/232
https://github.com/RevenueCat/purchases-ios/pull/236
- Removes old trello link
https://github.com/RevenueCat/purchases-ios/pull/231
- Removes unused functions …

version 3.3.0

---

Purchases/Misc/RCCrossPlatformSupport.h

**Description:**
As described on https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue?language=objc , the method ```- (BOOL)paymentQueue:(SKPaymentQueue *)queue shouldAddStorePayment:(SKPayment *)payment forProduct:(SKProduct *)product``` is only available for iOS and tvOS but not for Mac Catalyst.
However `PURCHASES_INITIATED_FROM_APP_STORE_AVAILABLE` is set to 1 for Mac Catalyst which leads to a unavailable method warning:
```
RevenueCat/purchases-ios/Purchases/Purchasing/RCStoreKitWrapper.m:87:1: warning: implementing unavailable method [-Wdeprecated-implementations]
- (BOOL)paymentQueue:(SKPaymentQueue *)queue shouldAddStorePayment:(SKPayment *)payment forProduct:(SKProduct *)product
^
In module 'StoreKit' imported from …
```

Prevent a warning when compiling for Mac Catalyst

---

Purchases.podspec
Purchases/Misc/RCCrossPlatformSupport.h

- clean up `RCCrossPlatformSupport`: `TARGET_OS_IOS` is always true if `TARGET_OS_MACCATALYST` is true, simplified related conditions
- clean up Podspec, used `**` for subfolders

Cleanup rc cross platform support & podspec

---

Purchases/Public/RCPurchasesErrorUtils.h
Purchases/Public/RCPurchasesErrorUtils.m
Purchases/Public/RCPurchasesErrors.h
Purchases/Purchasing/RCIdentityManager.m
PurchasesTests/IdentityManagerTests.swift

Fixes an issue where if the appUserID is missing for whatever reason and you call createAlias, an alias to `(null)` would be created. 
This fix makes the method no-op and return an error with a specific error code. 
I was hesitant about adding the error code at first, but it's probably the best way to get developers to notice without sending the call to the backend.

fix: `(null)` aliases

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
Purchases/Public/RCPurchases.m
PurchasesTests/Info.plist

- Added `proxyKey`, useful for kids category apps, so that they can set up a proxy to send requests through. **Do not use this** unless you've talked to RevenueCat support about it. 
https://github.com/RevenueCat/purchases-ios/pull/258
- Added `managementURL` to purchaserInfo. This provides an easy way for apps to create Manage Subscription buttons that will correctly redirect users to the corresponding subscription management page on all platforms. 
https://github.com/RevenueCat/purchases-ios/pull/259
- Extra fields sent to the post receipt endpoint: `normal_duration`, `intro_duration` and `trial_duration`. These will feed into the LTV model for more accurate LTV values. 
https://github.com/RevenueCat/purchases-ios/pull/256
- Fixed a bug where if the `appUserID` was not found in …

bumped version number and added changelog for 3.4.0

---

Purchases/Purchasing/RCProductInfoExtractor.m

The Clang Static Analyzer reports 5 warnings in RCProductInfoExtractor.m: "nil returned from a method that is expected to return a non-null value"
The warnings have been fixed by adding the missing nullable keyword to the methods prototypes.

Static Analyzer reports 5 warnings in RCProductInfoExtractor.m

---

Examples/SwiftExample/Configuration.storekit
Examples/SwiftExample/SwiftExample.xcodeproj/xcshareddata/xcschemes/WatchExample.xcscheme
Purchases/Purchasing/RCIdentityManager.m

Updates the StoreKit config file to reflect the new product IDs in the RevenueCat Dashboard.
Also fixes a debug copy bug

update storekit config file

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesTests/Info.plist
RELEASING.md
fastlane/README.md

- Added a sample watchOS app to illustrate how to integrate in-app purchases on watchOS with RevenueCat
https://github.com/RevenueCat/purchases-ios/pull/263
- Fixed build warnings from Clang Static Analyzer
https://github.com/RevenueCat/purchases-ios/pull/265
- Added StoreKit Configuration files for local testing + new schemes configured to use them. 
https://github.com/RevenueCat/purchases-ios/pull/267
https://github.com/RevenueCat/purchases-ios/pull/270
- Added GitHub Issue Templates
https://github.com/RevenueCat/purchases-ios/pull/269

Release 3.5.0

---

Purchases.xcodeproj/project.pbxproj
Purchases/ProtectedExtensions/RCAttributionFetcher+Protected.h
Purchases/Public/RCPurchases.m
Purchases/Purchasing/RCAttributionFetcher.h
Purchases/Purchasing/RCAttributionFetcher.m
PurchasesTests/Misc/AttributionFetcherTests.swift
PurchasesTests/Mocks/MockAttributionFetcher.swift
PurchasesTests/PurchasesTests-Bridging-Header.h

We are getting some reports of Kids apps being rejected. It looks like the mentioning `ASIdentifierManager` or `advertisingIdentifier` in our code might be triggering these rejections.
The proposed solution is to use rot13 to rotate both strings on runtime and access them by looking up the class name and the property name.

Removes all references to ASIdentifierManager and advertisingIdentifier

---

Purchases/Purchasing/RCProductInfoExtractor.m
PurchasesTests/Purchasing/ProductInfoExtractorTests.swift

It looks like some consumables have a non nil `subscriptionPeriod` and we are posting P0D to the backend when posting the product duration. I was only able to replicate this on a 12.2 iPad pro simulator. 
This PR adds a check to make sure we don't post these wrong durations.

Fix for posting wrong duration P0D

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesTests/Info.plist

- Removes all references to ASIdentifierManager and advertisingIdentifier. This should help with some Kids apps being rejected 
https://github.com/RevenueCat/purchases-ios/pull/286
- Fix for posting wrong duration P0D on consumables
https://github.com/RevenueCat/purchases-ios/pull/289
Note this release is against main since develop had changes we didn't want to include

Version 3.5.1

---

.github/ISSUE_TEMPLATE/bug_report.md

**Description**
The template to create a new issue uses "XCode" instead of "Xcode"
**Steps to reproduce:**
- Create a new bug report on GitHub
**Result:**
The GitHub template contains the words "XCode/Android Studio version:"

Change in the GitHub bug report template "XCode" by the correct word "Xcode"

---

Examples/SwiftExample/SwiftExample/SwiftPaywall.swift

**Description**
I noticed a double space after an `else` statement. This change is purely cosmetic and has no effect on the behavior.

Replace a double space with a single space

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
PurchasesTests/Mocks/MockReceiptFetcher.swift
PurchasesTests/Purchasing/PurchasesTests.swift

If the receipt does not contain any subscription purchases, calling /verifyReceipt will not update an empty receipt with any purchased subscriptions.
We should trigger an SKReceiptRefresh if the device receipt does not contain any subscription purchases.

Forces refreshing the receipt when calling restore

---

Purchases/Public/RCPurchases.m
Purchases/Public/RCPurchasesErrorUtils.h
Purchases/Public/RCPurchasesErrorUtils.m
PurchasesTests/Purchasing/PurchasesTests.swift

Should fix https://github.com/RevenueCat/purchases-ios/issues/273
In order to test it add:
```
payment.simulatesAskToBuyInSandbox = YES;
```
to the `SKMutablePayment`. This flag will trigger a `SKPaymentTransactionStateDeferred`. The flow in sandbox is not the same as in production. In production, guardians get a notification with an approval request. In sandbox I have only managed to get that `SKPaymentTransactionStateDeferred` transaction. 
Please note that we are not finishing the transaction. The documentation is not clear, but looking at [https://developer.apple.com/documentation/storekit/in-app_purchase/offering_completing_and_restoring_in-app_purchases](https://developer.apple.com/documentation/storekit/in-app_purchase/offering_completing_and_restoring_in-app_purchases), it looks …

Fixes handling of deferred payments (ask to buy)

---

Purchases/Misc/RCCrossPlatformSupport.h
Purchases/Misc/RCSystemInfo.h
Purchases/Misc/RCSystemInfo.m
Purchases/Public/RCPurchases.m
PurchasesTests/Mocks/MockSystemInfo.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

`UIApplication.sharedApplication` isn't available in iOS app extensions. They won't compile if the method is used. 
Unfortunately, there's no pre-processor macro to check if the code is running within an app extension. There's also no direct API. 
Most of the solutions I found online seem to involve adding a custom flag to the app extension target's build settings... which is fine, if you're the app developer. If you're developing an SDK, however, this isn't an option. 
I realized that MParticle used to ask developers to create this custom flag, but afterwards removed that and instead they now check if the app's bundle has the filename extension `.appex`. 
This only works at runtime, so I had to refactor the related code a bit: I use KVC to call the method by name, if and only if the code …

Fix: application state check on app extensions

---

PurchasesTests/Purchasing/PurchasesTests.swift

Fixed tests that were occasionally failing on develop. 
the reason for this was that the fixes in #303 would move some calls to a background queue that takes longer to execute, especially on slow CI machines.

fix failing tests on develop

---

Purchases/Public/RCPurchases.m
Purchases/Public/RCPurchasesErrorUtils.h
Purchases/Public/RCPurchasesErrorUtils.m
PurchasesTests/Purchasing/PurchasesTests.swift

We were assuming `transaction.payment.productIdentifier` to not be nil in some places in `RCPurchases`.
This will most likely fix https://github.com/RevenueCat/purchases-ios/issues/279

Safeguard against nil productIdentifiers or payments

---

.circleci/config.yml

We were not caching the Carthage folder and `carthage bootstrap` takes 4 minutes atm. Hopefully this PR reduces that time to seconds
Before (10-15 min):
After (2 min):

Cache carthage files to speed up build times

---

Purchases.xcodeproj/project.pbxproj
Purchases/ProtectedExtensions/RCPurchases+Protected.h
Purchases/Public/RCPurchases.m
Purchases/SwiftInterfaces/RCOperationDispatcher.h
Purchases/SwiftSources/Misc/OperationDispatcher.swift
PurchasesTests/Mocks/MockOperationDispatcher.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

The tests are failing intermittently failing on `develop` right now because we have a couple of operations running in a background thread, and there's no guarantee of how long they will take to start, especially on CircleCI machines, which are pretty slow. 
This PR replaces those calls with a new `OperationDispatcher` object, that dispatches the operations. This allows us to mock it for tests and have the operations running synchronously. 
`OperationDispatcher` also has a few convenience methods that will allow us to remove the `CALL_IF_SET_ON_MAIN_THREAD` calls from `RCPurchases.m`.

Fix non determistic tests

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesTests/Info.plist

- Fix crash when productIdentifier or payment is nil.
https://github.com/RevenueCat/purchases-ios/pull/297
- Fixes ask-to-buy flow and will now send an error indicating there's a deferred payment.
https://github.com/RevenueCat/purchases-ios/pull/296
- Fixes application state check on app extensions, which threw a compilation error.
https://github.com/RevenueCat/purchases-ios/pull/303
- Restores will now always refresh the receipt.
https://github.com/RevenueCat/purchases-ios/pull/287
- New properties added to the PurchaserInfo to better manage non-subscriptions.
https://github.com/RevenueCat/purchases-ios/pull/281

Version 3.6.0-beta

---

Purchases.podspec

`pod lib lint` would issue warnings because the swift version wasn't specified. 
This fixes it by specifying the swift version.
```
Validating podspec
-> Purchases (3.6.0-beta)
- WARN  | swift: The validator used Swift `4.0` by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_versions` attribute in your podspec. Note that usage of a `.swift-version` file is now deprecated.
- NOTE  | xcodebuild:  note: Using new build system
- NOTE  | xcodebuild:  note: Building targets in parallel
- NOTE  | xcodebuild:  note: Planning build
- NOTE  | xcodebuild:  note: Constructing build description
- NOTE  | xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated …
```

added swift version to podspec

---

Purchases/Public/RCPurchases.m
PurchasesTests/Purchasing/PurchasesTests.swift

There was a race condition in `handleReceiptPostWithTransaction:purchaserInfo:subscriberAttributes:error:`. 
The issue was that in the order of operations, we were: 
1. fetching the completion block
1. performing the completion block
1. removing it from the callbacks list. 
If the completion block performed in 2. does something like initiate another purchase, it would access the callbacks list  before it got removed in 3, and then the code would see that there's already a completion block for the product and return the `RCOperationAlreadyInProgressError`. 
might address #291, but it's not guaranteed to since I'm not sure that this was the original issue.

addresses a possible race condition with purchase completed callbacks

---

Purchases/Public/RCPurchases.m
PurchasesCoreSwift/Misc/OperationDispatcher.swift

Replacement of #310. 
This PR doesn't delete the macros, but rather makes sure that they use the `OperationDispatcher` instead of doing the dispatching directly from `RCPurchases`.

clean up dispatch calls in RCPurchases

---

Purchases.swift
Purchases.xcodeproj/project.pbxproj

This makes a couple of updates to our modularization system: 
- `PurchasesCoreSwift` is now static instead of dynamic
- `Purchases` uses the `-all_load` linker flag. 
This makes it so that developers won't need to make any changes to their code in order to use the swift stuff, meaning that they don't have to manually link `PurchasesCoreSwift` or even know that it exists. 
The changes here were inspired by this (excellent) blog entry that proposes a modularized structure for iOS apps: 
https://medium.com/fluxom/building-a-dynamic-modular-ios-architecture-1b87dc31278b
Tested on: 
- manual dependency
- carthage
- swift package manager (changes shouldn't affect it anyway)
- cocoapods (changes shouldn't affect it anyway)
Tested by running the app on physical device, calling methods from the …

modularization improvement: static dependency

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist
RELEASING.md
fastlane/Fastfile
fastlane/README.md

- Fixed a race condition with purchase completed callbacks
https://github.com/RevenueCat/purchases-ios/pull/313
- Made RCTransaction public to fix compiling issues on Swift Package Manager
https://github.com/RevenueCat/purchases-ios/pull/315
- Added ability to export XCFrameworks
https://github.com/RevenueCat/purchases-ios/pull/317
- Cleaned up dispatch calls
https://github.com/RevenueCat/purchases-ios/pull/318
- Created a separate module and framework for the Swift code
https://github.com/RevenueCat/purchases-ios/pull/319
- Updated release scripts to be able to release the new Pod as well
https://github.com/RevenueCat/purchases-ios/pull/320
- Added a local receipt parser, updated intro eligibility calculation to perform on device first
https://github.com/RevenueCat/purchases-ios/pull/302 …

release: 3.6.0-beta-2

---

Purchases.xcodeproj/project.pbxproj
Purchases/ProtectedExtensions/RCPurchases+Protected.h
Purchases/Public/RCPurchases.m
PurchasesCoreSwift/LocalReceiptParsing/ReceiptParser.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/ReceiptParserTests.swift
PurchasesCoreSwiftTests/Mocks/MockReceiptParser.swift
PurchasesTests/Mocks/MockReceiptParser.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

https://app.clubhouse.io/revenuecat/story/70/ios-only-post-receipt-on-restore-if-there-are-transactions
Adds logic to check if a receipt has transactions, and if it doesn't, prevent an unnecessary post. 
The one exception to the rule is if `purchaserInfo` is empty or it doesn't have an `originalPurchaseDate`, since that data is sometimes used to grandfather in subscribers.

Prevent unnecessary receipt posts

---

Purchases/Purchasing/RCReceiptFetcher.m

The fix in https://github.com/RevenueCat/purchases-ios/pull/263 that was discussed in https://github.com/RevenueCat/purchases-ios/issues/207 now itself causes a bug when using sandbox on watchOS 7 as of beta 7. The bug that this workaround was added for appears to no longer occur, as when I remove the workaround, the receipt data is successfully retrieved.
```
DEBUG: Loaded receipt from file:///private/var/mobile/Containers/Data/PluginKitPlugin/DC8F7577-9BE0-4A54-81CE-0CECB386EC5C/StoreKit/sandboxReceipt
DEBUG: POST /v1/receipts
DEBUG: POST /v1/receipts 200
```
However, when the workaround is left in, retrieving the receipt data fails.
```
DEBUG: Loaded receipt from file:/private/var/mobile/Containers/Data/PluginKitPlugin/D857C0D0-2739-4D9B-A011-144948BC8274/StoreKit/receipt
DEBUG: …
```

Fix bug caused by workaround for watchOS sandbox receipts being stored at wrong path

---

Purchases/Caching/RCDeviceCache.h
Purchases/Caching/RCDeviceCache.m
Purchases/Public/RCPurchases.m
PurchasesTests/Mocks/MockDeviceCache.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Fixes an issue where after calling `invalidatePurchaserInfoCache` and then `purchaserInfoWithCompletion`, the invalidated cached version of purchaserInfo would be returned first, and only the delegate would get the updated version. 
This is fixed by entirely removing the cached version from storage, so that the SDK forcibly only returns a new version, if communication with the backend succeeds.

Fix: cached purchaserInfo returned after invalidating purchaserInfo cache

---

Purchases/Public/RCPurchasesErrorUtils.m

Added the new SKError codes introduced with Xcode 12. 
Addresses https://github.com/RevenueCat/purchases-ios/issues/292
I'm using `#ifdef __IPHONE_14_0` as a proxy to check that the Xcode version is at least 12, and it works correctly in practice. 
A couple of the codes are not compatible specifically with Apple TV, so I added a check for those as well.

added new SKError codes

---

Purchases/Misc/RCSystemInfo.h
Purchases/Misc/RCSystemInfo.m
Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m

We support Universal Purchases for Mac, but the migration path is a bit clunky right now. 
Our implementation allows for an app configured on the Dashboard to either be fully Universal or not, but it doesn't support having two versions of a Mac app, one for each store.
However, developers who have an existing Mac App may want their old (pre-universal purchases) version to live on a bit longer while they transition users into the new Mac app, and purchases for the old app should continue to work. 
Our workaround, previous to this PR, is to ask devs to: 
1. Have one version of the Mac app on the legacy store that uses the regular SDK
2. Have a new version of the Mac app, fork our repo, and override the value for `platformHeader` so that the backend interprets the new app as an iOS app (or …

improve migration process for legacy Mac App Store apps to Universal Store

---

Examples/SwiftExample/Podfile.lock
Purchases.podspec
Purchases/Public/RCPurchasesErrorUtils.m

Fixes a couple of issues on develop: 
- in https://github.com/RevenueCat/purchases-ios/pull/334, I missed the fact that a couple of SKErrors weren't just unavailable on tvOS - they were unavailable everywhere except for iOS. Updated accordingly. 
- the `Purchases.podspec` file still depends on `PurchasesCoreSwift` 3.6.0, removed the number so that the version can be resolved correctly when running locally.

fix issues on develop

---

Purchases/Public/RCPurchases.h

Replaces the TODOs in headers for the new attribution methods with docs.

replaced todos in attribution headers with docs

---

Purchases/Public/RCPurchases.m

Addresses https://github.com/RevenueCat/purchases-ios/issues/341

fix intro eligibility not returning on old OS versions

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist
fastlane/Fastfile

- Attribution V2:
- Deprecated `addAttributionData:fromNetwork:` and `addAttributionData:fromNetwork:forNetworkUserId:` in favor of `setAdjustId`, `setAppsflyerId`, `setFbAnonymousId`, `setMparticleId`
- Added support for OneSignal via `setOnesignalId`
- Added `setMediaSource`, `setCampaign`, `setAdGroup`, `setAd`, `setKeyword`, `setCreative`, and `collectDeviceIdentifiers`
https://github.com/RevenueCat/purchases-ios/pull/321
https://github.com/RevenueCat/purchases-ios/pull/340
https://github.com/RevenueCat/purchases-ios/pull/331
- Prevent unnecessary receipt posts
https://github.com/RevenueCat/purchases-ios/pull/323
- Improved migration process for legacy Mac App Store apps moving to Universal Store 
https://github.com/RevenueCat/purchases-ios/pull/336
- Added new SKError codes for Xcode …

release: 3.7.0

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

-  Fix 'Invalid bundle' validation error when uploading builds to App Store using Carthage or binary
https://github.com/RevenueCat/purchases-ios/pull/346

version 3.7.1

---

Purchases.xcodeproj/project.pbxproj
Purchases/Caching/RCDeviceCache.m
Purchases/Networking/RCBackend.m
Purchases/Networking/RCHTTPClient.h
Purchases/Networking/RCHTTPClient.m
Purchases/Networking/RCHTTPRequest.h
Purchases/Networking/RCHTTPRequest.m
Purchases/Public/RCPurchases.m
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.h
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Adds logic in `RCHTTPClient` so that it can perform requests either serially or in parallel. 
This works by keeping track of the request currently being performed (if any), and a queue of future requests, then when a serial request is finished, popping the queue and making the next request. 
Also solves the issues we had with 404s in attributes posts, since it fixes the order that the requests are performed in.
Adds a data class, `RCHTTPRequest`, as a convenience for making checks and passing information around. 
**Future work:** this does _not_ prevent duplicate requests in the queue. In order to do that correctly, we'd have to do something similar to what we're doing in `ProductsManager` and keep track of all completion blocks. 
I didn't want to go overboard and dive into something more …

Feature: run backend requests serially

---

Purchases.xcodeproj/project.pbxproj
Purchases/Public/RCPurchases.m
PurchasesCoreSwift/Logging/Strings/AttributionStrings.swift
PurchasesCoreSwift/Logging/Strings/Strings.swift

This PR creates a couple of files, meant for us to start moving logging strings into. 
It could be done a bit more neatly if this was purely swift or purely objective-c, but the mix sort of constraints possible solutions. 
What I wanted: 
- Quick-n-easy usage from anywhere, concise, easy to read
- Easy to split the strings into multiple files so that we don't end up with one megafile
- The files should be easy enough to read that they could be edited by non-technical people in the future if needed
- Easy migration to localization solutions if needed in the future, without modifying other files
- Avoiding loading all strings into memory if they're not used. 
- Autocomplete compatibility
The current solution checks all of those boxes. 
Open to suggestions.

logging v2 starter: strings [proposal]

---

Purchases.podspec
Purchases.xcodeproj/project.pbxproj
Purchases/Public/RCPurchases.h
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
PurchasesCoreSwift.podspec

This is part 1 of fixing build issues for cocoapods projects in hybrid sdks. 
Fixes: 
- makes the `Purchases` and `PurchasesCoreSwift` frameworks static. This means that other frameworks built from them will need to be static as well, since this is a cocoapods restriction. 
- replaced a couple of imports in `RCPurchases.h` with forward declarations, which is the way they should be done. This might also prevent issues with `RCPurchases.h` not being a modular header. 
- Moves `RCHTTPClient` from `Project` to `Private`. This is unrelated, but I missed this when writing it. 
Should address https://github.com/RevenueCat/purchases-flutter/issues/99

Fix build issues in hybrid sdks

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

- Updates the Pod to make it compile as a static framework, fixing build issues on hybrid SDKs. Cleans up imports in `RCPurchases.h`.
https://github.com/RevenueCat/purchases-ios/pull/353
- Fixes Catalyst builds and build warnings
https://github.com/RevenueCat/purchases-ios/pull/352
https://github.com/RevenueCat/purchases-ios/pull/351

version 3.7.2

---

Examples/SwiftExample/Podfile.lock
Purchases.xcodeproj/project.pbxproj
Purchases/Caching/RCDeviceCache.m
Purchases/FoundationExtensions/NSDictionary+RCExtensions.h
Purchases/FoundationExtensions/NSDictionary+RCExtensions.m
Purchases/Purchasing/RCAttributionFetcher.m
PurchasesTests/Misc/AttributionFetcherTests.swift
PurchasesTests/Misc/NSDictionaryExtensionsTests.swift
PurchasesTests/PurchasesTests-Bridging-Header.h

Addresses a crash that's been reported through ZenDesk and in https://github.com/RevenueCat/purchases-flutter/issues/105, where calling `addAttributionData` with `NSNull` values inside the `NSDictionary` would make the app crash. 
The problem is actually a regression in 3.7.0 in the caching of the latest sent values for each network. 
breaking line: 
https://github.com/RevenueCat/purchases-ios/pull/331/files#diff-16824aa266a8f5da37f049ed477c425bR158
original line: 
https://github.com/RevenueCat/purchases-ios/pull/331/files#diff-1f8164986a491f4cc448a01a1161e2bbL395
note that the object cached should have been `newDictToCache`, not `newData`.

Fix NSNull Attributes crash

---

PurchasesCoreSwift/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
PurchasesCoreSwiftTests/TestHelpers/ContainerFactory.swift

Attempt at fixing https://github.com/RevenueCat/purchases-ios/issues/358
If an in-app purchase container inside a receipt as an unexpected number of internal containers, the app will crash. 
The expected number of containers is exactly 3: type, version and value. But if for whatever reason that's not the case, the current code will crash with a `fatalError()`, which can't be caught by `try`. 
This is a problem, since this could be caused by a corrupt receipt file, but won't be recoverable. 
Fixed by replacing the `fatalError` with a custom exception. I missed this one when replacing all fatalErrors with custom exceptions initially.

fix: receipt parser crash with unexpected number of attributes

---

Purchases.xcodeproj/project.pbxproj

We use direct Xcode project integration for Purchases in our app PDF Viewer (i.e. no Swift Package Manager or anything). After updating to 3.7.2 we noticed our archives showed up under ‘Other Items’ in the Xcode Organiser instead of under ‘iOS Apps’. Generic archives like this can’t be uploaded to the App Store. The cause was that the Products directory in the archive contained Purchases.framework and PurchasesCoreSwift.framework in addition to PDF Viewer.app.
We resolved this by disabling SKIP_INSTALL for the two Purchases frameworks. I have not tested this with any other integration methods: I’m just providing what worked for us.

Skip install to fix archives with direct integration

---

PurchasesCoreSwift/LocalReceiptParsing/DataConverters/ISO3601DateFormatter.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/DataConverters/ISO3601DateFormatterTests.swift

It looks like Apple might have changed the format of dates in receipts, updating the resolution from seconds to milliseconds. 
This PR updates our parser so that we handle both cases, since some receipts will still be in the old format even after the update. 
More info: https://twitter.com/depth42/status/1313750495710904320

fix parsing of dates in receipts with milliseconds 

---

Purchases/Caching/RCDeviceCache.h
Purchases/Caching/RCDeviceCache.m
Purchases/Caching/RCInMemoryCachedObject.h
Purchases/Caching/RCInMemoryCachedObject.m
Purchases/ProtectedExtensions/RCDeviceCache+Protected.h
Purchases/Public/RCPurchases.m
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
PurchasesCoreSwift/Misc/OperationDispatcher.swift
PurchasesTests/Caching/DeviceCacheTests.swift
PurchasesTests/Caching/InMemoryCachedObjectTests.swift
PurchasesTests/Mocks/MockDeviceCache.swift
PurchasesTests/Mocks/MockInMemoryCachedOfferings.swift
PurchasesTests/Mocks/MockOperationDispatcher.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

Apps opening from push notifications and potentially widgets may cause unnecessary strain on the backend by making calls simultaneously on all devices.
To alleviate the backend strain, we want to introduce a small, random delay to cache updates performed while the app is in the background. This will distribute requests over time so that the backend isn’t hit at once.
We’re also going to be more aggressive with the cache while the app is in the background, moving it from 5 mins to 1 day.
The value of 5 mins will still be used if the app is in the foreground.
Ruleset:
- if app is opened and in the foreground
- if cache is older than 5 mins
- update cache
- if app is opened and in the background:
- if cache is older than one day:
- update cache (with jitter)

Add jitter and extra cache for background processes

---

PurchasesTests/Misc/ISOPeriodFormatterTests.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
PurchasesTests/Purchasing/ProductInfoTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Tests currently fail on iOS < 12.2, because they assume that the APIs for subscription offers are available. 
This fixes those tests. 
Tested on my local computer on iOS 11. 
We should get CircleCI to also test on old OS versions, but I'm doing that as a part of integration tests later.

fixed tests for iOS < 12.2

---

Purchases.podspec
PurchasesCoreSwift.podspec

I made cocoapods linking static after reports of a few build issues (), but I'm not sure those were strictly related - it might have been xcode 12's linking changes. 
In any case, customers who do require static linking will still be able to accomplish it by adding in the podfile:
```ruby
use_frameworks! :linkage => :static
```
This will have a `purchases-hybrid-common` counterpart and other counterparts for the hybrid sdks to ensure that they all work before shipping
Original PR to make cocoapods linking static and customer build issue reports:
https://github.com/RevenueCat/purchases-ios/pull/353
https://github.com/RevenueCat/purchases-flutter/issues/99
Tested on: 
- a sample app that integrates the library with cocoapods
- purchases-hybrid-common
- react native plugin
- unity
- cordova …

Make cocoapods linking dynamic again

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

- Move test dependencies back to carthage
https://github.com/RevenueCat/purchases-ios/pull/371
https://github.com/RevenueCat/purchases-ios/pull/373
- fixed tests for iOS < 12.2
https://github.com/RevenueCat/purchases-ios/pull/372
- Make cocoapods linking dynamic again
https://github.com/RevenueCat/purchases-ios/pull/374

version 3.7.5

---

PurchasesCoreSwift/LocalReceiptParsing/BasicTypes/InAppPurchase.swift
PurchasesCoreSwift/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift
PurchasesCoreSwift/LocalReceiptParsing/DataConverters/ArraySlice_UInt8+Extensions.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/DataConverters/UInt8+ExtensionsTests.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
PurchasesCoreSwiftTests/TestHelpers/ContainerFactory.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/PurchaserInfoTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Addresses https://github.com/RevenueCat/purchases-ios/issues/379
the `web_order_line_item_id` is actually a 64-bit integer, so parsing it would crash on 32-bit devices. 
This PR forces the type to `Int64`, which will of course be slower but work correctly. 
I believe there's another issue in 64-bit devices, because unrelated tests are not passing correctly for me on iPhone 5. I'll work on those separately.

fix overflow of web_order_line_item_id in 32-bit devices

---

Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m

This is kind of a fascinating one to me. 
Tests were failing on 32-bit devices, on something that didn't seem arch-related to me at least in an obvious way. 
The actual bug was really clear: we were doing
```objective-c
if (syncingAppUserID != currentAppUserID) {
```
where both arguments are strings, so that comparison meant to check for value but was actually checking equality. 
The interesting part, though, was that it works for 64 bit devices (we would have caught it straight away in the tests if it didn't). 
Turns out, an implementation detail within `NSString` actually makes it work in 64-bit, but not 32-bit. 
| 64-bit | 32-bit |
| :-: | :-: |
| <img width="437" alt="image" src="https://user-images.githubusercontent.com/3922667/98559039-e6509400-2284-11eb-9f5d-696c6e128538.png"> <img …

fix: string comparison when deleting synced attributes

---

.circleci/config.yml

The `docs-deploy` job was failing with error:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system: '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/dateutil/parser.pyc'
```
I believe this error is happening because of how python2 is set up in circleci. In any case, we should be moving to python 3, and ~I also think this might fix the job.~
Update: confirmed that using python3, the `awscli` tool is installed correctly.

fix docs-deploy job

---

.jazzy.yaml
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist
RELEASING.md

- Fixed a race condition that could cause a crash after deleting and reinstalling the app
https://github.com/RevenueCat/purchases-ios/pull/383
- Fixed possible overflow when performing local receipt parsing on 32-bit devices
https://github.com/RevenueCat/purchases-ios/pull/384
- Fixed string comparison when deleting synced subscriber attributes
https://github.com/RevenueCat/purchases-ios/pull/385
- Fixed docs-deploy job
https://github.com/RevenueCat/purchases-ios/pull/386
- Fixed a typo in a RCPurchases.h
https://github.com/RevenueCat/purchases-ios/pull/380

version 3.7.6

---

Purchases.xcodeproj/project.pbxproj
Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
Purchases/Purchasing/RCReceiptRefreshPolicy.h
PurchasesTests/Purchasing/PurchasesTests.swift

Added a silent version of `restoreTransactions`, called `restoreTransactionsProgrammatically`. It will be useful for developers performing migrations for other systems.
The new method is exactly the same as `restoreTransactions`, but without refreshing the receipt. 
The tests are also exactly like the ones for `restoreTransactions`, except for the one that asserts that the receipt isn't refreshed. 
I added a new enum `RCRefreshReceiptPolicy`, which specifies what the policy should be for receipt refresh:
- always refresh
- never refresh
- refresh only if the receipt is empty, which we do for most stuff

feature: restoreTransactionsProgrammatically

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
Purchases/Purchasing/RCStoreKitWrapper.h
Purchases/Purchasing/RCStoreKitWrapper.m

Adds this as part of the new Subscription offer codes  https://developer.apple.com/app-store/subscriptions/#providing-subscription-offers

Adds presentCodeRedemptionSheet

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
PurchasesTests/Purchasing/PurchasesTests.swift

from yesterday's meeting: 
- renamed `restoreTransactionsProgrammatically` -> `syncPurchases` for consistency with android
- passed `isRestore` as the value of `allowSharingAppStoreAccount`

Sync purchases improvements

---

Examples/SwiftExample/SwiftExample.xcodeproj/project.pbxproj

If you build the sample app on macOS right now, you get a build error because we have the watchOS configured to get embedded with the app, which is correct on iOS, but not macOS. 
This just adds a filter so that the watchOS app isn't embedded when building for mac
| :-: | :-: |
| <img width="636" alt="Screen Shot 2020-11-18 at 5 28 55 PM" src="https://user-images.githubusercontent.com/3922667/99584512-d0994800-29c3-11eb-9c2e-6be224861105.png"> | <img width="661" alt="Screen Shot 2020-11-18 at 5 29 02 PM" src="https://user-images.githubusercontent.com/3922667/99584497-cbd49400-29c3-11eb-9166-5846a0792e23.png"> |

updated the sample so that the watchOS app isn't embedded on macOS

---

Purchases.xcodeproj/project.pbxproj
Purchases/Misc/RCLogUtils.h
Purchases/Misc/RCLogUtils.m
Purchases/Misc/RCSystemInfo.m
Purchases/Networking/RCBackend.m
Purchases/Networking/RCHTTPClient.m
Purchases/Public/RCPurchases.m
Purchases/Public/RCPurchasesErrorUtils.m
Purchases/Purchasing/RCAttributionFetcher.m
Purchases/Purchasing/RCIdentityManager.m
Purchases/Purchasing/RCReceiptFetcher.m
Purchases/Purchasing/RCStoreKitRequestFetcher.m
Purchases/Purchasing/RCStoreKitWrapper.m
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m
PurchasesCoreSwift/LocalReceiptParsing/ReceiptParser.swift
PurchasesCoreSwift/Logging/Logger.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Since our logging logic lives in `Purchases` and `Purchases` depends on `PurchasesCoreSwift`, we couldn't use our logging logic in Swift. 
This moves our logging to Swift, while making a few updates: 
- adds `warn` level, which we didn't have before
- logs `error` level messages independently of the value of `showDebugLogs`, it feels more appropriate to me that errors are always shown
- cleans up the implementation
- adds Swift-compatible API
- adds sample Swift usage. 
A follow-up PR will update our Swift code to include more logging. 
We'll also update it further when we port over the changes currently being added to `purchases-android`.

Logging v2: part 1

---

.circleci/config.yml

I forgot to add this before merging. This limits running integration tests to tags and release branches

limit running integration tests to tags and release branches

---

Purchases/Public/RCPurchases.m
PurchasesCoreSwift/IntroEligibilityCalculator.swift
PurchasesCoreSwift/LocalReceiptParsing/ReceiptParser.swift
PurchasesCoreSwift/Logging/Logger.swift
PurchasesCoreSwift/Purchasing/ProductsManager.swift

Improved API for logging in Swift. 
Added a few log entries to Swift code.

Logging v2 part 2

---

Purchases/ProtectedExtensions/RCPurchases+Protected.h
Purchases/Public/RCPurchases.m
Purchases/Purchasing/RCStoreKitWrapper.h
Purchases/Purchasing/RCStoreKitWrapper.m
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/Purchasing/StoreKitWrapperTests.swift

adds support for `didRevokeEntitlementsForProductIdentifiers`, the new `SKPaymentQueue` method for handling cases where a family-shareable subscription is no longer shared. 
Note that this does not involve any user-facing changes, so it can be released in a patch release.

add support for didRevokeEntitlementsForProductIdentifiers

---

.jazzy.yaml
CHANGELOG.latest.md
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist
fastlane/Fastfile

- Added support for `SKPaymentQueue`'s `didRevokeEntitlementsForProductIdentifiers:`, so entitlements are automatically revoked from a family-shared purchase when a family member leaves or the subscription is canceled.
https://github.com/RevenueCat/purchases-ios/pull/413

version 3.9.1

---

Purchases/Networking/RCBackend.m
Purchases/Purchasing/RCIdentityManager.m
PurchasesTests/Networking/BackendTests.swift

We're getting a few calls to the backend for offerings on empty appUserID strings. 
This checks whether the appUserID is empty before posting to the backend, and early exists with an error if that's the case.

skip offerings backend call with error if appUserID is empty

---

Purchases/Purchasing/RCStoreKitWrapper.m
PurchasesTests/Purchasing/StoreKitWrapperTests.swift

`purchases-ios` currently is incompatible with Xcode 11, because we're using a couple of APIs that are available on Xcode 12+ only. 
This adds a couple of compiler-time checks to ensure that those APIs are only used when building using Xcode 12+

fix: Xcode 11 compatibility

---

Purchases/Purchasing/RCStoreKitRequestFetcher.m
PurchasesCoreSwift/Purchasing/ProductsManager.swift

Addresses 
https://github.com/RevenueCat/purchases-ios/issues/391
We’ve been getting warnings when debugging for a while, where iOS seems to issue a warning for SKReceiptRefreshRequest and SKProductsRequest not getting terminated correctly.
My guess is that this is an OS bug.
However, canceling the tasks manually after they are done seems to fix it. 
I've verified that without this change, the `SKReceiptRefreshRequest` stays in memory after the finish calls happen, and that it gets released with this change. 
Screenshots from before the change:
The [docs](https://developer.apple.com/documentation/storekit/skrequestdelegate/1385536-request?language=objc) don't say anything specifically about canceling the requests, but they do specify that after `didFinish` and `didFailWithError` are …

Fix termination warnings for finished SKRequests

---

.circleci/config.yml
fastlane/Fastfile
fastlane/README.md

Fixes the following issues with CI deploys: 
1. deployment checks was running on tags as well as branches. This would fail, because one of the steps is to check that there's no tag yet 🤦‍♂️ I forgot to remove that. 
1. the "prepare next version" step had a bug where it would preserve the patch version when determining the next version number. i.e.: the next one to `3.2.5` would have been `3.3.5-SNAPSHOT` instead of `3.3.0-SNAPSHOT`
1. the "create pull request" step was missing the `api_token` param, so it would wait for user input, which can't happen in CI
There was another issue where the user used for CI deploys didn't have write access on `purchases-ios`, I fixed that directly in CI

Fix CI deploy bugs

---

Purchases/Networking/RCHTTPClient.m
PurchasesTests/Networking/HTTPClientTests.swift

We're consistently getting a few POST requests on the backend which have empty body. 
Thing is, we never _create_ requests with `nil` bodies intentionally, so after looking at the code it seems like this might happen if the `body` dictionary couldn't be parsed into JSON. 
It doesn't make sense to still hit the backend if the body of the request couldn't be correctly formed, so this does an early exit before that happens. 
Also, when you hit the backend unnecessarily, a panda dies. Don't kill pandas.

prevents POST requests when the JSON body couldn't be correctly formed

---

Purchases/Public/RCPurchases.m

Addresses https://github.com/RevenueCat/purchases-ios/issues/401
Slight optimization. Updates `getOfferings` and `getPurchaserInfo` so that if the cached value is not stale, it's returned right away, without waiting to find out whether the app is running in the background. 
Shoutout to @wsun for pointing this out 🙌

fix: Offerings/purchaserInfo no longer synchronously returned from cache via main thread

---

Purchases/Public/RCPurchases.h
Purchases/Purchasing/RCStoreKitWrapper.h
Purchases/Purchasing/RCStoreKitWrapper.m

Fixes an issue with `simulatesAskToBuyInSandbox` where we made the API available, but didn't check the OS version of the underlying API in `SKPayment`. 
This was caught by deployment checks 🎉

simulatesAskToBuyInSandbox fixes

---

.circleci/config.yml
fastlane/Fastfile

The automation that prepares the next version snapshot has a couple of bugs: 
- it was missing the "-SNAPSHOT" suffix in the version number
- it was automatically committing changes that weren't meant to be committed, like the sample API key that was embedded into the SPM integration tests project. 
The fixes here are: 
- pass in the suffix correctly
- separate the `prepare_next_version` job into its own fastlane job, so that it runs from a clean checkout, and it can even run in parallel, making the overall deploy a little quicker

Fix deploy "prepare next version" job bugs

---

.circleci/config.yml

Facepalm. 
forgot to add "install gems" step to `prepare_next_version`. I tested it locally, but of course, I already had the gems.

install gems when preparing next version

---

.jazzy.yaml
CHANGELOG.latest.md
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

- Enables improved logging prefixes so they're easier to locate.
https://github.com/RevenueCat/purchases-ios/pull/441
- Fixed issue with Prepare next version CI job, which was missing the install gems step. 
https://github.com/RevenueCat/purchases-ios/pull/440

version 3.10.1

---

Examples/SwiftExample/Podfile.lock
Examples/SwiftExample/SwiftExample/SwiftPaywall.swift

Addresses #445 
Detailed context: https://github.com/RevenueCat/purchases-ios/issues/445#issuecomment-760385735
| :-: | :-: |
| <img width="1179" alt="Screen Shot 2021-01-14 at 3 46 48 PM" src="https://user-images.githubusercontent.com/3922667/104634818-e489bf00-567f-11eb-9dda-44052aaa29a1.png"> | <img width="1171" alt="Screen Shot 2021-01-14 at 3 46 06 PM" src="https://user-images.githubusercontent.com/3922667/104634825-e6ec1900-567f-11eb-8d9c-309b98128197.png"> |

fix example paywall card length on iPad and mac

---

Purchases/Purchasing/RCStoreKitRequestFetcher.m

we were always logging ":apple::bangbang: Invalid Product Identifiers" even when there were none, so that looked unnecessarily alarming. This prevents the warning if all product identifiers are valid.

fix: logging 'invalid product identifiers' even when the list is empty

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/PurchasesDelegateHandler.swift
Examples/MagicWeatherSwiftUI/Shared/Sources/Views/WeatherView.swift

Instead of checking for entitlement access in two places, this uses the UserViewModel property to check for an active subscription. Note: You must still fetch PurchaserInfo regularly (Purchases.shared.purchaserInfo) to update the SDK's cache and reflect the latest subscription status.
Additionally, this adds some comments to PurchasesDelegateHandler to clarify how PurchaserInfo is fetched/cached.

Uses UserViewModel property for entitlement check.

---

Purchases/Caching/RCDeviceCache.m

iOS equivalent of https://github.com/RevenueCat/purchases-android/pull/255. 
Should alleviate cases where the app gets woken up by remote push notifications every 24 hours exactly, which could make the cache miss depending on the exact timing of the push notification.

update the cache duration in background from 24 hours to 25

---

.jazzy.yaml
CHANGELOG.latest.md
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

- Added .xcframework output to Releases, alongside the usual fat frameworks.
https://github.com/RevenueCat/purchases-ios/pull/466
- Added PurchaseTester project, useful to test features while working on `purchases-ios`.
https://github.com/RevenueCat/purchases-ios/pull/464
- Renamed the old `SwiftExample` project to `LegacySwiftExample` to encourage developers to use the new MagicWeather apps
https://github.com/RevenueCat/purchases-ios/pull/461
- Updated the cache duration in background from 24 hours to 25 to prevent cache misses when the app is woken every 24 hours exactly by remote push notifications.
https://github.com/RevenueCat/purchases-ios/pull/463

version 3.10.4

---

.circleci/config.yml
IntegrationTests/SPMIntegration/SPMIntegration.xcodeproj/project.pbxproj
IntegrationTests/SPMIntegration/fastlane/Fastfile

In current builds, doing `carthage update purchases-ios --no-use-binaries` will produce an error. 
The issue is caused by the fact that Carthage will try to build every single scheme it finds within a repository, even if it's not needed for a dependency. 
[There's a promising PR](https://github.com/Carthage/Carthage/pull/3055) for adding support to selecting which Schemes Carthage builds, but I'm not sure how long that'll take to ship, or if it will end up moving the responsibility of deciding which schemes to build to the end user, which we should not do, as it would add a ton of friction and complexity to an already-difficult process. 
In the meantime, the issue is that the SPMIntegration scheme in our IntegrationTests won't build from Carthage. The reason is that this integration test …

fix: carthage build from source issues

---

.jazzy.yaml
CHANGELOG.latest.md
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist
fastlane/Fastfile

- Fixed a couple of issues with `.xcframework` output in releases
https://github.com/RevenueCat/purchases-ios/pull/470
https://github.com/RevenueCat/purchases-ios/pull/469
- Fix Carthage builds from source, so that end customers can start leveraging XCFramework support for Carthage >= 0.37
https://github.com/RevenueCat/purchases-ios/pull/471

Version 3.10.5

---

Cartfile.resolved
Purchases/Public/RCEntitlementInfo.m
PurchasesTests/Purchasing/EntitlementInfosTests.swift

Right now consumables and promotionals return willRenew as true. We should update so that:
1. Consumables always return willRenew as false
1. Promotionals always return willRenew as false
1. Subscriptions return willRenew as true if they don't have unsubscribe detected or billing issues.

Updates willRenew logic

---

PurchasesTests/Purchasing/EntitlementInfosTests.swift

This is a followup from https://github.com/RevenueCat/purchases-ios/pull/475/files#r585742659
This PR removes the matchers from the arguments of the methods and simplifies the whole suite of tests

Refactors EntitlementInfosTests

---

.jazzy.yaml
CHANGELOG.latest.md
CHANGELOG.md
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

- Fix automatic Apple Search Ads Attribution collection for iOS 14.5
https://github.com/RevenueCat/purchases-ios/pull/473
- Fixed `willRenew` values for consumables and promotionals
https://github.com/RevenueCat/purchases-ios/pull/475
- Improves tests for EntitlementInfos
https://github.com/RevenueCat/purchases-ios/pull/476

version 3.10.6

---

Purchases.xcodeproj/project.pbxproj
Purchases/Networking/RCBackend.m
PurchasesTests/Networking/BackendTests.swift

Updates the location of the old appUserID in `/identify` calls: 
| :-: | :-: |
| included in the URL | included in the POST body as `app_user_id` |

Identity v3: update appUserID param location

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/issuecomplete.yml
.github/stale.yml
.github/workflows/lock.yml
CONTRIBUTING.md

This PR configures the follow Bots / Github Action:
- https://github.com/probot/stale
- https://github.com/stevenzeck/issue-check
- https://github.com/dessant/lock-threads
- Mark issues as stale after 30 days of no activity
- Close stale issues after 7 days of no activity
- Adds label `status: waiting-for-reply` for issues marked as stale
- Only check issues with `bug` label
- Does not check issues with `enhancement`, `next-release`, or `investigating` labels
- Does not check if issue has an assignee 
- Adds label `status: needs-additional-info` for issues that did not follow Issue template
- Runs at 00:00 UTC every day
- Excludes issues created before March 1st, 2021 (for the purpose of not creating noise for old issues)
- Will lock a closed issue after 7 days of no activity. 
This PR …

Initial configuration of bots

---

Purchases.xcodeproj/project.pbxproj
Purchases/Public/RCEntitlementInfo.h
Purchases/Public/RCEntitlementInfo.m
Purchases/Public/RCPurchaseOwnershipType.h
PurchasesTests/PurchasesTests-Bridging-Header.h
PurchasesTests/Purchasing/EntitlementInfosTests.swift

This is a new field, that allows customers to know whether a given subscription was purchased by the user or was shared to them by a member of their family. 
This in turn allows for apps to provide a custom onboarding for users who've had a subscription shared with them, but might not be aware of the benefits of the subscription, or that they even have one.

expose `ownershipType` in purchaserInfo

---

Purchases/Attribution/RCAttributionFetcher.m
Purchases/Attribution/RCAttributionTypeFactory.h
Purchases/Attribution/RCAttributionTypeFactory.m
PurchasesCoreSwift/Logging/Strings/AttributionStrings.swift
PurchasesTests/Attribution/AttributionFetcherTests.swift
PurchasesTests/Attribution/AttributionTypeFactoryTests.swift
PurchasesTests/Mocks/MockAttributionTypeFactory.swift

Obfuscates our soft-linking of the `AppAtrackingTransparency` framework, since Apple seems to be doing string searches for `ATTrackingManager` and rejecting apps even if they don't actually use `AppAtrackingTransparency`. 
Changes summary: 
Replaced the strings for ATT framework with ROT13 versions. 
Since we can't reference the property directly and it's a class property, calling it through KVC isn't possible, because the class itself isn't KVC-compatible (although all _instances of it would be). 
Since KVC won't work, I first tried with `performSelector`... but because the selector is created from a string, this actually [creates possible leaks](https://stackoverflow.com/a/20058585/5074358), because ARC isn't sure how to manage the return value. Note that the solution described in that …

Hotfix: ATTFramework usage rejections

---

PurchasesCoreSwift/Logging/Strings/IdentityStrings.swift

@danthorpe opened an issue https://github.com/RevenueCat/purchases-ios/issues/497
This PR updates the create alias log to make more clear what's happening.

Update create alias log

---

Cartfile.resolved
Purchases/FoundationExtensions/NSData+RCExtensions.h
Purchases/FoundationExtensions/NSData+RCExtensions.m
Purchases/FoundationExtensions/NSDate+RCExtensions.h
Purchases/FoundationExtensions/NSDate+RCExtensions.m
Purchases/FoundationExtensions/NSDictionary+RCExtensions.h
Purchases/FoundationExtensions/NSDictionary+RCExtensions.m
Purchases/FoundationExtensions/NSError+RCExtensions.h
Purchases/FoundationExtensions/NSError+RCExtensions.m
Purchases/Networking/RCBackend.m
Purchases/SubscriberAttributes/RCPurchases+SubscriberAttributes.m
Purchases/SubscriberAttributes/RCSubscriberAttribute.m
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m
PurchasesTests/FoundationExtensions/NSData+RCExtensionsTests.swift
PurchasesTests/FoundationExtensions/NSDate+RCExtensionsTests.swift
PurchasesTests/FoundationExtensions/NSError+RCExtensionsTests.swift
PurchasesTests/Misc/NSDictionaryExtensionsTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributeTests.swift
PurchasesTests/SubscriberAttributes/SusbcriberAttributesManagerTests.swift

Adds an `rc_` prefix to all foundation extensions, to prevent naming collisions. 
Also does some extra renaming to `millisecondsSince1970`, since it would conflict with another extension in `purchases-hybrid-common`
It should fix the following warning in hybrid sdks:

Fix: add prefix to foundation extensions

---

.jazzy.yaml
Purchases.podspec
Purchases/Info.plist
Purchases/Misc/RCSystemInfo.m
PurchasesCoreSwift.podspec
PurchasesCoreSwift/Info.plist
PurchasesCoreSwiftTests/Info.plist
PurchasesTests/Info.plist

Bumps version number to 3.12.0-SNAPSHOT. 
Our fancy fastlane automation failed so I'm doing this manually. 
```
[18:29:59]: GitHub responded with 422: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"missing_field","field":"head"}],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-pull-request"}
```

Preparing for next version: 3.12.0

---

fastlane/Fastfile

From #503 , it looks like the `create_pull_request` method now requires `head` to be passed in as a field. Fastlane hasn't updated [their docs yet](https://docs.fastlane.tools/actions/create_pull_request/), it's still marked as optional, so I'll open up a bug report. 
In the meantime, this just adds the field.

added missing field in create_pull_request call

---

Purchases/Public/RCPurchases.h
Purchases/Public/RCPurchases.m
PurchasesTests/Purchasing/PurchasesTests.swift

As mentioned in https://github.com/RevenueCat/purchases-ios/issues/490, the value of `sharedPurchases` can be `nil`, but it's marked as `non-nullable`. 
This can lead to some awkward behavior, particularly in Swift, where the compiler will assume that the value is not `nil` and will not let you check against it. 
To solve this, this PR does 2 things: 
- adds an `assert` when calling `sharedPurchases`, since calls to it will no-op, which is unexpected behavior the vast majority of the time. 
- adds a new property, `isConfigured`, that you can use to know whether it's safe to call `sharedPurchases`. I added this so that if someone is indiscriminately calling a method and relying on no-ops, they can use the new property to keep their code compatible with this behavior. However, this should …

Fix: sharedPurchases nullability

---

Purchases/Misc/RCLogUtils.h
Purchases/Misc/RCLogUtils.m
Purchases/Public/Purchases.h
Purchases/Public/RCLogger.h
Purchases/Public/RCLogger.m
Purchases/Public/RCPurchases.h
PurchasesCoreSwift/Logging/Logger.swift

This changes adds the ability to set a new handler on the `RCLogger` type. By default, the handler is the current implementation of `NSLog` that emits the framework description.
The log handler provides the parameters of the log level and the message, and then anyone providing a custom handler can interpret those parameters however they wish and/or redirect them to their own logging system.

Add hook to customize the way logs are emitted

---

Purchases.xcodeproj/project.pbxproj

These happened during #438, probably in one if the many, many rebases. 
They haven't been an issue, though, since the bad ones are a duplicate anyway - the good references were already in the project. 
| :-: | :-: |
| ﻿<img width="329" alt="Screen Shot 2021-06-09 at 4 32 42 PM" src="https://user-images.githubusercontent.com/3922667/121417520-608ee700-c940-11eb-9586-a7db5ee3c63c.png"> | <img width="340" alt="Screen Shot 2021-06-09 at 4 32 54 PM" src="https://user-images.githubusercontent.com/3922667/121417511-5cfb6000-c940-11eb-81ce-94d9fd2c68cb.png"> |

fix file references

---

Package.swift

Addresses https://github.com/RevenueCat/purchases-ios/issues/517
Fixes an outdated path reference in Package.swift

fix outdated path reference in Package.swift

---

Package.swift

Addresses #492 
Removed the "TEST" env variable, as well as the test dependencies, when using Swift Package Manager. 
Discussion: 
- I don't think there's any value in defining the dependencies there, given that they're only useful for running tests on our SDK. If you import the package from SPM I don't think you can even run the tests anyway. 
- Xcode will still pull all of the dev dependencies if they're defined, so you'll see them in your project even if you're not looking to do tests
- The only case I can think of where they'd be useful would be if we were using the dependencies ourselves - i.e.: if instead of using Carthage, we were using SPM for our unit tests dependencies. Which we might wanna do, but that's a story for another day. 
- This is functionally the same as we had …

removed test env variable

---

fastlane/Fastfile

- When running fastlane-based tests, we need to ensure that the environment variables are setup, added `ensure_testing_enviroment` function
- `sed` gives a message that requires you to track down the source of pain, so added some messaging around that to better find the source of your problem.
- Removed DEVELOPMENT_TEAM from projects, set to empty

Better error message when attempting to replace a nonexistent string

---

PurchasesCoreSwift/Misc/DateExtensions.swift
PurchasesCoreSwift/Purchasing/ProductsManager.swift
PurchasesCoreSwift/Purchasing/TransactionsFactory.swift
PurchasesCoreSwift/Transaction.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
PurchasesCoreSwiftTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
PurchasesCoreSwiftTests/Purchasing/TransactionsFactoryTests.swift

Addresses #394 
Replaces the last few remaining `fatalError`s with better error handling.

remove remaining `fatalError`s

---

PurchasesTests/Networking/HTTPClientTests.swift

Tests were failing in Xcode 13 beta. 
The cause is that in the beta, getting `NSBundle.mainBundle.infoDictionary[@"CFBundleShortVersionString"];` has a different behavior than usual. 
In other versions of Xcode, if you obtain `BundleShortVersionString` through that, by calling it inside a framework target, but within a unit tests target, you'd get `""`. 
In Xcode 13, it instead returns `13.0`. This looks like an Xcode bug. Curiously, if you get the value *within* the unit tests target, it returns `""` instead of `13.0`, so the trick to the bug is to call it from the unit tests target, but within a framework target. 
Hope that makes sense and doesn't sound like the ramblings of a mad person.

fix tests in Xcode 13 beta

---

Purchases/Caching/RCDeviceCache.m

When a developer deletes the userDefaults entry for appUserID that revenueCat uses, the SDK crashes with an error, and a link pointing to an article that explains the issue. 
The article was previously private, @beylmk caught that (👏 ) and we fixed it to make it public, but we also have a better article with more info to point to. 
I updated the link to the more complete article, and also used a rebrandly link so that we can update without issuing an SDK update in the future. 
| :-: | :-: |
| https://support.revenuecat.com/hc/en-us/articles/360047927393 | https://rev.cat/userdefaults-crash |

updated link to rev.cat link, points to more complete article

---

.circleci/config.yml
.swiftlint.yml
APITester/main.m
IntegrationTests/PurchaseTester/Podfile
PublicSDKAPITester/RevenueCatAPI.h
PublicSDKAPITester/RevenueCatAPI.m
PublicSDKAPITester/main.m
Purchases.xcodeproj/project.pbxproj
Purchases.xcodeproj/xcshareddata/xcschemes/APITester.xcscheme

- Added an `APITester` target that relies on the project's public API
- Added build phase run step that builds the `APITester` after the `Purchases` framework
- If the `APITester` target fails, that means we changed the public API
resolves #584

Add APITester target

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/migration_task.md

Looks like GitHub wants this named differently 🤷‍♂️

Update issue templates

---

Purchases.xcodeproj/project.pbxproj
Purchases/ProtectedExtensions/RCPurchases+Protected.h
Purchases/Public/RCPurchases.m
Purchases/Purchasing/RCStoreKitRequestFetcher.h
Purchases/Purchasing/RCStoreKitRequestFetcher.m
PurchasesCoreSwift/Logging/Strings/OfferingStrings.swift
PurchasesCoreSwift/Purchasing/ProductsManager.swift
PurchasesCoreSwift/Purchasing/ProductsRequestFactory.swift
PurchasesCoreSwiftTests/Mocks/MockProductsManager.swift
PurchasesTests/Mocks/MockRequestFetcher.swift
PurchasesTests/Mocks/MockSKProduct.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/Purchasing/StoreKitRequestFetcherTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

This migration is split into 2 parts:
- Part 1: migrate the fetching of products into the **already existing code** in `ProductsManager.swift`, and update its usage
- Part 2: migrate fetching of receipts following the standard procedure described in the [Swift Migration Project docs](https://github.com/RevenueCat/purchases-ios/blob/swift_migration/CONTRIBUTING.md#-objc-to-swift-migration)
The reason I separated them is that they're pretty different in execution, both likely large, and can be done atomically. 
As for the `ProductsManager.swift` bit: 
This was done as a part of the project to parse local receipt files, and it's been used and tested for a while. So it's not exactly new code, it was actually duplicated logic in Swift and Obj-C. The reason that we had this duplicated is that …

migrate StoreKitRequestFetcher: part 1

---

Purchases/Public/RCPurchases.m
PurchasesCoreSwift/Purchasing/StoreKitRequestFetcher.swift
PurchasesTests/Mocks/MockRequestFetcher.swift
PurchasesTests/Purchasing/StoreKitRequestFetcherTests.swift

`StoreKitRequestFetcherTests` were failing, because the new version in swift uses GCD for thread management, which might take a little longer to queue up than the old `@syncrhonized` blocks. 
This wasn't a problem locally, but on slow CI machines tests became flaky. 
This PR replaces the queue in `StoreKitRequestFetcher` by using `OperationDispatcher`. 
This is functionally the same, since `OperationDispatcher` will just forward to its own worker queue. However, we already have some mocks in place to have the tests execute the queued-up work straight away, so this should eliminate the flakiness. 
It's also best practice to [avoid creating too many private queues](https://developer.apple.com/documentation/dispatch/dispatchqueue), so this also helps by unifying to a single queue.

fix: flaky test in `StoreKitRequestFetcherTests`

---

Purchases.xcodeproj/project.pbxproj
PurchasesCoreSwift/Purchasing/RCReceiptFetcher.swift
PurchasesTests/Mocks/MockReceiptFetcher.swift

The PR where `RCReceiptFetcher` [was migrated](https://github.com/RevenueCat/purchases-ios/pull/628) introduced a swift file in the `Purchases` folder, instead of `PurchasesCoreSwift`. 
However, both our Podspecs and our SPM setup assume that all of the Swift files will be located in `PurchasesCoreSwift`, so the SDK could no longer be integrated, with a compilation failure. 
This fixes that compilation error by moving the file to the correct folder, and also updates the naming a little bit.

Fix: pod structure

---

Examples/MagicWeather/MagicWeather/Sources/Controllers/UserViewController.swift
Purchases.podspec
Purchases/Public/RCPurchases.h

Based on #438 
This adds only the public-facing changes, so that we can integrate the main identity v3 PR without worrying about making changes available publicly through the SDK until we're ready. 
- Introduces `logIn`, a new way of identifying users, which also returns whether a new user has been registered in the system. 
`logIn` uses a new backend endpoint. 
- Introduces `logOut`, a replacement for `reset`. 
- removes `createAlias`
- deprecates `identify` in favor of `logIn`
- deprecates `reset` in favor of `logOut`
- deprecates `allowSharingAppStoreAccount` in favor of dashboard-side configuration

identity v3: public-facing changes

---

Purchases/Networking/RCHTTPClient.m

remove unused typedef to fix build warning. I believe this was introduced in #509, and was unused

remove unused typedef to fix build warning

---

.circleci/config.yml

found even more jobs that were missing the `swiftlint` dependency, so I added it to all of them. 
This was the reason for carthage integration tests failing on main, and I'm still looking into it, but it's probably also the reason that the deploy script failed.

added swiftlint installation to all places that were missing it

---

Purchases/Public/RCPurchases.m
PurchasesTests/Purchasing/PurchasesTests.swift

Fix: Calling `setDebugLogsEnabled(false)` enables debug logs when it should not

---

Purchases.xcodeproj/project.pbxproj

Resolves #629
>This PR already included the suggested changes by @taquitos in PR #653
This PR aims to create a new build phase that runs a script to validate that some macros, like `TARGET_OS_ (TARGET_OS_IPHONE, TARGET_OS_SIMULATOR)`, are not included in any Swift file.
The script checks all the swift files in the project folder to find the specified tag.
If the script found some files, the project will not compile, and the developer can see this error:

Create a build step to check TARGET_OS macro

---

Purchases/Networking/RCBackend.m
PurchasesCoreSwift/Networking/HTTPClient.swift
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift

Solves #694 
This PR aims to create separate method signatures in the `HTTPClient` for both GET and POST requests to make sure that gets aren't called with a body and posts are called with a body.
BTW, although there is a task for doing all the post-migration TODOs, I think the `HTTPRequest` class is ready to be internal and remove the **ObjC** compatibility :)

Split HTTPClient method

---

PurchasesCoreSwift/IntroEligibilityCalculator.swift
PurchasesCoreSwiftTests/IntroEligibilityCalculatorTests.swift
PurchasesCoreSwiftTests/Mocks/MockSKDiscount.swift
PurchasesCoreSwiftTests/Mocks/MockSKProduct.swift

Our intro eligibility calculation is considering the status for all products that don't have any intro pricing set up as `eligible`, when they should be `ineligible` if no intro pricing exists. 
This only affects calls to `checkTrialOrIntroductoryPriceEligibility:` that include product identifiers for products that don't have intro pricing set up. 
Fixed by adding an extra check.

fix: introEligibility marked as `eligible` for products that don't have intro pricing

---

Purchases/Public/RCPurchases.m
PurchasesCoreSwift/Misc/SystemInfo.swift

Resolves #687 
Tiny PR that extracts the platform checks to find the application lifecycle notification names. There are a lot of approaches but considering that we are only using two notifications and we still have ObjC code, I think we could use the `SystemInfo` class to do the platform checks.
Maybe we could use the Apple approach in the future, creating a [`Notification.Name` extension with constants](https://developer.apple.com/documentation/foundation/nsnotification/name/1616519-nsextensionhostwillresignactive).

Extract platform checks for notification names

---

.github/stale.yml
.github/workflows/lock.yml

- removed `swift-migration` and `test-backfill` labels. They were wrong 🤦 but also, I think it's probably not a bad thing to lock these issues after they've been closed for over 7 days. 
- updated `swift-migration` and `test-backfill` labels to the correct names, `swift migration` and `test backfill` (space instead of dash).

issue bot fixes

---

PurchasesCoreSwift/Misc/SystemInfo.swift

follow-up to https://github.com/RevenueCat/purchases-ios/pull/701. 
Our tests were failing because the new methods were missing a `public`, so they weren't actually available to obj-c (but tests would still pass on `debug` schemes)

fix method not available to obj-c

---

Purchases/Public/RCPurchases.m
PurchasesCoreSwift/Purchasing/ProductsManager.swift
PurchasesCoreSwiftTests/Mocks/MockProductsManager.swift
PurchasesCoreSwiftTests/Purchasing/ProductsManagerTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

fixes #682, as described in #680. 
We had a duplicate `productsByIdentifier` cache between `RCPurchases` and `ProductsManager`. This unifies them and simplifies logic in `RCPurchases`.

Remove redundant products by identifier cache

---

Examples/MagicWeather/README.md
Examples/MagicWeatherSwiftUI/README.md
README.md

- Updated the MagicWeather sample app READMEs with setup instructions.
- Updated the root README to link to the sample apps.
[Clubhouse story for context](https://app.clubhouse.io/revenuecat/story/7089/update-ios-sample-app-readme-with-setup-run-instructions)

updated sample app READMEs with setup instructions

---

SwiftStyleGuide.swift

added sample code for capturing self weakly and strongly, and link to guide for when to do one or the other. 
Inspired by [this comment](https://github.com/RevenueCat/purchases-ios/pull/705#discussion_r683580830)

added style guide for strong and weak self references

---

Purchases/Attribution/RCAttributionPoster.m
Purchases/Identity/RCPurchaserInfoManager.m
Purchases/Public/RCPurchases.m
Purchases/SubscriberAttributes/RCSubscriberAttributesManager.m
PurchasesCoreSwift/Purchasing/StoreKitWrapper.swift

Fixes #689 
Moves a few logs away from `RCPurchases`, in the hopes of making that class slightly easier to migrate.

Move logs out of rcpurchases

---

Purchases.xcodeproj/project.pbxproj
Purchases/Public/RCPurchases.m
PurchasesCoreSwift/Purchasing/ReceiptFetcher.swift
PurchasesCoreSwiftTests/Mocks/MockBundle.swift
PurchasesCoreSwiftTests/Purchasing/ReceiptFetcherTests.swift
PurchasesTests/Mocks/MockReceiptFetcher.swift
PurchasesTests/Mocks/MockSystemInfo.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

Moved some logic away from `RCPurchases.m` and into `ReceiptFetcher`, as described in #680. 
Fixes #692

Extract receipt fetcher logic

---

PurchasesCoreSwift/Purchasing/OfferingsManager.swift

tests are currently failing in `swift_migration` because of a bad refactor, this fixes them.

fix tests from a bad refactor

---

Purchases/Public/RCPurchases.m

replaced a couple of macros: 
- `CALL_IF_SET_ON_MAIN_THREAD`
- `CALL_IF_SET_ON_SAME_THREAD`
with direct calls to operation dispatcher. 
Also cleaned up the nullability specifiers for a few private methods. 
I figured this is a good thing to do before trying to migrate the full class, since it'll be easier to translate. 
Fixes #681

Replace macro with direct calls to operation dispatcher

---

.circleci/config.yml
fastlane/Fastfile
fastlane/Scanfile

---
Follow up to #728
cc: @aboedo @taquitos 
Add support to test both iOS and tvOS with _fastlane_
`scan` cannot run with devices of different types (ie: iPhone and Apple TV). These are both iOS-ish but are different platforms. `scan` forwards these devices to the `xcodebuild` CLI tool and that is what gets confused. This was essentially like telling Xcode to run tests on iPhone and Apple TV within the same build which you cannot do (to my knowledge 😅)
This changes does two things:
1) Removes the devices from the `Scanfile` since we need to change the devices per platform
2) Adds two `scan` calls in the `test` lane to test both iOS and tVOS separately 
‼️ `fastlane …

Update Fastfile `test` lane to run scan for iOS and tvOS

---

PublicSDKAPITester/RCPurchasesAPI.m
PurchasesCoreSwift/Attribution/AttributionPoster.swift
PurchasesCoreSwift/Networking/Backend.swift
PurchasesCoreSwift/Public/EntitlementInfo.swift
PurchasesCoreSwift/Public/Offering.swift
PurchasesCoreSwift/Public/PurchaserInfo.swift
PurchasesCoreSwift/Purchasing/ProductsRequestFactory.swift
PurchasesCoreSwift/Purchasing/PurchasesOrchestrator.swift
PurchasesCoreSwift/Purchasing/StoreKitWrapper.swift
PurchasesCoreSwiftTests/Purchasing/EntitlementInfosTests.swift
PurchasesCoreSwiftTests/Purchasing/OfferingsManagerTests.swift
PurchasesCoreSwiftTests/Purchasing/PurchaserInfoTests.swift
RCPurchaserInfoAPI.m

Move TODOs into GitHub

---

IntegrationTests/PurchaseTester/Podfile.lock
IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift

Updated the `PurchaseTester` app to the latest syntax. 
Also, it looks like we now require importing StoreKit manually, perhaps that's something that we can improve. 
Reminder that this app is for our internal testing only, so we should just make it work as we fix issues along the way.

Update purchase tester

---

.circleci/config.yml
Purchases.xcodeproj/project.pbxproj
PurchasesTests/Mocks/MockSKDiscount.swift
StoreKitTests/StoreKitTests.swift

- Updates the StoreKit tests target to the latest syntax
- fixes a few issues with the xcode project setup after the swift migration changes
- enables the scheme for all branches, since we're making updates to critical components that StoreKit Tests can cover more effectively than other test types.

updated storeKitTests and enabled them for all builds

---

Purchases.xcodeproj/Purchases.xctestplan
Purchases.xcodeproj/project.pbxproj
Purchases.xcodeproj/xcshareddata/xcschemes/Purchases.xcscheme

Xcode [Test Plans](https://developer.apple.com/videos/play/wwdc2019/413/) make it easy to set up different configuration for tests, like repeating all tests several times, setting up different timeouts, etc. 
This PR migrates our test scheme to Test Plans. This will hopefully make it easier to reproduce the issues in `HTTPClient` for testing, since we can set it up to run several times until it fails. 
I didn't go crazy with configuration yet, the idea is to have this as a starting point.

Migrate to Test Plans

---

Purchases/Networking/Backend.swift
Purchases/Networking/ETagManager.swift
Purchases/Networking/HTTPClient.swift
PurchasesTests/Mocks/MockBackend.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift

There were a few places where we were queue-hopping a bit. The original implementation locked in just a few places. With the Swift migration we introduced a couple changes, like always dispatching `completion` to the main queue and wrapping the `handler` and `perform` methods in a dispatch work item. The data task we create dispatches the completion to the Session's own internal queue (we don't have a delegate), so we end up potentially using 4 queues here, original caller, serial http, internal session, then main. I reduced the queue usage to just two, the original caller and the internal queue on Session. I also used NSRecursiveLock for access control (to replace the original `@synchronized`).
resolves #750

Ensure order of operations for HTTPClient

---

PurchasesTests/Caching/DeviceCacheTests.swift
PurchasesTests/Identity/IdentityManagerTests.swift
PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
PurchasesTests/Purchasing/ProductInfoTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Tests are crashing on older OS versions (for example, iPhone running iOS 11.4)
One reason this is happening is that when testing for something to throw, you need to use the following syntax:
```swift
expect { mockNotificationCenter.fireNotifications() } .toNot(throwAssertion())
```
instead of 
```swift
expect(mockNotificationCenter.fireNotifications()).toNot(throwAssertion())
```
this is because the inside of expect() gets evaluated before the expect method itself, so if something throws, it crashes the test suite. 
There are a couple of other updates here, like cleaning up the architecture checks for `throwAssertion` to match those in the actual implementation in Nimble, cleaning up availability checks in a few places, and updating force unwraps to use `XCTUnwrap` (but there are still a …

Fix: tests on older OS versions

---

Purchases/Logging/Logger.swift
Purchases/Logging/Strings/AttributionStrings.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/SubscriberAttributes/SubscriberAttributesManager.swift

We're currently storing all logging strings as `static let`. 
This has the unfortunate side-effect of eagerly loading them all into memory. 
In addition, formatting them isn't very type-safe, and is difficult to do, because when using the strings, you don't know what each parameter does, in which order. 
This PR improves upon this by transforming them into enum cases with labels. 
This means we can move from this syntax: 
```swift
Logger.info(String(format: Strings.whatever.purchasing_product, productId))
```
into this one: 
```swift
Logger.info(Strings.whatever.purchasing_product(productIdentifier: productId))
```
which gets a lot better when there are multiple parameters.

Improve strings formatting part 1: `AttributionStrings`

---

Purchases/Purchasing/IntroEligibilityCalculator.swift
PurchasesTests/Mocks/MockSKDiscount.swift
PurchasesTests/Mocks/MockSKProduct.swift
PurchasesTests/Purchasing/IntroEligibilityCalculatorTests.swift

The changes from #679 were lost during the swift migration so this PR brings the changes back

Adds missing changes from #679 (bugfix on check intro eligibility)

---

Purchases/Networking/HTTPClient.swift

This PR doesn't change how things operate. Currently, all call sites still pass in `serially`. This change is an attempt to add guardrails in case we add a new call and forget to set `serially`. It is more likely we want the requests to perform in a serial manner than not.

Default HTTPClient to serial requests

---

Purchases/Networking/RCBackend.m
PurchasesTests/Networking/BackendTests.swift

Same as https://github.com/RevenueCat/purchases-ios/pull/829 for versions 3.x.x of the SDK

make getOfferings perform serially in RCv3

---

Purchases/Networking/Backend.swift
PurchasesTests/Networking/BackendTests.swift

getOfferings can sometimes trigger creation of a user. In that case, there can be a race condition if another request is in process and it happens to also create a user.

Make getOfferings execute serially

---

Purchases/Logging/Strings/RestoreStrings.swift

Follow-up to https://github.com/RevenueCat/purchases-ios/pull/816, updates the format in `RestoreStrings`.

Improve strings formatting: `RestoreStrings`

---

Purchases/Purchasing/ProductsManager.swift

There was a bug in `OfferingsManager` that made it not return for SK2. This PR fixes it

fixed offeringsManagerTests

---

Purchases/Networking/Backend.swift
PurchasesTests/Networking/BackendTests.swift

This is the ios counterpart for https://github.com/RevenueCat/purchases-android/pull/358
This PR prevents the same API calls with the same parameters from being called at the same time.
I made a follow-up ticket (one for android and one for ios) for "genericizing" these kinds of caching functions, since there is as lot of duplicate code, and potentially pulling them out of this class.

Cache createAlias and identify calls

---

Purchases/Purchasing/OfferingsManager.swift
PurchasesTests/Purchasing/OfferingsManagerTests.swift

Thanks to our beta community, we've found a bug around our logging of missing product identifiers. This log is intended to inform developers of product IDs created in RevenueCat that are not found in the Apple Store.
We had a regression in our logic for determining which IDs were missing -- using the intersection of RC/ASC products rather than the difference. 
Also includes:
* optimization to re-use extracted product IDs
* minor bug fix - checking the wrong empty list for an early return

Use subtraction instead of intersection to find missing product IDs

---

SwiftStyleGuide.swift

Updated the naming convention for optionals in `SwiftStyleGuide`, so that `public` properties don't use the `maybe` prefix. 
Open for discussion, though!! Would love to know what others think

clean up naming convention for optionals

---

Purchases/Networking/RCBackend.h
Purchases/Networking/RCBackend.m
PurchasesTests/Networking/BackendTests.swift

This is the hotfix equivalent for https://github.com/RevenueCat/purchases-ios/pull/867
I just made the release/3.12.5 branch off of the 3.12.4 tag...but still have to see how we will do a hotfix release?

Hotfix to cache createAlias and identify

---

Purchases/SubscriberAttributes/ReservedSubscriberAttributes.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

The name of the reserved attribute for AirshipChannelID was wrong, so this updates it. 
| :-: | :-: |
| `$airshipChannelID` | `$airshipChannelId` |

fixed name of reserved attribute `$airshipChannelId`

---

Purchases/Logging/Strings/OfferingStrings.swift
Purchases/Networking/Backend.swift
Purchases/Public/Error Handling/ErrorUtils.swift
Purchases/Purchasing/OfferingsFactory.swift
Purchases/Purchasing/OfferingsManager.swift
PurchasesTests/Mocks/MockOfferingsFactory.swift
PurchasesTests/Purchasing/OfferingsManagerTests.swift
PurchasesTests/Purchasing/OfferingsTests.swift

Fixed a couple of cases where we're not calling completion block. 
First up is this case: 
https://community.revenuecat.com/sdks-51/ios-bug-rcpurchases-offeringswithcompletionblock-offerings-and-error-are-both-nil-442?postid=1328#post1328
This is very easy to reproduce, and happens whenever you have a bad configuration: 
- no offerings in the backend
- offerings exist in the backend, but no corresponding skproducts exist. 
In both of those cases, we're returning `error = nil` && `offerings.current = nil`, which seems very confusing for developers. 
So I'm updating so that in those cases we return `configurationError`.

Fix: offerings completion not called in some cases

---

CHANGELOG.md
scripts/carthage.sh

Updates the carthage deploy script for Xcode 13 compatibility:
https://github.com/Carthage/Carthage/issues/3201
This doesn't need to be back-ported to 3.x.x, since we're as of right now using Xcode 12 for that one. 
Updates the changelog to include the latest 3.x.x releases.

fixed issues with Xcode 13 in carthage script

---

Purchases/Logging/Logger.swift

Hello RC team!
According to common programming practices it is insecure to pass dynamically generated strings as a format into printf-like methods. We use `purchases-ios` framework a lot and have a visible amount of crashes when something containing `%@` literal is being logged by the following method. That would be nice to have such a fix 😄 
Thanks!

Pass a message to NSLog as an argument instead of format

---

Purchases/Public/PurchaserInfo.swift

When attempting to retrieve transaction dates via `expirationDate(forProductIdentifier:) -> Date?` or `purchaseDate(forProductIdentifier:) -> Date?`, PurchaserInfo would always report nil values.
This appears to be due to 1) the `parseDatesIn(transactionsByProductId:dateLabel:) -> [String: Date?]` method attempting to cast transactions to a `[String: String]` dictionary. This always fails as a transaction can contain an `NSNull` amongst other non-String values. 2) the `purchaseDatesByProductId: [String: Date?]` property containing expiration dates rather than purchase dates due to an accidental call to `parseExpirationDates(transactionsByProductId:)` rather than `parsePurchaseDates(transactionsByProductId:)`.

Fix PurchaserInfo date parsing

---

PurchasesTests/Purchasing/PurchaserInfoTests.swift

Follow-up to https://github.com/RevenueCat/purchases-ios/pull/888, adds a few test cases to ensure that we don't accidentally break the code again. 
I tested that these test cases would fail before the bug fixes, and pass afterwards.

Add test cases for PurchaserInfo parsing bug fixes

---

Purchases/Error Handling/DescribableError.swift
Purchases/Error Handling/ErrorDetails.swift
Purchases/Error Handling/ErrorUtils.swift
Purchases/Error Handling/UnexpectedBackendResponseSubErrorCode.swift
Purchases/FoundationExtensions/Dictionary+Extensions.swift
Purchases/FoundationExtensions/Error+Extensions.swift
Purchases/FoundationExtensions/JSONDecoder+Extensions.swift
Purchases/Identity/CustomerInfoManager.swift
Purchases/Networking/Backend.swift
Purchases/Public/CustomerInfo.swift
Purchases/Public/Errors/ErrorCode.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
PurchasesTests/Identity/CustomerInfoManagerTests.swift
PurchasesTests/Identity/IdentityManagerTests.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/CustomerInfoTests.swift
PurchasesTests/Purchasing/EntitlementInfosTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
RevenueCat.xcodeproj/project.pbxproj

Distinguish between missing json/response and malformed data.
Add extra context to those error states including
- statusCode
- responseData
- which method called `handle`

Add more specific backend error subcodes

---

fastlane/Fastfile

I ran into an issue today where one of the integration tests projects was using an older version of fastlane. 
It got me thinking that we should just auto-update, since we're already updating fairly often, just manually.
This PR adds the step `update_fastlane` to all lanes. It won't auto-update into a new major version, though.

auto-update fastlane

---

Purchases/Attribution/ASIdManagerProxy.swift
Purchases/Attribution/AfficheClientProxy.swift
Purchases/Attribution/AttributionFetcher.swift
Purchases/Attribution/AttributionPoster.swift
Purchases/Attribution/AttributionTypeFactory.swift
Purchases/Logging/Strings/AttributionStrings.swift
PurchasesTests/Attribution/AttributionTypeFactoryTests.swift
PurchasesTests/Mocks/MockAttributionFetcher.swift
PurchasesTests/Mocks/MockAttributionTypeFactory.swift
RevenueCat.xcodeproj/project.pbxproj

Rename `ad` to `affiche`
Apple might have gotten more paranoid about Ad tracking classes being available in children's apps.

Remove more "ADClient" words

---

Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcodeproj/project.pbxproj
Examples/MagicWeatherSwiftUI/iOS/Magic Weather SwiftUI.entitlements

Useful for testing. I added support so I can more easily debug #370.

MagicWeatherSwiftUI: added support for MacCatalyst

---

Purchases/Public/Errors/ErrorCode.swift

macOS: improved ErrorCode.storeProblemError to indicate potential cancellation

---

PurchasesTests/Mocks/MockSK2BeginRefundRequestHelper.swift
fastlane/Fastfile

Tests are currently crashing on iOS < 15.0. 
This is related to a known issue with linking in XCTest. There's a more detailed description of the issue in a code comment in the changes. 
They weren't failing in CI, but this was because of a bug on our Fastfile, where we weren't actually testing on older OS versions.

Fix: storekit 2 tests on older OS versions

---

SwiftStyleGuide.swift

This came from the conversation [here](https://github.com/RevenueCat/purchases-ios/pull/944/files/b90f989d83d806c2d90223e1b3c9ffaab30fcd99#r749704127).
Still looking for feedback if anyone is opposed to this.

SwiftStyleGuide: add example for explicit self

---

Purchases/Error Handling/ErrorUtils.swift
Purchases/Purchasing/PurchasesOrchestrator.swift

Fixes #751.
All the other branches seem to already have adequate errors. This one was pretty ambiguous (what was wrong with the response?) so the extra data should show us what was `nil`.

PurchasesOrchestrator.paymentDiscount(forProductDiscount:product:completion:): improved error information

---

Purchases/Public/CustomerInfo.swift
Purchases/Public/EntitlementInfo.swift
Purchases/Public/RawDataContainer.swift
RevenueCat.xcodeproj/project.pbxproj

Fixes #708.
This makes `CustomerInfo` and `EntitlementInfo` expose its underlying data so clients can access new backend data without updating the SDK.
Also, as @vegaro [mentioned](https://github.com/RevenueCat/purchases-ios/issues/708#issuecomment-947035327), can be used to simplify implementations in `hybrid-common`.

Created RawDataContainer

---

.github/PULL_REQUEST_TEMPLATE.md

Idk how to make this open-source agnostic... do we want open-source contributors making Github issues?

Update PR template to remind about android and hybrid follow-ups

---

Purchases/Error Handling/ErrorUtils.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Fixes #392.
As per the conversation in that issue, this introspects and checks for the undocumented error domain and code.

Detect ErrorCode.productAlreadyPurchasedError when SKError.unknown is actually cased by it

---

PurchasesTests/Identity/CustomerInfoManagerTests.swift
PurchasesTests/LocalReceiptParsing/Builders/ASN1ContainerBuilderTests.swift
PurchasesTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift
PurchasesTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift
PurchasesTests/LocalReceiptParsing/ReceiptParserTests.swift
PurchasesTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
PurchasesTests/Misc/SystemInfoTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Purchasing/CustomerInfoTests.swift
PurchasesTests/Purchasing/OfferingsTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/Purchasing/RCIntroEligibilityTests.swift
PurchasesTests/Purchasing/ReceiptFetcherTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

Fixes [sc-11146]
It converts failures from a fatal error (process crashing):
To a test failure:

Replaced `try!` in tests with `throws`

---

Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcworkspace/xcshareddata/swiftpm/Package.resolved
IntegrationTests/CocoapodsIntegration/CocoapodsIntegration.xcodeproj/project.pbxproj
IntegrationTests/CocoapodsIntegration/Podfile
IntegrationTests/CocoapodsIntegration/Podfile.lock
IntegrationTests/SPMIntegration/SPMIntegration.xcodeproj/project.pbxproj
IntegrationTests/XcodeDirectIntegration/XcodeDirectIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
RevenueCat.podspec
RevenueCat.xcodeproj/project.pbxproj
docs/V4_API_Updates.md

Updated min deployment targets for `purchases-ios`. 
Here's a comparison of what the min deployment targets look like before and after:
|  | v3 | v4 |
| :-: | :-: | :-: |
| iOS | 9.0 | 11.0 |
| tvOS | 9.0 | 11.0 |
| macOS | 10.12 | 10.13 |
| watchOS | 6.2 | 6.2 (unchanged) |
As soon as we include any methods from StoreKit 2, the SDK stops compiling correctly for iOS 9.0 and 10.0. It seems like an incompatibility issue with SK2, and we haven't found a way to keep compatibility with both. 
The errors logs look like this, and happen when archiving (also reproducible by running `pod lib lint`)
```ruby
- ERROR | [iOS] xcodebuild:  /Users/andresboedo/repos/purchases-ios/Purchases/Support/ManageSubscriptionsModalHelper.swift:136:23: error: cannot find 'AppStore' in scope
- ERROR | [iOS] …
```

Storekit 2: update deployment targets

---

Purchases/Misc/Obsoletions.swift

See discussion in #974.
Since they were only marked as `obsoleted` for Swift, Objective-C was able to call them.

Obsoletions: correctly marked them as obsoleted on both Swift and Objective-C

---

Purchases/Purchasing/StoreKit2/SK2BeginRefundRequestHelper.swift

While adding the begin refund button to PurchaseTester, I realized we append an error message to the refund error one extra time. It was wasteful and also not recognizing the error type correctly the second time, resulting in an extra "unknown error type" prefix.

Remove extra call to add error message

---

Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcworkspace/xcshareddata/swiftpm/Package.resolved
IntegrationTests/CocoapodsIntegration/CocoapodsIntegration.xcodeproj/project.pbxproj
IntegrationTests/CocoapodsIntegration/Podfile
IntegrationTests/CocoapodsIntegration/Podfile.lock
IntegrationTests/SPMIntegration/SPMIntegration.xcodeproj/project.pbxproj
IntegrationTests/XcodeDirectIntegration/XcodeDirectIntegration.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Package.swift
Purchases/FoundationExtensions/Locale+Extensions.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKit1/StoreKitWrapper.swift
Purchases/Support/ManageSubscriptionsModalHelper.swift
PurchasesTests/Mocks/MockManageSubscriptionsModalHelper.swift
PurchasesTests/Purchasing/StoreKitWrapperTests.swift
RevenueCat.podspec
RevenueCat.xcodeproj/project.pbxproj
docs/V4_API_Updates.md

Clean up code that checks for OS versions that we no longer support. 
Fixes [sc-1917]
We should also remove our custom `ISO8601DateFormatter`, now that it's no longer needed because we can use [Apple's version](https://developer.apple.com/documentation/foundation/iso8601dateformatter#).

Storekit 2 cleanup post update deployment targets

---

Purchases/Caching/DeviceCache.swift
Purchases/Logging/Logger.swift
Purchases/Misc/FatalErrorUtil.swift
Purchases/Networking/Backend.swift
Purchases/Public/Purchases.swift
PurchasesTests/Caching/DeviceCacheTests.swift

```
2021-11-16 17:39:54.345436-0800 [Purchases] - DEBUG: ℹ️ Debug logging enabled
2021-11-16 17:39:54.345837-0800 [Purchases] - DEBUG: ℹ️ SDK Version - 4.0.0-beta.6
2021-11-16 17:39:54.346042-0800 [Purchases] - DEBUG: 👤 Initial App User ID - nil appUserID
2021-11-16 17:39:54.346582-0800 [Purchases] - DEBUG	IdentityManager.configure(appUserID:):53: 👤 Identifying App User ID: $RCAnonymousID:xxxx
2021-11-16 17:39:54.358750-0800 [Purchases] - DEBUG	CustomerInfoManager.sendUpdateIfChanged(customerInfo:):186: ℹ️ Sending latest CustomerInfo to delegate.
2021-11-16 17:39:54.360017-0800 [Purchases] - DEBUG	Purchases.delegate:78: ℹ️ Delegate set
2021-11-16 17:39:54.360377-0800 [Purchases] - DEBUG	OfferingsManager.offerings(appUserID:completion:):42: ℹ️ No cached Offerings, fetching from network …
```

Logger: added filename / function / line information

---

APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
fastlane/Fastfile

Follow up to #979.
This simplifies APITesters like so:
- 1 Workspace including ObjC/Swift
- Each project only has 1 cross-platform target
These can be built easily locally from Xcode, and therefore they're easier to maintain.

APITester: combined targets into one cross-platform target

---

PurchasesTests/Attribution/AttributionPosterTests.swift
PurchasesTests/Misc/ISOPeriodFormatterTests.swift
PurchasesTests/Purchasing/StoreKitWrapperTests.swift

Using XCTSkip instead of silently passing tests

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
IntegrationTests/PurchaseTester/Podfile.lock
Purchases/Public/CustomerInfo.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Public/PurchasesDelegate.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Support/BeginRefundRequestHelper.swift
Purchases/Support/ManageSubscriptionsModalHelper.swift
RevenueCat.xcodeproj/project.pbxproj

Adds `async` alternatives to all of our public methods that have completion blocks. Let me know if I missed any. 
This is somewhat necessary, because for purchases-ios v3, these async alternatives would be auto-generated, because it's an objective-c project. 
However, for Swift targets, this isn't done automatically. So not having them now means that we're effectively breaking the API. 
Remaning work:
- add more detail to the v4 migration guide, including some of the naming differences for methods that start with a `get` prefix, which Apple recommends against for `async` methods. 
- I'm setting min deployment target to iOS 15.0 (and equivalent OS versions) for now, but as soon as Xcode 13.2 is stable, we can update that to 13.0 🎉

Add async alternative APIs

---

Purchases/Caching/RCDeviceCache.m

This ensures that data isn't lost if the app is closed before it's had a chance to be saved.
This backports the Swift implementation (see https://github.com/RevenueCat/purchases-ios/blob/main/Purchases/Misc/SynchronizedUserDefaults.swift#L33-L45).

RCDeviceCache: synchronize NSUserDefaults after writes

---

RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

I keep getting Xcode automatically updating these 2. Looks like for 2 reasons:
- #946 got rid of SPM on the MagicWeatherProject
- The dependency got updated

Updated Package.resolved

---

Purchases/FoundationExtensions/String+Extensions.swift
Purchases/Identity/IdentityManager.swift
Purchases/Logging/Strings/IdentityStrings.swift
Purchases/Public/Purchases.swift
PurchasesTests/Identity/IdentityManagerTests.swift
PurchasesTests/Mocks/MockDeviceCache.swift

Fixes [sc-10159].
Based on top of #974 because it contains a significant simplification of `IdentityManager` that makes this a lot easier.
Note that `Purchases.logIn` will still fail with an error when trying to use an empty string. This PR does not change that behavior.

Don't allow empty string for `appUserID` during initialization

---

Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift

Forgot to push this before merging #987 🤦 
This PR adds names to tuple values for transaction results.

async/await APIs: name values in tuples

---

Purchases/FoundationExtensions/DateFormatter+Extensions.swift
Purchases/LocalReceiptParsing/DataConverters/ArraySlice_UInt8+Extensions.swift
Purchases/Public/CustomerInfo.swift
Purchases/Public/EntitlementInfo.swift
Purchases/Public/EntitlementInfos.swift
Purchases/Public/Transaction.swift
Purchases/Purchasing/TransactionsFactory.swift
PurchasesTests/FoundationExtensions/DateFormatter+ExtensionsTests.swift
PurchasesTests/Purchasing/CustomerInfoTests.swift

Fixes #988.
Unfortunately `ISO8601DateFormatter` inherits from `Formatter`, and not `DateFormatter`, so this introduces a new protocol `DateFormatterType` that both types can implement.
Another unfortunate difference with the new type compared to the old implementation is that milliseconds are either optional or mandatory.
For that reason, I added `ISO8601DateFormatter.default` which replicates the same behavior by deferring `date(from: String) -> Date` to one formatter or the other.
I added tests to cover this behavior directly, but it was only thanks to the existing `ArraySlice` tests that I became aware of this requirement.
Additionally, I made `Transaction.init(with:productId:dateFormatter)` not `public` and not `@objc` so it can take a new `DateFormatterType`.
The method didn't need …

Replaced custom `DateFormatter` with new `ISO8601DateFormatter`

---

RevenueCat.xcodeproj/project.pbxproj

Closes #1011 
Tiny PR that removes the build phase that validated that the `TARGET_OS_` macro was not included in any Swift file.

Removed build phase

---

docs/V4_API_Updates.md

- Added note about `Carthage` integration
- Added missing `RevenueCat.ErrorCode.operationAlreadyInProgressForProductError` to Swift section
- Added `Package.product`
- Fixed `:` in parameter lists
- Fixed `PurchasesDelegate` method name
- Added error handling section
- Added `createAlias`/`identify`/`reset` deprecations ([sc-11512])
`Package.product` -> `Package.productDetails` is now documented here, but this opens another can of worms because of the introduction of `ProductDetails`:

V4 API updates: added some more changes

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
IntegrationTests/PurchaseTester/PurchaseTester/CatsViewController.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Support/ManageSubscriptionsHelper.swift
PurchasesTests/Mocks/MockManageSubscriptionsHelper.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
PurchasesTests/Support/ManageSubscriptionsHelperTests.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/PurchasesOrchestratorTests.swift
docs/V4_API_Updates.md

The method isn't guaranteed to open up a modal, since depending on the OS version it might take you to iOS Settings instead. 
So this renames it to remove the word 'modal'. 
Also, this uses the plural "subscriptions", since the page allows you to manage more than one subscription to the current app.

Rename `manageSubscriptionModal` -> `manageSubscriptions`

---

Purchases/Public/Errors/ErrorCode.swift

Without this, the error becomes the default: `The operation couldn’t be completed.`.

`ErrorCode` conforms to `CustomNSError` to provide description

---

APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift

Note that thanks to the use of `@unknown`, these will still fail to compile if we don't add new `case`s, which is what we want.

SwiftAPITester: fixed several `@unknown default` warnings

---

Purchases/Purchasing/StoreKit2/ProductsFetcherSK2.swift
StoreKitUnitTests/StoreKitConfigTestCase.swift
StoreKitUnitTests/StoreProductTests.swift

Adding this on top of #1017 
Trying to figure out this error:
```xml
<testcase classname="StoreProductTests" name="testSk2DetailsWrapsCorrectly()" time="6.029647946357727">
<failure message="failed: caught error: "The operation couldn’t be completed. (RevenueCat.ProductsManagerSK2Error error 0.)" (#CharacterRangeLen=0)"></failure>
</testcase>
```

ProductsFetcherSK2: improved Error information

---

.circleci/config.yml

Fixes #1025: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/4339/workflows/f84cb4bd-fdf1-47f0-89a8-26622457ce30/jobs/12887/tests

CircleCI: added store_test_results to `runtest` job

---

PurchasesTests/Mocks/MockProductsRequest.swift
PurchasesTests/Purchasing/StoreKitRequestFetcherTests.swift

I was trying to look at this failure:
```xml
<testcase classname="PurchasesOrchestratorTests" name="testPurchaseSK2PackageHandlesPurchaseResult()" time="0.07754290103912354">
<failure message="failed: caught error: "The operation couldn’t be completed. (StoreKit.StoreKitError error 1.)" (#CharacterRangeLen=0)"></failure>
</testcase>
```
When I realized that this was `StoreKit.StoreKitError`, not `RevenueCat.StoreKitError`.
To avoid confusion, this uses a custom namespaced error type.

Renamed `StoreKitError` overload to avoid confusion

---

BackendIntegrationTests/BackendIntegrationTests.swift
IntegrationTests/PurchaseTester/Configuration.storekit
Purchases/Purchasing/StoreProduct.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/ProductsManagerTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
StoreKitUnitTests/StoreProductTests.swift

Fixes #1013 
Will follow up with another PR for the new methods that already format the price, figured smaller PRs was probably better. 
Also does some small cleanup for outdated comments after the AvailabilityChecks PR

Add `priceFormatter` to `StoreProduct`

---

Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
PurchasesTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/StoreProductTests.swift

Added an abstraction for `SubscriptionPeriod` so that we can re-enable it in StoreProduct. 
This wraps the native types for both SK1 and SK2.

`SubscriptionPeriod` abstraction

---

.circleci/config.yml
APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme

They don't compile when _building_ the framework, but they will when running for testing.
This adds an extra step for us locally to ensure that we don't break an API, without having to manually build those projects.
Because they're part of tests now, we don't need the extra CircleCI steps. I left the `fastlane` lanes because they might still be useful to run from the command line.
Because the testers are now part of the main project too, they can easily be run by themselves as well:

Compile APITesters when building `RevenueCat` for testing

---

.circleci/config.yml

We're currently running backend integration tests even from PRs coming from forks.
Thing is, they'll always fail, since we're not passing environment variables for jobs started from forks. 
So this PR adds a filter to skip running backend integration tests in these cases. 
https://circleci.com/blog/triggering-trusted-ci-jobs-on-untrusted-forks/

skip backend integration tests when running from forks

---

Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift

We're not going to directly wrap the `downloads` property in `SKProduct`. 
This property is used in non-consumables for [Content Hosting](https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/unlocking_purchased_content). 
We were not able to find any reference to it in StoreKit 2, it looks like it might not be compatible with it. So we're not going to attempt to wrap the methods for now. 
Note that they're still available if needed, albeit not trivial to access. 
They're still accessible through: 
```swift
guard let sk1StoreProduct = storeProduct as? SK1StoreProduct else {
return
}
let skProduct = sk1StoreProduct.underlyingSK1Product
let downloads = skProduct.downloads
```

Remove outdated comment

---

Purchases/Misc/ISOPeriodFormatter.swift
Purchases/Purchasing/ProductInfoExtractor.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
PurchasesTests/Misc/ISOPeriodFormatterTests.swift
PurchasesTests/Purchasing/ProductInfoExtractorTests.swift

NFC (not functional change)
Just a small refactor while working on #1038, separating here for easier review. Simplifying these will help when adding some new types to `ProductInfo`.
I'm guessing some of these things are leftovers from the Swift migration.
- Refactored `ProductInfoExtractorTests`, moved duplicated code into `setUp`
- `ProductInfoExtractor` and `ISOPeriodFormatter`: replaced method with static function: these types contain no data, and there is only one possible implementation that we can have. For that reason, we're not mocking them or injecting them anywhere, so they're simpler as static functions. As an example, we had `lazy var isoPeriodFormatter = ISOPeriodFormatter()`, but again `ISOPeriodFormatter` contains no data, only logic, so there's no point having a `lazy` …

ProductInfo / ProductInfoExtractorTests refactor

---

Purchases/Networking/Backend.swift
Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
PurchasesTests/Mocks/MockBackend.swift
PurchasesTests/Mocks/MockIntroEligibilityCalculator.swift
PurchasesTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift

If we can return productsWithIntroOffers for all productIds without asking the backend, we should. Otherwise, we should filter out the ids that we know about and only ask the backend for ones we don't.
Fixes #982

Check for productsWithIntroOffers first, before backend

---

PurchasesTests/Misc/XCTestCase+Extensions.swift

Without this the test failure originates from `XCTestCase+Extensions.swift` instead of the individual test.

`expectFatalError` / `expectNoFatalError`: forward file and line to preserve caller failure

---

APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift
Purchases/Error Handling/ErrorUtils.swift
Purchases/FoundationExtensions/DispatchTimeInterval+Extensions.swift
Purchases/FoundationExtensions/Result+Extensions.swift
Purchases/Public/Errors/ErrorCode.swift
Purchases/Purchasing/IntroEligibilityCalculator.swift
Purchases/Purchasing/OfferingsManager.swift
Purchases/Purchasing/ProductsManager.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift
Purchases/Purchasing/StoreKit2/ProductsFetcherSK2.swift
Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
PurchasesTests/Mocks/MockProductsManager.swift
PurchasesTests/Mocks/MockProductsRequest.swift
PurchasesTests/Mocks/MockProductsRequestFactory.swift
PurchasesTests/Purchasing/ErrorCodeTests.swift
PurchasesTests/Purchasing/ProductsFetcherSK1Tests.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/Mocks/PartialMockProductsManager.swift
StoreKitUnitTests/ProductsManagerTests.swift
StoreKitUnitTests/StoreKitConfigTestCase.swift
StoreKitUnitTests/StoreProductTests.swift

Fixes [sc-10709] and #1018.
After a lot of debugging I found out the source of the problem:
```
Error Domain=NSCocoaErrorDomain Code=4097 "connection to service with pid 4422 named com.apple.storekitservice" UserInfo={NSDebugDescription=connection to service with pid 4422 named com.apple.storekitservice}"
```
To deal with that, `StoreKitConfigTestCase` had an artificial delay to make sure `StoreKit` was ready and didn't lead to these random errors, which also happened in production.
With this new mechanism, we can try again within the timeout window.

ProductFetcherSK1: added retry mechanism to deal with StoreKit error

---

APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift
IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift
Purchases/Public/Package.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
docs/V4_API_Updates.md

#848 and [sc-11623].
Depends on #1038.
Also documented some more methods in `Package` (#1046).
- `Package.localizedIntroductoryPriceString` used to be non-optional and default to an empty string (thank you `SwiftAPITester` for helping me catch this!).
Making it optional would be a breaking change, but I think 4.0 would be a good chance to do that. Version 3.0 doc just said _“A String containing the localized introductory price”_ with no indication that it could return `“”`. Or better yet, if there was no `introductoryPrice`, I guess it would return `$0.00`?

`PurchaseTester`: using new `StoreProduct.introductoryPrice` in SwiftPaywall

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/FoundationExtensions/UIApplication+RCExtensions.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/ProductsManager.swift
Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift
PurchasesTests/Mocks/MockProductsManager.swift
StoreKitUnitTests/AvailabilityChecks.swift
StoreKitUnitTests/StoreProductTests.swift

Resolves #1052 
Swift Concurrency support was modified, so I've updated the availability of all the async methods in the codebase. Some of them couldn't be updated because depend on StoreKit 2.

Update availability for async methods

---

Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
PurchasesTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift

This will be very useful to users, and will simplify the logic in the `PurchaseTester`.
Related: [sc-11623].
Also documented more methods: #1046.
Depends on #1047.

StoreProduct.pricePerMonth

---

.circleci/config.yml
docs/V4_API_Updates.md

I forgot that #1062 requires Xcode 13.2, currently in RC. 
Updated the Xcode version to use for CircleCI as well as our migration guide to reflect the new required Xcode version.

Fix: update min xcode version

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
StoreKitUnitTests/StoreProductTests.swift

It's pretty incredible that `XCTest` isn't smart enough to not call the test method that isn't available.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/4447/workflows/c4b567b8-b040-4c83-9de6-efd4be43d7eb/jobs/13515
Also fixed `SwiftAPITests` running on `tvOS` (I broke this on #1056 but didn't notice because of the other test failures).

`StoreProductTests`: skip `testSk2PriceFormatterReactsToStorefrontChanges` on iOS 14

---

.circleci/config.yml
fastlane/Fastfile

I noticed we were getting no info here: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/4466/workflows/4e2c5f84-834b-411f-b313-a76babc16a24/jobs/13593/tests

`fastlane backend_integration_tests`: added `trainer` to parse test results in CircleCI

---

.circleci/config.yml
Purchases/Logging/Strings/ManageSubscriptionsStrings.swift
Purchases/Logging/Strings/PurchaseStrings.swift
Purchases/Logging/Strings/Strings.swift
Purchases/Support/ManageSubscriptionsHelper.swift
PurchasesTests/Support/ManageSubscriptionsHelperTests.swift
RevenueCat.xcodeproj/project.pbxproj
fastlane/Fastfile

Fixes for a couple of issues with `showManageSubscriptions`: 
- From [the docs](https://developer.apple.com/documentation/storekit/appstore/3803198-showmanagesubscriptions#), this method shouldn't be called on iOS apps running on Apple Silicon, or on mac Catalyst apps. This updates so that for both of those cases, we just open up the subscription management URL. 
- As of Xcode 13.2 / iOS 15.2, it looks like `showManageSubscriptions` only returns after the manage subscriptions sheet has been closed. This meant that our method wouldn't return right away, but rather once Apple's sheet was dismissed. 
I updated it so that it always returns right away. 
I'm not 100% convinced, though, since this means that if Apple's modal fails to show for whatever reason, we'll no longer be returning an …

Fixes for `showManageSubscriptions`

---

Purchases/FoundationExtensions/Error+Extensions.swift

If extra context is nil, use the underlying NSError's localizationDescription

Pass underlying NSError localizedDescription

---

Purchases/Purchasing/PurchasesOrchestrator.swift

This is now type safe so that error is unreachable.

`PurchasesOrchestrator.purchase(package:completion:)`: handled invalid product error by making it impossible

---

Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift

This now produces an error at compile time:
```
'StoreProduct' initializer is inaccessible due to 'fileprivate' protection level
```
Since this is an Objective-C class, `[[RCStoreProduct alloc] init]` also produces a better error rather than crashing in the different `fatalErrors` of the abstract methods.

Disallow abstract `StoreProduct` initialization

---

.swiftlint.yml
Purchases/Public/Purchases.swift
Purchases/Purchasing/OfferingsFactory.swift
Purchases/SubscriberAttributes/AttributionDataMigrator.swift
StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
SwiftStyleGuide.swift

- [multiline_parameters](https://realm.github.io/SwiftLint/multiline_parameters.html)
- [vertical_parameter_alignment](https://realm.github.io/SwiftLint/vertical_parameter_alignment.html)
- [vertical_parameter_alignment_on_call](https://realm.github.io/SwiftLint/vertical_parameter_alignment_on_call.html)
Brought up in #1078.

SwiftLint / SwiftStyleGuide: added rules for parameter locations

---

StoreKitUnitTests/PurchasesOrchestratorTests.swift

We always want to run the test. This test was currently skipped.

`PurchasesOrchestratorTests.testPurchaseSK2PackageSkipsIfPurchaseFailed`: don't skip if SK2 isn't enabled

---

Purchases/Error Handling/ErrorDetails.swift
Purchases/Error Handling/ErrorUtils.swift

- `ErrorUtils` doesn't need to be `@objc`
- Changed to `enum` as per the new SwiftLint rule (`convenience_type`)

`ErrorUtils`: added file/function/line information to errors

---

Purchases/Error Handling/ErrorUtils.swift
Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift

`ProductFetcherSK1`: changed `ErrorCode.productRequestTimedOut` creation to use `ErrorUtils`

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift

Without this, it seems like tapping on the `PackageCellView` sometimes doesn't do anything.

WeatherSwiftUI: use `contentShape` to allow tapping on the whole cell

---

Purchases/Public/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKit1/StoreKitWrapper.swift

Finished #864.
Fixes [sc-7664].
I also updated the [docs on Notion](https://www.notion.so/Ask-to-buy-iOS-68e5cef128b74fedb497f684d360e706).
Note that I haven't been able to get this working though. I tested on Catalyst and on device (Sandbox environment), and I don't see a different dialog as documented. I haven't been able to figure out why.

StoreKit 2 support for `simulatesAskToBuyInSandbox`

---

Purchases/Purchasing/PurchasesOrchestrator.swift

We currently had a `guard/else` that was failing silently with no logs or anything. I was going to add a `fatalError` or something when I realized that we can make this type-safe instead.
This is equivalent to #1080.

`PurchasesOrchestrator`: changed `purchase(sk1Package:completion:)` to avoid a silent failure with the wrong type of product

---

Purchases/Error Handling/ErrorUtils.swift
Purchases/Error Handling/StoreKitError+Extensions.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
RevenueCat.xcodeproj/project.pbxproj

This allows us to handle unknown errors, like reported we did in #943, and provide a better user experience.
I filed FB9808927 for this issue in StoreKit 2. Unfortunately we can't do the same we did in #965 because the `StoreKitError` has no underlying information.

`PurchasesOrchestrator`: wrapping `StoreKitError` in our own error

---

Purchases/Networking/Backend.swift

The loginHandler function should also be reporting the customer error instantiation failures.
Description: 
It was unclear why previous code for logging the customerinfo instantiation failures was not being applied to the `handleLogin` function. This change adds that context.  
Issue to contribute in response:
https://community.revenuecat.com/sdks-51/randomly-and-false-zero-entitlements-returned-from-purchaseproduct-withcompletion-657/index2.html?postid=2884#post2884

Put CustomerInfo Logging into LoginHandler function

---

Purchases/FoundationExtensions/Dictionary+Extensions.swift
Purchases/FoundationExtensions/Set+Extensions.swift
Purchases/Purchasing/OfferingsManager.swift
Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift
PurchasesTests/FoundationExtensions/DictionaryExtensionsTests.swift
PurchasesTests/FoundationExtensions/SetExtensionsTests.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/StoreProductTests.swift

This makes creating dictionaries simpler than using `reduce(into:)`.
Note that this doesn't change any behaviors. The existing implementations that allowed duplicates still do, and vice-versa.

Introduced `Set.dictionaryWithValues`, `Sequence.uniqueIndex`, and `Sequence.indexAllowingDuplicateKeys`

---

Purchases/Purchasing/OfferingsManager.swift
PurchasesTests/Purchasing/OfferingsManagerTests.swift

The current implementation was computing the intersection of products found in the backend and in the App Store.
If everything was set up correctly, this would lead to the intersection of all products being all of them.
Instead what the implementation needed was to find the products not found in the App Store.
This lead to showing the following error even when everything was set up correctly:
```
WARN: 🍎‼️ Could not find SKProduct for ["...."] 
There is a problem with your configuration in App Store Connect. 
More info here: https://errors.rev.cat/configuring-products
```
This was already fixed in #868, but looks like it got reverted in #953.

OfferingsManager: fixed erroneous "Could not find SKProduct" log

---

Purchases/Logging/Strings/NetworkStrings.swift
Purchases/Networking/DNSChecker.swift
Purchases/Networking/HTTPClient.swift
PurchasesTests/Networking/DNSCheckerTests.swift
RevenueCat.xcodeproj/project.pbxproj

api.revenuecat.com is falsely flagged as an ad-based domain. 
Let's detect this issue and log it. 
Note: if developers receive an error when making an API request, they can inspect `NSURLErrorFailingURLErrorKey` for the url. If they see `0.0.0.0` or `127.0.0.1`, the request was blocked at the DNS level.

Detect when API requests are being blocked

---

Purchases/Error Handling/ErrorDetails.swift
Purchases/Error Handling/ErrorUtils.swift
Purchases/Networking/Backend.swift

This was only used in a couple isolated places. #1078 introduced a more general approach.

Removed `ErrorUtils` `generatedBy` parameter

---

PurchasesTests/Purchasing/ProductInfoTests.swift
PurchasesTests/Purchasing/__Snapshots__/ProductInfoTests/testEncoding.1.json
RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved

For #1045.
Snapshot testing is a more maintainable and readable way to ensure that the output format doesn't change.
In this case, I'm using it to test `ProductInfo.asDictionary()`, as a way to ensure that #1107 doesn't introduce changes.
We can use this to check other types in the future, like `SubscriberAttribute`, `ETagAndResponseWrapper`, etc.
This uses [`swift-snapshot-testing`](https://github.com/pointfreeco/swift-snapshot-testing).
The simple line `try assertSnapshot(matching: productInfo.asDictionary(), as: .json)` automatically checks against a stored file (`PurchasesTests/Purchasing/__Snapshots__/ProductInfoTests/testEncoding.1.json`). If the output changes, the test error is very readable:
I've added the snapshot folder as a reference folder in Xcode, which makes looking at the …

`ProductInfoTests`: added snapshot test

---

TestPlans/AllTests.xctestplan

We currently have 3 (+1 for test coverage) test plans:
- `RevenueCat`
- `UnitTests`
- `AllTests`
`RevenueCat` tests are already set to run in parallel, while `UnitTests` aren't to avoid issues with the `StoreKit` test environment.
This PR makes `RevenueCat` tests inside of `AllTests` also run in parallel.
The different on my computer is 7 seconds versus 11 seconds.

`AllTests.xctestplan`: changed to run RevenueCat tests in parallel

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
Examples/MagicWeatherSwiftUI/Shared/Sources/ViewModels/UserViewModel.swift
Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift

- `UserViewModel.offerings` is `@Published`, so no need to call `objectWillChange.send()` manually
- `UserViewModel` doesn't need to inherit `NSObject`
- `@State` setters shouldn't be `public`

`MagicWeatherSwiftUI` improvements

---

Purchases/FoundationExtensions/JSONDecoder+Extensions.swift
Purchases/Networking/Backend.swift
Purchases/Purchasing/ProductInfo.swift
Purchases/Purchasing/ProductInfoExtractor.swift
Purchases/Purchasing/PromotionalOffer.swift
Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
PurchasesTests/Mocks/MockSK1Product.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/ProductInfoExtensions.swift
PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
PurchasesTests/Purchasing/ProductInfoTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/Purchasing/__Snapshots__/ProductInfoTests/testEncoding.1.json

First step towards #1045.
I've run the new test introduced in #1109 and this is backwards compatible.

`ProductInfo`: replaced manual encoding with `Encodable` implementation

---

Purchases/Purchasing/ProductInfo.swift
Purchases/Purchasing/ProductInfoExtractor.swift
Purchases/Purchasing/PromotionalOffer.swift
PurchasesTests/Purchasing/ProductInfoExtensions.swift
PurchasesTests/Purchasing/ProductInfoExtractorTests.swift
PurchasesTests/Purchasing/ProductInfoTests.swift

Removed `PromotionalOffer.IntroDurationType` in favor of `PaymentMode`

---

scripts/swiftlint.sh

Brought up by https://community.revenuecat.com/sdks-51/release-pre-built-xcframework-why-dsyms-are-separated-1025, when building `RevenueCat` target without having `SwiftLint` installed results in this error being printed. The script exists with code 0, but Xcode still fails:
> Command PhaseScriptExecution emitted errors but did not return a nonzero exit code to indicate failure
That's likely Xcode parsing the "Error" part of the message, which I don't think was done on purpose.
CircleCI doesn't use this script, and `fastlane run swiftlint` does fail if it's not installed, so this helps users build the framework even if they don't have it installed.

`swiftlint.sh`: avoid error if SwiftLint not installed

---

.circleci/config.yml

CircleCI has a new [executor type available](https://circleci.com/docs/2.0/executor-types/#using-macos). 
These machines are based on newer machines, I believe including SSDs. 
This should significantly improve our build times. 
Here's a quick sample, but take it with a grain of salt because I only ran tests once, didn't bother to run them multiple times and get averages. 
| :-: | :-: |
| <img width="511" alt="Screen Shot 2021-12-29 at 6 23 59 PM" src="https://user-images.githubusercontent.com/3922667/147704470-ff5d6279-49e7-4568-bbd1-0916d590638f.png"> |  <img width="637" alt="Screen Shot 2021-12-29 at 6 24 07 PM" src="https://user-images.githubusercontent.com/3922667/147704491-df3d8d86-d90f-49f2-bf2a-d8a770a6e7e8.png"> |
| <img width="501" alt="Screen Shot 2021-12-29 …

Update to gen2 circleCI machines

---

fastlane/Fastfile

Related [community post here](https://community.revenuecat.com/sdks-51/release-pre-built-xcframework-why-dsyms-are-separated-1025)
Our `.xcframework` folder didn't include .dSYMs. This could be a problem depending on the package manager being used. In particular, for Carthage, when using `carthage update --use-xcframeworks`, the `.xcframework` that got pulled in and built would never have the `dSYM`s. Only workaround would be to copy them from the checkouts folder. 
The plugin that we're using has an `include_debug_symbol` parameter that defaults to `true`, if omitted, it doesn't work. 
I've filed an [issue](https://github.com/bielikb/fastlane-plugin-create_xcframework/issues/16) and a [PR with a fix](https://github.com/bielikb/fastlane-plugin-create_xcframework/pull/17), but in the …

v3: Fix `.xcframework` not including dSYMs

---

fastlane/Fastfile

V4 equivalent of #1117 
Related [community post here](https://community.revenuecat.com/sdks-51/release-pre-built-xcframework-why-dsyms-are-separated-1025)
Our `.xcframework` folder didn't include .dSYMs. This could be a problem depending on the package manager being used. In particular, for Carthage, when using `carthage update --use-xcframeworks`, the `.xcframework` that got pulled in and built would never have the `dSYM`s. Only workaround would be to copy them from the checkouts folder. 
The plugin that we're using has an `include_debug_symbol` parameter that defaults to `true`, if omitted, it doesn't work. 
I've filed an [issue](https://github.com/bielikb/fastlane-plugin-create_xcframework/issues/16) and a [PR with a fix](https://github.com/bielikb/fastlane-plugin-create_xcframework/pul …

v4: Fix .xcframework not including dSYMs

---

StoreKitUnitTests/TransactionsManagerSK2Tests.swift

> Making a purchase without listening for transaction updates risks missing successful purchases. Create a Task to iterate Transaction.updates at launch.
This silences the warning by at least monitoring updates in the test.

`TransactionsManagerSK2Tests`: fixed runtime warning for purchasing without listening to transaction updates

---

README.md

I was going through the README and realized that this currently reads as if `RevenueCat.framework` is only compatible with `Swift`.

README: clarify V4 is Objective-C compatible

---

.circleci/config.yml

Fixes:
> The dev version of circleci/macos@dev:25cb9bd has expired. Dev versions of orbs are only valid for 90 days after publishing.
See failure: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/4662/workflows/09dbb7dd-bb2a-4cf7-8f11-7e8e9d1b6155/jobs/14399

CircleCI: updated Orb

---

CHANGELOG.latest.md
CHANGELOG.md

From comments [here](https://github.com/RevenueCat/purchases-ios/pull/1132#discussion_r779515931), the link to the diff compares against `main` instead of the release tag. This fixes that link.

fix link in changelog

---

Purchases/Caching/DeviceCache.swift
Purchases/Identity/IdentityManager.swift
Purchases/Logging/Strings/ConfigureStrings.swift
Purchases/Logging/Strings/IdentityStrings.swift
Purchases/Logging/Strings/PurchaseStrings.swift
Purchases/Networking/Backend.swift
Purchases/Public/Purchases.swift

Fixes https://github.com/RevenueCat/purchases-ios/issues/746 and [sc-10311].
After reviewing the conversations around the issue, I think we can all agree that this is the best solution.
We could make this optional for only `DEBUG` builds, but if a user has a debug build of `RevenueCat` in their app in production, with debug logs enabled (either the default handler or their own), these IDs would be leaking.
- Moved a few strings into Strings file
- Removed unused strings

Avoid logging user IDs

---

Purchases/Logging/Strings/PurchaseStrings.swift
Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift

`TrialOrIntroPriceEligibilityChecker`: added warning if no identifiers were requested

---

APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Purchases/Purchasing/ProductRequestData+Initialization.swift
Purchases/Purchasing/ProductRequestData.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreProductDiscount.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/ProductRequestDataExtensions.swift
PurchasesTests/Purchasing/ProductRequestDataInitializationTests.swift
PurchasesTests/Purchasing/ProductRequestDataTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
RevenueCat.xcodeproj/project.pbxproj

[sc-12282]
Our PromotionalOffer currently maps to SK1’s SKProductDiscount and SK2's Product.SubscriptionOffer (https://developer.apple.com/documentation/storekit/product/subscriptionoffer).
Confusingly, the method promotionalOffer() from SK2 does not return a Product.SubscriptionOffer, but rather a PurchaseOption
https://developer.apple.com/documentation/storekit/product/purchaseoption/3749444-promotionaloffer
We will use the `PromotionalOffer` naming for the SKPaymentDiscount/SubscriptionOffer instead

Rename PromotionalOffer -> StoreProductDiscount

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Identity/CustomerInfoManager.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/ProductsManager.swift
Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift
PurchasesTests/Mocks/MockProductsManager.swift
StoreKitUnitTests/AvailabilityChecks.swift
StoreKitUnitTests/StoreProductTests.swift

Brought up [here](https://github.com/RevenueCat/purchases-ios/pull/1100#discussion_r779831690).
> min deployment target on `watchOS` is 6.2 since previous versions didn't even have IAP

Fixed `watchOS` availability annotations from `6.0` to `6.2`

---

Purchases/Logging/Strings/OfferingStrings.swift
Purchases/Purchasing/StoreKit2/ProductsFetcherSK2.swift
StoreKitUnitTests/StoreProductTests.swift

- `ProductFetcherSK2` was checking its internal `cachedProductsByIdentifier`, but it was never populated. It now is.
- The test `testSk2PriceFormatterReactsToStorefrontChanges` only worked because the `ProductFetcherSK2` instance was recreated, invalidating the cache. `ProductFetcherSK2` now invalidates its cache when the `Storefront` changes instead.
- Tests in `StoreProductTests` no longer manually reset the `testSession.locale`, that's done by `StoreKitConfigTestCase` calling `resetToDefaultState` on setUp.
- Listening to `Storefront.updates` is what I tried first, but due to race conditions the update never arrives on time for the test to detect it and clear the cache.
- This also introduced challenges with the way listening to those updates must be done, requiring to either make …

`ProductFetcherSK2`: fixed product cache

---

Purchases/Purchasing/StoreKit1/ProductsFetcherSK1.swift
StoreKitUnitTests/StoreProductTests.swift

`ProductsFetcherSK2` was fixed in #1123. We could do the same in `ProductsFetcherSK1`,
but `Storefront.current` is iOS 15 only, so solving it wouldn't be quite as trivial.
For now at least this documents the behavior.
Filed future task: https://app.shortcut.com/revenuecat/story/12350/invalidate-productsfetchersk1-cache-when-storefront-changes

`StoreProductTests`: clarify `ProductsFetcherSK1` behavior

---

Purchases/Identity/CustomerInfoManager.swift

Requested [here](https://github.com/RevenueCat/purchases-ios/pull/1100#discussion_r779832767).

Added docstring for `CustomerInfoManager.customerInfoObserversByIdentifier`

---

PurchasesTests/Networking/HTTPClientTests.swift

After [this review comment ](https://github.com/RevenueCat/purchases-ios/pull/1124#discussion_r781401934)
> Feel free to do this in another PR, but to document that I would replace it with `fatalError("Unreachable")`
Tiny PR to replace a random number with a `fatalError` in an unreachable return sentence.

Replace a random number with an unreachable `fatalError` 

---

Purchases/Misc/Obsoletions.swift
docs/Deprecations.md

For some reason this only lead to a warning in the Objective-C `APITester` when deprecating a method with an `@objc` annotation:
>  Feature cannot be obsoleted in iOS version 1 before it was introduced in version 12.2; attribute ignored
But looking at the auto-generated `RevenueCat-Swift.h` I could see this was an issue for these methods as well. Likely the `obsoleted` annotation was being ignored.
To fix this, now we only have 1 `@available` annotation for each platform, with a matching `introduced` and `obsoleted` version.
I also created `Deprecations.md` to document this.
See also [sc-12354].

Obsoletions: fixed incompatible `introduced` and `obsoleted` annotations

---

scripts/swiftlint.sh

#1124 introduced a change to disable some rules for `PurchasesTests`.
This lead to lint issues being found by `swiftlint` that `swiftlint.sh` (and therefore Xcode) wasn't reporting.
To fix that, and simplify the logic at the same time, I removed the custom parameters and instead made the script call `swiftlint` from the root directory (by using `pushd`/`popd`).

swiftlint.sh: simplified script to make it equivalent to `fastlane run swiftlint`

---

APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
APITesters/SwiftAPITester/SwiftAPITester/SubscriptionPeriodAPI.swift

- Removed duplicate `main.m` from compile phase, probably from a bad merge.
- Fixed unused variable warning

Fixed 2 APITester warnings

---

StoreKitUnitTests/.swiftlint.yml
StoreKitUnitTests/BeginRefundRequestHelperTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift

Same rules disabled there in #1124.
This change will also need #1154 so that `scripts/swiftlint.sh` can parse `.swiftlint.yml` recursively.

`StoreKitUnitTests`: disable the same lint rules as `PurchasesTests`

---

Purchases/Misc/MacDevice.swift

Originally reported by @teeeeeegz in [this comment](https://github.com/RevenueCat/purchases-ios/pull/1006#issuecomment-1009976006). 
We were missing an `import Foundation` on `MacDevice`, which would make imports fail on macOS when importing through SPM. 
I added the missing import and double-checked that it now works correctly.

added missing `import Foundation` for `MacDevice`

---

fastlane/Fastfile

Currently, our beta GitHub releases aren't automatically marked as pre-release. 
We can do this automatically with fastlane, so I just added the param.

add `is_prerelease` param to GH releases

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Public/Purchases.swift
PurchasesTests/Misc/SystemInfoTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

Resolves [sc-12137]
Makes the configure() with `useStoreKit2IfAvailable` private for our beta 3 launch, since promotional offers won't be ready. In doing so, I saw we don't have the APITester calls or unit tests, so I added them and commented out.

Temporarily disable useStoreKit2IfAvailable

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesErrorCodeAPI.m
APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift

Add back enum cases in APITesters

Follow up for https://github.com/RevenueCat/purchases-ios/pull/1159

---

Purchases/Purchasing/PurchasesOrchestrator.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift

`isRestore` should be set to `false` when using observer mode since user/developer is handling transactions
- Passing `!systemInfo.finishTransactions` (which is observer mode) into `syncPurchases` 
- Added new tests for `StoreKit2TransactionListenerDelegate` to test with and without observer mode

`isRestore` respects observer mode when syncing purchases in `StoreKit2TransactionListenerDelegate`

---

Purchases/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
SwiftStyleGuide.swift

Currently the `Task` was outliving `StoreKit2TransactionListener`.

`StoreKit2TransactionListener`: cancel task on `deinit`

---

Purchases/Purchasing/PurchasesOrchestrator.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift

Resolves #1114 
Now, if `purchase(sk2Product:)` fails because of an error when posting the receipt, the method returns `ErrorCode.unknownError` because it assumes it always receives a `StoreKitError`. The goal of this PR is to improve the way to handle the error.
- Add a `where` condition to know if the error type is `StoreKitError`, if not the method returns the error received.
- Add a new test method to validate this logic.

Improve the way to handle the error if `purchase(sk2Product)` fails due to an error when posting the receipt

---

.circleci/config.yml
IntegrationTests/SPMIntegration/SPMIntegration.entitlements
IntegrationTests/SPMIntegration/SPMIntegration.xcodeproj/project.pbxproj
IntegrationTests/SPMIntegration/fastlane/Scanfile
fastlane/Fastfile

#1162 highlights the fact that we're not testing for macOS compatibility in SPM integration tests, so stuff could fall through the cracks. 
This adds `catalyst` and `tvOS` support so that tests would fail if we've messed up macOS compatibility on SPM.
See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/4883/workflows/358209fb-3643-406e-987d-24325ed18ac1/jobs/15354

Added catalyst and tvOS support for SPM integration tests

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
PurchasesTests/Mocks/MockBackend.swift
PurchasesTests/Mocks/MockStoreKitWrapper.swift
PurchasesTests/Mocks/MockTransaction.swift
PurchasesTests/Purchasing/PurchasesTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift

Fixes [sc-12407]
- Replaces `SKPaymentDiscount` with `StoreProductDiscount` in Public API
- Orchestrator does the `StoreProductDiscount` to `SKPyamentDiscount` so end user doesn't need to worry about that step anymore
- Updated `PuchaseOrchestrator.purchase` to take a `package: Package?` instead of a `presentedOfferingIdentifier maybePresentedOfferingIdentifier: String?`

use StoreProductDiscount instead of SKPaymentDiscount in public api

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKitAbstractions/StoreTransaction.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
docs/V4_API_Updates.md

Fixes [sc-12293] and #1055.
- Replaced `SK1Product` with `StoreProduct` in all `Purchases.purchase(product:)` methods.
- Unified all logic into a single (well, two unfortunately _(1)_) method in `PurchasesOrchestrator` that checks the underlying product inside `StoreProduct`.
- Added docs for new types in `docs/V4_API_Updates.md`
_(1) `SKPaymentDiscount` is only available from `iOS 12.2`, so we can't consolidate both methods while being able to call it from iOS 11. This introduces a small amount of duplication unfortunately_.
- Adding `purchase(product:)` overloads with deprecation warnings. That was my first approach, and I don't think think that's necessary and worth the duplication because all methods will be returning `StoreProduct`s.

Update public `purchase(product:)` methods with `StoreProduct`

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
BackendIntegrationTests/BackendIntegrationTests.swift
Purchases/Logging/Strings/RestoreStrings.swift
Purchases/Misc/Obsoletions.swift
Purchases/Public/CustomerInfo.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
PurchasesTests/Purchasing/PurchasesTests.swift
docs/V4_API_Updates.md

Fixes [sc-12539]
`restoreTransactions` is typically referred to as `restorePurchases` (and is this way on other platforms) so making this consistent)
- Renamed `Purchases.restoreTransactions` to `Purchases.restorePurchases`
- Obsoleted `Purchases.restoreTransactions` (since we are bumping to a major version)
- Renamed `PurchasesOrchestrator.restoreTransactions` to `PurchasesOrchestrator.restorePurchases`
- Updated all comments that referred to `restoreTransactions` to `restorePurchases`

Rename `restoreTransactions` to `restorePurchases`

---

Purchases/Misc/Obsoletions.swift
docs/V4_API_Updates.md

I realized that if you're using `package.product`, there's no obsoletion in place for an auto-fix it, so I added it

add obsoletion for `product` in `package`

---

Purchases/Misc/Obsoletions.swift

There were some obsoleted methods that either didn't have an `@objc` annotation, or the annotation didn't really match our Obj-C API from v3, so I updated them. 
[This should be our reference for the obj-c naming](https://github.com/RevenueCat/purchases-ios/blob/3.13.2/Purchases/Public/RCPurchases.h)

fixed `@objc` annotations for some obsoleted methods

---

Purchases/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift

`SKProductDiscount` was introduced in iOS 11.2, but its `identifier` was only available from iOS 12.2. Instead of making the latter the minimum version, this takes advantage of `StoreProductDiscountType.offerIdentifier` being `Optional`.
This is necessary for the change in #1184, so that `TrialOrIntroPriceEligibilityChecker` can continue to work from iOS 11.2.

Lowered `StoreProduct.introductoryDiscount` availability to `iOS 11.2`

---

Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift

Idea by @aboedo in https://github.com/RevenueCat/purchases-ios/pull/1184#discussion_r788085622.

`StoreProduct`: added `@available` annotations to help with migration from `SKProduct`

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift

Also removed redundant checks using the trailing closure syntax, which was basically testing a Swift feature, not our own APIs.

APITester: added explicit types to closure parameters

---

IntegrationTests/PurchaseTester/PurchaseTester/CatsViewController.swift
IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift

similar to #1189 and #1192, updates API calls to latest syntax

updated API calls in purchaseTester

---

Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift

If you're using `numberOfUnits` of `SKProductSubscriptionPeriod`, there was no auto-fix-it to update to `value` in `SubscriptionPeriod`, so similarly to #1191 this adds a fake obsoletion to make it easier to migrate

add obsoletion for `numberOfUnits` in `SubscriptionPeriod`

---

Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift

From [this comment](https://github.com/RevenueCat/purchases-ios/pull/1194#pullrequestreview-857391851), this cleans up so that it's marked as `unavailable` instead of `obsolete`, which is more accurate since it was never available

clean up obsoletion of `numberOfUnits`

---

Purchases/Logging/Strings/PurchaseStrings.swift
Purchases/Public/Purchases.swift
Purchases/Purchasing/StoreKit1/StoreKitWrapper.swift

Fixes [sc-10766]. The issue described there is supposed to be fixed in Xcode 13.2. This seems to be isolated to this particular method.
Even though the docs in [`SKPaymentQueue.presentCodeRedemptionSheet`](https://developer.apple.com/documentation/storekit/skpaymentqueue/3566726-presentcoderedemptionsheet) say that it's available on Catalyst 14.0, there is a note:
> This function doesn’t affect Mac apps built with Mac Catalyst.
It crashes when called both from Catalyst and also when running as "Designed for iPad".
To address that, this PR has 2 fixes:
- Disable API for Catalyst: this makes it impossible to call the method on "regular" Catalyst apps
- Disable call at runtime on "Designed for iPad" apps: because they're still "iOS" apps, it's still possible to call the method, but at …

`Purchases.presentCodeRedemptionSheet`: disable on Catalyst

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Public/Package.swift
Purchases/Public/Purchases+async.swift
Purchases/Public/Purchases.swift
Purchases/Public/PurchasesDelegate.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
PurchasesTests/Mocks/MockPurchasesDelegate.swift
PurchasesTests/Purchasing/PurchasesTests.swift

There was one method still referencing `SKProduct`, an optional method from `PurchasesDelegate`. 
I updated it and its tests. 
I'm somewhat torn because since it's an optional method, this won't break compilation, but it'll issue a build warning saying that you have a method that closely matches the signature of the method but not quite.

update `PurchasesDelegate` method to use `StoreProduct` instead of `SKProduct`

---

fastlane/Fastfile

The CircleCI job for deploys in purchases-android broke because a wrong variable name was used and I noticed we had the same issue in iOS too.

Fix github_release pre-releases

---

CHANGELOG.latest.md
Purchases/Purchasing/Purchases.swift

Since the CHANGELOG is cumbersome to compile, I figured I'd do it as a separate PR. 
This updates it to the current changes

prepare CHANGELOG.latest.md for RC

---

Purchases/Misc/Obsoletions.swift

Fixes [sc-12578].
- Cleaned up docs that referenced `completion` on `async` methods
- Fixed incorrect `paymentDiscount(forProductDiscount:)`. The old Swift name was `paymentDiscount(for:)` (Swift automatically removes parameter type from the name)
- Verified all previous (as of version 3.x) `async` methods get a fix-it equivalent to the non-`async` counterparts

Added missing obsoletions for async methods

---

Purchases/Purchasing/Package.swift

I'm going through the migration from 3.x to 4.0-rc1 in my app, and noticed that I relied on `Package` implementing `Equatable`/ `Hashable`. The old `Objective-C` type didn't override these, so it's not a regression, but it's nice to have.

`Package`: implement `isEqual`/`hash`

---

Purchases/Misc/Obsoletions.swift

This matches the guidance in `V4_API_Migration_guide`. The domain is still available in `Objective-C`, but for Swift `ErrorCode` is the new way to handle errors.

`ErrorDomain`: added obsoletion with message to direct users to `ErrorCode`

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m

`SKProduct` is no longer used in the API 🎉

ObjCAPITester: fixed warning by removing unused variable

---

PurchasesTests/Purchasing/PurchasesTests.swift

- Removed `eventually` since setup is synchronous
- Using `===` to avoid calling a potentially overridable `NSObject.isEqual`

`Purchases.configure`: simplified tests

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift

Very simple and crude UI, but it's something. Currently the error was only logged to the console.

`MagicWeatherSwiftUI`: display error when purchase fails

---

Purchases/Misc/Obsoletions.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
docs/Deprecations.md

Reported by @codykerns, the existing annotations were actually wrong, resulting in no warning or error!
Looks like this is the only way to have `introduced` and `obsoleted` (`unavailable` now) together, so I updated `Deprecations.md` to reflect this.

Fixed obsoletions that have an `introduced` version

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift

`APITesters`: added missing types to `Purchases.checkPromotionalDiscountEligibility(forProductDiscount:product:)`

---

APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductDiscountAPI.m
APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
Documentation.docc/V4_API_Migration_guide.md
Purchases/Logging/Strings/StoreKitStrings.swift
Purchases/Misc/Obsoletions.swift
Purchases/Purchasing/ProductRequestData+Initialization.swift
Purchases/Purchasing/ProductRequestData.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/ProductRequestDataExtensions.swift
PurchasesTests/Purchasing/ProductRequestDataInitializationTests.swift
PurchasesTests/Purchasing/ProductRequestDataTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift

- Was used prior to #1181 to indicate no intro durations when encoded in `ProductRequestData` (the old `ProductInfo`)
- When `IntroDurationType` was removed in favor of only one enum, `PaymentMode` (#1045), `.none` was required to accommodate for that
- Because neither SK1 and SK2's `PaymentMode`s aren't `@frozen`, RevenueCat needs to handle `@unknown default` cases when converting from that type. `.none` was repurposed for this reason.
`StoreProduct` already has optional `StoreProductDiscount`s (`introductoryDiscount` and potentially empty `discounts` `Array`).
If users get a `StoreProductDiscount`, it's unnecessary to make them handle the case of `PaymentMode.none`, when we can instead fail to parse it and not include it as part of the product.

`StoreProductDiscount.PaymentMode`: obsoleted `.none`

---

Documentation.docc/Documentation.md
Documentation.docc/Purchases.md
Purchases/Attribution/AttributionNetwork.swift
Purchases/Identity/CustomerInfo.swift
Purchases/Purchasing/EntitlementInfo.swift
Purchases/Purchasing/Offering.swift
Purchases/Purchasing/Package.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift

- Added a Documentation Extension so we can provide detailed docs for the Purchases class. This somewhat overlaps with the main SDK's docs, which is somewhat expected, with the main difference being that this is very specific to the Purchases class, and it lists all of its methods. 
- Added docs that were missing from a few public classes. I mostly just grabbed the copy from the existing v3 docs.

Improve docs

---

Documentation.docc/V4_API_Migration_guide.md

Did this wrong on #1220, I forgot this requires the new Docc format.

`V4_API_Migration_guide.md`: fixed `StoreProductDiscount.PaymentMode` reference

---

.circleci/config.yml

We had disabled the `docs_deploy` job for v4 releases because it would overwrite our v3 docs, with v3 being the currently stable version. 
However, since #1226, we're now deploying v4 docs to a separate site, so we can have both versions concurrently without issues.

enabled `docs_deploy` job for beta releases

---

APITesters/ObjCAPITester/ObjCAPITester/RCSubscriptionPeriodAPI.m
APITesters/SwiftAPITester/SwiftAPITester/SubscriptionPeriodAPI.swift
Purchases/Misc/ISOPeriodFormatter.swift
Purchases/Purchasing/ProductRequestData+Initialization.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
PurchasesTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift

Follow up to #1220.
In the same way that we obsoleted `StoreProductDiscount.PaymentMode.none`, this follows the same pattern of failing to initialize the `StoreProductDiscount` if the unit is not recognized, instead of exposing an invalid discount.
The type is new in V4, so I think it's safe to not have this in the `V4_API_Migration_guide`, and no obsoletion needed.

Removed unnecessary `SubscriptionPeriod.Unit.unknown`

---

Purchases/Error Handling/ErrorUtils.swift
Purchases/Error Handling/StoreKitError+Extensions.swift
Purchases/Misc/SynchronizedUserDefaults.swift
Purchases/Purchasing/ProductRequestData.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift

We were using `seeAlso` wrong in a couple of places. I also took the opportunity to standardize the syntax to reference format here: https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/SeeAlso.html
This fixes a few places were it looked a bit odd in the docs. 
Weirdly, it doesn't seem to do anything, at least in the preview ¯\\_(ツ)_/¯. But I still feel better using the correct format. 
| :-: | :-: |
| <img width="811" alt="Screen Shot 2022-01-31 at 2 35 29 PM" src="https://user-images.githubusercontent.com/3922667/151844619-4a649eb4-9e3e-4918-96b3-93df912d5016.png"> | <img width="1041" alt="Screen Shot 2022-01-31 at 2 35 45 PM" src="https://user-images.githubusercontent.com/3922667/151844593-f04268ab-a8f5-4f20-9859-dd8e95 …

fixed `seeAlso` use

---

Purchases/CodableExtensions/PeriodType+Extensions.swift
Purchases/Purchasing/EntitlementInfo.swift

Same as #1236.
If a new case is added, this will now fail to compile instead of throwing `CodableError.unexpectedValue`

`PeriodType`: refactored mapping to prevent forgetting a future case

---

Purchases/Purchasing/Purchases.swift

`Purchases.shared`: changed `note` to `warning`

---

fastlane/Fastfile

- CircleCI builds do not fail if uploaded junit test results have failures (to my surprise)
- https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/5207/workflows/adf40d6a-9fea-4aa3-b849-729b95f26204/jobs/16740
- _fastlane_ needs to fail the build
- _fastlane_ used to fail the build when we needed to use `trainer`
- But since everything can be done with `scan`, we now need to remove `fail_build: false`
- The CircleCI job will now error out if `scan` detects a failure during its run
**Bonus:** we can now remove `result_bundle: true` (which was outputting `.xcresult` in the output directory). Scan will get the result bundle automatically from the derived data.

[fastlane] fail build if scan fails (trainer used to do this)

---

Purchases/Error Handling/ErrorUtils.swift
Purchases/Logging/Logger.swift
Purchases/Purchasing/EntitlementInfos.swift
Purchases/Purchasing/Purchases.swift

It seems that `SeeAlso` doesn't work with DocC. 
It doesn't actually affect the outcome of the automated `See Also` section, and it doesn't render links either. 
So I replaced them with either `Related Symbols` or `Related Articles` so that at least something is rendered.

Replace `SeeAlso` with links

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Logging/Strings/StoreKitStrings.swift
Purchases/Misc/Obsoletions.swift
Purchases/Misc/Purchases+async.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift

Fixes [sc-7665]
~~Depends on #1216.~~
- `Purchases.purchase(product: StoreProduct, discount: StoreProductDiscount)` now supports `SK2`
- Added `PurchaseResultData` as a counterpart of `PurchaseCompletedBlock` for `async` APIs, greatly simplifying a lot of methods that returned the same tuple. See #1234 for how the type provides consistency across several layers.
- Cancelling an SK2 purchase was returning both `userCancelled` `true` but also throwing `ErrorUtils.purchaseCancelledError`, which is against what the method documented. Now cancelling a purchase won't `throw`, but instead return `userCancelled` `true`.
- `PurchaseResultData` now has an `Optional` `Transaction` because `Product.PurchaseResult` does not provide a `Transaction` if the purchase is cancelled. This would have been a …

`PurchasesOrchestrator`: added support for SK2 discounts

---

PurchasesTests/Purchasing/PurchasesTests.swift
RevenueCat.xcodeproj/project.pbxproj

Also added `AvailabilityChecks.swift` to `RevenueCatTests` target.

`PurchasesTests`: using `AvailabilityChecks`

---

Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
PurchasesTests/Mocks/MockStoreKit2TransactionListener.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
StoreKitUnitTests/StoreKit2TransactionListenerTests.swift

This was the last TODO for SK2 purchases. Made much cleaner thanks to the new `PurchaseResultData` introduced in #1217.
- Added test to verify transaction is returned
- Combined 2 redundant `PurchasesOrchestrator.purchase(sk2Product:discount:)` methods

SK2 Purchases: return original `Transaction`

---

PurchasesTests/Networking/BackendTests.swift

All tests are currently doing `backend?.`, which could potentially make the test silently pass while not doing anything.
Using `XCTUnwrap` in this case is unnecessary because the failure is more of a configuration error, so a hard crash is warranted.

`BackendTests`: fail tests if `Backend` isn't initialized

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Purchases/Logging/Strings/PurchaseStrings.swift
Purchases/Misc/Purchases+async.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift

This simplifies the API and allows users to use only one method to determine which `StoreProductDiscount`s to display in the UI.

Added `StoreProduct.getEligibleDiscounts()` and `Purchases.getEligibleDiscounts(forProduct:)`

---

Purchases/CodableExtensions/Store+Extensions.swift
Purchases/Purchasing/EntitlementInfo.swift

Same as #1236.
If a new case is added, this will now fail to compile instead of throwing `CodableError.unexpectedValue`

`Store`: refactored mapping to prevent forgetting a future case

---

Purchases/CodableExtensions/PurchaseOwnershipType+Extensions.swift
Purchases/Purchasing/PurchaseOwnershipType.swift

If a new `case` is added, this will now fail to compile instead of being parsed as `.unknown`.

`PurchaseOwnershipType`: refactored mapping to prevent forgetting a future case

---

Purchases/Identity/CustomerInfoManager.swift
Purchases/Purchasing/Purchases.swift

Fixes [sc-13029] and [sc-13030].

`Purchases.customerInfoStream`: improved docs and start emitting current `CustomerInfo`

---

PurchasesTests/Networking/DNSCheckerTests.swift

The test was crashing due to the force unwrap when ran with no internet connection. Now it just simply fails.

Documented `DNSCheckerTests.testResolvedHost` requires a connection

---

Purchases/Logging/Logger.swift

I think this is useful when running tests, and probably for users when debugging locally. Release builds will still default to `.info`.

`Logger.logLevel`: changed default to `.debug` for debug builds

---

Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift

`checkTrialOrIntroDiscountEligibility` is meant to be called programmatically, and should therefore **never** trigger a refresh receipt request, since that could make App Store prompt for log in credentials. 
This PR ensures that we never refresh the receipt for that method. 
This is the v4 equivalent of #1264

ensure `checkEligibility` doesn't refresh the receipt

---

CHANGELOG.latest.md
CHANGELOG.md

the migration guide was moved to `Documentation.docc/V4_API_Migration_guide.md`. This PR updates outdated references.

fixed links to v4 api migration guide

---

Purchases/Networking/Backend.swift
Purchases/Networking/Operations/CreateAliasOperation.swift
Purchases/Networking/Operations/GetCustomerInfoOperation.swift
Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
Purchases/Networking/Operations/GetOfferingsOperation.swift
Purchases/Networking/Operations/LogInOperation.swift
Purchases/Networking/Operations/NetworkOperation.swift
Purchases/Networking/Operations/PostAttributionDataOperation.swift
Purchases/Networking/Operations/PostOfferForSigningOperation.swift
Purchases/Networking/Operations/PostReceiptDataOperation.swift
Purchases/Networking/Operations/PostSubscriberAttributesOperation.swift

Fixes https://app.shortcut.com/revenuecat/story/12888/api-calls-are-not-always-executed-in-order
Initial step towards fixing https://app.shortcut.com/revenuecat/story/12802/api-cache-too-aggressive
See also https://app.shortcut.com/revenuecat/story/9521/rewrite-httpclient-for-purchases-ios
- Overridden `isAsynchronous` to tell `OperationQueue` that operations run in the background
- Manually calling KVO methods as required by `Operation`
- Manually completing `NetworkOperation`s when all work is completed

`NetworkOperation`s are asynchronous

---

Purchases/Purchasing/EntitlementInfo.swift
Purchases/Purchasing/Offering.swift
Purchases/Purchasing/Package.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreTransaction.swift

Fixes [sc-12884]
SwiftUI (kind of) requires these models conform to `Identifable` to more easily use them with `ForEach` and `List`
Adds extensions to a bunch of models

Add identifable to models (mainly for SwiftUI)

---

.circleci/config.yml
Purchases/Purchasing/EntitlementInfo.swift
fastlane/Fastfile
fastlane/README.md

⚠️  Depends on #1273
iOS 12 simulators don't run on M1 machines so next easiest way to test is installing iOS 12 simulators on CircleCI
- New `install-and-create-sim` command
- Installs new iOS simulator verion with `xcode-install`
- Creates new simulator with `xcrun`
- New `run-test-ios-12` job
- Passes iOS 12 simulator name into _fastlane_ to `scan` uses newly created sim
- Fixed naming on jobs so all uses consistent stylings
- Split `:test` lane into `:test_ios` and `:test_tvos` and new `run-test-ios-14` job
- `:test` was taking almost 11 minutes which felt really long
- `:test_tvos` now takes 3 minutes
- `:test_ios` with iOS 14 and iOS 14 now each takes 4 minutes
- We were actually using same or more time combining them... Not saving time 🤷‍♂️ 
👇 Link to `run-test-ios-12` since it …

[CircleCI] Test iOS 12 simulators

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Purchases/Purchasing/Purchases.swift
Purchases/SubscriberAttributes/ReservedSubscriberAttributes.swift
Purchases/SubscriberAttributes/SubscriberAttributesManager.swift
PurchasesTests/Mocks/MockSubscriberAttributesManager.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

Fixes [sc-12973]
Noticed when making PurchaseTester for v4 testing tha `setCleverTapID` was missing and was forcing users to manually set `Purchases.shared.setAttributes(["$clevertapId" : clevertapId])`
Some quick copy/paste/edit from other integrations.

Add Purchases.shared.setCleverTapID

---

APITesters/ObjCAPITester/ObjCAPITester/RCIntroEligibilityAPI.m
APITesters/SwiftAPITester/SwiftAPITester/IntroEligibilityAPI.swift
Purchases/Purchasing/IntroEligibility.swift
Purchases/Purchasing/IntroEligibilityCalculator.swift
Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
PurchasesTests/Purchasing/IntroEligibilityCalculatorTests.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift

Fixes [sc-10961]
Intro offer eligibility was only using `eligible` or `ineligible`. This meant that `ineligible` was even being used for products that didn't have an intro offer attached to it. This PR adds `noIntroOfferExists` for those cases.
👟 This also stomps a bug where `productsWithIntroOffers` was filtering out products that didn't have an intro offer. This was bug was introduced in v4.
- Added new `IntroEligibilityStatus. noIntroOfferExists`
- StoreKit 1 (on device)
- Renamed `productsWithIntroOffers` to `productsWithKnownIntroEligibilityStatus` 
- Maps products no intro offer to `noIntroOfferExists`
- Reworked `getIntroEligibility` in [this commit](https://github.com/RevenueCat/purchases-ios/pull/1267/commits/8f24508aad9fedb827075459a44c4f15631860b6) to...
- Step 1: Filter out …

Add noIntroOfferExists as an IntroEligibilityStatus

---

Documentation.docc/RevenueCat.md

[sc-13006]
Updated the Migration Guide section in the main SDK Docs to make it clearer that the migration guide is a separate page, and the topics underneath are unrelated. I also moved it a little bit to make it even clearer. 
| :-: | :-: |
| <img width="804" alt="Screen Shot 2022-02-10 at 1 02 33 PM" src="https://user-images.githubusercontent.com/3922667/153447059-b7c0aa3a-6064-4531-9019-fc0629aac88b.png"> | <img width="818" alt="Screen Shot 2022-02-10 at 1 05 26 PM" src="https://user-images.githubusercontent.com/3922667/153447228-0239444b-589e-41b8-b45a-8a0b3084a320.png"> |
The difference in background color in the screenshots is just because one was taken through Xcode's developer documentation and the other one from the actual docs website, but it's unrelated.

updated migration guide link for clarity

---

Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
PurchasesTests/Mocks/MockProductsManager.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift

Fixes [sc-13232]
`checkEligibility` was returning an empty dictionary if an error occured when using StoreKit2. StoreKit1 returns a dictionary with all product identifiers but with the `.unknown` status
- Replaced empty dictionary with dictionary of all product identifiers (as keys) with `.unknown` status
- Updated tests to include a way to mock an error being thrown for sk2 checking

Fix sk2 checkEligibility to return unknown status when error occurs

---

.circleci/config.yml
fastlane/Fastfile

- Renamed job to `run-test-ios-15` to be explicit and match format from `run-test-ios-14` and `run-test-ios-12`.
- Explicit `SCAN_DEVICE` on `run-test-ios-15` instead of relying on default in Fastlane lane
- Changed Test Plan to `AllTests`, which runs `RevenueCat` tests in parallel (we can run coverage separately once we parse that).

[Circle-CI] Explicit iOS 15 job name

---

APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductDiscountAPI.m
APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
Purchases/Logging/Strings/AttributionStrings.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
PurchasesTests/Mocks/MockStoreProductDiscount.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/ProductRequestDataTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
StoreKitUnitTests/StoreProductTests.swift

Fixes [sc-13183]
Address #1277
`StoreProductDiscount` was missing a reference discount type to underlying StoreKit1 and StoreKit2 discount types
- Added `type: DiscountType` to `StoreProductDiscount`
- `introductory`
- `promotional`

Add type to StoreProductDiscount

---

Documentation.docc/V4_API_Migration_guide.md

From RC feedback: we were referencing types as `SwiftName`/`RCObjectiveCName`, but it seems noisy and unnecessary. 
Objective-C users will be able to click on the reference and see the objc name anyway

removed unnecessary objc references

---

Purchases/Purchasing/Purchases.swift

Cleans up the formatting for a lot of the public methods. 
DocC renders an "Overview" section separately for stuff starting in the second paragraph, which lends to a much cleaner view when you look a class at a glance. 
The first paragraph should always be a high-level summary of the method, and the second can go into more detail.

clean up overview section of some symbols

---

Purchases/Networking/Operations/NetworkOperation.swift

This was just printing "NetworkOperation.Type".
I didn't realize when I had changed the `log` method to `static`.

`NetworkOperation`: fixed logs

---

Documentation.docc/RevenueCat.md

The relative links were leading to the wrong path: `https://github.com/RevenueCat/purchases-ios/blob/main/Documentation.docc/Examples/MagicWeatherSwiftUI`

[Documentation] Fixed MagicWeather links

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Documentation.docc/Purchases.md
Documentation.docc/RevenueCat.md
Documentation.docc/V4_API_Migration_guide.md
Purchases/Misc/Obsoletions.swift
Purchases/Misc/Purchases+async.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/PurchasesOrchestrator.swift
Purchases/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift

Fixes [sc-13355].
Before this PR, users had to call `Purchases.checkPromotionalDiscountEligibility`, and if eligible, then call `Purchases.purchase(product:discount:)` (or their equivalents).
However, as pointed out by @aboedo, this had 2 downsides:
- If `Purchases.checkPromotionalDiscountEligibility` wasn't called, it was possible to call `Purchases.purchase(product:discount:)` with an illegible discount, and it would just fail.
- Doing it right meant the SDK would make 2 redundant API requests to get the signed discount data.
With this change, both issues are resolved.
`checkPromotionalDiscountEligibilityForProductDiscount` is replaced with `getPromotionalOffer`. The returned `PromotionalOffer` already contains the necessary data to make the payment.
I've updated all docs and …

Introduced `PromotionalOffer` to simplify purchasing with `StoreProductDiscount`

---

Purchases/Networking/Caching/CallbackCache.swift
Purchases/Networking/Caching/CustomerInfoCallback.swift
Purchases/Networking/Operations/GetCustomerInfoOperation.swift
Purchases/Networking/SubscribersAPI.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/__Snapshots__/BackendTests/testGetsUpdatedSubscriberInfoAfterPost.1.json

Fixes [sc-12802].
Before this change, the sequence illustrated by the new test `testGetsUpdatedSubscriberInfoAfterPost` (started in #1249, with a few modifications here) would fail:
- GET /subscribers/
- POST /receipts
- GET /subscribers/
#1261 fixed the race condition in the test, making it so that operations are actually run serially.
However, when the first GET request finished, the second one shared the cache key, so it received the (soon to be) outdated `CustomerInfo`.
Unfortunately this fix is isolated for this specific issue, and not a generalized one. A more comprehensive rewrite of `HTTPClient` is needed ([sc-9521]).
I came up with several other alternatives, but what I ended up going with here involves the least amount of moving pieces.
If a `GetCustomerInfoOperation` request is …

`GetCustomerInfoOperation`: improve logic for caching responses

---

APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Purchases/Logging/Strings/StoreKitStrings.swift
Purchases/Purchasing/StoreKitAbstractions/ProductType.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/StoreProductTests.swift
StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
StoreKitUnitTests/UnitTestsConfiguration.storekit

Fixes [sc-13369] and #1295.
The two types provide different levels of information. For SK1, `SubscriptionType` is all the information that we can determine, but for SK2 `ProductType` provides more granularity.

Added `StoreProduct.ProductType` and `StoreProduct.ProductCategory`

---

APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductDiscountAPI.m
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
PurchasesTests/Mocks/MockSKProductDiscount.swift
PurchasesTests/Mocks/MockStoreProductDiscount.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Purchasing/ProductRequestDataTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
StoreKitUnitTests/StoreProductTests.swift

- Needed for hybrid common migration
- https://github.com/RevenueCat/purchases-hybrid-common/pull/113
- Added as `String?` because it never seemed like it was guaranteed anywhere 😬 
- Added `currencyCode` to `StoreProduct`
- Added `currencyCode` to `StoreProductDiscount`
- `SK2StoreProductDiscount` takes `currencyCode` in initializer as currency code can only be fetched from `SK2StoreProduct`

Add currency code to store product and store product discount

---

APITesters/.swiftlint.yml

These aren't really relevant for `APITester`s.
Fixes https://circleci.com/gh/RevenueCat/purchases-ios/17927?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

`APITester`s: disable some `SwiftLint` rules

---

APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductDiscountAPI.m
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
StoreKitUnitTests/StoreProductTests.swift

`NSDecimal` is a fairly useless `struct` in Objective-C, but that's how `Decimal` is bridged from Swift.
Kudos to @aboedo for the idea!
Fixes [sc-13447].

Improved `StoreProduct.price` and `StoreProductDiscount.price` type for Objective-C

---

Purchases/Misc/PlatformInfo.swift
Purchases/Misc/SystemInfo.swift
Purchases/Purchasing/Purchases.swift
PurchasesTests/Attribution/AttributionPosterTests.swift
PurchasesTests/Misc/SystemInfoTests.swift
PurchasesTests/Mocks/MockBackend.swift
PurchasesTests/Mocks/MockIdentityManager.swift
PurchasesTests/Mocks/MockSystemInfo.swift
PurchasesTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Purchasing/IntroEligibilityCalculatorTests.swift
PurchasesTests/Purchasing/OfferingsManagerTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/Purchasing/ReceiptFetcherTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
RevenueCat.xcodeproj/project.pbxproj
StoreKitUnitTests/ProductsManagerTests.swift
StoreKitUnitTests/PurchasesOrchestratorTests.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift

- Needed a way to set `flavor` and `flavorVersion` from hybrid common
- Created a `Purchases.platformInfo` that takes a new `Purchases.PlatformInfo` object 
- Has string value for `flavor` and `version`
- This is the same design as what Android has
- `SystemInfo` ends up taking in the `PlatformInfo` object now
- This allowed the removal of a some safety checks that could throw a system setup error
- Updated a bunch of tests

Allow flavor and flavor version to be set on Purchases.configure

---

Purchases/Misc/DangerousSettings.swift

SPM integration will fail without this. `MagicWeather` for example isn't building.

`DangerousSettings`: added missing `import Foundation`

---

PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

All these tests were eagerly initializing `MockIdentityManger`, which lead to the console flooding with the log `"Identifying App User ID"`, even when these tests weren't running.

Tests: delay `MockIdentityManager` initialization to `setUp`

---

PurchasesTests/Purchasing/CustomerInfoTests.swift

Most of these tests were not testing the real `CustomerInfo.init(data:)`, but instead they were testing a test implementation detail: `CustomerInfo.init(testData:)`.
By leveraging `throws` and `.to(throwError())`, the tests now verify the real implementation and they wouldn't crash if the test fails.
- `setUp` now enforces that the `customerInfo` field is initialized, so tests don't need to force-unwrap it
- Using `==`, `!=`, etc to simplify expectations

`CustomerInfoTests`: modernized implementation and testing real method

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift

[skip-ci] `MagicWeatherSwiftUI`: removed redundant `Package: Identifiable` conformance

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift

[skip-ci] `MagicWeatherSwiftUI`: removed reference to `SubscriptionPeriod.Unit.unknown`

---

APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift

`StoreProductAPI`: removed SwiftLint rule

---

PurchasesTests/Mocks/MockDNSChecker.swift
PurchasesTests/Networking/HTTPClientTests.swift

`OHHTTPStubs`' `stub` response method and `HTTPClient` completions are called in a background thread, so when running `HTTPClientTests` with tsan enabled all of these tests produced warnings.
Example:
- I'm thinking that `HTTPClient` could always call completion blocks in the main thread, which would eliminate a few of these. Unfortunately we can't change `OHHTTPStubs` method. I tried adding an overload that would do it, but the callback needs to run synchronously in order to produce the response.

`HTTPClientTests`: fixed data races

---

Purchases/Purchasing/Offering.swift
PurchasesTests/Purchasing/OfferingsTests.swift

Brought up by @joshdholtz, this shouldn't be a warning.

`Offering`: removed known warning for non-subscription `Package`s

---

BackendIntegrationTests/BackendIntegrationTests.swift

See [**results**](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5a677352c9e77c0001541fa5/6213305f20e8a32d08f17992-0-build/artifacts/scan-test-output/ios/report.junit?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220221T063327Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20220221%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=d9d322f65c40d915bb90ae52706eaa3ad7b14a43120ad68a43c4af59a7662819)

`IntegrationTests`: running on both SK1 and SK2

---

Purchases/Purchasing/EntitlementInfo.swift
Purchases/Purchasing/Offering.swift
Purchases/Purchasing/Package.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
Purchases/Purchasing/StoreKitAbstractions/StoreTransaction.swift

Follow up to #1268.
The `Identifiable` protocol has a default implementation for `AnyObject`:
```swift
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Identifiable where Self : AnyObject {
/// The stable identity of the entity associated with this instance.
public var id: ObjectIdentifier { get }
}
```
Basically the instance pointer becomes the identity by default.
But these types have their own overridden `isEqual` and `hash` implementations, so we want their identities to be defined by their own identifiers.

Provide explicit `Identifiable` implementation

---

BackendIntegrationTests/BackendIntegrationTests.swift

Without this we can get a bunch of different potentially confusing errors, instead of pointing to the source of the problem.

`IntegrationTests`: avoid running tests if `Constants` aren't set

---

Purchases/FoundationExtensions/Array+Extensions.swift
Purchases/Networking/HTTPClient.swift
PurchasesTests/FoundationExtensions/ArrayExtensionsTests.swift
RevenueCat.xcodeproj/project.pbxproj

Follow up to #1303. For [sc-9521] and #695.
Depends on #1313 and #1311.
The internal state is now encapsulated in a `State` `struct`, and all reads and mutations go through the `Atomic` interface, enforcing no possible thread safety issues.
⚠️ This exposed one place (enqueueing requests) that wasn't protected by the internal lock.
- Refactored methods into smaller methods, like `start(request:, serially:)` and `beginNextRequest`.
- Avoiding recursive locking (which would be fine) by avoiding calling `perform` recursively. Instead, the smaller and simpler `start` method is now what gets invoked to start the next request in the queue.

`HTTPClient`: refactored using `Atomic`

---

Purchases/Networking/HTTPClient.swift
Purchases/Networking/Operations/CreateAliasOperation.swift
Purchases/Networking/Operations/GetCustomerInfoOperation.swift
Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
Purchases/Networking/Operations/GetOfferingsOperation.swift
Purchases/Networking/Operations/LogInOperation.swift
Purchases/Networking/Operations/PostAttributionDataOperation.swift
Purchases/Networking/Operations/PostOfferForSigningOperation.swift
Purchases/Networking/Operations/PostReceiptDataOperation.swift
Purchases/Networking/Operations/PostSubscriberAttributesOperation.swift
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift

Depends on #1314.
`false` was only being used in tests, so this simplifies the implementation.

`HTTPClient`: removed `serially` parameter

---

Documentation.docc/V4_API_Migration_guide.md
Purchases/Misc/Obsoletions.swift

Fixes [CF-232] and [CF-231].
[CF-232]: https://revenuecats.atlassian.net/browse/CF-232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CF-231]: https://revenuecats.atlassian.net/browse/CF-231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`StoreTransaction`: added deprecations for version 3.x properties

---

Documentation.docc/V4_API_Migration_guide.md

Resolves issue where images were not showing up on the v4 migration guide
e

Update V4_API_Migration_guide.md image links

---

.swiftlint.yml
BackendIntegrationTests/BackendIntegrationTests.swift
BackendIntegrationTests/Constants.swift

We're also linting tests now: #1124

Enable `SwiftLint` for `BackendIntegrationTests`

---

PurchasesTests/Purchasing/EntitlementInfosTests.swift

I ran into a lot of test crashes during a refactor that would have simply been test failures with this change.

`EntitlementInfosTests`: replaced force-unwrap with `XCTUnwrap`

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Documentation.docc/Purchases.md
Documentation.docc/RevenueCat.md
Purchases/Misc/Purchases+async.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift

For [CF-160](https://revenuecats.atlassian.net/browse/CF-160)
Checking intro eligibility for a single product is a little awkward, since you need to provide an array of `productIdentifiers` and we return a dict with product identifiers and statuses.
Adds a new method (+async) for checking the eligibility of a single `StoreProduct` that returns a single `IntroEligibilityStatus`, using our abstractions to avoid product ID strings and dictionaries.

Adds new method for checking intro eligibility for a single `StoreProduct`

---

Purchases/Identity/CustomerInfoManager.swift
Purchases/Networking/Backend.swift
Purchases/Networking/HTTPClient.swift
Purchases/Networking/HTTPRequest.swift
Purchases/Networking/Operations/CreateAliasOperation.swift
Purchases/Networking/Operations/GetCustomerInfoOperation.swift
Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
Purchases/Networking/Operations/GetOfferingsOperation.swift
Purchases/Networking/Operations/LogInOperation.swift
Purchases/Networking/Operations/PostAttributionDataOperation.swift
Purchases/Networking/Operations/PostOfferForSigningOperation.swift
Purchases/Networking/Operations/PostReceiptDataOperation.swift
Purchases/Networking/Operations/PostSubscriberAttributesOperation.swift
Purchases/Networking/SubscribersAPI.swift
PurchasesTests/Mocks/MockBackend.swift
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Networking/HTTPRequestTests.swift
PurchasesTests/Purchasing/PurchasesTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
RevenueCat.xcodeproj/project.pbxproj

For [CF-195] and #695.
- Moved `HTTPClient.Method` into `HTTPRequest` (now `HTTPRequest.Method`).
- `HTTPClient.Request` now has an `HTTPRequest`, to encapsulate the `method` and `path`.
- `HTTPClient` now has a single `perform` method, since the method is encapsulated in the request.
- Abstracted creation of “relative” path that includes `/v1` to avoid hardcoding that everywhere.
- Represented all paths into `HTTPRequest.Path` to avoid hardcoding paths everywhere.
- Renamed `Backend.getSubscriberData` to `getCustomerInfo`.
- Simplified `MockHTTPClient` by using new `HTTPRequest` type.
- Simplified `BackendTests.MockHTTPClient` by using new `HTTPRequest` and `HTTPRequest.Path` types.
- Simplified `BackendTest`s by comparing `HTTPRequest`s.
- Refactored many tests using `Nimble` and …

Added `HTTPRequest` and `HTTPRequest.Path` to abstract all request information

---

Purchases/Networking/Backend.swift
Purchases/Networking/HTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/ETagManagerTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift

For [CF-195] and #695.
This was duplicated all over the place, now only defined in one place.
[CF-195]: https://revenuecats.atlassian.net/browse/CF-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extracted authorization header creation

---

Purchases/Networking/ETagManager.swift
Purchases/Networking/HTTPClient.swift
Purchases/Networking/HTTPStatusCode.swift
Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
Purchases/Networking/Operations/GetOfferingsOperation.swift
Purchases/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
Purchases/Networking/Operations/Handling/NoContentResponseHandler.swift
Purchases/Networking/Operations/Handling/SubscriberAttributeHandler.swift
Purchases/Networking/Operations/Handling/UserInfoAttributeParser.swift
Purchases/Networking/Operations/LogInOperation.swift
Purchases/Networking/Operations/PostOfferForSigningOperation.swift
PurchasesTests/Networking/ETagManagerTests.swift
RevenueCat.xcodeproj/project.pbxproj

For [CF-195] and #695.
An `enum`eration should be singular, as each value represents just one code.
Just a preliminary change before a larger refactor.
[CF-195]: https://revenuecats.atlassian.net/browse/CF-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Renamed `HTTPStatusCodes` to `HTTPStatusCode`

---

Purchases/Logging/Strings/BackendErrorStrings.swift
Purchases/Logging/Strings/NetworkStrings.swift
Purchases/Networking/ETagAndResponseWrapper.swift
Purchases/Networking/ETagManager.swift
Purchases/Networking/HTTPClient.swift
Purchases/Networking/HTTPResponse.swift
Purchases/Networking/HTTPStatusCode.swift
Purchases/Networking/IntroEligibilityResponse.swift
Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
Purchases/Networking/Operations/GetOfferingsOperation.swift
Purchases/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
Purchases/Networking/Operations/Handling/NoContentResponseHandler.swift
Purchases/Networking/Operations/Handling/SubscriberAttributeHandler.swift
Purchases/Networking/Operations/Handling/UserInfoAttributeParser.swift
Purchases/Networking/Operations/LogInOperation.swift
Purchases/Networking/Operations/PostOfferForSigningOperation.swift
PurchasesTests/Mocks/MockETagManager.swift
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/ETagManagerTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/Networking/HTTPStatusCodeTests.swift
PurchasesTests/SubscriberAttributes/AttributionDataMigratorTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
RevenueCat.xcodeproj/project.pbxproj

For [CF-195] and #695.
- Abstracted duplicated logic for checking status codes into tested `HTTPSTatusCode` properties
- Reuse `HTTPClient.Completion` typealias
- Using `XCTUnwrap` in a few more tests
[CF-195]: https://revenuecats.atlassian.net/browse/CF-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Using `HTTPStatusCode` for status codes everywhere

---

Purchases/Networking/Operations/NetworkOperation.swift
PurchasesTests/Networking/BackendTests.swift

This was a regression that came with the move to `Operation` subclasses. Prior to that, `HTTPClient` was only used from the main thread.
This meant that if the snapshot tests failed, the test runner would crash because `XCTest` doesn't allow adding attachments from outside the main thread.
Additionally, `MockHTTPClient` wasn't thread safe, so without this, it could have lead to race conditions.

`BackendTests`: fixed `MockHTTPClient` thread safety and `SnapshotTesting` usage

---

PurchasesTests/Purchasing/ProductRequestDataExtensions.swift
PurchasesTests/Purchasing/ProductRequestDataTests.swift
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsCurrencyCodeCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsDiscountsCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsIntroDurationCorrectlyForFreeTrial.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsIntroDurationCorrectlyForIntroPrice.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsIntroPriceCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsNormalDurationCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsPaymentModeCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsPaymentModeCorrectly.2.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsPaymentModeCorrectly.3.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsPaymentModeCorrectly.4.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsPriceCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsProductIdentifierCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryConvertsSubscriptionGroupCorrectly.1.json
PurchasesTests/Purchasing/__Snapshots__/ProductRequestDataTests/testAsDictionaryDoesntAddIntroDurationIfDurationTypeUnknown.1.json
PurchasesTests/TestHelpers/SnapshotTesting+Extensions.swift
RevenueCat.xcodeproj/project.pbxproj

Future refactor is removing manual JSON encoding, and this is easier to maintain without needing to hardcode key names.

`ProductRequestData`: changed tests from manual dictionary comparisons to snapshot testing

---

PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/HTTPRequestTests.swift
PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostReceiptWithSubscriberAttributesPassesErrorsToCallbackIfStatusCodeIsError.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostReceiptWithSubscriberAttributesPassesErrorsToCallbackIfStatusCodeIsSuccess.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostReceiptWithSubscriberAttributesReturnsBadJson.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostReceiptWithSubscriberAttributesSendsThemCorrectly.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostReceiptWithoutSubscriberAttributesSkipsThem.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesCallsCompletionInNetworkErrorCase.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesCallsCompletionInSuccessCase.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesCallsCompletionWithErrorInBackendErrorCase.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesCallsCompletionWithErrorInBadRequestCase.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesCallsCompletionWithErrorInNotFoundCase.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesSendsAttributesErrorsIfAny.1.json
PurchasesTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/testPostSubscriberAttributesSendsRightParameters.1.json
RevenueCat.xcodeproj/project.pbxproj

For [CF-195](https://revenuecats.atlassian.net/browse/CF-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ) and https://github.com/RevenueCat/purchases-ios/issues/695.
~~Depends on #1357.~~
A future PR is replacing `PostSubscriberAttributesOperation` manual encoding with `Encodable`, so this supports this.
- Added `assertSnapshot` to `MockHTTPClient` like `BackendTests.MockHTTPClient`.
- No longer using `Date()` to make sure times don't change every time the test runs.
- Added `SnapshotTesting` to `StoreKitUnitTests` since `MockHTTPClient` is also used there.
- I've made a mental note to combine both `MockHTTPClient`, since they've basically converged into the same implementation.

`BackendSubscriberAttributesTests`: replaced manual request body checking with snapshot testing

---

Purchases/Attribution/AttributionNetwork.swift
Purchases/Logging/Strings/NetworkStrings.swift
Purchases/Networking/HTTPClient.swift
Purchases/Networking/HTTPRequest.swift
Purchases/Networking/Operations/CreateAliasOperation.swift
Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
Purchases/Networking/Operations/Handling/SubscriberAttributesMarshaller.swift
Purchases/Networking/Operations/LogInOperation.swift
Purchases/Networking/Operations/PostAttributionDataOperation.swift
Purchases/Networking/Operations/PostOfferForSigningOperation.swift
Purchases/Networking/Operations/PostReceiptDataOperation.swift
Purchases/Networking/Operations/PostSubscriberAttributesOperation.swift
Purchases/Networking/SubscribersAPI.swift
PurchasesTests/Mocks/MockHTTPClient.swift
PurchasesTests/Networking/BackendTests.swift
PurchasesTests/Networking/HTTPClientTests.swift
PurchasesTests/TestHelpers/SnapshotTesting+Extensions.swift
RevenueCat.xcodeproj/project.pbxproj

Finishes [CF-195] and #695.
All the prior PRs have been building up to being able to do this, and with 100% confidence thanks to snapshot tests.
[CF-195]: https://revenuecats.atlassian.net/browse/CF-195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`HTTPRequest.Method.post`: replaced all request bodies manual encoding with `Encodable`

---

Purchases/Error Handling/StoreKitError+Extensions.swift

Fixes [CF-321]
[CF-321]: https://revenuecats.atlassian.net/browse/CF-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Handle new `StoreKitError.notEntitled`

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
BackendIntegrationTests/BackendIntegrationTests.swift
Documentation.docc/Purchases.md
Documentation.docc/RevenueCat.md
Purchases/Misc/Deprecations.swift
Purchases/Misc/Purchases+async.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
PurchasesTests/Purchasing/PurchasesTests.swift
RevenueCat.xcodeproj/project.pbxproj
docs/Deprecations.md

Fixes [CF-287]
Now we have `checkTrialOrIntroDiscountEligibility(product:)` and `checkTrialOrIntroDiscountEligibility(productIdentifiers:)`
[CF-287]: https://revenuecats.atlassian.net/browse/CF-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added explicit parameter name to `checkTrialOrIntroDiscountEligibility` for consistency

---

Purchases/FoundationExtensions/Result+Extensions.swift
Purchases/Misc/Purchases+async.swift
PurchasesTests/FoundationExtensions/ResultExtensionsTests.swift
RevenueCat.xcodeproj/project.pbxproj

New `Result` initializer to simplify conversions from old completion blocks

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesErrorCodeAPI.m
APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift
Purchases/Error Handling/ErrorCode.swift
Purchases/Error Handling/ErrorUtils.swift
Purchases/Error Handling/StoreKitError+Extensions.swift
PurchasesTests/Purchasing/ErrorCodeTests.swift

Unfortunately Swift still doesn't have typed errors (sad face).
Turns out that `Product.purchase` may throw either a `Product.PurchaseError` or `StoreKitError`, but we were only handling the latter.
Additionally, the call to `.unknownError()` wasn't adding the error, so we were losing all the context of the underlying error.
There's already a Jira for adding test coverage here: [CF-323]
[CF-323]: https://revenuecats.atlassian.net/browse/CF-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SK2 Purchases: handle `Product.PurchaseError` in `ErrorUtils.purchasesError`

---

PurchasesTests/Networking/DNSCheckerTests.swift

I improved this on #1259, but I think it doesn't make sense to have a test that always fails when working on the codebase while not online. This skips the test instead.

`DNSCheckerTests.testResolvedHost`: skip test if offline

---

Purchases/Purchasing/TransactionsManager.swift

This was currently using SK2 without it being enabled.

`TransactionsManager`: added note about using SK2 implementation

---

Purchases/Networking/HTTPClient.swift

This wasn't used anywhere, so it makes the code safer by making sure response bodies aren't mutable references.
Note that this will only be short-lived however, since all response deserialization will be done using `Decodable`.

`HTTPClient`: removed `JSONSerialization.ReadingOptions.mutableContainers`

---

Purchases/Logging/Strings/NetworkStrings.swift
Purchases/Networking/HTTPClient.swift

I was looking at these while debugging and getting confused because of the message "completed with status", followed by something that wasn't a status.
The new format is consistent across "started" and "completed" messages, and it's easier to read:
> 2022-03-08 09:51:04.633994-0800 BackendIntegrationTestsHostApp[74639:8672511] [Purchases] - DEBUG: ℹ️ API request started: POST /v1/receipts
> 2022-03-08 09:51:05.037849-0800 BackendIntegrationTestsHostApp[74639:8672508] [Purchases] - DEBUG: ℹ️ API request completed: POST /v1/receipts 200

`HTTPClient`: improved debug logs by making them consistent

---

Purchases/FoundationExtensions/UIApplication+RCExtensions.swift
StoreKitUnitTests/BeginRefundRequestHelperTests.swift

These have began failing on #1387, even though that doesn't change anything that should affect the `UIWindowScene` or anything related. This could have been a regression from Xcode 13.3.
When the test fails (which isn't always), the scene isn't yet `.foregroundActive` . To workaround that, this defaults to any scene, *though only when running tests, on debug, and on the simulator*. So nothing is changed in release or device builds.
This also has a small refactor on `BeginRefundRequestHelperTests` to move the test data below and make the tests more readable.
Additionally, the `MockSK2BeginRefundRequestHelper` is recreated for every test. I thought initially that this is what was making the test fail, as the mock expectations and state was being shared across tests. It's not, but now that …

Fixed sporadic `BeginRefundRequestHelperTests` failures

---

APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Documentation.docc/Purchases.md
Documentation.docc/RevenueCat.md
Purchases/Purchasing/Purchases.swift
Purchases/SubscriberAttributes/ReservedSubscriberAttributes.swift
Purchases/SubscriberAttributes/SubscriberAttributesManager.swift
PurchasesTests/Mocks/MockSubscriberAttributesManager.swift
PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

[CF-346](https://revenuecats.atlassian.net/browse/CF-346)
We now support setting the `$mixpanelDistinctId` subscriber attribute for the RevenueCat Mixpanel integration to use for an event's identity instead of the last seen alias: https://docs.revenuecat.com/docs/mixpanel 
Adds a new convenience method for setting the Mixpanel reserved attribute: `$mixpanelDistinctId`

Adds new convenience method for setting Mixpanel Distinct ID attribute

---

Purchases/CodableExtensions/EntitlementProductData+Extensions.swift
Purchases/FoundationExtensions/JSONDecoder+Extensions.swift

Fixes https://github.com/RevenueCat/purchases-ios/issues/1392
I am not sure about the fix, so open to suggestions. For now I made the logging optional, but maybe we want to not log anytime there's a `defaultValue`.
[CF-366]
[CF-366]: https://revenuecats.atlassian.net/browse/CF-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Preventing logging if ownershipType key is missing

---

APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Documentation.docc/Purchases.md
Documentation.docc/RevenueCat.md
Documentation.docc/V4_API_Migration_guide.md
Purchases/Misc/Deprecations.swift
Purchases/Misc/Obsoletions.swift
Purchases/Misc/Purchases+async.swift
Purchases/Purchasing/Purchases.swift
Purchases/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift

For [CF-337](https://revenuecats.atlassian.net/browse/CF-337)
Most async / await APIs omit the `get` that we have in the completion block counterparts, but for `getEligiblePromotionalOffers` and `getPromotionalOffer`, we kept the get part in the async / await version.
This goes against Apple’s recommendations for naming, which is to omit the `get` for async methods.
Renames the `getEligiblePromotionalOffers` methods to `eligiblePromotionalOffers` and renames `getPromotionalOffer` to `promotionalOffer`

Rename async promotional offer methods

---

Purchases/Networking/HTTPClient.swift
Purchases/Networking/HTTPResponse.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

Fixes https://community.revenuecat.com/sdks-51/error-fetching-offerings-but-only-from-second-run-onwards-1405

`HTTPClient`: correctly return cached data for 304 responses

---

Documentation.docc/V4_API_Migration_guide.md

Just a tiny fix for a typo I came across while migrating

Fix typo in v4 migration guide

---

Purchases/Networking/Backend.swift
Purchases/Networking/SubscribersAPI.swift
Purchases/Purchasing/Purchases.swift
Purchases/SubscriberAttributes/ReservedSubscriberAttributes.swift
RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift

Part 2 of 3 
breaking apart my previous PR (https://github.com/RevenueCat/purchases-ios/pull/1400)
This is for [CF-281]
[CF-281]: https://revenuecats.atlassian.net/browse/CF-281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Route the AttributionFetcher and DateProvider to the SubscriptionAPI

---

Purchases/Logging/Strings/OfferingStrings.swift

This issue was opened https://github.com/RevenueCat/purchases-ios/issues/1395 with valid feedback.
Offerings is optional and the log message makes it sound like there's an error in the configuration. I figured the easiest would be to update the log so it's less alarming but still provides information for whoever is actually having issues.

Updates log message for unconfigured offerings

---

Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Purchasing/StoreKitWrapperTests.swift

Looks like `SwiftLint` v0.47.0 added this new rule.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/5838/workflows/65f92776-8d3e-4344-bd4f-f90c1a646a25/jobs/20591

Fixed lint warnings

---

Documentation.docc/V4_API_Migration_guide.md

fixed a couple of broken references in the v4 api migration guide

fix broken references in migration guide

---

.swiftlint.yml
Package.swift

There was an outdated exclusion in Package.swift, left over from [this PR](https://github.com/RevenueCat/purchases-ios/pull/1416)

fix: invalid exclude in Package.swift

---

.gitignore
.swiftlint.yml
Package.swift
fastlane/Fastfile
fastlane/README.md

Part 1 of a series of PRs to break #1368 into actually manageable pieces. 
This adds two lanes, one to preview the docs, and another one to compile them into files, both as a static site. 
We already have lanes in place for DocC docs, but for a dynamic website, so the difference here is that using the new setup we'll have more flexibility when deploying, for example, to github pages. 
I didn't remove the old lanes yet because we'll still need them until a few more cleanups are done w/regards to file structure (PRs incoming).

Static DocC docs part 1: lanes

---

Tests/UnitTests/Mocks/MockUserDefaults.swift

Right now the original `UserDefaults.synchronize` is being called which isn't great.

`MockUserDefaults`: override `synchronize`

---

Sources/FoundationExtensions/Data+Extensions.swift

I noticed that the existing implementation was creating many copies of the string as it grows, which isn't very efficient.
The new implementation allocates the required size initially and writes to the same buffer inside the loop.

`NSData.asString()`: optimized string creation

---

Sources/Misc/OperationDispatcher.swift
Sources/Misc/SystemInfo.swift
Sources/Purchasing/Purchases.swift

This solves a race condition that could cause operations to run out of order (discovered in #1441).
`Purchases.configure` triggers a `getCustomerInfo` call, which relies on `isApplicationBackgrounded`.
The previous implementation always had a runloop "jump", meaning that sometimes a subsequent request might happen out of order.
By using `OperationDispatcher.dispatchOnMainThread`, the jump is avoided if we're already in the main thread, meaning we run everything deterministically in order.

Changed `SystemInfo.isApplicationBackgrounded` to use `OperationDispatcher`

---

Sources/Error Handling/BackendErrorCode.swift

I was debugging this, so I guess it makes sense to at least add it to the `enum` even if we don't do anything special with it.

Added `BackendErrorCode.subscriptionNotFoundForCustomer`

---

Sources/FoundationExtensions/JSONDecoder+Extensions.swift
Sources/Networking/ETagManager.swift
Sources/Networking/HTTPClient.swift
Sources/Networking/HTTPResponse.swift
Sources/Networking/IntroEligibilityResponse.swift
Sources/Networking/Operations/CreateAliasOperation.swift
Sources/Networking/Operations/GetCustomerInfoOperation.swift
Sources/Networking/Operations/GetIntroEligibilityOperation.swift
Sources/Networking/Operations/GetOfferingsOperation.swift
Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
Sources/Networking/Operations/Handling/NoContentResponseHandler.swift
Sources/Networking/Operations/Handling/SubscriberAttributeHandler.swift
Sources/Networking/Operations/Handling/UserInfoAttributeParser.swift
Sources/Networking/Operations/LogInOperation.swift
Sources/Networking/Operations/PostAttributionDataOperation.swift
Sources/Networking/Operations/PostOfferForSigningOperation.swift
Sources/Networking/Operations/PostReceiptDataOperation.swift
Sources/Networking/Operations/PostSubscriberAttributesOperation.swift
Tests/UnitTests/Mocks/MockETagManager.swift
Tests/UnitTests/Mocks/MockHTTPClient.swift
Tests/UnitTests/Networking/Backend/BackendCreateAliasTests.swift
Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift
Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
Tests/UnitTests/Networking/Backend/BackendLoginTests.swift
Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift
Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTestBase.swift
Tests/UnitTests/Networking/ETagManagerTests.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTestBase.swift

For #695.
The biggest change is that this code at the beginning of `HTTPClient.handle` is now gone:
```swift
var statusCode: HTTPStatusCode = .networkConnectTimeoutError
var jsonObject: [String: Any]?
var httpResponse: HTTPResponse? = HTTPResponse(statusCode: statusCode, jsonObject: jsonObject)
var receivedJSONError: Error?
```
It was hard to trace which paths modified these default values. The new implementation has a mostly linear path (part of it abstracted in smaller methods now) and doesn’t have mutable values.
This is the new `handle` implementation:
```swift
func handle(urlResponse: URLResponse?,
request: Request,
urlRequest: URLRequest,
data: Data?,
error networkError: Error?) {
let (response, shouldRetry) = self.parse(
urlResponse: urlResponse,
request: request,
urlRequest: …
```

Simplified `HTTPClient.Completion` and refactored response handling implementation

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Networking/HTTPResponse.swift
Sources/Networking/HTTPStatusCode.swift
Sources/Networking/Operations/Handling/UserInfoAttributeParser.swift
Tests/UnitTests/Networking/HTTPResponseTests.swift
Tests/UnitTests/Networking/HTTPStatusCodeTests.swift

This is duplicated in most of the `NetworkOperation`s. This new shared implementation will be used by `HTTPClient`.
For #695.
See #1429 for how this is used.

Created `ErrorResponse` to abstract error deserialization

---

Sources/FoundationExtensions/JSONDecoder+Extensions.swift
Sources/Purchasing/EntitlementInfo.swift

Follow up to #1429. The `decode` methods no longer mutate the underlying `JSONDecoder`, and instead the codebase uses a shared `defaultJSONDecoder` with the correct configuration.

Simplified `JSONDecoder.decode` decoding strategies

---

Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcodeproj/project.pbxproj

Not sure why this worked when I added it in #1218, but this `alert` initializer is now only available on iOS 15.0

`MagicWeatherSwiftUI`: increased deployment target to iOS 15.0

---

Sources/Error Handling/ErrorUtils.swift
Sources/Error Handling/SKError+Extensions.swift
Sources/Error Handling/StoreKitError+Extensions.swift

Our mapping between SK1/SK2 errors and `ErrorCode` was inconsistent, so that test was only passing for SK2.
This PR addresses that. It also makes use of `ErrorUtils` methods to ensure that the underlying error is added to the returned errors.

`SKError.toPurchasesError`: fixed mapping to make it consistent with `StoreKitError.toPurchasesError`

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

I was trying to add an automated test to cover #1445, but unfortunately `SKTestSession.failureError` only forwards a limited set of errors.
At least this test verifies that purchase errors are reported correctly.

`BackendIntegrationTests`: added test for failed purchase

---

RevenueCat.xcodeproj/project.pbxproj
Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift
Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift
Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
Tests/UnitTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift

This PR fixes local receipt parsing for StoreKitTest receipts. 
So far this only includes a single test, next PR is going to add more tests for different StoreKitTest receipts, and will also clean up the test code to make it a lot nicer. 
So this is part 1, but it does the main thing, which is to make it actually compatible. 
Main changes: 
These receipts use indefinite-length containers, so our calculation for the container length would break, because it would be understood to be zero. 
This first (naive) implementation assumes the indefinite-length containers to be as big as the entire payload, which is incorrect, but works in practice, so it's a decent temporary patch. 
The [`originalAppVersion`](https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Ch …

Fix: local receipt parsing for StoreKitTest - part 1

---

Sources/Error Handling/SKError+Extensions.swift
Sources/Purchasing/PurchasesOrchestrator.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift

Fixes #1445.
Similar solution to #965, this attempts to introspect the unknown `SKError` to detect if it actually corresponds to a failed purchase.

Added workaround for StoreKit 1 incorrectly reporting purchase cancellations

---

Sources/LocalReceiptParsing/BasicTypes/ASN1Container.swift
Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift
Sources/LocalReceiptParsing/ReceiptParser.swift
Tests/UnitTests/TestHelpers/ContainerFactory.swift

Follow-up to #1446. 
This one fixes the length calculation logic for indefinite-length receipts. 
In this type of receipt, the length bytes are set to a value of zero, and you find the actual length by finding a container with `objectIdentifier` = `endOfContent` (two bytes of 0x00 value). 
So the new logic for indefinite-length containers parses the inner containers until an endOfContent container is found, then sums up the length of all of them and uses that value. 
Definite-length receipts don't actually have `endOfContent` bytes, which makes the parsing logic slightly more complex, sadly.

Fix: ASN1 length calculation for indefinite-length

---

Sources/Purchasing/ReceiptFetcher.swift
Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift

Yet another follow-up for storekit parsing in #1446 
This one cleans up the test code. The final follow-up will include more tests for the actual receipt using this as a base.

Clean storekit receipt parsing tests

---

fastlane/Fastfile

Fixes a missing step in `fastlane bump`: 
After updating changelog.latest.md, the changes from that file aren't pushed to the master changelog. 
This adds that step

fastlane bump: update master changelog

---

Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md

For [CF-476](https://revenuecats.atlassian.net/browse/CF-496)
We support using SK2 (beta, experimentally), so we should include it in our DocC docs.
Adds the `configure` option with `useStoreKit2IfAvailable` to DocC docs

Add SK2 configure parameter to DocC

---

Sources/Purchasing/Purchases.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

The class never uses it directly, just through `TrialOrIntroPriceEligibilityChecker`.

`Purchases`: removed `IntroEligibilityCalculator`

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/PurchasesDelegateHandler.swift

Also added example link from @vegaro's post: https://stackoverflow.com/a/68386112/401024
For [CF-464]
[CF-464]: https://revenuecats.atlassian.net/browse/CF-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`MagicWeatherSwiftUI`: implemented `purchases(:shouldPurchasePromoProduct:defermentBlock:)`

---

Sources/Networking/ETagManager.swift
Tests/UnitTests/Networking/ETagManagerTests.swift

`ETagManager`: added test to verify that reading cached data in old format fails gracefully

---

Sources/Purchasing/Purchases.swift
Sources/SubscriberAttributes/SubscriberAttributesManager.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Attribution/AttributionPosterTests.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/6125/workflows/d418661d-752d-403e-84d5-e7fdc32dad88/jobs/22409/tests
The tests introduced in #1441 exposed a potential race condition in the SDK.
On SDK initialization, `Purchases` calls `updateAllCaches`, which in turn makes `CustomerInfoManager` and `OfferingsManager` update its internal caches. Specifically, `CustomerInfoManager` makes a `getCustomerInfo` request ensuring that the backend knows about the current `appUserID`.
These 2 calls are made in the `OperationDispatcher.workerQueue`, so they're ensured proper ordering.
However, `SubscriberAttributesManager` enqueues the requests to post new attributes synchronously and outside this worker thread. If this happens _before_ `CustomerInfoManager` has had a chance …

`SubscriberAttributesManager`: fixed potential race condition

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Attribution/AttributionPoster.swift
Sources/Identity/IdentityManager.swift
Sources/Purchasing/Purchases.swift
Sources/Purchasing/PurchasesOrchestrator.swift
Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
Sources/Support/BeginRefundRequestHelper.swift
Sources/Support/ManageSubscriptionsHelper.swift
Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Tests/UnitTests/Attribution/AttributionPosterTests.swift
Tests/UnitTests/Mocks/MockCurrentUserProvider.swift
Tests/UnitTests/Mocks/MockIdentityManager.swift
Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

A lot of our classes depended on the mutable `IdentityManager`, when in reality they only needed a read-only `currentAppUserID`.
This PR changes the requirement, with the following advantages:
- Ensure all these classes (`AttributionPoster`, `PurchasesOrchestrator`, `TrialOrIntroPriceEligibiltyChecker`, `BeginRefundRequestHelper`, `ManageSubscriptionsHelper`) cannot logIn / logOut, only read the current user
- Simplify tests by only requiring a smaller type
- Simplifying instantiation of these types outside the normal `Purchases` initialization.
I've also created `MockCurrentUserProvider`, but changed the existing `MockIdentityManager` so that calls to `logIn`/`logOut` just fail. These aren't mocked, and they wouldn't have an impact on the mocked readable values, so calling them is most …

Extracted `CurrentUserProvider` protocol to simplify dependency injection

---

.circleci/config.yml

Updates all CircleCI jobs to use Xcode 13.3.0. 
This also fixes the `docs_deploy` job, which needs 13.3.0 for static page generation with DocC.

update all jobs to use Xcode 13.3.0

---

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift

Hoping that this makes debugging flaky tests easier to find the root of the issues in CI.
The default value for this is `true`.

Integration Tests: don't continue after failure

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

Hoping this will make debugging flaky CI failures easier.
Example failure that's hard to debug:
>  ✖ testPurchaseMadeBeforeLogInWithExistingUserIsNotRetainedUnlessRestoreCalled, failed - expected to equal <1>, got <0>
- Added `file`/`line` information so the failure comes from the actual test line
- Added explicit descriptions to failures

Integration Tests: improved verification methods

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Misc/StoreKit2Setting.swift
Sources/Misc/SystemInfo.swift
Sources/Networking/HTTPClient.swift
Sources/Purchasing/ProductsManager.swift
Sources/Purchasing/Purchases.swift
Sources/Purchasing/TransactionsManager.swift
Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
Tests/StoreKitUnitTests/ProductsManagerTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/TransactionsManagerSK1Tests.swift
Tests/StoreKitUnitTests/TransactionsManagerSK2Tests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Tests/UnitTests/Misc/SystemInfoTests.swift
Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

This adds a third case `disabled` that allows tests to explicitly disable StoreKit 2.
Some types, like `TrialOrIntroPriceEligibilityChecker` and `TransactionsManager` always used SK2 because the implementation was better. But this meant that tests couldn't explicitly disable it (other than calling the internal methods directly).
This allows #1464 to be a lot simpler but being able to use the public `Purchases` methods, but forcing the implementation to use SK1.
Note that this is purely an implementation detail. `StoreKit2Setting` is `internal`, and the public API still only exposes the same boolean.
This basically solves [CF-497] too, since those tests will now force `TrialOrIntroPriceEligibilityChecker` to run the SK1 implementation.
[CF-497]: …

Added `StoreKit2Setting` to replace `useStoreKit2IfAvailable`

---

Sources/Purchasing/PurchasesOrchestrator.swift

These calls were only in the original SK1 purchase methods, but we never logged purchasing SK2 products.
I've moved the calls to the parent `purchase` method before we split by SK1/SK2 to fix this.

`PurchasesOrchestrator`: added missing `Logger.purchase` calls for SK2

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit

Finishes [CF-497].
Depends on ~~#1462~~ and #1467.
This adds a lot more tests for `TrialOrIntroPriceEligibilityChecker` that run in both SK1 and SK2 thanks to #1467.
[CF-497]: https://revenuecats.atlassian.net/browse/CF-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`StoreKitIntegrationTests`: added more tests for `TrialOrIntroPriceEligibilityChecker`

---

Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit

Fixes the noisy console warning:
> Empty Product titles are not supported. Found in product with identifier: com.revenuecat.annual_39.99.2_week_intro

Integration Tests: localized test IAP to avoid warnings

---

Sources/Logging/Logger.swift
Sources/Logging/Strings/PurchaseStrings.swift
Sources/Purchasing/PurchasesOrchestrator.swift

Follow up to #1489
Examples:
> 2022-04-11 14:36:08.815265-0700 UnitTestsHostApp[58688:3901390] [Purchases] - INFO: 😻💰 Purchased product - 'com.revenuecat.monthly_4.99.1_week_intro'
> 2022-04-11 14:37:31.793204-0700 BackendIntegrationTestsHostApp[58835:3904176] [Purchases] - ERROR: 💰 Product purchase for 'com.revenuecat.monthly_4.99.1_week_intro' failed with error: Error Domain=RevenueCat.ErrorCode Code=34 "The information associated with this PromotionalOffer is not valid.

`PurchasesOrchestrator`: added logs for completed and failed purchases

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Error Handling/ErrorUtils.swift
Sources/Error Handling/SKError+Extensions.swift
Sources/Error Handling/StoreKitError+Extensions.swift
Tests/UnitTests/StoreKitExtensions/PurchaseErrorTests.swift
Tests/UnitTests/StoreKitExtensions/SKErrorTests.swift
Tests/UnitTests/StoreKitExtensions/StoreKitErrorTests.swift

Follow up to #1437.
Fixes [CF-323]
[CF-323]: https://revenuecats.atlassian.net/browse/CF-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`SKError`, `StoreKitError`, and `Product.PurchaseError` conform to `ErrorCodeConvertible` + tests

---

Sources/Error Handling/ErrorDetails.swift
Sources/Error Handling/ErrorUtils.swift
Sources/FoundationExtensions/Error+Extensions.swift
Sources/Networking/Backend.swift
Sources/Networking/HTTPResponse.swift
Tests/UnitTests/FoundationExtensions/NSError+RCExtensionsTests.swift
Tests/UnitTests/Networking/BaseErrorTests.swift
Tests/UnitTests/Networking/HTTPResponseTests.swift
Tests/UnitTests/Networking/NetworkErrorTests.swift
Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTestBase.swift

This could help debug these errors.
Thanks to the error refactor this only had to be put in one place.

`NetworkError.errorResponse`: added status code to `userInfo`

---

Tests/UnitTests/Networking/BackendErrorTests.swift

The race condition fixed #1479 is luckily not a big deal because posting the attributes would have been retried.
This test ensures that behavior in a concise way.

`BackendErrorTests`: added explicit test for subscriber not found errors

---

.circleci/config.yml

Will be useful to validate the tests after [CF-547].
Also considering that we support it, I think it's useful to run tests there too.
[CF-547]: https://revenuecats.atlassian.net/browse/CF-547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CircleCI: added iOS 13 job

---

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

This is probably a leftover from before integration tests got changed to async.
`Purchases` initialization can fetch an updated `CustomerInfo`, so assuming this will be 1 is a race condition waiting to happen, because there are potentially multiple customer info requests happening.
Also, SDK initialization begins with an initial request to offerings, which results in a get-create of the initial anonymous user. To avoid race conditions with when this request finishes and make all tests deterministic, integration tests now wait for the initial get offerings to finish
- Removed `waitUntilCustomerInfoIsUpdated`
- `verifyEntitlementWentThrough` now calls `verifyEntitlementWentThrough` to verify the `CustomerInfo` has the correct entitlement
- No longer checking the …

`StoreKitIntegrationTests`: removed incorrect `waitUntilCustomerInfoIsUpdated` and fixed race condition

---

Tests/StoreKitUnitTests/UnitTestsConfiguration.storekit
Tests/UnitTests/Mocks/MockSK1Product.swift

Same as #1494 but for Unit Tests.
This makes the logs during tests a lot less noisy.

Unit Tests: localized test IAP to avoid warnings

---

fastlane/Fastfile

Might help with flaky tests too.

Integration Tests: added `number_of_retries` parameter to match iOS tests

---

.circleci/config.yml

This fixes the following error:
> [12:36:21]: No simulators found that are equal to the version of specifier (15.2) and greater than or equal to the version of deployment target (0)
> [12:36:21]: Ignoring 'iPhone 12 (15.2)', couldn’t find matching simulator
> [12:36:21]: Couldn't find any matching simulators for '["iPhone 12 (15.2)"]' - falling back to default simulator
> [12:36:21]: Found simulator "iPhone 8 (14.5)"
Neither iOS 15 nor Integration Tests were actually running on iOS 15, probably since we switched to Xcode 13.3.

`CircleCI`: fixed iOS 15 simulator versions

---

Tests/UnitTests/Misc/XCTestCase+Extensions.swift

`XCTAsyncUnwrap`: fixed implementation by passing parameters to `XCTUnwrap`

---

.circleci/config.yml

Follow up to #1503.
Fixes the following error:
> [12:36:18]: No simulators found that are equal to the version of specifier (13.7) and greater than or equal to the version of deployment target (0)
> [12:36:18]: Ignoring 'iPhone 8 (13.7)', couldn’t find matching simulator
> [12:36:18]: Couldn't find any matching simulators for '["iPhone 8 (13.7)"]' - falling back to default simulator
> [12:36:18]: Found simulator "iPhone 8 (14.5)"
The tests weren't actually running on iOS 13.x.

`CircleCI`: install iOS 13 simulator to fix iOS 13 tests

---

Sources/Purchasing/PurchasesOrchestrator.swift
Tests/StoreKitUnitTests/StoreTransactionTests.swift
Tests/UnitTests/Mocks/MockTransaction.swift

Clears a bunch of these errors:
> 2022-04-14 15:57:25.051397+0200 xctest[86968:5767146] [Purchases] - WARN: 🍎‼️ There is a problem with the SKPaymentTransaction missing a transaction date - this is an issue with the App Store.
> 2022-04-14 15:57:25.051530+0200 xctest[86968:5767146] [Purchases] - WARN: 🍎‼️ There is a problem with the SKPaymentTransaction missing a transaction identifier - this is an issue with the App Store.

Logging: removed duplicate log and cleared some warning noise

---

Sources/Error Handling/BackendError.swift
Sources/Error Handling/ErrorCode.swift
Sources/Error Handling/ErrorUtils.swift
Sources/Networking/NetworkError.swift

- Removed default conformance of `ErrorCodeConvertible` to `DescribableError`. This implementation called `asPurchasesError`, which created the error through `ErrorUtils`, leading to calling `logErrorIfNeeded` more than once.
- `logErrorIfNeeded` now logs the underlying error if it's present.
Example:
> 2022-04-14 16:05:15.557712+0200 xctest[88464:5783875] [Purchases] - ERROR: 🍎‼️ The product is not available for purchase.
> 2022-04-14 16:05:15.558381+0200 xctest[88464:5783875] [Purchases] - ERROR: 😿‼️ The operation couldn’t be completed. (SKErrorDomain error 5.)

`ErrorUtils`: fixed duplicate error logs and logging underlying errors

---

.circleci/config.yml

See [documentation](https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-hit-timeout-limit). The default value is 10 minutes.
Fixes [CF-528].
[CF-528]: https://revenuecats.atlassian.net/browse/CF-528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`CircleCI`: increased `make-release`'s `no_output_timeout` to 30 minutes

---

Sources/Error Handling/ErrorCode.swift
Sources/Error Handling/ErrorUtils.swift
Sources/Networking/HTTPClient.swift
Sources/Networking/NetworkError.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesErrorCodeAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Networking/NetworkErrorTests.swift
Tests/UnitTests/Purchasing/ErrorCodeTests.swift

This is a special enough error that it's worth distinguishing from other `ErrorCode.networkError`s.
I see a couple benefits:
- When opening an app that has the SDK, this used to print lots of errors that just said "Error performing request". Now it's more clear what's happening
- Users can respond to failed calls to the SDK more appropriately, whereas before it might not be clear why a request failed.
Also fixed `logErrorIfNeeded` not passing the file/function/line parameters to the log functions.

Added new `ErrorCode.offlineConnectionError`

---

Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
Sources/Purchasing/Purchases.swift
Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
Sources/SubscriberAttributes/SubscriberAttributesManager.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

For [CF-566]
We have convenience setter methods for reserved attributes, and `$firebaseAppInstanceID` is another reserved attribute that needs a setter.
Adds new public method to Purchases: `setFirebaseAppInstanceID(_:)`
[CF-566]: https://revenuecats.atlassian.net/browse/CF-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

New public convenience setter for Firebase app instance ID

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Networking/Backend.swift
Sources/Networking/Caching/OfferingsCallback.swift
Sources/Networking/Operations/GetOfferingsOperation.swift
Sources/Networking/Responses/OfferingsResponse.swift
Sources/Purchasing/OfferingsFactory.swift
Sources/Purchasing/OfferingsManager.swift
Sources/Purchasing/Purchases.swift
Tests/UnitTests/Caching/DeviceCacheTests.swift
Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Mocks/MockOfferingsFactory.swift
Tests/UnitTests/Mocks/MockOfferingsManager.swift
Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Tests/UnitTests/Purchasing/OfferingsTests.swift
Tests/UnitTests/Purchasing/PurchasesTests.swift

Depends on #1437.
This takes full advantage of `Decodable` when decoding and creating `Offerings`.

`OfferingsManager`/`OfferingsFactory`: using `OfferingsResponse`

---

Sources/Purchasing/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift

`StoreKit2TransactionListener` was triggering an asynchronous call to `syncPurchases` during transaction verification, and at the end of every purchase, another `syncPurchases` call was being made.
This refactor combines both calls into one by making `finish(transaction:)` wait for that call to finish.

StoreKit 2 purchases: removed double request to `syncPurchases`

---

Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPromotionalOfferAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/PromotionalOfferAPI.swift

This is what's causing the tests in https://github.com/RevenueCat/purchases-hybrid-common/pull/129 to fail - the type isn't exposed, so I'm temporarily using `@testable` just to compile locally, but we really can't have that in production. 
This PR exposes the type, so that in turn purchases-hybrid-common can send it to the hybrids. 
I'm not 100% sure if the hybrids actually ever use the type, but this is kind of the path of least resistance 😅 Since it means one less breaking change in the hybrids. I also don't really see an issue with exposing the type

expose signed data in promo offers

---

Sources/CodableExtensions/PeriodType+Extensions.swift
Sources/CodableExtensions/PurchaseOwnershipType+Extensions.swift
Sources/CodableExtensions/Store+Extensions.swift
Sources/FoundationExtensions/JSONDecoder+Extensions.swift
Sources/Logging/Strings/CodableStrings.swift

- Improved output of decoding errors:
```
[Purchases] - ERROR: 😿‼️ Couldn't decode data from json. Error:
The operation couldn’t be completed. (RevenueCat.CodableError error 0.))
```
```
[Purchases] - ERROR: 😿‼️ Couldn't decode data from json. Error:
Found unexpected value 'tienda' for type 'Store'
```
- `CodableStrings.decodingError` relied on `Error.localizedDescription`, so `CodableError` now conforms to `LocalizedError` to provide that as well
- Added incorrect `value` to the error to find out why it was invalid
- Removed extra `)` at the end of the error string
- Cleaned up `switch`es to use a single `let` syntax

Fixed `ErrorUtils.logDecodingError`

---

Sources/FoundationExtensions/JSONDecoder+Extensions.swift

The main difference is that `default` has `KeyEncodingStrategy.convertToSnakeCase`. Probably everything was still working because the types that use this explicitly define the keys.
Either way this makes more sense long term.

`Encodable.asDictionary()`: use `JSONEncoder.default`

---

.circleci/config.yml
Sources/Purchasing/Purchases.swift
Sources/Purchasing/PurchasesDelegate.swift
Sources/Purchasing/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit1/StoreKitWrapper.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
Tests/APITesters/SwiftAPITester/SwiftAPITester/PromotionalOfferAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Purchasing/StoreKitWrapperTests.swift

As well as `Purchases.showPriceConsentIfNeeded()` to manually handle showing the price consent if `shouldShowPriceConsent` is set to `false`
Resolves [CF-69]
[CF-69]: https://revenuecats.atlassian.net/browse/CF-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Expose `shouldShowPriceConsent` on PurchasesDelegate

---

Sources/Identity/CustomerInfo.swift
Sources/Misc/Deprecations.swift

A small refactor taken out of #1496.

`CustomerInfo`: moved deprecated property to `Deprecations`

---

Purchases.podspec

This question comes up quite often on why `v4` has was not installed when running `pod install` or `pod update` and its because `v4` is associated with the pod name `RevenueCat` and not `Purchases`
Sets `deprecated` and `deprecated_in_favor_of` in the v3 `Purchases` podspec that will output the `RevenueCat` in now favored

3.x.x - add `s.deprecated_in_favor_of ` to reduce confusion when v4 not installed

---

RevenueCat.xcodeproj/project.pbxproj

This fixes the `watchOS` and `tvOS` compilation (yay CI test coverage catching this!)
Now the framework is only linked for the rest of the platforms.

Don't link `AdServices.framework`  on `watchOS` & `tvOS`

---

Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

I broke these tests in a refactor and these improvements are making it much easier to figure out what's failing. Right now the failures come from the `verify` methods so it's hard to find the root issue.
- Use `#file` and `#line` to make failures show up in the right line
- Use `ISO8601DateFormatter`
- Moved verification methods to an extension separate from the tests

Improved `EntitlementInfosTests`

---

Sources/FoundationExtensions/Decoder+Extensions.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift

Follow up to #1537. This will be needed for several properties of `CustomerInfo`'s response, like `managementURL`.

Added `@IgnoreDecodeErrors` property wrapper

---

RevenueCat.xcodeproj/project.pbxproj
Sources/FoundationExtensions/JSONDecoder+Extensions.swift
Sources/FoundationExtensions/LossyCollections.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift

Inspired by https://github.com/marksands/BetterCodable/blob/master/Sources/BetterCodable but supporting nested collections and with simplified code.
These property wrappers allows decoding `Array`s and `Dictionary`s and ignore elements that fail to decode.
For example, this will ignore any elements that aren't numbers, instead of failing to decode altogether.
```swift
struct Data: Decodable {
@LossyArray var list: [Int]
@LossyDictionary var map: [String: Int]
}
```
This does require that the values are the right type, but these wrappers can be composed with `@DefaultDecodable.EmptyArray` and `@DefaultDecodable.EmptyDictionary` introduced in #1537 to make it produce an empty array in case of any other type error:
```swift
struct Data: Decodable {
@DefaultDecodable.EmptyArray @LossyArray …
```

Created `@LossyArray` and `@LossyDictionary`

---

Sources/FoundationExtensions/LossyCollections.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift

The new test illustrates the behavior change that adding `@LossyDictionary` to a `[String: Decodable]` property had. Keys were being converted to camel case, which is inconsistent from the default behavior that `container.decode([String: Value].self, forKey: key)` would have.
The reason for this is some implementation detail on Foundation that ignores the `keyDecodingStrategy` when decoding "raw" dictionaries versus property names. To deal with this, we decode the strings first as "raw", and then match them to the corresponding converted key.
This was necessary to make sure that keys [like these](https://github.com/RevenueCat/purchases-ios/blob/4.3.0/Tests/UnitTests/Purchasing/CustomerInfoTests.swift#L58) aren't incorrectly converted to camel case, which is required for #1496.

`@LossyDictionary`: workaround for decoding snake case dictionary keys

---

Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift

Operations run asynchronously, but this test was not waiting, and therefore the only assertion always passed no matter what.
Now this actually ensures that when the operation ends, there are still no requests being made.

`BackendGetIntroEligibilityTests`: fixed test that was passing before anything ran

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Misc/AnyDecodable.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Tests/UnitTests/Misc/AnyDecodableTests.swift

This will be used to decode the entire data in JSON for the new implementation of `RawDataContainer` in #1496.

Created `AnyDecodable`

---

Sources/Purchasing/EntitlementInfo.swift

Inspired by https://github.com/RevenueCat/purchases-flutter/issues/361
The comment for entitlement's `willRenew` was wrong. Lifteime purchases will return `false`

willRenew update comment for lifetime will be false

---

Sources/CodableExtensions/Store+Extensions.swift
Sources/Purchasing/EntitlementInfo.swift
Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/StoreKit2StorefrontListenerTests.swift
Tests/StoreKitUnitTests/StorefrontTests.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

This PR adds `AmazonStore` to the `Store` enum.
- TODO: Create corresponding PRs for hybrid SDKs
Resolves [CF-653](https://revenuecats.atlassian.net/browse/CF-653).
- Added the `AmazonStore` value to the `Store` enum with a value of `6` to ensure that any implementations relying on `Unknown` being `5` don't break.
- Ensured that the `name` value of the case matches the value used by the backend.
- Updated relevant `switch` statements to include the new case.
- Fixed a few Swiftlint warnings to get the CI to pass

CF-653: Add `AmazonStore` to `Store` enum

---

Sources/CodableExtensions/Store+Extensions.swift
Sources/Purchasing/EntitlementInfo.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

This PR is a follow up to #1586 that renames the `Store` enum's `AmazonStore` case to `Amazon` to match the naming conventions used in the [Android SDK](https://github.com/RevenueCat/purchases-android/blob/8b81142904780aede258962b4aef350273cfaad7/public/src/main/java/com/revenuecat/purchases/EntitlementInfo.kt#L150).

CF-653: Rename `AmazonStore` Store enum case to `Amazon` to match Android naming

---

RevenueCat.xcodeproj/project.pbxproj
Sources/CodableExtensions/PurchaseOwnershipType+Extensions.swift
Sources/CodableExtensions/Store+Extensions.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Tests/UnitTests/Purchasing/PeriodTypeTests.swift
Tests/UnitTests/Purchasing/PurchaseOwnershipTypeTests.swift
Tests/UnitTests/Purchasing/StoreTests.swift

Follow up to #1551. Using `Codable.encodeAndDecode` we ensure that each value can be bidirectionally converted.
These tests exposed that unknown values were being encoded as `null`, but then failed to decode.
I've updated the implementation and added a few more tests to cover this behavior.

Added tests for `PeriodType`/`PurchaseOwnershipType`/`Store`

---

Sources/Purchasing/Configuration.swift

Fixes warning:
> Parameter 'useStoreKit2IfAvailable' not found in the function declaration

`Configuration.builder.with(usesStoreKit2IfAvailable:)`: fixed docstring

---

Sources/Networking/HTTPClient.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

Fixes [CF-649].
[CF-649]: https://revenuecats.atlassian.net/browse/CF-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`HTTPClient`: added `X-Is-Sandbox` header

---

Sources/FoundationExtensions/String+Extensions.swift
Sources/Purchasing/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
Tests/UnitTests/Caching/DeviceCacheTests.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift
Tests/UnitTests/Networking/ETagManagerTests.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Networking/HTTPResponseTests.swift
Tests/UnitTests/Purchasing/OfferingsTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

Turns out `Data(string.utf8)` is a much simpler way of converting `String` to `Data` that doesn't lead to an `Optional`.
UTF-8 can represent all valid Unicode code points, so this was always safe, but now we know at compile time.
The reason the old variant returned an `Optional` is because it accepts other encodings like `.ascii` which might not be able to represent everything in the `String`.
This simplifies several parts of the code that were dealing with an error that was impossible.

Added `String.asData` to avoid dealing with `Data?`

---

Sources/CodableExtensions/PeriodType+Extensions.swift
Sources/CodableExtensions/PurchaseOwnershipType+Extensions.swift
Sources/CodableExtensions/Store+Extensions.swift
Sources/FoundationExtensions/Decoder+Extensions.swift

The method doesn't actually throw, so calling `throw decoder.throwValueNotFoundError()` was confusing. Now the code reads `throw decoder.valueNotFoundError()`.

Renamed `Decoder.throwValueNotFoundError`

---

Sources/Logging/Strings/PurchaseStrings.swift

```
PaymentQueue removedTransaction: com.revenuecat.monthly_4.99.1_week_intro 2 (0   - 1
```
```
PaymentQueue removedTransaction: com.revenuecat.monthly_4.99.1_week_intro 7 0 1
```

`PurchaseStrings`: fixed transaction message formatting

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Purchasing/StoreKitAbstractions/StoreKitWorkarounds.swift
Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
Tests/UnitTests/Purchasing/StoreKitAbstractions/StoreKitWorkaroundsTests.swift
Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift

This PR resolves [CF-659](https://revenuecats.atlassian.net/browse/CF-659) & `react-native-purchases` issue [#348](https://github.com/RevenueCat/react-native-purchases/issues/348).
Occasionally, StoreKit will state that a period is 7 days instead of 1 week. This unexpected behavior can cause unintended issues for customers on their paywalls and generally decreases developer confidence in the Offerings/Products provided by the SDK.
- Implemented a `normalization` function to be run on the input parameters of the `SubscriptionPeriod` class that, if possible to do so evenly, converts days into weeks and months into years.
- This function is static since it needs to be executed before the `SubscriptionPeriod` class has completed instantiation.
- Conversion of weeks to months and weeks to …

Ensure SubscriptionPeriods are represented as 1week instead of 7days

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/PurchasesDelegateHandler.swift

This was changed in #1460. Additionally, without #1600 this wasn't producing the correct rename, it wasn't finding `DeferredPromotionalPurchaseBlock` anywhere.

`MagicWeatherSwiftUI`: fixed usage of `PurchaseDelegate`

---

Sources/Purchasing/PurchasesOrchestrator.swift

Fixes #1598.
Without this `catch`, we were throwing `ErrorCode.purchaseCancelledError`, which then was being logged as a failed purchase and returned as such.
Now this correctly returns no error, and `userCancelled` `true`.
Unfortunately we can't cover this in tests because `SKTestSession.failureError` doesn't allow mocking cancellations (yet?)

`StoreKit 2` purchases: don't throw when purchase is cancelled

---

Tests/UnitTests/Misc/AnyDecodableTests.swift

Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/6737/workflows/b945f5f6-6f31-4716-b1ac-6e16e3848c7e/jobs/26321
For some reason, on iOS 12.x only, this:
```swift
JSONDecoder.default.decode(jsonData: "null".data(using: .utf8)!)
```
Fails:
```
dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))
```
We don't rely on decoding fragments, so I just updated the test to check `.null` within a dictionary instead.

Fixed `AnyDecodableTests.testNull` on iOS 12

---

Tests/UnitTests/Purchasing/PeriodTypeTests.swift
Tests/UnitTests/Purchasing/PurchaseOwnershipTypeTests.swift
Tests/UnitTests/Purchasing/StoreTests.swift

Follow up to #1589.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/6805/workflows/550827f9-ff8e-469d-b7a7-889417582eff/jobs/26743
Turns out the tests introduced in #1558 weren't compatible with iOS 12. As explained in #1589.
For some reason, on iOS 12.x only, this:
```
JSONDecoder.default.decode(jsonData: "null".data(using: .utf8)!)
```
Fails:
> dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.})))
Since iOS 12.x doesn't allow decoding …

Fixed iOS 12 `Codable` tests

---

Sources/Identity/CustomerInfo.swift
Sources/Misc/RawDataContainer.swift
Sources/Networking/Responses/CustomerInfoResponse.swift
Sources/Purchasing/EntitlementInfo.swift
Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfo.json
Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

Follow up to #1496. Depends on ~~#1567,  #1568, #1604~~.
The solution implemented in #1496 was very simple, but [as pointed out by @joshdholtz](https://github.com/RevenueCat/purchases-ios/pull/1496#discussion_r869463028), it was only encoding the data that was formally decoded by the `struct`s.
We had no test coverage for this, so it went unnoticed.
The new solution adds a new field:
```swift
@IgnoreEncodable @IgnoreHashable
var rawData: [String: Any]
```
Which, together with a new helper method `decodeRawData()`, allows storing all the data to be used by `CustomerInfo`'s `RawDataContainer` implementation.
Unfortunately, despite many attempts, I realized that this can't be abstracted into a property wrapper, because a `KeyedDecodingContainer` can't access the parent `Decoder`.
That's why …

Added tests and fix to ensure `RawDataContainer` includes all data

---

fastlane/Fastfile

I was getting rate limited when generating the changelog automatically. This deserves a proper fix eventually but will do that later 🤷‍♂️
🤢 Adds optional `GITHUB_RATE_LIMIT_SLEEP ` env to add a sleep between github requests
```
GITHUB_RATE_LIMIT_SLEEP=5 bundle exec fastlane bump
```

Optional ENV for rate limiting github requests when generating changelog

---

Sources/Purchasing/PurchasesOrchestrator.swift

I tried adding tests for this, but because the listener is created internally, there is no time to override it with the mock before verifying if `listenForTransactions` is called.
Will at least prevent #1528 if SK2 is disabled.

`PurchasesOrchestrator`: don't listen for StoreKit 2 transactions if it's disabled

---

Sources/Logging/Strings/ManageSubscriptionsStrings.swift
Sources/Misc/SystemInfo.swift
Sources/Support/ManageSubscriptionsHelper.swift
Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
Tests/UnitTests/Misc/SystemInfoTests.swift

Fixes [CF-684] and #1594.
`SystemInfo.appleSubscriptionsURL` was a short URL that didn't pass the `SystemInfo.isAppleSubscription(managementURL:)` test. This is fixed and covered by a test now.
- Made `SystemInfo.isAppleSubscription(managementURL:)` and `SystemInfo.appleSubscriptionsURL` static since they don't need any properties in `SystemInfo`.
- Forced-unwrapped `SystemInfo.appleSubscriptionsURL` to remove unnecessary error handling. This is safe because the URL is provided statically at compile time. Per the docs "This initializer returns nil if the string doesn’t represent a valid URL. For example, an empty string or one containing characters that are illegal in a URL produces nil.". This is known at compile time, and covered by tests, so it could never return `nil`.
- Combined …

`ManageSubscriptionsHelper`: fixed discrepancy between `SystemInfo.isAppleSubscription(managementURL:)` and `SystemInfo.appleSubscriptionsURL`

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Logging/Strings/BackendErrorStrings.swift
Sources/Networking/Operations/PostOfferForSigningOperation.swift
Sources/Networking/Responses/PostOfferResponse.swift
Tests/UnitTests/Networking/Responses/Fixtures/PostOffer.json
Tests/UnitTests/Networking/Responses/PostOfferDecodingTests.swift

- Added `PostOfferResponse`
- Added `PostOfferDecodingTests` tests
- Using the automatic deserialization by `HTTPClient` by simply changing the callback to `HTTPResponse<PostOfferResponse>.Result`
- All tests in `BackendPostOfferForSigningTests` (which are very exhaustive) pass with no changes!

`PostOfferForSigningOperation`: changed response parsing to using `Decodable`

---

Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift

I often get failures when running all tests in parallel because this test takes more than 1 second to run.
Example:
> failed - expected to be close to <2022-05-24 10:59:18.3370> (within 1), got <2022-05-24 10:58:18.0000>
To allow the test to take a few more seconds, I think this is a reasonable compromise.

`LocalReceiptParserStoreKitTests`: relaxed `purchaseDate` expectation

---

RevenueCat.xcodeproj/project.pbxproj
Sources/FoundationExtensions/Operators+Extensions.swift
Sources/Purchasing/PurchasesOrchestrator.swift
Tests/UnitTests/FoundationExtensions/OperatorExtensionsTests.swift

Both `return` statements where the same, the `else` was just providing a default value to `customerInfoIfSynced`.
Because `??` doesn't support an `async` function, we couldn't use that. By using this new operator we can simplify the implementation to a single `return` statement.

`PurchasesOrchestrator.purchase(sk2Product:promotionalOffer:)`: simplified implementation with new operator

---

Sources/Purchasing/PurchasesOrchestrator.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift

Fixes [CF-682], and probably #1528.
Looks like possibly something was broken demangling `lazy` properties with `@available` in iOS 15.0 (per the 2 bug reports).
This changes the approach to simply having `Any?` as the value, and making the exposed `@available` property a derived one.
[CF-682]: https://revenuecats.atlassian.net/browse/CF-682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`PurchasesOrchestrator`: removed `lazy` hack for properties with `@available`

---

Sources/Purchasing/Purchases.swift
Sources/Purchasing/PurchasesOrchestrator.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Mocks/MockSystemInfo.swift

Added tests for `PurchasesOrchestrator` invoking `listenForTransactions` only if SK2 is enabled

---

Sources/Purchasing/StoreKitAbstractions/Storefront.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStorefrontAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/StorefrontAPI.swift
Tests/StoreKitUnitTests/StorefrontTests.swift

Fixes https://community.revenuecat.com/sdks-51/objective-c-how-to-access-rcstorefront-1647?postid=5154#post5154
`RCStoreFront` does have a `currentStorefront` property which supports StoreKit 1 and StoreKit 2, but due to the fact that the SK2 way of obtaining the current storefront is `async`, this property is only `async`, which means that it indeed isn’t available on Objective-C.
This adds a way to be able to access the current storefront from Objective-C.

 `Storefront`: added `sk1CurrentStorefront` for Objective-C

---

RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift

`PurchasesTests.swift` is nearly 3000 lines. This is the first step towards making separate smaller files like I did with `BackendTests.swift` in #1365.

Split `PurchasesTests` step 1: extracted `BasePurchasesTests`

---

RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift

Split `PurchasesTests` step 4: extracted `PurchasesRestoreTests`

---

RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift

Follow up to #1609. 
I've also cleaned up the initialization of these tests.

Split `PurchasesTests` step 7: extracted `PurchasesDeferredPurchasesTests`

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Error Handling/BackendError.swift
Sources/Identity/CustomerInfoManager.swift
Sources/Identity/IdentityManager.swift
Sources/Logging/Strings/PurchaseStrings.swift
Sources/Purchasing/CacheFetchPolicy.swift
Sources/Purchasing/Purchases.swift
Sources/Support/BeginRefundRequestHelper.swift
Sources/Support/ManageSubscriptionsHelper.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCCustomerInfoAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Mocks/MockCustomerInfoManager.swift

Fixes [CF-19].
This allows specifying `CustomerInfoManager` fetching behavior, both as a public API for users, and also internally.
Some future uses of `CustomerInfoManager` might want to ensure that we don't rely on cached data, for example.
Thanks to the `APITester` we know that the existing methods still work, this is purely an additive change.
This is the core of the change:
```swift
/// Specifies the behavior for a caching API.
@objc(RCCacheFetchPolicy)
public enum CacheFetchPolicy: Int {
/// Returns values from the cache, or throws an error if not available.
case fromCacheOnly
/// Always fetch the most up-to-date data.
case fetchCurrent
/// Returns the cached data if available and not stale, or fetches up-to-date data.
case notStaleCachedOrFetched
/// Default behavior: returns the …
```

`Purchases.customerInfo()`: added overload with a new `CacheFetchPolicy`

---

Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift

Split `PurchasesTests` step 9: moved more tests

---

Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
Sources/Purchasing/Purchases.swift

Replace ``Purchases/customerInfo()`` with ``Purchases/customerInfo(fetchPolicy:)``
The proper name is `customerInfo(fetchPolicy:)`

Update doc reference to ``Purchases/customerInfo(fetchPolicy:)``

---

RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift

Follow up to #1609.
Also moved the final test from and removed `PurchasesTests`
Finishes [CF-717].
[CF-717]: https://revenuecats.atlassian.net/browse/CF-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Split `PurchasesTests` step 13: extracted `PurchasesDelegateTests`

---

Sources/Networking/Responses/CustomerInfoResponse.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift

Fixes https://revenuecats.atlassian.net/browse/SDKONCALL-20
`LossyDictionary` was trying to convert the keys of product identifiers with a `JSONEncoder` and `JSONDecoder` encoding strategy (snake and camel case) when writing and reading from the cache.
These keys should not be using any encoding strategies (since the product identifiers are not getting mapped to any properties). Removing the `LossyDictionary` allows the product identifier keys to remain as they case they were intended to be.
This also fixes the test that would have caught this. The test for `CustomerInfo` had two subscriptions that expired in `2018` to `activeSubscriptions` was returning empty array for pre-cache and post-cache. There also a few more product identifier case formats added to this to try and catch any other …

Fix decoding issue caused by LossyDictionary for subscriptions and active entitlements

---

Sources/Logging/Strings/CodableStrings.swift

While debugging `CustomerInfo` decoding errors for example, this is the existing error logged in the console:
```
ERROR: 😿‼️ Couldn't decode data from json. Error:
There was a problem related to the customer info.
```
With this change:
```
ERROR: 😿‼️ Couldn't decode data from json.
Error: There was a problem related to the customer info..
Underlying error: Swift.DecodingError.typeMismatch(Swift.Dictionary<Swift.String, RevenueCat.CustomerInfoResponse.Subscription>, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "subscriber", intValue: nil), CodingKeys(stringValue: "subscriptions", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Subscription> but found an array instead.", underlyingError: nil))
```

`CodableStrings.decoding_error`: added underlying error information

---

Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfo.json
Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json

See #1650.
I've added a failing subscription identifier in the fixture `CustomerInfo.json` so that the `CustomerInfoDecodingTests` would catch this.
Also updated the test introduced in #1651 to include one more case and improved the assertions.

Added more failing tests for `CustomerInfo` encoding regression

---

fastlane/Fastfile

This allows creating a changelog from a different version using `bundle exec fastlane bump old_version:4.5.1`.

`fastlane bump` lane passes `options` to `github_changelog`

---

README.md

I noticed while browsing Swift Package Index that there are badges for Swift Package Index that we can use for supported Swift versions and platforms.
These badges will automatically update with what SPI detects so we don't need to maintain these.
Adds two badgest into README
Totally fine if we don't want to merge this PR (if its too many badges) but figured I'd quickly make this PR to see if any interest 🤷‍♂️

Add Swift Package Index badges for Swift version and platforms

---

fastlane/Fastfile

`.version` ended up with a line break (see https://github.com/RevenueCat/purchases-ios/blob/78bd65f/.version) which is breaking our release script. This fixes it.

`fastlane current_version_number`: added `strip` to deal with line break

---

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift

I've noticed sometimes tests start with some receipts that are pending to submit, which could lead to flaky tests.
Hopefully this makes them less flaky.

`Integration Tests`: always clear `Bundle.appStoreReceiptURL` before every test

---

Sources/FoundationExtensions/Decoder+Extensions.swift
Sources/Networking/Responses/CustomerInfoResponse.swift
Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
Tests/UnitTests/Networking/Backend/BackendLoginTests.swift
Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfoWithInvalidSubscription.json
Tests/UnitTests/Purchasing/CustomerInfoTests.swift

See also #1658.
This updates the behavior of `CustomerInfoResponse` decoding so that having invalid content inside of one of the structures fails more loudly instead of getting ignored.
For that, `@DefaultValue` no longer ignores errors, and instead `@IgnoreDecodeErrors` must be used.
For some of the values in `CustomerInfoResponse` this makes sense (like `Store`), but not for things like subscriptions where we would be losing data.

`CustomerInfoDecodingTests`: added test to check decoding invalid data behavior

---

Sources/Misc/MacDevice.swift

From the docs:
```
@abstract The default mach port used to initiate communication with IOKit.
@discussion When specifying a main port to IOKit functions, the NULL argument indicates "use the default". This is a synonym for NULL, if you'd rather use a named constant.
extern
const mach_port_t kIOMainPortDefault
```
`kIOMasterPortDefault` is deprecated, and `kIOMainPortDefault` isn't available on Catalyst in Xcode 14. This fixes compilation by simply using `NULL` (0).
Fixes [CSDK-106].
[CSDK-106]: https://revenuecats.atlassian.net/browse/CSDK-106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`MacDevice`: changed usage of `kIOMasterPortDefault` to fix Catalyst compilation on Xcode 14

---

Sources/FoundationExtensions/Result+Extensions.swift
Tests/UnitTests/FoundationExtensions/ResultExtensionsTests.swift

Our implementation of `ErrorUtils.error(with:message:underlyingError:extraUserInfo:)` always calls `ErrorUtils.logErrorIfNeeded`, this means that even though the error wasn't actually used, it was being logged as if it had occurred.
By using `@autoclosure` we avoid this and instead create it lazily.
This incorrect logging lead to [CSDK-112], which won't be confusing anymore.
[CSDK-112]: https://revenuecats.atlassian.net/browse/CSDK-112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`Result.init(value:error:)`: avoid creating error if value is provided

---

Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostsReceiptDataWithProductDataCorrectly.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testPostsReceiptDataWithProductDataCorrectly.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testPostsReceiptDataWithProductDataCorrectly.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostsReceiptDataWithProductDataCorrectly.1.json

Looking into [SDKONCALL-19], realized that there's no test that explicitly checks the `ProductRequestData` is sent along with the receipt data.
[SDKONCALL-19]: https://revenuecats.atlassian.net/browse/SDKONCALL-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`BackendPostReceiptDataTests`: added new test with `ProductRequestData`

---

Sources/Purchasing/EntitlementInfo.swift

This avoids the error-prone implementation of `equals` and `hashValue`.
Small refactor in preparation for [CSDK-53].
[CSDK-53]: https://revenuecats.atlassian.net/browse/CSDK-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extracted `struct` from `EntitlementInfo` to simplify implementation

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Caching/DeviceCache.swift
Sources/Misc/SandboxEnvironmentDetector.swift
Sources/Misc/SystemInfo.swift
Sources/Purchasing/Purchases.swift
Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Attribution/AttributionPosterTests.swift
Tests/UnitTests/Caching/DeviceCacheTests.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Identity/IdentityManagerTests.swift
Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift
Tests/UnitTests/Mocks/MockDeviceCache.swift
Tests/UnitTests/Mocks/MockIdentityManager.swift
Tests/UnitTests/Mocks/MockSandboxEnvironmentDetector.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

For [CSDK-53], `EntitlementInfos` will need access to the environment. This provides a lighter interface for that, as well as a simple implementation to inject that doesn't require the entire `SystemInfo`
[CSDK-53]: https://revenuecats.atlassian.net/browse/CSDK-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extracted `SandboxEnvironmentDetector`

---

Sources/Identity/CustomerInfo.swift
Sources/Purchasing/EntitlementInfos.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfosAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfosAPI.swift
Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

Fixes [CSDK-53].
Depends on #1645.
This is backwards compatible. `EntitlementInfos.active` maintains the previous behavior of returning `activeInAnyEnvironment`
[CSDK-53]: https://revenuecats.atlassian.net/browse/CSDK-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`EntitlementInfos`: added `activeInAnyEnvironment` and `activeInCurrentEnvironment`

---

Sources/Purchasing/Purchases.swift

Just noticed this small thing in docs, this fixes it.

Fix small bug in docs

---

Sources/Purchasing/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift
Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift

Fixes [SDKONCALL-19].
SK2 purchases were always calling `syncPurchases`, which called `Backend.post(receiptData:...)` with no `productData`, which meant that after every SK2 purchase we never posted the price.
This refactor makes a lot of methods in `PurchasesOrchestrator` use `StoreTransaction` so they can be used during SK2 purchases as well. Specifically, `handlePurchasedTransaction` is now called after both SK1 and SK2 purchases.
- `StoreKit2TransactionListenerDelegate` no longer needs to return `CustomerInfo`
- `StoreKit2TransactionListenerDelegate.handle(purchaseResult:)` no longer notifies the delegate (only done by `StoreKit.Transaction.updates`), which was leading to duplicate `syncPurchases` calls.
- If the purchase is cancelled, `syncPurchases` isn't called. Instead, the …

`PurchasesOrchestrator`: replaced calls to `syncPurchases` with posting receipt for an individual product during SK2 purchases

---

RevenueCat.xcodeproj/project.pbxproj
Sources/FoundationExtensions/String+Extensions.swift
Tests/UnitTests/FoundationExtensions/StringExtensionsTests.swift

Fixes #1685.
Swift's `lazy` and `static` property initialization is always thread-safe. However, `key` was only created as an empty dictionary, and the evaluation of `ROT13.string`, which was the one initializing that data, wasn't isolated.
By creating `ROT13.key` inline, this ensures that the initialization is only done once in a thread-safe way.

Fixed `ROT13.string` thread-safety

---

Sources/Purchasing/EntitlementInfos.swift
Sources/Purchasing/Offering.swift
Sources/Purchasing/Offerings.swift
Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift

That's not supported by docC, so replaced with `Related Symbols` and `Related Articles`

Fixed usages of `seealso`

---

.circleci/config.yml

Updated to use Xcode 14 for docs generation, so we get: 
- A navigation side bar
- Obj-C APIs in the docs
- Search bar
I tried running it manually with Xcode 14 and it looks stable enough:
https://revenuecat.github.io/purchases-ios-docs/4.6.0/documentation/revenuecat/
Although the language selector doesn't work just yet 😅 
Still, it'll hopefully start working in future betas.

Use xcode 14 for docs generation

---

Tests/StoreKitUnitTests/ProductsManagerTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Identity/IdentityManagerTests.swift
Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift
Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift

Thanks @taquitos for finding this.
Our existing use as illustrated in the diff could lead to race conditions, because the `completionCalled.toEventually(beTrue())` would potentially evaluate before the next line, leading to flaky tests.

Fixed thread unsafe usage of `toEventually`

---

Sources/Purchasing/EntitlementInfo.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

Giving the end users back a millisecond of entitlement access, and hopefully solving [a Sandbox issue](https://github.com/RevenueCat/purchases-ios/issues/1597) wherein entitlements are returned as inactive because expirationDate == latestPurchaseDate for 30 second subscription renewals.
Did I miss any repercussions around making this change?

EntitlementInfo.isActive returns true if requestDate == expirationDate

---

Sources/FoundationExtensions/String+Extensions.swift

- Using `Dictionary.init(minimumCapacity:)` to allocate the necessary size initially instead of growing when adding data to it
- Defined `uppercase` in terms of `lowercase`
- Removed magic `13` and `26` numbers

`ROT13`: optimized initialization and removed magic numbers

---

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift

Equivalent to #1671 but for unit tests.
In iOS 16 (as of beta 1), the receipt persists across tests, despite the use of `SKTestSession.resetToDefaultState`.
This might also help with flaky tests pre-iOS 16 too.
Also note that I fixed this method in `BaseBackendIntegrationTests`. Using `URL.absoluteString` was incorrect there, so the file was probably never deleted.
I filed a feedback for this:

`StoreKitConfigTestCase`: delete `Bundle.appStoreReceiptURL` after every test

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Error Handling/ErrorCode.swift
Sources/Networking/Backend.swift
Sources/Networking/BackendConfiguration.swift
Sources/Networking/HTTPClient.swift
Sources/Networking/Operations/GetCustomerInfoOperation.swift
Sources/Networking/Operations/GetIntroEligibilityOperation.swift
Sources/Networking/Operations/GetOfferingsOperation.swift
Sources/Networking/Operations/LogInOperation.swift
Sources/Networking/Operations/NetworkOperation.swift
Sources/Networking/Operations/PostAttributionDataOperation.swift
Sources/Networking/Operations/PostOfferForSigningOperation.swift
Sources/Networking/Operations/PostReceiptDataOperation.swift
Sources/Networking/Operations/PostSubscriberAttributesOperation.swift
Sources/Networking/SubscribersAPI.swift
Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Mocks/MockHTTPClient.swift
Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift

Extract various dependencies that are required to instantiate the `Backend` object.
Refactor to assist with the next few PRs that extract out other pieces
See [CSDK-82]
Resolves [CSDK-155]
Depends on [CSDK-152]
Blocked by https://github.com/RevenueCat/purchases-ios/pull/1695
[CSDK-82]: https://revenuecats.atlassian.net/browse/CSDK-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSDK-155]: https://revenuecats.atlassian.net/browse/CSDK-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSDK-152]: https://revenuecats.atlassian.net/browse/CSDK-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Extract Backend dependencies into a BackendConfiguration object

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift

Fixes [CSDK-120].
See conversation: https://github.com/RevenueCat/purchases-ios/pull/1666#discussion_r892423490
> why do we have `onlyIfEmpty` in this case? If we're calling this method, we know that there was a purchase, right? I feel like we should always refresh in that case, there's a good chance that the receipt isn't up to date otherwise
[CSDK-120]: https://revenuecats.atlassian.net/browse/CSDK-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`PurchasesOrchestrator.handlePurchasedTransaction`: always refresh receipt data

---

RevenueCat.xcodeproj/project.pbxproj

I fixed this in #1697, but looks like d637b6c9217d1e27376be3531bda67da8c0d38ba had a bad merge conflict.

Removed duplicate `SwiftStyleGuide` reference

---

Sources/Misc/Purchases+async.swift
Sources/Purchasing/Purchases/Purchases.swift

This was being ignored in the `async` method

`Purchases.customerInfo(fetchPolicy:)`: actually use `fetchPolicy` parameter

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift
Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
Sources/Purchasing/TransactionsFactory.swift

Fixes [CSDK-122].
Before this change, transactions were finished separately for SK1 and SK2. Now this is combined through a common method in `StoreTransactionType`.
[CSDK-122]: https://revenuecats.atlassian.net/browse/CSDK-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

`PurchasesOrchestrator`: unify finish transactions between SK1 and SK2

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit

`SKTestSession.expireSubscription` doesn't seem to always work.
To work around it, this manually waits until `expirationDate`.
I've added a warning to make it clear what's happening:
```
INFO: ℹ️ Expiring subscription for product 'com.revenuecat.weekly_1.99.3_day_intro'
WARN: ⚠️ Sleeping for 4 seconds to force expiration
```
I've changed all the tests that rely on this to use a weekly subscription. and manually set the `SKTestSession.timeRate` to the lowest value to minimize this duration.

Integration Tests: fixed subscription expiration to fix flaky tests

---

Sources/Identity/CustomerInfo.swift
Sources/Misc/SandboxEnvironmentDetector.swift
Sources/Misc/SystemInfo.swift
Sources/Purchasing/EntitlementInfos.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/UnitTests/Attribution/AttributionPosterTests.swift
Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift

For some reason the url is `[app_bundle]/StoreKit/receipt` in integration tests.
This is not correct, so I've added a couple of tests: one for entitlements, and another one to check the raw output value of that property.
This is necessary to make sure that receipts are loaded correctly after #1726.

Integration Tests: ensure that environment is sandbox

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

Makes this more clear to read and easier maintain.

`PurchasesOrchestrator`: using `PurchaseResultData` tuple value names

---

Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift

The reason the receipt data is required, is because if it's `nil`, it ends up becoming empty because of `data ?? Data()`, but `GetIntroEligibilityOperation` never actually runs because that's empty.
To make sure the test doesn't fail, we begin by ensuring the receipt data is loaded first.
Also documented the reason for `ReceiptRefreshPolicy.never`.

`TrialOrIntroPriceEligibilityChecker`: fixed integration test to ensure receipt is always loaded

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

Integration Tests require iOS 14.1 right now.
Also removed an unused property.

Integration Tests: removed unnecessary availability checks

---

Sources/FoundationExtensions/Dictionary+Extensions.swift
Tests/UnitTests/FoundationExtensions/DictionaryExtensionsTests.swift

Fixes [CSDK-105].
This came up in https://github.com/RevenueCat/purchases-ios/pull/1534#discussion_r891433648 and will simplify some of the code in #1727.
[CSDK-105]: https://revenuecats.atlassian.net/browse/CSDK-105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added `Dictionary.mapKeys` and `Dictionary.compactMapKeys`

---

Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
Tests/StoreKitUnitTests/StoreProductTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift

This is currently broken on iOS 16.
I filed [CSDK-261] to make sure we review this before the GM is out.
I filed a Radar:
We might have to wait for a future beta, or find a workaround.
[CSDK-261]: https://revenuecats.atlassian.net/browse/CSDK-261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Disabled tests that rely on `StoreKitConfigTestCase.changeStorefront` on iOS 16.0

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Identity/CustomerInfo.swift
Sources/Misc/Deprecations.swift
Sources/Purchasing/NonSubscriptionTransaction.swift
Sources/Purchasing/TransactionsFactory.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCCustomerInfoAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCNonSubscriptionTransactionAPI.h
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCNonSubscriptionTransactionAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/main.m
Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/NonSubscriptionTransactionAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreTransactionAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Tests/UnitTests/Purchasing/TransactionsFactoryTests.swift

Fixes [CF-781]
Making `CustomerInfo.nonSubscriptionTransactions` return type a `StoreTransaction` was my mistake from an earlier refactor. I saw the two types were similar, so I made them conform to the same interface.
However, they represent different concepts.
- Added new `NonSubscriptionTransaction` type
- Deprecated `CustomerInfo.nonSubscriptionTransactions` with a `renamed` for a new `nonSubscriptions`
- Made the old `BackendParsedTransaction` initialization depend on the new type to avoid duplicating code
- Add new test to cover the new method, and left the existing one
- Added more checks in `CustomerInfoTest` for missing properties
- Updated all APITesters
[CF-781]: https://revenuecats.atlassian.net/browse/CF-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …

Replaced `CustomerInfo.nonSubscriptionTransactions` with a new non-`StoreTransaction` type

---

Sources/Logging/Strings/PurchaseStrings.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

Example:
```
💰 Purchasing Product 'com.revenuecat.weekly_1.99.no_intro' with Offer 'com.revenuecat.weekly_1.99.3_free_days'
```

Improved purchasing logs, added promotional offer information

---

Contributing/RELEASING.md

Looks like this was changed in #1719 but not updated.

`RELEASING.md`: fixed `bump` lane name

---

fastlane/Fastfile

Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7382/workflows/91dd2e3a-9244-405e-b04c-44d2a4de047f/jobs/30748
With #1719 this was importing `CommonFastfile`. However, some release scripts have a different working directory, like `Tests/InstallationTests/CarthageInstallation`, that `import` the root `Fastfile`. When that happens, this `import` was being evaluated from that working directory, and failing to find `CommonFastfile`.

`Fastfile`: changed `CommonFastfile` `import` relative to current file

---

fastlane/CommonFastfile
fastlane/Fastfile
fastlane/README.md

In #1719 I extracted some of the logic to automate our versioning system. The change I made was wrong since it allowed `plist` files to include prerelease modifiers, which was not the previous behavior. This should fix it moving forward. Additionally, I removed a couple of files that didn't seem to contain any versions (at least in the last few releases)

Fix replace version without prerelease modifiers

---

.github/ISSUE_TEMPLATE/bug_report.md

We've seen several reports where users say "yes" maybe because they assume that's the default.
This makes it more clear that it's only enabled if they're passing the flag.

`bug_report.md`: clarify SK2 support

---

Sources/Error Handling/ErrorUtils.swift

For errors with a custom `message` it turns out that we were never logging it.
This was extra confusing for `OfferingsManager.Error.configurationError`, which ended up displaying this:
> 😿‼️ There is an issue with your configuration. Check the underlying error for more details.
With no underlying details.
> 😿‼️ There is an issue with your configuration. Check the underlying error for more details.
> There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is being used).
> More information: https://rev.cat/why-are-offerings-empty

`logErrorIfNeeded`: also log message if present

---

Sources/Purchasing/EntitlementInfo.swift
Sources/Purchasing/EntitlementInfos.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

A while ago, #1647 added these properties to `EntitlementInfos`: `activeInCurrentEnvironment` and `activeInAnyEnvironment`.
However, the only way to use them was by filtering the `EntitlementInfos`.
A common pattern is to use:
```swift
customerInfo.entitlements.all[entitlementIdentifier].isActive
```
So this adds a couple more properties to allow filtering using the `all` dictionary, directly from the `EntitlementInfo` itself.
For that, I moved the logic down one level, and made the existing methods rely on those new ones instead.
To test the new properties I simply added 2 new expectations to the shared methods used [in the existing tests](https://github.com/RevenueCat/purchases-ios/blob/829b69041da4bd53c5de3b1beb3034d8e8f2532a/Tests/UnitTests/Purchasing/EntitlementInfosTests.swift#L1116- …

`EntitlementInfo`: added `isActiveInCurrentEnvironment` and `isActiveInAnyEnvironment`

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

expireSubscription crashes with current betas 
resolves [CSDK-338]
[CSDK-338]: https://revenuecats.atlassian.net/browse/CSDK-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Don't fail test when expireSubscription fails us.

---

Tests/TestPlans/CI-AllTests.xctestplan
Tests/TestPlans/CI-BackendIntegration.xctestplan

Reduced from the default of 10 minutes. If a test hasn't passed by then, it's probably stuck.

Integration Tests / StoreKit tests: limit execution to 3 minutes

---

.circleci/config.yml
fastlane/Fastfile

Equivalent to https://github.com/RevenueCat/purchases-hybrid-common/pull/181
This allows us to get more details on the failures. I'm planning to do the same for regular iOS tests as well, which will allow us to look at snapshot test failures, etc.

Integration Tests: store result bundle

---

Sources/SubscriberAttributes/SubscriberAttributesManager.swift

This was caused by a new rule `for_where` in the latest version of SwiftLint.

Lint: fixed `SubscriberAttributesManager`

---

Sources/Purchasing/Purchases/Purchases.swift

Not sure why we didn't get a warning for this one, but navigation through the symbol in Xcode wasn't working for me.

fix links to restorePurchase

---

Sources/Purchasing/Purchases/Purchases.swift

Fix another broken link. Again, not sure why we're not getting a warning

fix another broken link in docC docs

---

.circleci/config.yml
fastlane/Fastfile

Follow up to #1771 for all test jobs. This allows us download the `.xcresult` file so we can look at all the test results in detail, including snapshot failures.

CircleCI: always store compressed result bundle

---

Sources/Logging/Logger.swift

I realized in #1780 that we might be doing unnecessary work creating messages that are never logged. This is a small optimization to prevent that.

`Logger`: wrap `message` in `@autoclosure` to avoid creating when `LogLevel` is disabled

---

Tests/UnitTests/Mocks/MockHTTPClient.swift
Tests/UnitTests/TestHelpers/OSVersionEquivalent.swift

This was a getter which meant that it was being evaluated unnecessarily for every mock network request. Now it's only set once.

`OSVersionEquivalent.current`: evaluate only once

---

Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json

Follow up to #1783. I couldn't run iOS 12 tests locally (not working with Xcode 14), so I couldn't verify that this was wrong.
Downloading the full `.xcresult` from https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7546/workflows/b47843e1-bf9a-40f3-9992-220581772f00/jobs/32130/artifacts (thanks to #1773) helped me see what was wrong.

Fixed iOS 12 snapshot

---

Sources/Error Handling/ErrorUtils.swift
Sources/Logging/Strings/OfferingStrings.swift
Sources/Purchasing/OfferingsManager.swift
Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
Tests/UnitTests/Mocks/MockProductsManager.swift
Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift

This will help figure out the reason behind #1765.
We were currently ignoring the error returned by `ProductsManager`.
In the example below, we can see the underlying issue is `SKErrorDomain` code 5.
> Error fetching offerings - The operation couldn’t be completed. (RevenueCat.OfferingsManager.Error error 1.)
> Error fetching offerings - The operation couldn’t be completed. (RevenueCat.OfferingsManager.Error error 1.)
_**Underlying error: The operation couldn’t be completed. (SKErrorDomain error 5.)**_
ERROR: 😿‼️ There is an issue with your configuration. Check the underlying error for more details. There's a problem with your configuration. None of the products registered in the RevenueCat dashboard could be fetched from App Store Connect (or the StoreKit Configuration file if one is …

`OfferingsManager`: expose underlying error when `ProductsManager` returns an error

---

.circleci/config.yml

This is a copy of the android PR https://github.com/RevenueCat/purchases-android/pull/583. Basically with the changes to the fastlane plugin, I added a validation step that checked that the branch was `main` when creating the next snapshot PR. This actually shouldn't be like that since this job is executed from the tag. I removed the validation for this action in https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/12 but until that's merged, copying the fix from android here.

Pass CircleCI branch to prepare_next_version job

---

.circleci/config.yml

https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7590/workflows/f9b051cd-6b41-4d7b-b4b1-77edbec943a5
Restoring caches is taking long time because it's failing to restore caches that are stored in Danger's job, which runs on a Docker image. In a run from before the merge of the Danger changes, it’s finding the cache in Cached paths: `/Users/distiller/purchases-ios/vendor/bundle`. In the newer runs it’s failing in `/home/circleci/purchases-ios/vendor/bundle/`
CircleCI docs say:
> Warning: Caching files between different executors, for example, between Docker and machine, Linux, Windows or macOS, or CircleCI image and non-CircleCI image, can result in file permissions and path errors. These errors are often caused by missing users, users with different UIDs, and missing …

Invalidates gem caches and separates danger and macOS caches

---

Tests/UnitTests/Attribution/AttributionPosterTests.swift

Fixed failing iOS 12 and 13 tests - https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7598/workflows/ba30c2e5-cae0-4a15-837a-8a972821a6b6
Forgot to add `try AvailabilityChecks.iOS14APIAvailableOrSkipTest()` in `IOSAttributionPosterTests`

AdServices: Fix failing tests on main in iOS 12 and 13 - IOSAttributionPosterTests

---

fastlane/Fastfile

This was fixed by @joshdholtz in #1800. However, we created an action to replace text in a list of files so this changes that to use that action.

Replace usages of replace_in with replace_text_in_files action

---

scripts/pre-commit.sh

I noticed this new warning in the `pre-commit` hook:
> warning: The --path option is deprecated. Pass the path(s) to lint last to the swiftlint command.
This fixes that.

`SwiftLint`: fixed deprecation warning

---

Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift

Looks like this is fixed in Xcode 14.0.
`Any` is not `Sendable`, so we need to remove this workaround for [CSDK-379].

`SK2StoreProduct`: conditionally removed `@available` workaround

---

Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
Tests/StoreKitUnitTests/StoreProductTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift

See #1701.
Apple fixed this in beta 5!

`StoreKitConfigTestCase.changeStorefront`: re-enabled on iOS 16

---

.circleci/config.yml
Gemfile.lock
fastlane/Fastfile

Updates to latest fastlane plugin with this change: https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/12. Now we won't validate the current branch when running the `prepare_next_version` lane.

Update to latest fastlane plugin

---

Dangerfile

See also https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/17

`Dangerfile`: added "next_release" as supported label

---

Sources/Purchasing/Purchases/Purchases.swift

Clarifies why it's not available for macCatalyst
improves https://github.com/RevenueCat/react-native-purchases/issues/401

Update documentation for presentCodeRedemptionSheet

---

Sources/Attribution/AttributionFetcher.swift

This removes this unnecessary type in the global namespace.
Also removed 2 `cases` introduced in #1727 that aren't actually used.

Moved `AttributionFetcherError` inside `AttributionFetcher`

---

Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
Tests/StoreKitUnitTests/ProductsManagerTests.swift

Fixed warnings for unnecessary `try`

---

Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift

Not sure how this passes normally in CI (probably only because of retries). It's flaky locally probably because the requests are asynchronous.

`PurchasesAttributionDataTests`: fixed potential race condition in flaky test

---

Sources/Misc/Atomic.swift
Sources/Misc/Lock.swift
Sources/Misc/PriceFormatterProvider.swift
Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift

This class was used all over the place **but it wasn't thread-safe**. The Swift compiler enforces this now that it conforms to Sendable (note it's not unchecked!).
Because `Atomic` guarantees correctness, this thread-safety can be enforced now by the compiler.

`PriceFormatterProvider: Sendable` conformance and fixed thread-safety

---

Sources/FoundationExtensions/Optional+Extensions.swift
Sources/Misc/Atomic.swift
Tests/UnitTests/Mocks/MockDNSChecker.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

Small simplification to make initializing `Atomic<Optional>` easier to create.

`Atomic: ExpressibleByNilLiteral`

---

Sources/Misc/SystemInfo.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

This property is publicly exposed through `Purchases`, but it's mutable state. With the move to `Sendable` we need to enforce correctness.

`SystemInfo.finishTransactions`: made thread-safe
