RevenueCat/purchases-ios

Sources/Identity/CustomerInfoManager.swift, Sources/Purchasing/Purchases/Purchases.swift
Fixes [TRIAGE-55](https://revenuecats.atlassian.net/browse/TRIAGE-55)
Delegate would not always/reliably call `didReceiveUpdatedCustomerInfo`. 
`customerInfoManager.sendCachedCustomerInfoIfAvailable` would only call the delegate when the latest customer info object was already sent.
☝️ This, according to a customer bug report, appears to be a breaking change between v3 and v4. It also appears to be a difference in behavior with `Purchases.shared.customerInfoStream` as this gets the initial customer value. 
```swift
@main
struct PurchaseTesterApp: App {
@UIApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
@State private var revenueCatCustomerData = RevenueCatCustomerData()
var body: some Scene {
WindowGroup {
ContentView()
.environmentObject(revenueCatCustomerData)
.task {
for …
```
=> Directly send delegate customer info when delegate is set (always sends cached CustomerInfo value)

RevenueCat.xcodeproj/project.pbxproj
Starting with `Xcode 14`, building the SDK results in this warning:
> warning build: Run script build phase 'SwiftLint' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
See https://github.com/realm/SwiftLint/issues/4015
We've always linted all files when building, so this isn't a change. In the future we could make this smarter to avoid linting everything all the time, but `SwiftLint` is already pretty fast.
=> `SwiftLint`: fixed build warning

Sources/Misc/Atomic.swift, Sources/Networking/Operations/NetworkOperation.swift, Tests/UnitTests/Mocks/MockDNSChecker.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
=> `Atomic: ExpressibleByBooleanLiteral`

Sources/Caching/DeviceCache.swift, Sources/Misc/SynchronizedUserDefaults.swift
Extracted #1795 to make it easier to review this fix in isolation.
`handleUserDefaultsChanged` isn't guaranteed to be called from any particular thread, so its access to `appUserIDHasBeenSet` wasn't thread-safe.
This is now guaranteed by `Sendable`.
_In theory. In practice we are required to use `@unchecked` for now because of `NotificationCenter` and the class not being `final`. But without those I verified that the class does compile with `Sendable`, which means that there aren't any other potential issues._
=> `DeviceCache`: `Sendable` conformance and fixed thread-safety

scripts/swiftlint.sh
The output of `SwiftLint` is pretty noisy, which sometimes makes it hard to see other build warnings or errors in Xcode:
This removes the "Linting... " lines when ran from Xcode.
=> `SwiftLint`: cleaned up output

RevenueCat.xcodeproj/project.pbxproj, Sources/Networking/IdentityAPI.swift, Tests/UnitTests/Mocks/MockIdentityManager.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Working on [CSDK-394], I realized that `Purchases.logIn` and `Purchases.logOut` had no tests.
[CSDK-394]: https://revenuecats.atlassian.net/browse/CSDK-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Created `PurchasesLoginTests`

Sources/Networking/BackendConfiguration.swift, Sources/Networking/Caching/CallbackCache.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/IdentityAPI.swift, Sources/Networking/OfferingsAPI.swift, Sources/Networking/Operations/GetCustomerInfoOperation.swift
We don't actually need to share a single queue to synchronize all the callback caches.
This new implementation also avoids using the risky `DispatchQueue.sync`.
This also fixes potential issues because `cachedCallbacksByKey` was exposed, and it could have been read without synchronizing access with the queue. This is now impossible.
=> `CallbackCache`: simplified implementation using `Atomic`

Sources/Networking/Caching/CallbackCache.swift
The change in #1834 made this possible because the type is now immutable.
=> `CallbackCache: Sendable` conformance

Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Fixes [CSDK-399]. Follow up to #1828.
Also changed the implementation to remove the `DispatchQueue.async` which wasn't necessary. I think it's reasonable to send the call on the same thread that the `delegate` was set.
[CSDK-399]: https://revenuecats.atlassian.net/browse/CSDK-399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `PurchasesDelegate`: added test for latest cached customer info always being sent

Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md, Sources/Logging/Strings/ConfigureStrings.swift
Fixes [TRIAGE-55](https://revenuecats.atlassian.net/browse/TRIAGE-55)
Turns out the #1828 was not the solution for the delegate not being called. There was an issue in the migration docs with the wrong delegate name for Objective-C types.
=> Update migration doc from didReceiveUpdatedCustomerInfo to receivedUpdatedCustomerInfo

Sources/Identity/CustomerInfoManager.swift, Sources/Networking/Backend.swift, Sources/Networking/BackendConfiguration.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/OfferingsAPI.swift, Sources/Purchasing/OfferingsManager.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockIdentityAPI.swift, Tests/UnitTests/Mocks/MockOfferingsAPI.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS12-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS13-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS14-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS15-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS16-testGetOfferingsCallsHTTPMethodWithRandomDelay.1.json, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Fixes [CSDK-391]. As described in that ticket, calling a method that introduces a random delay before performing an API request could lead to a race condition. Example:
> Request 1: delay 0 seconds. Start now.
> Request 2: delay 2 seconds. Waiting…
> Request 1 finishes.
> Request 2: 2 seconds past. There is no in progress request, so we start it again
This also solves [CSDK-394]. If any part of our code (or users) call a method that would enqueue a request multiple times, we need to insert it into the callback queue right away.
That's what this does: it moves the random delay to *after* the callback has been added to the `CallbackCache`.
[CSDK-391]: https://revenuecats.atlassian.net/browse/CSDK-391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> `Backend`: fixed potential race conditions introduced by `OperationDispatcher.dispatchOnWorkerThread(withRandomDelay:)`

Sources/Misc/Purchases+async.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Fixes [CSDK-113] and https://github.com/RevenueCat/purchases-flutter/issues/403
- SK2 purchase now forwards an error (`ErrorCode.purchaseCancelledError`) if the purchase is cancelled. This matches the behavior in SK1.
- In order to retain the behavior on `async` APIs, this error is ignored if `userCancelled` is `true`, to ensure that `PurchaseResultData` is returned instead of an error being thrown.
Unfortunately, as explained in [CSDK-113], we can't test this because there's no way to fake cancellations (_FB10300403_).
[CSDK-113]: https://revenuecats.atlassian.net/browse/CSDK-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CSDK-113]: https://revenuecats.atlassian.net/browse/CSDK-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> Purchase cancellations: unify behavior between SK1 and SK2

Examples/MagicWeatherSwiftUI/Shared/Sources/ViewModels/UserViewModel.swift, Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift, Examples/MagicWeatherSwiftUI/Shared/Sources/Views/UserView.swift, Examples/MagicWeatherSwiftUI/Shared/Sources/Views/WeatherView.swift
I was testing some of these with a recent change, and I realized that it's probably best to have this example use the "modern" APIs anyway.
Not the best implementation, since we should move these methods to the view model, but this was the simplest way to do it for now without a huge refactor.
It's also not ideal that we were and are ignoring errors, but luckily the SDK logs them.
=> `MagicWeatherSwiftUI`: updated to use `async` APIs

.circleci/config.yml
This should fix https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7845/workflows/c2cbb588-56b3-4357-a244-27735694a957/jobs/34700
=> `release-train`: set `github_rate_limit` to deal with rate limiting

CHANGELOG.md
Changelog in `main` was missing 4.10.1 changelog because it was a hotfix
=> Add 4.10.1 changelog

Contributing/RELEASING.md
After a hotfix is release, the changelog in `main` needs to be updated to include the new version. 
We will be able to automate this at some point, but regular releases are a priority for now
=> Update hotfixes instruction to include updating changelog in main

fastlane/Fastfile
=> `Fastfile`: `test_tvos` lane had duplicate parameter

Sources/Purchasing/Configuration.swift
Fixes [CSDK-418].
[CSDK-418]: https://revenuecats.atlassian.net/browse/CSDK-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `Configuration.with(usesStoreKit2IfAvailable:)`: removed "experimental" warning

Sources/Misc/SystemInfo.swift
Fixes [CSDK-416].
Starting on `watchOS 9.0` (Xcode 14.0), `watchOS` apps can be configured as a single target.
Apps that run in this single-target crash when calling `WKExtension.shared`:
> -[WKExtension init]:62: Critical failure. Simulating crash: Condition failed:"NO". WKExtension is part of WatchKit.framework and can only be instanciated from a WatchKit Extension
To prevent this, we can use `WKApplication` if it's available.
[CSDK-416]: https://revenuecats.atlassian.net/browse/CSDK-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `watchOS`: fixed crash on single-target apps

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Looks like calling `XCTFail` followed by throwing an error was making the test continue for some reason, which was then making it crash instead because `Purchases.shared` isn't set.
By removing the `XCTFail`, `XCTest` now correctly sees this as a test failure and doesn't run the tests.
See also https://github.com/RevenueCat/purchases-hybrid-common/pull/210
=> `IntegrationTests`: actually fail test if tests aren't configured

Examples/MagicWeather/README.md, README.md
Main README and MagicWeather README updated to be consistent with docs in purchases-android repository.
- [ x ] If applicable, unit tests
- [ x ] If applicable, create follow-up issues for `purchases-android` and hybrids
These are minor formatting tweaks that will make the READMEs more consistent with the purchases-android READMEs.
Most changes include moving the order of the information or adding a link to docs.revenuecat.com
I don't know how to test a readme 🙃
=> README updates

Sources/FoundationExtensions/Array+Extensions.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift, Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift, Tests/StoreKitUnitTests/ProductsManagerTests.swift, Tests/StoreKitUnitTests/StoreProductTests.swift, Tests/UnitTests/FoundationExtensions/ArrayExtensionsTests.swift, Tests/UnitTests/Networking/Responses/PostOfferDecodingTests.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
Simplifies the common pattern in tests:
```swift
expect(array).to(haveCount(1))
let element = try XCTUnwrap(array.first)
```
Into simply:
```swift
let element = try XCTUnwrap(array.onlyElement)
```
=> Added `Collection.onlyElement`

Sources/Identity/CustomerInfo.swift, Sources/Purchasing/EntitlementInfo.swift, Sources/Purchasing/EntitlementInfos.swift, Sources/Purchasing/NonSubscriptionTransaction.swift, Sources/Purchasing/PurchaseOwnershipType.swift
The type is now immutable, so the compiler ensures it's thread-safe.
Extracted from #1795 to make it easier to review this in isolation.
=> `CustomerInfo: Sendable` conformance

Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift, Sources/LocalReceiptParsing/Builders/ASN1ObjectIdentifierBuilder.swift, Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift, Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift, Sources/LocalReceiptParsing/ReceiptParser.swift, Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift, Tests/UnitTests/LocalReceiptParsing/Builders/ASN1ObjectIdentifierBuilderTests.swift, Tests/UnitTests/LocalReceiptParsing/ReceiptParserTests.swift, Tests/UnitTests/Mocks/MockReceiptParser.swift
Extracted from #1795 to make it easier to review this in isolation.
Also made `ASN1ObjectIdentifierBuilder` an `enum` since we don't need to create instances of it to use it.
=> `ReceiptParser: Sendable` conformance

Sources/Purchasing/Offering.swift, Sources/Purchasing/Package.swift, Sources/Purchasing/PackageType.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift, Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift, Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
The type is now immutable, so the compiler ensures it's thread-safe.
Extracted from #1795 to make it easier to review this in isolation.
=> `Offering`/`StoreProductType`: `Sendable` conformance

Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Fixes [CSDK-432].
The SK1 implementation [was checking](https://github.com/RevenueCat/purchases-ios/blob/39746c7e2a3f2ad3ba491cd1c5bbb3643e4aac89/Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift#L161) if the product actually had an intro offer.
However, the SK2 version only checked if `Product` had a `SubscriptionInfo`, and relied on `isEligibleForIntroOffer`. But we needed to verify that the `SubscriptionOffer` actually contained an `introductoryOffer`.
[CSDK-432]: https://revenuecats.atlassian.net/browse/CSDK-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `TrialOrIntroPriceEligibilityChecker`: return `.noIntroOfferExists` if the product has no introductory offer

.circleci/config.yml
Fixes [CSDK-221].
SPM requires explicit `import Foundation` statements. Missing these could go unnoticed, so this new step will ensure that we don't break compilation with SPM.
- Example of [successful build](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7913/workflows/129b5e08-cdbe-4b3e-8606-8709655df205/jobs/35323/parallel-runs/0/steps/0-107).
- Example of [failed build from a missing `import Foundation`](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7914/workflows/4296ba99-f966-40d0-8fac-f8ece4db39aa/jobs/35329/parallel-runs/0/steps/0-102
).
[CSDK-221]: https://revenuecats.atlassian.net/browse/CSDK-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `CircleCI`: added job for building SDK with `SPM`

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Purchases+nonasync.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Fixes [CSDK-218].
The underlying implementation provided by Apple is `async` only, which is still available to Objective-C. However, to be able to use it from Swift, it must be used with `await`.
This exposes an overload that allows using it with a completion-block based API. Because we don't need these in Objective-C (those are already available), these blocks can use the Swift-only `Result`.
[CSDK-218]: https://revenuecats.atlassian.net/browse/CSDK-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added `beginRefundRequest` overload with completion block

Sources/Misc/Purchases+async.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes #1868.
See https://github.com/RevenueCat/purchases-ios/issues/1868#issuecomment-1229614774 for a summary of the changes in #1841.
- SK1 / completion-block: no `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- SK1 / `async`: thrown `ErrorCode.purchaseCancelledError`
- SK2 / completion-block: `CustomerInfo` + cancelled + no error
- SK2 / `async`: `CustomerInfo` + cancelled (not error)
- SK1 / completion-block:  no `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- SK1 / `async`: no `CustomerInfo` + ignored error -> crash! :rotating_light:
- SK2 / completion-block: `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- SK2 / `async`: `CustomerInfo` + cancelled (not error)
- SK1 / completion-block:  no `CustomerInfo` + cancelled + …
=> Fixed crash on `async` SK1 cancelled purchase

Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
This is a key part of how we document error handling in [`V4_API_Migration_guide.md`](https://github.com/RevenueCat/purchases-ios/blob/4.10.3/Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md#error-handling).
I'm working on an error type-safety refactor that broke this invariant, which wasn't covered in any test.
=> `ErrorUtils`: added test to verify that returned errors can be converted to `ErrorCode`

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
We currently were only using the `purchase(package:)` method. This adds another test (for SK1 and SK2) using `purchase(product:)`.
=> `Integration Tests`: added test for purchasing `StoreProduct` instead of `Package`

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Logger.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift, Tests/UnitTests/TestHelpers/Box.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
We had this fragile pattern in several tests:
```swift
var loggedMessages = [String]()
let originalLogHandler = Logger.logHandler
defer { Logger.logHandler = originalLogHandler }
Logger.logHandler = { _, message, _, _, _ in
loggedMessages.append(message)
}
```
Which was too verbose and error prone.
This new type works like an RAII type. Its lifetime scopes the messages that are observed, so simply having a reference around for the lifetime of the test allows observing only those messages.
This much simpler abstraction will make it easier for us to test more of what's logged by the SDK.
- Initialize in `setUp`:
```swift
private var testLogHandler: TestLogHandler!
override func setUp() {
super.setUp()
self.testLogHandler = TestLogHandler()
}
override func tearDown() {
self.testLogHandler = …
```
=> Introduced `TestLogHandler` to simplify how we test logged messages

README.md
Just unifying the format of the links to SDK reference docs everywhere. They'll have one at the top and another one near the bottom.
=> add link to SDK reference

Sources/Logging/Strings/ConfigureStrings.swift, Sources/Misc/SystemInfo.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
Fixes [CSDK-461].
[CSDK-461]: https://revenuecats.atlassian.net/browse/CSDK-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `HTTPClient`: added `X-Client-Bundle-ID` and logged on SDK initialization

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
Fixes [CSDK-454].
This should reduce a lot of the noise during initialization. The internal backing property was already `Bool?`, so we can check if it was ever set, and if not, not log anything.
Using `TestLogHandler` introduced in #1858 to verify this behavior.
[CSDK-454]: https://revenuecats.atlassian.net/browse/CSDK-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `PurchasesOrchestrator`: don't log warning if `allowSharingAppStoreAccount` setting was never explicitly set

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/StoreKitStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift, Sources/Purchasing/StoreKit1/StoreKitWrapper.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Purchasing/StoreKitWrapperTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
When SK2 is enabled, `StoreKit2TransactionListener` is enough to handle transactions, so it's no longer necessary to have that and `StoreKitWrapper` both listening to them.
Depends on #1881 and #1879.
=> Disable SK1's `StoreKitWrapper` if SK2 is enabled and available

Sources/Logging/Strings/OfferingStrings.swift, Sources/Purchasing/Offering.swift
Fixes [CSDK-450].
We were logging a message for packages with custom duration that says "Unknown subscription length for package, ignoring."
This is very confusing for customers, as it looks like something is wrong. However it’s expected and normal behavior for packages with custom duration.
[CSDK-450]: https://revenuecats.atlassian.net/browse/CSDK-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `Offering`: improved confusing log for `PackageType.custom`

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Deprecations.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Mocks/MockStoreKitWrapper.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift, Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Follow up to #1882. Now that `StoreKit1Wrapper` is not initialized for SK2, it makes sense to clarify that this class is only for SK1.
This is just a simple find-replace.
=> Renamed `StoreKitWrapper` to `StoreKit1Wrapper`

Sources/Error Handling/BackendError.swift, Sources/Identity/CustomerInfoManager.swift, Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/Purchasing/OfferingsManager.swift
Improved these 2 logs:
> 🍎‼️ Error fetching offerings - The operation couldn’t be completed. (RevenueCat.OfferingsManager.Error error 0.)
Underlying error: The operation couldn’t be completed. (RevenueCat.BackendError error 0.)
> ⚠️ Attempt to update CustomerInfo from network failed.
The operation couldn’t be completed. (RevenueCat.BackendError error 0.)
These 2 now will display the underlying `NetworkError` instead of the opaque "(RevenueCat.BackendError error 0.)".
=> `CustomerInfoManager`/`OfferingsManager`: improved display of underlying errors

Sources/Misc/SystemInfo.swift
Follow up to #1849. That fix was incomplete, and still crashed when ran before watchOS 9.0.
Fixes [SDKONCALL-119] and [CSDK-416] and #1891.
There are 3 variables we need to take into account:
- `watchOS` version
- Xcode version
- Dual/single target app
| watchOS       | Xcode     | Dual / Single target | Before PR          | With this PR      |
|---------------|-----------|----------------------|--------------------|-------------------|
| < 9.0         | < 14.x    | Single               | `WKExtension`      | `WKExtension`     |
| < 9.0         | < 14.x    | Dual                 |  N/A               |     N/A           |
| < 9.0         | >= 14.0   | Single               | crash :warning:    |  always `false`   |
| < 9.0         | >= 14.0   | Dual                 | `WKApplication`    | …
=> `watchOS`: fixed crash when ran on single-target apps with Xcode 14 and before watchOS 9.0

Tests/InstallationTests/CarthageInstallation/CarthageInstallation.xcodeproj/project.pbxproj, Tests/InstallationTests/CarthageInstallation/CarthageInstallation.xcodeproj/xcshareddata/xcschemes/CarthageInstallation.xcscheme
For #1890.
The failure was likely because the simulators had a dialog which was blocking the tests from continuing. In order to fix that, I removed the test host from the target, which was never necessary and will make running these tests a bit faster.
- `CarthageInstallation`: removed unnecessary `FRAMEWORK_SEARCH_PATHS`
- Removed test host
- Added single scheme with `test` action
=> Fixed `CarthageInstallation` tests

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
`verifyEntitlementWentThrough` was only looking for an entitlement inside of `EntitlementInfos.all`, but not verifying that it's active.
=> `Integration Tests`: actually verify that entitlement is active

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Follow up to #1880. The duplicated and unnecessary `verifyEntitlementWentThrough` (that's already done by `purchaseWeeklyOffering`) didn't pass the new `verifyEntitlementIsActive`, which lead to false negatives due to the short expiration rate in weekly subscriptions.
=> `IntegrationTests`: simplified `testExpireSubscription` to fix flaky test

Sources/Purchasing/Purchases/Purchases.swift
These are only used for tests, so we don't need to compile them in the final binary.
=> `Purchases`: only expose testing data on `DEBUG`

.circleci/config.yml
See #1860.
We want to ensure that the framework can be correctly compiled with SPM, so I think it makes sense to ensure that the _RELEASE_ version of it can be compiled specifically.
We have a lot of coverage of `DEBUG` builds basically by most other CI jobs, so this provides coverage of the release build as well.
See #1902 for example for the type of change that could break release builds if not covered in CI.
=> `spm build` CI job: changed to release build

Tests/UnitTests/Misc/AtomicTests.swift
I'm relying on this behavior in an upcoming change so I wanted to make sure this worked as expected.
=> `Atomic`: added unit test to verify `value`'s setter

.circleci/config.yml
Now that [Xcode 14 RC](https://discuss.circleci.com/t/xcode-14-rc-released/45334) is out, we should make it the default for all the jobs moving forward.
=> `CircleCI`: changed all jobs to use Xcode 14

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
Using `init` in the `@main` app is the `SwiftUI` way of setting up `Purchases`
=> `PurchaseTesterSwiftUI`: removed unnecessary `UIApplicationDelegate`

.circleci/config.yml
Looks like this broke in #1909. Not sure why it's not finding those simulators, but we can just run those old versions with an older Xcode for now.
=> `CircleCI`: changed iOS 12/13 to use Xcode 13

Tests/TestingApps/PurchaseTester/PurchaseTester/Constants.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Constants.swift, scripts/pre-commit.sh
=> `pre-commit` hook: also verify leftover API keys in `PurchaseTester`

Sources/Error Handling/ErrorUtils.swift, Sources/Misc/Purchases+nonasync.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
This was missed in #1879. Without this, we might have been forwarding some private errors instead of ensuring that we only sent `CodeError`s
=> `Purchases.beginRefundRequest`: ensured errors are `PublicError`

Sources/Networking/Caching/CustomerInfoCallback.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/Operations/GetCustomerInfoOperation.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Fixes [CSDK-419].
This is an improvement over the fix in #1292. In there, we avoided appending on an existing `CustomerInfoOperation` if there were any `PostReceiptDataOperation`s in progress, because those might come back with outdated entitlements.
This fix removes that cache key hack, and instead *reuses* the entire response to that `PostReceiptDataOperation` by "stealing" that request's cache key.
This is perfectly captured by the existing test `BackendPostReceiptDataTests.testGetsUpdatedSubscriberInfoAfterPost`, added in #1292. Amazingly enough, that test still passes with one minor change: the entire process requires one fewer API call :tada: 🐼
[CSDK-419]: https://revenuecats.atlassian.net/browse/CSDK-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
=> `GetCustomerInfoAPI`: avoid making a request if there's any `PostReceiptDataOperation` in progress

Sources/FoundationExtensions/OperationQueue+Extensions.swift, Sources/Logging/Strings/NetworkStrings.swift, Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS12-testRepeatedRequestsLogDebugMessage.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS13-testRepeatedRequestsLogDebugMessage.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS14-testRepeatedRequestsLogDebugMessage.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS15-testRepeatedRequestsLogDebugMessage.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS16-testRepeatedRequestsLogDebugMessage.1.json, Tests/UnitTests/TestHelpers/TestLogHandler.swift
Right now there is no way to know when a request is being reused. If this were to lead to a hard to debug issue, at lease we'll now have evidence for this in the logs.
=> `OperationQueue`: log debug message when requests are found in cache and skipped

Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
This will help us debug flaky tests.
Example:
> INFO: 😻💰 Purchased product - 'com.revenuecat.monthly_4.99.1_week_intro'
DEBUG: ℹ️ Force refreshing the receipt to get latest transactions from Apple.
DEBUG: ℹ️ Loaded receipt from url file:///Users/nachosoto/Library/Developer/CoreSimulator/Devices/A3576DC2-355E-45BA-B32C-D2C0A3811BB4/data/Containers/Data/Application/EDF3B7C8-A4BD-4629-813E-0934528AF02E/StoreKit/receipt
INFO: ℹ️ Receipt parsed successfully
INFO: ℹ️ Receipt content:
["inAppPurchases": [], "creationDate": 2022-09-21 21:00:07 +0000, "opaqueValue": 8 bytes, "applicationVersion": "1", "originalApplicationVersion": "<unknown>", "bundleId": "com.revenuecat.StoreKitTestApp", "expirationDate": 4001-01-01 00:00:00 +0000, "sha1Hash": 20 bytes] …
=> `StoreKitIntegrationTests`: print `AppleReceipt` data whenever `verifyEntitlementWentThrough` fails

Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
This is a key part of how we document error handling in the SDK, so it's important that it's covered in a test.
The second test also verifies that this same error contains all the metadata.
This is a follow up to #1879.
=> `ErrorUtils`: added test to verify that `PublicError`s can be `catch`'d as `ErrorCode`

Tests/TestPlans/CI-BackendIntegration.xctestplan
I've observed that a lot of the time flaky tests still don't pass after a retry.
This change can probably decrease the likelyhood that a retry will still fail, by ensuring that we create a brand new `SKTestSession` in a new simulator session.
=> `Integration Tests`: relaunch tests when retrying failures

RevenueCat.xcodeproj/project.pbxproj
[The new 1.10.0 version](https://github.com/pointfreeco/swift-snapshot-testing/releases/tag/1.10.0) requires iOS 13+, which is making CI builds all fail.
We'll be able to upgrade when we drop support for those version, but for now we're stuck with `1.9.0`
=> `SnapshotTesting`: require version 1.9.0 to keep supporting iOS 12/13 tests

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Misc/Deprecations.swift, Sources/Misc/StoreKit2Setting.swift, Sources/Purchasing/Configuration.swift, Tests/UnitTests/Misc/StoreKit2SettingTests.swift
The main change is `StoreKit2Setting.default` is now `enabledForCompatibleDevices`, but I've also made sure that all places in the codebase are derived from this value.
=> `StoreKit 2`: enabled by default

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes [CSDK-464]. Follow up to #1869.
SK1 and SK2 had inconsistent behavior during cancelled purchases.
- SK1 / completion-block:  no `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- **SK1 / `async`: thrown `ErrorCode.purchaseCancelledError`** :warning:
- SK2 / completion-block: `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- SK2 / `async`: `CustomerInfo` + cancelled (not error)
The output is now consistent across the board:
- SK1 / completion-block:  `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- SK1 / `async`: `CustomerInfo` + cancelled (not error)
- SK2 / completion-block: `CustomerInfo` + cancelled + `ErrorCode.purchaseCancelledError`
- SK2 / `async`: `CustomerInfo` + cancelled (not error)
This is of course a somewhat backwards …
=> `StoreKit 1`: changed result of cancelled purchases to be consistent with `StoreKit 2`

Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift, Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift, Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift, Tests/UnitTests/LocalReceiptParsing/Builders/AppleReceiptBuilderTests.swift, Tests/UnitTests/LocalReceiptParsing/Builders/InAppPurchaseBuilderTests.swift, Tests/UnitTests/TestHelpers/ContainerFactory.swift
Before this change we had a lot of global types. Now they're all nested inside of `AppleReceipt`, `InAppPurchase`, and `InAppPurchaseBuilder`.
=> `AppleReceipt`: refactored declarations into nested types

Sources/Logging/Logger.swift
Defining the property "twice" was a big weird and hard to read. Now `logLevel` is only defined once, with the default value extracted into a separate method.
=> `Logger`: refactored default `LogLevel` definition

Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Follow up to #1922. Most of the tests from the subclasses assume SK2 is disabled. This changes the default for those back to SK1.
The tests that do require SK2, define so explicitly.
I also replaced a bunch of force-unwraps with `XCTUnwrap` so tests don't crash (which is what was happening when running these tests with SK2 enabled).
=> `BasePurchasesTests`: changed default back to SK1

Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, fastlane/Fastfile
The test introduced by #1926 passed locally, but sometimes failed in CI due to a race condition.
What we're testing is that the second request reuses the callback of the first one, **if called while the first one is still in progress**. However, nothing in the test ensures that's the case.
This introduces an optional delay in `MockHTTPClient` so we can ensure that.
Another reason that test was failing randomly is because we had another test modifying global state, which interferes with every other test. We run tests in parallel, so it was making the new test that requires `debug` logs to fail randomly, if this test happened to run before.
_Note: because of the nature of these 2 tests, they don't actually wait for the whole response to finish, so they still pass in ~0.006s_
=> `CacheableNetworkOperation`: fixed race condition in new test

Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetOfferingsTests/iOS12-testRepeatedRequestsLogDebugMessage.1.json
I blindly copy-pasted this snapshot and forgot that iOS 12 has different formatting. This was wrong in #1926.
It wasn't caught originally because we hadn't been running tests on iOS 12 until #1928.
=> Fixed iOS 12 tests

Sources/FoundationExtensions/JSONDecoder+Extensions.swift, Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift, Sources/LocalReceiptParsing/ReceiptParser.swift, Sources/Logging/Strings/ReceiptStrings.swift, Sources/Networking/Operations/NetworkOperation.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift, Tests/UnitTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift
For [CSDK-478].
Follow up to #1929.
> DEBUG: ℹ️ PostReceiptDataOperation: Started
INFO: ℹ️ Receipt parsed successfully
DEBUG: ℹ️ PostReceiptDataOperation: Posting receipt: {
"opaque_value" : "Rn\/39QYAAAA=",
"sha1_hash" : "Ii8Z7ocZm524eJcWFOvVauNrNHs=",
"bundle_id" : "com.revenuecat.StoreKitTestApp",
"in_app_purchases" : [
{
"quantity" : 1,
"product_id" : "com.revenuecat.monthly_4.99.1_week_intro",
"purchase_date" : "2022-09-27T19:09:47Z",
"transaction_id" : "0",
"is_in_intro_offer_period" : true,
"expires_date" : "2022-09-27T19:09:57Z"
}
],
"application_version" : "1",
"creation_date" : "2022-09-27T19:09:47Z",
"expiration_date" : "4001-01-01T00:00:00Z"
}
DEBUG: ℹ️ There are no requests currently running, starting request POST receipts
DEBUG: ℹ️ API request started: POST /v1/receipts …
=> `PostReceiptDataOperation`: print receipt data if `debug` logs are enabled

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/AsyncExtensions.swift, Sources/Misc/Purchases+nonasync.swift, Sources/Purchasing/ProductsManager.swift, Sources/Purchasing/TransactionsManager.swift, Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift, Sources/Support/ManageSubscriptionsHelper.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/StorefrontAPI.swift, Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
Created `Async` with some shared methods that make this conversion simpler in a type-safe way.
Helps turn this:
```swift
_ = Task<Void, Never> {
do {
completion(.success(try await f()))
} catch {
completion(.failure(ErrorUtils.error())
}
}
```
Into this:
```swift
Async.call(with: completion) {
try await f()
}
```
=> Abstracted conversion from `async` to completion-block APIs

Sources/Purchasing/ReceiptFetcher.swift
I'm considering adding a 4th `ReceiptRefreshPolicy` that re-fetches the receipt N-times until it finds a transaction for a recently purchased product ([CSDK-478]).
This will make it easier to implement.
[CSDK-478]: https://revenuecats.atlassian.net/browse/CSDK-478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Refactored `ReceiptFetcher.receiptData`

RevenueCat.xcodeproj/project.pbxproj, Sources/Purchasing/CachingProductsManager.swift, Sources/Purchasing/IntroEligibilityCalculator.swift, Sources/Purchasing/OfferingsManager.swift, Sources/Purchasing/ProductsManager.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift, Tests/StoreKitUnitTests/ProductsManagerTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreKit2CachingProductsManagerTests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift, Tests/UnitTests/Mocks/MockProductsManager.swift, Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes [SDKONCALL-129].
The main feature that this change introduces is providing a _request_ cache to `ProductsFetcherSK2` (like `ProductsFetcherSK1` has).
It already implements a _product_ cache, but concurrent requests for the same products result in fetching those multiple times. It does not cache products until they're done being fetched.
This was observed in the logs when doing something simple like purchasing a product. This is running `testCanPurchaseProduct` integration test:
> DEBUG: ℹ️ No existing products cached, starting store products request for: ["com.revenuecat.monthly_4.99.1_week_intro", "com.revenuecat.annual_39.99.2_week_intro", "com.revenuecat.weekly_1.99.3_day_intro"]
DEBUG: ℹ️ No existing products cached, starting store products request for: …
=> Created `CachingProductsManager` to provide consistent caching logic when fetching products

Sources/Purchasing/ProductsManager.swift, Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift, Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift, Tests/StoreKitUnitTests/ProductsFetcherSK2Tests.swift, Tests/StoreKitUnitTests/StoreProductTests.swift
Follow up to #1907.
This logic is now implemented and shared in `CachingProductsManager`.
I've decided to keep the logic in `ProductsFetcherSK1` because it's intertwined with the retry mechanism, and it wasn't trivial to remove caching while leaving that logic.
=> `ProductsFetcherSK2`: removed now redundant caching logic

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Fixes [CSDK-479].
- Removed extra `verifyEntitlementWentThrough`. #1880 introduced a change so that weekly subscriptions aren't verified, because they expire within a second. This make the test flaky due to that race condition.
- Removed `assertNoActiveSubscription`: I tried calling `SKTestSession.disableAutoRenewForTransaction`, but sometimes the server still thinks the subscription has auto-renewed. This was making the test flaky. Turns out that even if it's not active, the eligibility test still passes as expected.
- Removed call to `syncPurchases`. It doesn't matter what state the server is in, as long as locally `SKTestSession` has an expired subscription.
This, together with #1945, should fix the last of the issues causing flaky integration tests 🤞🏻
[CSDK-479]: …
=> `Integration Tests`: simplified `testIneligibleForIntroAfterPurchaseExpires` to fix flakiness

Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
This way it's more clear which methods belong to which protocol.
This confusion is what lead to #1901 being wrong (will fix in a separate PR).
=> `StoreKit1Wrapper`: separated `SKPaymentTransactionObserver` and `SKPaymentQueueDelegate` implementations

RevenueCat.xcodeproj/project.pbxproj, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift, Tests/UnitTests/Mocks/MockPaymentQueue.swift, Tests/UnitTests/Purchasing/PaymentQuueWrapperTests.swift, Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Follow up to #1901. That fix was incomplete. I missed it because the protocols were mixed up (fixed in #1961). Now `PaymentQueueWrapper`, when set up as the delegate (only when SK2 is enabled and SK1 is disabled) will be added as a transaction observer.
=> `PaymentQueueWrapper`: also conform to `SKPaymentTransactionObserver` to fix promoted purchases

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Data+Extensions.swift, Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift, Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift, Sources/Logging/Strings/ReceiptStrings.swift, Sources/Misc/DangerousSettings.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/ReceiptFetcher.swift, Sources/Purchasing/ReceiptRefreshPolicy.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/LocalReceiptParsing/AppleReceiptTests.swift, Tests/UnitTests/Misc/SystemInfoTests.swift, Tests/UnitTests/Mocks/MockBundle.swift, Tests/UnitTests/Mocks/MockReceiptParser.swift, Tests/UnitTests/Mocks/MockRequestFetcher.swift, Tests/UnitTests/Mocks/MockSystemInfo.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Fixes [CSDK-478]
~~Depends on #1941, #1942, and #1943.~~
Log of a successful purchase after retrying 🎉 
> INFO: 💰 Purchasing Product 'com.revenuecat.monthly_4.99.1_week_intro'
DEBUG: ℹ️ Loaded receipt from url file:///Users/nachosoto/Library/Developer/CoreSimulator/Devices/A3576DC2-355E-45BA-B32C-D2C0A3811BB4/data/Containers/Data/Application/7ACD12DA-2A12-4CF1-8A76-8295E40B64EF/StoreKit/receipt
INFO: ℹ️ Receipt parsed successfully
WARN: 🍎‼️ Local receipt is still missing purchase for 'com.revenuecat.monthly_4.99.1_week_intro': 
{
"opaque_value" : "79v2XwwAAAA=",
"sha1_hash" : "GhOmfuioo2Z4R3zX8K60l4b0qgs=",
"bundle_id" : "com.revenuecat.StoreKitTestApp",
"in_app_purchases" : [
{
"quantity" : 1,
"product_id" : "com.revenuecat.monthly_4.99.1_week_intro",
"purchase_date" : …
=> `ReceiptFetcher`: added retry mechanism

.circleci/config.yml
Adds two approval jobs and a Slack notification posted to the `#sdk-prs` channel. After this is merged, it can be moved to the orb so it can be shared across all repos
[CSDK-420]
[CSDK-420]: https://revenuecats.atlassian.net/browse/CSDK-420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remind about updating docs and parity spreadsheet on minor releases

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift
Follow up to #1962. This is also needed when `StoreKit1Wrapper` is not setup (see #1882).
=> `PaymentQueueWrapper`: also implement `shouldShowPriceConsent`

Sources/FoundationExtensions/AsyncExtensions.swift, Sources/Purchasing/ProductsManager.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift, Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift, Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
This simplifies calling completion-block APIs as `async`. The opposite of what #1943 introduced.
=> `Async.call` method to convert completion-block call to `async`

Sources/Networking/Caching/CallbackCache.swift, Sources/Networking/Caching/CustomerInfoCallback.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/IdentityAPI.swift, Sources/Networking/OfferingsAPI.swift
This is the Swifty way to avoid the duplication in `cache.add(callback: callback)`.
=> Renamed `CallbackCache.add(callback:)`

Sources/Error Handling/ErrorUtils.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
This allows methods throwing something like `BackendError` and converting it to `PurchasesError` automatically.
=> `ErrorUtils.purchasesError(withUntypedError:)` handle `PurchasesErrorConvertible`

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Deprecations.swift, Sources/Misc/Either.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Misc/EitherTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
This is a follow up to #1901 and #1882. Depends on #1967.
Essentially before this change, `Purchases` had both `StoreKit1Wrapper?` and a `PaymentQueueWrapper`. The later wasn't actually needed when the first was not-nil, so it was essentially storing `(a?, b?)`. What we really wanted to express is that it could have one OR the other.
This introduces `Either` to express this requirement in the type system, as well as `PaymentQueueWrapperType` that will be used to fix #1964.
=> `PaymentQueueWrapper`: improved abstraction for active `SKPaymentQueue` wrapper

Sources/Error Handling/ErrorUtils.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
- `Error.localizedDescription` now matches the message being logged. Improvements introduced in #1776, for example, now apply to the description too.
- Logged `BackendError` messages now include underlying error.
The following errors are improved:
- Before:
>  😿‼️ There was an unknown backend error.
- After:
> 😿‼️ There was an unknown backend error. Page not found
- Before:
> 😿‼️ There was a credentials issue. Check the underlying error for more details.
- After:
> 😿‼️ There was a credentials issue. Check the underlying error for more details. Invalid API key
- Before:
> ["$email": "invalid"]
- After:
> One or more of the attributes sent could not be saved. ["$email": "invalid"]
=> `ErrorUtils`: improved logging and `localizedDescription` to include underlying errors

Sources/Logging/Strings/OfferingStrings.swift, Sources/Misc/Purchases+async.swift, Sources/Purchasing/OfferingsManager.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Mocks/MockOfferingsManager.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
The default behavior is unchanged: if any products aren't found, those are logged, but an `Offerings` value is returned with the found products.
This introduces a new `OfferingsManager.FetchPolicy` that allows receiving an error if any product is not found. For the time being, this is `internal` only, and will be used for [CSDK-451], since we don't want to ignore those errors when using this new SDK tester.
[CSDK-451]: https://revenuecats.atlassian.net/browse/CSDK-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `OfferingsManager`: added ability to fail if any product is not found

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Misc/Deprecations.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit, Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes #1964, [TRIAGE-134], [TRIAGE-131], and possibly [TRIAGE-82].
Depends on #1967, #1968.
- For `SK2` purchases we were never finishing transactions. We are now.
- For `SK1` purchases, transactions were finished _after_ the completion block was invoked (and tests were very lenient checking that _eventually_ this happened). This could have lead to race conditions.
- For SK2 only (at least in `SKTestSession`s), this fixes the ability to purchase multiple consumable purchases.
This is the log from the failing test using SK2:
<details>
<summary>Open</summary>
```
2022-10-06 15:18:52.286813-0700 BackendIntegrationTestsHostApp[45464:7076968] [Purchases] - DEBUG: ℹ️ API request started: GET /v1/subscribers/$RCAnonymousID:6f630d50b8294288a2d0862629d766fb/offerings
2022-10-06 …
```
=> Purchasing: fixed consumable purchases by fixing transaction-finishing

Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
I broke this in an earlier PR but we didn't notice because we don't compile that on every PR. I filed [TRIAGE-82] for that.
This fixes the rest of the release checks in #1980.
[TRIAGE-82]: https://revenuecats.atlassian.net/browse/TRIAGE-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed `Mac Catalyst` build

Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
This is similar to #1894, but as a permanent change.
This used to always default to the SK2 implementation if it was available because it was much more reliable.
However, as we've learned (#1893), it can be significantly slow.
Until we implement caching for it ([CSDK-493]), this for now allows users to disable it if it's too slow.
For users that don't specify `useSk2IfAvailable`, SK2 is now the new default, so this class will continue to use the "better" implementation for them too.
[CSDK-493]: https://revenuecats.atlassian.net/browse/CSDK-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `TrialOrIntroPriceEligibilityChecker`: only use SK2 implementation if enabled

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Result+Extensions.swift, Sources/Networking/Backend.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPRequest.swift, Sources/Networking/InternalAPI.swift, Tests/UnitTests/FoundationExtensions/ResultExtensionsTests.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Networking/Backend/BackendInternalTests.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS12-testHealthRequestIsNotAuthenticated.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS12-testHealthRequestWithFailure.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS12-testHealthRequestWithSuccess.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS13-testHealthRequestIsNotAuthenticated.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS13-testHealthRequestWithFailure.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS13-testHealthRequestWithSuccess.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS14-testHealthRequestIsNotAuthenticated.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS14-testHealthRequestWithFailure.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS14-testHealthRequestWithSuccess.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS15-testHealthRequestIsNotAuthenticated.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS15-testHealthRequestWithFailure.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS15-testHealthRequestWithSuccess.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS16-testHealthRequestIsNotAuthenticated.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS16-testHealthRequestWithFailure.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendInternalTests/iOS16-testHealthRequestWithSuccess.1.json, Tests/UnitTests/Networking/HTTPRequestTests.swift
For [CSDK-451].
Depends on #1969 and #1970.
- Allow `HTTPRequest.Path`s to be non-authenticated
[CSDK-451]: https://revenuecats.atlassian.net/browse/CSDK-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Created `InternalAPI` for "health" request

Sources/Logging/Strings/IdentityStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
This only works in `Swift`, but it can be useful to catch incorrect usages of `logIn`, where a user might accidentally pass the api key, or some other key known at compile time.
=> `Purchases.logIn`: log warning if attempting to use a static `appUserID`

RevenueCat.xcodeproj/project.pbxproj
It raised the deployment target so we can't use `main` anymore.
=> `Nimble`: use a fixed version

.circleci/config.yml
That's already part of `install-dependencies`.
=> CI: removed redundant `swiftlint` installation

.circleci/config.yml, fastlane/Fastfile
Fixes [CSDK-508].
#1912 moved all the docs to the `protocol`. The generated docs locally were correct, so I didn't notice that [the online docs](https://revenuecat.github.io/purchases-ios-docs/4.13.2/documentation/revenuecat/purchases/offerings()) were wrong.
I checked and Xcode was generating them with an extra parameter:
This is also [documented](https://www.swift.org/documentation/docc/documenting-a-swift-framework-or-package), and it works like magic.
`--enable-inherited-docs` doesn't seem to be needed to fix this, but it doesn't hurt to be explicit.
[CSDK-508]: https://revenuecats.atlassian.net/browse/CSDK-508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Documentation: fixed missing docs from inherited symbols

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/TransactionsView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/PromoOfferDetailsView.swift
Fixing warnings before working on a few improvements
=> `PurchaseTesterSwiftUI`: fixed warnings and simplified code using `async` methods

.circleci/config.yml, fastlane/Fastfile
It contains the updated `macOS` SDK so we should be able to use it for most jobs.
#1990 will ensure that we maintain backwards compatibility with the oldest Xcode version we support.
I disabled `watchOS` from `check_pods` until https://github.com/CocoaPods/CocoaPods/issues/11558 is fixed.
=> CI: use `Xcode 14.1`

Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md, Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
These became ambiguous after #1958.
=> Docs: fixed `logIn` references

Sources/Networking/Operations/NetworkOperation.swift
This _might_ fix [CSDK-503].
The latest stacktrace provided gave me a clue:
```
Fatal error: Should never be reached: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_overlay_Foundation_Device/swiftlang-1001.2.63.13/swift/stdlib/public/SDK/Foundation/NSObject.swift, line 46
0xa3d10 @objc static NSObject.__old_unswizzled_keyPathsForValuesAffectingValue(forKey:) + 84
53  libswiftFoundation.dylib       0xa436c static __KVOKeyPathBridgeMachinery.keyPathsForValuesAffectingValue(forKey:) + 272
64  libswiftFoundation.dylib       0xa4864 @objc static __KVOKeyPathBridgeMachinery.keyPathsForValuesAffectingValue(forKey:) + 88
```
That crash is coming from [here](https://github.com/apple/swift-corelibs-foundation/blob/swift-DEVELOPMENT-SNAPSHOT-2022-10-24-a/Darwin/Foundation-swiftoverlay …
=> `NetworkOperation`: workaround for iOS 12 crashes

.github/ISSUE_TEMPLATE/bug_report.md
Now that SK2 is enabled by default (#1922) this makes more sense.
=> `bug_report.md`: changed SK2 wording

.circleci/config.yml
Equivalent of https://github.com/RevenueCat/purchases-android/pull/644/files
Fixes two things:
- Makes sure installation tests pass before deploying anything
- Prevents installation tests from running also when the branch is tagged (after the hold job is approved), which was unnecessary and caused unnecessary waiting time
=> Makes hold job wait for installation tests to pass

Tests/TestingApps/PurchaseTesterSwiftUI/Constants.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Identifiable.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Fixes [CSDK-456].
_Note that if you enter an invalid API key and there's a credentials issue, you can tap on "reconfigure" to start over:
[CSDK-456]: https://revenuecats.atlassian.net/browse/CSDK-456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `PurchaseTesterSwiftUI`: allow configuring API key at runtime

Sources/Misc/StoreKit2Setting.swift, Sources/Purchasing/Configuration.swift
This changes the default back to `StoreKit 1`. We decided to do this for the following reasons:
- Purchasing with `PromotionalOffer`s does not work with StoreKit 2 due to an Apple bug (see https://github.com/RevenueCat/purchases-ios/pull/2020#discussion_r1012278099)
- `checkTrialOrIntroDiscountEligibility` is significantly slower with `StoreKit 2` (#1893). We're adding optimizations to help with that (#2007), but the underlying logic will still be slow.
- A rare race-condition where `StoreKit 2` does not have transactions after a purchase ([TRIAGE-82]). We have some workarounds (#1945), but it's still being investigated.
_Note: This effectively reverts 0ee540aa. That commit made it easier to only change the default in one place which is why this PR is basically just one line._ …
=> Changed `StoreKit2Setting.default` back to `.enabledOnlyForOptimizations`

.circleci/config.yml
- I noticed the `author` part was useless
- I also noticed this would run on every commit to the branch instead of after the release is successful so I moved it to after `make-release`
=> Some updates on notify-on-non-patch-release-branches:

.circleci/config.yml, fastlane/Fastfile
Pushes the pod in its own job until https://github.com/CocoaPods/CocoaPods/issues/11621 is fixed. Otherwise make-release always fails
=> Runs push-pods after make-release

Sources/Misc/Purchases+async.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
When calling this method, we were logging a message saying that determining eligibility failed, when in fact it didn't. It successfully detected that it's not eligible.
I've also added a small test for this scenario.
=> `eligiblePromotionalOffers`: don't log error if response is ineligible

Sources/FoundationExtensions/AsyncExtensions.swift, Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
This will be used by an upcoming PR.
=> `Async.call`: added non-throwing overload

.circleci/config.yml
See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/8749/workflows/f4994fe6-6ea3-4165-aaf0-4c5ee481260c/jobs/43015
We can't run these tests on Xcode 14 without first installing the runtime (see https://circle-macos-docs.s3.amazonaws.com/image-manifest/v8973/index.html).
Not sure if there's an API for that, and even if there was, it would be way too slow to bother instead of using an image that has the runtime already installed.
=> CI: fixed `iOS 14` tests Xcode version

.circleci/config.yml
iOS 16 is here to stay, so we should make sure our tests run there too.
One could make the case for running integration tests in all versions of iOS, but I think for now running on the latest is a good default.
=> `Integration Tests`: run on iOS 16

fastlane/Fastfile
This will help figure out failures more easily. Right now we only see the title of the error because that's all that `Xcode` generates (see https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/8749/workflows/f4994fe6-6ea3-4165-aaf0-4c5ee481260c/jobs/43011/tests for example).
=> `Integration Tests`: changed log output to `raw`

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcworkspace/contents.xcworkspacedata, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Logger.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LoggerView.swift
This is required for #2011.
Catalyst is not building reliable with the embedded framework, and Xcode does not allow adding the explicit target dependency. This solves that.
=> `PurchaseTesterSwiftUI`: replaced `Purchases` dependency with `SPM`

Sources/Error Handling/BackendErrorCode.swift
See https://github.com/RevenueCat/khepri/pull/4716
This makes that error `ErrorCode.invalidReceiptError` instead of `.unknownBackendError`.
I've also added #2032 to improve error messages when these errors are unknown in the future.
=> Added `BackendErrorCode.purchasedProductMissingInAppleReceipt`

Sources/FoundationExtensions/DateFormatter+Extensions.swift
Fixes [TRIAGE-172]
See stacktrace:
```
Fatal Exception: NSInternalInconsistencyException
Invalid parameter not satisfying: formatOptions == 0 || !(formatOptions & ~(NSISO8601DateFormatWithYear | NSISO8601DateFormatWithMonth | NSISO8601DateFormatWithWeekOfYear | NSISO8601DateFormatWithDay | NSISO8601DateFormatWithTime | NSISO8601DateFormatWithTimeZone | NSISO8601DateFormatWithSpaceBetweenDateAndTime | NSISO8601DateFormatWithDashSeparatorInDate | NSISO8601DateFormatWithColonSeparatorInTime | NSISO8601DateFormatWithColonSeparatorInTimeZone | NSISO8601DateFormatWithFullDate | NSISO8601DateFormatWithFullTime | NSISO8601DateFormatWithInternetDateTime))
Fatal Exception: NSInternalInconsistencyException
0 CoreFoundation 0x141d04 __exceptionPreprocess
1 libobjc.A.dylib 0x8528 objc_exception_throw …
```
=> `ISO8601DateFormatter.withMilliseconds`: fixed iOS 11 crash

Sources/Logging/Strings/OfferingStrings.swift, Sources/Purchasing/CachingProductsManager.swift, Tests/StoreKitUnitTests/StoreKit2CachingProductsManagerTests.swift, Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift
#1907 introduced this `CachingProductsManager` abstraction, but simply copied the existing caching mechanism, which was very limited. This expands on it by not ignoring cached products when not _all_ requested products are found. Instead, it uses the partial cache hit, and requests the rest of products.
This performance optimization is illustrated in the test change, as the second request only fetches the missing product now.
=> `CachingProductsManager`: use partial cached products

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/8800/workflows/15003c88-3322-4c55-8cc4-e44d4494b9c3/jobs/43446/tests
This was failing with `StoreKit 2` (probably a recent `SKTestSession`/`StoreKit` change since it used to pass):
```
[00:51:46]: ▸ 2022-11-09 00:51:46.820614+0000 BackendIntegrationTestsHostApp[4240:21475] [Default] [StoreKit] Received error that does not have a corresponding StoreKit Error:
[00:51:46]: ▸ Error Domain=ASDServerErrorDomain Code=3532 "You’re currently subscribed to this." UserInfo={storefront-country-code=USA, client-environment-type=XcodeTest(/Users/distiller/Library/Developer/CoreSimulator/Devices/E616C409-03A4-4A07-B2DC-FFF7544CBCCD/data/Containers/Shared/App ... tTestApp), AMSServerErrorCode=3532, NSLocalizedDescription=You’re …
```
=> `Integration Tests`: fixed `testPurchaseWithAskToBuyPostsReceipt`

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
As exposed by #2038, weekly subscriptions were leading to false negatives because they were always expired by the time the purchase was made (using `TimeRate.monthlyRenewalEveryThirtySeconds`), instead of lasting 10 seconds as documented. This is reported as `FB11767559`.
The advantage of using weekly subscriptions was to also work around `FB11767679`, which means that we have to manually _wait_ for the subscription to expire, as `SKTestSession.expireSubscription(productIdentifier:)` doesn't actually change the receipt.
Because we had to wait, using weekly subscriptions was faster, since we only needed to wait 10 seconds.
This does mean that expirations in these tests now have to wait 30 seconds instead of 10, but now they're no longer flaky :tada:
Looks like tests right now pass in CI in …
=> `Integration Tests`: changed weekly to monthly subscriptions to work around 0-second subscriptions

Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift, Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift, Sources/Logging/Strings/ReceiptStrings.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift, Tests/UnitTests/LocalReceiptParsing/AppleReceiptTests.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
A large amount of flaky integration tests are due to this bug, so detecting it early in the logs will help debug this.
Radar: `FB11767559`.
`productType` is missing in `StoreKitTest` purchases, so I changed `isSubscription` to default to checking if there is an expiration when the type is `.unknown`.
To simplify the code, I changed `ProductType?` to be non-optional, since we already have `.unknown` as a case.
```
[00:27:56]: ▸ 2022-11-09 00:27:56.000533+0000 BackendIntegrationTestsHostApp[3942:17000] [Purchases] - DEBUG: ℹ️ PostReceiptDataOperation: Posting receipt: {
[00:27:56]: ▸   "opaque_value" : "1n+XXw8AAAA=",
[00:27:56]: ▸   "sha1_hash" : "unR7vAzPaUlB0TtZ09z5jMyqqAs=",
[00:27:56]: ▸   "bundle_id" : "com.revenuecat.StoreKitTestApp",
[00:27:56]: ▸   "in_app_purchases" : [ …
```
=> `PostReceiptDataOperation`: log Apple error when purchase equals expiration date

Sources/Error Handling/ErrorDetails.swift, Sources/Error Handling/ErrorUtils.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift, Tests/UnitTests/Attribution/AttributionPosterTests.swift, Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift, Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift, Tests/UnitTests/Networking/BackendErrorTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Currently we only include the message and not the error code. So when these unknown errors are returned, unless the message is clear, we might not known which code the backend actually sent.
Example:
> There was an unknown backend error. The purchased product was missing in the receipt. This is typically due to a bug in StoreKit.
In this case it's clear, but nowhere in the logs we can find the error code.
This adds the error code to those messages (only when the code is unknown), as well as to `userInfo`.
> There was an unknown backend error. This is a future unknown error
> There was an unknown backend error. This is a future unknown error (1234)
> 😿‼️ There was an unknown backend error. Page not found
> 😿‼️ There was an unknown backend error. Page not found (6000)
=> `ErrorCode.unknownBackendError`: include original error code

Sources/Networking/HTTPClient/HTTPResponse.swift
I noticed this error in an integration test failure:
> BackendIntegrationTestsHostApp[3972:15171] Exception attempting to serialize sanitized error of issue. All userInfo with be discarded except localized description: NSInvalidUnarchiveOperationException: The data couldn’t be read because it isn’t in the correct format.
This was the only instance I could see that might potentially fail to serialize (it's `[String: String]`.
This should be a safe conversion anyway, so it's worth trying.
=> `ErrorResponse.asBackendError`: serialize attribute errors as `NSDictionary`

Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/HTTPClient/HTTPClient.swift
I'm looking into [CSDK-517], and it's hard to tell why we ended up with concurrent requests. It appears that a second request begins before the last one started.
That's seemingly impossible, and the only explanation for the logs missing "request completed" is that the first request failed.
This extra log will help us understand what's happening.
=> `HTTPClient`: added log for failed requests

CHANGELOG.md
This fixes the links to the V4 Migration guide document. While there were two different links pointing to to the document referred to as `RevenueCat V4 API update doc`, I suspect they both refer to the same document that has moved and is now called `RevenueCat V4 API Migration Guide`.
I fixed the links, but did not rename `RevenueCat V4 API update doc` to `RevenueCat V4 API Migration Guide` in the changelog.
Links changed:
`(Documentation.docc/V4_API_Migration_guide.md)`
`(docs/V4_API_Updates.md)`
=> Changelog: Fix links to V4 API Migration guide

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift, Tests/UnitTests/Mocks/MockStoreTransaction.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
- Greatly increased test coverage for `StoreKit2TransactionListener`
- Extracted `AsyncSequence.extractValues`
- Created `MockStoreTransaction` to be able to mock and verify `finish()` calls
- Simplified `StoreKit2TransactionListener`, moved `finish` call to `PurchasesOrchestrator`
- Follow up to #1965, also finish SK2 transactions from `StoreKit.Transaction.updates`
=> `StoreKit 2`: don't finish transactions in observer mode

Tests/TestPlans/BackendIntegrationTests.xctestplan
This is already set to random in `CI-BackendIntegration.xctestplan`, but it's useful to default to random when running them locally too, to potentially catch any state issues.
=> `Integration Tests`: always run them in random order locally

Tests/APITesters/SwiftAPITester/SwiftAPITester/SubscriptionPeriodAPI.swift
For some reason this wasn't compiling when compiling with test coverage on because the `switch` value was known at compile time.
=> `APITester`: fixed warning in `SubscriptionPeriodAPI`

Tests/UnitTests/FoundationExtensions/NSData+RCExtensionsTests.swift
I was adding a temporary test to verify a receipt, and made these better to help debugging.
Mainly because I had to look at this failing code to realize that the new receipt needed to be `.txt` (since Xcode doesn't show extensions anymore), so I added that to the error messages.
=> `NSData+RCExtensionsTests`: improved errors

.swiftlint.yml, Sources/Purchasing/Purchases/Purchases.swift, Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift, Tests/UnitTests/Mocks/MockCustomerInfoManager.swift, Tests/UnitTests/Mocks/MockOfferingsManager.swift, Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
[The new release](https://github.com/realm/SwiftLint/releases/tag/0.50.0) is much faster as [it uses](https://github.com/realm/SwiftLint/pull/4216) the [new SwiftParser](https://github.com/apple/swift-syntax).
- Disabled `orphaned_doc_comment`: it provides warnings for non-public declarations (see https://github.com/realm/SwiftLint/issues/4573#issuecomment-1322502917), but those are still useful for us.
- `function_body_length` has a new logic
- `large_tuple` seems to have new default thresholds, so I've specified them in `.swiftlint` to relax them. Tuples will most likely even become `Equatable` soon in Swift 6.0 so they're here to stay.
=> Fixed lint issues with `SwiftLint 0.5.0`

RevenueCat.xcodeproj/project.pbxproj, Sources/Caching/DeviceCache.swift, Sources/FoundationExtensions/UserDefaults+Extensions.swift, Sources/Logging/Strings/ConfigureStrings.swift, Sources/Networking/HTTPClient/ETagManager.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/StoreKitUnitTests/UserDefaultsDefaultTests.swift, Tests/UnitTests/FoundationExtensions/UserDefaultsExtensionsTests.swift, Tests/UnitTests/Mocks/MockDeviceCache.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Fixes [CSDK-16].
See https://docs.google.com/document/d/1DDyed98RFpIvUwUPJcetc7X4fBhDzf-r1trC4g3zf4c/edit# for reasoning and documentation.
The RevenueCat SDK has always used `UserDefaults.standard` as the default value. The advantage of this was simplicity, however, this brings a few challenges.
- While `UserDefaults` is itself thread-safe, our users might be observing `UserDefaults.defaults` changes via `KVO`, `NotificationCenter`, or `@AppStorage` (see https://github.com/RevenueCat/purchases-ios/issues/1527). We update `UserDefaults` from background threads, and users might be getting updates on those threads without handling thread-safety correctly.
- Users can accidentally delete data from the shared `UserDefaults` (see https://rev.cat/userdefaults-crash).
Using a custom …
=> Changed default `UserDefaults` from `.standard` to our own Suite

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
My current theory for what's causing [CSDK-517] is that we have a leaking `StoreKit1Wrapper` when running integration tests, and that's why we're posting multiple receipts concurrently.
```
PaymentTransactionObserver (0x0000600000e36480) updatedTransaction: com.revenuecat.monthly_4.99.1_week_intro 0
```
=> `StoreKit1Wrapper`: added instance address when detecting transactions

Sources/Caching/DeviceCache.swift, Tests/UnitTests/Mocks/MockNotificationCenter.swift
This could solve [CSDK-519], and at the very least it makes the semantics simpler to understand.
The traditional `NotificationCenter.addObserver` seems to always lead to a jump to the main thread when modifying `UserDefaults` from any other thread.
See:
```
Thread 1:
0 libsystem_kernel.dylib 0x1fa81041c __psynch_cvwait + 8
1 libsystem_pthread.dylib 0x20aa5406c _pthread_cond_wait + 1232
2 Foundation 0x1b85b3800 -[NSOperation waitUntilFinished] + 508
3 CoreFoundation 0x1be16fe0c _CFXNotificationPost + 772
4 Foundation 0x1b85d04dc -[NSNotificationCenter postNotificationName:object:userInfo:] + 92
5 AudioMemos2 0x102ed18a4 specialized closure #1 in DeviceCache.cache(customerInfo:appUserID:) + 972964 (<compiler-generated>:0)
```
There were no potential race condition (and as far as we can …
=> `DeviceCache`: changed `NotificationCenter` observation to be received on posting thread

Sources/Caching/DeviceCache.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift
We can do this now thanks to #2046. Solves #1906.
We no longer need to do this check if we're using our own `UserDefaults`, which simplifies the code, avoids a dangerous `fatalError`, and makes [CSDK-519] less likely.
[CSDK-519]: https://revenuecats.atlassian.net/browse/CSDK-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `DeviceCache`: removed `fatalError` for users not overriding `UserDefaults`

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift
Can be useful when debugging observer mode.
=> `PurchaseTesterSwiftUI`: added observer mode setting

Sources/Logging/Strings/ConfigureStrings.swift, Sources/Misc/SystemInfo.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/UnitTests/Misc/SystemInfoTests.swift
This is an important detail to log when initializing the SDK.
=> `Logging`: added log when configuring SDK in observer mode

Sources/Logging/Logger.swift
This will be used for [CSDK-512] to be able to configure the log level.
[CSDK-512]: https://revenuecats.atlassian.net/browse/CSDK-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `Logger`: exposed generic `log` method

Tests/UnitTests/Misc/AtomicTests.swift
Looking into [CSDK-519], a key part of that potential deadlock comes down to this use of `Atomic`.
This is a useful test to have to verify that this obvious usage is valid.
[CSDK-519]: https://revenuecats.atlassian.net/browse/CSDK-519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `Atomic`: added new test to verify each instance gets its own `Lock`

.circleci/config.yml
We see [some instances](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/8977/workflows/2eefe06e-29bc-465c-827b-059cd899c6dc/jobs/45088) where the simulator gets stuck (probably because of a system dialog) and the build ends up taking about 1 hour total.
CircleCI doesn't have [an easy way](https://support.circleci.com/hc/en-us/articles/4411204604059-Automatically-cancel-build-after-set-amount-of-time) to set an overall timeout, but lowering the `no_output_timeout` would help.
30 minutes is very excessive. It's useful for things like making a release, where CocoaPods might be slow, but shouldn't lead to false negatives in test execution.
=> `CircleCI`: lowered `no_output_timeout` to 5 minutes

RevenueCat.xcodeproj/project.pbxproj, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift, Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Filed this as `FB11799675`. I noticed some tests began with prior transactions (despite using `SKTestSession.clearTransactions`), so this workaround ensures each test begins in a clean state.
=> `SKTestSession`: finish all unfinished transactions before starting each test

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/LogIntent.swift, Sources/Misc/TimingUtil.swift, Tests/UnitTests/Misc/TimingUtilTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
For [CSDK-512].
This will print messages like:
> 🍎⚠️ Computation took too long (2.13 seconds)
```swift
let (result, duration) = try await TimingUtil.measure {
return try await asyncMethod()
}
```
```swift
let result = try await TimingUtil.measureAndLogIfTooSlow(
threshold: 2,
message: "Computation too slow",
level: .warn,
intent: .appleWarning
) {
try await asyncMethod()
}
```
```swift
TimingUtil.measure { completion in
work { completion($0) }
} result: { result, duration in
print("Result: \(result) calculated in \(duration) seconds")
}
```
```swift
TimingUtil.measureAndLogIfTooSlow(
threshold: 2,
message: "Computation too slow",
level: .warn,
intent: .appleWarning
) { completion in
work { completion($0) }
} result: { result in
print("Finished computing: \(result)")
}
```
[CSDK-512]: …
=> Created `TimingUtil` to measure and log methods that are too slow

Sources/Logging/LogIntent.swift, Sources/Logging/Logger.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
I want to add some extra logs to figure out [CSDK-517] which would be too verbose (no pun intended) for `debug`, so this will allow us to have some additional logging that wouldn't be enabled by default.
=> Added `LogLevel.verbose`

Sources/Logging/Logger.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Logging/Strings/StoreKitStrings.swift, Sources/Misc/TimingUtil.swift, Sources/Purchasing/Configuration.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift, Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
Using #2059 in a few places for now.
We can add this to more places, and tweak the thresholds.
Fixes [CSDK-512].
[CSDK-512]: https://revenuecats.atlassian.net/browse/CSDK-512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `StoreKit`: added logs when purchasing and product requests are too slow

Sources/Logging/Strings/ConfigureStrings.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Logging/Strings/Strings.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Depends on #2080.
This will help debug [CSDK-517].
```
- VERBOSE: Purchases.init: created new Purchases instance: Purchases (0x00006000037af800)
StoreKit Wrapper: left(<RevenueCat.StoreKit1Wrapper: 0x600000b6d3a0>)
- VERBOSE: Purchases.deinit: Purchases (0x0000600003f82600)
```
=> Added `verbose` logs for `Purchases` and `StoreKit1Wrapper` lifetime

.circleci/config.yml
I found this while looking into [CSDK-532].
Fixes the following error:
```
[18:29:04]: ▸ Committer: Distiller <...>
[18:29:04]: ▸ Your name and email address were configured automatically based
[18:29:04]: ▸ on your username and hostname. Please check that they are accurate.
[18:29:04]: ▸ You can suppress this message by setting them explicitly:
[18:29:04]: ▸ git config --global user.name "Your Name"
[18:29:04]: ▸ git config --global user.email you@example.com
```
[CSDK-532]: https://revenuecats.atlassian.net/browse/CSDK-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `CircleCI`: fixed `docs-deploy` git credentials

Tests/StoreKitUnitTests/ProductsManagerTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Identity/IdentityManagerTests.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift, Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift, Tests/UnitTests/Networking/Backend/BackendInternalTests.swift, Tests/UnitTests/Networking/Backend/BackendLoginTests.swift, Tests/UnitTests/Networking/Backend/BackendPostAdServicesTokenTests.swift, Tests/UnitTests/Networking/Backend/BackendPostAttributionDataTests.swift, Tests/UnitTests/Networking/Backend/BackendPostOfferForSigningTests.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Backend/BackendPostSubscriberAttributesTests.swift, Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
Example:
```diff
-        var result: Result<Offerings, OfferingsManager.Error>?
-        offeringsManager.offerings(appUserID: MockData.anyAppUserID) {
-            result = $0
+        let result = waitUntilValue { completed in
+            self.offeringsManager.offerings(appUserID: MockData.anyAppUserID) {
+                completed($0)
+            }
}
-        expect(result).toEventuallyNot(beNil())
```
This removes the need to _poll_ for when the value is returned, and instead it gets detected immediately, potentially providing a significant boost in test execution speed.
I've also used `Nimble`'s own `waitUntil` for cases where we don't need to return a value.
- Before this PR: 353
- After: 229
There's still a lot of legitimate usage of `toEventually`, but I'm sure I missed other …
=> `Tests`: replaced `toEventually` with new `waitUntilValue` to simplify tests

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
This compiles fine in Xcode 14 and Xcode 13.4, but produces the following error in Xcode 13.2:
```
static method 'measureAndLogIfTooSlow(threshold:message:level:intent:_:)' requires that 'PurchaseStrings' conform to 'Sendable'
```
To fix that, we can pass the `String` directly instead of a `CustomStringConvertible`.
See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/9028/workflows/fdd6cb34-a28f-4f1c-9e56-
abecc4eab8c0/jobs/45630
=> `TimingUtil`: fixed Xcode 13.2 compilation

.circleci/config.yml
We need an older version compatible with `macOS 11`.
=> Fixed `SwiftLint` installation

.circleci/config.yml
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/9137/workflows/28969b50-feae-4f06-b271-f38dc91b62c0/jobs/46576
=> Version 3.x: increased output timeout for `make-release`

Sources/Identity/IdentityManager.swift, Sources/Purchasing/Configuration.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift, Tests/UnitTests/Identity/IdentityManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
The docs had this:
> Pass `nil` or an empty string if you want ``Purchases`` to generate this for you.
But `nil` wasn't a valid input.
I noticed [this reported issue](https://github.com/RevenueCat/purchases-ios/issues/2107#issuecomment-1332007011) where the user was doing this:
```swift
.with(appUserID: userUID ?? "")
```
Which technically would have the same semantics, since we allow empty and convert it to anonymous, but now this is more clear and it matches the docstring.
=> `Configuration.with(appUserID:)`: allow passing `nil` and added new tests

Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift, Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Fixes #2107 and [SDKONCALL-180]. That's a rare issue where a user ends up with thousands of transactions.
That exposed the fact that we're processing all of these transactions on the main thread. This fixes that.
[SDKONCALL-180]: https://revenuecats.atlassian.net/browse/SDKONCALL-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `StoreKit1Wrapper`: process transactions in a background thread

Sources/Caching/DeviceCache.swift, Sources/Logging/Strings/PurchaseStrings.swift
Equivalent to #2082.
This change will help continue debugging [CSDK-517].
While debugging locally I ran into this crash:
```
Test Case '-[StoreKitUnitTests.UserDefaultsDefaultTests testDefaultIsRevenueCatSuiteIfStandardDoesNotContainUserID]' started.
RevenueCat/DeviceCache.swift:85: Fatal error: [Purchases] - Cached appUserID has been deleted from user defaults.
This leaves the SDK in an undetermined state. Please make sure that RevenueCat
entries in user defaults don't get deleted by anything other than the SDK.
More info: https://rev.cat/userdefaults-crash
```
But that should have been impossible because the current test had not initialized `Purchases` or `DeviceCache`, which showed that there was a leaking `DeviceCache` from another test.
[CSDK-517]: …
=> `DeviceCache`: added verbose logs for `init`/`deinit`

Sources/Purchasing/StoreKit2/StoreKit2StorefrontListener.swift, Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
A small performance improvement, since technically these don't need higher priorities.
=> `StoreKit2` listeners: set `Task` `priority` to `.utility`

Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift, Sources/LocalReceiptParsing/Builders/AppleReceiptBuilder.swift, Sources/LocalReceiptParsing/Builders/InAppPurchaseBuilder.swift, Sources/LocalReceiptParsing/DataConverters/UInt8+Extensions.swift, Sources/LocalReceiptParsing/ReceiptParser.swift, Sources/LocalReceiptParsing/ReceiptParsingError.swift, Tests/UnitTests/LocalReceiptParsing/ReceiptParserTests.swift, Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift, Tests/UnitTests/TestHelpers/ContainerFactory.swift
This will be used for [CSDK-17]. 
Since this will be a public API, we want to make sure we provide consistent and documented errors.
This changes a few thrown `BitShiftError`s into `ReceiptParser.Error`.
[CSDK-17]: https://revenuecats.atlassian.net/browse/CSDK-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `ReceiptParser.parse` always throws `ReceiptParser.Error`

Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
To continue debugging [CSDK-517], this adds an assertion to make sure that we don't leak `Purchases`, either because of a retain cycle, or due to any `XCTest` issue.
=> `BasePurchasesTests`: added assertion to ensure `Purchases` does not leak

Sources/Misc/StoreKit2Setting.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Misc/StoreKit2SettingTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
This will be used for https://github.com/RevenueCat/khepri/pull/4843, to fix [SDKONCALL-160] and #2020.
`X-StoreKit2-Setting` only told us if the apps had that setting enabled. However, when running on an older device, `SK2` would still be disabled.
[SDKONCALL-160]: https://revenuecats.atlassian.net/browse/SDKONCALL-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `HTTPClient`: replaced `X-StoreKit2-Setting` with `X-StoreKit2-Enabled`

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Calling `PurchasesDiagnostics.default` was lazily initializing it:
```swift
public static let `default`: PurchasesDiagnostics = .init(purchases: Purchases.shared)
```
Which was keeping a reference to `Purchases.shared` around.
For most cases this is fine, since `Purchases` would only be initialized once, but for tests it meant that it was leaking, which is now detected by #2106.
=> `Integration Tests`: fixed `Purchases` leak through `PurchasesDiagnostics`

.circleci/config.yml, Brewfile, Brewfile.lock.json
We currently spend almost 3 minutes on every build installing `swiftlint` and `xcbeautify`, so this is worth optimizing.
As brought up in #2094, the cache key should have some sort of hash of what's installed.
However, we don't have a way to list the dependencies. For the time being, this should be enough. We can bump the "version" number to invalidate the cache whenever we need it to update.
This makes installing `SwiftLint` go from almost 3 minutes to just a few seconds (around 5 between restoring cache and `brew link`).
=> `CircleCI`: cache Homebrew installation

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
See [iOS 15.5 release notes](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-15_5-release-notes):
> Fixed an issue so developers using StoreKit 2 can now initiate a subscription offer purchase for a product that the customer currently subscribes to. (89152302).
This adds a test to verify this behavior.
Blocked for #2020.
=> `StoreKitIntegrationTests`: added test to check applying a promotional offer during subscription

Sources/Networking/Operations/PostReceiptDataOperation.swift
This was fine when we only had `debug` logs, but since #2080 we need to check for `verbose` too.
Thanks to #2102 we can just use `<=`, because `LogLevel` conforms to `Comparable`.
=> `PostReceiptDataOperation`: also print receipt data with `verbose` logs

Sources/LocalReceiptParsing/ReceiptParser.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/ReceiptFetcher.swift
Fixes #2107 and [SDKONCALL-180].
[This comment](https://github.com/RevenueCat/purchases-ios/issues/2107#issuecomment-1342846583) pointed out that parsing a long receipt can freeze the UI for almost a second.
⚠️ This new assertion (running only in integration tests using the code added in #2100) has exposed a couple of code paths where we parse receipts from the main thread!
[SDKONCALL-180]: https://revenuecats.atlassian.net/browse/SDKONCALL-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `ReceiptParser`: ensure parsing never happens in the main thread

Sources/Networking/Caching/CallbackCache.swift
See also #2135.
I'm looking into the leak in #2105, and I have a theory that it's due to callbacks being stored in this cache, but sometimes not being dequeued, so leaking all references in them.
This assertion will only run in RC tests, and will ensure that this doesn't happen.
=> `CallbackCache`: added assertion for tests to ensure we don't leak callbacks

Sources/Networking/Caching/CallbackCache.swift, Sources/Networking/Caching/CustomerInfoCallback.swift
Small refactor to avoid users of this `class` change the content of the cache without using the methods.
=> `CallbackCache`: avoid exposing internal mutable cache

Sources/Misc/Deprecations.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Fixes [CSDK-544].
This makes these 2 common configuration patterns a bit simpler than using `Configuration.Builder`.
I've also updated the docs in https://docs-origin.revenuecat.com/docs/configuring-sdk
The documentation is the same as the old one (see https://github.com/RevenueCat/purchases-ios/blob/5679b2b954c9bfda0d7bddb3e43cdd4dcc489519/Sources/Purchasing/Purchases.swift).
[CSDK-544]: https://revenuecats.atlassian.net/browse/CSDK-544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Un-deprecate `Purchases.configure(withAPIKey:appUserID:)` and `Purchases.configure(withAPIKey:appUserID:observerMode:)`

Sources/Logging/Strings/ReceiptStrings.swift
Fixes [CSDK-543].
See https://github.com/RevenueCat/purchases-flutter/issues/540.
Users might be confused and think that if data is missing from the receipt, something is wrong.
This new log should clarify that.
[CSDK-543]: https://revenuecats.atlassian.net/browse/CSDK-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `PostReceiptDataOperation`: clarified receipt debug log

Sources/LocalReceiptParsing/Builders/ASN1ContainerBuilder.swift, Sources/LocalReceiptParsing/DataConverters/UInt8+Extensions.swift, Sources/LocalReceiptParsing/ReceiptParser.swift
See also #2123 and https://github.com/RevenueCat/purchases-ios/issues/2107#issuecomment-1342846583.
=> Added a few performance improvements for `ReceiptParser`

Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
=> `ReceiptFetcherTests`: refactored tests using `waitUntilValue`

fastlane/Fastfile
Fixes [CSDK-527].
Thanks to @joshdholtz for the help.
Configured CircleCI environment variables to use an ASC API Key:
```
APP_STORE_CONNECT_API_KEY_ISSUER_ID=
APP_STORE_CONNECT_API_KEY_KEY_ID=
APP_STORE_CONNECT_API_KEY_KEY=
APP_STORE_CONNECT_API_KEY_IS_KEY_CONTENT_BASE64=true
```
[CSDK-527]: https://revenuecats.atlassian.net/browse/CSDK-527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `CI`: fixed `PurchaseTester` deployment

Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift, Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
This is necessary because we can't use `Quick` v6.x yet.
Abstracting this out to use it in #2069.
=> Extracted `asyncWait` to poll `async` conditions in tests

Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift, Sources/Logging/Strings/ReceiptStrings.swift, Sources/Purchasing/ReceiptFetcher.swift, Sources/Purchasing/ReceiptRefreshPolicy.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Fixes #2116.
Depends on #2134, #2144, #2145.
We've known that, especially for sandbox accounts with lots of purchases, the SDK can get flooded with a lot of transactions to process at once.
I've been making some improvements for this (like #2115).
Another consequence of this behavior, is that we can end up failing due to `StoreKit` throttling us (see #2116):
> 2022-12-03 12:31:58.670892+0100 app[673:61074] <SKReceiptRefreshRequest: 0x283edc860>: Finished refreshing receipt with error: Error Domain=ASDErrorDomain Code=603 "Request throttled" UserInfo={NSLocalizedFailureReason=Unified receipt is valid and current, NSLocalizedDescription=Request throttled, AMSServerErrorCode=0}
This change avoids that by skipping the refresh if less than 2 seconds have elapsed. I chose 2 to make this a …
=> `ReceiptFetcher`: throttle receipt refreshing to avoid `StoreKit` throttle errors

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Fixes [CSDK-546](https://revenuecats.atlassian.net/browse/CSDK-546)
Looks like we were not caching the offeringIdentifier for a productIdentifier when using store kit 2. This should fix that.
=> Fix sending presentedOfferingIdentifier in StoreKit2

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
See [TRIAGE-179].
I wrote all these to cover the change in #2063. I wrote a failing test that only passed with the change in #2063. However, when running that in SK1, that would fail.
With the change as suggested in #2063, the SK2 behavior would differ from SK1.
From the `Transaction.all` docs:
> This sequence returns the user’s transaction history current to the moment you access the sequence. The sequence emits a finite number of transactions. If the App Store processes new transactions for the user while you’re accessing this sequence, the new transactions appear in the transaction listener, updates.
These new tests verify the behavior of the SDK when encountering transactions created prior to initializing the SDK, and some made after initialization.
Integration tests now are as …
=> Added integration and unit tests to verify observer mode behavior

RevenueCat.xcodeproj/project.pbxproj, Sources/Attribution/AttributionFetcher.swift, Sources/Logging/Strings/AttributionStrings.swift, Tests/UnitTests/Attribution/AttributionFetcherTests.swift
Fixes #2121 and [CSDK-600].
Initially I wanted to check `.toNot(beEmpty())`, but at least locally it's throwing an error:
> Error Domain=com.apple.ap.adservices.attributionError Code=2 "Error generating token" UserInfo={NSLocalizedDescription=Error generating token}
Which is `AAAttributionError.Code.internalError`.
At least we have some test coverage to see if in any combination of Xcode / iOS it hangs, as reported.
[CSDK-600]: https://revenuecats.atlassian.net/browse/CSDK-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fixed `AttributionFetcher.adServicesToken` hanging when called in simulator

fastlane/Fastfile
We don't want CI jobs updating provisioning profiles.
If they're set up correctly, nothing should change when using `match` to run these jobs.
Also removed unnecessary `verbose` parameter.
=> `Fastfile`: changed `match` to `readonly`

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
The `scheme` was pointing to this file, but it wasn't finding it because it was missing from the project.
In older Xcode versions this would simply make it crash. Now I was able to figure out the issue.
=> `Purchase Tester`: fixed `.storekit` config file reference

Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/HTTPClient/DNSChecker.swift
Example:
> DEBUG: ℹ️ Failing url 'https://0.0.0.0/offers' resolved to host '0.0.0.0'
Looking into #2028, it appears that the user is getting a `NSURLErrorCannotFindHost` with a `NSErrorFailingURLKey`. We didn't determine that this was a `DNS` error because whatever the host resolved to, wasn't one of `Set(["0.0.0.0", "127.0.0.1"])`.
This will add a log that will help us figure out why they got a `NSURLErrorCannotFindHost`.
=> `DNSChecker`: added log with resolved host

Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
See #2066.
I saw a bunch of these messages:
> DEBUG: ℹ️ Finishing 0 transactions before running tests
Which doesn't add anything if there aren't any leftover transactions.
=> `StoreKitTestHelpers`: cleaned up unnecessary log

Sources/Logging/Strings/StoreKitStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift, Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
See #2107. We still don't know what caused that, but it leads to degraded performance (mildly reduced by #2115). To advice of that, in case users are wondering why the app might potentially take excessive CPU usage, I added this warning.
=> `StoreKit1Wrapper`: added warning if receiving too many updated transactions

Sources/Misc/SandboxEnvironmentDetector.swift, Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift, Tests/UnitTests/Mocks/MockBundle.swift
I found out today that when running `PurchaseTester` on `macOS` (either native or with Catalyst), the SDK was sending `X-Is-Sandbox` = `true`.
The new examples in `MockBundle` illustrate this.
=> `BundleSandboxEnvironmentDetector`: fixed logic for `macOS`

Sources/Purchasing/IntroEligibility.swift
This fixes the following log:
> DEBUG: ℹ️ Local intro eligibility computed locally. Result: ["com.revenuecat.annual_39.99.2_week_intro": RevenueCat.IntroEligibilityStatus]
And now we get a much more useful value:
> DEBUG: ℹ️ Local intro eligibility computed locally. Result: ["com.revenuecat.annual_39.99.2_week_intro": IntroEligibilityStatus.eligible]
=> `IntroEligibilityStatus`: added `CustomStringConvertible` implementation

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Core/Constants.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Core/Core.h, Tests/TestingApps/PurchaseTesterSwiftUI/Core/Logger.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTesterWatchOS.xcscheme, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/Assets.xcassets/AccentColor.colorset/Contents.json, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/Assets.xcassets/AppIcon.appiconset/Contents.json, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/Assets.xcassets/Contents.json, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/ContentView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/PurchaseTesterWatchApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LoggerView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/fastlane/Matchfile, scripts/pre-commit.sh
I added this in order to debug #2132.
- Extracted `Core` framework to be used by both apps
- Added new `watchOS` target
- Changed `fastlane match` to also create profiles for this new target
- Added a simple view in the watch app that displays a text if an entitlement is active, or a `restore` purchases button otherwise
This is just a starting point, we can add more to it in the future.
_Unfortunately I haven't been able to test this because of an Apple bug (`FB11873951`):_
=> `Purchase Tester`: added companion `watchOS` app

Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift, Tests/UnitTests/Purchasing/StoreKitRequestFetcherTests.swift
`finishReceiptRequest` is already running on the worker thread, so there's no need for the double dispatch.
Also refactored tests.
=> `StoreKitRequestFetcher`: removed unnecessary dispatch

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester-Info.plist
Fixes the following warnings when launching the app:
```
2022-12-19 11:57:15.692222-0800 PurchaseTester[40211:4411274] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2022-12-19 11:57:15.692564-0800 PurchaseTester[40211:4411274] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2022-12-19 11:57:15.692707-0800 PurchaseTester[40211:4411274] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no name)")
2022-12-19 11:57:15.692810-0800 PurchaseTester[40211:4411274] [SceneConfiguration] Info.plist contained no UIScene configuration dictionary (looking for configuration named "(no …
```
=> `Purchase Tester`: fixed scene manifest

Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/Purchasing/IntroEligibilityCalculator.swift
This is useful when debugging potentially incorrect logic, like [TRIAGE-221].
[TRIAGE-221]: https://revenuecats.atlassian.net/browse/TRIAGE-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `IntroEligibilityCalculator`: added log including `AppleReceipt`

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
It was working well for Mac Catalyst, but not compiling with `macOS` directly. This fixes that, and makes the configuration UI work.
=> `PurchaseTester`: fixed `macOS` support

Sources/FoundationExtensions/OperationQueue+Extensions.swift, Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/BackendConfiguration.swift, Sources/Networking/Caching/CustomerInfoCallback.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/IdentityAPI.swift, Sources/Networking/InternalAPI.swift, Sources/Networking/OfferingsAPI.swift, Sources/Networking/Operations/GetCustomerInfoOperation.swift, Sources/Networking/Operations/GetOfferingsOperation.swift, Sources/Networking/Operations/LogInOperation.swift, Sources/Networking/Operations/NetworkOperation.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift
- Created `CacheableNetworkOperationFactory` to abstract operation and cache key creation
- Instead of always creating an operation, we create a factory first, which pre-computes the cache key
- This cache key is used to determine if it's a cache hit, as well as for the subsequently created operation
I'm still investigating a leak (#2105), and I suspect it's coming from us creating and storing completion blocks, and those staying in memory beyond the lifetime of the operation.
This refactor and performance improvement helps us avoid get more things in memory than we need to.
See #2138 for how this is tested.
=> `CacheableNetworkOperation`: avoid unnecessarily creating operations for cache hits

Sources/FoundationExtensions/OperationQueue+Extensions.swift, Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/BackendConfiguration.swift, Sources/Networking/Caching/CustomerInfoCallback.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/IdentityAPI.swift, Sources/Networking/InternalAPI.swift, Sources/Networking/OfferingsAPI.swift, Sources/Networking/Operations/GetCustomerInfoOperation.swift, Sources/Networking/Operations/GetOfferingsOperation.swift, Sources/Networking/Operations/LogInOperation.swift, Sources/Networking/Operations/NetworkOperation.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift
Looking into the leak in #2135, I realized that we have an operation which doesn't call `completion`, we would be leaking the completion block in the cache.
This ensures that it doesn't happen in tests. In production, we won't risk crashing.
=> `NetworkOperation`: added assertion to ensure that subclasses call completion

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift, Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Fixes [CSDK-504].
`SKPaymentQueue.finishTransaction` is asynchronous, but we were assuming it wasn't.
This meant that when performing multiple purchases (like consumables) in quick succession, before the first transaction was finished, the second purchase was reusing the first transaction.
Example log:
```
[Purchases] - INFO: :moneybag: Finishing transaction ‘0’ for product ‘consumable.10_coins’
[Purchases] - INFO: :heart_eyes_cat::moneybag: Purchased product - ‘consumable.10_coins’
[Purchases] - INFO: :moneybag: Purchasing Product ‘consumable.10_coins’ from package in Offering ‘coins’
[Purchases] - DEBUG: :information_source: StoreKit1Wrapper (0x00006000008a9530) removedTransaction: consumable.10_coins 0 1
```
Notice how the "removed transaction" was notified _after_ we had already …
=> Fixed race condition finishing `SK1` transactions

Tests/TestingApps/PurchaseTesterSwiftUI/Core/Logger.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTesterWatchOS.xcscheme, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LoggerView.swift
See #2012.
This is useful when debugging some feature. You can now clear the logs before performing whatever action you need to test, and have a cleaner output with only the logs from that point.
=> `Purchase Tester`: added button to clear messages on logger view

Sources/Networking/HTTPClient/DNSChecker.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
`DNSChecker.errorWithBlockedHostFromError` already checks `isBlockedAPIError` when constructing this error, so we can simplify this to avoid calling `DNSChecker.resolvedHost` twice.
=> `DNSChecker`: simplified `NetworkError` initialization

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ObserverModeManager.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ProductFetcherSK1.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ProductFetcherSK2.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/PurchasesOrchestrator.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
This will help test observer mode, mimicking how an app might use `RevenueCat` with observer mode.
When that setting is enabled, 2 new buttons will appear:
The implementation isn't the most maintainable, but we don't really need it to be. I favored simplicity instead of over-complicating the implementation. It's not meant to be a canonical example of the correct way to purchase with StoreKit, just a quick way of testing this behavior.
=> `Purchase Tester`: added ability to purchase products directly with `StoreKit`

Sources/Error Handling/ErrorUtils.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
See https://github.com/RevenueCat/purchases-hybrid-common/pull/278.
A valid error ended up as:
> failed: caught error: "Unknown error."
This change ensures that calling this method with an `NSError` does not return `ErrorCode.unknownError`, and instead we extract the correct error.
=> `ErrorUtils.purchasesError(withUntypedError:)`: handle `PublicError`s

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
This was probably done before we exposed this as part of `StoreProduct`. With SK2 enabled, no period was being displayed.
=> `Purchase Tester`: fixed `SubscriptionPeriod`

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Before this change we were displaying `"no"` instead of `noIntroOfferExists`, which was confusing.
=> `Purchase Tester`: display specific `IntroEligibilityStatus`

Sources/FoundationExtensions/Dictionary+Extensions.swift, Tests/UnitTests/FoundationExtensions/DictionaryExtensionsTests.swift
This simplifies the `+=` implementation by avoiding an intermediate dictionary, and allows a simpler way of merging dictionaries.
Will be used in #2174.
=> Added `Dictionary.merge`

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/EligibilityStrings.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Logging/Strings/Strings.swift, Sources/Misc/Purchases+async.swift, Sources/Purchasing/CachingTrialOrIntroPriceEligibilityChecker.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift, Tests/UnitTests/Mocks/MockCachingTrialOrIntroPriceEligibilityChecker.swift, Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift, Tests/UnitTests/Purchasing/CachingTrialOrIntroPriceEligibilityCheckerTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Fixes [CSDK-493].
This will help a little bit with the SK2 performance issues computing eligibility (#1893).
[CSDK-493]: https://revenuecats.atlassian.net/browse/CSDK-493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Created `CachingTrialOrIntroPriceEligibilityChecker`

Sources/LocalReceiptParsing/PurchasesReceiptParser.swift
The most obvious way to create `PurchasesReceiptParser` is using `.init`.
In order to expose that we'd need to `override` `init` from an `extension` because each (RC / `ReceiptParser`) `target` needs a different `LoggerType`. However,  `NSObject.init` can't be overridden from an extension.
That's why the API exposes `default` instead. This will make the usage clearer:
=> `PurchasesReceiptParser`: improved documentation to reference `default`

Sources/FoundationExtensions/Data+Extensions.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Tests/UnitTests/FoundationExtensions/NSData+RCExtensionsTests.swift
Should fix #2198 and [SDKONCALL-200]. This is a big performance optimization in time and memory, as we no longer need to convert the entire receipt to `base64` and concatenate it to the string, which is what was likely causing #2198.
This now uses `Data.hashString`, which avoids any data copies and efficiently creates a hash with the receipt content.
Apart from the new tests for this property, `BackendPostReceiptDataTests.testDoesntCacheForDifferentReceipts` ensures that different receipts have different cache keys, and therefore this new implementation still avoids collisions (other than the extremely unlikely hash collisions).
[SDKONCALL-200]: https://revenuecats.atlassian.net/browse/SDKONCALL-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> `PostReceiptDataOperation`: replaced receipt `base64` with `hash` for cache key

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Data+Extensions.swift, Sources/FoundationExtensions/Optional+Extensions.swift, Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift, Sources/Purchasing/ReceiptFetcher.swift, Tests/UnitTests/FoundationExtensions/OptionalExtensionsTests.swift, Tests/UnitTests/Mocks/MockBundle.swift
- Added `Optional.orThrow` to simplify implementation (this will be useful in many other parts of the code too)
- Added missing `OptinalExtensionsTests`
`DefaultFileReader` was implemented using `try?`, now it throws an error instead of returning `nil`
- `ReceiptFetcher`: logging specific error when loading receipt fails
- Refactored `ReceiptFetcher`:
- No longer logging "loaded receipt" if the content was empty
- No longer logging an error twice if the receipt failed to load
- Simplified logic to handle errors only once
=> `ReceiptFetcher`: refactored implementation to log error when failing to fetch receipt

.swiftlint.yml, Package.swift, ReceiptParserTests-Info.plist, RevenueCat.xcodeproj/project.pbxproj, RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme, Tests/ReceiptParserTests/ReceiptParserFetchingTests.swift, Tests/TestPlans/AllTests.xctestplan, Tests/TestPlans/CI-AllTests.xctestplan
For [CSDK-622], we need to be able to write tests specific to `ReceiptParser` implementations.
This sets up that target, and allows running those tests via Xcode or SPM.
- Added `ReceiptParserTests` target to Xcode
- Added `ReceiptParserTests` target to `Package.swift`
- Added `ReceiptParserTests` to "test" phase of `ReceiptParser` scheme
- Added `ReceiptParserTests` to All-Tests test plan
- Added `ReceiptParserTests` to CI-All-Tests test plan
[CSDK-622]: https://revenuecats.atlassian.net/browse/CSDK-622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added `ReceiptParserTests`

Sources/FoundationExtensions/JSONDecoder+Extensions.swift, Sources/Logging/Strings/CodableStrings.swift
See [TRIAGE-240].
That logged an error:
```
Key 'CodingKeys(stringValue: "data", intValue: nil)' not found, codingPath: [], description:
No value associated with key CodingKeys(stringValue: "data", intValue: nil) ("data").
```
But it was impossible to determine where it was coming from.
With this change now we get:
```
Error deserializing `Response`. Key 'CodingKeys(stringValue: "data", intValue: nil)' not found, codingPath: [], description:
No value associated with key CodingKeys(stringValue: "data", intValue: nil) ("data").
```
[TRIAGE-240]: https://revenuecats.atlassian.net/browse/TRIAGE-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `JSONDecoder`: added decoding type when logging `DecodingError.keyNotFound`

Sources/Identity/CustomerInfo.swift, Sources/Identity/CustomerInfoManager.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift, Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfo-v2.json
Fixes [TRIAGE-240].
When we converted `CustomerInfo` to use `Codable` (#1496), the schema version was also changed from 2 to 3.
I don't remember if this was done on purpose, but turns out that it was not necessary.
This means that a user opening an app while offline, after upgrading from version `3.x` to `4.x` (>= `4.3`), would not have a cached `CustomerInfo` and therefore no entitlements.
This fixes that by restoring support and adding a specific test with a sample version 2 JSON (which is virtually identical).
[TRIAGE-240]: https://revenuecats.atlassian.net/browse/TRIAGE-240?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `CustomerInfo`: support parsing schema version 2 to restore SDK `v3.x` compatibility

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Data+Extensions.swift, Sources/LocalReceiptParsing/Helpers/FileReader.swift, Sources/LocalReceiptParsing/ReceiptParser-only-files/PurchasesReceiptParser+Fetching.swift, Sources/LocalReceiptParsing/ReceiptParsingError.swift, Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester/PurchasesReceiptParserAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesReceiptParserAPI.swift, Tests/ReceiptParserTests/Helpers/MockBundle.swift, Tests/ReceiptParserTests/ReceiptParserFetchingTests.swift, Tests/UnitTests/Mocks/MockFileReader.swift
Fixes [CSDK-622].
- Extracted `FileReader` to be able to use it in `ReceiptParser`
- Extracted `MockBundle` to be able to use it in `ReceiptParser`
- Added new `public` `ReceiptParser.fetchAndParseLocalReceipt()`, **only to `ReceiptParser`** (this is not available through `RevenueCat`).
- Added tests for the new API
- Added new API to `ReceiptParserAPITester`
Initially I thought about moving `ReceiptFetcher` to the `Receipt|Parser` target. Unfortunately that would require moving a whole bunch of other dependencies (`OperationDispatcher`, etc, etc).
We have no easy way to create a third "Core" framework in which to place these common dependencies, so that wouldn't be trivial.
This solution adds a much simpler version of `ReceiptFetcher` that simply reads from `Bundle.appStoreReceiptURL`. …
=> Added new `ReceiptParser.fetchAndParseLocalReceipt`

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LocalReceiptView.swift
Fixes [CSDK-626].
Depends on #2199, #2200, #2202, #2203, #2204, #2210.
[CSDK-626]: https://revenuecats.atlassian.net/browse/CSDK-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `PurchaseTester`: added section to visualize `AppleReceipt`

Package.swift
This flag is already set in `Xcode`'s target, so setting it here matches it when embedding the frameworks through `SPM`.
This allows users to embed these package in non-app targets.
Unfortunately setting the flag directly is the only way to do this at the moment.
=> `SPM`: added `APPLICATION_EXTENSION_API_ONLY` flag to `RevenueCat` and `ReceiptParser`

Contributing/UpdatingRequirements.md, RevenueCat.xcodeproj/project.pbxproj, Sources/Support/SwiftVersionCheck.swift
This will make it easier to figure out that the version is no longer compatible.
Aditionally, I've added `UpdatingRequirements.md` so we have a single place to reference when changing these requirements.
=> Produce a compilation error when using an old `Xcode` version

Package.swift
This reverts commit 02c2bcec4b51cc59c07cb09c4a62e160c919f7bd.
Unfortunately this breaks SPM integration under some conditions (see #2223):
> error: The package product 'RevenueCat' cannot be used as a dependency of this target because it uses unsafe build flags. (in target 'PurchaseTester' from project 'PurchaseTester')
I haven't been able to reproduce this locally, but better to remove this for now until `SPM` adds a way to set this flag without using unsafe flags.
=> Revert "`SPM`: added `APPLICATION_EXTENSION_API_ONLY` flag to `RevenueCat` and `ReceiptParser` (#2217)"

fastlane/Fastfile
This will provide some context when a new build is submitted.
Also changed the lane to use `upload_to_testflight` instead of `upload_to_appstore`.
=> `PurchaseTester`: setting `changelog` when submitting to `TestFlight`

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
`isPurchasing` was not being set to `false` when a purchase fails, which lead to the UI being locked.
=> `PurchaseTester`: fixed `isPurchasing` state when purchasing fails

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/LocalReceiptView.swift
See #2211.
If `restorePurchases` fails for any reason, we still want to try to load the local receipt. We're only interested in refreshing the receipt to load it.
=> `PurchaseTester`: ignore errors when restoring purchases

Sources/Purchasing/Purchases/Purchases.swift
#2224 likely fixes #1877. This change also avoids running the code being triggered in that crashing stack trace, since it's not necessary.
`Purchases.delegate` setter already calls `sendCachedCustomerInfoToDelegateIfExists`, so that method was unnecessary. Removing this call to `sendCachedCustomerInfoIfAvailable` doesn't make any test fails because of that.
This behavior is also verified by `PurchasesConfiguringTests`: `testFirstInitializationFromBackgroundCallsDelegateForAnonIfInfoCached` and `testSettingTheDelegateAfterInitializationSendsCachedCustomerInfo`.
I also improved this by extracting it into its own method and adding an explanation for the `isApplicationBackgrounded` check.
=> `Purchases`: avoid potential crash when initializing in the background

Sources/Misc/SystemInfo.swift, Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
Unfortunately we can't use this in any of the places that use the asynchronous method, but as we move more code to `async` this might be beneficial.
For now this also improves the documentation to explain why the API is asynchronous.
=> `SystemInfo.isApplicationBackgrounded`: added overload for `@MainActor`

Sources/Logging/Strings/OfferingStrings.swift
The previous logs were vague, seemed kind of scary mentioning that the packages would be ignored - but it was just referencing that they couldn't be accessed from an Offering's convenience methods for each duration.
Updates the logs to explain that packages can be referenced by their identifiers directly with a link to the docs.
=> Improve logging for custom package durations

Sources/Purchasing/Purchases/PurchasesType.swift
Fixed this warning:
These started happening after #1958. I assumed it was an Xcode bug, because they were showing up on the wrong file pointing to some unrelated code.
Turns out that by itself was an Xcode bug (filed as `FB11959877`):
---
But the underlying warning was correct, which this fixes. We just needed to fix the reference to `logIn` to point to the specific overload.
=> `Purchases`: fixed documentation warnings

Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/BasicTypes/InAppPurchase.swift, Sources/Purchasing/IntroEligibilityCalculator.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit, Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
- Fixes  [TRIAGE-221] for `SK1`.
- Filed `FB11889732` for `SK2`.
- Added 2 `IntroEligibilityCalculatorTests` unit tests to cover this scenario
- Added 1  `IntroEligibilityCalculatorTests` unit tests to cover the equivalent of the `testIneligibleForIntroAfterPurchaseExpires` integration test
- Added 2 `StoreKitIntegrationTests` to cover this scenario (one of them disabled in SK2)
- Updated `IntroEligibilityCalculator` logic to fix the new tests.
- Refactored `IntroEligibilityCalculatorTests` to avoid duplication and allow adding new cases more easily.
- Added a few more tests to ensure other cases are correct.
[TRIAGE-221]: https://revenuecats.atlassian.net/browse/TRIAGE-221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `IntroEligibilityCalculator`: fixed logic for subscriptions in same group

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
We've had reports of receipt fetching throttling errors (#2116). #2146 improved this by throttling receipt refreshing.
However, we can avoid this altogether by not refreshing the receipt unless it's empty.
The main reason being that the backend will automatically refresh the receipt using `/verifyReceipt`, so it doesn't matter if the receipt we post is slightly out of date.
=> `PurchasesOrchestrator`: changed `ReceiptRefreshPolicy.always` to `.onlyIfEmpty` after a purchase

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
See https://developer.apple.com/documentation/xctest/expected_failures
I realized this going through the old PR. Better to actually run the test so that if/when it gets fixed in the future, we're notified because it will "fail".
=> `StoreKitIntegrationTests`: replaced `XCTSkipIf` with `XCTExpectFailure`

Sources/Purchasing/IntroEligibilityCalculator.swift, Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
=> `IntroEligibilityCalculator`: changed logic to handle products with no subscription group

Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift
Fixes https://app.codecov.io/gh/RevenueCat/purchases-ios/pull/2257
Depending on this value, we were evaluating a different string.
=> `StoreKit1WrapperTests`: avoid using `Bool.random` to fix flaky code coverage

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ReceiptInspector.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ReceiptVerifier.swift
Adds a new MenuBar UI to the PurchaseTester app on macOS. 
The UI provides a quick utility to parse the local receipt and to check it against `/verifyReceipt`. This makes it super easy to debug receipts using PurchaseTester.
=> PurchaseTester: Add Receipt Inspector UI

Tests/UnitTests/Networking/HTTPClientTests.swift
See also #2168 and #2071.
I was looking into randomness in tests that might lead to test coverage fluctuations and saw that these tests could be simplified to avoid use of `toEventually`.
=> `HTTPClientTests`: refactored tests to use `waitUntil`

Tests/UnitTests/Networking/HTTPClientTests.swift
`HTTPClientTest.testRequestIsRetriedIfResponseFromETagManagerIsNil` was actually failing (the request wasn't successful), but because it had no expectations, we didn't notice until we introduced Code Coverage.
As you can see [in the Codecov diff](https://app.codecov.io/gh/RevenueCat/purchases-ios/pull/2258):
Most of the time that code didn't have coverage (meaning we weren't testing it). The reason for why is uncovered in this PR.
The random execution order meant that sometimes (most of the time) tests like `testHandlesRealErrorConditions` were running first, which did this:
```swift
let response = HTTPStubsResponse.emptySuccessResponse
response.error = error
return response
```
That seemingly innocuous code was modifying `HTTPStubsResponse.emptySuccessResponse`, defined in an extension …
=> `HTTPClientTests`: fixed failing test with missing assertions

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Box.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Mocks/MockNotificationCenter.swift, Tests/UnitTests/Mocks/MockSK2BeginRefundRequestHelper.swift, Tests/UnitTests/TestHelpers/Box.swift
See https://github.com/apple/swift/issues/58099
This is fixed in newer versions of Xcode, but we still need the workaround for older ones. Instead of using `Any` and force-casting, `Box` is better since it's type safe.
- Moved `Box` to `RevenueCat` to be able to use the workaround there too.
- Made `Box` immutable. It's very dangerous to have a reference value (`Box` is a `class`) with reference semantics be mutable. Instead, we force users to have a mutable property instead and re-create the `Box`, to avoid mutating that data under the hood.
- Updated the comments to point to the new `Swift` GitHub issue page.
=> Replaced `Any` uses for workaround with `Box`

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/SigningStrings.swift, Sources/Logging/Strings/Strings.swift, Sources/Misc/Signing.swift, Tests/UnitTests/Misc/SigningTests.swift
Fixes [CSDK-633].
This adds `Signing.verify(message:nonce:hasValidSignature:with:)`.
Thanks to @tonidero for helping with the signature part (#2253).
[CSDK-633]: https://revenuecats.atlassian.net/browse/CSDK-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Created `Signing.verify(message:hasValidSignature:with:)`

Sources/Error Handling/ErrorUtils.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
> [Purchases] - ERROR: 😿‼️ Error performing request.
> [Purchases] - ERROR: 😿‼️ Error performing request. The operation couldn’t be completed. (NSURLErrorDomain error -1.)
=> `NetworkError`: added underlying error to description

RevenueCat.xcodeproj/project.pbxproj, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit2/StoreKit2StorefrontListener.swift, Sources/Purchasing/StoreKitAbstractions/Storefront.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreKit2StorefrontListenerTests.swift, Tests/UnitTests/Mocks/MockAsyncSequence.swift
Similarly to #2262, test execution ordering was leading to [flaky code coverage results](https://app.codecov.io/gh/RevenueCat/purchases-ios/pull/2262) with this.
Because we didn't have any test coverage, only if some other test changed the `Storefront`, this test was calling the delegate code.
This adds explicit test coverage using a `MockAsyncSequence`.
- Added `StorefrontType` to `StoreKit2StorefrontListenerDelegate` method
- `Storefront` initializers are no longer `Optional` `init?`
- Simplified `StoreKit2StorefrontListenerTests` by moving `AvailabilityChecks` to `setUp`
=> `StoreKit2StorefrontListener`: added tests to fix flaky code coverage

Sources/Misc/SandboxEnvironmentDetector.swift, Sources/Misc/SystemInfo.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift, Tests/UnitTests/Misc/SystemInfoTests.swift
Thanks to @chrisvasselli for the find and initial implementation (#2275).
This supersedes the workaround introduced in #1730, now making `IntegrationTests` not override the `SandboxEnvironmentDetector`.
=> `BundleSandboxEnvironmentDetector`: always return `true` when running on simulator

RevenueCat.xcodeproj/project.pbxproj, RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme, RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme, RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme, Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj, Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme, Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj, Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/xcshareddata/xcschemes/ReceiptParserAPITester.xcscheme, Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
This fixes the last few warnings in the project:
=> Updated targets and schemes for Xcode 14.2

Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
I had this fail with a new class and I couldn't figure out where it was coming from, this will help.
=> `BaseBackendTest`: improved test failure message

Tests/StoreKitUnitTests/UserDefaultsDefaultTests.swift, Tests/UnitTests/Misc/XCTestCase+Extensions.swift
See also #2046.
Depending on test execution order sometimes we were getting crashes when running this test.
Because we're removing `UserDefaults` on purpose to test `UserDefaults.computeDefault`, we want to ignore errors here.
=> `UserDefaultsDefaultTests`: fixed flaky failures

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes #2260 and [SDKONCALL-216].
Follow up to #2245.
The change in #2245 was meant to avoid receipt refresh throttling errors (#2116).
However, that was a regression when using StoreKit config files because those don't get refreshed in the backend.
Unfortunately the workaround introduced in #1945 prevented us from noticing this, because we use `DangerousSettings.InternalSettings.enableReceiptFetchRetry` in our own integration tests.
I added an integration test that explicitly covers this scenario. That fails without this change if disabling that dangerous setting. I thought about making that test run without the setting, but that might lead to flaky failures in CI, which is why we introduced that workaround in the first place. But at least now we have an explicit integration test for …
=> `PurchaseOrchestrator`: always refresh receipt purchasing in sandbox

RevenueCat.xcodeproj/project.pbxproj, Sources/Error Handling/ErrorCode.swift, Sources/Error Handling/ErrorUtils.swift, Sources/Logging/Strings/SigningStrings.swift, Sources/Misc/Signing+ResponseValidation.swift, Sources/Misc/Signing.swift, Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPRequest.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Sources/Networking/HTTPClient/NetworkError.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesErrorCodeAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/ErrorCodesAPI.swift, Tests/UnitTests/Misc/SigningTests.swift, Tests/UnitTests/Mocks/MockETagManager.swift, Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Mocks/MockSigning.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPResponseTests.swift, Tests/UnitTests/Purchasing/ErrorCodeTests.swift
Fixes [CSDK-634].
- Created `HTTPResponseValidationResult`
- Added `HTTPResponseValidationResult` and `HTTPClient.ResponseHeaders` to `HTTPResponse`
- Added new `ErrorCode.signatureVerificationFailed`
- Extracted `SigningType` to create `MockSigning` to test `HTTPClient` without bothering with signatures
- Refactored `ETagManager` to use `HTTPResponse`, making it easier to pass through response headers and verification results
- Stored `HTTPResponseValidationResult` in `ETagManager` cache
- `HTTPClient` handles signatures from response based on `SystemInfo.responseVerificationLevel`
- Renamed `HTTPRequest.createIntegrityEnforcedRequestRequest` to `HTTPRequest.createWithResponseVerification`
- Added lots of tests for this new behavior in `HTTPClient`
- Added lots of new tests for …
=> `HTTPClient`: added signature validation and introduced `ErrorCode.signatureVerificationFailed`

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Fixes #2291.
This has led to issues in the past too (#1994, #2221, 	https://github.com/RevenueCat/purchases-flutter/issues/516, https://github.com/RevenueCat/purchases-flutter/issues/507) because I tried to reuse that code to call a single completion method.
The new version of Swift makes that impossible now, because it detects that `@MainActor` isn't available in iOS 12.
To finally work around all those issues, this simply duplicates this single line of code, which should work across all versions of Swift.
=> Fixed `PurchasesOrchestrator` compilation error on Xcode 14.3 beta 1

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreKitWorkarounds.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/xcshareddata/xcschemes/PurchaseTester.xcscheme
We have a few error messages for StoreKit 1 bugs that look pretty scary. 
However, they really aren't - while they surface genuine bugs in StoreKit, they require no action on the developer's side, and our backend won't be affected. So in practice, they're not useful. 
This PR updates the copy so that: 
- it doesn't suggest using SK2
- it moves from `warn` to `verbose`, since there's really no action on the developer's side needed
- it clarifies what's going on under the hood
| :-: | :-: |
| <img width="1311" alt="Screenshot 2023-02-17 at 3 43 02 PM" src="https://user-images.githubusercontent.com/3922667/219758984-c9593d12-23fb-4076-ab87-2c5454f7084b.png"> | <img width="1304" alt="Screenshot 2023-02-17 at 3 52 05 PM" …
=> clarifies error messages for storekit 1 bugs

Sources/Misc/Deprecations.swift, Sources/Purchasing/Configuration.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
There's been a lot of customer confusion with the use SK2 parameter. 
In order to reduce confusion, and to improve the overall experience, we're moving into a more opinionated approach. 
Currently, we're defaulting to SK1-only. 
Once we get diagnostics data in, we'll be able to get more visibility into real-world, production performance of StoreKit 1 vs StoreKit 2 on a per-API basis. Using this data, we will implement remote configuration to ensure that the best implementation is utilized for each specific functionality, optimizing for maximum stability and performance. 
Until then, we can save our customers from confusion and headache by going back to the simplest approach.
=> Deprecate `usesStoreKit2IfAvailable`

Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift
I hit this bug when I first tried the example. My offerings loaded slowly - so the paywall was empty, and didn't update when the offerings were retrieved.
nope
swiftui example app doesn't update paywall when offerings are retrieved
app stores current state in the shared UserViewModel, but the PaywallView doesn't currently observe changes on this model - so it only shows the state at the point where the view was shown.
This is potentially a state where offerings have not yet been retrieved.
=> SwiftUI: Paywall View should respond to changes on the UserView model

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
=> `PurchaseTester`: added ability to set `Configuration.EntitlementVerificationMode`

Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
I am seeing errors in my logs that are not very helpful:
`2023-02-14 04:20:35.356 Nihongo[96412:1082124] [Purchases] - DEBUG: ℹ️ Store products request failed! Error: The operation couldn’t be completed. (RevenueCat.ProductsFetcherSK2.Error error 0.)`
It looks like there is an error being thrown by `StoreKit.Product.products(for: identifiers)`, but it is wrapped in `productsRequestError` and so no information from the actual underlying error is being printed to the logs.
I tried to follow the pattern I saw in other parts of the framework (specifically, `PurchasesDiagnostics.swift`) to update the localized description of the error to print the localized description of the underlying error.
I don't think there's any unit testing needed for this change, since it should just update the debug …
=> Fix issue where underlying error information for product fetch errors was not printed in log.

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift
The `task` was not being cancelled when `Purchases` was reinitialized, which meant that it was kept in memory,
and so multiple `Purchases` instances were in memory, leading to weird errors.
I've also enabled `verbose` logs to be able to see this more clearly.
=> `PurchaseTester`: fixed leak when reconfiguring `Purchases`

Contributing/RELEASING.md
These were out of date. The new workflow requires pushing the commits before using `bump` so it can find the commits for the changelog.
=> `RELEASING.md`: fixed hotfix instructions

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
This will help testing cache invalidation in the context of signature verification.
See https://linear.app/revenuecat/issue/SDK-2873/invalidate-devicecache-cache-if-entitlement-verification-is-missing
=> `PurchaseTester`: added ability to reload `CustomerInfo` with a custom `CacheFetchPolicy`

Sources/Misc/Signing.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPRequest.swift, Sources/Networking/InternalAPI.swift, Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/Backend/BackendSignatureVerificationTests.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS12-testSendsNonceWhenEnabled.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS13-testSendsNonceWhenEnabled.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS14-testSendsNonceWhenEnabled.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS15-testSendsNonceWhenEnabled.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendGetCustomerInfoTests/iOS16-testSendsNonceWhenEnabled.1.json, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPRequestTests.swift
Instead of manually choosing when to include `nonce` in requests, this data-driven approach ensures that all requests to endpoints that support signature verification will make `HTTPClient` do the right thing.
See also #2277 for how `CustomerInfo` and `EntitlementInfo` will use this.
=> `HTTPClient`: automatically add `nonce` based on `HTTPRequest.Path`

Sources/Caching/DeviceCache.swift, Sources/Identity/IdentityManager.swift, Sources/Logging/Strings/AttributionStrings.swift, Sources/Logging/Strings/IdentityStrings.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift, Tests/UnitTests/Identity/IdentityManagerTests.swift, Tests/UnitTests/Mocks/MockDeviceCache.swift
Deals with [SDK-2817](https://linear.app/revenuecat/issue/SDK-2817/fix-issue-with-missing-subscriber-attributes-on-purchases-[ios])
This is the iOS counterpart to https://github.com/RevenueCat/purchases-android/pull/809
There was an issue where subscriber attributes could be delayed to be synced to the backend. This happened when setting a subscriber attribute AFTER the `logIn` call but BEFORE the `logIn` operation was completed.
This issue happens because we start syncing subscriber attributes immediately when calling `logIn`, but if we set any after that but before the login is complete, they will be assigned to the old user id. We would sync those the next time the app is backgrounded/foregrounded but might be missed if there is a purchase before that happens. When there is a purchase, …
=> Fix issue with missing subscriber attributes if set after login but before login callback

Sources/FoundationExtensions/Date+Extensions.swift, Sources/Logging/Strings/SigningStrings.swift, Sources/Misc/Signing+ResponseVerification.swift, Sources/Misc/Signing.swift, Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Misc/SigningTests.swift, Tests/UnitTests/Mocks/MockETagManager.swift, Tests/UnitTests/Mocks/MockSigning.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
See https://github.com/RevenueCat/khepri/pull/5300
=> `Signing`: added request time & eTag to signature verification

Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift, Sources/LocalReceiptParsing/DataConverters/DateFormatter+Extensions.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/EntitlementInfo.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift, Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
This prevents users from keeping an outdated active entitlement forever.
One could start a free trial then block all further requests from the backend in order to keep that active.
When this check fails, a new warning log is generated:
> WARN: ⚠️ Entitlement is no longer active (expired 2023-02-12 18:15:11 +0000) and it's outside grace period window (last updated 2023-02-12 18:13:31 +0000)
Depends on #2310
=> `EntitlementInfo`: add a grace period limit to outdated entitlements

Sources/Identity/CustomerInfo.swift, Sources/Misc/Signing+ResponseVerification.swift, Sources/Purchasing/VerificationResult.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCVerificationResultAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift, Tests/UnitTests/Misc/SigningTests.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPResponseTests.swift, Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift
See conversation in https://linear.app/revenuecat/issue/SDK-2896/invalidate-devicecache-cache-if-entitlement-verification-is-missing
This is more clear, as "not verified" could be confused as "failed to verify".
This hasn't shipped yet so it's safe to rename.
=> Renamed `VerificationResult.notVerified` to `.notRequested`

Sources/Identity/CustomerInfo.swift, Sources/Purchasing/VerificationResult.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCCustomerInfoAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift
See conversation in https://linear.app/revenuecat/issue/SDK-2842/[android]-create-trusted-property-in-entitlementinfo
This was redundant, it makes more sense to access this from `EntitlementInfos`.
=> `CustomerInfo`: removed `entitlementVerification`

Sources/Purchasing/EntitlementInfo.swift, Sources/Purchasing/EntitlementInfos.swift
See https://github.com/RevenueCat/purchases-ios/pull/2288#discussion_r1127988134
This didn't need to be `Optional` since it's always there.
=> `EntitlementInfo`: request date is not optional

RevenueCat.xcodeproj/project.pbxproj, Sources/Identity/CustomerInfo+ActiveDates.swift, Sources/Identity/CustomerInfo.swift, Sources/Purchasing/EntitlementInfo.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift, Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
=> `CustomerInfo`: use same grace period logic for active subscriptions

Sources/Networking/InternalAPI.swift, Sources/Purchasing/Configuration.swift, Sources/Security/Signing.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPRequestTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Depends on #2326 and #2328.
This allows us to keep all the code, except users won't be able to configure the SDK with this option.
Note that `Signing.ResponseVerificationMode.enforced` _is_ available, so we can still test all that behavior, including from integration tests.
=> Made `Configuration.EntitlementVerificationMode.enforced` unavailable

Sources/Identity/IdentityManager.swift, Sources/Logging/Strings/IdentityStrings.swift, Sources/Networking/Backend.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Identity/IdentityManagerTests.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockCustomerInfoManager.swift
Android counterpart: https://github.com/RevenueCat/purchases-android/pull/844
=> `IdentityManager`: clear `ETagManager` and `DeviceCache` if verification is enabled but cached `CustomerInfo` is not

RevenueCat.xcodeproj/project.pbxproj, Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Security/Signing.swift, Tests/UnitTests/Mocks/MockETagManager.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Essentially we don't want to modify any behavior on `.informational` mode. Everything will continue behaving normally, and simply report verification failures.
=> `ETagManager`: don't ignore failed etags with `Signing.VerificationMode.informational`

Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift
No need to sort the entire list of subscriptions
=> `AppleReceipt.mostRecentActiveSubscription`: performance optimization

RevenueCat.xcodeproj/project.pbxproj, Sources/Security/VerificationResult.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Security/SigningTests.swift
See https://docs.google.com/spreadsheets/d/1kNcFNB8U47N5_vm8Ww57izMgdp60mdzUxZFK-cm46KU/edit#gid=0
- Extracted signature verification `HTTPClient` tests into a separate file
- Added helper stubbing methods to simplify tests
- Created `InformationalSignatureVerificationHTTPClientTests` and `EnforcedSignatureVerificationHTTPClientTests`
- Changed `VerificationResult.from(cache:response:)` to match new expected tests
- Finished coverage for `ResponseVerificationMode.informational` tests
=> Finished signature verification `HTTPClient` tests

Contributing/RELEASING.md
This is necessary to avoid rate limiting errors.
=> `RELEASING.md`: added GitHub rate limiting parameter

Sources/Security/VerificationResult.swift
This is no longer true since #2330.
=> `VerificationResult.notRequested`: removed caching reference

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Date+Extensions.swift, Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift, Sources/Security/Signing+ResponseVerification.swift, Sources/Security/Signing.swift, Sources/SubscriberAttributes/SubscriberAttribute.swift, Tests/UnitTests/FoundationExtensions/DateExtensionsTests.swift, Tests/UnitTests/FoundationExtensions/DispatchTimeIntervalExtensionsTests.swift, Tests/UnitTests/Security/SigningTests.swift, Tests/UnitTests/SubscriberAttributes/SubscriberAttributeTests.swift
Fixes #2338, [SDKONCALL-237], [SDK-2974].
`Int` is actually 32 bits in 32-bit platforms, like `watchOS` still is (sort of).
This fixes 2 potential `Int` overflows: `Date.millisecondsSince1970` and `DispatchTimeInterval` arithmetic using `nanoseconds`.
See also #2340.
[SDKONCALL-237]: https://revenuecats.atlassian.net/browse/SDKONCALL-237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `DispatchTimeInterval` & `Date`: avoid 32-bit overflows, fix `watchOS` crashes

Sources/Networking/HTTPClient/ETagManager.swift, Sources/Security/VerificationResult.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Scenario:
- Response 1: 200 / `VerificationResult.failed`
- Response 2: 304 / `VerificationResult.verified`
Before this change, that was resulting in `VerificationResult.verified`, even though it was using the unverified response body.
This fixes that so that we don't use the ETag for a response that failed validation, even in `ResponseVerificationMode.informational`.
=> `ETagManager`: don't use ETags if response verification failed

CHANGELOG.latest.md, CHANGELOG.md
=> Version 4.17.9 release notes

Sources/Purchasing/Configuration.swift, Sources/Purchasing/EntitlementInfo.swift, Sources/Purchasing/EntitlementInfos.swift, Sources/Security/VerificationResult.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfosAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfosAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
This isn't ready quite ready to be released yet. With this change, `main` can be released once again.
I've added a comment to all the changes so we can easily find them when ready to be made `public` again.
=> `Trusted Entitlements`: changed all APIs to `internal`

Sources/Caching/DeviceCache.swift, Sources/Caching/InMemoryCachedObject.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift, Tests/UnitTests/Caching/InMemoryCachedObjectTests.swift, Tests/UnitTests/Mocks/MockInMemoryCachedOfferings.swift
Having an optional with a default value is redundant. This simply provides a default value in the parameter to simplify the implementation
Also made `InMemoryCachedObject.cachedInstance` a property instead of a method.
=> `DeviceCache`: simplified constructor

Sources/Purchasing/Purchases/Purchases.swift
This was breaking `PurchaseTester`. This property is global for all `Purchases` instances (it's `static`), so resetting it here meant that when re-initializing the SDK, depending on when the old instance was deallocated, the new proxy URL was being reset.
Example:
```swift
Purchases.proxyURL = customURL
Purchases.configure(...)
// Later on, reconfiguring. Not something users should really do
// But this would have unknowingly reset `Purchases.proxyURL` back to `nil`
Purchases.configure(...)
```
=> `Purchases.deinit`: don't reset `Purchases.proxyURL`

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ContentView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
- Reworked `SwiftUI` lifetime and configuration
- Fixed `Purchases` leak
- Fixed `CustomerView` not updating when the view model changed
- Added _return_ key shortcut to `ConfigurationView`
- Display error when fetching `CustomerInfo` fails
- Fixed resetting proxy URL
=> `PurchaseTesterSwiftUI` improvements

Tests/UnitTests/Networking/HTTPClientTests.swift
Simple case that we didn't have coverage for.
=> `HTTPClient`: added test for 2xx response for request with etag

Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
This fixes flaky test failures.
`TestLogHandler` wires into the global log handler. When running test concurrently, depending on which tests and how many are running, there could be a lot of logs being stored in there.
Specifically, `StoreKit1WrapperTests.testUpdatedTransactionsLogsWarningWhenSendingTooManyTransactions` logs 100 messages to test that too many transactions lead to a warning. With the current limit, it only took 50 other logs to trigger this `precondition`, which could happen relatively easily.
=> `TestLogHandler`: increased default capacity

Sources/Networking/HTTPClient/ETagManager.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
Technically the backend would be breaking the contract with this, but it's worth checking that the SDK does something reasonable in this scenario.
=> `ETagManager`: added test for 304 responses with no etag

Sources/Misc/DangerousSettings.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
This will help testing offline entitlements.
Note that this is only available as an `internal` API, and only on `debug` builds.
=> `HTTPClient`: new flag to force server errors

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPStatusCode.swift, Sources/Networking/HTTPClient/RedirectLoggerTaskDelegate.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPStatusCodeTests.swift
This will be used to detect the load balancer redirecting to the load shedder. See also #2362.
=> `HTTPClient`: debug log when performing redirects

Sources/FoundationExtensions/Decoder+Extensions.swift, Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
This allows `Codable` types to provide a default value for a new `Date` field that defaults to `Date()`.
This is going to be used to add a new `Date` field to `ETagManager.Response`.
=> Added `@DefaultDecodable.Now`

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/JSONDecoder+Extensions.swift, Sources/Logging/Strings/OfflineEntitlementsStrings.swift, Sources/Networking/Responses/CustomerInfoResponse.swift, Sources/OfflineEntitlements/CustomerInfo+OfflineEntitlements.swift, Sources/OfflineEntitlements/PurchasedProductsFetcher.swift, Sources/OfflineEntitlements/PurchasedSK2Product.swift, Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift, Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreKit2TransactionListenerTests.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift, Tests/StoreKitUnitTests/UnitTestsConfiguration.storekit
Based on #2352.
Depends on #2351 and #2365.
=> `Offline Entitlements`: create `CustomerInfo` from offline entitlements

Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/10484/workflows/453cb381-e2b4-4549-93fd-4bb7e0e03485/jobs/60959
I'm not quite sure why, but for some reason sometimes, the `tearDown` handle for these tests was running before this `continunation` finished, leading to a crash:
```swift
fatalError(Strings.purchase.purchases_nil.description)
```
This simple change saves `Purchases.shared` before creating a new `Task` to fix that.
=> `SubscriberAttributesManagerIntegrationTests`: fixed potential race condition

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Fixes from #2345.
The changes were made to make `macOS` work better, but they're only available in iOS 16+.
This brings back the previous `NavigationView` and `NavigationLink` APIs that are backwards compatible.
=> `PurchaseTesterSwiftUI`: fixed iOS compilation

Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
`Date`s don't encode milliseconds, which meant that this test could fail.
See #2372.
=> `@DefaultDecodable.Now`: fixed flaky test

Sources/Networking/Operations/GetCustomerInfoOperation.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift
After #2368, `CustomerInfoResponseHandler` is going to perform more tasks. This ensures that if there are multiple callbacks, that's only done once.
=> `PostReceiptDataOperation` / `GetCustomerInfoOperation`: only invoke response handlers once

Sources/Caching/DeviceCache.swift, Sources/Identity/IdentityManager.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift
Fixes #2252, #2364, [SDKONCALL-214], [SDKONCALL-241].
See also #2078 and #2079.
#2078 solved a potential deadlock in `DeviceCache`. This could happen when a background thread was in the middle of writing to `UserDefaults` through `DeviceCache`, and at the same time, the main thread wanted to read from it.
This is normally fine, except that if there are any `NotificationCenter` observations on the `UserDefaults` used, the background thread would then post that notification and wait for the main thread, leading to a deadlock. What #2078 did was to use a different method to make sure that the observation was received in the calling thread.
Additionally, #2079 avoided that observation whenever we used a different `UserDefaults`.
When the SDK changed to a custom `UserDefaults` (#2046), we made …
=> `DeviceCache`: workaround for potential deadlock

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Turns out we had already solved this race condition in #1492 that lead to flaky failures,
but it was only in `BaseStoreKitIntegrationTests`. This moves it up to `BaseBackendIntegrationTests` so that
`SubscriberAttributesManagerIntegrationTests` can use it too.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/10501/workflows/cb6dbf22-cda8-4c41-875b-04b489992631/jobs/61135
=> `SubscriberAttributesManagerIntegrationTests`: fixed flaky failures

Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTests.swift, fastlane/Fastfile, fastlane/README.md
This adds a fastlane lane to execute load shedder integration tests. 
In a follow-up PR I'll call this lane automatically from CircleCI, on a schedule. 
It won't be a part of regular integration tests, since this logic is tied to v3 and static. So only the load shedder itself is getting tested here.
=> Add lane for running iOS v3 load shedder integration tests

.circleci/config.yml, Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTests.swift, fastlane/Fastfile, fastlane/README.md
Adds a scheduled job that runs once a day, every day, for load shedder & backend integration tests.
=> Integration tests: add scheduled job

Tests/TestingApps/PurchaseTester/PurchaseTester/CatsViewController.swift
Because memory leaks in `for await` loop.
Changed `self` to weak capture.
=> `PurchaseTester`: fix memory leaks

Sources/Security/VerificationResult.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCVerificationResultAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift, Tests/UnitTests/Security/SigningTests.swift
This will be used to represent data that has been created and verified locally.
=> Added new `VerificationResult.verifiedOnDevice`

Sources/Logging/Strings/OfflineEntitlementsStrings.swift, Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
Broken by #2358. This is the same as https://github.com/apple/swift/issues/58099
Even though `OfflineEntitlementsStrings` isn't available on iOS 12, it can't contain types that aren't available at runtime on iOS 12.
=> Fix iOS 12 compilation

Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift
I expected it to be marked `Sendable` in the next version of Swift, but it still hasn't so I filed https://github.com/apple/swift/issues/65044.
`DispatchTimeInterval` is a value type, so it's safe to do this. I don't want to remove the `#if swift` version check because I expect it to be marked `Sendable` in a future version.
=> `DispatchTimeInterval`: fixed Xcode 14.3 compilation

Sources/Caching/DeviceCache.swift, Sources/Logging/Strings/PurchaseStrings.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift
Fixes an issue where a deadlock could happen if you fire a notification in the customerInfoListener. 
The issue stems from our usage of NotificationCenter to detect deletion of userDefaults. 
Since we've changed the default UserDefaults anyway, I don't feel like this adds much value anymore, and we've spent wayyyy too much time dealing with race conditions caused by it, so I'm just getting rid of it. 
I couldn't get it to reproduce on my device, but @codykerns was able to get a consistent repro and confirmed the fix with this branch.
=> Fix deadlock when sending notification center in customerInfoListener

Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Mocks/MockETagManager.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
=> `ETagManager`/`HTTPClient`: sending new `X-RC-Last-Refresh-Time` header

Sources/Identity/CustomerInfoManager.swift, Sources/Misc/Concurrency/OperationDispatcher.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Mocks/MockOperationDispatcher.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Fixes #2410 and https://github.com/RevenueCat/react-native-purchases/issues/579.
This adds 2 previously failing tests that reproduce this issue: one directly on `CustomerInfoManager` and another one utilizing `PurchasesDelegate`.
These illustrate the issue: if the observer (through `CustomerInfoManager.monitorChanges` or `PurchasesDelegate`) called a method that ended up reading `CustomerInfoManager`'s data inside of the observation, the SDK would deadlock.
This is because we were invoking the observers while inside the lock. This was unnecessary, so this fixes the issue by ensuring that the observers receive updates after the lock is released, using a new `OperationDispatcher.dispatchAsyncOnMainThread`.
=> `CustomerInfoManager`: fixed deadlock caused by reading `CustomerInfo` inside of observer

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
Follow up to #2350. This fixes compilation until the API is made `public` again.
=> `PurchaseTester`: fixed compilation for `internal` entitlement verification

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Follow up to #2381.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/10666/workflows/872136c8-5309-45de-958a-5957b5868ba5/jobs/63011
When #2381 was introduced, I didn't realize that `SubscriberAttributesManagerIntegrationTests` would be calling `offerings()` without an `SKTestSession`. Why that doesn't _always_ fail I don't understand (my only guess is that based on test order, which is random, sometimes a previously created session is still active in the background), but it _can_ fail due to products not being found.
This ignores those errors while still allowing the server to create the anonymous user.
=> `Integration Tests`: fixed flaky errors when loading offerings

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
This would make issues like #2415 easier to debug.
=> `StoreKit1Wrapper`: added debug log when transaction is removed but no callbacks to notify

Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
Added a new header in httpClient, which is sent only if the customEntitlementsComputation (#2416) setting is enabled.
=> `customEntitlementComputation`: new `X-Custom-Entitlement-Computation` header

Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/10707/workflows/b41375ee-d8a5-44b2-9dd0-63e9628d578e/jobs/63486
For some reason this has been failing lately. It times out, but unfortunately the retries also fail because `SnapshotTesting` looks for a repeated response snapshot instead of the original filename.
=> `BackendPostReceiptDataTests`: increased timeout to fix flaky test

Sources/Purchasing/Purchases/Purchases.swift
Super small and nitpicky, I know, but I just came across this while checking something else and figured it was worth cleaning up since it took like a second.
=> remove unnecessary line break

Sources/Purchasing/Purchases/Purchases.swift
I just came across this code and realized that I knew why it was there just because I was there when we added it, but reading the comment it wouldn't have been that clear to me why we were disfavoring what should be the preferred way of calling `logIn`.
=> clarify reasoning for disfavoredOverload in logIn

Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md, Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md, Sources/Purchasing/Purchases/Purchases.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Adds a new configuration method that's meant as a convenience for enabling customEntitlementsComputation. 
Syntax using this method is just: 
```swift
Purchases.configureInCustomEntitlementsComputationMode(apiKey: "<api_key>", appUserID: "<app_user_id>")
```
=> customEntitlementsComputation part 4: create convenience configuration method

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesTransactionHandlingTests.swift
All StoreKit 1 transactions were being sent with `InitiationSource.purchased`.
#1957 introduced this, but it was only set correctly for SK2.
The consequence of this is that users might see "invalid receipt" errors when posting receipts due to updated transactions from the queue, which can only happen for `InitiationSource.purchased`.
=> `PurchaseOrchestrator`: fix incorrect `InitiationSource` for SK1 queue transactions

Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift, Sources/Identity/IdentityManager.swift, Sources/Logging/Strings/ConfigureStrings.swift, Sources/Logging/Strings/IdentityStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/UnitTests/Identity/IdentityManagerTests.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockIdentityManager.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Adds a new method to switch users without posting to the backend for Custom Entitlements Computation mode.
=> `customEntitlementsComputation`: new method to switch users

Sources/Networking/Backend.swift, Sources/Networking/BackendConfiguration.swift, Sources/Networking/CustomerAPI.swift, Sources/SubscriberAttributes/SubscriberAttribute.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockIdentityAPI.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testDoesNotPostConsentStatus.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testDoesNotPostConsentStatus.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testDoesNotPostConsentStatus.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testDoesNotPostConsentStatus.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testDoesNotPostConsentStatus.1.json, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
Removed automatic syncing of attConsentStatus when sending  a POST /receipt for customEntitlementsComputation
=> `customEntitlementsComputation`: disable automatic sync of `attConsentStatus`

Sources/Misc/Concurrency/Purchases+async.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift
This will remove the `promotionaOffer` purchase methods from the API in the custom entitlement computation package
=> Hide promotional offers APIs in custom entitlements computation package

Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes SDK-3088
Supersedes #2447
Thanks to @tonidero for doing most of this.
Note that it's currently impossible to test this for SK2, so we only have SK1 tests (we have a Radar for that).
The next step will be to deprecate the current API to remove the `userCancelled` property and make this the new behavior.
See also #1910 for an explanation of the different return values of the purchase APIs.
=> Custom Entitlement Computation: avoid `getCustomerInfo` requests for cancelled purchases

Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift, Sources/Logging/Strings/ConfigureStrings.swift, Sources/Misc/Concurrency/Purchases+async.swift, Sources/Misc/Deprecations.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift, Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift, Sources/Support/PurchasesDiagnostics.swift, Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/InstallationTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
- `getCustomerInfo`
- `logIn`
- `logOut`
- `Purchases.attribution`
- `syncPurchases`
- `restorePurchases`
- Trial eligibility
- Promotional purchases
- `async` counterparts
=> Custom Entitlement Computation: disabled unnecessary APIs

Sources/Misc/Concurrency/Purchases+async.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift
=> Custom Entitlement Computation: re-enable `syncPurchases`/`restorePurchases`

Sources/Identity/IdentityManager.swift, Sources/Logging/Strings/IdentityStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Added updating of offerings cache when `switchUser(to:)` is called. 
Also added checking that the new appUserID != the current one and no-op if it is.
=> Update offerings cache when switchUser(to:) is called

Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
It's no longer required with Xcode 14.3.
=> `Integration Tests`: removed `@preconcurrency import`

fastlane/Fastfile
There's some confusion when checking if a tag exists since Fastlane prints a message in red if the tag doesn't exist.
I added a message if the tag doesn't exist, so it doesn't look like there's an error
=> Add message indicating tag doesn't exist

RevenueCat.xcodeproj/project.pbxproj, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/MainThreadMonitor.swift
We've had a few reports of deadlocks (#2412, #2375). This might have not detected them, but it would detect future issues, as well as busy operations running on the main thread.
Example:
=> `Integration Tests`: add `MainThreadMonitor` to ensure main thread is not blocked

Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPStatusCode.swift
We were currently logging the status code retrieved from `ETagManager`, which made it seem like etags weren't working.
Example:
> API request completed: GET /v1/subscribers/identify (200)
With this change, we now log the actual response status code so we can verify the server is returning the correct status code:
> API request completed: GET /v1/subscribers/identify (304)
=> `HTTPClient`: log actual response status code

Sources/Identity/CustomerInfoManager.swift, Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/OfflineEntitlements/CustomerInfo+OfflineEntitlements.swift, Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
This is meant to be a temporary `CustomerInfo` while the backend is offline.
See also #2368.
=> `CustomerInfoManager`: don't cache offline `CustomerInfo`

Sources/Caching/DeviceCache.swift, Sources/Logging/Strings/OfferingStrings.swift, Sources/Networking/Responses/OfferingsResponse.swift, Sources/Purchasing/Offerings.swift, Sources/Purchasing/OfferingsFactory.swift, Sources/Purchasing/OfferingsManager.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift, Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift, Tests/UnitTests/Mocks/MockDeviceCache.swift, Tests/UnitTests/Mocks/MockOfferingsFactory.swift, Tests/UnitTests/Mocks/MockProductsManager.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
This new cache is used only when the server is down, so paywalls can continue to work in that case.
```
- DEBUG: ℹ️ Configuring SDK using RevenueCat's UserDefaults suite.
- DEBUG: ℹ️ No cached Offerings, fetching from network
- DEBUG: ℹ️ Offerings cache is stale, updating from network in foreground
- WARN: ⚠️ Error fetching offerings: server appears down
- DEBUG: ℹ️ MockProductsManager: no stubbed products, returning fake products for ["monthly_freetrial"]
- DEBUG: ℹ️ Vending Offerings from disk cache
```
=> `OfferingsManager`: return `Offerings` from new disk cache when server is down

RevenueCat.xcodeproj/project.pbxproj, Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json, Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
- Added `SnapshotTesting` to `BackendIntegrationTests` target
- Verify `OfferingsResponse` content with snapshots
This relies on the new serializable `OfferingsResponse` from #2495. It will make it trivial to verify the changes with the upcoming metadata in #2498.
=> `Integration Tests`: added snapshot test for `OfferingsResponse`

RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme, Tests/v3LoadShedderIntegration/v3LoadShedderIntegration.xcodeproj/xcshareddata/xcschemes/v3LoadShedderIntegration.xcscheme
For some reason this has been giving a warning:
=> `Xcode`: fixed `.storekit` file references in schemes

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/NetworkStrings.swift, Sources/Misc/DangerousSettings.swift, Sources/Misc/SystemInfo.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift, Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift, Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift, Tests/StoreKitUnitTests/ProductsManagerTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreProductTests.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift, Tests/UnitTests/Mocks/MockOfflineEntitlementsManager.swift, Tests/UnitTests/Mocks/MockSystemInfo.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
```swift
func testOfferingsAreCachedInMemory() async throws {
let onlineOfferings = try await Purchases.shared.offerings()
expect(onlineOfferings.all).toNot(beEmpty())
self.serverDown()
let offlineOfferings = try await Purchases.shared.offerings()
expect(offlineOfferings) === onlineOfferings
}
func testOfferingsAreCachedOnDisk() async throws {
let onlineOfferings = try await Purchases.shared.offerings()
expect(onlineOfferings.all).toNot(beEmpty())
self.serverDown()
await self.resetPurchases()
let offlineOfferings = try await Purchases.shared.offerings()
expect(offlineOfferings.response) == onlineOfferings.response
let offering = try XCTUnwrap(offlineOfferings.current)
expect(offering.availablePackages.count) == onlineOfferings.current?.availablePackages.count …
```
=> `Offline Entitlements`: integration tests

Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift, Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift, Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
This matches the behavior in Android. It still will fail if the mapping hasn't been fetched yet, but if it has and it's empty, it'll still create a `CustomerInfo`. This is useful for apps that don't use entitlements. They'll still be able to check the product ID in `activeSubscriptions`.
=> `Offline Entitlements`: allow creating offline `CustomerInfo` with empty `ProductEntitlementMapping`

Sources/OfflineEntitlements/PurchasedProductsFetcher.swift, Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
This is a best-effort implementation. We can still compute the offline `CustomerInfo` if we found some purchased products.
Extracted from #2368 and added tests.
=> `PurchasedProductsFetcher`: don't throw errors if purchased products were found

Tests/UnitTests/Purchasing/CustomerInfoTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
These 2 tests should have been skipped on iOS 12.
Technically offline entitlements require iOS 15, but we can still run these tests before that, which doesn't hurt. However, in iOS 12, we can't even tell if the `CustomerInfo` was computed offline, so no point running them.
=> `Offline Entitlements`: fixed iOS 12 tests

Sources/Logging/Strings/OfflineEntitlementsStrings.swift, Sources/OfflineEntitlements/OfflineEntitlementsManager.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Mocks/MockOfflineEntitlementsManager.swift, Tests/UnitTests/Mocks/MockSystemInfo.swift, Tests/UnitTests/OfflineEntitlements/OfflineEntitlementsManagerTests.swift
This disables fetching `ProductEntitlementMapping` for `RevenueCat_CustomEntitlementComputation`, which essentially disables offline entitlements.
=> `Offline Entitlements`: disable for custom entitlements mode

Tests/BackendIntegrationTests/MainThreadMonitor.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/11230/workflows/78444bf6-22b8-40fc-ad92-1f29279377d0/jobs/69663
This is meant to detect deadlocks. 1 second is unfortunately too low for CI with limited resources.
=> `MainThreadMonitor`: fixed flakiness in CI

Sources/FoundationExtensions/DispatchTimeInterval+Extensions.swift, Sources/Logging/Strings/OfflineEntitlementsStrings.swift, Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift, Sources/OfflineEntitlements/PurchasedProductsFetcher.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift, Tests/UnitTests/FoundationExtensions/DispatchTimeIntervalExtensionsTests.swift, Tests/UnitTests/Mocks/MockPurchasedProductsFetcher.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
To optimize potentially computing offline `CustomerInfo`, this caches what's likely the most expensive part.
=> `PurchasedProductsFetcher`: cache current entitlements

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Not sure why this broke, but SwiftUI on Mac is incredibly brittle and ever changing.
=> `PurchaseTesterSwiftUI`: fixed macOS UI

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/LocalizedAlertError.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Currently we were only printing that on the console. This will show an alert after the purchase either fails or succeeds.
=> `PurchaseTesterSwiftUI`: added visual feedback for purchase success/failure

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyManager.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyViewModel.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Windows.swift
This allows managing the proxy at runtime through the UI:
See also https://github.com/RevenueCat/khepri-mitm-proxy/pull/6
=> `PurchaseTesterSwiftUI`: added new window on Mac to manage proxy

Sources/OfflineEntitlements/PurchasedProductsFetcher.swift, Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
It forces users to sign in to their AppStore account instead of making `PurchasedProductsFetcher` work completely in the background.
Testing this feature with `PurchaseTester` makes it obvious that it's not feasible, so this removes it.
Integration tests will confirm that it's not actually necessary.
=> `PurchasedProductsFetcher`: removed `AppStore.sync` call

.circleci/config.yml
So we can better debug failures.
=> `CircleCI`: save test archive on `loadshedder-integration-tests`

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyManager.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Proxy/ProxyViewModel.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Follow up to #2518.
Also fixed the `CustomerInfo` `Picker`, which wasn't working on iOS due to its design.
=> `PurchaseTesterSwiftUI`: added `ProxyView` to `iOS`

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
While working on #2533, I knew that my proof of concept had a retain cycle. I however was very confused when it wasn't detected by this mechanism introduced first introduced in #2104.
Turns out that this had been wrong the whole time: the current implementation, as explained by the comment, was executing those blocks in LIFO order, which meant that the references were being set to `nil` before the assertions could be created.
This meant that by the time the `except { [weak purchases = self.purchases] ... }` lines were called, `self.purchases` itself was `nil`, so nothing was being checked.
This simplifies the implementation by inlining the checks, and saving a `weak` reference before clearing the singleton and all the local references.
Luckily there was only one failing test that had to …
=> `BasePurchasesTests`: fixed leak detection

Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
When receiving 500 responses, `HTTPClient` was always calling `ErrorResponse.from(_ data: Data)`, which tried to decode the content as if it was JSON.
However, if the response had something completely different, it would fail to decode.
This wasn't really a bug because `HTTPClient` was still forwarding the right result, but now it will do so without even trying to parse it.
=> `HTTPClient`: don't assume error responses are JSON

Sources/Purchasing/Offering.swift
`defaultValue` in the `getMetadataValue()` doc should be `default`
Update method doc to be `default` instead of `defaultValue`
=> Fix doc on getMetadataValue

.circleci/config.yml
For consistency with the normal `backend-integration-tests` job, this updates `loadshedder-integration-tests`.
I noticed that it was running tests on iOS 15.
We've been getting more flaky failures on this job that this might resolve.
=> `CircleCI`: specify device to run `backend_integration_tests`

Sources/Attribution/AttributionPoster.swift, Sources/Logging/Strings/AttributionStrings.swift, Sources/Networking/Backend.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Sources/Purchasing/Purchases/Attribution.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/APITesters/CustomEntitlementComputationSwiftAPITester/CustomEntitlementComputationSwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/AttributionAPI.swift, Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/main.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift, Tests/UnitTests/Attribution/AttributionPosterTests.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockSystemInfo.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift, Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift, Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS16-testPostReceiptWithAdServicesToken.1.json
- Added `aadAttributionToken` to `PostReceiptDataOperation`
- Exposed `AttributionPoster.adServicesTokenToPostIfNeeded`
- Added snapshot test to verify it's sent
- Added `PurchasesOrchestrator` tests (SK1/SK2) for sending the attribution token
- Added missing `PurchasesOrchestrator` tests for sending attributes
- Added log when marking `AdServices` token as synced
- Exposed `Purchases.attribution` for custom entitlement computation framework (and added to API tester)
- Exposed `Purchases.enableAdServicesAttributionTokenCollection`  for custom entitlement computation framework (and added to API tester)
=> `PostReceiptOperation`: added ability to also post `AdServices` token

Sources/Attribution/AttributionPoster.swift
Just a small refactor to avoid having these magic strings duplicated there.
=> `AttributionPoster`: replaced hardcoded strings with constants

Sources/Attribution/AttributionFetcher.swift, Sources/FoundationExtensions/ProcessInfo+Extensions.swift, Sources/Logging/Strings/AttributionStrings.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/TestPlans/BackendIntegrationTests.xctestplan, Tests/TestPlans/CI-BackendIntegration.xctestplan
Because `AAAttribution.attributionToken()` isn't available on simulators, we currently had no coverage for this entire part of the codebase.
By mocking the token (on simulator + debug + integration tests only), we can verify posting to the server works correctly.
As a follow-up, we can also verify that posting it as part of the receipt with #2549 works correctly as well.
=> `enableAdServicesAttributionTokenCollection`: added integration test

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Concurrency/OperationDispatcher.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Necessary refactor for #2533. This allows `CustomerInfoManager` to have an instance of `TransactionPosterType` instead of the whole `PurchasesOrchestrator`.
Essentially this becomes the hierarchy now:
- Created stateless `TransactionPoster`
- Extracted `handlePurchasedTransaction` into `TransactionPoster`
- The new implementation there is _mostly_ the same, with the one difference that it's stateless. Instead of holding `purchaseCompleteCallbacksByProductID`, that's done by `PurchasesOrchestrator`. The methods there all take a callback, so they're easier to use and don't require keeping a callback around.
- Created `PurchaseSource` to abstract the combo of `isRestore` and `InitiationSource`. This is still messy using the deprecated `allowSharingAppStoreAccount`, but at least that's …
=> Extracted `TransactionPoster` from `PurchasesOrchestrator`

Sources/Networking/Backend.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
This was necessary for a follow-up refactor to #2540. The main change is in `Backend`, the rest are test changes that are required now that the closure is `@Sendable`.
=> `Backend.ResponseHandler` is now `@Sendable`

Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift
This improves an upcoming log from #2533:
```
DEBUG: ℹ️ Found unfinished transaction, will post receipt in lieu of fetching CustomerInfo:
<StoreTransaction:
identifier="9CB3E6CE-A6F6-41EC-B25D-FE0CCE5783F6"
product=""
date="2023-05-26 21:07:55 +0000"
quantity=1
>
```
=> `StoreTransaction`: implemented `description`

RevenueCat.xcodeproj/project.pbxproj, Sources/Identity/CustomerInfoManager.swift, Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift, Tests/StoreKitUnitTests/ManageSubscriptionsHelperTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Identity/IdentityManagerTests.swift, Tests/UnitTests/Mocks/MockIdentityManager.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionFetcher.swift, Tests/UnitTests/Mocks/MockTransactionPoster.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
This fixes the last edge-case for offline entitlements. Solves the following scenario:
```swift
func testPurchaseWhileServerIsDownPostsReceiptWhenForegroundingApp() async throws {
let logger = TestLogHandler()
// 1. Purchase while server is down
self.serverDown()
try await self.purchaseMonthlyProduct()
logger.verifyMessageWasNotLogged("Finishing transaction")
// 2. Server is back
self.serverUp()
// 3. Request current CustomerInfo
let info1 = try await Purchases.shared.customerInfo()
try await self.verifyEntitlementWentThrough(info1)
// 4. Ensure transaction is finished
logger.verifyMessageWasLogged("Finishing transaction", level: .info)
// 5. Restart app
Purchases.shared.invalidateCustomerInfoCache()
await self.resetSingleton()
// 6. To ensure (with a clean cache) that the receipt was …
```
=> `GetCustomerInfo` posts receipts if there are pending transactions

Sources/Misc/Box.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Even though https://bugs.swift.org/browse/SR-15825 is supposedly fixed on Xcode 14.x, and we validated that on CI (#1794), that's still crashing for some reason on iOS 12 devices.
Fixes https://github.com/RevenueCat/purchases-unity/issues/278, [SDKONCALL-267], SDK-3154.
[SDKONCALL-267]: https://revenuecats.atlassian.net/browse/SDKONCALL-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> `SK2StoreProduct`: fix crash on iOS 12

RevenueCat.xcodeproj/project.pbxproj, Sources/Purchasing/Purchases/TransactionPoster.swift, Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift, Tests/UnitTests/Mocks/MockTransactionPoster.swift, Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
Follow up to #2540.
We could add more tests (which are a lot simpler than `PurchasesOrchestratorTests`) but this is just a start.
=> Added `TransactionPoster` tests

Sources/LocalReceiptParsing/BasicTypes/AppleReceipt.swift, Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
Xcode seems to limit logs to some amount of lines, so we were always missing the end of receipts.
This also removes duplicated implementations of `Encodable.jsonEncodedData`.
=> `AppleReceipt.debugDescription`: don't pretty-print JSON

Sources/Identity/CustomerInfoManager.swift, Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift, Tests/UnitTests/Mocks/MockTransactionPoster.swift
This expands the logic added in #2533 to post not only the first transaction, but all of them.
This is important for cases where there might be a consumable transaction. By handling _all_ those, we ensure that we are able to process offline `CustomerInfo` later on, instead of potentially failing due to a consumable transaction still unfinished.
=> `CustomerInfoManager`: post all unfinished transactions

Package.swift
Fixes this warning:
> warning: 'purchases-ios': found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
> purchases-ios/Tests/ReceiptParserTests/ReceiptParserTests-Info.plist
=> `Package.swift` fix warning for unrecognized `Info.plist`

Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/11501/workflows/b978f26f-ce2d-4040-ac40-96e121c4407f/jobs/72997/steps
Same as #2532, this prevents test crashes when this function is called after `Purchases` has been reset.
Test crashes are inconvenient because it makes the entire test run fail, instead of allowing retries.
=> `Integration Tests`: avoid crashes when printing receipt

Sources/Logging/Strings/StoreKitStrings.swift, Sources/Purchasing/ProductsManager.swift, Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift, Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
This goes from:
```
ERROR: 🍎‼️ Store products request failed! Error: UNKNOWN_ERROR
```
To:
```
ERROR: 🍎‼️ Store products request failed! Error: Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x600002b04cf0 {Error Domain=ASDErrorDomain Code=950 "Unhandled exception" UserInfo={NSLocalizedDescription=Unhandled exception, NSLocalizedFailureReason=An unknown error occurred}}}
```
=> `ProductsManager`: improved display of underlying errors

.circleci/config.yml, RevenueCat.xcodeproj/project.pbxproj, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/StoreKitUnitTests/LoggerTests.swift, Tests/TestPlans/BackendIntegrationTests.xctestplan, Tests/TestPlans/CI-BackendIntegration.xctestplan, Tests/UnitTests/Misc/XCTestCase+Extensions.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift, Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift, fastlane/Fastfile
Fixes SDK-3158.
- Added new `BackendCustomEntitlementsIntegrationTests` target that depends on the `RevenueCat_CustomEntitlementComputation` SPM
- Updated `BaseBackendIntegrationTests` and `BaseStoreKitIntegrationTests` to support `RevenueCat_CustomEntitlementComputation`
- Added `CustomEntitlementsComputationIntegrationTests` with custom `Purchases.configureInCustomEntitlementsComputationMode` initialization
- Added integration tests for basic operations
- Verify that none of those integration tests ever use `GetCustomerInfoOperation`
- Added `testGetCustomerInfo` to `OtherIntegrationTests` (we didn't have an explicit test for this)
=> `Custom Entitlements Computation`: added Integration Tests

Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/xcshareddata/xcschemes/testCustomEntitlementsComputation.xcscheme
Probably the scheme wasn't marked as "shared", so it was never pushed to the repo. This is necessary to be able to run the app.
=> `Custom Entitlement Computation`: added missing scheme to project

Sources/FoundationExtensions/Dictionary+Extensions.swift
> Generic parameter 'Value' shadows generic parameter from outer scope with the same name; this is an error in Swift 6
=> `Dictionary.MergeStrategy`: fixed Xcode 15 compilation

Sources/Purchasing/Configuration.swift
This fixes a warning on Xcode 15.
=> `Configuration.Builder`: fixed doc reference

Sources/FoundationExtensions/Dictionary+Extensions.swift
Follow up to #2582. Didn't realize that the issue was the `Value` shouldn't have been there, since it could use the parent `associatedtype` from `Dictionary`.
=> `Dictionary.MergeStrategy`: simplify implementation

Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Turns out this test was only passing because it was waiting for the receipt to be posted during a renewal, not the initial purchase!
This updates the test to reflect the correct expectation (disabling renewals), and added the `XCTExpectFailure` so we can detect if it starts passing in a future iOS version.
Also changed the test to not use `customerInfo()` because of #2563.
=> `StoreKitObserverModeIntegrationTests`: fixed and disabled SK2 `testPurchaseInDevicePostsReceipt`

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/SystemInfo.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewModel.swift, Sources/Support/DebugUI/DebugViewSheetPresentation.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
=> Introduced `debugRevenueCatOverlay()`: new SwiftUI debug overlay

Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md, Sources/Purchasing/Configuration.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift, Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
These still work correctly when using Xcode 14 as well.
=> `Xcode 15`: fixed all documentation warnings

Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugViewModel.swift
- Separate `User ID` and `Original User ID`
- Share button to be able to copy / send configuration as pretty-printed JSON
Thanks to @codykerns for the suggestions.
=> `debugRevenueCatOverlay` improvements

Sources/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
A few tests are failing in iOS 17, so this makes it easier to see what's different in the discounts.
=> `StoreProductDiscount`: added `description`

Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift, Tests/UnitTests/TestHelpers/Matchers.swift
=> Fixed test compilation with `Xcode 15`

Sources/FoundationExtensions/String+Extensions.swift, Sources/Networking/Operations/LogInOperation.swift
This was duplicated code, we can simply use `notEmpty` to be able to detect it. That warning was also unnecessary.
=> Removed unnecessary `Strings.trimmedOrError`

Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift
The "invalid" test URLs we were using are no longer invalid on iOS 17. This fixes those tests by using an `Int` instead of a `String`.
=> Changed tests to work around `URL` decoding differences in `iOS 17`

Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift, Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
A bunch of tests were failing on Xcode 15 due to [a change in Swift](https://github.com/apple/swift/issues/66466), because we relying on being able to verify that the encoded `Data` saved to caches is consistent.
Starting on Swift 5.9 `JSONEncoder` has optimizations that mean we can't rely on it.
To fix this, this PR does 2 things:
- Changed `JSONEncoder.prettyPrinted` to have `.sortedKeys`
- Changed test to verify the decoded response `struct`, not the raw encoded `Data`
Note that I didn't make `JSONEncoder.default` use `.sortedKeys` because of the potential performance impact. `Encodable.prettyPrintedData` is used in tests like `ReceiptFetcherTests` (which this PR fixes) and for debug purposes, but `Encodable.encodedJSON` is used everywhere.
=> `Encodable.jsonEncodedData`: fixed tests on iOS 17 due to inconsistent key ordering

.circleci/config.yml
https://discuss.circleci.com/t/xcode-15-beta-1-released/48298
- #2603
- #2602
- #2605
- #2606
- #2607
=> `CI`: added `iOS 17` job

Sources/Support/PaywallExtensions.swift
Not sure why I didn't notice this when compiling through Xcode, but just noticed this on CI in #2591.
Fixes:
```
❌ /Users/distiller/purchases-ios/Sources/Support/PaywallExtensions.swift:106:27: 'some' return types are only available in application extensions for iOS 13.0.0 or newer
private var products: some Sequence<StoreProduct> {
```
=> `PaywallExtensions`: fixed compilation

Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
We already do this in `BaseBackendIntegrationTests`. There is no point continuing tests if an assertion failed. In fact it can be dangerous because it might lead to a crash instead of a failure, which means it won't get retried, and it would lead to a failure in CI.
=> `StoreKitConfigTestCase`: set `continueAfterFailure` to `false`

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Also hoping that this would work around `FB11799675`, but it still didn't. I still think it's useful to ensure a clean slate in tests.
This new implementation does 3 things:
- Delete transactions from `SKTestSession.allTransactions()` (those should be empty after `SKTestSession.clearTransactions()`, but this method further ensures that)
- Finish transactions from `StoreKit.Transaction.unfinished`
- Delete transactions in `StoreKit.Transaction.unfinished`
Because this new implementation requires an `SKTestSession`, it exposed the fact that we were calling this from `BaseBackendIntegrationTests`, which not all subclasses create an `SKTestSession`. Now it's in `BaseStoreKitIntegrationTests` where it belongs.
=> Improved `finishAllUnfinishedTransactions`

.circleci/config.yml, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, fastlane/Fastfile
Not sure how we didn't notice this before, but the build we were submitting wasn't being updated! It was stuck at 4.17.0 🤦🏻
=> `PurchaseTester`: make CI job always point to current version

Sources/Misc/Deprecations.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift, Tests/StoreKitUnitTests/StoreTransactionTests.swift, Tests/UnitTests/Mocks/MockStoreTransaction.swift
This was added in iOS 17, and it's potentially more accurate than reading `Storefront.currentStorefront` later.
=> `StoreTransaction`: read `Storefront` from `StoreKit.Transaction`

Sources/Caching/DeviceCache.swift, Sources/Logging/Strings/ConfigureStrings.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Misc/SystemInfo.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/UnitTests/Caching/DeviceCacheTests.swift, Tests/UnitTests/Mocks/MockDeviceCache.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
This method was a hack to deal with apps getting `didBecomeActive` notifications in the middle of a purchase when the popups were displayed.
This had several problems:
- It was only being used for StoreKit 1 purchases
- It wasn't used for StoreKit 2 purchases through the SDK
- It wasn't used for purchases initiated outside the SDK (like using the upcoming paywall screens)
- It updated the cache timestamp to "now", including offerings, despite not actually updating data
- It was an indirect and implicit way of solving a problem instead of an explicit one
This solves the same by observing `willEnterForeground`, which only happens when the app actually comes back from the background, and not when it simply loses focus.
=> Removed `preventPurchasePopupCallFromTriggeringCacheRefresh`, update caches on `willEnterForeground`

.circleci/config.yml
Basically disabling #2591. I didn't realize that we can't even run them because of the iOS 11 issue (I had tested changing that locally).
I filed SDK-3184 to drop support in the short term, but for now this disables those tests.
=> `CI`: disable iOS 17 for now

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Looks like `Storefront.current` is usually `nil` during tests.
After #2612, it's important than renewals posted from SK1 and SK2 end up with equivalent cache keys. This will be ensured by a test in #2590, which breaks unless we do this.
Example cache keys between SK1 and SK2:
```
PostReceiptDataOperation $RCAnonymousID:9d38b05059d442b082f915011041bbcb-true-77c15e6fad291c0ff9bf8a4efdfa21eca7cdd74e7a0a4a1bdcf320e8ddcfc2d5\n-com.revenuecat.monthly_4.99.no_intro-0.99-USD-USA--1-0-7096FF06-P1M---1-com.revenuecat.monthly_4.99.1_free_week\n--true\n-[\"$attConsentStatus\": [SubscriberAttribute] key: $attConsentStatus value: notDetermined setTime: 2023-06-12 22:31:56 +0000]
PostReceiptDataOperation $RCAnonymousID:9d38b05059d442b082f915011041bbcb-true-77c15e6fad291c0ff9bf8a4efdfa21eca7cdd74e7a0a4a1b …
```
=> `PurchasesOrchestrator`: also get `Storefront` from SK1

Sources/Networking/Operations/PostReceiptDataOperation.swift
This does not change any behavior, but I was debugging this and was confused about the trailing `"`.
Likely from when this was changed to use `"""`.
=> `PostReceiptDataOperation`: clean up cache key

Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
This would have lead to really confusing failures because the line wouldn't match the file.
=> `verifyNoUnfinishedTransactions`/`verifyUnfinishedTransaction`: added missing `#file` parameter

RevenueCat.xcodeproj/project.pbxproj, Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewController.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOtherAPI.h, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOtherAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift, Tests/TestingApps/PurchaseTester/PurchaseTester/InitialViewController.swift
Built on top of `DebugSwiftUIRootView`. This can be presented either manually, or using `UIViewController.presentDebugRevenueCatOverlay`.
This looks exactly the same as the `SwiftUI` version:
=> New `DebugViewController`: UIKit counterpart for SwiftUI's `debugRevenueCatOverlay`

RevenueCat.xcodeproj/project.pbxproj, Sources/Security/Signing.swift, Tests/UnitTests/Resources/public_keys/invalid_certificate.cer, Tests/UnitTests/Security/SigningTests.swift
This is a leftover from when we were going to embed the certificate as a file, but it's not needed anymore.
=> `Signing`: removed API for loading key from a file

Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
I noticed that `BaseBackendIntegrationTests` sets the `StoreKit2Setting` to `.default`, but in these `StoreKit 1` tests we weren't overriding that setting.
When the default changes to `StoreKit 2`, this would have unknowingly changed and we'd have stopped testing `StoreKit 1`.
=> `IntegrationTests`: explicit `StoreKit 1` mode

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/NetworkStrings.swift, Sources/Misc/DangerousSettings.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Security/FakeSigning.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Similar to #2486. This will be used for SDK-3181.
```
- WARN: ⚠️ Returning fake signature verification failure for 'GET /v1/subscribers/$RCAnonymousID:fc0508bea4a74a41bfc9a69db30d925f'
- ERROR: 😿‼️ Request failed signature verification. Request to /v1/subscribers/$RCAnonymousID%3Afc0508bea4a74a41bfc9a69db30d925f failed verification
```
=> Add `InternalDangerousSettings.forceSignatureFailures`

Tests/UnitTests/Networking/HTTPResponseTests.swift
This didn't start with `test` so it wasn't actually running!
_(I wish `XCTest` moved to some sort of macro like `@Test` in the future to avoid this)._
=> `HTTPResponseTests`: fixed disabled test

Sources/Identity/CustomerInfo.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Tests/UnitTests/Networking/HTTPResponseTests.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift
I noticed this could be improved while working on #2635.
=> `copy(with: VerificationResult)`: optimization to avoid copies

Sources/Logging/Strings/ConfigureStrings.swift, Sources/Purchasing/Purchases/Purchases.swift
I was going through some logs, and realized I couldn't tell what mode was configured, and I thought it would be useful.
=> `Trusted Entitlements`: added debug log with `ResponseVerificationMode`

Sources/Error Handling/BackendError.swift, Sources/Error Handling/ErrorUtils.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Sources/Purchasing/ReceiptFetcher.swift, Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift, Tests/UnitTests/Mocks/MockReceiptFetcher.swift, Tests/UnitTests/Networking/BackendErrorTests.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift, Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift
Added `rc_receipt_url` and `rc_receipt_file_exists`. This is useful when debugging issues like #2558.
This goes from this:
> [Purchases] - ERROR: 💰 Product purchase for 'rc_1099_1w' failed with error: Error Domain=RevenueCat.ErrorCode Code=9 "The receipt is missing." UserInfo={NSLocalizedDescription=The receipt is missing., readable_error_code=MISSING_RECEIPT_FILE, source_function=handlePurchasedTransaction(_:data:completion:), source_file=RevenueCat/TransactionPoster.swift:96}
To this:
> [Purchases] - ERROR: 💰 Product purchase for 'rc_1099_1w' failed with error: Error Domain=RevenueCat.ErrorCode Code=9 "The receipt is missing." UserInfo={NSLocalizedDescription=The receipt is missing., readable_error_code=MISSING_RECEIPT_FILE, source_function=handlePurchasedTransaction(_:data:completion:), …
=> `ErrorUtils.missingReceiptFileError`: added receipt URL `userInfo` context

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Logging/Strings/StoreKitStrings.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit1/PaymentQueueWrapper.swift, Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
This is necessary for the new paywall screens to work.
Tests for this added in #2590.
=> Always initialize `StoreKit2TransactionListener` even on SK1 mode

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Follow up to #2589.
Depends on #2612.
=> `StoreKitObserverModeIntegrationTests`: added test for posting renewals

Tests/UnitTests/TestHelpers/ImageSnapshot.swift
Same as #2602, but didn't notice this in #2630, and since we don't have iOS 17 tests in CI yet, it went unnoticed.
=> `ImageSnapshot`: fixed Xcode 15 compilation

Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewModel.swift, Sources/Support/DebugUI/DebugViewSheetPresentation.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
I wanted to support it to be able to look into #2558.
=> `debugRevenueCatOverlay`: added support for `macOS`

Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewModel.swift, Sources/Support/DebugUI/DebugViewSheetPresentation.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift
=> `debugRevenueCatOverlay`: ability to close on `macOS`/`Catalyst`

Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewModel.swift, Sources/Support/DebugUI/DebugViewSheetPresentation.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
=> `PurchaseTester`: added ability to display `debugRevenueCatOverlay`

Tests/BackendIntegrationTests/MainThreadMonitor.swift
See also #2517.
We keep getting flaky failures with this in CI, which is annoying because it marks the whole test run as failed and it doesn't retry.
The reason for that is because we have to use `fatalError` and can't use `fail()` because this detection has to happen outside the main thread.
If the main thread is blocked, well, we can't rely `XCTest` to run in the main thread.
Ultimately, we can't guarantee that CI machines will be fast enough to ensure they don't get blocked.
The purpose of this class was to detect deadlocks. By increasing it to 30 seconds, we pretty much avoid flaky failures for slow CI machines, but still have the ability to detect if the main thread is deadlocked due to a locking issue.
=> `MainThreadMonitor`: increased threshold

RevenueCat.xcodeproj/project.pbxproj, Sources/LocalReceiptParsing/Helpers/LoggerType.swift, Sources/LocalReceiptParsing/Helpers/ReceiptParserLogger.swift, Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift, Sources/Logging/Logger.swift, Sources/Logging/Strings/AttributionStrings.swift, Sources/Logging/Strings/BackendErrorStrings.swift, Sources/Logging/Strings/CodableStrings.swift, Sources/Logging/Strings/ConfigureStrings.swift, Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/Logging/Strings/DiagnosticsStrings.swift, Sources/Logging/Strings/EligibilityStrings.swift, Sources/Logging/Strings/IdentityStrings.swift, Sources/Logging/Strings/ManageSubscriptionsStrings.swift, Sources/Logging/Strings/NetworkStrings.swift, Sources/Logging/Strings/OfferingStrings.swift, Sources/Logging/Strings/OfflineEntitlementsStrings.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Logging/Strings/SigningStrings.swift, Sources/Logging/Strings/StoreKitStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/Helpers/TestMessage.swift, Tests/BackendIntegrationTests/MainThreadMonitor.swift, Tests/StoreKitUnitTests/LoggerTests.swift, Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift, Tests/UnitTests/Mocks/MockProductsManager.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
Fixes SDK-3173.
`os_log` (and the new `Logger.log`) is the canonical way of logging in Apple platforms, replacing the old `NSLog`. This was made even more useful with the [updates to log printing in Xcode 15](https://developer.apple.com/videos/play/wwdc2023/10226/).
Additionally, this allows us in the future to log `OSLogMessage` (using `OSLogInterpolation`), and therefore being able to mark certain parts of logs as `privacy: .private`.
- Introduced `LogMessage` to ensure every logged message has a `category`
- Created `LoggerStore` to abstract `os.Logger` creation
- Changed `Logger` to use `os.Logger` if available (defaulting to the old `NSLog` otherwise)
- Updated tests to always use `LogMessage` instances (same as #2600)
With these new categories, log provide extra context. Example
``` …
```
=> Changed `Logger` to use `os_log`

Sources/Identity/CustomerInfo+ActiveDates.swift, Sources/Networking/Responses/CustomerInfoResponse.swift, Sources/Purchasing/EntitlementInfo.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift, Tests/UnitTests/Purchasing/EntitlementInfosTests.swift
Addresses https://github.com/RevenueCat/purchases-flutter/issues/692
Shows the product id as `<product>:<base_plan>` if the subscription was purchased from Google Play. This uses the `product_plan_identifier` that is returned with the subscription.
=> Support `product_plan_identifier` for purchased subscriptions from `Google Play`

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/PaywallExtensions.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/OtherAPI.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
- Exposed `internal`-only `Purchases.cachePresentedOfferingIdentifier`
- Changed `SwiftUI` extensions to `static` methods: this is required to be able to call an instance method on them
- Added integration test to verify this offering identifier is used
Technically this is an API change, but these APIs are implicitly beta because they're only available in Xcode 15 beta.
=> `PaywallExtensions`: post purchases with `Offering` identifier

Sources/Networking/HTTPClient/HTTPResponse.swift
Probably a bad conversion to multiline string. It had a leftover `" +`
=> Fixed `HTTPResponse.description`

Sources/Logging/Strings/SigningStrings.swift, Sources/Security/Signing+ResponseVerification.swift
I've been debugging a signature problem in an integration test, and this has been helpful.
=> `Signature Verification`: added test-only log for debugging invalid signatures

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/ETagStrings.swift, Sources/Logging/Strings/NetworkStrings.swift, Sources/Logging/Strings/Strings.swift, Sources/Networking/HTTPClient/ETagManager.swift, Tests/UnitTests/Purchasing/ErrorUtilsTests.swift
These were very important when debugging a new integration test failing regarding ETags.
=> `ETagManager`: added new verbose logs

Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/HTTPClient/HTTPClient.swift
Changed this log:
```
[network] DEBUG: ℹ️ API request failed: GET /v1/subscribers/17571811-B0A4-49DC-B326-572E602BF195: Request failed signature verification.
```
To this:
```
[network] DEBUG: ℹ️ API request failed: GET /v1/subscribers/BD9F38FF-33C6-4A77-86F7-6AEA92E6717D (200): Request failed signature verification.
```
This was useful when debugging #2668 and #2659.
=> `HTTPClient`: improved log for failed requests

Sources/Error Handling/ErrorUtils.swift, Sources/Networking/HTTPClient/NetworkError.swift, Sources/Security/Signing+ResponseVerification.swift, Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift, Tests/UnitTests/Networking/Backend/BackendSignatureVerificationTests.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
I'm debugging a potential issue with signatures, so knowing whether the signature was invalid on a 200 or a 304 was important.
=> `NetworkError.signatureVerificationFailed`: added status code to error `userInfo`

Sources/Networking/HTTPClient/HTTPStatusCode.swift, Tests/UnitTests/Networking/HTTPStatusCodeTests.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift
Adding this new `HTTPStatusCode.unauthorized` has exposed the fact that we were treating all `4xx` as "successfully synced".
=> Documented `HTTPStatusCode.isSuccessfullySynced`

Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Sources/Networking/HTTPClient/NetworkError.swift, Tests/UnitTests/Networking/BaseErrorTests.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift
We've gotten several reports with error messages that aren't very helpful, like #2390.
Turns out that whenever the API returned a non-successful response but without an error code, we always produced _"unknown error"_.
This improves the behavior to default to showing the status code. One example that was very obvious is setting up the SDK with an invalid API key.
- Before:
```
[Purchases] - ERROR: 🍎‼️ Error fetching offerings - The operation couldn’t be completed. (RevenueCat.OfferingsManager.Error error 0.)
Underlying error: The operation couldn’t be completed. (RevenueCat.NetworkError error 6.)
```
- After:
```
[Purchases] - ERROR: 🍎‼️ Error fetching offerings - The operation couldn’t be completed. (RevenueCat.OfferingsManager.Error error 0.)
Underlying error: Unknown error. API request …
```
=> `ErrorResponse`: drastically improved error messages, no more "unknown error"s

Sources/Networking/HTTPClient/HTTPClient.swift
Turns out this was breaking an HTTP 304 integration test in #2659. I'm very confused why we hadn't seen it before.
Possibly it didn't matter for normal requests, but it was breaking signature verification because the `nonce` was different on the new request, and therefore it wouldn't match the cached signature.
=> `HTTPClient`: disable `URLSession` cache

Sources/Networking/HTTPClient/HTTPClient.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift
We had no end-to-end tests for ETags.
=> `Integration Tests`: added tests to verify 304 behavior

Sources/Networking/HTTPClient/ETagManager.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
When working on #2663, the new `isLoadShedder` was not getting the right value for 304 responses because we were returning `[:]`, since we don't store headers in `ETagManager`.
=> `ETagManager.httpResultFromCacheOrBackend`: return response headers

Sources/Logging/Strings/NetworkStrings.swift, Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
This is important to avoid false positives if the API key redirect stops working.
=> `LoadShedderIntegrationTests`: verify requests are actually handled by load shedder

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Configuration.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
This includes the time the user takes to go through the dialogs (including potentially signing in, etc), so it doesn't make a lot of sense.
=> `TimingUtil`: removed slow purchase logs

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
This is the last piece needed after #2612. Transactions handled from `StoreKit.Transaction.updates` were ignoring the result `CustomerInfo`.
On example where this was noticed is when redeeming promo codes: we posted the transaction, but `PurchasesDelegate` was not notified of the change.
=> `PurchasesOrchestrator`: update `CustomerInfoManager` cache after processing transactions

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Fixes #2580.
Promotional offers require a receipt. If there is none (like in sandbox), it means no purchases were found, which implies that the user is not eligible.
=> `getPromotionalOffer`: return `ErrorCode.ineligibleError` if receipt is not found

Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
We had lots of different parts of the code doing `request.url?.absoluteString` and also using different values for e-tags.
This refactor combines all that to use a single `eTag(for:)` method.
I did this as part of #2665, which is getting closed, but it will still be useful if we ever decide to change the content of e-tags.
=> `ETagManager`: refactored e-tag creation and tests

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Locale+Extensions.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift, Tests/UnitTests/FoundationExtensions/LocaleExtensionsTests.swift
This is required to compile for `xrOS`.
=> `Xcode 15`: handle `Locale.currencyCode` deprecation

Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/AdaptiveStack.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ObserverModeManager.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/PurchasesOrchestrator.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
=> `xrOS`: added support to `PurchaseTester`

Sources/FoundationExtensions/UIApplication+RCExtensions.swift, Sources/Misc/SystemInfo.swift
This was missing in #2683, these methods need to be invoked from the `@MainActor`.
=> `xrOS`: fixed runtime warning

Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewController.swift, Sources/Support/DebugUI/DebugViewModel.swift, Sources/Support/DebugUI/DebugViewSheetPresentation.swift, Sources/Support/PaywallExtensions.swift
We can look into making them work in the future, but for now this helps compile the SDK for `xrOS`.
=> `xrOS`: fixed compilation by disabling debug overlay

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
`debugRevenueCatOverlay` is only available on `DEBUG`
=> `PurchaseTester`: fixed release compilation

RevenueCat.xcodeproj/project.pbxproj, Sources/Diagnostics/FileHandler.swift, Sources/FoundationExtensions/String+Extensions.swift, Tests/UnitTests/Diagnostics/FileHandlerTests.swift, Tests/UnitTests/FoundationExtensions/StringExtensionsTests.swift
Implemented as an `actor` to easily synchronize operations on a file.
Simple interface:
=> `Diagnostics`: new `FileHandler` for abstracting file operations

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Data+Extensions.swift, Tests/UnitTests/FoundationExtensions/DataExtensionsTests.swift, Tests/UnitTests/LocalReceiptParsing/TestsAgainstRealReceipts/ReceiptParsing+TestsWithRealReceipts.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift, Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
This was duplicated with the `hexString` implementation, which is also memory efficient.
This also renames the file and removes any unnecessary references to `NSData`
=> Refactored `Data.asString` implementation

Sources/FoundationExtensions/Data+Extensions.swift, Tests/UnitTests/FoundationExtensions/DataExtensionsTests.swift
This also refactors the implementation to be able to share the same code.
This algorithm will be used for some of the components in the new signatures.
=> Add `Data.sha1`

Sources/Identity/CustomerInfo+ActiveDates.swift, Sources/Networking/Responses/CustomerInfoResponse.swift, Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Reported in https://github.com/RevenueCat/purchases-flutter/issues/738. 
After https://github.com/RevenueCat/purchases-ios/pull/2654, we were using the new Google Play identifiers that include the plan id in expiration dates, but we didn't change the system that parses purchase dates. Later on, when we map purchases, we iterate over the expiration dates map, and since that id wasn't found in the purchase dates, it was null, causing the issue in flutter.
This makes the purchase date calculation use the same algorithm that we use for expiration dates to get the new google play product identifiers.
=> Fix google play purchases missing purchase date

Sources/Purchasing/Purchases/Purchases.swift, Tests/StoreKitUnitTests/LoggerTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
`Purchases.verboseLogHandler` changed in #2608 with the introduction of a new `internalLogHandler`.
Restoring the log handler doing `Purchases.verboseLogHandler = Purchases.verboseLogHandler` now loses the message category.
We didn't have test coverage for `Purchases.logHandler` either which this adds as well.
This also fixes tests in https://github.com/RevenueCat/purchases-hybrid-common/pull/435
=> `Purchases.restoreLogHandler`

Sources/Support/DebugUI/DebugContentViews.swift, Sources/Support/DebugUI/DebugView.swift, Sources/Support/DebugUI/DebugViewModel.swift, Sources/Support/DebugUI/DebugViewSheetPresentation.swift
=> `xrOS`: add support for `debugRevenueCatOverlay`

Sources/Misc/PriceFormatterProvider.swift, Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
=> `PriceFormatterProvider.priceFormatterForSK2`: enable on all versions

fastlane/Fastfile
It's useful to have it in `release_checks` lane, to make sure that our framework can be built with `Carthage`.
However, what we actually release is using `export_xcframework`, which also builds the frameworks.
This will make `release` MUCH faster since we no longer build everything twice as many times (and for each platform / architecture combination).
=> `CI`: removed `carthage_archive` from `release` lane

fastlane/Fastfile
_I filed https://github.com/fastlane/fastlane/issues/21359, but for now we can do this ourselves._
This is what happens with Xcode 15 if you try to build with an unsigned `XCFramework`:
That breaks the build until you accept it.
This can be inspected in Xcode:
When using Xcode 15, this modifies the project to save the known signature:
But the `.xcframework` remains compatible with Xcode 14.
=> `XCFramework`: sign archive for `Xcode 15`

Sources/Misc/DateAndTime/TimingUtil.swift, Tests/UnitTests/Misc/TimingUtilTests.swift
This is needed in order to test signature verification timing.
=> `TimingUtil`: added synchronous API

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/Integer+Extensions.swift, Tests/UnitTests/FoundationExtensions/IntegerExtensionsTests.swift
This will be used for extracting intermediate key expiration from the new signature format.
=> Add `UInt32(littleEndian32Bits:)` and `UInt32.littleEndianData`

Sources/Logging/Strings/ConfigureStrings.swift, Sources/Security/Signing.swift, Tests/UnitTests/Security/SigningTests.swift
Same as #2638. This was never needed.
=> Remove unused `Signing.loadPublicKey(with:)`

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
For some reason `synchronize()` is needed so that subsequent reads and writes actually see that we cleared the domain.
I added a new expectation to make sure if this breaks we catch it early instead of a weird failure later in the test.
=> `Integration Tests`: fix clearing `UserDefaults` before each test

.circleci/config.yml, RevenueCat.xcodeproj/project.pbxproj, Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesDiagnosticsAPI.m, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStorefrontAPI.m, Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj, Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
We weren't running iOS 11.x tests anyway because it's no longer possible to install those simulators.
This simply changes the deployment target of **_only_ test targets** to iOS 12.0 so that running those in `Xcode 15.0` doesn't fail.
Note that iOS 17 tests are still disabled in CI since we still have a few failures (see #2606).
=> `Tests`: disabled `iOS 11.x` tests to fix `Xcode 15` tests

Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
I remembered this behavior while going through the code, so I thought it would be useful to encode as integration tests.
=> `Trusted Entitlements`: add integration tests to verify `CustomerInfo` cache invalidation

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
I found this while looking into SDK-3097.
=> Refactor: simplified `PurchasesOrchestrator.syncPurchases`

Sources/Security/VerificationResult.swift
I'm debugging some code and it's harder to follow it when we just print `VerificationResult(rawValue: 1)`
=> `VerificationResult: CustomDebugStringConvertible`

Examples/MagicWeatherSwiftUI/Shared/Sources/Views/PaywallView.swift, RevenueCat.xcodeproj/project.pbxproj, Sources/Purchasing/Offering.swift, Sources/Purchasing/Package.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKitAbstractions/ProductType.swift, Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProductDiscount.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductDiscountAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreProductTests.swift, Tests/UnitTests/Mocks/MockOfferingsFactory.swift
Fixes #1563 and #2193.
This introduces **`DEBUG` and `Swift` only** types that allow creating a whole `Offering` for tests and SwiftUI previews.
Example:
By making it available in only `DEBUG` builds we ensure that apps can't accidentally try to purchase these products, which would be impossible. If this is attempted in `DEBUG` builds, we return `ErrorCode`.
When trying to compile this API in release builds, you get an error with a suggestion:
=> New `TestStoreProduct` for creating mock `StoreProduct`s and `Offering`s

Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
If tests are skipped or failed early, before the `SKTestSession` is initialized, this will crash instead of failing or being skipped.
=> `Integration Tests`: avoid crashes when stopping tests early

Sources/Logging/Strings/SigningStrings.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Sources/Security/Signing+ResponseVerification.swift, Sources/Security/Signing.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift, Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Security/SigningTests.swift
- 32 bytes: intermediate public key
- 4 bytes: Expiration (in days since epoch)
- 64 bytes: intermediate public key signature, signed with the root private key
- 16 bytes: salt
- 64 bytes: payload signature:
- salt
- nonce (if present)
- request time (as int string)
- etag (if present)
- payload
This also adds support for optional nonces for "static" signatures, which is required for #2667.
=> `Trusted Entitlements`: new Signature format

Sources/Logging/Strings/ETagStrings.swift, Sources/Logging/Strings/SigningStrings.swift, Sources/Networking/HTTPClient/ETagManager.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPResponse.swift, Sources/Networking/InternalAPI.swift, Sources/Networking/Operations/GetCustomerInfoOperation.swift, Sources/Networking/Operations/GetIntroEligibilityOperation.swift, Sources/Networking/Operations/GetOfferingsOperation.swift, Sources/Networking/Operations/GetProductEntitlementMappingOperation.swift, Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift, Sources/Networking/Operations/LogInOperation.swift, Sources/Networking/Operations/PostAdServicesTokenOperation.swift, Sources/Networking/Operations/PostAttributionDataOperation.swift, Sources/Networking/Operations/PostOfferForSigningOperation.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Sources/Networking/Operations/PostSubscriberAttributesOperation.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Security/Signing+ResponseVerification.swift, Sources/Security/Signing.swift, Sources/Security/VerificationResult.swift, Tests/UnitTests/Mocks/MockETagManager.swift, Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPResponseTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift, Tests/UnitTests/Security/SigningTests.swift
- `ETagManager` no longer stores the verification mode
- Created new `VerifiedHTTPResponse`, which has the `VerificationResult`, extracted from `HTTPResponse`
- Removed `VerificationResult.from(cache:response:)`
- Changed `SignatureVerificationHTTPClientTests` to test using the real `ETagManager`, so they become more "end to end" unit tests. A lot of them were relying on implementation details of the mock instead of the real `ETagManager`.
- Removed several `HTTPClient` tests that were checking a behavior that was impossible (for example, no verification result despite it being enabled), or that checked behavior based on the cached `VerificationResult`
Depends on #2679 and #2697.
=> `Trusted Entitlements`: update handling of 304 responses

Sources/Logging/Strings/SigningStrings.swift, Sources/Security/Signing.swift, Tests/UnitTests/Security/SigningTests.swift
Last step of the new Signature format. Follow up to #2679 and #2698.
This reverts the public key change in #2679, since that was the intermediate key.
This now extracts the new intermediate public key from the signature, and verifies it using the public key.
=> `Signing`: extract and verify intermediate key

Sources/Misc/DangerousSettings.swift, Sources/Networking/CustomerAPI.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostsReceiptDataWithTestReceiptIdentifier.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS13-testPostsReceiptDataWithTestReceiptIdentifier.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS14-testPostsReceiptDataWithTestReceiptIdentifier.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS15-testPostsReceiptDataWithTestReceiptIdentifier.1.json, Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostsReceiptDataWithTestReceiptIdentifier.1.json, Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithAdServicesToken.1.json, Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithAdServicesToken.1.json, Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS14-testPostReceiptWithAdServicesToken.1.json, Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS15-testPostReceiptWithAdServicesToken.1.json
This allows the backend to disambiguate receipts that are coming from different test invocations.
With `SKTestSession` receipts, [the backend has limited information](https://github.com/RevenueCat/khepri/blob/d8887de84863fd846bee559d2bed03245bfb8467/khepri/stores/apple/local/store_kit_test_receipt_formatter.py#L281) to disambiguate receipts coming from different tests. By adding a new UUID that we can re-generate in each test, we help the backend not mix receipts from separate tests.
Note that the value sent in `X-Apple-Device-Identifier` is unchanged (and verified with tests) because it's important that this is the real `IDFV`, since it's used to validate `AppleReceipt.sha1Hash`.
Depends on https://github.com/RevenueCat/khepri/pull/6183
=> `PostReceiptDataOperation`: add new `testReceiptIdentifier` parameter

Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
Yesterday this was added, making this test fail.
=> `Integration Tests`: updated load-shedder offerings snapshot

Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md, Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
=> `Documentation`: add reference to `TestStoreProduct`

Sources/FoundationExtensions/String+Extensions.swift, Sources/Networking/HTTPClient/HTTPRequest.swift, Sources/Networking/Operations/GetCustomerInfoOperation.swift, Sources/Networking/Operations/GetIntroEligibilityOperation.swift, Sources/Networking/Operations/GetOfferingsOperation.swift, Sources/Networking/Operations/LogInOperation.swift, Sources/Networking/Operations/PostAdServicesTokenOperation.swift, Sources/Networking/Operations/PostAttributionDataOperation.swift, Sources/Networking/Operations/PostSubscriberAttributesOperation.swift, Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift, Tests/UnitTests/FoundationExtensions/StringExtensionsTests.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/HTTPRequestTests.swift
We were escaping users for every (hopefully) request. This refactor moves that responsibility to the path creation in `HTTPRequest.Path` to ensure it's done consistently.
Additionally, this is required so that `SigningTests` produce a consistent path (see #2746).
=> `HTTPRequest.Path`: escape `appUserID`

Sources/Logging/Strings/SigningStrings.swift, Sources/Networking/Backend.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Security/FakeSigning.swift, Sources/Security/Signing+ResponseVerification.swift, Sources/Security/Signing.swift, Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Mocks/MockSigning.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPResponseTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Security/SigningTests.swift
Depends on #2747.
- Changed `Signing` to a `final class`, so it can be instantiated with the api key.
-  Updated all `SigningTests` to include the correct signatures
=> `Trusted Entitlements`: add API key and `HTTPRequest.Path` to signature

Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
This extracts a common `verifySubscriptionExpired`.
If we want to change the approach to detecting this, we can modify a single method.
=> `Integration Tests`: refactored expiration detection

Sources/Logging/Strings/SigningStrings.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPRequest.swift, Sources/Security/Signing+ResponseVerification.swift, Sources/Security/Signing.swift, Tests/UnitTests/Networking/HTTPRequestTests.swift, Tests/UnitTests/Networking/HTTPResponseTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Security/SigningTests.swift
Equivalent to https://github.com/RevenueCat/purchases-android/pull/1119
=> `Trusted Entitlements`: produce verification failures for static endpoints with no signature

Sources/Logging/Strings/SigningStrings.swift, Sources/Security/Signing.swift, Tests/UnitTests/Security/SigningTests.swift
The backend no longer unescapes URLs when creating signatures.
=> `Trusted Entitlements`: update handling of escaped URLs

Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift, Sources/Support/PurchasesDiagnostics.swift, Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift, Tests/UnitTests/Mocks/MockPurchases.swift
Signature verification is not working due to changing signature (see #2744), but the debug screen shouldn't show an error if verification isn't enabled.
=> `PurchasesDiagnostics`: don't test signature verification if it's disabled

Tests/TestingApps/SimpleApp/SimpleApp.xcodeproj/project.pbxproj, Tests/TestingApps/SimpleApp/SimpleApp.xcodeproj/xcshareddata/xcschemes/SimpleApp.xcscheme, Tests/TestingApps/SimpleApp/SimpleApp.xcworkspace/contents.xcworkspacedata, Tests/TestingApps/SimpleApp/SimpleApp.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Tests/TestingApps/SimpleApp/SimpleApp/Assets.xcassets/AccentColor.colorset/Contents.json, Tests/TestingApps/SimpleApp/SimpleApp/Assets.xcassets/AppIcon.appiconset/Contents.json, Tests/TestingApps/SimpleApp/SimpleApp/Assets.xcassets/Contents.json, Tests/TestingApps/SimpleApp/SimpleApp/ContentView.swift, Tests/TestingApps/SimpleApp/SimpleApp/Preview Content/Preview Assets.xcassets/Contents.json, Tests/TestingApps/SimpleApp/SimpleApp/Products.storekit, Tests/TestingApps/SimpleApp/SimpleApp/SimpleApp.entitlements, Tests/TestingApps/SimpleApp/SimpleApp/SimpleApp.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views.swift
Just like `PurchaseTester` this can be used to debug the SDK, but as a much simpler setup.
This depends on the SPM as a relative path, so it's easier to iterate on the main SDK library(s) while using this app.
=> `Testing`: add new `SimpleApp`

Tests/UnitTests/TestHelpers/TestLogHandler.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/12568/workflows/58ed4f07-e5f8-4ed0-821e-87413ac06e11/jobs/86331/steps
The only source of flaky integration tests now is `testPurchaseWhileServerIsDownPostsReceiptAfterServerComesBack`.
I haven't been able to figure out why the capacity is exceeded there, even after looking through the logs and the implementation.
My only guess is leftover transactions.
However, instead of failing the run altogether, this will now make the test fail so it can be retried.
=> `Integration Tests`: `TestLogHandler` no longer crashes tests

Sources/Security/Signing.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/UnitTests/Security/SigningTests.swift
`HealthOperation` for example doesn't send an api key (see `HTTPRequest.Path.authenticated`), so the signature needs to handle that.
=> `Trusted Entitlements`: added support for unauthenticated endpoints

Sources/Logging/Strings/SigningStrings.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Example (the first `warn` log is `debug` and when running RC tests only):
```
[signing] WARN: ⚠️ INVALID SIGNATURE DETECTED:
Request: GET /v1/subscribers/identify
Response: 200
Headers: ["X-Signature: signature", "X-RevenueCat-Request-Time: 1658749988564", "Content-Length: 0", "X-RevenueCat-ETag: etag"]
Body (length: 0): e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[signing] ERROR: 😿‼️ Request to subscribers/identify failed verification. This is likely due to a malicious user intercepting and modifying requests.
```
=> `Trusted Entitlements`: log signature errors on requests with `.informational` mode

Sources/Misc/Codable/AnyEncodable.swift, Tests/UnitTests/Misc/AnyEncodableTests.swift
This will be used for an upcoming test that uses `AnyEncodable` and needs to extract the contents.
=> `AnyEncodable`: also implement `Decodable`

Sources/Purchasing/Configuration.swift, Sources/Purchasing/EntitlementInfo.swift, Sources/Purchasing/EntitlementInfos.swift, Sources/Security/VerificationResult.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfosAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfosAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift, Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTesterWatchOS/PurchaseTesterWatchApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Extensions.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/ConfigurationView.swift, Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
_This is reverting #2350 and #2417_
=> `Trusted Entitlements`: re-enable public API

Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesDelegateTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
The `getCustomerInfo` call is asynchronous, so this expectation should be too.
I also renamed the old property name to "customer".
=> `Tests`: fixed flaky failure with asynchronous check

Sources/Error Handling/ErrorCode.swift
Same as https://github.com/RevenueCat/purchases-android/pull/1132
=> `Trusted Entitlements`: added link to docs in `ErrorCode.signatureVerificationFailed`

Sources/FoundationExtensions/Array+Extensions.swift, Tests/UnitTests/FoundationExtensions/ArrayExtensionsTests.swift, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
This is useful to have in extensions and not just in this test.
=> `Refactor`: extracted `Collection.subscript(safe:)`

RevenueCat.xcodeproj/project.pbxproj, Sources/Security/VerificationResult.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift, Tests/UnitTests/Security/VerificationResultTests.swift
The documentation was slightly updated, because we also need to accept `.verifiedOnDevice`.
=> `TrustedEntitlements`: new `VerificationResult.isVerified`

Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
=> `Tests`: fixed another flaky failure with asynchronous check

Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
While useful, this has proven to be extremely flaky in CI. This relies on `XCTest`'s finishing and the autorelease pool being cleared. When CI is slow, this can take more than 1 second.
We could increase the timeout, but it doesn't make sense to make tests wait for over a second, that can really add up with ~1800 tests, instead of continuing with the next test.
Note that `BaseBackendIntegrationTests` still checks that `Purchases` doesn't leak, so at least we get some level of functional test for this.
=> `Unit Tests`: removed leak detection

Sources/Misc/DateAndTime/Clock.swift, Sources/Misc/DateAndTime/TimingUtil.swift, Tests/UnitTests/Misc/TimingUtilTests.swift, Tests/UnitTests/Mocks/TestClock.swift
These tests will be a lot less flaky now since they won't depend on sleeping the current thread, so they won't be susceptible to slow running CI.
Additionally, we can use `seconds` instead of `milliseconds` which will remove imprecision errors when determining if the time was over the threshold.
=> `TimingUtil`: improved tests by using `Clock`

Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
Similar to #2786 and #2777.
This test was verifying `getCustomerInfoCallCount`, but that gets updated asynchronously since #2533.
The correct version waits for it to be updated, then ensures that it doesn't get updated again after logging out.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/12762/workflows/a7e8c4ac-cecb-4c25-90ff-4390ed226bc4/jobs/88794
=> `Tests`: fixed another flaky test

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Codable/AnyDecodable.swift, Sources/Misc/Codable/DefaultDecodable.swift, Sources/Networking/Responses/OfferingsResponse.swift, Sources/Paywalls/PaywallData.swift, Sources/Paywalls/PaywallTemplate.swift, Sources/Purchasing/Offering.swift, Sources/Purchasing/OfferingsFactory.swift, Tests/APITesters/ObjCAPITester/ObjCAPITester/RCOfferingAPI.m, Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json, Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json, Tests/UnitTests/Misc/XCTestCase+Extensions.swift, Tests/UnitTests/Networking/Responses/BaseHTTPResponseTest.swift, Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_and_default_locale.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Networking/Responses/PaywallDataTests.swift
- Added `Offering.paywall`
- Decoding `PaywallData` in `OfferingsResponse`, using `IgnoreDecodeErrors` (this will be better after #2778)
- New `PaywallData` `struct`
- Added new APIs to testers
- Testing paywall deserialization from `Offerings`
- Testing paywall deserialization separately to check edge cases
- Made `DefaultDecodable` and `AnyDecodable` `Sendable`
=> `Paywalls`: initial configuration types

RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/Example1Template.swift, RevenueCatUI/Templates/TemplateViewType.swift, RevenueCatUI/TestData.swift, Tests/RevenueCatUITests/PaywallViewTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SimpleApp.swift
This adds a new `TemplateViewType` that different templates can conform to.
`PaywallView` now takes `PaywallData` and renders the paywall depending on its template.
=> `Paywalls`: using `PaywallData` and setting up basic template loading

Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
If `result` is `nil` this would have crashed instead of failing.
=> `Tests`: removed forced-unwrap

Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
I did this as part of looking into issues running tests on CI.
Ultimately I found the root cause, but this is a useful refactor to make sure all tests have a shared timeout.
=> `Tests`: unified default timeouts

Sources/Misc/SystemInfo.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift, Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift, Tests/StoreKitUnitTests/ProductsManagerTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift, Tests/UnitTests/Attribution/AttributionPosterTests.swift, Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift, Tests/UnitTests/Misc/SystemInfoTests.swift, Tests/UnitTests/Mocks/MockBackend.swift, Tests/UnitTests/Mocks/MockIdentityManager.swift, Tests/UnitTests/Mocks/MockSystemInfo.swift, Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Backend/BaseBackendTest.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift, Tests/UnitTests/Purchasing/StoreKitAbstractions/StoreKitWorkaroundsTests.swift, Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift, Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
Not sure when we stopped throwing errors, but we no longer do, which simplifies code a lot.
=> `SystemInfo.init` no longer `throws`

Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
This reverts commit 0a814ed8be07cda319ec8150cf668911027f7faa.
The actual fix for the problem was #2802.
=> Revert "`Unit Tests`: removed leak detection"

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/12839/workflows/2b1e24b9-428a-40ed-bcfd-a94d7591236d/jobs/89720/steps
I noticed when downloading the `.xcresult` that the tests had crashed with this:
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   libswiftCore.dylib            	       0x10bc64589 swift::runtime::AccessSet::insert(swift::runtime::Access*, void*, void*, swift::ExclusivityFlags) + 73
1   libswiftCore.dylib            	       0x10bc647e2 swift_beginAccess + 66
2   BackendIntegrationTests       	       0x13ab37c76 default argument 1 of Expectation.toEventually(_:timeout:pollInterval:description:) + 54
3   BackendIntegrationTests       	       0x13ab37b44 closure #1 in BaseBackendIntegrationTests.verifyPurchasesDoesNotLeak() + 276 …
```
=> `Tests`: avoid race-condition in leak detection

RevenueCatUI/Helpers/ProcessedLocalizedConfiguration.swift, RevenueCatUI/Helpers/Variables.swift
Had to join in the fun!
This PR updates the regex logic for variables to use RegexBuilder.
=> `Paywalls`: changed variable handling to use Swift `Regex`

Tests/UnitTests/Purchasing/PackageTypeTests.swift
Follow up to #2797.
These tests are failing there because:
```
failed - Failed encoding 'PackageType.unknown': invalidValue(PackageType.unknown, Swift.EncodingError.Context(codingPath: [], debugDescription: "Top-level PackageType encoded as null JSON fragment.", underlyingError: nil))
```
=> `PackageTypeTests`: fixed iOS 12

.circleci/config.yml, Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift, fastlane/Fastfile, fastlane/README.md
For some reason the existing command was failing, but CI was ignoring that failure.
This moves the job to our `Fastfile`, and fixes compilation.
That API was removed in #2442.
=> `CustomEntitlementsComputation`: fixed API testers

Tests/UnitTests/Misc/XCTestCase+Extensions.swift
=> `throwAssertion`: fixed Xcode 15 compilation

Tests/UnitTests/Mocks/MockDeviceCache.swift
I noticed that in some tests that shouldn't be using real `UserDefaults` this was being logged, even multiple times per test:
> Configuring SDK using RevenueCat's UserDefaults suite.
=> `MockDeviceCache`: avoid using real `UserDefaults`

RevenueCatUI/Templates/Example1Template.swift, RevenueCatUI/Templates/TemplateViewType.swift, Tests/RevenueCatUITests/PackageFilteringTests.swift
Some missing tests for the logic added in #2798.
I've also moved this function to be fined in `PaywallData` instead of the `TemplateViewType` protocol, which makes more sense.
=> `Paywalls`: added tests for `PackageType` filtering

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Codable/NonEmptyStringDecodable.swift, Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
This allows decorating a `String` property in a `Decodable` type so it ensures it gets converted to `nil` if it's empty.
It will be used for `PaywallData`.
=> New `@NonEmptyStringDecodable`

Tests/BackendIntegrationTests/MainThreadMonitor.swift
This was introduced in #2463, as a way to verify the SDK didn't have any deadlocks (#2412, #2375).
However, it has caused more trouble than it's worth, because that loop keeps the main thread busy.
This solution proposed by @aboedo makes it only check every 3 seconds.
If there is a deadlock, it would still detect it. But after it's verified there is no deadlock, it won't check again until that interval has elapsed again.
This makes it so that on a test that takes 6 seconds to run, we only execute this code 2 times instead of... a lot.
=> `MainThreadMonitor`: check deadlocks only ever N seconds

Sources/Paywalls/PaywallData.swift, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
Uses the new wrapper added by #2819.
=> `PaywallData`: ignore empty strings in `LocalizedConfiguration`

RevenueCat.xcodeproj/project.pbxproj, RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift, RevenueCatUI/TestData.swift, Sources/Paywalls/PaywallColor.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_and_default_locale.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json, Tests/UnitTests/Paywalls/PaywallColorTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
This adds a new `PaywallColor` that handles the cross-platform representation of colors, decoding, and even combining light and dark schemes.
`PaywallData.Configuration` also gets the new fields containing the colors.
=> `Paywalls`: added support for decoding colors

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift
Prior to this it was not possible to simulate cancellations with `SKTestSession`.
Relying on the new [`SKTestSession.setSimulatedError`](https://developer.apple.com/documentation/storekittest/sktestsession/4196369-setsimulatederror) (see `FB10300403`)
=> `iOS 17`: added tests for simulating cancellations

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/Codable/EnsureNonEmptyArrayDecodable.swift, Tests/UnitTests/FoundationExtensions/DecoderExtensionTests.swift
This allows us to define properties in a `Decodable` type and ensure that they're not empty.
Example
```swift
struct Data: Codable {
@EnsureNonEmptyArrayDecodable
var value: [String]
}
```
Used for #2832.
=> `@EnsureNonEmptyArrayDecodable`

.circleci/config.yml, Package.swift, RevenueCatUI/Templates/Example1Template.swift, RevenueCatUI/Views/DebugErrorView.swift, Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Tests/APITesters/RevenueCatUIAPITester/RevenueCatUISwiftAPITester.xcodeproj/project.pbxproj, Tests/APITesters/RevenueCatUIAPITester/RevenueCatUISwiftAPITester.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Tests/APITesters/RevenueCatUIAPITester/RevenueCatUISwiftAPITester.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Tests/APITesters/RevenueCatUIAPITester/RevenueCatUISwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme, Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift, Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/main.swift, Tests/RevenueCatUITests/PaywallViewTests.swift, Tests/UnitTests/TestHelpers/OSVersionEquivalent.swift, Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift, fastlane/Fastfile, fastlane/README.md
The new `spm-revenuecat-ui-ios-16` CircleCI job does the following:
- Build using `SPM` on release configuration, on `macOS` (because SPM on command line can only build for the target architecture)
- Run tests on iOS 16 simulator
- Compile new API tests
- Fixed a couple of warnings building `RevenueCatUI`
- Fixed `macOS` `RevenueCatUI` build (even though it will be disabled in #2821).
=> `Paywalls`: set up CI tests and API Tester

RevenueCatUI/PaywallView.swift
In the future we'll be able to polish support for those platforms.
=> `Paywalls`: disable `macOS`/`macCatalyst`/`watchOS` for now

fastlane/Fastfile
These aren't used by CI since the targets are compiled along with our unit tests.
But I noticed the definitions were wrong and wouldn't build.
=> `CI`: fixed Fastlane APITester lanes

Tests/BackendIntegrationTests/MainThreadMonitor.swift, Tests/UnitTests/TestHelpers/CurrentTestCaseTracker.swift
I was testing this locally, and I noticed that sometimes this would trigger _after_ a test had already finished:
```
Test Case '-[BackendIntegrationTests.StoreKit2IntegrationTests testCanPurchasePackage]' passed (16.712 seconds).
Test Suite 'StoreKit2IntegrationTests' passed at 2023-07-18 10:27:45.282.
Executed 1 test, with 0 failures (0 unexpected) in 16.712 (16.713) seconds
Test Suite 'BackendIntegrationTests.xctest' passed at 2023-07-18 10:27:45.282.
Executed 1 test, with 0 failures (0 unexpected) in 16.712 (16.713) seconds
Test Suite 'Selected tests' passed at 2023-07-18 10:27:45.282.
Executed 1 test, with 0 failures (0 unexpected) in 16.712 (16.714) seconds
BackendIntegrationTests/MainThreadMonitor.swift:47: Precondition failed: Main thread was blocked for more than 1.0 seconds …
```
=> `MainThreadMonitor`: don't crash if there is no test in progress

Sources/Misc/Concurrency/Purchases+async.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift, Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
These didn't mean to be exposed, and they're not used.
=> `CustomEntitlementComputation`: removed `syncPurchases`/`restorePurchases`

RevenueCatUI/Templates/Example1Template.swift, RevenueCatUI/Views/IntroEligibilityStateView.swift
Small refactor, starting to take views out of `Example1Template` so they're usable by other templates. This also removes some of the duplicate code.
=> `Paywalls`: extracted `IntroEligibilityStateView`

RevenueCatUI/Data/TestData.swift, RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Purchasing/PurchaseHandler.swift, RevenueCatUI/Templates/Example1Template.swift, RevenueCatUI/Views/AsyncButton.swift, RevenueCatUI/Views/PurchaseButton.swift
Another small refactor, follow up to #2837.
Slowly taking implementation details from `Example1Template` to make it easier to implement more templates.
=> `Paywalls`: extracted `PurchaseButton`

RevenueCatUI/Data/TestData.swift, RevenueCatUI/Helpers/TrialOrIntroEligibilityChecker.swift, Sources/Purchasing/IntroEligibility.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift
This will be used for the multi-package template.
Includes #2858.
=> `Paywalls`: `TrialOrIntroEligibilityChecker.eligibility(for packages:)`

Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
This improves snapshot tests, and means we can reduce the polling time.
=> `Paywalls`: disable animations during unit tests

RevenueCat.xcodeproj/project.pbxproj, Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift
Follow up to #2597.
When we implemented #2449 we couldn't add tests for that difference in behavior. This can be reflected with this test now.
=> `CustomEntitlementComputation`: added integration test for cancellations

.gitignore, Package.resolved, RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, RevenueCat.xcworkspace/xcshareddata/swiftpm/Package.resolved
This is required for Xcode Cloud:
> a resolved file is required when automatic dependency resolution is disabled and should be placed at /Volumes/workspace/repository/RevenueCat.xcworkspace/xcshareddata/swiftpm/Package.resolved. Running resolver because the following dependencies were added: 'purchases-ios' (https://github.com/RevenueCat/purchases-ios)fatalError
=> Add SPM `Package.resolved` for Xcode Cloud

Tests/UnitTests/Networking/BackendErrorTests.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
This has been improved significantly (like #1974). I wrote these tests to see if I could reproduce why the logs in https://github.com/RevenueCat/purchases-flutter/issues/766 don't include the underlying error.
It's likely that's using an old version of the SDK, but these tests are still useful.
=> `NetworkError`: 2 new tests to ensure underlying error is included in description

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift, Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift, Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
This is a similar change to #2532.
I noticed yet another source of crashes in our integration tests.
This is what [the result](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/13247/workflows/52fd2014-7a19-442f-a572-64116393abec/jobs/94728) was:
```
failed - Message 'Finishing transaction' should not have been logged
expected to not find object in collection that satisfies predicate
```
That came from this code:
```swift
self.logger.verifyMessageWasNotLogged("Finishing transaction")
let info1 = try await Purchases.shared.customerInfo()
```
After that assertion failure, `XCTest` continued execution, while it had already tear down `Purchases`, which lead to this crash:
```
Thread 0 Crashed:
0   libswiftCore.dylib            	       0x103b84e81 …
```
=> `IntegrationTests`: replaced `Purchases.shared` with a `throw`ing property

Sources/FoundationExtensions/Decoder+Extensions.swift, Sources/Logging/Strings/CodableStrings.swift, Sources/Networking/HTTPClient/ErrorResponse.swift
This is a simple example, but on a larger JSON it becomes easier for us to debug decoding the entire JSON rather than seeing only the part that failed:
```
[codable] DEBUG: ℹ️ Encountered error when decoding JSON: {"e": "e3"}
[codable] ERROR: 😿‼️ Couldn't decode data from json, it was corrupted: Context(codingPath: [CodingKeys(stringValue: "e", intValue: nil)], debugDescription: "Cannot initialize E from invalid String value e3", underlyingError: nil)
```
=> `Codable`: debug log entire JSON when decoding fails

Tests/UnitTests/Mocks/MockIdentityManager.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
I moved the `Purchases.logLevel` change to the beginning of the test too, which makes this more obvious: every test was creating 2 instances of `MockDeviceCache`.
This also required setting `MockCachingTrialOrIntroPriceEligibilityChecker` to `nil` because that was making `IdentityManager` leak, and therefore one of the 2 `MockDeviceCache`s leak!
=> `BasePurchasesTests`: consolidate to only initialize one `DeviceCache`

Sources/Paywalls/PaywallData.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
`Locale.current` might only report a language and not a region. For example when configuring the scheme like this:
iOS localization supports this, and so should we.
=> `Paywalls`: fuzzy `Locale` lookups

RevenueCatUI/Data/TestData.swift, RevenueCatUI/Templates/MultiPackageTemplate.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Paywalls/PaywallDataTests.swift
=> `Paywalls`: added new `blurredBackgroundImage` configuration

Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
I thought I saw a bug because this wasn't true, and realized that it's important to cover in a test. The order of package should depend on the setting, not the offering order. This test ensures that.
=> `Paywalls`: added test to ensure package selection maintains order

Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/Purchases/PurchasesType.swift
This wasn't meant to be exposed in that build. Same as #2854.
=> `CustomEntitlementComputation`: removed `invalidateCustomerInfoCache`

Tests/UnitTests/Misc/TestCase.swift
We get failures due to this sometimes in `Integration Tests` (https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/13272/workflows/112808d6-7292-4a58-8530-7e499fe9d91f/jobs/95055/tests).
I noticed that it's mostly because of `ReceiptRefreshPolicy.retryUntilProductIsFound`, where we log the receipt multiple times as we wait for the product to be found.
=> `Tests`: increased default logger capacity

Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
I noticed the order of cache updates on SDK initialization was:
- `Offerings`
- `ProductEntitlementMapping`
- `CustomerInfo`
This is inefficient because fetching `CustomerInfo` first is the most important. Also, #2860 will pre-warm intro eligibility, so we want to do that _after_ we might have potentially cleared the intro eligibility cache after a `CustomerInfo` update.
Example log from before:
```
[eligibility] DEBUG: ℹ️ Warming up intro eligibility cache for packages in paywall: [PackageType.$rc_monthly, PackageType.$rc_annual]
[customer] DEBUG: ℹ️ Sending latest CustomerInfo to delegate.
[customer] DEBUG: 😻 CustomerInfo updated from network.
[eligibility] DEBUG: ℹ️ Detected active subscriptions changed. Clearing trial or intro eligibility cache.
```
The new order is:
- `CustomerInfo` …
=> `Perf`: update `CustomerInfo` cache before anything else

Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift, Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProductDiscount.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductDiscountAPI.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift, Tests/StoreKitUnitTests/StoreProductTests.swift
See #2711. This is needed for #2855. In order to be able to create test products for the paywall loading screen, we need to be able to do this in release builds as well.
Another benefit of exposing `TestStoreProduct` in release builds is that it's also usable for pre-built versions of the SDK (like Carthage).
=> `TestStoreProduct`: made available on release builds

RevenueCatUI/Data/TemplateViewConfiguration.swift, RevenueCatUI/Templates/MultiPackageTemplate.swift, RevenueCatUI/Templates/TemplateViewType.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
It's optional, so it defaults to the first package if not set.
=> `Paywalls`: added new `defaultPackage` configuration

Sources/Support/PaywallExtensions.swift
visionOS beta 2 had compile errors in `SubscriptionStoreView`
Replaced `DefaultSubscriptionStoreMarketingContent` with `AutomaticSubscriptionStoreMarketingContent`
=> `xrOS`: fixed `SubscriptionStoreView` for visionOS beta 2

Tests/UnitTests/Misc/XCTestCase+Extensions.swift
This started failing with beta 5.
=> `Xcode 15 beta 5`: fixed test compilation

RevenueCatUI/Data/ProcessedLocalizedConfiguration.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/Templates/MultiPackageTemplate.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
This is now used in `MultiPackageTemplate`, defaulting to the `productName` if none is set.
=> `Paywalls`: added `offerName` parameter

RevenueCatUI/Data/Variables.swift, RevenueCatUI/Helpers/Package+VariableDataProvider.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift
We were relying on both the price and price per month to be formatted the same way. When debugging in the simulator, the actual region doesn't change, so StoreKit's internal price formatter doesn't pick it up.
To make this more resilient, this now checks whether it's a monthly subscription instead of comparing strings.
This is an example where `Locale.current` is only overriden partially and the logic breaks:
=> `Paywalls`: fixed `{{ total_price_and_per_month }}`

RevenueCat.xcodeproj/project.pbxproj, Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift, Tests/StoreKitUnitTests/CachingProductsManagerTests.swift
I noticed this was being logged twice when requesting SK1 products, which makes it seem like we're fetching them twice:
```
[store_kit] DEBUG: ℹ️ No existing products cached, starting store products request for: ["com.revenuecat.monthly_4.99.1_week_intro"]
```
`CachingProductsManager` was introduced in #1907. Explained there is why `ProductsFetcherSK1` keeps some caching behavior.
But the main caching layer is now `CachingProductsManager`, so it makes sense to keep the log only there.
This adds 4 basic integration tests. We had independent coverage of `ProductsManager` and `CachingProductsManager` with a mock `ProductsManager`, but no unit tests covering both together. This serves that purpose too.
=> `CachingProductsManager`: removed duplicate log and added tests

Sources/Networking/OfferingsAPI.swift, Sources/Purchasing/OfferingsManager.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/UnitTests/Mocks/MockOfferingsAPI.swift, Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift, Tests/UnitTests/Purchasing/OfferingsManagerTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
I noticed this in our logs:
```
[offering] DEBUG: ℹ️ No cached Offerings, fetching from network
[purchases] VERBOSE: Updating all caches
[offering] DEBUG: ℹ️ Offerings cache is stale, updating from network in foreground
[offering] DEBUG: ℹ️ Offerings cache is stale, updating from network in foreground
[network] DEBUG: ℹ️ Network operation 'GetOfferingsOperation' found with the same cache key 'GetOfferingsOpe...'. Skipping request.
[network] DEBUG: ℹ️ GetOfferingsOperation: Started
```
The double "updating from network" can be confusing, so this fixes it so it's only logged if the request will actually be started. Also added/updated our tests to verify the correct logs as well as caching behavior.
=> `Logging`: avoid logging "updating offerings" when request is cached

Tests/BackendIntegrationTests/Constants.swift, Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift, Tests/InstallationTests/SPMCustomEntitlementComputationInstallation/InstallationTests.swift, fastlane/Fastfile
We were using the default API key to test the custom entitlement computation package installation and integration tests. This changes that so we use a special API key with some special behavior in the backend to mimic real scenarios.
=> `CustomEntitlementComputation`: use custom API key

Tests/StoreKitUnitTests/StoreProductTests.swift
I saw this log duplicated in our logs. I thought this test would cover the cause for it, but afterwards realized this only happens in hybrids because we call this eagerly.
Either way I thought covering this in a test was helpful.
=> `StoreProduct`: added test covering warning log

Sources/FoundationExtensions/OperationQueue+Extensions.swift, Sources/Logging/Strings/NetworkStrings.swift
This can be useful when figuring out why requests are being shared.
No need to crop it if we have verbose logs.
=> `Logging`: log entire cache key with verbose logs

RevenueCatUI/Data/ProcessedLocalizedConfiguration.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/Helpers/PaywallData+Default.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift, Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift, Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
To be used by upcoming templates.
=> `Paywalls`: added "features" to `LocalizedConfiguration`

RevenueCatUI/Data/ProcessedLocalizedConfiguration.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, RevenueCatUI/Templates/SinglePackageStandardTemplate.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
Not all templates require it, so it's optional from here on.
=> `Paywalls`: changed `subtitle` to be optional

RevenueCatUI/Data/IntroEligibilityViewModel.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, RevenueCatUI/Templates/SinglePackageStandardTemplate.swift, RevenueCatUI/Templates/TemplateViewType.swift
This simplifies template views further. Before they needed to get the `TrialOrIntroEligibilityChecker` environment and call the appropriate method.
Now they just need to inject the new `IntroEligibilityViewModel`, and extract either `.allEligibility` or `singleEligibility` based on the type of template. Everything else is done automatically outside of templates.
=> `Paywalls`: extracted intro eligibility out of templates

RevenueCatUI/Templates/MultiPackageBoldTemplate.swift
Added new border around unselected packages.
(Note that the test snapshots don't included blurred background)
=> `Paywalls`: updated multi-package bold template design

RevenueCatUI/Data/TestData.swift, RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift, RevenueCatUI/Helpers/PaywallData+Default.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, RevenueCatUI/Templates/OnePackageStandardTemplate.swift, RevenueCatUI/Templates/OnePackageWithFeaturesTemplate.swift, RevenueCatUI/Views/FooterView.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_and_default_locale.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json, Tests/UnitTests/Paywalls/PaywallDataTests.swift
`foreground` becomes `text1`, allowing us to keep growing that list just like accents.
`accent1` is now also optional.
=> `Paywalls`: new `text1` and `text2` colors

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
We saw this behavior on a real app. Unfortunately doesn't reproduce in a test, but still useful to cover because it would break many assumptions if we were to see it fail.
=> `Integration Tests`: new test to verify that SK1 purchases don't leave SK2 unfinished transactions

Sources/PrivacyInfo.xcprivacy
See #2619. [Docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):
> CA92.1:
> Declare this reason to access user defaults to read and write information that is only accessible to the app itself.
>
> This reason does not permit reading information that was written by other apps or the system, or writing information that can be accessed by other apps.
=> `PrivacyInfo.xcprivacy`: added `UserDefaults` to access API types

RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
After testing this on a device I realized that both the paywall list in the sample app and the package buttons were only tappable on the labels.
=> `Paywalls`: fixed tappable area for a couple of buttons

Tests/TestingApps/SimpleApp/SimpleApp/Configuration.swift, Tests/TestingApps/SimpleApp/SimpleApp/SimpleApp.swift, Tests/TestingApps/SimpleApp/ci_scripts/ci_pre_xcodebuild.sh, ci_scripts/ci_pre_xcodebuild.sh
This will allow us to automatically make new releases from the `paywalls` branch.
See [docs](https://developer.apple.com/documentation/xcode/writing-custom-build-scripts).
=> `Paywalls`: SimpleApp reads API key from Xcode Cloud environment

RevenueCatUI/Data/TemplateViewConfiguration.swift
This is unnecessary noise, especially potentially when displaying `PaywallData.default` because those packages might not exist in a given app.
=> `Paywalls`: removed "couldn't find package" log

Sources/Purchasing/Purchases/Purchases.swift, Sources/Support/FrameworkDisambiguation.swift
Follow-up to #2860.
Thanks to integration tests for catching this (#2123).
=> `Paywalls`: pre-warm intro eligibility in background thread

Sources/Purchasing/Purchases/Purchases.swift, Sources/Support/FrameworkDisambiguation.swift, Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
I added a paywall to the integration test offering so we can validate the response format with our integration tests.
=> `Paywalls`: updated Integration Test snapshot

RevenueCatUI/Data/Constants.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Purchasing/PurchaseHandler.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, RevenueCatUI/Templates/OnePackageStandardTemplate.swift, RevenueCatUI/Templates/OnePackageWithFeaturesTemplate.swift, RevenueCatUI/Views/AsyncButton.swift, RevenueCatUI/Views/FooterView.swift, RevenueCatUI/Views/LoadingPaywallView.swift, RevenueCatUI/Views/PackageButtonStyle.swift, RevenueCatUI/Views/PurchaseButton.swift, Tests/RevenueCatUITests/BaseSnapshotTest.swift, Tests/RevenueCatUITests/Templates/MultiPackageBoldPaywallViewTests.swift
This allows `PaywallView` to handle state handling during a purchase: instead of the previous behavior where only `PurchaseButton` would disable itself, now the entire `PaywallView` is disabled.
I extracted `PackageButtonStyle` so any template with multi-package selection can get this same behavior: the package selection also becomes disabled, as well as any other button (like restore purchases).
I've also cleaned up the templates since we no longer needed the "Content" inside view, and they can be simplified with a single type.
By making `PurchaseHandler` `@MainActor` we also ensure that all these state transitions lead to UI changes happening exclusively on the main thread.
=> `Paywalls`: moved purchasing state to `PurchaseHandler`

RevenueCatUI/Data/TestData.swift, RevenueCatUI/Data/Variables.swift, RevenueCatUI/Helpers/Package+VariableDataProvider.swift, RevenueCatUI/Helpers/PaywallData+Default.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift, Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift
This could still use more polish, but some basic fixes:
- Fixed colors
- Added application name as a title
- Using `total_price_and_per_month` instead of `price_per_month` so it also works with monthly subscriptions
- Added snapshot test for its dark mode version
=> `Paywalls`: improved default paywall configuration

RevenueCatUI/Helpers/PaywallData+Default.swift, RevenueCatUI/Helpers/PreviewHelpers.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, RevenueCatUI/Templates/OnePackageStandardTemplate.swift, RevenueCatUI/Templates/OnePackageWithFeaturesTemplate.swift, RevenueCatUI/Templates/TemplateViewType.swift, RevenueCatUI/Views/FooterView.swift, RevenueCatUI/Views/PurchaseButton.swift
This makes it easier to preview and iterate on each individual template instead of doing that through `PaywallView`. I extracted a lot of the common code into a new `PreviewHelpers` for this.
=> `Paywalls` added individual previews for templates

Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
This allows debugging the default template.
=> `Paywalls`: added default template to `SamplePaywallsList`

RevenueCatUI/Views/LoadingPaywallView.swift, RevenueCatUI/Views/PackageButtonStyle.swift
This was broken in #2923. Unfortunately it couldn't be caught by snapshot tests because those don't display progress views.
I simplified `PackageButtonStyle` to get the shared `PurchaseHandler.actionInProgress` state instead of relying on whether the button is enabled.
=> `Paywalls`: fixed `LoadingPaywallView` displaying a progress view

RevenueCatUI/Helpers/TrialOrIntroEligibilityChecker.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Purchasing/PurchaseHandler.swift, RevenueCatUI/View+PresentPaywall.swift, Tests/RevenueCatUITests/PresentIfNecessaryTests.swift, Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Follow up to #2930.
Added `PresentIfNecessaryTests` and `PurchaseHandlerTests`.
This also removes the last source of "crashes" whenever `Purchases` isn't configured, leading to errors instead.
=> `Paywalls`: more unit tests for purchasing state

RevenueCatUI/Views/IntroEligibilityStateView.swift
Upcoming paywalls will allow empty offer details. This means that the layout would jump when switching packages, so this deals with that.
=> `Paywalls`: improved `IntroEligibilityStateView` to avoid layout changes

RevenueCatUI/Modifiers/ViewExtensions.swift
This wasn't setting the correct axes on the scroll view. This will be necessary for the upcoming paywall using a horizontal scroll view.
=> `Paywalls`: fixed `View.scrollableIfNecessary`

RevenueCatUI/Data/Localization.swift, RevenueCatUI/Data/TemplateViewConfiguration.swift, RevenueCatUI/Resources/en.lproj/Localizable.strings, RevenueCatUI/Resources/es.lproj/Localizable.strings, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/RevenueCatUITests/LocalizationTests.swift
Useful for template 4, but also for others.
=> `Paywalls`: added ability to calculate and localize subscription discounts

RevenueCatUI/Helpers/PreviewHelpers.swift
This is necessary to get the proper size / aspect-ratio when previewing on iPad.
=> `Paywalls`: added ability to preview templates in a `.sheet`

RevenueCatUI/PaywallView.swift, RevenueCatUI/View+PresentPaywall.swift, Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
This displays a paywall fullscreen, which implies that `PaywallViewMode`. Also corrected the docstring in `PaywallView` since it doesn't necessary imply fullscreen.
=> `Paywalls`: removed `mode` parameter from `presentPaywallIfNecessary`

RevenueCatUI/Data/Variables.swift, RevenueCatUI/Helpers/Package+VariableDataProvider.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift
This will be used by template 4, but also useful in others.
=> `Paywalls`: new `subscription_duration` variable

Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/TestingApps/SimpleApp/SimpleApp/SimpleApp.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/AppContentView.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
It no longer loads the real packages and creates demo paywalls.
=> `Paywalls`: changed `SamplePaywallsList` to work offline

RevenueCatUI/Data/Localization.swift, RevenueCatUI/Data/Strings.swift, RevenueCatUI/Data/TemplateViewConfiguration.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/Data/Variables.swift, RevenueCatUI/Helpers/Package+VariableDataProvider.swift, RevenueCatUI/Resources/en.lproj/Localizable.strings, RevenueCatUI/Resources/es.lproj/Localizable.strings, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift, Tests/RevenueCatUITests/LocalizationTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift
The main change is that `VariableHandler` no longer cashes when trying to determine price per month for non-subscriptions. I added a test to cover this behavior.
=> `Paywalls`: added support for custom and lifetime products

RevenueCatUI/View+PresentPaywall.swift, Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift, Tests/RevenueCatUITests/PresentIfNeededTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/AppContentView.swift
This is a slightly clearer API.
=> `Paywalls`: `presentPaywallIfNecessary` -> `presentPaywallIfNeeded`

RevenueCatUI/Data/TemplateViewConfiguration.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
Thanks to @joshdholtz for catching this.
=> `Paywalls`: fix crash when computing localization with duplicate packages

Sources/Purchasing/StoreKitAbstractions/SK1StoreProduct.swift, Tests/StoreKitUnitTests/StoreProductTests.swift
See https://community.revenuecat.com/sdks-51/purchases-purchasepackage-doesn-t-return-1956?postid=10251#post10251
Because hybrids proactively call this method to construct the internal representation, it gets logged automatically whether they call it or not,.
It's still useful, but making it a warning makes it seem more of a bug.
=> `SK1StoreProduct`: changed `productType` warning to debug

RevenueCatUI/Helpers/PaywallData+Default.swift, RevenueCatUI/Helpers/PreviewHelpers.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/MultiPackageBoldTemplate.swift, RevenueCatUI/Templates/OnePackageStandardTemplate.swift, RevenueCatUI/Templates/OnePackageWithFeaturesTemplate.swift, RevenueCatUI/Templates/TemplateViewType.swift, RevenueCatUI/View+PresentPaywall.swift, RevenueCatUI/Views/LoadingPaywallView.swift, RevenueCatUI/Views/PurchaseButton.swift
=> `Paywalls`: fixed `tvOS` compilation by making it explicitly unavailable

RevenueCatUI/Data/ProcessedLocalizedConfiguration.swift, RevenueCatUI/Views/IntroEligibilityStateView.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Paywalls/PaywallDataTests.swift
In template 4 this is optional, so all templates will support this now.
=> `Paywalls`: changed `offerDetails` to be optional

RevenueCatUI/Helpers/PaywallData+Default.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Views/LoadingPaywallView.swift
Currently it was doing a best effort and showing `weekly`/`monthly`/`annual` if those existed in the offering. This makes it so it doesn't have to guess, and it creates a `Paywall` using the `availablePackages`.
=> `Paywalls`: changed default `PaywallData` to display available packages

Tests/TestingApps/SimpleApp/SimpleApp/Views/OfferingsList.swift
I noticed that every time I opened this it was in a different order. That's because `dictionary.values` is non-deterministic, so this sorts them by description now.
=> `Paywalls`: sort offerings list in sample app

Tests/TestingApps/SimpleApp/SimpleApp.xcodeproj/xcshareddata/xcschemes/SimpleApp - Live Config.xcscheme
I broke something and noticed that I wasn't seeing the error in TestFlight. Because this is a test app, it's useful to see the debug errors there too.
=> `Paywalls`: deploy `debug` sample app

RevenueCatUI/Data/TestData.swift, RevenueCatUI/Modifiers/ViewExtensions.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/MultiPackageHorizontalTemplate.swift, RevenueCatUI/Templates/TemplateViewType.swift, Sources/Paywalls/PaywallTemplate.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/RevenueCatUITests/Templates/MultiPackageHorizontalPaywallViewTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
=> `Paywalls`: multi-package horizontal template 

Sources/Attribution/AttributionPoster.swift, Sources/Purchasing/Purchases/Attribution.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Attribution/AttributionPosterTests.swift
It was not clear what `postAdServicesTokenIfNeeded()` was doing for anybody unfamiliar with our codebase or AdServices. This method is in `applicationWillEnterForeground` and without digging into any of the implementation, it looks like it could send the attribution token every time the app enters the foreground. 
The behavior was actually only sending it once per install (as it should) so the method rename reflects that.
Renames `postAdServicesTokenIfNeeded()` to `postAdServicesTokenOncePerInstallIfNeeded()`
=> `AdServices`: Rename `postAdServicesTokenIfNeeded()` to `postAdServicesTokenOncePerInstallIfNeeded()`

RevenueCatUI/Data/Localization.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/Data/Variables.swift, RevenueCatUI/Helpers/Package+VariableDataProvider.swift, RevenueCatUI/Helpers/PaywallData+Default.swift, Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json, Tests/RevenueCatUITests/Data/PackageVariablesTests.swift, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift, Tests/RevenueCatUITests/LocalizationTests.swift, Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_and_default_locale.json, Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
These match the new agreed upon variables.
- Improved the localized unit abbreviations
- Refactored `VariableDataProvider` so all the logic is now in `Package`
- Added new tests for `Package` variables
=> `Paywalls`: updated variable names

Sources/Networking/OfferingsAPI.swift, Sources/Networking/Operations/GetIntroEligibilityOperation.swift, Sources/Purchasing/CachingTrialOrIntroPriceEligibilityChecker.swift, Sources/Purchasing/Purchases/Purchases.swift, Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift, Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift, Tests/UnitTests/Mocks/MockOfferingsAPI.swift, Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift, Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift, Tests/UnitTests/Purchasing/CachingTrialOrIntroPriceEligibilityCheckerTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Order is irrelevant when requesting intro eligibility.
Note that I haven't changed the public API because that wouldn't be backwards compatible.
=> `IntroEligibility`: changed products to `Set<String>`

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/EligibilityStrings.swift, Sources/Paywalls/PaywallCacheWarming.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Mocks/MockPaywallCacheWarming.swift, Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
This refactors #2860 extracting it to a separate type so we can easily extend it to pre-warm the image cache as well (PWL-10).
=> `Paywalls`: extracted `PaywallCacheWarming`

RevenueCat.xcodeproj/project.pbxproj, Sources/Logging/Strings/EligibilityStrings.swift, Sources/Logging/Strings/PaywallsStrings.swift, Sources/Logging/Strings/Strings.swift, Sources/Paywalls/PaywallCacheWarming.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Mocks/MockPaywallCacheWarming.swift, Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
This relies on `AsyncImage` using `URLSession.shared`
I've tested this, and the app doesn't even make a request the second time around because the images are caches on disk.
=> `Paywalls`: warm-up image cache

RevenueCatUI/Templates/Template2View.swift
Selected offer details text color was using background color
Switched selected offer details foreground to using `accent1Color`
=> `Paywalls`: fix template 2 selected text offer details color

RevenueCat.xcodeproj/project.pbxproj, Sources/Caching/DeviceCache.swift, Sources/Caching/PostedTransactionCache.swift, Tests/UnitTests/Caching/PostedTransactionCacheTests.swift, Tests/UnitTests/Mocks/MockDeviceCache.swift
This will be used to skip posting the same transaction multiple times, as a way to work around StoreKit reporting SK1 notifications from SK2 APIs.
=> Created `PostedTransactionCache`

RevenueCat.xcodeproj/project.pbxproj, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/Helpers/CustomPuchasesOrchestrator.swift, Tests/BackendIntegrationTests/Helpers/ExternalPurchasesManager.swift, Tests/BackendIntegrationTests/Helpers/ObserverModeManager.swift, Tests/BackendIntegrationTests/Helpers/SK1ProductFetcher.swift, Tests/BackendIntegrationTests/Helpers/SK2ProductFetcher.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
This extracts the purchasing code into a new `ExternalPurchasesManager` and `ObserverModeManager`, which can be used to perform purchases without using the SDK.
I've also bumped the deployment target of integration tests to 15.0 to simplify the code.
=> `Integration Tests`: added more observer mode tests

RevenueCat.xcodeproj/project.pbxproj, Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Misc/Deprecations.swift, Sources/Networking/Operations/PostReceiptDataOperation.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/StoreTransactionTests.swift, Tests/UnitTests/Mocks/MockOperationDispatcher.swift, Tests/UnitTests/Mocks/MockPayment.swift, Tests/UnitTests/Mocks/MockStoreTransaction.swift, Tests/UnitTests/Mocks/MockTransaction.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
This adds tests and a fix for a scenario discovered by @aboedo and @mcastany.
- Make a purchase of product_1
- Close app
- Renewals happen in the background
- Subscription expires
- Open app, renewals are in the queue but not processed yet
- Start a purchase of `product_1` (`SKPaymentQueue.add`)
- StoreKit queue shows renewal from step 3 as finished, it's expired
- SDK sees finished transaction in the queue for `product_1`
- SDK sees completion block for `product_1`, considers it a successful `.purchase`
- SDK posts receipt, `initiation_source: .purchase` 💥
- Backend replies with 422 because StoreKit hasn't processed the transaction from 6
The fix looks at the date when the completion block was added (the time `.purchase()` is called).
If the transaction was created _before_ this, we know …
=> `PurchasesOrchestrator`: disambiguate transactions from the queue

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift, Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
This is a preparatory refactor for an upcoming fix.
This improves the thread-safety of this class, and also refactors its mock to use a `protocol` instead.
=> `StoreKit2TransactionListener`: converted into an `actor`

Sources/FoundationExtensions/AsyncExtensions.swift, Sources/Purchasing/StoreKit2/StoreKit2StorefrontListener.swift, Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift, Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift, Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
Currently when launching an app in SK1 mode, if there are multiple transactions in the queue, we handle them all and begin operations in parallel. If the cache keys are the same, those end up being a combined POST receipt request.
However with `StoreKit 2`, because we were waiting to handle each one of the `StoreKit.Transaction.updates` using `await`, we ended up posting them all sequentially, instead of relying on `CallbackCache`.
This also adds a lot more coverage for `StoreKit2TransactionListener` to verify this behavior.
=> `StoreKit2TransactionListener`: handle transactions asynchronously

Sources/Purchasing/CachingProductsManager.swift
@joshdholtz found this because he had a typo in his product setup. It shouldn't happen, but technically `SK2StoreProduct.hashValue` is not _just_ the product identifier.
=> `CachingProductsManager`: avoid crash when caching different products with same identifier

fastlane/Fastfile
This avoids false negatives due to flaky failures.
=> `Paywalls`: retry test failures

RevenueCatUI/Templates/Template1View.swift
=> `Paywalls`: fixed horizontal padding on template 1

RevenueCatUI/Views/PurchaseButton.swift
Tapping multiple times on the `PurchaseButton` can lead to "purchase already in progress", because of a race condition with SwiftUI not updating the `.disabled` state on time. This works around that.
=> `Paywalls`: prevent multiple concurrent purchases

RevenueCat.xcodeproj/project.pbxproj, Sources/Error Handling/ErrorUtils.swift, Sources/Logging/Strings/NetworkStrings.swift, Sources/Misc/SystemInfo.swift, Sources/Networking/HTTPClient/HTTPClient.swift, Sources/Networking/HTTPClient/HTTPRequest.swift, Sources/Networking/HTTPClient/HTTPRequestPath.swift, Sources/Networking/HTTPClient/NetworkError.swift, Sources/Security/Signing.swift, Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift, Tests/UnitTests/Misc/SystemInfoTests.swift, Tests/UnitTests/Mocks/MockHTTPClient.swift, Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift, Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift, Tests/UnitTests/Networking/Backend/BackendSignatureVerificationTests.swift, Tests/UnitTests/Networking/ETagManagerTests.swift, Tests/UnitTests/Networking/HTTPClientTests.swift, Tests/UnitTests/Networking/HTTPRequestTests.swift, Tests/UnitTests/Networking/NetworkErrorTests.swift, Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Security/SigningTests.swift
This paves the way to add a second set of paths with a separate server URL to be able to shed requests to offerings and product entitlement mapping to a separate server.
- New `HTTPRequestPath` with the same properties as `HTTPRequest.Path` + a new `serverHostURL`
- Moved proxy logic from `SystemInfo`/`HTTPClient` to `HTTPRequestPath`
- Simplified `HTTPRequest` implementation
=> `HTTPClient`: extracted `HTTPRequestPath` protocol

Package.swift
This is a small follow-up to #2989. Thanks @bcapps for reporting this.
=> `Custom Entitlement Computation`: fixed `visionOS` build

Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
This is useful to verify how these 2 features are working together.
=> `Integration Tests`: test for `SignatureVerificationMode.informational` and receipt posting when fetching `CustomerInfo`

.circleci/config.yml, Package.swift, Package@swift-5.7.swift, Package@swift-5.8.swift
Fixes #2998. See #2989 for why this is needed in the first place.
This is now fixed in SPM: https://github.com/apple/swift-package-manager/pull/6794, but we need a workaround for now.
Since `.custom` doesn't work properly (it gets evaluated in Xcode even outside of that platform), this splits `Package.swift` based on Xcode version.
Thanks @neonichu for helping with this.
=> `Xcode 15`: fix non-`visionOS` build by replacing `.custom` platform

Sources/FoundationExtensions/OperationQueue+Extensions.swift, Sources/Identity/CustomerInfoManager.swift, Sources/Logging/Strings/CustomerInfoStrings.swift, Sources/Logging/Strings/NetworkStrings.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift, Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift, Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift, Tests/UnitTests/Mocks/MockTransactionPoster.swift, Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift, Tests/UnitTests/TestHelpers/TestLogHandler.swift
The existing implementation was posting them in sequence, which meant that it was always going to make N requests.
With this new implementation we can ensure that only one request is made for all transactions.
=> `CustomerInfoManager`: post transactions in parallel to POST receipts only once

Sources/Identity/CustomerInfo.swift, Sources/Purchasing/NonSubscriptionTransaction.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json, Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
There were some questions about these in #2841, and realized we had no test coverage for them.
This also improves the documentation of `CustomerInfo.nonSubscriptions` and `NonSubscriptionTransaction`.
=> `Integration Tests`: added tests for non-renewing and non-consumable packages

Sources/Networking/Responses/CustomerInfoResponse.swift, Sources/Purchasing/NonSubscriptionTransaction.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift, Tests/UnitTests/Networking/Responses/Fixtures/CustomerInfo.json, Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json, Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithFailedVerificationResponse.1.json, Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithVerifiedResponse.1.json, Tests/UnitTests/Purchasing/CustomerInfoTests.swift, Tests/UnitTests/Purchasing/TransactionsFactoryTests.swift
=> Added `internal` `NonSubscriptionTransaction.storeTransactionIdentifier`

.swiftlint.yml
See https://realm.github.io/SwiftLint/unneeded_synthesized_initializer.html
This is currently broken (https://github.com/realm/SwiftLint/issues/5153) which leads to `swiftlint --autocorrect` removing actually needed code.
=> `SwiftLint`: disable `unneeded_synthesized_initializer`

Tests/BackendIntegrationTests/OtherIntegrationTests.swift
This adds more coverage for why we don't actually need #2983.
=> `Integration Tests`: add tests to verify `CustomerInfo`+`Offerings` request de-dupping

Sources/Logging/Strings/NetworkStrings.swift, Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/OtherIntegrationTests.swift, Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
#2983 was an attempt to work around this. Instead, this PR adds integration tests to cover this behavior and ensure that we don't make duplicate requests.
=> `Integration Tests`: begin tests with `UIApplication.willEnterForegroundNotification` to simulate a real app

RevenueCat.xcodeproj/project.pbxproj, Sources/Identity/CustomerInfo+NonSubscriptions.swift, Sources/Logging/Strings/PurchaseStrings.swift, Sources/Misc/Deprecations.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/SK2StoreTransaction.swift, Sources/Purchasing/StoreKitAbstractions/StoreTransaction.swift, Sources/Support/FrameworkDisambiguation.swift, Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/StoreTransactionTests.swift, Tests/UnitTests/Mocks/MockStoreTransaction.swift, Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
This ensures that if the server returns a 200, but didn't actually process the transaction, we don't lose it forever.
When this happens, a warning will be logged:
```
[purchases] DEBUG: ℹ️ TransactionPoster: handling transaction for product 'BA92DCD8-74C2-45FF-AEE4-2FFD036AF827'
[purchases] WARN: ⚠️ Transaction '19B3BD23-181B-442A-A5B8-05D686ED98E2' will not be finished: it's a non-subscription and it's missing in CustomerInfo list: []
```
- #3008
- #3009
=> `TransactionPoster`: don't finish transactions for non-subscriptions if they're not processed

RevenueCat.xcodeproj/project.pbxproj, Sources/Misc/DateAndTime/Clock.swift, Sources/Misc/DateAndTime/TimingUtil.swift, Sources/Misc/SystemInfo.swift, Sources/Networking/Backend.swift, Sources/Purchasing/ReceiptFetcher.swift, Tests/UnitTests/Mocks/MockSystemInfo.swift, Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift, Tests/UnitTests/Purchasing/ReceiptFetcherTests.swift, Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
This extracts a useful refactor from #2983: `ClockType` now lives in `SystemInfo`, so types that depend on type can use the same clock, and tests can rely on the mocked `TestClock`.
=> `SystemInfo`: added `ClockType`

Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
This test was added in #2841, but iOS 12 can't detect offline `CustomerInfo`s because those aren't available, so this test isn't relevant there.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/14193/workflows/a3836667-878c-4bdd-939a-e809e9f0ac5a/jobs/107291/tests
=> `TransactionPoster`: fix iOS 12 test

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Purchases/TransactionPoster.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Looking into #3020, it would have been helpful to see these.
=> `TransactionPoster`: added transaction ID and Date to log

.github/ISSUE_TEMPLATE/bug_report.md
- Made the required fields a bit more obvious
- Changed some fields to checkboxes
- A reference to `.verbose` logs
=> `GitHub`: improved `ISSUE_TEMPLATE`

RevenueCat.xcodeproj/project.pbxproj, RevenueCatUI/Data/PaywallData+Validation.swift, RevenueCatUI/Data/PaywallTemplate.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/Data/Variables.swift, RevenueCatUI/Helpers/PaywallData+Default.swift, RevenueCatUI/Helpers/PreviewHelpers.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/TemplateViewType.swift, RevenueCatUI/Views/LoadingPaywallView.swift, Sources/Paywalls/PaywallData.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift, Tests/RevenueCatUITests/Data/PaywallDataValidationTests.swift, Tests/RevenueCatUITests/Data/VariablesTests.swift, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json, Tests/RevenueCatUITests/Helpers/DataExtensions.swift, Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift, Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/OfferingsList.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift, Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift, Tests/UnitTests/Paywalls/PaywallDataTests.swift
See https://docs.google.com/document/d/1oLZR77apAjZf04hDzlrJpPaFV0xhuQ1-hApsNBohhfA/edit
This simplifies `PaywallView`: the validated `PaywallData` is what's always displayed, and a `DebugErrorView` containing an error description will potentially explain why a default paywall is being displayed.
=> `Paywalls`: validate `PaywallData` to ensure displayed data is always correct

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
I was looking into #3020, and saw that we already have this test to cover downgrades. I added an extra assertion to verify entitlements.
I also ran this test on iOS 17 and it passes.
=> `Integration Tests`: improved `testCanPurchaseMultipleSubscriptions`

Sources/Logging/Strings/PurchaseStrings.swift, Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Fixes #3020.
This essentially reverts #2890.
As shown in #3020, downgrades are reported with the same transaction identifier as the original transaction. Therefore our approach in #2890 is invalid.
We considered checking whether the `SKPayment` in the `SKPaymentTransaction` matches the one added to the queue as a way to disambiguate these transactions, but it doesn't. So we have no way of telling the difference between queue transactions and purchases.
I've left the original tests as a way to at least document this behavior.
=> `PurchasesOrchestrator`: fixed callback not invoked regression during downgrades

.circleci/config.yml, Sources/Purchasing/Purchases/Purchases.swift
Fixes https://github.com/RevenueCat/purchases-ios/pull/3028#issuecomment-1681533213
This was wrong in #3032 because `Purchases.storeKit2Setting` is only available in `DEBUG` builds, but we didn't catch it because we have no CI for Xcode 15 yet, which this adds as well.
=> `Xcode 15`: fixed release build

Sources/Networking/HTTPClient/HTTPClient.swift, Tests/UnitTests/Networking/HTTPClientTests.swift
=> `HTTPClient`: also parse errors with `application/json;charset=utf8`

Sources/Misc/DateAndTime/Clock.swift, Tests/UnitTests/Misc/ClockTests.swift
This is extracted from #3023. That's closed but this is still useful.
=> `Tests`: added tests for `ClockType`

fastlane/Fastfile
The `build_tv_watch_mac` job already builds on Release mode (`Carthage`'s default).
This would have also helped detect the issue fixed by #3034.
I've also changed the API tester jobs to compile on release, though those aren't ran by CI.
=> `visionOS`: changed CI job to Release

RevenueCatUI/View+PresentPaywall.swift, RevenueCatUI/Views/PurchaseButton.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
This makes more sense than assuming we can call the `\.dismiss` environment variable.
=> `Paywalls`: only dismiss `PaywallView` when explicitly presenting it with `.presentPaywallIfNeeded`

RevenueCatUI/Data/TemplateViewConfiguration.swift, RevenueCatUI/Helpers/PreviewHelpers.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/TemplateViewType.swift, RevenueCatUI/View+PresentPaywall.swift, RevenueCatUI/View+PresentPaywallFooter.swift, RevenueCatUI/Views/LoadingPaywallView.swift, RevenueCatUI/Views/PurchaseButton.swift, Tests/RevenueCatUITests/BaseSnapshotTest.swift, Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift, Tests/RevenueCatUITests/PaywallFooterTests.swift, Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift, Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift, Tests/RevenueCatUITests/Templates/PaywallViewDynamicTypeTests.swift, Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift, Tests/RevenueCatUITests/Templates/Template1ViewTests.swift, Tests/RevenueCatUITests/Templates/Template2ViewTests.swift, Tests/RevenueCatUITests/Templates/Template3ViewTests.swift, Tests/RevenueCatUITests/Templates/Template4ViewTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/CustomPaywall.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
This adds `currentlySubscribed` to `TemplateViewConfiguration.Package` so that `PurchaseButton` can access that information.
`PurchaseButton` now gets automatically disabled for products that are already subscribed.
=> `Paywalls`: handle already purchased state

Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
This test had a race condition because it was assuming that the prior transactions had already been posted.
Otherwise the only post receipt that happens is detected as `.queue`.
=> `Integration Tests`: fixed race condition in flaky test

Sources/Identity/CustomerInfo.swift
I needed this to debug a test failure, so it can be useful.
=> `CustomerInfo`: add `VerificationResult` to `description`

RevenueCatUI/Data/PaywallTemplate.swift
It's not available in the dashboard so we don't want the first SDK releases to support it yet.
I was going to remove the `enum` `case` but that required commenting out a lot of extra code.
This is a much simpler one-line change.
=> `Paywalls`: temporarily disable `PaywallTemplate.template4`

Sources/Misc/Concurrency/OperationDispatcher.swift, Sources/Paywalls/PaywallCacheWarming.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/TestingApps/SimpleApp/SimpleApp/Products.storekit, Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
This prevents us from warming up the cache twice on app launch (because of the explicit call in `Purchases.init` + `applicationWillEnterForeground`).
I turned `PaywallCacheWarming` into an `actor` to simplify thread-safety of the internal state.
=> `Paywalls`: avoid warming up cache multiple times

.circleci/config.yml, .gitmodules, Package.swift, Tests/RevenueCatUITests/Templates/__Snapshots__
See https://github.com/RevenueCat/purchases-ios-snapshots
=> `Paywalls`: reference test snapshots from submodule

RevenueCat.xcodeproj/project.pbxproj, Sources/FoundationExtensions/ProcessInfo+Extensions.swift, Sources/LocalReceiptParsing/Helpers/LoggerType.swift
`OSLogType.debug` logs are purged and not saved:
> The system only captures debug-level messages in memory when you enable debug logging through a configuration change, and purges them in accordance with the configuration’s persistence setting.
I haven't been able to find a way to override this behavior. This means than when reading the logs on CI or when downloading the `xcresult` archive, we can't see these, making it really hard to debug failures.
See also #3048.
=> `Integration Tests`: workaround to not lose debug logs

Sources/FoundationExtensions/UIApplication+RCExtensions.swift, Sources/Paywalls/PaywallColor.swift
Fixes this warning:
```
PaywallColor.swift:168:6: Initializer cannot be more available than enclosing scope
PaywallColor.swift:168:6: Enclosing scope requires availability of Mac Catalyst 13.1 or newer
```
=> `Catalyst`: fixed a couple of Catalyst build warnings

fastlane/Fastfile
`xcodebuild -list` loads all SPM dependencies, which includes our own repo (necessary to test `RevenueCat_CustomEntitlementComputation`):
```
Resolve Package Graph
Resolve Package Graph
Resolved source packages:
CwlPreconditionTesting: https://github.com/mattgallagher/CwlPreconditionTesting.git @ 2.1.2
swift-snapshot-testing: https://github.com/pointfreeco/swift-snapshot-testing @ 1.11.1
CwlCatchException: https://github.com/mattgallagher/CwlCatchException.git @ 2.1.2
Nimble: https://github.com/quick/nimble @ 10.0.0
OHHTTPStubs: https://github.com/AliSoftware/OHHTTPStubs.git @ 9.1.0
RevenueCat: https://github.com/RevenueCat/purchases-ios @ main
```
`Carthage` has as [hardcoded timeout of 60 seconds](https://github.com/Carthage/Carthage/blob/0.39.0/Source/CarthageKit/XCDBLDExtensions.swift# …
=> `CI`: add workaround for `Carthage` timing out

Sources/Identity/CustomerInfoManager.swift, Sources/Purchasing/Purchases/Purchases.swift, Tests/UnitTests/Identity/CustomerInfoManagerTests.swift, Tests/UnitTests/Mocks/MockCustomerInfoManager.swift, Tests/UnitTests/Mocks/MockPurchasesDelegate.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift, Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
These caches are important, especially for `RevenueCatUI`.
Without this fix, launching the app was doing this:
- Pre-warming cache
- Pre-warming cache a second time (to be fixed by a separate PR)
- Clearing cache
Which meant that the cache wasn't really warm when launching paywalls.
To fix that, this only clears the cache after receiving an actual change.
I've also removed `CustomerInfoManager.sendCachedCustomerInfoIfAvailable` because it wasn't used.
=> `Purchases`: don't clear intro eligibility / purchased products cache on first launch

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift, Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift, Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Avoids an extra request to the /offers endpoint in the common case where receipt has no trasactions.
=> `PurchasesOrchestrator`: return early if receipt has no transactions when checking for promo offers

RevenueCatUI/Data/Constants.swift, RevenueCatUI/Data/PaywallTemplate.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/PaywallView.swift, RevenueCatUI/Templates/Template2View.swift, RevenueCatUI/Templates/Template3View.swift, RevenueCatUI/Templates/Template4View.swift, RevenueCatUI/Templates/Template5View.swift, RevenueCatUI/Templates/TemplateViewType.swift, RevenueCatUI/Views/IconView.swift, RevenueCatUI/Views/PackageButtonStyle.swift, Tests/RevenueCatUITests/Templates/Template5ViewTests.swift, Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/CustomPaywall.swift, Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
=> `Paywalls`: template 5

.circleci/config.yml, Package@swift-5.6.swift, RevenueCat.xcworkspace/xcshareddata/swiftpm/Package.resolved
This updates:
- `swift-snapshot-testing`
- `purchases-ios`
Updating our own commit fixes this issue that could happen if you didn't "update to latest package versions" locally:
=> `SPM`: update `Package.resolved`

.circleci/config.yml, Tests/InstallationTests/CarthageInstallation/fastlane/Fastfile, fastlane/Fastfile, fastlane/README.md
Follow up to #3119. This job also needed the workaround to make sure `Carthage` doesn't time out.
Also moved the implementation to Fastlane.
=> `carthage_installation_tests`: optimize SPM package loading

Sources/Misc/PriceFormatterProvider.swift, Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift, Tests/StoreKitUnitTests/StoreProductTests.swift
This allows overriding the `Locale` to be used for this test product, which is used to configure the price formatter.
This will be used by #3133.
=> `TestStoreProduct`: new `locale` parameter

RevenueCatUI/Data/Localization.swift, RevenueCatUI/Data/TestData.swift, RevenueCatUI/Helpers/Package+VariableDataProvider.swift, Sources/Misc/PriceFormatterProvider.swift, Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift, Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift, Tests/RevenueCatUITests/Data/PackageVariablesTests.swift, Tests/RevenueCatUITests/LocalizationTests.swift, Tests/StoreKitUnitTests/StoreProductTests.swift
This was incorrect for `PackageType.threeMonth` and `PackageType.sixMonth`.
=> `Paywalls`: `{{ price_per_period }}` now takes `SubscriptionPeriod.value` into account

Sources/Support/DebugUI/DebugViewModel.swift
Fixes https://github.com/RevenueCat/purchases-capacitor/issues/100 and https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/14093/workflows/b3f8d001-6f39-40db-a5c5-00fc37d0211e/jobs/105838
```
Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	               0x0 ???
1   libswiftCore.dylib            	       0x18f9b8cf8 swift_getSingletonMetadata + 956
2   RevenueCat                    	       0x107f42de4 type metadata accessor for DebugViewModel + 64
3   libobjc.A.dylib               	       0x18017d938 realizeClassMaybeSwiftMaybeRelock(objc_class*, mutex_tt<false>&, bool) + 116
4   libobjc.A.dylib               	       0x180184eb0 realizeAllClasses() + 168
5   libobjc.A.dylib               	       0x180187b3c objc_copyClassList + 36 …
```
=> `DebugViewModel`: fixed runtime crash on iOS < 16

RevenueCatUI/PaywallView.swift, RevenueCatUI/Views/DebugErrorView.swift
Thanks @aboedo for catching this.
I've also improved the API to avoid using `AnyView`.
=> `Paywalls`: fixed error view being displayed on release builds

RevenueCatUI/Data/Strings.swift, Sources/Paywalls/PaywallData.swift, Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json, Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json
Thanks to @vegaro for pointing this out. It's not required, but it helps to ensure that these properties don't end up with empty strings.
=> `PaywallData`: added `@NonEmptyString` to `subtitle` and `offerName`

Sources/FoundationExtensions/Decoder+Extensions.swift, Sources/Logging/Strings/CodableStrings.swift
This adds the type to the errors.
```
2023-09-06 15:58:05.394583-0700 xctest[55784:3435527] [codable] DEBUG: ℹ️ Encountered error when decoding JSON: not an event
```
```
2023-09-06 16:03:29.606223-0700 xctest[57222:3447821] [codable] DEBUG: ℹ️ Encountered error when decoding JSON for 'PaywallStoredEvent': this is not an event
```
=> `Codable`: improved decoding errors
