RevenueCatUI/Helpers/PaywallData+Default.swift
Sources/Paywalls/PaywallColor.swift
Sources/Paywalls/PaywallData.swift
Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
Tests/UnitTests/Paywalls/PaywallColorTests.swift
Tests/UnitTests/Paywalls/PaywallDataTests.swift

See #2847.
Thanks to @vegaro for pointing this out.
Also removed all checks for Xcode 13 (see #3161 and #3147).

`Paywalls`: support fuzzy-Locale search in `iOS 15`

---

Sources/Logging/Strings/NetworkStrings.swift
Sources/Logging/Strings/OfflineEntitlementsStrings.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift

We get a lot of flaky failures on `OfflineStoreKitIntegrationTests` (example: https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/14843/workflows/a3cffa7c-da25-4811-931d-fc241befee0f/jobs/118214/tests).
I managed to reproduce locally running some of these 100+ times on a loop until they failed.
I traced the issue to this sequence:
- SK2 purchase
- `StoreKit.Transaction.unfinished` is empty
This is likely due to a race condition. In practice, when computing offline `CustomerInfo`, we never check it right away, since we need to wait for the server to return a 500.
I filed a Radar for this: `FB13133387`.
To make tests more realistic, I introduced a delay in `HTTPClient` returning fake 5xx errors. I haven't been able to reproduce this issue again, so this should make …

`Integration Tests`: improve flaky tests

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Paywalls/Events/PaywallEvent.swift
Tests/APITesters/.swiftlint.yml
Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift

This will represent events created by `RevenueCatUI`.

`Paywalls`: add `PaywallEvent` model

---

Sources/Purchasing/CachingProductsManager.swift
Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift

`Xcode 13`: removed last `Swift 5.7`  checks

---

Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift

Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/14917/workflows/4f22199c-2229-45da-8758-9587559d02be/jobs/119481/tests
This test was failing with this error:
> failed - Message 'Finishing transaction' should not have been logged
I looked through the logs, and noticed that transaction had been finished prior to the test even starting (before `.serverDown()` was called), likely due to a leftover transaction from an earlier test (this can still happen with `SKTestSession` despite our best efforts. Supposedly fully fixed in iOS 17).
This removes that possibility by clearing the log history at the beginning of the test.

`Integration Tests`: fix flaky test failure due to leftover transaction

---

Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift

See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/14903/workflows/a607f078-553a-44c0-8873-16abc12d3e3a/jobs/119243
This test (`testCallToGetCustomerInfoWithPendingTransactionsPostsReceiptOnlyOnce`) has a race condition. It currently does:
- `purchaseMonthlyProduct`
- `forceRenewalOfSubscription`
However, with a slow CPU, it's possible that StoreKit will renew automatically, leading to more unfinished transactions.
This modifies the test to be a bit more lenient, while still complying with the spirit of the test: `testCallToGetCustomerInfoWithPendingTransactionsPostsReceiptOnlyOnce`.

`Integration Tests`: another flaky failure

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Identity/CustomerInfoManager.swift
Sources/Misc/Concurrency/OperationDispatcher.swift
Sources/Networking/Backend.swift
Sources/Networking/BackendConfiguration.swift
Sources/Networking/CustomerAPI.swift
Sources/Networking/InternalAPI.swift
Sources/Networking/OfferingsAPI.swift
Sources/Networking/OfflineEntitlementsAPI.swift
Sources/OfflineEntitlements/OfflineEntitlementsManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Identity/CustomerInfoManagerPostReceiptTests.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Misc/OperationDispatcherTests.swift
Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Mocks/MockOfflineEntitlementsAPI.swift
Tests/UnitTests/Mocks/MockOperationDispatcher.swift
Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
Tests/UnitTests/Networking/Backend/BackendGetOfferingsTests.swift
Tests/UnitTests/Networking/Backend/BackendOfflineEntitlementsTests.swift
Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift

See also https://github.com/RevenueCat/purchases-android/pull/1017.
This will be used for dispatching paywall events.

`OperationDispatcher`: add support for "long" delays

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcworkspace/xcshareddata/swiftpm/Package.resolved
fastlane/Fastfile

The project no longer depends on `purchases-ios` through SPM.
This was needed for 2 reasons:
- `v3LoadShedderIntegration`
- `BackendCustomEntitlementsIntegrationTests`
Both of these depend on `RevenueCat_CustomEntitlementComputation`, which is only an SPM library.
This solution allows us to build it but without having to clone the repo separately through a dependency, and instead embedding a reference to the _local_ Package.
`v3LoadShedderIntegration` depended on the 3.x release, so I've simply removed it from the workspace. It can still be modified and ran directly by opening the project.
This solves at least 2 major current annoyances:
- Compiling `BackendIntegrationTests` lead to compile errors because the local changes weren't seen when building …

`Xcode`: removed `purchases-ios` SPM reference

---

RevenueCatUI/Views/FooterView.swift

`hidden` is not the right approach here because it's still part of the layout. Obvious in retrospect, but this was one of the first few elements done for paywalls and never went back to it.

`Paywalls`: fixed `FooterView` horizontal centering

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Networking/HTTPClient/HTTPRequest.swift
Sources/Networking/HTTPClient/HTTPRequestPath.swift
Sources/Networking/InternalAPI.swift
Sources/Paywalls/Events/Networking/PaywallEventsRequest.swift
Sources/Paywalls/Events/Networking/PaywallHTTPRequestPath.swift
Sources/Paywalls/Events/Networking/PostPaywallEventsOperation.swift
Tests/UnitTests/Mocks/MockInternalAPI.swift
Tests/UnitTests/Paywalls/Events/PaywallEventsBackendTests.swift
Tests/UnitTests/Paywalls/Events/PaywallEventsRequestTests.swift
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS15-testPostPaywallEventsWithMultipleEvents.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS15-testPostPaywallEventsWithOneEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS16-testPostPaywallEventsWithMultipleEvents.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS16-testPostPaywallEventsWithOneEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testCancelEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testCloseEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testViewEvent.1.json

This adds the operation + `PaywallEventsRequest` and associated tests. Also added method to `InternalAPI` for posting events.

`Paywalls`: implemented `PostPaywallEventsOperation`

---

RevenueCatUI/Templates/Template2View.swift

`Paywalls`: fixed template 2 + `.condensedFooter` + iPad

---

RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
RevenueCatUI/Templates/TemplateViewType.swift

Reported by @joshdholtz. If the developer doesn't configure dark colors, we don't want things like materials from inheriting the automatic dark mode configuration.

`Paywalls`: don't apply dark appearance with no dark mode colors

---

RevenueCatUI/Helpers/TrialOrIntroEligibilityChecker.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/View+PresentPaywall.swift

This was breaking event notifications as well as `OnPurchaseCompletedModifier`, because there were multiple `PurchaseHandler` instances created.
The solution is to make `PaywallView` store these as `@StateObject`. In order to do that, the type can't be optional, so I instead encoded the "is configured" information inside.

`Paywalls`: fixed data flow resulting in multiple `PurchaseHandler` instances

---

.swiftpm/xcode/xcshareddata/xcschemes/RevenueCatUI.xcscheme
Tests/RevenueCatUITests/BaseSnapshotTest.swift
Tests/RevenueCatUITests/TestPlans/RevenueCatUI-UnitTests.xctestplan

Snapshot tests are inherently slow. Sometimes it's useful to be able to run the rest of unit tests alone, and this test plan makes that easier.

`Paywalls`: test plan for running non-snapshot tests

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift

Follow up to #3187.
Thanks to @charliemchapman for reporting.
`IntroEligibilityViewModel` was being recreated, which meant that we were losing the internal state on redraws.
I've also simplified the initialization of `TrialOrIntroEligibilityChecker` and `PurchaseHandler` to avoid duplicated calls to `.default()`.

`Paywalls`: fixed `IntroEligibilityViewModel` data lifetime

---

Sources/Paywalls/PaywallData.swift
Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json
Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json
Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json
Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json
Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json
Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json
Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-empty_images.json
Tests/UnitTests/Paywalls/PaywallDataTests.swift

Ideally the backend would never send `""` for images, but better to be defensive.

`Paywalls`: convert empty images into `nil`

---

RevenueCatUI/Data/Strings.swift
RevenueCatUI/Data/TestData.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/Views/LoadingPaywallView.swift
Tests/RevenueCatUITests/PaywallViewEventsTests.swift

Last part, follow up to #3160.
This now makes `PaywallView` track events through the `RevenueCat` SDK.

`Paywalls`: send events to `Purchases`

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Diagnostics/FileHandler.swift
Sources/Logging/Strings/PaywallsStrings.swift
Sources/Networking/InternalAPI.swift
Sources/Paywalls/Events/Networking/PaywallEventsRequest.swift
Sources/Paywalls/Events/PaywallEventStore.swift
Sources/Paywalls/Events/PaywallEventsManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Mocks/MockPaywallEventsManager.swift
Tests/UnitTests/Paywalls/Events/PaywallEventStoreTests.swift
Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS15-testPostPaywallEventsWithMultipleEvents.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS15-testPostPaywallEventsWithOneEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS16-testPostPaywallEventsWithMultipleEvents.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsBackendTests/iOS16-testPostPaywallEventsWithOneEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testCancelEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testCloseEvent.1.json
Tests/UnitTests/Paywalls/Events/__Snapshots__/PaywallEventsRequestTests/testViewEvent.1.json

- Added `PurchasesOrchestrator` tests for paywall data sent through post receipt
- Fixed and tested state issue with cached paywall data and failed purchases
- Added `Integration Tests` for tracking and flushing events
- Configured `Integration Tests` with a custom documents directory to ensure it's empty on every test invocation
- Changed deployment target on `Integration Tests` to iOS 16 to simplify code
- Setting `Purchases.logLevel` before configuring purchases on `Integration Tests`
- Added assertion to ensure `FileHandler` never runs on the main thread

`Paywalls`: events unit and integration tests

---

RevenueCatUI/Data/PaywallTemplate.swift
RevenueCatUI/Templates/Template4View.swift

I broke this on #3183.
We need to reset the height calculation when the inputs change, but setting it to 0 was making it layout with a 0 height instead of unlimited height to measure it.
This also now enables template 4 since it's ready!

`Paywalls`: fixed broken layout on template 4

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Paywalls/Events/PaywallEventsManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
Tests/UnitTests/Mocks/MockOperationDispatcher.swift
Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
Tests/UnitTests/Paywalls/Events/PurchasesPaywallEventsTests.swift

This uses the new `Delay.long` (#3168) to flush events on app foreground.
Also added more tests.

`Paywalls`: automatically flush events

---

Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift

We found that there was another runtime crash in Capacitor in iOS < 15 similar to https://github.com/RevenueCat/purchases-ios/pull/3139. This applies the same fix to this new crash.

Fix runtime crash in SK2TransactionListener in iOS < 15

---

Sources/Paywalls/PaywallCacheWarming.swift
Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json
Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift

If a developer ends up with a lot of different paywalls (like our test app), potentially _a lot_ of images will get downloaded on app launch. Example:
```
[https://assets.pawwalls.com/954459_1691526599.png, https://assets.pawwalls.com/954459_1693514956.png, https://assets.pawwalls.com/954459_1691434999.jpg, https://assets.pawwalls.com/954459_1692617804.jpeg, https://assets.pawwalls.com/954459_1694552000.jpg, https://assets.pawwalls.com/954459_1690923068.png, https://assets.pawwalls.com/954459_1691438608.jpg, https://assets.pawwalls.com/954459_1692992845.png, https://assets.pawwalls.com/954459_1691445169.jpg, https://assets.pawwalls.com/954459_1692723197.png, https://assets.pawwalls.com/954459_1692821276.png, https://assets.pawwalls.com/954459_1692984654.jpg, …
```

`Paywalls`: only pre-warm images/intro-eligibility for `Offerings.current`

---

RevenueCatUI/Views/PurchaseButton.swift

Fixes #3216.
This likely got broken with #3121 because we stopped using `.buttonStyle`. This implements a manual style when the button is `disabled` (when `PurchaseHandler.actionInProgress` is `true`).
https://github.com/RevenueCat/purchases-ios/assets/685609/0e23bcf1-7e1d-4d57-adf7-61a76b1e997e

`Paywalls`: loading indicator for in-progress purchases

---

Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift

Same as #3167. These can fail when verifying that no transactions are finished because there might be leftover transactions before the test even begins. In order to ignore those, we clear `TestLogHandler` at the beginning. We don't do that for every test because in some test we want to look at what was logged during SDK initialization.

`Integration Tests`: fixed more flaky failures

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift

I noticed we had no integration tests for this.

`Integration Tests`: add coverage for `Purchases.customerInfoStream`

---

RevenueCat.xcodeproj/project.pbxproj
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/Helpers/BaseStoreKitIntegrationTests+Verification.swift
Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift

Good news: offline entitlements are amazing, and our SDK is very resilient to the backend being down.
Bad news: this is kind of a false positive, this behavior is already verified by `OfflineStoreKitIntegrationTests`.
I refactored `BaseStoreKitIntegrationTests` because it had grown a lot. I put this verification in the `purchase` methods so all tests benefit from this.
So that `OfflineStoreKitIntegrationTests` don't fail, I added a parameter to ignore that verification in those tests.

`Integration Tests`: prevent false positives when purchasing returns 5xx

---

.circleci/config.yml

Now that `CircleCI` updated the `xcode-15` image this wasn't found. Available simulators now:
```
[19:40:56]: ▸ { platform:iOS Simulator, id:6105C8BF-2099-4DEF-BAF2-732BFECFD90B, OS:16.4, name:iPad (10th generation) }
[19:40:56]: ▸ { platform:iOS Simulator, id:6684C364-D76B-461D-AB76-07BA7D5CBFB3, OS:17.0, name:iPad (10th generation) }
[19:40:56]: ▸ { platform:iOS Simulator, id:A0AADD88-4AC3-453F-AAC0-AC424BD543CF, OS:16.4, name:iPad Air (5th generation) }
[19:40:56]: ▸ { platform:iOS Simulator, id:72B511A8-E129-4D2B-9A73-B8BE5F07FE8F, OS:17.0, name:iPad Air (5th generation) }
[19:40:56]: ▸ { platform:iOS Simulator, id:A5D8B4DD-7D7C-4350-B237-2C10DA03D312, OS:16.4, name:iPad Pro (11-inch) (4th generation) }
[19:40:56]: ▸ { platform:iOS Simulator, id:D0FF23E7-18A4-4DAC-AFDF-AB6C2CC7A25E, …
```

`CI`: updated iOS 17 simulator

---

Sources/Logging/Strings/ConfigureStrings.swift
Sources/Misc/Deprecations.swift
Sources/Purchasing/Configuration.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/UnitTests/Purchasing/ConfigurationTests.swift

See also https://github.com/RevenueCat/revenuecat-docs/pull/299.
Since #3032 developers using observer mode need to configure the SDK with the correct StoreKit 2 setting.

`Configuration`: log warning if attempting to use observer mode with StoreKit 2

---

RevenueCatUI/Templates/Template1View.swift

Noticed this when referencing the method for Android.

`Paywalls`: removed unused property

---

RevenueCatUI/Data/TestData.swift
RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/Views/FooterView.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift

We can improve the logic here, but this is a simple improvement for the obvious case where nothing was actually restored.

`Paywalls`: don't display "Purchases restored successfully" if nothings was restored

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/SimpleApp.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
Tests/TestingApps/SimpleApp/SimpleApp.xcworkspace/contents.xcworkspacedata

When launching the app now _without_ a configured API key, it goes into a simpler mode where it only shows the "offline" test paywalls.

`Paywalls`: changed `PaywallsTester` to allow not configuring API key

---

Sources/PrivacyInfo.xcprivacy

Fixes https://community.revenuecat.com/sdks-51/xcode-15-s-privacyinfo-xcprivacy-privacy-manifest-what-if-developer-uses-anonymous-app-ids-only-3310?postid=10800#post10800
This new value matches [our documentation](https://community.revenuecat.com/sdks-51/xcode-15-s-privacyinfo-xcprivacy-privacy-manifest-what-if-developer-uses-anonymous-app-ids-only-3310?postid=10800#post10800:~:text=https%3A//www.revenuecat.com/docs/apple%2Dapp%2Dprivacy%232%2Dpurchase%2Dhistory%2Dlinked%2Dto%2Didentity).
> If you are using RevenueCat’s anonymous app user ID’s, and do not have a way to identify individual users, you can select ‘No’.
By default, the SDK uses anonymous user IDs, so this being `false` is a better default.

`PrivacyInfo.xcprivacy`: changed `NSPrivacyCollectedDataTypePurchaseHistory` to `false`

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift

The navigation is slightly awkward because we're rendering a list on the left side, but then we display a sheet, so the right side pane is never filled. This just updates it so that it always looks like a full screen list instead. The changes don't apply to iPhone, just iPad landscape and macOS
| :-: | :-: |
| <img width="1031" alt="Screenshot 2023-09-27 at 5 53 31 PM" src="https://github.com/RevenueCat/purchases-ios/assets/3922667/c9d3da09-d716-40ca-9497-c00d99a0e672"> | <img width="730" alt="Screenshot 2023-09-27 at 6 06 55 PM" src="https://github.com/RevenueCat/purchases-ios/assets/3922667/cc5d2477-bab5-4c92-bccc-fdb592f27204"> |

PaywallsTester: improve navigation on macOS and iPadOS

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift

Refactored so that in mac catalyst, instead of presenting as a sheet, we present as part of navigation, so that resizing the view also resizes the paywall. 
This is useful for quick testing of different sizes on macOS.
iOS remains unchanged
https://github.com/RevenueCat/purchases-ios/assets/3922667/8de24c5d-80ef-4ed6-8813-eca72af00008

PaywallsTester: allow resizing on macOS

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/PaywallViewMode+Extensions.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift

Adds a Haptic Touch gesture to allow you to press and hold the name of a template in All Templates to select which specific mode to open it in. 
https://github.com/RevenueCat/purchases-ios/assets/3922667/4713daef-c6d4-427b-9551-dca31129785b

PaywallsTester: allow easy testing of paywall modes for All Offerings tab

---

Sources/Support/DebugUI/DebugContentViews.swift

`debugRevenueCatOverlay`: added list of active entitlements

---

RevenueCatUI/Views/IntroEligibilityStateView.swift

This was useful when refactoring this view. I also added the same in https://github.com/RevenueCat/purchases-android/pull/1286.

`Paywalls`: added previews for `IntroEligibilityStateView`

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift

Adds a new tab that calls `presentPaywallIfNeeded`

PaywallsTester: add a new tab that calls presentPaywallIfNeeded

---

Sources/Purchasing/Purchases/Attribution.swift
Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
Sources/SubscriberAttributes/SubscriberAttributesManager.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCAttributionAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/AttributionAPI.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

OneSignal is migrating to a new User Centric API (v11.0). Adding a new reserved attribute to provide the new OneSignal User Id.
* Added $onesignalUserId reserved attribute with setter methods

Add `Attribution.setOnesignalUserID`

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Misc/Concurrency/Purchases+nonasync.swift
Sources/Purchasing/Configuration.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Sources/Support/StoreMessageType.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/StoreKitUnitTests/StoreMessageTypeTests.swift
Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
Tests/UnitTests/Mocks/MockPurchases.swift

This removes the extra APIs that were added to support showing store messages in ObjC. We will add these in PHC. If there is a demand for it we can always add it later.

Remove ObjC showStoreMessages API

---

RevenueCatUI/Views/LoadingPaywallView.swift
RevenueCatUI/Views/PurchaseButton.swift

This is a better fix than #3235. Instead of marking the view as disabled, which is also used by `PurchaseHandler` to signal that a purchase is in progress, we simply make that view not accept touches.
Which has the actual effect that we want (not being interactive), without messing with how it's displayed).

`Paywalls`: simplified `LoadingPaywallView`

---

RevenueCatUI/Modifiers/ViewExtensions.swift

Fixes https://community.revenuecat.com/sdks-51/issue-with-app-build-after-adding-sdk-package-in-xcode-15-0-3404
Note that `RevenueCatUI` isn't actually compatible with `macOS` yet (see #3128), but it should at least build.

`Paywalls`: fixed `macOS` compilation

---

RevenueCatUI/Data/TemplateViewConfiguration+Images.swift
RevenueCatUI/Views/LoadingPaywallView.swift
RevenueCatUI/Views/PurchaseButton.swift
Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift

https://github.com/RevenueCat/purchases-ios/assets/685609/c8c5b2e5-f004-4fff-93dd-221d61bbad6a

`Paywalls`: added shimmer effect to `LoadingPaywallView`

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/SimpleApp.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh

This introduces buttons that allow you to reconfigure the app with a different API key. 
This will be useful when doing demos for customers, since the Testing app's Offerings are pretty cluttered at this point.

PaywallsTester: allow for configuration for demos

---

Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Tests/StoreKitUnitTests/StoreProductTests.swift

This only works in iOS 16+ (because it needs `StoreKit.Product.priceFormatStyle`), but it's a good improvement which ensures consistent formatting of prices in paywalls, where sometimes `StoreProduct.localizedPrice` would have a different format compared to formatting `pricePerMonth` using `StoreProduct.priceFormatter`.

`SK2StoreProduct.priceFormatter`: use locale from `StoreKit.Product`

---

Sources/Attribution/AttributionFetcher.swift
Sources/Attribution/AttributionPoster.swift
Sources/Purchasing/Purchases/Attribution.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/UnitTests/Attribution/AttributionFetcherTests.swift
Tests/UnitTests/Attribution/AttributionPosterTests.swift
Tests/UnitTests/Mocks/MockAttributionFetcher.swift

Fixes #3280.
Turns out that `AAAttribution.attributionToken()` is asynchronous, and Apple will happily allow you to make a blocking network request on the main thread. This avoids that.
I've refactored `AttributionFetcher.adServicesToken` to be `async` and added `RCTestAssertNotMainThread` to ensure this doesn't break again.
The rest of the changes were necessary to accommodate the new `async` API.

`AAAttribution.attributionToken`: avoid using on main thread

---

Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift

`Tasks` aren't guaranteed to start in order.

`Tests`: improved flaky test

---

Sources/Purchasing/EntitlementInfo.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift

Exposes `productPlanIdentifier` in `EntitlementInfo`. This will be helpful in the hybrids so they have actual values for users purchasing Google play products and using iOS apps.

Expose `productPlanIdentifier` in `EntitlementInfo`

---

Sources/Purchasing/OfferingsManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Mocks/MockOfferingsManager.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift

This allows fixing #3283.
Fixes #2391.

`Purchases`: new `cachedCustomerInfo` and `cachedOfferings`

---

Sources/Paywalls/Events/PaywallEventStore.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/UnitTests/Paywalls/Events/PaywallEventStoreTests.swift

See https://nemecek.be/blog/57/making-files-from-your-app-available-in-the-ios-files-app#writing-files-into-the-application-support-directory
Unfortunately the choice of `URL.documentsDirectory` meant that any app wanting to make its documents accessible via the Files app,
would have exposed these events.

`PaywallEventStore`: changed container to use `URL.applicationSupportDirectory`

---

RevenueCatUI/PaywallView.swift

Depends on #3274.
https://github.com/RevenueCat/purchases-ios/assets/685609/d4a4e78b-69ca-4288-97a5-3168867758ef
https://github.com/RevenueCat/purchases-ios/assets/685609/1c23c50b-e802-4b25-b9a3-30b8ea27b84e

`Paywalls`: avoid flickering when displaying paywalls with available cache

---

RevenueCatUI/Helpers/PreviewHelpers.swift
RevenueCatUI/Templates/TemplateViewType.swift

`PreviewHelpers` was duplicating the call to `background()` and was missing the color scheme override.
In an upcoming PR I needed to add a third change to the view that would have been missing on previews, so this refactor helps.

`Paywalls`: extracted common `TemplateViewType` method for previews

---

.circleci/config.yml

Extracted this from #3262 since that's blocked by CocoaPods.

`CI`: change `visionOS` build to environment with `xrOS` SDK

---

RevenueCatUI/Data/IntroEligibility/IntroEligibilityViewModel.swift
RevenueCatUI/Modifiers/ConsistentPackageContentView.swift
RevenueCatUI/Templates/Template1View.swift
RevenueCatUI/Templates/Template2View.swift
RevenueCatUI/Templates/Template3View.swift
RevenueCatUI/Templates/Template4View.swift
RevenueCatUI/Templates/Template5View.swift
RevenueCatUI/Views/PurchaseButton.swift

This abstracts away the logic to ensure layouts are consistent when selecting different packages in multi-package templates, in a way that the content doesn't move around.

`Paywalls`: created `ConsistentPackageContentView` to improve package change transitions

---

Sources/Logging/Strings/PurchaseStrings.swift

See https://github.com/RevenueCat/purchases-ios/issues/2415#issuecomment-1579324706
This should make it more obvious for anyone running into this issue.

`StoreKit 1`: improved debug log for `finishTransactions` invoked outside the SDK

---

.circleci/config.yml

They haven't announced this yet, but iOS 17.0.0 isn't found anymore.
See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/15764/workflows/45cfe00a-4721-4bc9-8b20-1e0acd4969d2/jobs/134809/parallel-runs/0/steps/0-112

`CircleCI`: update simulators for Xcode 15.0.1

---

Sources/Paywalls/Events/PaywallEventStore.swift

Fixes #3316. Follow up to #3289.
That previous fix was only removing the store itself, but not the `revenuecat` folder.
Running an app with 4.27.2 produces this:
```bash
$ tree -L 3 ~/Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../
~/Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../
├── Documents
│   └── revenuecat
│       └── paywall_event_store
```
After this fix, the Documents directory is empty.
```bash
tree -L 4 ~/Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../
/Users/ignacio/Library/Developer/CoreSimulator/Devices/.../data/Containers/Data/Application/.../
├── Documents
├── Library
│   ├── Application Support
│   │   └── revenuecat
│   │       └── paywall_event_store
```
This is still …

`PaywallEventStore`: also remove legacy `revenuecat` documents directory

---

Tests/RevenueCatUITests/BaseSnapshotTest.swift
Tests/RevenueCatUITests/PaywallViewEventsTests.swift
Tests/RevenueCatUITests/PresentIfNeededTests.swift

These were failing in some of the earlier Xcode 15 betas, but they all seem to be passing now. `PresentIfNeededTests` are still not working though. But I just manually verified that these modifiers do work correctly on iOS 17 on an app.

`Paywalls`: enable all iOS 17 tests

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PurchaseRestoreCompleted.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift

The current API only provided a `CustomerInfo`.
Note that this does not include `userCanceled`. We can expose separately with another `.onPurchaseCancelled` modifier in the future.

`Paywalls`: new `.onPurchaseCompleted` overload with `StoreTransaction`

---

.circleci/config.yml

See https://circleci.com/product/features/resource-classes/#macos
See https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/
Hopefully this makes the iOS 17 failures less common.

`CircleCI`: change iOS 17 job to use M1 Large resource

---

Sources/Logging/Strings/OfflineEntitlementsStrings.swift
Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/Helpers/TestMessage.swift

This modifies `BaseStoreKitIntegrationTests.printReceipt` to also log `StoreKit 2` transactions which can be used to debug failures of `OfflineStoreKitIntegrationTests`.
`PurchasedProductsFetcher` also logs how many `currentEntitlements` it found since failures are coming from there.

`Integration Tests`: new logs for troubleshooting flaky tests

---

Sources/Logging/Strings/OfflineEntitlementsStrings.swift
Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/Helpers/TestMessage.swift
Tests/TestPlans/CI-BackendIntegration.xctestplan
fastlane/Fastfile

See https://github.com/RevenueCat/purchases-ios/blob/4.28.1/Tests/TestPlans/CI-BackendIntegration.xctestplan#L28
This was changed to 5 repetitions in #3218, but the `Fastfile` was overriding that. Also #1925 didn't have any effect because of this, and that actually makes tests take significantly longer, so this reverts that.

`Integration Tests`: use repetition count from test plan

---

fastlane/Fastfile

- Remove further dependencies from the no-longer-maintained `Carthage`
- Avoid building multiple architectures (`ONLY_ACTIVE_ARCH`)
- Disable unnecessary code-signing
The main benefit of this is that it will drastically speed up the `build-tv-watch-and-macos` CI job.

`CI`: replace Carthage build jobs with `xcodebuild`

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift

Having the `.sheet` deep inside a `List` + `Section` + `if` was making `SwiftUI` re-evaluate it over and over.
This cleans up `PaywallPresenter` and moves it to the top level of the view to avoid that.

`Paywall Tester`: fixed paywall presentation

---

Sources/Purchasing/ProductsManager.swift
Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift
Tests/UnitTests/Purchasing/ProductsFetcherSK1Tests.swift

`ProductFetcherSK1` had 2 public methods for fetching products: `products(withIdentifiers:completion:)` and `sk1Products(withIdentifiers:completion:)`.
Only one of them was using `TimingUtil` to log slow requests, and that one happened to not be used by `ProductsManager`, which means that we weren't getting these logs.
This is evident in https://github.com/RevenueCat/react-native-purchases/issues/755. With this change, we'll now be able to see how long the product request took.

`ProductFetcherSK1`: enable `TimingUtil` log

---

Sources/FoundationExtensions/OperationQueue+Extensions.swift
Sources/Logging/Logger.swift
Sources/Logging/Strings/NetworkStrings.swift
Sources/Networking/HTTPClient/ETagManager.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Networking/HTTPClient/HTTPResponse.swift
Sources/Networking/HTTPClient/HTTPStatusCode.swift
Sources/Networking/Operations/Handling/CustomerInfoResponseHandler.swift
Sources/Networking/Operations/LogInOperation.swift
Sources/Networking/Operations/PostOfferForSigningOperation.swift
Sources/Security/Signing+ResponseVerification.swift
Tests/BackendIntegrationTests/OtherIntegrationTests.swift
Tests/UnitTests/Mocks/MockHTTPClient.swift
Tests/UnitTests/Networking/ETagManagerTests.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Networking/HTTPResponseTests.swift
Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift
Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Tests/UnitTests/Security/SigningTests.swift

See https://github.com/RevenueCat/khepri/pull/6798.
This can help debug issues as it helps us cross-reference requests on our end.
- Logging `X-Request-ID` and `X-Amzn-Trace-ID` headers if present (only in verbose mode)
- Logging these even for failed requests
- Also logging `request_handled_by_load_shedder` for failed requests
- To accomplish that. `HTTPURLResponse` now conforms to our `HTTPResponseType`, this allows us to extract headers in an uniform way
```
[network] DEBUG: ℹ️ API request completed: GET '/v1/subscribers/$RCAnonymousID%3Ad9dc4f3b33054cf28c0f2ec9da0f48d5' (304)
Request-ID: 'be534c50-5231-403b-be2f-7c077861751d'; Amzn-Trace-ID: 'Root=1-6532c6ca-7ef80f961ec9c4145484df13'
```

`HTTPClient`: verbose logs for request IDs

---

Sources/Paywalls/PaywallColor.swift

Fixes #3344.
This wasn't meant to be `public` as it's only used within the `RevenueCat` framework and can lead to conflicts.

`PaywallColor`: change visibility of `Color.init(light:dark:)` to `private`

---

Sources/Error Handling/ErrorUtils.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Networking/HTTPClient/NetworkError.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Networking/NetworkErrorTests.swift
Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
Tests/UnitTests/Purchasing/ErrorUtilsTests.swift

Fixes #3343.
`SKPaymentTransaction.error` docs say:
> The error property is undefined except when `transactionState` is set to `SKPaymentTransactionState.failed`. Your application can read the error property to determine why the transaction failed. For a list of error constants, see `SKErrorDomain` in StoreKit Constants.
Which is why [`PurchasesOrchestrator` only considered that domain](https://github.com/RevenueCat/purchases-ios/blob/4.28.1/Sources/Purchasing/Purchases/PurchasesOrchestrator.swift#L792).
This expands this handling to consider any other network error, therefore providing more precise errors.
Since offline connection error detection was only in `HTTPClient`, I also moved that out and removed `NetworkError.offlineConnection`, so that we detect this when converting …

`ErrorUtils.purchasesError(withSKError:)`: handle `URLError`s

---

RevenueCatUI/Views/FooterView.swift

This overrides the `accessibilityLabel` to always read the longest text, even if it didn't fit on the screen.
I thought of this while working on [Android A11y](https://github.com/RevenueCat/purchases-android/pull/1392).

`Paywalls`: improve `FooterView` accessibility

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Templates/TemplateViewType.swift

This simplifies the implementation in `PaywallView` and reuses this code so `PreviewableTemplate` can use it too.

`Paywalls`: move size configuration to `TemplateViewType`

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Views/CustomPaywall.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/CustomPaywallContent.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift

This uses `CustomPaywallContent` instead of the `Text` simple paywall:
I also fixed a bug where the context menu no longer worked since #3339, by unifying the state into a single property.

`Paywalls Tester`: improve `.paywallFooter` presentation

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/Views/LoadingPaywallView.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift

The [documentation](https://www.revenuecat.com/docs/displaying-paywalls#close-button) points out that this is only automatic when using `presentPaywallIfNeeded`, but it can also be useful to have `RevenueCatUI` do this automatically.

`Paywalls`: new optional `displayCloseButton` parameter

---

RevenueCatUI/Templates/Template1View.swift
RevenueCatUI/Templates/Template2View.swift
RevenueCatUI/Templates/Template3View.swift
RevenueCatUI/Templates/Template4View.swift
RevenueCatUI/Templates/Template5View.swift
RevenueCatUI/Views/IntroEligibilityStateView.swift
RevenueCatUI/Views/PurchaseButton.swift

This will be used to implement a similar fix to https://github.com/RevenueCat/purchases-android/pull/1416

`Paywalls`: refactored `IntroEligibilityStateView`

---

RevenueCatUI/Templates/Template1View.swift
RevenueCatUI/Templates/Template2View.swift
RevenueCatUI/Templates/Template3View.swift
RevenueCatUI/Templates/Template4View.swift
RevenueCatUI/Templates/Template5View.swift
RevenueCatUI/Views/IntroEligibilityStateView.swift
RevenueCatUI/Views/PurchaseButton.swift

Equivalent to https://github.com/RevenueCat/purchases-android/pull/1416

`Paywalls`: avoid animating `PurchaseButton` labels when text does not change

---

RevenueCatUI/Templates/Template2View.swift

When presenting `PaywallView` inside of a `NavigationView` (which was automatic, and more common with #3359) the icon had too much padding at the top:
e
With this fix (note there is no actual navigation title):

`Paywalls`: fix template 2 top padding inside navigation view 

---

RevenueCatUI/Views/IntroEligibilityStateView.swift
RevenueCatUI/Views/PurchaseButton.swift

This moves some of the modifications outside of `ConsistentPackageContentView` so they're not duplicated in the hierarchy for each package.

`Paywalls`: simplify `PurchaseButton`

---

RevenueCatUI/Data/Strings.swift
RevenueCatUI/Views/PurchaseButton.swift

Until we improve the presentation of already-subscribed products this is just a no-op. This will at least help developers know why nothing is happening.

`Paywalls`: log warning when attempting to purchase already-subscribed product

---

RevenueCatUI/Data/Localization.swift
Tests/RevenueCatUITests/LocalizationTests.swift

This mainly fixes `{{ price_per_period }}` showing `¥1/y` for year.
I fixed it by forcing a single abbreviation style for Japanese.

`Paywalls`: improve period abbreviations in Japanese

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/View+PresentPaywall.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift

This brings parity with `PaywallView()`.
I've also added notes mentioning that this would disable automatic offering selection for experiments.

`Paywalls`: `.presentPaywallIfNeeded` allows overriding `Offering`

---

Sources/Purchasing/Offering.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/OfferingAPI.swift
Tests/UnitTests/Purchasing/OfferingsTests.swift

This allows to easily extract data from `Offering.metadata` in a structured way.
Example:
```swift
struct Data: Decodable {
var number: Int
}
let elements: [Data] = offering.getMetadataValue(for: "elements") ?? []
let element: Data? = offering.getMetadataValue(for: "element")
```

`Offering`: new `getMetadataValue` with `Decodable` type

---

RevenueCatUI/Data/Localization.swift

We normally don't have to handle this because of our lower deployment target, except we do for `visionOS 1.0`, so this updates it for all.
```
▸ ⚠️  Localization.swift:265:25: 'languageCode' was deprecated in visionOS 1.0: renamed to 'language.languageCode.identifier'
▸ return self.languageCode
▸                         ^
```

Fix deprecation warning

---

RevenueCatUI.podspec

This allows us to use it with the same deployment target as `RevenueCat`.

`RevenueCatUI`: lowered CocoaPods deployment target to 11.0

---

RevenueCatUI/Modifiers/FooterHidingModifier.swift
RevenueCatUI/Modifiers/ViewExtensions.swift
RevenueCatUI/Templates/Template4View.swift

This only reproduces on iOS 16 and using the new `displayCloseButton: true` (because it embeds `PaywallView` in a `NavigationView`).
The problem was that the template used `ViewDimentionPreferenceKey` in several parts of the hierarchy and `SwiftUI` mixes both.
I work around it by separating `onWidthChange` and `onHeightChange`.

`Paywalls`: fix template 4 layout bug on iOS 16

---

.circleci/config.yml

`visionOS` requires M1 since Xcode 15.1 beta 2.

`CircleCI`: fix `visionOS` job

---

RevenueCatUI/Resources/tr.lproj/Localizable.strings

`Paywalls`: fix Turkish discount string

---

RevenueCatUI/Resources/tr.lproj/Localizable.strings

I updated translation of `Privacy`, `Restore`, `Terms`, `Lifetime` and `Continue`.

`Paywalls`: fix Turkish translation

---

Sources/Purchasing/Purchases/Purchases.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift

I ran into this locally. We re-initialize `Purchases` on some tests to simulate re-starting apps. If a test fails mid-test, `Purchases.shared` might not be defined.

`Integration Tests`: fix potential crash on `tearDown`

---

Package.swift
RevenueCatUI/PaywallFontProvider.swift
RevenueCatUI/Templates/Template4View.swift
RevenueCatUI/Views/FooterView.swift
Sources/FoundationExtensions/Locale+Extensions.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/AdaptiveStack.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ObserverModeManager.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/PurchasesOrchestrator.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift

Apple changed `xrOS` to `visionOS` on the latest beta. Looks like this was already supported in prior `Xcode 15.1` betas, so this doesn't break compatibility with them.

`visionOS`: fix support for `Xcode 15.1 beta 3`

---

Sources/Misc/SystemInfo.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Purchasing/StoreKitAbstractions/Storefront.swift
Tests/UnitTests/Misc/SystemInfoTests.swift
Tests/UnitTests/Mocks/MockSystemInfo.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

Allow backend to determine Storefront of customer
- Adds `X-Storefront` as a default header
- Uses StoreKit 1 implementation since its not async
- StoreKit 2 implementation is async and would require a some restructuring that we don't need right now

Adds `X-Storefront` request header for App Store Storefront

---

Tests/StoreKitUnitTests/StorefrontTests.swift
Tests/UnitTests/Misc/SystemInfoTests.swift

Follow up to #3405.
`SystemInfo.storefront` relies on `SKPaymentQueue`, which requires an `SKTestSession`.
This is why this new test was being flaky. This new implementation explicitly sets the storefront to fix that.

`SystemInfo`: fix flaky `Storefront` test

---

.swiftlint.yml
Sources/Error Handling/ErrorUtils.swift
Sources/Misc/Codable/IgnoreHashable.swift
Sources/Purchasing/StoreKitAbstractions/SK1StoreProductDiscount.swift
Sources/Purchasing/StoreKitAbstractions/SK2StoreProductDiscount.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
Tests/UnitTests/Networking/Backend/BackendGetIntroEligibilityTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift

This rule will warn when calling `init` with the explicit type where it can be inferred, or where the `.init` part can be omitted.

Enable explicit_init lint rule and fix issues

---

RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Mocks/MockStoreMessagesHelper.swift

This was meant to be just for tests.

Remove `MockStoreMessagesHelper` from SDK

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
Tests/TestPlans/CI-RevenueCat-Snapshots.xctestplan
fastlane/Fastfile

See #2421.
iOS 14 + Snapshots needs a new test plan that doesn't run StoreKit tests.

`CircleCI`: fix snapshot generation for iOS 14

---

Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/VerificationResultAPI.swift

Not sure why but sometimes Xcode gets in a state where it won't compile these without this.

Some `APITester` fixes

---

RevenueCatUI/Data/PaywallViewMode+Extensions.swift
RevenueCatUI/Templates/Template1View.swift
RevenueCatUI/Templates/Template2View.swift
RevenueCatUI/Templates/Template3View.swift
RevenueCatUI/Templates/Template4View.swift
RevenueCatUI/Templates/Template5View.swift

This brings the implementations closer to Android, removing the unnecessary `PaywallViewMode` properties.

`Paywalls`: simplified `PaywallViewMode` logic

---

RevenueCatUI/Data/TemplateViewConfiguration+Extensions.swift
RevenueCatUI/Views/PurchaseButton.swift
Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift

This adds test coverage for the logic added in #3361, now extracted from `PurchaseButton` into a `TemplateViewConfiguration` extension.

`Paywalls`: tests for `PurchaseButton` layout logic

---

RevenueCatUI/Data/TemplateViewConfiguration+Extensions.swift
RevenueCatUI/Templates/Template4View.swift
Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift

`Paywalls`: remove empty space when template 4 has no offer details

---

.circleci/config.yml

Supposedly [the new image](https://discuss.circleci.com/t/xcode-15-beta-2-re-released-and-bumped-to-macos-14-1/49816) has a fix for the [performance issues](https://discuss.circleci.com/t/severe-performance-problems-with-xcode-15/49205/110).
Blocked by `FB13358220`. Waiting on CircleCi to update to Xcode 15.1 beta 3.

`CircleCI`: upgrade to Xcode 15.1

---

RevenueCatUI/Resources/zh-Hans.lproj/Localizable.strings
RevenueCatUI/Resources/zh_HK.lproj/Localizable.strings
RevenueCatUI/Resources/zh_TW.lproj/Localizable.strings

Resolves #3489
Another issue I found after looking at the [Localizable.strings](https://github.com/RevenueCat/purchases-ios/pull/3489/files): You can’t directly translate "%d%% off” as "%d%%折” in Chinese. In Chinese, if one item is 20% off, we say it’s “8折” (8 comes from (1-20%)*10).
So if you insist on this translation you will need to change the related code. I would suggest you to simply translate "%d%% off" as "优惠%d%%"(Simplified Chinese) and "優惠%d%%" (Traditional Chinese), which aligns with the word ”off”.
Last issue regarding formatting: "Default_offer_details_with_intro_offer" = "开始 {{ sub_offer_duration }} 试用，然后 {{total_price_and_per_month }}。";  I don’t think we need spaces around “{{ sub_offer_duration }}” and ”{{total_price_and_per_month }}”.

Fix Chinese localizations

---

RevenueCatUI/Data/Localization.swift
Sources/Paywalls/PaywallData+Localization.swift

See https://github.com/apple/swift/issues/55374
`.first` has been broken since 2020.

`Optimization`: changed `first` to `first(where:)`

---

RevenueCatUI/Data/Localization.swift
RevenueCatUI/Data/TestData.swift
RevenueCatUI/Data/Variables.swift
RevenueCatUI/Helpers/Package+VariableDataProvider.swift
RevenueCatUI/Templates/Template4View.swift
Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
Tests/RevenueCatUITests/Data/VariablesTests.swift
Tests/RevenueCatUITests/LocalizationTests.swift

If you select a custom package type and set Offer Period, the paywall would have an empty entry for that package. 
| :-: | :-: |
| ![IMG_908CED5B663B-1 (1)](https://github.com/RevenueCat/purchases-ios/assets/3922667/2519c74e-c0d2-44c1-a126-64bd78808384) | ![IMG_B1CED574DF20-1](https://github.com/RevenueCat/purchases-ios/assets/3922667/1eaf17d6-75fd-4e20-86cf-ef93de2d74d3) |

`Paywalls`: fix empty description when using `custom` package type and `{{ sub_period }}`

---

RevenueCatUI/Views/FooterView.swift

Updated the terms and Privacy Policy links to open within the app, without exiting to Safari
https://github.com/RevenueCat/purchases-ios/assets/685609/e10df16d-1016-4271-9270-35c4ae8a87d4

`Paywalls`: open Terms and Privacy Policy links in-app

---

RevenueCatUI/Resources/zh-Hans.lproj/Localizable.strings

“終” is Traditional Chinese while “终” is Simplified Chinese.

Fix typo in zh-Hans localization of RevenueCatUI

---

Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift

Thanks to #3278, this can now never be `nil` starting from iOS 16.

`StoreProduct`: improve `priceFormatter` documentation

---

RevenueCatUI/Views/FooterView.swift

Follow up to #3475.
This new implementation doesn't make sense (and doesn't work very well) on Catalyst. It will now fall back to the previous implementation and open the link on a new window (using the default system browser).

`Paywalls`: open footer links on Safari on Catalyst

---

.circleci/config.yml

Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/16692/workflows/6314719e-fc77-44db-b653-5d6f13311a4b/jobs/152113
This adds a call to `setup-git-credentials` when generating snapshots.
Instead of duplicating that in every job, I've extracted `create-snapshot-pr-if-needed`

`CircleCI`: add git credentials to snapshot generation

---

RevenueCatUI/Views/PurchaseButton.swift

This is what it looked like before:
I chose that on purpose to provide a "native" look to paywalls. However, as others have reported, it has several issues:
- It's too small. The button should be the most obvious action to take on the paywall.
- It doesn't respect the configuration for the paywall (background and foreground color).
This looked like a "bug", so the new implementation will provide consistency with what users probably expect:

`Paywalls`: change style of CTA button to be consistent with other platforms

---

RevenueCatUI/Modifiers/ViewExtensions.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/Templates/Template4View.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/Views/LoadingPaywallView.swift
Tests/RevenueCatUITests/Templates/OtherPaywallViewTests.swift

Fixes #3516.
This logic only existed for `.presentPaywallIfNeeded`. However, it should apply to `PaywallView` when presented manually as well.
This is also consistent with how Android works, reduces boilerplate code required by users, and removes the possibility that a paywall is still presented after a purchase, which doesn't make sense since our paywalls don't have a mode for "already subscribed".

`Paywalls`: always dismiss paywalls automatically after a purchase

---

RevenueCatUI/Helpers/Logger.swift

I made the wrong assumption that the log level checking was part of `Purchases.verboseLogHandler`,
but it's done by `Logger` outside of that call. Therefore `RevenueCatUI` also needed the check.

`Paywalls`: silence logs below `Purchases.logLevel`

---

RevenueCatUI/UIKit/PaywallViewController.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

This adds a new method to the `PaywallViewControllerDelegate` to indicate when the `PaywallViewController` is dismissed.
This will be useful to listen to responses in the hybrids, since we need to present the paywall and wait until it's been purchased/dismissed before returning a value for the hybrids.
This will be needed to fix: https://github.com/RevenueCat/purchases-flutter/issues/886

Paywalls: Add dismissal method in `PaywallViewControllerDelegate`

---

RevenueCatUI/Views/FooterView.swift

These seemed to be the default before, but it broke with #3475.
Difference (before and after):
This restores the layout shown on the left side.

`Paywalls`: improve `FooterView` text alignment

---

RevenueCatUI/Views/FooterView.swift

Fixes #3518.
Follow up to #3475 and #3508.

`Paywalls`: ensure footer links open in full-screen sheets

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift

Presenting the default paywall was still displaying 2 close buttons

`Paywalls Tester`: remove double close button

---

RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift

The existing implementation was not compiling on `watchOS` and needed to be in the `#else` branch.

`Paywalls`: fix `ColorInformation.multiScheme` on `watchOS`

---

RevenueCatUI/Templates/Template5View.swift

`Paywalls`: fix template 5 footer loading view alignment

---

Sources/Logging/Strings/NetworkStrings.swift
Sources/Misc/DangerousSettings.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Security/HTTPRequest+Signing.swift
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
Tests/UnitTests/Mocks/MockHTTPClient.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Networking/SignatureVerificationHTTPClientTests.swift

Follow up to #3424. This adds coverage to ensure that the backend continues to sign correctly for old SDK versions that don't support this.

`Trusted Entitlements`: tests for signature verification without header hash

---

RevenueCatUI/Templates/Other platforms/WatchTemplateView.swift

I demoed the paywall with a header during the Launch Party 🎈 but this wasn't part of the template before.
With this change, it becomes an optional element if the paywall has a configured header image:

`Paywalls`: add header image to `watchOS` paywalls

---

RevenueCatUI/UIKit/PaywallViewController.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

- Add `paywallViewControlleSizeDidChange` to notify of size changes
- Added back top anchor to footers for auto layout to size correctly

`Paywalls`: new `PaywallViewControllerDelegate.paywallViewController(_:didChangeSizeTo:)`

---

RevenueCatUI/UIKit/PaywallViewController.swift

`PaywallViewControllerDelegate`: fixed typo in `@objc` method name

---

.circleci/config.yml

There is a lot of flaky failures due to bugs that have been fixed in iOS 17.
Depends on #3403, blocked by `FB13358220`.

`Integration Tests`: run on iOS 17

---

RevenueCatUI/Helpers/Package+VariableDataProvider.swift
Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProduct.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/TestStoreProductAPI.swift
Tests/StoreKitUnitTests/StoreProductTests.swift

Added `localizedPricePerWeek`, `localizedPricePerMonth` and `localizedPricePerYear`.
I started on this before noticing that we already [have an equivalent at the package level](https://github.com/RevenueCat/purchases-ios/blob/main/RevenueCatUI/Helpers/Package%2BVariableDataProvider.swift#L107), still need to unify them.

`StoreProduct`: add localized price per period strings

---

Tests/TestingApps/PurchaseTesterSwiftUI/Shared/ReceiptInspector.swift

Receipts in logs have extra escape sequences now (forward slashes), so this updates the ReceiptInspector tool to be able to accept them for easier usage. 
It also accepts extra `"` so that if you copied slightly incorrectly it still works.

`PurchaseTester`: improved `ReceiptInspector` so it accepts receipts with escape sequences

---

RevenueCatUI/Data/LocalizedAlertError.swift
Tests/RevenueCatUITests/Data/LocalizedAlertErrorTests.swift

This prevents "leaking" _RevenueCat_ in the error dialogs:
With this change, users still get some information about the problem, and we get enough context to be able to diagnose it:

`Paywalls`: improve error display

---

RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PurchaseRestoreCompleted.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift

This allows apps to be able to receive notifications when users cancel a purchase.

`Paywalls`: new `.onPurchaseCancelled` and `paywallViewControllerDidCancelPurchase:`

---

.circleci/config.yml
Tests/BackendIntegrationTests/OtherIntegrationTests.swift

`CircleCI` is deprecating Intel machines, so we need to get this working: https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
~~Deadline for this is January 31 2024.~~ New deadline is 28 June 2024.
Note that Codecov isn't compatible ([yet?](https://github.com/codecov/feedback/issues/51)) so I'm turning it off for now.

`CircleCI`: change all jobs to M1

---

RevenueCatUI/Data/PaywallViewConfiguration.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift
Tests/RevenueCatUITests/BaseSnapshotTest.swift
Tests/RevenueCatUITests/PaywallViewEventsTests.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift

The number of parameters was already very large. This refactor combines the different values into its own type.
This is also a preliminary refactor to be able to configure a paywall with an offering identifier instead of an offering, which will be used by the hybrid SDKs.

`Paywalls`: extracted `PaywallViewConfiguration`

---

RevenueCatUI/Data/Errors/PaywallError.swift
RevenueCatUI/Data/PaywallViewConfiguration.swift
RevenueCatUI/Helpers/Optional+Extensions.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/UIKit/PaywallFooterViewController.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift
Sources/FoundationExtensions/Optional+Extensions.swift
Sources/FoundationExtensions/String+Extensions.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

Depends on #3586.
This will be used by the hybrid SDKs to be able to load paywalls with an offering identifier.

`PaywallViewController`: new initializer with `Offering` identifier

---

RevenueCatUI/Helpers/Optional+Extensions.swift

Fixes https://circleci.com/gh/RevenueCat/purchases-ios/163464 Unfortunately CocoaPods does not support symlinks, and neither `pod spec lint` nor our installation tests (because they use a local reference) can catch that.
This replaces it with a copy of the file.

`RevenueCatUI`: fix CocoaPods build

---

Tests/InstallationTests/CocoapodsInstallation/CocoapodsInstallation.xcodeproj/project.pbxproj
Tests/InstallationTests/CocoapodsInstallation/Podfile
Tests/InstallationTests/CocoapodsInstallation/Podfile.lock

`RevenueCatUI` doesn't require a higher deployment target.
This led to `CocoaPods` creating a duplicate target unnecessarily.

Simplify `CocoapodsInstallation` `Podfile`

---

RevenueCatUI/UIKit/PaywallViewController.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

For use by `react-native-purchases`.
This is not the most efficient, but it's required because we don't get the props on React Native until after we've already returned the `UIView`.

`PaywallViewController`: methods for reconfiguring paywall with new offering

---

Sources/Networking/InternalAPI.swift
Sources/Paywalls/Events/PaywallEventStore.swift
Sources/Purchasing/StoreKit2/SK2BeginRefundRequestHelper.swift
Sources/Support/BeginRefundRequestHelper.swift
Sources/Support/DebugUI/DebugContentViews.swift
Sources/Support/DebugUI/DebugViewModel.swift
Sources/Support/StoreMessagesHelper.swift
Tests/UnitTests/Mocks/MockSK2BeginRefundRequestHelper.swift

- `InternalAPI` is now `Sendable` to deal with new compilation error
- `PaywallEventStoreType` is now `Sendable`
- Extracted `SK2BeginRefundRequestHelperType` to make `SK2BeginRefundRequestHelper` `Sendable`
- Updated `MockSK2BeginRefundRequestHelper` to be thread-safe and `Sendable`
- Fixed compilation error in `DebugContentViews`
- Fixed compilation error in `DebugViewModel`
- Fixed compilation error in `StoreMessagesHelper`

`Xcode 15.3 beta 1`: fix compilation errors

---

Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2CachingProductsManagerTests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift
Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
Tests/StoreKitUnitTests/Support/DebugViewSwiftUITests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift
Tests/UnitTests/Diagnostics/FileHandlerTests.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Tests/UnitTests/OfflineEntitlements/OfflineEntitlementsManagerTests.swift
Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift
Tests/UnitTests/Purchasing/CachingTrialOrIntroPriceEligibilityCheckerTests.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
Tests/UnitTests/Purchasing/StoreKitAbstractions/StoreEnvironmentTests.swift
Tests/UnitTests/Purchasing/StoreKitRequestFetcherTests.swift

#3599 made the SDK compile.
These addresses more issues on tests so we can now run them on Xcode 15.3 beta 1 with Swift 5.10

`Xcode 15.3 beta 1`: fix warnings on tests

---

Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

`FB11889732` was [fixed on iOS 17.4](https://developer.apple.com/documentation/ios-ipados-release-notes/ios-ipados-17_4-release-notes#Resolved-Issues):

`Integration Tests`: disable failure expectation on `iOS 17.4`

---

Sources/Logging/Strings/StoreKitStrings.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Mocks/MockStoreKit2TransactionListener.swift

We already set this for SK1 purchases:
https://github.com/RevenueCat/purchases-ios/blob/daa0e1f3d0b8eaf653d81ef99396caa2a5e95506/Sources/Purchasing/Purchases/PurchasesOrchestrator.swift#L385
However, as explained in the documentation, if this value is not a UUID, it basically gets ignored:
https://developer.apple.com/documentation/storekit/skmutablepayment/1506088-applicationusername
This PR makes sure we do the equivalent in SK2 purchases.

Set StoreKit 2 appAccountToken if our appUserID is an UUID

---

.circleci/config.yml

Follow up to #3262.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/17384/workflows/4c13d08f-1970-4e40-b5e6-0cccae0d5ab7/jobs/166078/parallel-runs/0/steps/0-106

`CircleCI`: push pods using Xcode 15

---

Sources/Identity/CustomerInfo.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift

This will be used by `RevenueCatUI` for #3620.

`CustomerInfo`: conform to `Identifiable`

---

RevenueCatUI/Data/Strings.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/Views/FooterView.swift
Tests/RevenueCatUITests/PaywallFooterTests.swift
Tests/RevenueCatUITests/PresentIfNeededTests.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift

Fixes #3617.
This allows users to handle that notification only once the user has dismissed the "purchases restored" dialog.

`Paywalls`: `.onRestoreCompleted` is invoked after the restore dialog is dismissed

---

RevenueCatUI/UIKit/PaywallFooterViewController.swift
RevenueCatUI/UIKit/PaywallViewController.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

- [❌ ] If applicable, unit tests
- [✅ ] If applicable, create follow-up issues for `purchases-android` and hybrids
This is the ios counter part to https://github.com/RevenueCat/purchases-android/pull/1589
This exposes the fontName as a parameter and sets CustomFontProvider. 
Created updateFontWithFontName for PaywallViewController
Created init function for offerIdentifier and fontName

`PaywallViewController`: expose `fontName` for `CustomFontProvider`

---

RevenueCatUI/UIKit/PaywallFooterViewController.swift
RevenueCatUI/UIKit/PaywallViewController.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

Original PR: #3626.
This is the iOS counterpart to https://github.com/RevenueCat/purchases-android/pull/1589
This exposes the `fontName` as a parameter and sets `CustomFontProvider`. 
- Created `updateFontWithFontName` for `PaywallViewController`
- Created init function for `offerIdentifier` and `fontName`

`PaywallViewController`: expose `fontName` for `CustomFontProvider` (by @Jjastiny)

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift
RevenueCatUI/View+PurchaseRestoreCompleted.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Tests/RevenueCatUITests/Helpers/AsyncTestHelpers.swift
Tests/RevenueCatUITests/PaywallFooterTests.swift
Tests/RevenueCatUITests/PresentIfNeededTests.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift

Similar to #3622.
This API is available in:
- `PaywallView()`
- `.presentPaywallIfNeeded`
- `.paywallFooter`
- `PaywallViewControllerDelegate`

`Paywalls`: new `.onPurchaseStarted` modifier

---

RevenueCatUI/Data/Localization.swift
RevenueCatUI/Data/Variables.swift
RevenueCatUI/Helpers/Package+VariableDataProvider.swift
Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
Tests/RevenueCatUITests/Data/VariablesTests.swift

- `price_per_period_full`
- `total_price_and_per_month_full`
- `sub_period_length`
- `sub_period_abbreviated`

`Paywalls`: add 4 new variables

---

Sources/FoundationExtensions/Locale+Extensions.swift
Sources/Paywalls/PaywallData+Localization.swift
Tests/UnitTests/FoundationExtensions/LocaleExtensionsTests.swift
Tests/UnitTests/Paywalls/PaywallDataTests.swift

This was a regression introduced by #3605.
Consider a paywall configuration with these locales: `en_US`, `de_DE`.
Running on a device with locale `en_IN` for example.
Before #3605, `PaywallData.localizedConfiguration` would have returned the `en_US` localization. However, that change made it so that it could no longer find a matching localization with a different region.
This fix improves the locale lookup so that if it doesn't find a matching localization with both language AND region, it then tries to look it up with only the language, before falling back to the default localization.

`Paywalls`: fix finding locales with different regions

---

RevenueCatUI/View+PresentPaywall.swift

- Added a way to present `PaywallView` either as sheet or full screen
- No breaking changes have been made
I wanted to easily present the PaywallView on full screen.
I added a new enum `PaywallPresentationMode` which currently has 2 options: `.sheet` and `.fullScreen `. I added this as a parameter to the current public `presentPaywallIfNeeded` modifiers. The default is `sheet` so there are no breaking changes with the current public API.
| Sheet             | Full Screen    |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-02-05 at 18 08 51](https://github.com/RevenueCat/purchases-ios/assets/1515520/80f4c418-5dd7-4ba9-87a3-1b824bd6fc10)  |  ![Simulator Screenshot - iPhone 15 Pro - 2024-02-05 at 18 44 …

`Paywalls`: new `presentationMode` parameter

---

RevenueCatUI/View+PresentPaywall.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift

Original PR: #3632 by [Lascorbe](https://github.com/Lascorbe).
- Added a way to present `PaywallView` either as sheet or full screen
- No breaking changes have been made
I wanted to easily present the PaywallView on full screen.
I added a new enum `PaywallPresentationMode` which currently has 2 options: `.sheet` and `.fullScreen`. I added this as a parameter to the current public `.presentPaywallIfNeeded` modifiers. The default is `sheet` so there are no breaking changes with the current public API.
| Sheet             | Full Screen    |
| ------------- | ------------- |
| ![Simulator Screenshot - iPhone 15 Pro - 2024-02-05 at 18 08 51](https://github.com/RevenueCat/purchases-ios/assets/1515520/80f4c418-5dd7-4ba9-87a3-1b824bd6fc10)  |  ![Simulator Screenshot - iPhone 15 Pro - 2024-02-05 …

`Paywalls`: new `presentationMode` parameter (by @Lascorbe)

---

Sources/Purchasing/NonSubscriptionTransaction.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCNonSubscriptionTransactionAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/NonSubscriptionTransactionAPI.swift

Fixes #3636.
This was added in #3009.
It was not made `public` because it was only used for #2841, but as explained in #3636 it can be useful as `public`.

`NonSubscriptionTransaction`: expose `storeTransactionIdentifier`

---

Sources/Support/DebugUI/DebugViewModel.swift
Sources/Support/StoreMessagesHelper.swift
Tests/StoreKitUnitTests/StoreKitConfigTestCase.swift

See #3599.
This is listed in the [release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-15_3-release-notes) as fixed.

`Xcode 15.3 beta 2`: remove `nonisolated` workaround

---

RevenueCat.xcodeproj/project.pbxproj

This fixes a compilation error with `Xcode 15.3 beta 2`.
Because we were missing the deployment target, Xcode defaults to the latest (which is `1.1`), and fails with a deprecation warning.

Add explicit `visionOS` deployment target

---

.circleci/config.yml

Many jobs were calling both `install-dependencies` and `update-spm-installation-commit`, which was then installing dependencies again:

`CircleCI`: remove duplicate `install-dependencies`

---

Sources/Logging/Strings/PaywallsStrings.swift
Sources/Paywalls/PaywallData+Localization.swift

Will make debugging issues like #3633 and https://github.com/RevenueCat/purchases-ios/pull/3633#issuecomment-1931848279 easier.
```
VERBOSE: Looking up localized configuration for ["de_CH", "de"]
VERBOSE: Found localized configuration for 'de'
```

`Paywalls`: add logs for localization lookup

---

.circleci/config.yml
Package.swift
Package@swift-5.7.swift
Package@swift-5.8.swift
README.md
RevenueCat.podspec
RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI.podspec
Sources/Support/SwiftVersionCheck.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
Tests/UnitTests/StoreKitExtensions/SKErrorTests.swift

See https://github.com/RevenueCat/purchases-ios/blob/1fd2736217c94ec025f5e44724f978505f4a84c0/Contributing/UpdatingRequirements.md
- #3616 
- Update deployment target on PHC and hybrids
- Update https://github.com/RevenueCat/revenuecat-docs/blob/main/docs_source/Getting%20Started/installation/ios.md
- Update https://github.com/RevenueCat/revenuecat-docs/blob/main/docs_source/Getting%20Started/installation/macos.md

Bump deployment target to `iOS 13` / `tvOS 13` / `macOS 10.15`

---

Sources/Misc/StoreKitVersion.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreKitVersionAPI.m

The word `StoreKit` was unnecessarily duplicated.

`StoreKitVersion`: simplify `Objective-C` names

---

Sources/Logging/Strings/PaywallsStrings.swift
Sources/Paywalls/PaywallData+Localization.swift
Tests/UnitTests/Paywalls/PaywallDataTests.swift

Fixes #3655.
Follow up to #3633.
This improves upon that PR by using `Locale.current.removingRegion` for each locale **before** trying to look up `Locale.preferredLocales`.
This fixes this scenario:
- Configure your phone with: `en_IN` and `es_ES`
- Launch paywall with localization `en_US` and `es_ES`
Prior to this change, we'd be looking up localizations in this order:
- `en_IN`
- `es_ES`
- `en` (no region)
Because there _is_ a localization for `es_ES` we'd return that one before attempting to look up `Locale.current.removingRegion`.
Example of the new log:
> VERBOSE: Looking up localized configuration for ["en_IN", "es_ES"], searching for ["en_IN", "en", "es_ES", "es"]
> VERBOSE: Found localized configuration for 'en'

`Paywalls`: prioritize `Locale.current` over `Locale.preferredLocales`

---

RevenueCatUI.podspec

Localized files are found automatically by `SPM`, but not through CocoaPods.

`Paywalls`: fix localization when installing through `CocoaPods`

---

RevenueCatUI/Data/PaywallData+Validation.swift
RevenueCatUI/Data/TemplateViewConfiguration.swift
RevenueCatUI/TemplatePackageSetting.swift
RevenueCatUI/Templates/TemplateViewType.swift
Sources/Paywalls/PaywallData.swift

`PaywallData.packages` won't be used by multi-tier paywalls, so we need to allow that.

`Paywalls`: allow empty `packages`

---

.circleci/config.yml
BackendIntegrationTests/BackendIntegrationTests-Shedder.xctestplan
RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme

Follow up to #3673.
- Split `loadshedder-integration-tests` into `integration-tests-all` and `loadshedder-integration-tests-v3`
- Removed `loadshedder-integration-tests` from `build_test`: this reverts #3673. We already run loadshedder tests as part of `SK1` and `SK2` test suites.
- Add `BackendIntegrationTests-Shedder` test plane. This isn't used by CI (see above point), but it can be useful to run all of the load shedder tests.

`CI`: split load shedder integration tests

---

RevenueCatUI/Helpers/PreviewHelpers.swift

This adds the paywall name to the display name:

`Paywalls`: improve `PreviewableTemplate`'s display name

---

.circleci/config.yml

Small performance optimization. This isn't needed when creating snapshots.

`CI`: skip `RevenueCatUI` API tests when generating snapshots

---

RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift

We probably didn't notice this because `PaywallData.Configuration.ColorInformation.multiScheme` checks for the existence of `dark` before.
However, this new implementation helps with the upcoming tier color overrides.

`Paywalls`: fix `PaywallColor.init(light:dark:)`

---

RevenueCatUI/PaywallView.swift

Follow up to #3517.
This behavior is the default and not opt-in, and it doesn't make sense on footer paywalls.

`Paywalls`: don't dismiss footer paywalls automatically

---

RevenueCatUI/Helpers/TemplateView+MultiTier.swift
RevenueCatUI/Templates/Template7View.swift
RevenueCatUI/View+PresentPaywallFooter.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/CustomPaywall.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/CustomPaywallContent.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift

This is useful for implementing custom paywalls using `.footerPaywall` and responding to the tier selected in a paywall.

`Paywalls`: `.onPaywallTierChange`

---

RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
Sources/Logging/Strings/OfferingStrings.swift
Sources/Logging/Strings/PurchaseStrings.swift
Sources/Purchasing/Package.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/Support/PaywallExtensions.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/CustomEntitlementComputationSwiftAPITester.xcodeproj/project.pbxproj
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PackageAPI.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/main.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPackageAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContext.h
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPresentedOfferingContext.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/main.m
Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
Tests/APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PresentedOfferingContextAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

Allow for storing of other presented offering context on a `Package`
- Replaced `offeringIdentifier: String` on `Package` with new `presentedOfferingContext: PresentedOfferingContext`
- Currently it only has a `offeringIdentifier: String`
- Eventually this will add new optional properties for targeting and placements

New `Package.presentedOfferingContext`

---

RevenueCatUI/View+PresentPaywallFooter.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift

We added purchase cancellation callbacks in #3578 but we didn't add them to the `paywallFooter` modifier. 
This adds them there so it's more convenient.

`Paywalls`: Add `purchaseCancelled` parameter to `paywallFooter` modifier

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift
RevenueCatUI/View+PurchaseRestoreCompleted.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
Tests/RevenueCatUITests/PaywallFooterTests.swift
Tests/RevenueCatUITests/PresentIfNeededTests.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift

Similar to #3627.
This API is available in:
- `PaywallView()`
- `.presentPaywallIfNeeded`
- `.paywallFooter`
- `PaywallViewControllerDelegate`

`Paywalls`: new `.onRestoreStarted` modifier

---

Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift

While working on #3693 I noticed we were missing some API tests that would be helpful for that PR

Add more Paywalls API tests

---

RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift

Since we are deprecating the old function in https://github.com/RevenueCat/purchases-ios/pull/3693/files 
I thought it will be simpler to just add both `restoreStarted` and the new `purchaseStarted(package:)`  in the same release. We haven't made a release since I merged #3694 so these are safe to remove for now.
I open this PR in case we want to make a release before #3693 is finished.

Remove `restoreStarted` from extensions

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift
RevenueCatUI/View+PurchaseRestoreCompleted.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
Tests/RevenueCatUITests/PaywallFooterTests.swift
Tests/RevenueCatUITests/PresentIfNeededTests.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift

Similar to #3627.
This API is available in:
- `PaywallView()`
- `.presentPaywallIfNeeded`
- `.paywallFooter`
- `PaywallViewControllerDelegate`

`Paywalls`: new `.onPurchaseStarted(package)` modifier

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
Tests/StoreKitUnitTests/StoreProductTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitConfigTestCase+Extensions.swift

We can use any transaction token available, not only auto-renewable ones

`[SK2]`: Fix syncPurchases

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Error Handling/ErrorCode.swift
Sources/Logging/Strings/IdentityStrings.swift
Sources/Misc/RateLimiter.swift
Sources/Purchasing/OfferingsManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/HomeView.swift
Tests/UnitTests/Misc/RateLimiterRests.swift
Tests/UnitTests/Mocks/MockOfferingsManager.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesSyncAttributesAndOfferingsIfNeededTests.swift

Adding new method to manually sync attributes and fetch fresh offerings 
- New `Purchases.shared.syncAttributesAndOfferingsIfNeeded()` method
- Syncs subscriber attributes and then fetches fresh offerings from network
- This is designed to be a blocking call since developer will want fresh offerings after syncing subscriber attributes
- The method is rate limited to 5 calls per minute (new `RateLimiter` class()

New `syncAttributesAndOfferingsIfNeeded` method

---

.circleci/config.yml
Gemfile
Gemfile.lock
Package.swift
Package@swift-5.7.swift
Package@swift-5.8.swift
RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Tests/UnitTests/Misc/XCTestCase+Extensions.swift

Follow up to #3599 and #3600.
These `@MainActor` annotations don't work anymore because of this:
> Main actor-isolated class '...' has different actor isolation from nonisolated superclass 'TestCase'; this is an error in Swift 6
They were necessary with an older version of Xcode (likely 13.x), but not anymore.

`Xcode 15.3`: fix warnings on Integration Tests

---

.circleci/config.yml
Gemfile
Gemfile.lock
Package.swift
Package@swift-5.7.swift
Package@swift-5.8.swift
RevenueCat.xcodeproj/project.pbxproj
RevenueCat.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Tests/StoreKitUnitTests/LocalReceiptParserStoreKitTests.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Tests/UnitTests/Misc/XCTestCase+Extensions.swift

Reverts RevenueCat/purchases-ios#3603
I _think_ this is causing a bunch of failures in SK2 tests

Revert "`Xcode 15.3`: fix warnings on Integration Tests"

---

BackendIntegrationTests/BackendIntegrationTests-SK2.xctestplan
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift

Unlock shipping by skipping tests that are flaky unneeded tests
Removing StoreKit2JWS tests from `BackendIntegrationTests-SK2.xctestplan`
⚠️ The functionality in `StoreKit2JWSIntegrationTests` (which is the `usesStoreKit2JWS` dangerous setting), is not publicly available in iOS v4. Its intention was intended only for iOS v5. These tests are safe to skip since they have no production use. 
⚠️ It _is_ important that these are not skipped for iOS v5.

Remove unneeded tests for StoreKit2 with JWS

---

Sources/Purchasing/Offerings.swift
Tests/UnitTests/Purchasing/OfferingsTests.swift

Targeting context was not being passed when getting current offering for placement
- Passing `Offerings.Targeting` when copying `Offering` with a placement identifier
- Added test

Fix for passing `TargetingContext` when using `currentOffering(forPlacement:)`

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift

The changes in https://github.com/RevenueCat/purchases-ios/pull/3694/ included a few parameters being passed to PaywallsTester that had the wrong name, this addresses it

PaywallsTester: fix compilation

---

.circleci/config.yml

Xcode 14 tests broke with xcbeautify 2.0.0, which needs xcode 15. Earlier versions of xcbeautify are not available in homebrew, so we need to install it using mint

Pin xcbeautify version for xcode 14 tests

---

Sources/LocalReceiptParsing/Helpers/ReceiptStrings.swift
Sources/LocalReceiptParsing/PurchasesReceiptParser.swift
Tests/UnitTests/Purchasing/ReceiptStringsTests.swift

[EXTERNAL] Fix Typos in ReceiptStrings.swift (#3756) via @nickkohrn

---

Gemfile.lock
fastlane/.env.SAMPLE
fastlane/Fastfile
fastlane/README.md

This avoids having to go through CircleCI's UI when we want to trigger a bump

Add lane to trigger bumps

---

Sources/CodableExtensions/Store+Extensions.swift
Sources/Purchasing/EntitlementInfo.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCEntitlementInfoAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

iOS part of adding `RC_BILLING` store to the mobile SDKs

Add `RC_BILLING` store

---

RevenueCat.podspec

The library already includes Privacy.xcprivacy in SPM, but when used with CocoaPods (mandatory in Flutter), these files are not exported as the podspec does not include that file as a resource bundle.
Listing the PrivacyInfo.xcprivacy file inside the resource_bundles specification in the podspec allows to distribute the file correctly. Ref. https://github.com/CocoaPods/CocoaPods/issues/10325#issuecomment-1718723762
This GitHub issue contains the entire discussion on how to add these xcprivacy files and is referenced in multiple places; many libraries already follow this approach:
https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseCrashlytics.podspec
https://github.com/SDWebImage/SDWebImage/pull/3649
https://github.com/flutter/packages/pull/5846 …

[EXTERNAL] Cocoapods support for privacy manifest

---

RevenueCat.podspec

The library already includes Privacy.xcprivacy in SPM, but when used with CocoaPods (mandatory in Flutter), these files are not exported as the podspec does not include that file as a resource bundle.
Listing the PrivacyInfo.xcprivacy file inside the resource_bundles specification in the podspec allows to distribute the file correctly. Ref.
https://github.com/CocoaPods/CocoaPods/issues/10325#issuecomment-1718723762
This GitHub issue contains the entire discussion on how to add these xcprivacy files and is referenced in multiple places; many libraries already follow this approach:
https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseCrashlytics.podspec https://github.com/SDWebImage/SDWebImage/pull/3649 https://github.com/flutter/packages/pull/5846 …

[EXTERNAL] Cocoapods support for privacy manifest (#3772) via @sdurban

---

Tests/BackendIntegrationTests/__Snapshots__/StoreKitIntegrationTests/testCanGetOfferings.1.json

Fix integration tests
Integration test snapshot was missing `placements` key with the default offering the the placements fallback. This will always happen now to make sure that `getCurrentOffering(forPlacement:)` has a fallback even when placements isn't enabled.

Fix offerings integration test

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Diagnostics/DiagnosticsEntry.swift
Sources/Diagnostics/DiagnosticsFileHandler.swift
Sources/Misc/Codable/AnyEncodable.swift
Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
Tests/UnitTests/Diagnostics/FileHandlerTests.swift

Based off https://github.com/RevenueCat/purchases-ios/pull/2672/
Equivalent to https://github.com/RevenueCat/purchases-android/pull/784/
Adds DiagnosticsEntry classes and implements adding an entry to the file, getting all entries, and deleting X first entries

iOS append events to JSONL file and get diagnostics events

---

Sources/Misc/Concurrency/Purchases+async.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesSyncAttributesAndOfferingsIfNeededTests.swift

Added async version of `syncAttributesAndOfferingsIfNeeded()`
- New async version of `syncAttributesAndOfferingsIfNeeded()` on `PurchasesType`
- Added both async and non-async (oops) versions to API Testers

Add async `syncAttributesAndOfferingsIfNeeded()`

---

RevenueCatUI/Modifiers/ViewExtensions.swift
Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md

`onChangeOf` was accidentally made public in #3517 
- Change scope of `onChangeOf` from `public` to `internal`
- Added breaking change in v5 migration doc

Change `onChangeOf` to be internal

---

RevenueCatUI/Templates/Template4View.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift

Prevent "Lifetime" from wrapping in Template 4
- Added `.frame(maxWidth: .infinity)` to the package button textfields
-  They were not expanding all the way due to calculations on their parent's width
| <img width="609" alt="Screenshot 2024-04-09 at 9 12 57 PM" src="https://github.com/RevenueCat/purchases-ios/assets/401294/29890622-648a-4b40-975c-66432b721873"> | <img width="609" alt="Screenshot 2024-04-09 at 9 12 16 PM" src="https://github.com/RevenueCat/purchases-ios/assets/401294/a0623580-888c-4e3f-8e8a-000223968320"> |

Prevent Template 4 from wrapping Lifetime

---

RevenueCatUI/UIKit/PaywallFooterViewController.swift
RevenueCatUI/UIKit/PaywallViewController.swift
Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift

This will help dealing with https://github.com/RevenueCat/purchases-flutter/issues/1023
We will conditionally not propagate touch events from the `PaywallViewController` to fix this issue.

Add option to intercept touch events in `PaywallViewController`

---

RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/Templates/TemplateViewType.swift
Sources/Paywalls/PaywallData.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift

Allow presented paywall view to have a custom close button color from the dashboard
- New `close_button` color

Paywalls: Allow closed button color to be configured

---

.circleci/config.yml

Creates a copy of this repo at `/RevenueCat/purchases-ios-spm` that is much faster for integrating RC via SPM.
Before merge:
Before or after merge:

Sync repo in an SPM-friendly way

---

Tests/BackendIntegrationTests/OtherIntegrationTests.swift

Backend integration test account added a new product and tests started failing
Fix test

Fix backend integration test

---

RevenueCatUI/Resources/no.lproj/Localizable.strings

Correct word but wrong context
`Restaurere` to `Gjenopprett`

`Paywalls`: Update Norwegian "restore" localization

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsFileHandler.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
Sources/Identity/CustomerInfoManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/Networking/Backend/BackendPostDiagnosticsTests.swift
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS15-testPostDiagnosticsEventsWithMultipleEvents.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS15-testPostDiagnosticsEventsWithOneEvent.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithMultipleEvents.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/iOS17-testPostDiagnosticsEventsWithOneEvent.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithMultipleEvents.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostDiagnosticsTests/macOS-testPostDiagnosticsEventsWithOneEvent.1.json

Track CustomerInfo verification results

Add diagnostics event for Customer Info verification

---

.circleci/config.yml

It is now required to use xcode 15 to push to the store
https://developer.apple.com/news/?id=fxu2qp7b

Change deploy-purchase-tester to use xcode 15

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/Assets.xcassets/AccentColor.colorset/Contents.json
Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/ManagePaywallButton.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingButton.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift

Base branch is https://github.com/RevenueCat/purchases-ios/pull/3850
This improves the Offerings list UI:
- Offerings with paywalls are grouped into a single section
- Offering paywall buttons are named by their offering, with the sub-title containing the template number and main content.
- Paywall buttons get a ••• menu that is the same as the long-press context menu, but easier to discover
- If there are offerings without configured paywalls, they are listed in a separate section.
- Offerings have links out to the revenue cat dashboard for quick edits (or even to create a new one), which may be handy for use on the phone or for sending the URL to a desktop.
The PR also contain quite a bit of refactoring - view decomposition, simplification in places as well as better data organization …

PaywallsTester: Improves OfferingList UI  (#2 in queue)

---

Tests/Package.swift

Alternative approach to #3876, where in this one we _only_ add the Package.swift file. 
That was the most important part in any case. 
I would still love to clean up the project structure, but it's a much bigger change.

Cleanup: Remove test storekit configuration files when importing through SPM

---

RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker+TestData.swift
RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker.swift
RevenueCatUI/Data/PaywallViewConfiguration.swift
RevenueCatUI/Modifiers/ViewExtensions.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/View+PresentPaywallFooter.swift
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - Live Config.xcscheme
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - SK config.xcscheme
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywallContent.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
Tests/TestingApps/PaywallsTester/Postprocessor.sh
Tests/TestingApps/PaywallsTester/Preprocessor.sh

This PR allows the Paywalls Tester app to access some items internal to purchases-ios by temporarily marking them public during complication.
Items that need to be public have been annotated with `\\@PublicForExternalTesting`.
The Paywalls Tester project runs a script, Preprocessor.sh, as a pre-action to add `public` to all classes/structs/enums/functions/inits that have been annotated.
After compilation it runs a second script, Postprocessor.sh, as a post-action to undo these changes so that they don't accidentally get checked in.
The first script is run as a scheme pre-action rather than as a run script build phase, because when run as a build phase the changes to the files aren't picked up until the next compilation attempt.
It also changes the archive step to be built with a release …

Preprocessor to make select constructs public

---

Sources/Misc/Codable/EnsureNonEmptyCollectionDecodable.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/AsyncButton.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/ErrorDisplay.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/ManagePaywallButton.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift

Adds missing user-facing error alerts, makes the error messages more readable and uses `Error` rather than `NSError` as the type to use when passing errors for presentation.
resolves PWL-458

Improved Error Handling

---

RevenueCatUI/Views/RemoteImage.swift

The paywall template I'm using (five) displays a decorative image but the image isn't marked as decorative to accessibility. In my particular test case that meant that VoiceOver could access it, but there was no audible description of what the image actually was. 
Normally I would change Image() to Image(decorative: ), but since that wasn't possible I used .accessibilityHidden(true).
Added .accessibilityHidden(true) to the two images in RemoteImage. I initially was hesitant to change RemoteImage itself, but went ahead and did so since it seems to be only used by the Paywall templates.

Hide decorative Paywall images from accessibility.

---

RevenueCatUI/Data/IntroEligibility/TrialOrIntroEligibilityChecker.swift
RevenueCatUI/Data/PaywallTemplate.swift
RevenueCatUI/Data/TestData.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/Templates/TemplateViewType.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywall.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomPaywallContent.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Tests/TestingApps/PaywallsTester/Preprocessor.sh

The paywalls examples weren't showing up when compiled in release mode. Enabling it meant making a bunch of more internal things public via the preprocessing script. `TestData` is no longer `#ifdef DEBUG`ed out, but most of its data is still `#ifdef DEBUG`, and when it's compiled with an `internal` modifier and thus nothing uses it, I'd expect what remains to be stripped away during linking.

Paywalls Tester: Enable Example Paywalls in Release Mode

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
Sources/Identity/CustomerInfoManager.swift
Sources/Networking/Backend.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockBackendConfiguration.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/Mocks/MockHTTPClient.swift
Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift

This adds a new diagnostics event `http_request_performed` with some useful information we would like to track about the http requests performed to our servers.

Add `http_request_performed` diagnostics event

---

Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md

Adds notes about observer mode limitations on macOS to the v5 migration guide.

macos observer mode notes

---

.circleci/config.yml
.swiftlint.yml
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
fastlane/Fastfile
fastlane/README.md
fastlane/actions/retry_scan_save_failed_tests.rb

Looking into our flaky tests, I noticed that calls to [forceRenewalOfSubscription](https://developer.apple.com/documentation/storekittest/sktestsession/3579486-forcerenewalofsubscription) don't always trigger calls from `StoreKit.product.updates`, it's flaky as hell. 
I tried instead using an accelerated timeRate value and adding explicit waits, and that seems to consistently work in local testing. Opening this up to see if this helps with the flakiness of these particular tests. 
- This also contains a cherry-picked `swiftlint` fix from https://github.com/RevenueCat/purchases-ios/pull/3909 
- This also contains a cleanup of the _fastlane_ code for started in #3902 (which is what this branch is merging into)

Fix a few flaky tests

---

.circleci/config.yml
.swiftlint.yml
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift

Better implementation of https://github.com/RevenueCat/purchases-ios/pull/3909 and what was just commited to `5.0-dev`
- Only install `swiftlint` on Xcode 15.3 jobs
- Also moved Ruby 3.2.2 install into `install-bundle-dependencies` which was also done in `5.0-dev`

Only install `swiftlint` on Xcode 15 jobs

---

Sources/Misc/StoreKitVersion.swift

Removes an unneeded warning from StoreKitVersion.storeKit2 since we no longer require `handleObserverModePurchase()` to be called for SK2 observer mode.

Remove SK2 warning

---

.circleci/config.yml
Tests/InstallationTests/SPMInstallation/SPMInstallation.xcodeproj/project.pbxproj

Min supported deployment version is 12 in xcode 15
https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/19375/workflows/5e33fc29-dd59-44bf-9868-336faa32b595/jobs/212939

SPMInstallation tests deployment version increase

---

.circleci/config.yml
Sources/Networking/Operations/PostOfferForSigningOperation.swift
Sources/Networking/Operations/PostReceiptDataOperation.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
Sources/Purchasing/StoreKitAbstractions/EncodedAppleReceipt.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Misc/CustomerInfo+TestExtensions.swift
Tests/UnitTests/Mocks/MockStoreKit2TransactionFetcher.swift
Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS16-testPostsReceiptDataWithAppTransactionAndNoReceiptCorrectly.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS17-testPostsReceiptDataWithAppTransactionAndNoReceiptCorrectly.1.json
Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/macOS-testPostsReceiptDataWithAppTransactionAndNoReceiptCorrectly.1.json

This PR adjusts the behavior in `syncPurchases()` so that if no purchases are present, we still POST the `AppTransaction` to POST /receipt instead of just fetching the CustomerInfo.
- If no transactions are present when `syncPurchases()` is called and SK2 is used, then we POST the `AppTransaction` to the POST /receipt endpoint instead of just fetching the CustomerInfo.
- This PR introduces the ability to make a call to POST /receipt without a `fetch_token`.

Only POST AppTransaction in syncPurchases if No Transactions Present

---

.circleci/config.yml
fastlane/Fastfile

Reverted to xcode 14 because it failed in #3932 
I used this PR to also force deploy the docs of that version
I tried with upgrading the ios version and also the arch, but still got issues in xcode 15 see https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/19513/workflows/7d8d2c53-a081-4761-9d77-dfaac7b49d30/jobs/215993

Revert docs-deploy to xcode 14

---

Sources/Purchasing/Configuration.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift

This actually enables consumers to use diagnostics by making the setting public

Diagnostics: Make setting public

---

.circleci/config.yml

Looks like the `prepare-next-version` is failing because the git credentials are not set. This should fix it. I haven't checked the other jobs... But we can fix them later if needed.

Fix prepare next version job

---

.circleci/config.yml
README.md

- Remove jobs that check we can build on xcode 14
- Update requirements section in README.md

Drop xcode 14 support in v5

---

Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md

This PR removes the Original Application Version section guide from the V5 migration guide since it is no longer relevant given the ongoing work with StoreKit2's `AppTransaction`.

Remove Original Application Version Section from Migration Guide

---

.circleci/config.yml

Based on the changes in #3948, this makes it so the iOS 12 and 13 jobs run correctly on M1 machines.

Switch tests for iOS 12 and 13 to M1

---

.circleci/config.yml
Examples/MagicWeather/MagicWeather/Sources/Lifecycle/AppDelegate.swift
Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Purchasing/MockPurchases.swift
RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
Sources/Logging/Strings/ConfigureStrings.swift
Sources/Logging/Strings/PurchaseStrings.swift
Sources/Misc/Deprecations.swift
Sources/Misc/Obsoletions.swift
Sources/Purchasing/Configuration.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesAreCompletedBy.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/ConfigurationTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift

Adds a `PurchasesAreCompletedBy` enum which is used to set if the RC SDK performs the purchase, formerly referred to as "observer mode". This replaces observer mode and finishTransactions. The change has only been made to public-facing APIs, internal ones will be renamed as part of a subsequent PR.
Other changes:
- Renamed `handleObserverModeTransaction(_ PurchaseResult:` to `recordPurchase(_ PurchaseResult:` to try to better communicate what the purpose of the call is. Feedback on if this is needed and what the new name should be is welcome!
- There is a "deprecated" method that doesn't appear to really be a deprecated method, but the deprecation is used as a way of generating a warning where customers are likely mis-using the API. I updated its signature to match the new API. Screenshot …

Deprecate observer mode in 5.0 branch

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Purchasing/MockPurchases.swift
RevenueCatUI/Purchasing/PurchaseHandler+TestData.swift
Sources/Misc/Deprecations.swift
Sources/Purchasing/Configuration.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesAreCompletedBy.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/RevenueCatUITests/PurchaseCompletedHandlerTests.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/ConfigurationTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift

This PR adds:
* `purchasesAreCompletedBy`
which replaces and deprecates public instances of:
* `observerMode`
* `finishTransactions`
Internal references to the above will be removed in a subsequent PR.

finishTransactions/ObserverMode -> PurchasesAreCompletedBy

---

.circleci/config.yml
Gemfile
Gemfile.lock
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
fastlane/Fastfile
fastlane/README.md
fastlane/actions/retry_scan_save_failed_tests.rb

This moves the offline backend integration tests to run on M1 machines in CircleCI.
Since this causes tests to be much more flaky, this includes a cherry-pick of the changes in the 5.0 branch that improves those:  https://github.com/RevenueCat/purchases-ios/pull/3902

Run offline backend integration tests on M1 machines

---

.circleci/config.yml
Tests/InstallationTests/CarthageInstallation/fastlane/Fastfile

It deletes all non-RevenueCat schemes which I assume are not needed by Carthage, so this should save a bit of time over what it was doing before too because it won't spend time on them.
https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/19899/workflows/a895e06e-305d-439d-9f99-3047a0375594

Fix Carthage

---

.circleci/config.yml
Gemfile
Gemfile.lock
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/PaywallEventsIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitObserverModeIntegrationTests.swift
Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
fastlane/Fastfile
fastlane/README.md
fastlane/actions/retry_scan_save_failed_tests.rb

This was introduced in #3961 and reverted temporarily in #3974. This brings the changes back.

Bring back offline integration tests on M1

---

Tests/InstallationTests/CocoapodsInstallation/Gemfile

With #3976, we added a new dependency, but we need to also add it to the gemfile for the cocoapods installation tests

Fix cocoapods installation tests

---

Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md

Fixes the OS versions that StoreKit 1 is used in the migration guide.

Fix OS versions in migration guide

---

Sources/Misc/Deprecations.swift
Sources/Misc/Obsoletions.swift
Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift

I found two observer mode configure functions this morning that were deprecated but not obsoleted. This PR obsoletes them to match the obsoletion of the other observerMode configure functions.

Obsolete all observer mode configure functions

---

.circleci/config.yml

At some point along the way, the 5.0-dev branch's CI lost the required `spm-release-build-xcode-14`, `spm-release-build-xcode-15`, and `spm-xcode-14-1` jobs. This PR brings them back!

Bring back ci jobs

---

.circleci/config.yml

The `5.0-dev` branch was using the `macos.x86.medium.gen2` resource class for the `backend-integration-tests-offline-job`, but that resource class was removed from CircleCI on June 28, 2024 ([source](https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718)). Since the resource class is now unavailable, this job currently fails 100% of the time on `main`.
This PR brings the job onto the same M1 resource as most other jobs. While the tests may be more flaky on M1 machines, the job retry mechanism we have in place now should help counter this.

Use available resource class for backend-integration-tests-offline-job

---

Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift

This PR updates the Purchase Tester app to compile with 5.0.0.

Update Purchase Tester for 5.0.0

---

.circleci/config.yml
fastlane/Fastfile

The doc building process can be fragile at times, and since we only build the docs when we make a deployment, we can be unaware when changes in individual PRs can break our docs' build. This PR aims to make changes that break the docs building process visible earlier in the development cycle to help avoid tricky failures during deployments.
This PR makes two main changes to how docs are built in the CI process:
- Fixes the existing docs job in the deploy pipeline by having it run on Xcode 14.3.0. This fix comes from an [earlier commit](https://github.com/RevenueCat/purchases-ios/commit/f05f0cf14aaf061d7d8f17d2f4f6ac1fec9200a2) by @vegaro that likely got overridden when `5.0-dev` was merged into `main` recently.
- Introduces a job to build the docs on each PR instead of only during the …

CI Build Docs Improvements

---

scripts/docs/v5_api_migration_guide.html

This should be on the latest version so our automations perform the replacements correctly. Otherwise, the matching won't work correctly

Update v5 migration guide to contain current latest version

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift

Restore's Paywall Tester's ability to make sandbox purchases. You must include the Paywalls test app's API key in `LocalConfigItems.swift`. If it doesn't work initially try deleting the app from your simulator (or device) and try again.

Paywalls tester with sandbox purchases

---

.circleci/config.yml

This PR brings back the official xcode version since it looks like version 1.5.0 of xcodes fixed iOS 18 issues https://github.com/XcodesOrg/xcodes/releases/tag/1.5.0. We were relying on a fork that fixed the issues that arose with the release of iOS 18 betas

Bring official `xcodes` back to CI

---

RevenueCatUI/Data/PaywallViewConfiguration.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/View+PresentPaywall.swift

Fixes #4034
`PurchaseHandler` was being cleared/reset when a paywall was being rendered (ex: if an overlay was applied to it)
- Restores `PurchaseHandler` back to being a `@StateObject` from #3187
- `checkForConfigurationConsistency()` has a few changes
- Takes a `PurchaseHandler` as a parameter so it doesn't try to access the `StateObject`
- This was fixes the purple Xcode warning of being access wrongly by it being a `StateObject` again
- Removes `mutating` keyword and returns an `NSError?` which it now sets in the constructor
https://github.com/RevenueCat/purchases-ios/assets/401294/7e6430ca-6243-49ad-b7c0-8a90d90894f8
https://github.com/RevenueCat/purchases-ios/assets/401294/829f12c3-a11a-4952-883c-7ae7addd9c1d

Prevent paywall PurchaseHandler from being cleared on rerender

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Data/FeedbackSurveyData.swift
RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

Based off #3933 
https://github.com/RevenueCat/purchases-ios/assets/664544/11eae984-294a-4e14-8c40-7c2d50994c09
Can probably use some animations, but tuning that up will come up later
It will open a feedback survey for an option if there's one

[Customer Center] Build feedback survey from JSON

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift

This adds a modifier, `presentCustomerCenter` that can be used to more simply display the customer center. The API looks like:
```
.presentCustomerCenter(isPresented: self.$presentingCustomerCenter) {
self.presentingCustomerCenter = false
}
```

[CustomerCenter] Add `presentCustomerCenter` modifier

---

scripts/pre-commit.sh

As the title says. It does a rudimentary intersect of the existing `FILES_TO_CHECK` and the staged files, and checks _those_ files for leftover API keys. 
This allows you to set API keys in any of the `FILES_TO_CHECK` files, as long as you're not trying to commit them. Otherwise you'd have to revert your local API key every time you'd want to commit anything.

Only checks staged files for leftover API keys.

---

.circleci/config.yml
.github/workflows/trigger_all_tests.yml

Follow up to #4025 
Adds a github action to trigger all tests based on a github PR comment. 
Annoyingly, this can only be [tested once the action is in the default branch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only), the docs state: 
> Note: This event will only trigger a workflow run if the workflow file is on the default branch.
(I commented on this PR like 10 times before seeing this and didn't understand why it wouldn't fire)
This uses [CircleCI's Marketplace action for it](https://github.com/marketplace/actions/trigger-circleci-pipeline). 
I also considered [triggering via API](https://circleci.com/docs/triggers-overview/#run-a-pipeline-using-the-api), but that has one big disadvantage in that …

added new workflow to trigger all tests

---

.circleci/config.yml
.github/workflows/trigger_all_tests.yml

Fixes the trigger #4051, which had a bad pointer to the workflow from circleCI.

[Ci] Fix trigger to run all tests from github actions 

---

.circleci/config.yml

The deploy workflow didn't run correctly, because of a regression introduced in #4025 . 
The problem is that we replaced the tag filters with a `when` clause, but the job itself was relying on us using the filter and running the second part of the deploy workflow from the tag itself and not the branch. 
I.e.: it wasn't entirely a chain of jobs, rather, there were two separate chains, one for releases and one for tags, running in the same job. 
This PR splits the jobs into two parts: one that creates the tag, and one that fires when a new tag is pushed, to create a release for it

Fix release train deploy workflow

---

.circleci/config.yml

Follow-up to https://github.com/RevenueCat/purchases-ios/pull/4079, removes the `when` and re-introduces filters as the way to trigger the job since `when` doesn't seem to work for tags

Fix release release trains part 2

---

.circleci/config.yml
fastlane/Fastfile

Fix failing docs
When `Dir.mktmpdir` uses a block, the temp dir is deleted at the end of the block. Not using the block syntax anymore so the temp dir lives the entire process.
Also adds `run-manual-docs-deploy` action to trigger docs manually for easy testing since Xcode 14 can't be run on macOS Sonoma.
Docs build and published in https://github.com/RevenueCat/purchases-ios-docs/commit/56b09af83637a6e40450062e805849a04ade6043

Fix docs deploy and add manual trigger on CI

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Data/SubscriptionInformation.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift

This PR improves the presentation of the current subscription.
- Adds hierarchy to the various texts.
- Uses padding to indicate which texts belong together and which do not.
- Adds some descriptive icons.
- Adds a short explanation as to which subscription we're showing. 
- Describes the date as the "next billing date" (or date of expiry, if applicable). 
- Wraps it in a card.
This PR can be seen as a proposal. Feel free to add any suggestions!

[Customer Center] Improves the UI of the current subscription

---

RevenueCatUI/Views/FooterView.swift

This was causing issues for some developers, because the old, deprecated Alert API would fail silently if there was a view higher up in the view hierarchy which already had an Alert modifier
This in turn caused the `onRestoreCompleted` callback not to be called.
https://community.revenuecat.com/sdks-51/restore-completion-handlers-not-firing-in-presentpaywallifneeded-4674
The newer Alert API seems to not suffer from the same issue.

Use newer Alert API for showing customer restored alert

---

.circleci/config.yml
.github/workflows/trigger_all_tests.yml

This improves the permission checking logic for running github actions. We also have it setup to only run actions by organization members, but this acts as an additional check.

Fix workflow permission check logic

---

RevenueCatUI/Data/TestData.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift

It looks like some annotations `PublicForExternalTesting` got removed in https://github.com/RevenueCat/purchases-ios/pull/4022/files#diff-c458d88e52633024e0da56833bdfd34e2790a17f15a9b93ff75dfd7aec02a168, which prevented `PaywallsTester` from archiving
It was causing these errors https://github.com/RevenueCat/purchases-ios/runs/27655512796

Add missing @PublicForExternalTesting that broke PaywallsTester

---

RevenueCatUI/Data/TestData.swift

Round 2 on https://github.com/RevenueCat/purchases-ios/pull/4087. There were still some stuff not being available to `PaywallsTester` on archive

Fix PaywallsTester by changing TestData DEBUG checks

---

RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift

This is based on the changes in #3968 
This PR:
- Moves the strings currently hardcode into the `CustomerCenterConfigData.Localization` object.
- Fixes an issue compiling paywall tester introduced in a previous PR
- Modifies how we read backend strings to not account for the `common_` prefix, which is already removed by the backend.

Move No subscriptions page strings to Localization

---

Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift

macOS builds were failing when archiving, this fixes a broken API call

PaywallsTester: fix macOS build

---

Sources/Misc/Concurrency/OperationDispatcher.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

This PR performs some validations on the server-provided retry backoff period. Specifically, it:
- Defaults to a backoff interval of 0ms if Retry-After is negative
- Caps the backoff interval from the Retry-After header at a maximum of 1 hour.
- Adds tests to verify the behavior

Server Provided Backoff Interval Validation

---

Sources/Networking/HTTPClient/HTTPClient.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

The RevenueCat REST API v2's `Retry-After` header uses seconds instead of milliseconds, so we've decided to treat it as seconds to maintain consistency.
Adjusts the SDK to treat the `Retry-After` header's value as seconds instead of milliseconds.

Treat Retry-After Header As Seconds

---

Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift

These two previews were crashing due to expecting objects in the SwiftUI environments that were not added in the preview provider
Adds the two missing environment objects, tested by uploading to emerge and confirming the snapshots of these previews rendered without crashing

[External] Add missing SwiftUI environment for previews

---

Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift

These two previews were crashing due to expecting objects in the SwiftUI environments that were not added in the preview provider
Adds the two missing environment objects, tested by uploading to emerge and confirming the snapshots of these previews rendered without crashing

[External] Add missing SwiftUI environment for previews (#4109) via @noahsmartin

---

.github/workflows/trigger_all_tests.yml

The `trigger_all_tests.yml` workflow triggers for every issue comment. It doesn't check that the comment body matches "\@RCGitBot please test". 
You can see this if you check [the latest workflow runs](https://github.com/RevenueCat/purchases-ios/actions/workflows/trigger_all_tests.yml), and click a few of the comments in that list.
For example, [this run](https://github.com/RevenueCat/purchases-ios/actions/runs/10083907383) was triggered by this comment:
> This does add noise to the overall schemes in Xcode, let me know if that feels like a bit too much
Also, these workflow runs all fail. 
Checking [rhysd.github.io/actionlint](https://rhysd.github.io/actionlint/#eJx9VNtu2kAQffdXTF2ai1TbSdQnV0ghLiKobYgIeUojy6wHvI3ZdfcCpSn/3rGxCRDSN3t2zpnZM2dHJDMMYaT4dIoKOnkOI9RGO44UoQPAtbYYMzmboTBlAMAsC9QhP …

Fixes trigger_all_tests.yml triggering on every issue comment

---

Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Networking/HTTPClient/HTTPRequest.swift
Sources/Networking/Operations/PostReceiptDataOperation.swift
Tests/BackendIntegrationTests/OtherIntegrationTests.swift
Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/UnitTests/Networking/HTTPClientTests.swift
Tests/UnitTests/Networking/HTTPRequestTests.swift

This PR modifies the HTTPClient's retry logic to only perform retries on requests to the `/v1/receipts` URL path that result in a 429 status code.
- Updated existing tests to set the `isRetryable` field correctly
- Added unit tests to `HTTPClient.Request` to ensure that the `isRetryable` field is being set properly
- Wrote new unit & integration tests to ensure that we don't retry requests to unsupported endpoints (like `/v1/subscribers/identify`)

Only Retry POST Receipt Paths for 429

---

.circleci/config.yml

I realized that we weren't running the suite of tests from RevenueCatUI in every commit. 
I missed this one because the name made it seem like it was a test specific to SPM, but it's just that it could only be run through SPM at the time. 
It can now be run from Xcode, but that's a separate story, so for now this just re-adds it and clarifies the naming a bit

Re-added the RevenueCatUI tests job on every commit

---

.github/workflows/trigger_all_tests.yml

Fix trigger all tests branch (again). 
This was a pretty obvious bug - I was using the output of the `get-branch` step, but I never set the id of the step to that. 
This setup now more closely matches the [solution laid out as a github comment](https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/issues/61#issuecomment-1662021882)

Fix trigger all tests branch

---

.circleci/config.yml

[The cleanup PR](https://github.com/RevenueCat/purchases-ios/pull/4111) would actually break the release process. 
This disables it for now, but it will get re-enabled in #4131. 
The reason is that one of the steps is to upload PurchaseTester to TestFlight, which is currently broken since it's set up to build from the PurchaseTester workspace.
And that workspace won't work correctly anymore since the dependency has been updated from Swift Package Manager as a pinned commit to a local dependency instead. 
This is a lot more convenient when developing, because it means that we can just run PurchaseTester from the main workspace and it all works, but it needs some updates to our fastlane stuff to be able to reploy purchaseTester again.

temporarily disables purchasetester deploy

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ColorFromAppearance.swift
RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Data/CustomerCenterEnvironment.swift
RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
RevenueCatUI/CustomerCenter/Views/TintedProgressView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift

- Adapt changes from https://github.com/RevenueCat/khepri/pull/9707/ which makes colors nullable and adds new colors for buttons
- Change background and text color in all screens
- Modified buttons to use `.buttonStyle(.borderedProminent)` so they look native by default
- Applied accent color to back button in navigation view

[Customer Center] Make colors nullable

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

I noticed the purchase button for the promo offers is always disabled. Changing the order of the modifiers fixes it

[Customer Center] Fix for disabled promo offer button

---

RevenueCatUI/Binding+Extensions.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

The issue in the [ticket](https://linear.app/revenuecat/issue/SDK-3519/extra-blank-screen-after-back-button-on-cancel-subscription) is caused by the use of `.constant` and `.onDisappear`, which probably resulted in a timing issue where the `feedbackSurveyData` is not set to `nil` quickly enough after pressing the Back button. 
The fix in this PR is to bind directly to the `.feedbackSurveyData` property. I've added an `.isNotNil` Binding extension for this, as it seemed useful to reuse in other parts of RevenueCatUI. Let me know if the `Binding+Extensions.swift` file should be placed somewhere else instead.  
---
Closes SDK-3519

[Customer Center] Fixes an extra blank screen after popping FeedbackSurveyView on iOS 18.

---

.circleci/config.yml

Cleans up the deploy purchase tester job's treatment of `dry-run`: it's now a parameter of the job instead of a separate job entirely. 
This is based off of @tonidero and @vegaro's feedback in #4131

Deploy purchaserTester: clean up dry-run parameter

---

RevenueCatUI/Modifiers/ViewExtensions.swift

Temporary fix for https://github.com/RevenueCat/purchases-ios/issues/4150
Hopefully iOS 8 beta 6 fixes `ViewThatFits` and we can roll this back, but this should help in the meantime

Fix Paywalls crash on iOS 18 beta

---

RevenueCatUI/CustomerCenter/Views/BackwardsCompatibleContentUnavailableView.swift
RevenueCatUI/CustomerCenter/Views/CompatibilityContentUnavailableView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift

Attempting some UI polish
- Implements `ContentUnavailableView` for the views that have 'empty' content (with a visually similar backwards compatible version)
- Improves instructions for each platform for wrong-platform subscription management
| New           | Old           |
|:-------------:|:-------------:|
| ![New Version](https://github.com/user-attachments/assets/866266ae-4996-4480-b990-17bc143641fa) | ![Old Version](https://github.com/user-attachments/assets/936e7892-2d60-4b86-889b-7b1b543d729c) |

[Customer Center] UI polish for empty content

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/TintedProgressView.swift

- Uses system navigation titles instead of text views for screen titles
- Display subtitle for the manage subscriptions screen
- improves preview test data with some standard default colors
- fixes progress view tint color
| New           | Old           |
|:-------------:|:-------------:|
| ![New Version](https://github.com/user-attachments/assets/2af439cf-a536-4930-bdd4-afc308bd100d) | ![Old Version](https://github.com/user-attachments/assets/5e53044c-e65d-4953-9faa-fd2217e6b84f) |

[Customer Center] Use system navigation titles

---

RevenueCatUI/Modifiers/ViewExtensions.swift

Since iOS version cannot change at runtime, we can make it a stored variable so we only compute it once.

[Paywalls] Make iOS version calculation lazy

---

fastlane/Fastfile

Customer Center is currently `#ifdef`ed out via `CUSTOMER_CENTER_ENABLED` while it is under development, but we want to run its tests during development.  This defines `CUSTOMER_CENTER_ENABLED` for `OTHER_SWIFT_FLAGS` via the command line build arguments for test lanes, which will override the project settings, so the tests are run.
This PR can be reverted when the customer centre is released.
‼️This PR is not needed if we go for the [source-processing method](https://github.com/RevenueCat/purchases-ios/pull/4170) instead.

Enable customer center tests

---

RevenueCatUI/Modifiers/ViewExtensions.swift

The issue has been fixed in iOS 18.1 beta 2 / iOS 18 beta 6.
Original PR: https://github.com/RevenueCat/purchases-ios/pull/4154

Revert workaround for iOS 18 beta 5 SwiftUI crash

---

RevenueCatUI/CustomerCenter/ColorFromAppearance.swift
RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift

Small refactor that replaces the color(from colorInformation:) global it with internal extension. 
The idea is to keep the global namespace cleaner. Also it feels a bit neater to be able to find it through Color.

replace `color(from colorInformation:)` global with extension

---

.circleci/config.yml
Tests/InstallationTests/CarthageInstallation/fastlane/Fastfile

Speeds up carthage installation tests by reducing the amount of work that they do. 
It almost halves the execution time:
| :-: | :-: |
| <img width="812" alt="Screenshot 2024-08-14 at 12 05 07 PM" src="https://github.com/user-attachments/assets/5d124805-feaa-46e4-b35a-a5ce1e30e0e1"> | <img width="512" alt="Screenshot 2024-08-14 at 12 30 54 PM" src="https://github.com/user-attachments/assets/535d2792-ae8c-4a1c-8158-c75f90f487c3"> |

Speed up carthage installation tests

---

.circleci/config.yml
RevenueCat.xcodeproj/project.pbxproj
fastlane/Fastfile

Follow up to https://github.com/RevenueCat/purchases-ios/pull/4172
Adds the xcframework as a circleci artifact
Also fixes a code signing issue when archiving `RevenueCatUI.xcframework`
linear ticket: SDK-3555

XCFramework artifacts in CircleCI

---

fastlane/Fastfile
fastlane/README.md

This lane will do the cherry pick command that enables the customer center, without the need to check the commit hash

Create lane to enable customer center

---

.circleci/config.yml
RevenueCat.xcodeproj/project.pbxproj

The official docs don't say a lot about `SKIP_INSTALL`, but I missed the mark during the #4172 PR, where the ideal setup is  NO for debug, YES for release. I spent a lot of time figuring this out a couple of years back but the other day I completely forgot about it 🤦 
Here's ChatGPT's far better explanation than Apple's: 
```
•	Debug Configuration:
•	SKIP_INSTALL = YES
•	During development, you typically don’t need to install (or include) the product (e.g., .framework, .app) in the final build output. The focus is on quick builds, so setting SKIP_INSTALL = YES can help speed up the process by skipping unnecessary steps.
•	Release Configuration:
•	SKIP_INSTALL = NO
•	In the Release configuration, you usually want to include everything in the final build output. This is particularly …
```

Fix the setting for SKIP_INSTALL in Xcode project

---

RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift

I noticed the Contact Support button wouldn't work in cases when the email URL is nil, like for example in simulators that don't have Mail app.
I improved the alert a little bit to hide the Contact Support button for those cases.

[Customer Center] Hide Contact Support button if URL can't be created

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CompatibilityContentUnavailableView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginScreen.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingButton.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallForID.swift

Updates the target of Paywalls Tester to iOS 15 so that we can test RevenueCatUI easily.

Set Paywalls Tester deployment target to iOS 15

---

Tests/RevenueCatUITests/Helpers/TestCase.swift

There's a new release of Swiftlint 0.56.2 that makes one of our `unneeded_override` disables obsolete
https://github.com/realm/SwiftLint/releases/tag/0.56.2
From the changelog:
> Silence unneeded_override rule on methods and initializers with attributes.

Remove `unneeded_override` disable to fix linter

---

RevenueCatUI/CustomerCenter/ButtonStyles.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift

For some reason, the dismiss environment variable was causing the view to constantly recreate, which was causing a loop when trying to launch the feedback survey view, and the app would freeze.
I moved the `dismiss` to the `DismissCircleButton` and looks like it has solved it.

[Customer Center] Fix `FeedbackSurveyView` not opening

---

Sources/Misc/SandboxEnvironmentDetector.swift
Tests/UnitTests/Misc/SandboxEnvironmentDetectorTests.swift

Alternative approach to #3875, also meant to address https://github.com/RevenueCat/purchases-ios/issues/3871
We're currently looking at a field called Environment in the local receipt to check whether the app is running in sandbox on macOS. 
However, since it's an undocumented field, we can't trust that it will always be there, so if the value is production then we check the bundle's signature, which can be slow to run. 
This PR changes that behavior so that we only perform that check if the value for that variable isn't available, which would cause a receipt parsing failure since it's marked as non-optional. 
Still need to write tests for this, but it should be significantly easier than for the other PR.

fix mac os sandbox check slowness

---

Package.swift
Package@swift-5.7.swift
Package@swift-5.8.swift

Pins swift-docc-plugin for the time being as 1.4.0 and 1.4.1 are failing to compile (https://revenuecat.slack.com/archives/C03HPN9UE80/p1724438146087079).

Pin swift-docc-plugin to 1.3.0

---

Sources/Info.plist
Tests/BackendIntegrationTestApp/Info.plist
Tests/BackendIntegrationTests/Info.plist
Tests/UnitTests/Info.plist
Tests/UnitTestsHostApp/Info.plist

I am unsure why (paths look correct) but the plist files had the wrong version number. My theory is that the previous release was manual and someone might have forgotten to update these.

Fix version number in plist files

---

RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift

| ![simulator_screenshot_1D4B17FD-B4FE-4F00-BC80-B9A2428EA757](https://github.com/user-attachments/assets/420291bc-45cf-4d91-9dc7-82fdca13c733) | ![simulator_screenshot_4B84F02B-2296-47A9-B5B1-2649A0778289](https://github.com/user-attachments/assets/5cd2c5e3-dc7b-476d-9d6b-49e89b010600) |

[Customer Center] Add padding to `No thanks` in promotional offer screen

---

Sources/Misc/SystemInfo.swift
Sources/OfflineEntitlements/OfflineEntitlementsManager.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift

This shouldn't display "enabled" for custom entitlements computation: ![Screenshot 2024-08-23 at 09 16
17](https://github.com/user-attachments/assets/57e0bb0a-8cf3-4755-a7d9-d1444383b9fa)
Contributed by @NachoSoto in #4215

[EXTERNAL] `Custom Entitlements Computation`: fix support display on debug screen (#4215) by @NachoSoto

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

The sheet was being created multiple times and we realized it was due to it being created from the buttons instead of from the view `ManageSubscriptionsView` itself
We moved the creation of the sheet and the restore alert to the `ManageSubscriptionsView` to fix it

[CustomerCenter] Move sheet and restore alert creation to `ManageSubscriptionsView`

---

RevenueCatUI/View+PresentPaywall.swift
RevenueCatUI/View+PresentPaywallFooter.swift

`restoreStarted` callback was not being fired on `presentPaywallIfNeeded` when using `requiredEntitlementIdentifier`
We weren't doing anything with the `restoreStarted` argument 🤦‍♂️ Now its getting passed along and gets called 💪 
**BONUS:** Fixed two more that were missing in the footer (thanks @jamesrb1 🙌 )
⚠️ We don't _really_ have a great way to test this right now 😬 All of our existing tests use the call some internal things so we can pass mocked customer info and intro eligibility checkers. So this didn't get caught earlier because its one level above those internal methods that do most of the testing.

[Paywall] Fix restoreStarted not being called on `presentPaywallIfNeeded` when using `requiredEntitlementIdentifier`

---

RevenueCatUI/CustomerCenter/Views/CompatibilityTopBarTrailing.swift
Tests/APITesters/AllAPITests/SwiftAPITester/CustomerCenterConfigDataAPI.swift

Build was broken in MacOS, see https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/21833/workflows/1a159a1e-994a-4ed6-bbe2-e7b64203a0ce/jobs/254514
Also API tests

Fix `compatibleTopBarTrailing` in MacOS and api tests

---

.circleci/config.yml

We are not sure why but iOS 15 tests get sometimes stuck re-running forever (see https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/21864/workflows/7af8697c-aad3-4e1f-92ae-f55186a72f27/jobs/254961). It looks like rerunning fixes it.
Until we find out what's up, we are going to set a max time for this job. CircleCI recommends setting a sleep and calling an API to cancel the job when that finishes https://support.circleci.com/hc/en-us/articles/14114124583195-How-to-set-a-custom-maximum-job-duration

Set a maximum duration for iOS 15 tests

---

RevenueCatUI/CustomerCenter/Views/CompatibilityContentUnavailableView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift

Build `WrongPlatformView` using Strings from the JSON
Cleaned up the view as well so the logic is simpler and looks cleaner

[Customer Center] Build `WrongPlatformView` from JSON

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/Networking/HTTPClientTests.swift

This adds the `backend_error_code` property to diagnostics `http_request_performed` events.

[Diagnostics] Add `backend_error_code` property

---

RevenueCat.xcodeproj/project.pbxproj

This should fix #4250 by marking RevenueCat.framework as Do not embed in RevenueCatUI

Do not embed `RevenueCat.framework` in `RevenueCatUI`

---

Sources/Purchasing/Purchases/Attribution.swift
Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
Sources/SubscriberAttributes/SubscriberAttributesManager.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCAttributionAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/AttributionAPI.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/SubscriberAttributesView.swift
Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

This adds a new API `setKochavaDeviceId` that allows to set the kochava device ID required for the Kochava integration. 
Keeping on hold until backend support is added

Add `$kochavaDeviceId` attribution convenience method

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

The AdServicesToken wasn't being sent to the the post receipt endpoint when syncing purchases, but was marking it as synced, so better to remove it altogether.
Removed usage of adServicesToken in syncPurchases.
The diff is a mess even in split mode. The changes are the same in the `syncPurchasesSK1` and `syncPurchasesSK2` methods:
- The following line was removed:
```
self.attribution.unsyncedAdServicesToken { adServicesToken in
```
- The `adServicesToken` parameter was changed to nil:
```
adServicesToken: nil
```

Remove usage of adServicesToken in syncPurchases

---

.github/ISSUE_TEMPLATE/bug_report.md

Version 5.X of the SDK introduced changes to the default StoreKit version used to process purchases and changes to how developers can override the StoreKit version used by the SDK. This PR updates the GH Issue template to reflect these changes.
- Marks StoreKit2 as enabled by default, since that's the new default in SDK versions >=5.0.0.
- Updates the comments related to the StoreKit versions to reflect:
- The default StoreKit versions used on SDK versions <5.X and >=5.X
- The code used to override the StoreKit version in version >5.X of the SDK.
This should be merged at some point, but we may want to hold off until the 5.X SDKs have a larger adoption. I'm open to thoughts here!

Update StoreKit Version Info in GitHub Issues Template

---

RevenueCatUI/Helpers/Package+VariableDataProvider.swift
Tests/RevenueCatUITests/Data/PackageVariablesTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Products.storekit

`{{ sub_period }} ` was returning package identifier when using custom package names
Look at the `StoreProduct` periods to determine the period length first 😁

[Paywalls] Use store product for `{{ sub_period }}` duration

---

Sources/Purchasing/Purchases/Purchases.swift

Updates the deprecation message of `allowSharingAppStoreAccount` to tell people who are already using the field to continue using it and not remove it.

Update allowSharingAppStoreAccount deprecation message

---

Sources/FoundationExtensions/AsyncExtensions.swift
Sources/Misc/Concurrency/Purchases+async.swift
Sources/Purchasing/ReceiptFetcher.swift
Tests/BackendIntegrationTests/Helpers/ExternalPurchasesManager.swift
Tests/BackendIntegrationTests/Helpers/SK1ProductFetcher.swift
Tests/RevenueCatUITests/ImageLoaderTests.swift
Tests/RevenueCatUITests/Purchasing/PurchaseHandlerTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Helpers/ProductFetcherSK1.swift

iOS 18 introduces a bug in Swift that causes calls to `withCheckedThrowingContinuation` to crash in certain scenarios. This PR provides some promise in addressing this issue, documented in https://github.com/RevenueCat/purchases-ios/issues/4177
This PR replaces all calls to `withCheckedThrowingContinuation` to `withUnsafeThrowingContinuation`, which we're unable to reproduce the issue with.
`withUnsafeThrowingContinuation` doesn't provide any checking to ensure that the continuation isn't called multiple times, so this is something we'll need to be aware of going forward. Luckily, all existing usages of `withCheckedThrowingContinuation` were in just a few files and in small functions, so this is easy to check manually for now.

Replace withCheckedThrowingContinuation Calls With withUnsafeThrowingContinuation

---

Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Identity/CustomerInfoManager.swift
Sources/Networking/HTTPClient/HTTPClient.swift
Sources/Purchasing/ProductsManager.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/Mocks/MockOperationDispatcher.swift

Before this, callers of the diagnostics `track` methods had to handle concurrency and offloading the work to a background thread. This moves the work inside the `DiagnosticsTracker`, which makes the methods non-async anymore.

[Diagnostics] Refactor diagnostics track methods to handle background work automatically

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterAction.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift

- Noticed the public init contained `CustomerCenterConfigData.Localization` and `CustomerCenterConfigData.Appearance`
- Improved public docs

More customer center docs and fix init

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Views/ErrorDisplay.swift

As the title says, and as discussed on Slack. This is needed for https://github.com/RevenueCat/purchases-kmp/issues/217.

Adds an `onDismiss` callback to `ErrorDisplay`

---

RevenueCatUI/UIKit/PaywallViewController.swift

We got a report of duplicated callbacks in Flutter when using the Paywall view in iOS
We pinpointed the issue to the `update(with:` methods, that create a new controller. 
It turned out, the `didSet` function of `hostingController` was calling `loadView` when adding the `subView`, and the `PaywallViewController` ended up having two `PaywallContainerView`. Since each of these views was being set as delegates for the callbacks, Flutter ended up getting two callbacks for the `PaywallView` interactions.
After a lot of attempts, I ended up fixing it by replacing the `loadView` with `viewDidLoad` and ensuring we don't create a new controller there. `viewDidLoad` will be called from the `addSubView` but it won't recreate a new controller since it checks it already has one.
I've tested this both …

Fixes double callbacks when using `PaywallViewController`

---

RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
RevenueCatUI/Data/Strings.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Products.storekit

- Improved debug logs for promotional offer view
- Updated SKConfig file to add a promotional offer
- Updated SKConfig file storefront to en_US

Better logs for promotional offer view

---

RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift

There was a warning caused by accessing the `Localization` environment variable from outside a View
```
Accessing Environment<Localization>'s value outside of being installed on a View. This will always read the default value and will not update.
```

Remove access to Localization env variable in ManageSubscriptionsViewModel

---

.gitignore
Local.xcconfig.SAMPLE
RevenueCat.xcodeproj/project.pbxproj

This PR adds a `Local.xcconfig` file that can be used to enable various build settings, such as the `PAYWALL_COMPONENTS` flag or any other future flag. It's added to `.gitignore`, so these settings only affect local builds. 
This allows for a workflow similar to Gradle's `local.properties`. Personally I like this workflow, as it avoids having to find options in Xcode's GUI, which also result in changes in Xcode's project files (which we should be careful not to commit). 
Note that the original workflow of changing compiler flags in Xcode's GUI still works with this PR. It just adds another option.
There's a new `Local.xcconfig.SAMPLE` file, in similar vein as the `fastlane/.env.SAMPLE` file. This file should be copied by the developer, removing the `.SAMPLE` extension. Then, any desired …

Allows enabling PAYWALL_COMPONENTS using a Local.xcconfig file.

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

We were displaying paths with unknown type and just ignoring the button when tapped. This is not a problem right now but might be in the future.
We might also want to move this processing to the view model or something but wanted to fix the issue separately for now.

[CustomerCenter] Hide unknown paths

---

RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift

Reported in https://github.com/RevenueCat/purchases-ios/issues/4335
- Adds a loading to the button
- Disables the button when pressed to prevent multiple presses
https://github.com/user-attachments/assets/c0ae8189-9e5a-4e58-b209-3a1f9fdddf8b

Improve promotional offer button when pressed

---

Sources/Support/StoreMessagesHelper.swift
Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift

Currently, when a developer attempts to show deferred StoreKit messages, all pending messages are removed from the list—regardless of their type—even if they haven't been displayed. This leads to a bug where, if a developer intends to display only a specific subset of message types, all messages are incorrectly marked as shown. As a result, subsequent calls to showStoreMessages() fail to display the messages that were initially skipped.
This PR addresses the issue by retaining any messages that don't match the specified types, allowing them to be displayed in future calls to showStoreMessages().
Added a unit test to cover this scenario.

Only Treat Deferred StoreKit Messages as Shown When They are Shown

---

Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift

iOS 14 tests are failing with:
```
❌  /Users/distiller/purchases-ios/Sources/Purchasing/StoreKit1/ProductsFetcherSK1.swift:259:5: unexpected platform condition (expected 'os', 'arch', or 'swift')
#if hasFeature(RetroactiveAttribute)
^
```
see https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/22627/workflows/1c541690-3b85-4aa2-ad9e-dc7f15ada779/jobs/262246/steps
I think adding a swift compiler check would fix this, but seeing this issues I realized we should maybe change the check to `#if $RetroactiveAttribute`
https://github.com/swiftlang/swift/issues/69643
https://forums.swift.org/t/hasattribute-only-supports-declaration-attributes/68202

Fix `hasFeature(RetroactiveAttribute)` check in iOS 14

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift

#4356 reported that `No Thanks` wasn't getting the correct Accent color.
After digging into it a bit more, I realized that the accent color wasn't being set at all in the Customer Center. I pin pointed it to a regression in the constructor of `CustomerCenterView`, where the appearance was always being set to the defaults

Fix setting accent color in Customer Center

---

.gitignore

As discussed in the weekly, this adds the `.index-build` folder to `.gitignore`. 
From some exploratory testing, I have concluded that it is caused by the combination of Cursor and the sswg Swift extension. Some observations from opening the project in various editors: 
| Editor | `.index-build` created |
|---------------|-----------------|
| Xcode 16 | ❌ |
| VS Code without Swift extension | ❌ |
| VS Code with Swift extension | ❌ |
| Cursor without Swift extension |  ❌ |
| Cursor with Swift extension | ✅ |

Adds `.index-build` to `.gitignore`.

---

RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift

Reported at #4355 
| ![simulator_screenshot_B4FBE7C3-1F7A-4936-A6AD-D17D0DE808DE](https://github.com/user-attachments/assets/485479f2-4452-4fd0-9b1f-af70c21633b4) | ![simulator_screenshot_5A03972A-D677-4AE4-A652-B3780AA5A388](https://github.com/user-attachments/assets/c34469cd-8dac-4563-b5a9-a7072c4ce633) |

Better spacing in `PromotionalOfferView`

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift

The `SubscriptionDetailsView` has 2 different background colors in dark mode.
The fix is to remove the entire background color from `SubscriptionDetailsView`. The `Section` in which the `SubscriptionDetailsView` is placed by `ManageSubscriptionsView` already sets the correct background color. 
Added dark mode previews to `SubscriptionDetailsView` and `ManageSubscriptionsView` to more easily catch these issues.
Closes #4335.

Fixes `SubscriptionDetailsView` background color in dark mode

---

Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift

We added a new case in the backend for path types, and current code in the SDK fails to decode unknown values.
We need to handle unknown values and also make sure these new values are not sent down by the backend for versions that break with unknown values.

Add default values to enums in Customer Center config response

---

RevenueCat.xcodeproj/project.pbxproj

This PR intends to fix errors like: 
```
error: Multiple commands produce '/Users/distiller/Library/Developer/Xcode/DerivedData/RevenueCat-etwwovrsjatlsobqeniqyhgbqoaq/Build/Intermediates.noindex/RevenueCat.build/Release-iphonesimulator/RevenueCatUI.build/Objects-normal/arm64/PurchaseButtonComponentView.stringsdata'
```
It removes these broken references in `project.pbxproj`:

Fixes broken references in project.pbxproj.

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/Templates/Components/Button/ButtonComponentView.swift
RevenueCatUI/Views/SafariView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift

This allows to specify paths with custom URLs in the manage subscriptions view which can be opened either externally or in_app as a bottom sheet.
`IN_APP`:
https://github.com/user-attachments/assets/2767eb64-c645-4f52-882c-d88233702287
`EXTERNAL`: 
https://github.com/user-attachments/assets/8ecfa3c4-9fa7-4c3f-8fb7-61fd76c8a803

Support custom URL paths in `ManageSubscriptionsView`

---

Package@swift-5.7.swift
Package@swift-5.8.swift
Tests/APITesters/AllAPITests/SwiftAPITester/CustomerCenterConfigDataAPI.swift

```
❌ /Users/distiller/purchases-ios/Tests/UnitTests/Mocks/MockHTTPClient.swift:98:13: ambiguous use of 'assertSnapshot(matching:as:named:record:timeout:file:testName:line:)'
assertSnapshot(matching: call,
^
```
We were getting that issue only in iOS 14 and iOS 15. @JayShortway noticed the version of `swift-snapshot-testing` might differ because of the how we set the version of the library in the Package.swift files

Fix iOS 15, 14 tests using wrong version of `swift-snapshot-testing` and API tests

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ContactSupportUtilities.swift
RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift

This adds some default information to the support emails when contacting them

[CustomerCenter] Add default info to support emails

---

README.md

This installation tip is [easy to miss](https://community.revenuecat.com/sdks-51/swift-package-takes-hours-to-download-5318), which costs developers a lot of time.
Adds a callout format for the SPM installation tip.

adds callout to SPM installation tip for visibility

---

Sources/CustomerCenter/CustomerCenterConfigData.swift

@tonidero I noticed you added this in [#release](https://github.com/RevenueCat/purchases-ios/pull/4391/commits/d9c1e49a67f123263fbb02e5522d41edd9a2fb4f)
Adding as a separate PR before I trigger the release again

Default URL to nil in CustomerCenter HelpPaths

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/Components/Button/ButtonComponentView.swift
RevenueCatUI/Templates/Components/Button/ButtonComponentViewModel.swift
Sources/Paywalls/Components/PaywallButtonComponent.swift
Sources/Paywalls/Components/PaywallStackComponent.swift
Tests/UnitTests/Paywalls/Components/ButtonComponent.swift

The `ButtonComponent` had great looking enums but I just realized that they wouldn't codable the JSON structure that we want them too.
Previously...
```json
{
"type": "button",
"action": {
"navigateTo": {
"destination": {
"privacyPolicy": {
"urlLid": "https://example.com/privacy-policy",
"method": "externalBrowser"
}
}
}
},
"stack": {
"type": "stack",
"components": []
}
}
```
Now...
```json
{
"type": "button",
"action": {
"type": "navigate_to",
"destination": "privacy_policy",
"url": {
"urlLid": "https://example.com/terms-of-service",
"method": "deepLink"
}
},
"stack": {
"type": "stack",
"components": []
}
}
```

Improved JSON format for ButtonComponent codables

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/Components/ShadowModifier.swift
RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Sources/Paywalls/Components/PaywallStackComponent.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift

As the title says. I was initially going to build this just for the sticky footer, but I noticed on Figma that any stack can have a shadow, hence this PR.
Applied to the sticky footer, it looks like this:

The StackComponent has an optional shadow

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/UnitTests/Mocks/MockNotificationCenter.swift
Tests/UnitTests/Paywalls/Events/PurchasesPaywallEventsTests.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

Right now we are only sending events when the app moves to the foregound. Sending events with backgrounding will help us record impression events that might happen when a user installs an app, opens it, proceeds to uninstall it or never use it again. Additionally, we try to sync events after a successful purchase.

[Paywalls] Send paywall events when the app is backgrounded and after a successful purchase

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/Components/PaywallComponentTypeTransformers.swift
RevenueCatUI/Templates/Components/Stack/FlexHStack.swift
RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/Components/TemplateComponentsView.swift
RevenueCatUI/Templates/Components/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/Components/TemplateComponentsViewPreviews/Template5Preview.swift
RevenueCatUI/Templates/Components/Text/TextComponentView.swift
Sources/Networking/Responses/OfferingsResponse.swift
Sources/Paywalls/Components/Common/Dimension.swift
Sources/Paywalls/Components/Common/PaywallComponentBase.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Sources/Paywalls/Components/PaywallPackageComponent.swift
Sources/Paywalls/Components/PaywallTextComponent.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift

Fixes for paywall tester for Paywalls V2
- Added `@frozen` to all the enums to get rid of Swift 6 warnings
- New `FlexHStack` to support horizontal `distribution`
- Fixed a width bug with `LazyVStack`
- `LazyVStack` is used to make rendering a bit snappier feeling but it has issues with width sometimes
- It was behaving as `maxWidth: .infinity` so added some naive logic to only use `LazyVStack` if more than 3 children. Ideally this should look recursively down  
- Temporarily removed the error in the paywall if there are no packages (because it makes initial testing of paywall designs hard)
- Could maybe only show a warning when in debug
- Fixed a bunch of `Codable` things that were failing when testing real life paywalls
| Blinkist | HabitKit |
| ![Simulator …

Fixes for paywalls v2 renderer after testing some real life paywalls

---

Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/ErrorCodesAPI.swift
Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/StoreProductDiscountAPI.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesErrorCodeAPI.m
Tests/APITesters/AllAPITests/ObjcAPITester/RCStoreProductDiscountAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/ErrorCodesAPI.swift
Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
Tests/APITesters/AllAPITests/SwiftAPITester/StoreProductDiscountAPI.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesWinBackOfferTests.swift

This PR addresses a few issues with some tests that aren't normally covered by the `build-test` workflow. 
Specifically, it addresses two issues:
- The async version of `fulfillment()` wasn't introduced until Xcode 13/Swift 5.5/iOS 15. This PR removes the affected tests from compilation on Swift compiler versions <6.0. This won't affect our test coverage of the win-backs feature since win-backs aren't available on iOS versions below 18.
- Adds a few items from https://github.com/RevenueCat/purchases-ios/pull/4431 to the Obj-C and Swift API testers

Fix winback tests on iOS 14 & API Tester

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/Components/Packages/Package/PackageComponentView.swift
RevenueCatUI/Templates/Components/SizeModifier.swift
RevenueCatUI/Templates/Components/Stack/FlexVStack.swift
RevenueCatUI/Templates/Components/Stack/JustifyContent.swift
RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/Components/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/Components/TemplateComponentsViewPreviews/Template5Preview.swift
Sources/Paywalls/Components/Common/Dimension.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Sources/Paywalls/Components/PaywallStackComponent.swift

Update stack size per spec
All basic components (text, image, and stacks) gained a size property. It allows their `width` and `height` to be either `fit`, `fill`, or `fixed`
This is the implementation for `StackComponent` and `StackComponentView`
- Replaces `width` with `size`
- New `.size(Size)` view modifier that applies these width and height settings and can be used by other components
- Added new `FlexVStack` (similar to `FlexHStack`) which wasn't added before 🤷‍♂️ 
https://github.com/user-attachments/assets/72652503-f7a6-4507-bd24-fce079c8ea85

[Paywalls V2] Update stack size spec

---

RevenueCatUI/Templates/Components/Image/ImageComponentView.swift
RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift

Adds size class, selection state, and intro offer overrides to image
See #4476 for more info

[Paywalls V2] Update Image to handle property overrides

---

Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh

[Paywalls V2] Enable PAYWALL_COMPONENTS compiler flag when building PaywallTester in Xcode Cloud

---

Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift

Make Paywalls Tester build again
Add `#if PAYWALL_COMPONENTS` around new logic for displaying if a paywall has an error in it

Fix Paywalls Tester when not being built with Paywalls V2

---

Package.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh

Building Paywalls Tester was failing on Xcode Cloud and it also needed to be enabled for Paywalls V2
Paywalls Tester and the RevenueCat and RevenueCatUI frameworks needed to get the `PAYWALL_COMPONENTS` flag in different ways. Not sure why its works locally (before this change) but not on Xcode Cloud 🤦‍♂️ 
- Paywalls Tester will get the `PAYWALL_COMPONENTS` flag from `Local.xcconfig`
- RevenueCat and RevenueCatUI will get the `PAYWALL_COMPONENTS` flag by replacing a commented out string in `Package.swift` with `.define("PAYWALL_COMPONENTS")` 
It's not great but it works and we can do something different later

Enable Paywall Tester to build with Paywalls V2

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

Cleans up the flow a bit, so the feedback survey is closed after picking an option and doesn't stay there after cancelling a subscription
This is needed to be able to send the selected feedback survey option to the backend as event.

Close feedback survey after picking an option

---

Sources/Misc/Concurrency/Purchases+async.swift
Sources/Networking/Responses/CustomerInfoResponse.swift
Sources/Purchasing/Purchases/PurchaseParams.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Sources/Purchasing/StoreKitAbstractions/WinBackOffer.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
Tests/BackendIntegrationTests/BaseStoreKitIntegrationTests.swift
Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK1Tests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorSK2Tests.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Offerings/OfferingDetailView.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/PurchaseParamsTests.swift

This is a follow-up PR to https://github.com/RevenueCat/purchases-ios/pull/4485, which does the following:
1. Makes the PurchaseParams functionality publicly available by removing the `ENABLE_PURCHASE_PARAMS` compiler flag checks
- Note: The PurchaseParams functionality is not available if the `ENABLE_CUSTOM_ENTITLEMENT_COMPUTATION` flag is used
2. Make the functions to fetch & redeem eligible win-back offers public
3. Makes the new transaction metadata functionality public
This PR is based off of the `purchase-params-api-enhancements` PR to keep the PR size down. [The PR for that branch](https://github.com/RevenueCat/purchases-ios/pull/4485) should be reviewed first.

Make purchase params & winback functions public

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionInformationFixtures.swift
Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift

There's a new `product_mapping` field in the `promotional_offer` JSON object. This map is more specific on which offer to load. This mapping will be configurable with the new UI, but we should still support the old `ios_offer_id` in case the developer has not configured a mapping yet.

Add support for `product_mapping` in promotional offers

---

Sources/OfflineEntitlements/PurchasedSK2Product.swift
Tests/StoreKitUnitTests/OfflineEntitlements/CustomerInfoOfflineEntitlementsStoreKitTest.swift

I have seen that `beCloseToDate()` / `beCloseToNow()` is one of our sources of flakiness. For instance, see the last test [here](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/22711/workflows/611f9df0-7cef-4abe-a622-c64cb5e97f97/jobs/263013/tests). A hiccup in the CI server, an extra background process, a little bit more heat in the CircleCI data center, and things can take a fraction longer, causing this to fail.
This PR makes the tests deterministic, by defining the exact date we expect. It only tackles `CustomerInfoOfflineEntitlementsStoreKitTest.verifyEntitlement()` for now. More to come in later PRs.

Fighting flakiness: no longer uses `beCloseToDate` in `CustomerInfoOfflineEntitlementsStoreKitTest.verifyEntitlement`

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/PaywallView.swift
RevenueCatUI/Templates/Components/PackageContext.swift
RevenueCatUI/Templates/Components/PackageValidator.swift
RevenueCatUI/Templates/Components/Packages/Package/PackageComponentView.swift
RevenueCatUI/Templates/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
RevenueCatUI/Templates/Components/PreviewHelpers/PreviewMock.swift
RevenueCatUI/Templates/Components/ScreenCondition.swift
RevenueCatUI/Templates/Components/TemplateComponentsView.swift
RevenueCatUI/Templates/Components/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/Components/TemplateComponentsViewPreviews/Template5Preview.swift
RevenueCatUI/Templates/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Views/LoadingPaywallView.swift

Process the same [Paywalls V1 variables](https://www.revenuecat.com/docs/tools/paywalls/creating-paywalls#variables) but in the Paywalls V2 text component
- Renamed `PaywallState` to `PackageContext`
- Stored on the paywall to store the "selected package"
- Renamed because this is now used by the `TextComponentView` to get the any type of package context
- Could be because text is INSIDE `Package` component
- Could be because text is OUTSIDE `Package` component (like a CTA) and needs to get the selected package
It works 👇

[Paywalls V2] Process variables in the text component

---

RevenueCatUI/Templates/Components/Button/ButtonComponentView.swift
RevenueCatUI/Templates/Components/Button/ButtonComponentViewModel.swift
RevenueCatUI/Templates/Components/Image/ImageComponentView.swift
RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentViewModel.swift
RevenueCatUI/Templates/Components/Packages/Package/PackageComponentView.swift
RevenueCatUI/Templates/Components/Packages/Package/PackageComponentViewModel.swift
RevenueCatUI/Templates/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/Components/TemplateComponentsView+Extensions.swift
RevenueCatUI/Templates/Components/TemplateComponentsView.swift
RevenueCatUI/Templates/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/Components/ViewModelFactory.swift

Needed to pass locale into view models so might as well pair it with the localized strings 🤷‍♂️ 
This just replaces all `PaywallComponent.LocalizationDictionary` with `LocalizationProvider`
A `LocalizationProvider` contains:
- `PaywallComponent.LocalizationDictionary` 
- `Locale`
It didn't _really_ make sense to just add `Locale` as another parameter into the whole chain so grouped them together in `LocalizationProvider`

[Paywalls V2] Introduce new `LocalizationProvider` for localized strings and locale

---

LICENSE

My mom sent me a screenshot of our license page she saw in an app she was using because she's so proud of me but I realized that the copyright still said 2017 (c) Jacob Eiting, so I updated it.

[FIX] Update License Copywrite

---

RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/ViewHelpers/SizeModifier.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift

So far, we were setting the alignment in the H/VStack initialiser, but that affects the alignment of the children items relative to each other. In order to affect their alignment with respect to their container, we need to apply the `.frame(alignment:)` modifier as well.

[Paywalls] Fix stack alignment issues by applying frame alignment to the size modifier

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

While investigating another issue, we noticed we were not passing `transactionData` to `handleReceiptPost` in `syncPurchasesSK2`.
The only place it's used down the line is here when re-caching the paywall in case of a failure, but this cannot happen since `syncPurchases` would never have an associated paywall.
https://github.com/RevenueCat/purchases-ios/blob/c85c6ecb62c32e7a94c9f58ae10d073551a860d3/Sources/Purchasing/Purchases/PurchasesOrchestrator.swift#L1413
Regardless, we can fix it just in case we want to use `purchaseData` down the line in the future for other reasons.

Pass transactionData to handleReceiptPost in syncPurchasesSK2

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Data/SubscriptionInformation.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
RevenueCatUI/Data/CustomerInfoFixtures.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionInformationFixtures.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionInformationTests.swift

| Header | Header |
| Lifetime (there's an entitlement and a non subscription) | ![simulator_screenshot_B11812CC-D3EA-4320-8E48-8AAD5F16E810](https://github.com/user-attachments/assets/038260bd-4c10-47ee-aadb-09935cebd651) |
| Monthly + Lifetime: displays lifetime because the entitlement is assigned to the Lifetime. We should display the monthly information but we are missing CustomerInfo information | !![simulator_screenshot_B11812CC-D3EA-4320-8E48-8AAD5F16E810](https://github.com/user-attachments/assets/038260bd-4c10-47ee-aadb-09935cebd651) |
| Base case monthly assigned to an entitlement | ![simulator_screenshot_40CA9FE8-DB93-4591-9253-CFAAC015AB43](https://github.com/user-attachments/assets/b015ea42-7e94-4675-9f57-5c96f0a4bb20) |

Add lifetime support to the Customer Center

---

RevenueCatUI/Templates/V2/Components/Stack/FlexHStack.swift
RevenueCatUI/Templates/V2/Components/Stack/FlexVStack.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift

Cramped three related things together in this PR:
- **Set the min length of `Spacer` to zero:** otherwise, there is a minimum size that depends on the platform but it's > 0 and could make a view overflow its parent if has fixed size and the sum of its child views + spacers exceeds it.
- **Removed usages of `LazyVStack` and `LazyHStack`:** they cannot have a child view with width/height type `fill` because the lazy rendering makes it impossible to know how much space they can occupy. There is not much potential for performance wins since the paywalls should be static and not have a lot of scrolling.
- **Fixed alignment issues to make rendering the view below possible:**
3 alignments are needed to achieve this layout:
1- Align green box to the top of the red box
2- Align yellow boxes to the …

[Paywalls] Remove lazy stack usages and fix alignment issues

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
RevenueCatUI/Templates/V2/ViewHelpers/ForegroundColorScheme.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
RevenueCatUI/Views/GradientView.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift

This PR adds support for gradient backgrounds.
Supported gradient types are Radial and Linear.
Additionally, gradients as text foreground style are now supported:

[Paywalls] Add support for gradient backgrounds

---

RevenueCatUI/Resources/fi.lproj/Localizable.strings

Better translations provided by a customer. Internal ticket 48413.
"Restore" > Palauta 
"Restore Purchases" > Palauta ostot
"Purchases restored successfully!" Ostot palautettu onnistuneesti

Paywalls: Update Finnish "restore" localization

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - Live Config.xcscheme
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - SK config.xcscheme
Tests/TestingApps/PaywallsTester/PaywallsTester.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests/TestingApps/PaywallsTester/PaywallsTesterTests/PaywallsTesterTests.swift

Adds a preview snapshot test to locally generate and debug snapshots from previews. This can be used along with EmergeTools snapshot testing whenever you need to debug a snapshot locally.
Adds the previews snapshot swift package and a new test target that renders all Xcode previews in the app
This also caught a bug with a crashing preview, which I fixed in https://github.com/RevenueCat/purchases-ios/pull/4406

Add preview test target

---

Gemfile.lock
fastlane/Fastfile
fastlane/Pluginfile
fastlane/README.md

Support uploading snapshot to emerge
Adds a new fastlane action to build the paywalls tester app and upload it to emerge. This isn't hooked up with CI yet because I wasn't sure if that needs to run in a GitHub action or something else. That will also require adding the emerge access token to the repository secrets

Build test app

---

Tests/APITesters/AllAPITests/ObjcAPITester/RCTransactionAPI.m

Adds an API Test for the `jwsRepresentation` property in `RCTransaction`, which is available exclusively in Objective-C

Adds API Test for `jwsRepresentation` in obj-c

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift

We let devs configure the screen that's displayed to users with NO active subscriptions, but the `NoSubscriptionsView` is not dynamically built. This PR changes the logic so `ManageSubscriptionsView` is also used with the data in the `NO_ACTIVE` screen of the configuration.
I had to change the view a little bit since the Missing purchase option is optional and it doesn't make sense it always displays the "We can try checking your Apple account for any previous purchases"
| <img width="600" alt="Screenshot 2024-12-02 at 17 54 02" src="https://github.com/user-attachments/assets/bb6e81e9-f03e-4952-a9fd-f204e28ef0e1"> | <img width="600" alt="Screenshot 2024-12-02 at 17 54 02" src="https://github.com/user-attachments/assets/d556027f-ea9b-40ec-838e-db5cac6b …

Use `ManageSubscriptionsView` for users without active subscriptions

---

.circleci/config.yml
Gemfile.lock
RevenueCat.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - Live Config.xcscheme
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - SK config.xcscheme
Tests/TestingApps/PaywallsTester/PaywallsTester.xcworkspace/xcshareddata/swiftpm/Package.resolved
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
Tests/TestingApps/PaywallsTester/PaywallsTesterTests/PaywallsTesterTests.swift
fastlane/Fastfile
fastlane/Pluginfile
fastlane/README.md

This PR:
- Adds a test target to `PaywallTester`.
- Adds Emerge's `SnapshotPreviews` package to the test target.
- Adds Emerge's Fastlane plugin and a new lane which uploads `PaywallsTester` to Emerge.
- Adds a CircleCI job to run the lane.
Shoutout to @noahsmartin for all the help!

[Paywalls] Add Emerge Snapshot Tests

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Identity/CustomerInfo.swift
Sources/Identity/SubscriptionInfo.swift
Sources/Networking/Responses/CustomerInfoResponse.swift
Sources/Purchasing/EntitlementInfo.swift
Sources/Purchasing/NonSubscriptionTransaction.swift
Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
Tests/APITesters/AllAPITests/ObjcAPITester/RCSubscriptionInfoAPI.h
Tests/APITesters/AllAPITests/ObjcAPITester/RCSubscriptionInfoAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/CustomerInfoAPI.swift
Tests/APITesters/AllAPITests/SwiftAPITester/SubscriptionInfoAPI.swift
Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
Tests/UnitTests/Identity/CustomerInfoManagerTests.swift
Tests/UnitTests/Networking/Backend/BackendGetCustomerInfoTests.swift
Tests/UnitTests/Networking/Backend/BackendPostReceiptDataTests.swift
Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Tests/UnitTests/Purchasing/CustomerInfoTests.swift
Tests/UnitTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift

We had more information we were not exposing in the CustomerInfo JSON
This PR adds `CustomerInfo.subscriptions` which has some useful information for devs that don't use the entitlements system

Adds `subscriptions` to `CustomerInfo`

---

RevenueCatUI/CustomerCenter/URLUtilities.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
RevenueCatUI/Data/Strings.swift

Deeplinks should always be configured as `external`, if someone configures a deeplink as inapp, we'll try to open that link with a Safari view, which crashes. This PR makes sure deeplinks are always opened correctly.
There should be an update in the UI as well to make sure deeplinks are configured correctly

Customer Center deeplinks should always be opened externally

---

RevenueCatUI/CustomerCenter/URLUtilities.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift

Followup on #4533 after @JayShortway comment on deeplinks also having http as prefix

Renames isDeeplink to isWebLink

---

Sources/CustomerCenter/Events/EventsRequest+CustomerCenter.swift
Tests/UnitTests/CustomerCenter/Events/__Snapshots__/CustomerCenterEventsRequestTests/testCanInitFromDeserializedEvent.1.json
Tests/UnitTests/CustomerCenter/Events/__Snapshots__/CustomerCenterEventsRequestTests/testImpressionEvent.1.json

We were missing the revision id for Customer Center impression events which the backend expects. I had that in another PR but not in `main`
It's hardcoded to 1 for now, since the config JSON doesn't have revision ids yet

Adds missing revisionId to CustomerCenter impression event

---

Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj

The project could not be opened in Xcode 15 because PaywallsTesterTests was added as a folder instead of a group.

[Paywalls] Fix PaywallTester compilation on Xcode 15

---

Sources/Error Handling/BackendError.swift
Sources/Error Handling/BackendErrorCode.swift
Sources/Error Handling/ErrorCode.swift
Sources/Error Handling/ErrorUtils.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/WebPurchaseRedemption/WebPurchaseRedemptionHelper.swift
Sources/WebPurchaseRedemption/WebPurchaseRedemptionResult.swift
Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorCommonTests.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/PurchaseTesterApp.swift
Tests/UnitTests/DeepLink/WebPurchaseRedemptionHelperTests.swift
Tests/UnitTests/Networking/Backend/BackendPostRedeemWebPurchaseTests.swift
Tests/UnitTests/Purchasing/ErrorCodeTests.swift

We decided to rename this redemption result value to better represent the meaning of the result. Note that the API is marked as experimental and the feature is still not enabled in our backend, so it should be ok to rename it.

WebPurchaseRedemption: Rename `alreadyRedeemed` result to `purchaseBelongsToOtherUser`

---

RevenueCatUI/Resources/pl.lproj/Localizable.strings

https://github.com/RevenueCat/purchases-android/pull/1919
The Polish translation for Restore and Continue actions does not sound great for native speakers:
- "Przywrócić" means "To restore", not "Restore" which should be on a CTA
- "Kontynuować" means "To continue", not "Continue" which should be on a CTA
After this changes, the paywall in Polish 🇵🇱 will feel better. Thanks for all the good work!

[EXTERNAL] Polished the Polish paywall translation

---

RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift

The promo offer view felt pretty barren. This is a very small update, but I feel like it looks significantly better this way. 
All I'm doing is reading the icon from the bundle if available. If the image cannot be loaded, it looks exactly the same as it used to. 
| :-: | :-: |
|  <img width="458" alt="Screenshot 2024-12-05 at 6 18 10 PM" src="https://github.com/user-attachments/assets/17cb4292-3d99-445a-9488-0df2242f3a37"> | <img width="470" alt="Screenshot 2024-12-05 at 6 17 30 PM" src="https://github.com/user-attachments/assets/4309904b-80e4-4917-9b28-6bb7a136de1a"> |
| <img width="473" alt="Screenshot 2024-12-05 at 6 22 21 PM" src="https://github.com/user-attachments/assets/01cc736e-aead-48d5-b7b8-966fbf83a375"> | <img width="474" alt="image" …

[Customer Center] Slight improvement to the Customer Center Promotional Offer view

---

Sources/Purchasing/Offering.swift
Tests/UnitTests/Purchasing/OfferingsTests.swift

When fetching an offering metadata value with `getMetadataValue(for:)` (without a default value), a primitive Decodable (like `String`) causes the JSON decoder to crash, as it assumes the value is a JSON object, but it isn't a valid top-level JSON type.
- Use JSONSerializer's `isValidJSONObject` method before attempting to serialize values
- If it's not a valid JSON object, attempt to return the metadata value as the provided decodable type

Support non-JSON object decodable values in `getMetadataValue`

---

RevenueCatUI/Resources/pl.lproj/Localizable.strings

https://github.com/RevenueCat/purchases-android/pull/1919
The Polish translation for Restore and Continue actions does not sound great for native speakers:
- "Przywrócić" means "To restore", not "Restore" which should be on a CTA
- "Kontynuować" means "To continue", not "Continue" which should be on a CTA
After this changes, the paywall in Polish 🇵🇱 will feel better. Thanks for all the good work!
Original PR #4496 by @miszu

[EXTERNAL] Polished the Polish translation (#4496) via @miszu

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/UIKit Compatibility/CustomerCenterViewController.swift
Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
Tests/APITesters/AllAPITests/RevenueCatUISwiftAPITester/CustomerCenterViewControllerAPI.swift
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/CustomerCenterUIKitView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift

This PR:
- Exposes the Customer Center to UIKit through a new public `CustomerCenterViewController` class
- Adds a way to test the `CustomerCenterViewController` in the PaywallTester app
- Adds CustomerCenterViewController API tests to the RevenueCatUISwiftAPITester app
- Manually tested displaying the new `CustomerCenterViewController` in the PaywallTester app

Expose Customer Center to UIKit

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift

Hides the `mode` parameter from the public constructor. This is really only used for the `presentCustomerCenterView` functions

Hide mode from public init in `CustomerCenterView`

---

Sources/CustomerCenter/Events/CustomerCenterEvent.swift

Made some last minute changes in #4528  and added the wrong discriminator to the `CustomerCenterAnswerSubmittedEvent`

Fix wrong discriminator on `CustomerCenterAnswerSubmittedEvent`

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/UIKit Compatibility/CustomerCenterViewController.swift
Sources/CustomerCenter/CustomerCenterPresentationMode.swift
Sources/CustomerCenter/Events/CustomerCenterEvent.swift
Sources/Purchasing/Purchases/Purchases.swift

This PR is a follow-up to some comments from https://github.com/RevenueCat/purchases-ios/pull/4560 's review and updates some of the Customer Center's DocC documentation. It:
- Includes a high-level overview of the feature in the DoC for the `CustomerCenterView` and `CustomerCenterViewController` class/structs, taken from the public docs here: https://www.revenuecat.com/docs/tools/customer-center#overview
- Brands the "Customer Center" by changing all references to the feature to be upper cased.

Customer Center DocC updates

---

.circleci/config.yml
Package.resolved
RevenueCat.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/SnapshotTestingStub/.gitignore
Tests/TestingApps/PaywallsTester/SnapshotTestingStub/Package.swift
Tests/TestingApps/PaywallsTester/SnapshotTestingStub/Package@swift-5.7.swift
Tests/TestingApps/PaywallsTester/SnapshotTestingStub/Sources/SnapshotTestingStub/SnapshotTestingStub.swift
fastlane/README.md

This PR fixes running iOS 13/14 tests with Xcode 14 by removing the direct dependency on the `SnapshotPreviews` package and instead depending on it through a `SnapshotTestingStub` package.
Why is SnapshotTestingStub needed?
At the time of the writing, we still support iOS 13 and iOS 14, which need macOS 12 to run tests in the simulator.
CircleCI bundles Xcode 14.2 with the macOS 12 image, which comes with Swift 5.7.
Emerge's SnapshotPreviews package currently has a dependency on the https://github.com/swhitty/FlyingFox package version 0.16 which requires Swift 5.8.
When we open Revenuecat.xcodeproj in Xcode 14.2, it tries to pull all dependencies, including SnapshotPreviews, and fails to build because of the FlyingFox dependency.
This prevents us from running tests in the iOS 13 and iOS …

[Paywalls] Fix iOS 13/14 tests

---

RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
Tests/APITesters/AllAPITests/RevenueCatUISwiftAPITester/CustomerCenterViewAPI.swift

- Makes `presentCustomerCenter`'s `onDismiss` parameter optional and defaults to `nil`
- Adds API tester for the `presentCustomerCenter` view modifier

Make presentCustomerCenter's onDismiss optional

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift

This PR:
- Uses the `Support.shouldWarnCustomerToUpdate` boolean from the backend to determine if update warnings should be displayed to the user
- Switches the restore flow from using a SwiftUI `Alert` to a `ConfirmationDialog` since we have up to 3 actions that a user can take, and `Alert` only supports a max of 2
- Adds message & button to the restore flow to instruct the user to update their app if no purchases are found, `Support.shouldWarnCustomerToUpdate` is enabled, and the user is an old app version
> [!WARNING]
> This PR is a breaking change from a UI standpoint because it now requires `Support.shouldWarnCustomerToUpdate` to be set for the AppUpdateWarningView to be displayed. This hasn't been enabled by default yet, so most people using Customer Center so far will need to …

Support toggling update warnings & show update in restore flow

---

RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift

There was an issue where a sibiling component would overlap the border and make it look like border didn't exist
Just needed to subtract 1 from the max y 
| ![Simulator Screenshot - iPhone 16 Pro - 2024-11-26 at 20 10 03](https://github.com/user-attachments/assets/2200e6d2-352a-498c-aa67-df6b660b88bf) | ![Simulator Screenshot - iPhone 16 Pro - 2024-11-26 at 20 11 06](https://github.com/user-attachments/assets/f7eb2b76-c40c-4eba-95d7-b25deff9d8ea) |

[Paywalls V2] Fix border being hidden by next sibling component

---

RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift

Currently, when the user cancels a refund, we show the following message on the SubscriptionDetailsView screen under the "Refund Status" message:
This message is a little confusing because it implies that a refund was created and was then cancelled, when one was never created in the first place. When I saw the message, my first thought was, "do I have the money, or does the developer?".
This PR modifies the behavior so that the "Refund Status" section doesn't display at all when the user dismisses the refund screen without creating a refund, since the user already knows that they cancelled it.
The PR doesn't remove the `refundCanceled` localized string in case we need it in the future here or on another platform.

Dont show refund cancelled message when user cancels refund

---

RevenueCatUI/View+OnRedeemWebPurchaseAttempt.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/WebPurchaseRedemption/URL+WebPurchaseRedemption.swift
Sources/WebPurchaseRedemption/WebPurchaseRedemption.swift
Sources/WebPurchaseRedemption/WebPurchaseRedemptionResult.swift

This removes the experimental mention from the docs of the new APIs to redeem Redemption Links.

Make web Redemption Link APIs stable

---

Sources/CustomerCenter/CustomerCenterConfigData.swift

When a refund request completes successfully, it's not necessarily granted yet, as Apple reviews refund requests and can deny them.
This PR updates the default refund granted string to state that the refund has been requested. This copy is consistent with the primary button on the refund sheet, which says "Request Refund".
- The string's default value will need to be updated in the backend as well

Update refund granted default string

---

Sources/Error Handling/BackendErrorCode.swift

Currently these error codes would display in the API as "UnknownBackendError". This performs some better processing of these error codes.

[WEB-1757] Handle new backend error codes that may show in the redemption endpoint

---

Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift

This PR is a potential fix for https://github.com/RevenueCat/purchases-ios/issues/4582. A customer is reporting occasional crashes when the `PurchaseDelegate`'s `readyForPromotedProduct`. The stacktraces indicate that this is happening in both SK1 & SK2 flows. My current theory is that we are calling the `readyForPromotedProduct` function on a background thread when the calling code expects it to be on the main actor/thread.
Update: We heard back from the creator of the issue, and the code that their calling code is in a @MainActor class.
This PR:
- Always calls the PurchaseDelegate's `readyForPromotedProduct` on the main actor
- Updates `PurchaseDeferredPurchasesTests` and `PurchaseDeferredPurchasesSK2Tests` to wait for the callback to be completed since it's now called asynchronusly

Always call readyForPromotedProduct on the main actor

---

RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift

- When using the `Capsule` shape for Pill style shapes, use the `Circular` `RoundedCornerStyle`.
- If available (iOS 16>) use `UnevenRoundedRectangle` for rounded corners and borders.
- Use `.strokeBorder` instead of `.stroke` where available, which first insets the shape by `lineWidth/2` so the whole border stays within the frame of the shape.
- Improve `BorderRoundedCornerShape` to make it conform to `InsettableShape`, so we can use use `.strokeBorder` on it.
- Use `addArc` instead of `addQuadCurve` in `BorderRoundedCornerShape` to match the circular corners in `SingleRoundedCornerShape`.
These changes help fix scenarios where the border would overflow outside of the Stack's frame:
|Before | After
|-------|--------
|<img width="574" alt="Screenshot 2024-12-16 at 14 21 09" …

[Paywalls] Fix issues with rounded corners and borders

---

Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesDeferredPurchasesTests.swift

Despite passing fine locally, these changes have been flaky in the CI for iOS 14-16. This PR reverts the changes in https://github.com/RevenueCat/purchases-ios/pull/4584 out of an abundance of caution

Revert "Always call readyForPromotedProduct on the main actor"

---

RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/Data/Strings.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift

Projects with multiple apps fail to load when the entitlement is granted by another app in the project. For example this Customer Info response:
```
{
"request_date": "2024-12-17T13:47:05Z",
"request_date_ms": 1734443225832,
"subscriber": {
"entitlements": {
"pro": {
"expires_date": "2024-12-17T14:01:33Z",
"grace_period_expires_date": null,
"product_identifier": "premiumyearly",
"purchase_date": "2024-12-16T14:01:33Z"
}
},
"first_seen": "2024-04-29T06:37:25Z",
"last_seen": "2024-12-16T15:24:53Z",
"management_url": "https://apps.apple.com/account/subscriptions",
"non_subscriptions": {
},
"original_app_user_id": "_",
"original_application_version": "1.0",
"original_purchase_date": "2019-05-09T08:20:34Z",
"other_purchases": {
},
"subscriptions": {
"premiumyearly": {
"auto_resume_date": null, …
```

Fix loading Customer Center when entitlement is granted by another Apple app

---

RevenueCatUI/Helpers/Logger.swift
Sources/Error Handling/Assertions.swift

These were the only non-test files where we were using #file instead of #fileID

Use #file instead of #fileID to avoid including the full path in the compiled binary

---

RevenueCatUI/Modifiers/FitToAspectRatio.swift
RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
RevenueCatUI/Templates/V2/Components/Image/ImageComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Root/RootView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template5Preview.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift

- Text was not rendering markdown
- Images where growing the width of its parent
- Footer was expanding whole height
- Text
- Use the `.init` initializers
- Image
- Use the `.fitToAspect` modifier and get the aspect ratio from the width and heigh property of an image
- Footer
- Render with `.fixedSize` so it doesn't expand entire vertical view
- But use `.overlay` because SwiftUI was locking up with `.safeAreaInset`

Fixing text, image, and footer render issues

---

Tests/StoreKitUnitTests/StoreKit2/StoreKit2ObserverModePurchaseDetectorTests.swift

I found myself wondering why we were running the tests in `StoreKit2ObserverModePurchaseDetectorTests` on iOS 15 since we only support purchasing with SK2 on iOS 16+, so I added this comment to remind future me and other folks of why we run these tests on iOS 15.

Add Comment to StoreKit2ObserverModePurchaseDetectorTests

---

RevenueCatUI/Templates/V2/Components/Root/RootView.swift
Sources/Purchasing/Offerings.swift

Some fixes while testing
- Current offering didn't have paywall component data
- Sticky footer wasn't showing content behind
- `safeAreaInsets` breaks with complex layouts
- `overlay` kept scroll content behind it
- Just putting a vstack unedr the scrollview

[Paywalls V2] Fix current offering and sticky footer

---

RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
Sources/Paywalls/Events/PaywallEvent.swift

Paywalls V2 view was not tracking impression/close event, disabling while purchase, dismissing after purchase.
Brought in code that was being used in Paywalls V1 for this

[Paywalls V2] Fix analytics and dismiss

---

RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
RevenueCatUI/Templates/V2/ViewHelpers/ForegroundColorScheme.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift

Add support for aliased `hex` colors (for when dashboard supports them)
⚠️ Gradients will required a bigger rework (a Linear ticket has been added for this)
Passes a `UIConfigProvider` into the `toColor()` method which does the alias lookup

[Paywalls V2] Add support for alias solid hex colors (not gradients)

---

Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift

[Paywalls] Fix PaywallTester build

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Misc/RateLimiter.swift
Tests/UnitTests/Misc/RateLimiterTests.swift

Introduced in #3709, `RateLimiter` is used exclusively by `Purchases.syncAttributesAndOfferingsIfNeeded(completion:)`. The [documentation of this method](https://www.revenuecat.com/docs/tools/targeting/custom-attributes#the-syncattributesandofferingsifneeded-method) doesn't mention any threading requirement, so it's reasonable to assume that it can be called on any thread. This means `RateLimiter` needs to be thread safe, otherwise clients will run into race conditions as reported in #4440.
Fortunately the `RateLimiter` class is quite simple.
Its contants don't need to be atomic/locked since they are thread safe by definition. Turning `timestamps` and `index` vars into atomics doesn't help much in this case because `shouldProceed()` needs multiple reads and writes in a "transaction". …

[EXTERNAL] Lock RateLimiter.shouldProceed() entirely to avoid race conditions (#4635) via @nguyenhuy

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Config/ConfigItem.swift
Tests/UnitTests/Paywalls/Components/Properties/CornerRadiusesPropertyTests.swift
Tests/UnitTests/Paywalls/Components/Properties/MaskShapePropertyTests.swift
Tests/UnitTests/Paywalls/Components/Properties/PaddingPropertyTests.swift
Tests/UnitTests/Paywalls/Components/Properties/ShapePropertyTests.swift

Removing hard requirement for properties that can/should easily default to zero (just for safety)
Made properties optional for:
- `Padding`
- `CornerRadiuses`

[Paywalls V2] Optionalizing padding, margin, and corner radius properties for safety

---

RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
RevenueCatUI/Templates/V2/ViewHelpers/ShadowModifier.swift
RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift

By default shadows in SwiftUI are applied to children views as well, so we implemented a workaround by using `.compositingGroup()`.
However when the background color of a view with a shadow has less than 100% opacity, the `.compositingGroup()` workaround no longer works. Additionally, the shadow inherits the opacity of the view which is less than ideal.
In this PR, we replace SwiftUI shadows with a CALayer-backed solution. Because this solution requires knowing the shape of the view, I took the opportunity to refactor the Shape modifier code.
I didn't modify any current SwiftUI previews so make sure nothing broke. The only changes were minor rendering differences in the shadows which are not perceptible with your naked eye, and a change in how a shadow applied to a `Text` view renders, as …

[Paywalls] Use CALayer-backed shadows and refactor Shape.swift

---

Sources/Misc/Deprecations.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m

The `purchase(_ params: PurchaseParams, completion: @escaping PurchaseCompletedBlock)` was mistakenly exposed to Objective-C with the name `params` in https://github.com/RevenueCat/purchases-ios/pull/4485.
This PR deprecates that existing `params` name in Objective-C (`@objc(params:withCompletion:)`) and replaces it with `purchaseWithParams` (`@objc(purchaseWithParams:completion:)`).
Swift doesn't support deprecating only an Objective-C selector. You need to create a second Swift function with the correct `@objc` selector and ensure that the Swift function names don't conflict. This isn't ideal because it adds an extra deprecated function to the Swift API, but it gets the job done. 
So to accomplish this, this PR renames the existing Swift function with the incorrect `@objc` selector to …

Deprecate misnamed purchase(params) function in Obj-C

---

RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/ViewHelpers/SizeModifier.swift

Vertical and horizontal stacks would act as fill when set as fit
- Remove frame infinity
- Added new SwiftUI preview for snapshot
| ![Screenshot 2025-01-10 at 11 24 32 AM](https://github.com/user-attachments/assets/0806a0ba-712b-471b-8797-721f210275ec) | ![Screenshot 2025-01-10 at 11 24 47 AM](https://github.com/user-attachments/assets/289fe4cd-1ec0-4d63-866a-904612b47943) |

[Paywalls V2] Fix vstack and hstack growing size when fit

---

RevenueCatUI/CustomerCenter/Views/CompatibilityContentUnavailableView.swift

This PR tries to address https://github.com/RevenueCat/purchases-ios/issues/4638.
| ![IMG_7180](https://github.com/user-attachments/assets/4c38c0e1-4fec-4c48-9c90-9f2b57823e6d) | ![IMG_7179](https://github.com/user-attachments/assets/2ef54487-3b0d-471b-bcae-84b7509889eb) |
For some reason, `ContentUnavailableView` truncates the label. I've tried using `lineLimit(nil)` over the `Label`, but that didn't work. This seems to do the trick. 
`fixedSize(vertical:true)` forces the view to grow vertically to the needed height.

fix: Use custom label for CompatibilityContentUnavailableView

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
RevenueCatUI/Templates/V2/ViewHelpers/DisplayableColor.swift
RevenueCatUI/Templates/V2/ViewHelpers/ForegroundColorScheme.swift
RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
RevenueCatUI/Templates/V2/ViewHelpers/SizeModifier.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
Sources/Networking/Responses/RevenueCatUI/UIConfig.swift

Aliased color will be both light and dark
This ended up being a whole thing...
TL;DR - Added a new `DisplayableColorScheme` object that has types of `hex`, `linear`, and `radial`... 
`PaywallComponent.ColorScheme -> `DisplayableColorScheme` -> `Color`/`Gradient`
We have `.alias` as a value on `ColorInfo` but we need to alias an entire set of light/dark colors (aka `ColorScheme`).
Our logic right now directly converts `ColorInfo` into a SwiftUI/UI color (for foreground, background, etc). This works fine for `hex`, `linear`, and `radial` but will not work well for alias. We need to perform the alias lookup at the `ColorScheme` level (near the view model layer instead of at the render layer)
Create a new `DisplayableColorScheme` and `DisplayableColorInfo` struct. These new data structures …

[Paywalls V2] Updating UIConfig aliased colors to contain both light and dark

---

RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
RevenueCatUI/Templates/V2/Components/Image/ImageComponentViewModel.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template5Preview.swift
Sources/Paywalls/Components/PaywallImageComponent.swift

Image component was missing some new properties (and had some outdated ones)
- Removed:
- Gradient overlay
- Max height
- Added:
- Color overlay
- Padding
- Margin
- Border
- Shadow
⚠️ Follow PR to actually use all these properties

[Paywalls V2] Updated outdated image component properties

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Sources/Paywalls/Components/PaywallStackComponent.swift

This PR adds a `.stackBadge` modified to `Stacks` which is displayed in one of three ways: nested, edge_to_edge, or overlaid.
Check emerge for snapshots for all examples e.g.:

[Paywalls] Add Badge Modifier

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template5Preview.swift
Sources/Paywalls/Components/PaywallTextComponent.swift
Tests/UnitTests/Networking/Responses/Fixtures/UIConfig.json
Tests/UnitTests/Networking/Responses/UIConfigDecodingTests.swift
Tests/UnitTests/Paywalls/Components/PartialComponentTests.swift
Tests/UnitTests/Paywalls/Components/TextComponentTests.swift

More flexability in font size
Use `CGFloat` as `fontSize` on `TextComponent` but also back support `FontSize` for a while

[Paywalls V2] Accept number as font size for text

---

RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift

This is a follow-up of https://github.com/RevenueCat/purchases-ios/pull/4622 just to have a cleaner PR.
The environment `dismiss` dismisses the whole thing, whereas using `isPresented` just closes the alert, which is the original intention.

fix: dismiss alert using binding instead of environment dismiss

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/ComponentsView.swift
RevenueCatUI/Templates/V2/Components/Icon/IconComponentView.swift
RevenueCatUI/Templates/V2/Components/Icon/IconComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Image/ImageComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
Sources/Paywalls/Components/Common/PaywallComponentBase.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Sources/Paywalls/Components/PaywallIconComponent.swift
Sources/Paywalls/Components/PaywallconComponent.swift

[Paywalls V2] Icon Component

---

RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift

This adds a simple wrapper over `LabeledContent` to work with iOS prior 16. It will be used in purchase history view
| Header |
|--------|
| ![image](https://github.com/user-attachments/assets/f45bbab2-e89d-4a39-b391-9621735c506c) |

feat: [CustomerCenter] Introduce CompatibilityLabeledContent

---

Package.resolved
Package.swift
Package@swift-5.7.swift
Package@swift-5.8.swift

While working on the codebase, `Package.resolved` keeps getting modified. This addresses that by fixing the dependency versions to specific commits.
- Nimble (10.0.0) https://github.com/Quick/Nimble/commit/1f3bde57bde12f5e7b07909848c071e9b73d6edc
- swift-snapshot-testing (1.12.0) https://github.com/pointfreeco/swift-snapshot-testing/commit/26ed3a2b4a2df47917ca9b790a57f91285b923fb
- Dooc (1.3.0) https://github.com/swiftlang/swift-docc-plugin/commit/26ac5758409154cc448d7ab82389c520fa8a8247
> This is the fastest, and simple enough till we integrate tuist (or something else)

fix: Fix versions for swift-doc, snapshot-testing & nimble

---

RevenueCatUI/Templates/V2/Components/Icon/IconComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
Sources/Paywalls/Components/PaywallButtonComponent.swift
Sources/Paywalls/Components/PaywallIconComponent.swift
Sources/Paywalls/Components/PaywallImageComponent.swift
Sources/Paywalls/Components/PaywallPackageComponent.swift
Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
Sources/Paywalls/Components/PaywallStackComponent.swift
Sources/Paywalls/Components/PaywallStickyFooterComponent.swift
Sources/Paywalls/Components/PaywallTabsComponent.swift
Sources/Paywalls/Components/PaywallTextComponent.swift

We were getting random-ish `EXC_BAD_ACCESS` after the merge of the badge PR. It took some debuggin and it turned out..
When decoding 5-ish paywall v2 in an `OfferingsResponse`, the `struct` structure while in the encoder would just fail.
Note that this is in the ENCODER... and not the DECODER. So this was happening when we decode string response to Swift object and then encode back for storage.
After some debugging and experimentation with Mark, it was our conclusion that our OfferingsResponse struct with the Paywalls V2 struct were causing some sort of struct structure that was WAY too big causing some sort of buffer overflows or something.
We experiment with converting one struct to a class and it made the issue go away. So we continue this in the PR to convert all Paywalls V2 …

[Paywalls V2] Convert Codable structs to classes

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Paywalls/Components/PaywallV2CacheWarming.swift
Sources/Paywalls/PaywallCacheWarming.swift

Prefetch low res images of all paywalls v2 paywalls
Collects all the images in v2 paywalls for warming up cache
- Traverses the stack tree to get all of the low res images
- Collects all the images from the localizations

[Paywalls V2] Prefetch low res images

---

Sources/Purchasing/Configuration.swift
Tests/UnitTests/Purchasing/ConfigurationTests.swift

`mac_` prefixed API keys are still valid and we shouldn't warn when using them.

Do not warn when using mac API keys

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Views/CustomerCenterNavigationLink.swift

This PR aims to reduce ambiguity in how `CustomerCenterView` is used. Together with `presentCustomerCenter`, `CustomerCenterNavigationLink` becomes the recommended approach for navigating to `CustomerCenterView`.
Following up on [#4622](https://github.com/RevenueCat/purchases-ios/pull/4622) and based on feedback from @hiddevdploeg, we are introducing `CustomerCenterNavigationLink`.
The primary objective is to offer a straightforward method for integrating `CustomerCenterView` into an existing `NavigationView`, without requiring developers to handle the `isEmbeddedInNavigationStack` parameter manually.

feat: [CustomerCenter] Introduce CustomerCenterNavigationLink

---

RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
RevenueCatUI/Templates/V2/Components/Image/ImageComponentViewModel.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift

Image was missing a bunch of properties in its rendering
- Mask
- Replaced `pill` with `circle`
- Added `concave` and `convex`
- Add `padding` and `margin`
| Circle | Convex | Concave |
|--------|--------|--------|
| <img width="479" alt="Screenshot 2025-01-15 at 12 07 25 PM" src="https://github.com/user-attachments/assets/9f3d97f6-0b8a-4dbf-ab9b-7780f55bbd08" /> | <img width="490" alt="Screenshot 2025-01-15 at 11 57 30 AM" src="https://github.com/user-attachments/assets/7e9f4538-e39e-4cac-8a92-501fa90cfad4" /> | <img width="543" alt="Screenshot 2025-01-15 at 11 57 42 AM" src="https://github.com/user-attachments/assets/cd527fc4-2159-4947-b8c3-9cd83a9c491c" /> |

[Paywalls V2] Add masking (concave, convex, circle) and padding/margin to image

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterNavigationLink.swift

This is a follow-up of https://github.com/RevenueCat/purchases-ios/pull/4664 that makes the action handler optional, matching how `CustomerCenterView` initializer works.

feat: Make CustomerCenterActionHandler optional for CustomerCenterNavigationLink

---

Sources/Identity/IdentityManager.swift
Sources/Logging/Strings/IdentityStrings.swift
Tests/UnitTests/Identity/IdentityManagerTests.swift

Until now, when devs enabled Trusted Entitlements, we would clear the cached `CustomerInfo` and customers would need to refetch the latest value from the server, which could potentially cause delays and/or losing access temporarily.
With this PR, we won't be clearing the cached CustomerInfo anymore. Instead, we would return the cached customer info, which will have a `VerificationResult` of `NOT_REQUESTED`. 
iOS equivalent of https://github.com/RevenueCat/purchases-android/pull/2049

[Trusted Entitlements] Do not clear CustomerInfo upon enabling Trusted Entitlements

---

RevenueCatUI/CustomerCenter/Views/CompatibilityNavigationStack.swift

To avoid having conditional navigation based on iOS versions everywhere, this adds a wrapper to navigate smoothly. Showing [here](https://github.com/RevenueCat/purchases-ios/pull/4662/files#diff-5b7c7f2707e8c72de42ed7acd513720b59fdaea1244f3d4dcc748ff813e6005cR86) how it is used

feat: Add View extension based on CompatibilityNavigationStack

---

Sources/Purchasing/Purchases/Attribution.swift
Sources/SubscriberAttributes/ReservedSubscriberAttributes.swift
Sources/SubscriberAttributes/SubscriberAttributesManager.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCAttributionAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/AttributionAPI.swift
Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/SubscriberAttributesView.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Tests/UnitTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift

#4656 
- Adds a convenience method to set the PostHog User ID (`$posthogUserId`)

Add convenience method for setting PostHog User ID

---

RevenueCatUI/CustomerCenter/ButtonStyles.swift
RevenueCatUI/CustomerCenter/ContactSupportUtilities.swift
RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseDetailViewModel.swift
RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseDetailView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseLinkView.swift
RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift

The previous syntax made the whole dance too verbose:
```diff
- .navigationTitle(localization.commonLocalizedString(for: .purchaseHistory))
+ .navigationTitle(localization[.purchaseHistory])
```
This simplifies it 💅 
> This only affects `CustomerCenter`

refactor: [CustomerCenter] Improve syntax for CommonLocalizedString

---

Sources/CustomerCenter/CustomerCenterConfigData.swift
Sources/Networking/Responses/CustomerCenterConfigResponse.swift
Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift

Currently this is false by default. This will leave it ready for the feature flag, enabling purchase history

Use config response for `displayPurchaseHistoryLink`

---

RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift

This PR addresses a bug where environment values, such as localizations, were not propagating to child views. 
The bug occurs when the navigation stack or navigation view is provided by the client app instead of the one managed by the customer center. To resolve this, the environment must be applied directly to the container view, allowing it to cascade properly to all child views.

fix: Set environment values for every child view in CustomerCenter

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

Use `. usesNavigationStack` instead of `.usesExistingNavigation` for the custom modifier.

fix: Use usesNavigationStack instead of usesExistingNavigation

---

RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseDetailViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseInfo.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseDetailView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseLinkView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift

This PR splits the purchase detail into two different sections to be explicit on what's only in debug mode
> it also sets the content shape to a few views to improve "tappabitliy" of the button

feat: Add debug section for purchase detail

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift

I noticed the error view was not showing the close button. The navigation is not applied to all views, so there's nowhere to place the button.
This wraps all the views to the navigation stack if not provided

fix: Show close button in ErrorView

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Packages/Package/PackageComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PresentedPartials.swift
Sources/Paywalls/Components/Common/ComponentOverrides.swift
Sources/Paywalls/Components/PaywallV2CacheWarming.swift
Tests/RevenueCatUITests/PaywallsV2/PresentedPartialsTests.swift
Tests/RevenueCatUITests/PaywallsV2/VariableHandlerV2Tests.swift
Tests/UnitTests/Paywalls/Components/PartialComponentTests.swift

Migrating `overrides` from a structured object to an array of override objects
Overrides were a very structure object that had all of the different types of states/conditions that allowed base properties of a component to be overridden. However, this was not flexible when it came to multiple being activated as it was missing for cases when multiples types of conditions were being evaluated.
Overrides is an array that has an array of `conditions` and `properties`. It will get applied in order from first to last IF all of the `conditions` are true.
This allows the FE/BE to determine the orders of overrides from lowest to higher priority so all of the SDKs/renderers don't need to duplicate that logic.

[Paywalls V2] New overrides structure

---

RevenueCatUI/PaywallFontProvider.swift

`Font.TextStyle.caption3` was introduced with Xcode 16.0/tvOS 18.0, but was removed with no warning in Xcode 16.1/tvOS 18.1 and hasn’t been reintroduced since.
Thus, if you try to build RevenueCatUI for tvOS on Xcode 16.1-16.2, you’ll get a build failure. This PR addresses these build failures by only compiling the `.caption3` related code when the SDK is built with Xcode 16.0
If `Font.TextStyle.caption3` is reintroduced in a future tvOS/Xcode release, we'll need to update these compilation checks again to avoid warnings.
I tested this by building RevenueCatUI with Xcode 15.4, 16.0, 16.1, and 16.2. All builds passed

Fix Font.TextStyle.caption3 Availabilities on tvOS

---

RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift

Fix compile error when trying to build for release
Some SwiftUI previews were not behind `DEBUG`

[Paywalls] Move SwiftUI previews for badge behind DEBUG flag

---

RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
Tests/UnitTests/Paywalls/Components/StackComponentTests.swift

Badge was not rendering on package and had some padding issues
- Badge is no longer using a box for codables
- Everything in `ViewModelFactory` is `toStackViewModel` for stacks
- `toStackViewModel` is doing badge view modeling
- Models that whole stack (instead of the stacks components) which then includes the correct padding and margin on the stack
1) Badge was not showing before this (because badge wasn't being view model-ed on package's stack)
2) Badge didn't have any padding inside it (because view model was happening on its stacks components and needed to include stack)
👇

[Paywalls V2] Fix paywalls badge rendering

---

Sources/Misc/DangerousSettings.swift
Tests/APITesters/AllAPITests/AllAPITests.xcodeproj/project.pbxproj
Tests/APITesters/AllAPITests/SwiftAPITester/DangerousSettingsAPI.swift
Tests/APITesters/AllAPITests/SwiftAPITester/main.swift

We need a way to activate the UI Preview mode in the SDK to enable the Paywall Previews functionality in the RC app without actually adding any new public APIs to the SDK
This PR adds a new property to `DangerousSettings`: `uiPreviewMode`. 
* This new public API is opt-in only, thanks to the [`@_spi` attribute](https://swiftpackageindex.com/swiftlang/swift-syntax/600.0.1/documentation/swiftsyntax/spi).
* The UI Preview Mode of the SDK will limit all the functionality of the SDK to only enable implementing the Paywall Previews functionality (and similar) in the RevenueCat app, so that developers can properly test their paywalls on their own devices.

Add `uiPreviewMode` to `DangerousSettings`

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseLinkView.swift

After some feedback, this removes the `.buttonStyle(.plain)` modifier from buttons to get some tap feedback.
https://github.com/user-attachments/assets/760f4d69-4e6e-4b90-ab57-cbba241cf8c7

fix: Remove  buttonStyle for PurchaseHistory

---

RevenueCatUI/Templates/V2/Components/Root/RootView.swift
RevenueCatUI/Templates/V2/PaywallsV2View.swift

Footer was showing empty space between footer and safe space on the bottom
- Ignoring edges on bottom instead of top (which I think was a typo)
- Added a spacer to the bottom of the footer to expand space to fill out the safe space
👇 This is what the `Spacer()` fixes
| ![Simulator Screenshot - iPhone 16 - 2025-01-28 at 23 13 08](https://github.com/user-attachments/assets/aefc197f-d14c-49da-b577-95a1521e4800) | <img width="614" alt="Screenshot 2025-01-28 at 11 12 54 PM" src="https://github.com/user-attachments/assets/0561f843-efdd-4e9f-95ed-05d98fcc7034" /> |

[Paywalls V2] Fix footer spacing issues

---

RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseDetailViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseDetailView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseLinkView.swift
RevenueCatUI/CustomerCenter/Views/TintedProgressView.swift

This PR revisits every `.environment` use inside CustomerCenter. The root cause is related to https://github.com/RevenueCat/purchases-ios/pull/4704
1. Order alphabetically environment declarations in each view
2. Set explicit environment values for each view
3. Reordered `ManageSubscriptionsView` moving all navigation modifiers to the same place
> I am still thinking what's the best way to test this, or write type-safe code.

fix: Revisit environment values for CustomerCenter

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/Variables/VariableHandlerV2.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
Tests/RevenueCatUITests/PaywallsV2/VariableHandlerV2Tests.swift

Support the backward compatibility variable mapping
- Unknown variables and functions will map existing ones that have a sensible match
- Super unknown (which shouldn't happen) just leave leave empty string for variable and no-op for functions

[Paywalls V2] Support variable mapping

---

RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
Sources/Paywalls/Components/PaywallStackComponent.swift
Tests/UnitTests/Paywalls/Components/StackComponentTests.swift

Which will supersede the backgroundColor property

[Paywalls] Add background property to Stack component

---

RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
RevenueCatUI/Templates/V2/Components/ComponentsView.swift
RevenueCatUI/Templates/V2/Components/Packages/Package/PackageComponentView.swift
RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
RevenueCatUI/Templates/V2/Components/Root/RootViewModel.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FallbackComponentPreview.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift

Be smart about when and where to ignore safe area edges so header images expand all the way to the top edge.
1. In the `ViewModelFactory`, find if the first non-container type component is an image
- If we find one, also pair it with its parent if its a ZStack
- We need this so that we can apply safe area insets to the non-images in the ZStack so they stay pushed down
- We add a new boolean into the `StackViewModel` of the containing ZStack that we need to apply safe area inset padding
2.  If we found that an image is first:
- Apply `.edgesIgnoringSafeArea(.top)` to the entire paywall contents
- Send the value of the safe area insets as an environment variable
3. When rendering the paywall, we apply the safe area insets into the ZStack components if needed so they stay pushed down
👉  See …

[Paywalls V2] Ignore top safe area edges for image

---

Sources/Identity/IdentityManager.swift
Sources/Logging/Strings/IdentityStrings.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Identity/IdentityManagerTests.swift
Tests/UnitTests/Mocks/MockIdentityManager.swift

The SDK uses a fixed, specific user ID when initialized in UI preview mode in order to prevent cluttering usage statistics for the developer
When using the UI preview mode introduced in #4714, the SDK will force the `appUserID` to be `"$RCPREVIEWMODE"`.

UI Preview Mode: app user ID

---

Sources/Networking/Responses/OfferingsResponse.swift
Sources/Purchasing/OfferingsManager.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift

The UI Preview Mode of the SDK should limit all the functionality of the SDK to only enable implementing the Paywall Previews functionality in the RevenueCat app.
Mock the `StoreProducts`, as we cannot fetch them from StoreKit

UI Preview Mode: mock products

---

Sources/Purchasing/OfferingsManager.swift
Tests/UnitTests/Purchasing/OfferingsManagerTests.swift

To make sure that paywalls are always up-to-date when in UI Preview mode, the SDK should always fetch the Offerings from the network, ignoring the local cache
Always fetch Offerings from the network when `uiPreviewMode` is `true`

UI preview mode/always fetch offerings

---

Sources/Paywalls/Events/Networking/EventsRequest+Paywall.swift

Just a simple message for future generations to come. In `purchases-android` it's clear that snake_case is used for encoding. This is just a message so other people don't waste time like I did =)

chore: A simple message for posterity

---

Sources/Purchasing/Purchases/Purchases.swift

`Purchases`'s `delegate` property is a computed property and isn't marked or documented as being weak, but the underlying `privateDelegate` that backs it is weak. This means that if a developer sets a PurchasesDelegate like this:
```swift
Purchases.shared.delegate = MyPurchasesDelegate()
```
the delegate will be deallocated. Since we only retain a _reference_ to the delegate, none of the log messages in the `Purchases.delegate.set` block will be logged, and future calls to the delegate will not be received. It's possible for this to happen without the developer's knowledge, so this PR documents the behavior.
This PR documents the fact that `Purchases.delegate` uses a weak reference.

Document Weak PurchasesDelegate Reference

---

RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Sources/Purchasing/EntitlementInfo.swift

RevenueCat Billing product is being renamed to Web Billing
- Rename "RevenueCat Billing"/"RC Billing" to "Web Billing" in a couple of places. 
- Store enum remains unchanged

Rename RC Billing to Web Billing

---

Sources/CustomerCenter/CustomerCenterConfigData.swift

Tweak the default translation for `dateWhenAppWasPurchased`

chore: Tweak default copy for dateWhenAppWasPurchased

---

README.md
RevenueCatUI/Views/GradientView.swift

The `spm-revenuecat-ui-ios-15` CI job is [currently failing](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/25075/workflows/cb710f05-3ac7-4c86-9cc3-8cd532afac0b/jobs/288868) due to compilation issues with the `GradientView` previews - the preview has more than 10 views inside a container, which SwiftUI doesn't allow:
This PR addresses the build issue by abstracting the title and gradient to a private, preview-only `LinearGradientPreview` view, which halves the number of views in the `VStack`. This doesn't affect the look of the preview:
I'm not yet sure why the existing code worked on newer iOS versions but failed in the iOS 15 job - looking into that now

Fix Gradient Preview on iOS 15

---

RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift

On macOS (Catalyst), the Customer Center currently does not display the option to cancel, only the option to refund. 
This PR removes the filter that was previously applied, which prevented the cancel option from appearing. After testing all affected paths, they appear to work as expected. There is no known reason or documentation indicating why this filter was originally applied.

feat: Enable cancellation in CustomerCenter for catalyst

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Localizations/LocaleExtensions.swift
RevenueCatUI/Templates/V2/Localizations/LocaleFinder.swift
RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
Tests/RevenueCatUITests/PaywallsV2/LocaleFinderTests.swift

There were issues with finding locales like `zh-Hans` and `zh-Hant`
1. Attempt to look for the locale identifier as is
2. If nothing, replace `-` with `_`
| Example |
|--------|
| ![Simulator Screenshot - iPhone 16 - 2025-02-06 at 22 25 52](https://github.com/user-attachments/assets/4529070b-2067-43ea-8e62-ee2669a00840) |

Fixed issues with finding some locales (ex: `zh-Hans` and `zh-Hant`)

---

RevenueCatUI/Templates/V2/Variables/VariableHandlerV2.swift
Tests/RevenueCatUITests/PaywallsV2/VariableHandlerV2Tests.swift

⚠️ Dependent on a backend PR to be merged first with the new keys
The period abbreviation when multiple months was rendering as `months` or `mo` instead of `3 months` or `3mo`
Four new localization keys for abbreviated days/weeks/months/years

Fix period abbreviated when multiple days/weeks/months/years

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift

Support generic fonts for serif and monospace
`TextComponentStyle` still map `serif`, `sansserif`, and `monospace` to generic system fonts

[Paywalls V2] Support generic fonts

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Misc/DateAndTime/ISODurationFormatter.swift
Sources/Misc/DateAndTime/ISOPeriodFormatter.swift
Tests/UnitTests/Misc/ISODurationFormatterTests.swift

This PR introduces `ISODurationFormatter` to work with ISO Duration
We need support for this in Customer Center, to work with refund windows. This PR adds a basic parser.
I've added it inside `ISOPeriodFormatter` maintaining the tests, just to prove it does not break anything. I would remove `ISOPeriodFormatter` in favor of this new formatter

feat: Introduce ISODurationFormatter

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Data/FeedbackSurveyData.swift
RevenueCatUI/CustomerCenter/Data/PromotionalOfferData.swift
RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Tests/RevenueCatUITests/CustomerCenter/FeedbackSurveyViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/Mocks/MockLoadPromotionalOfferUseCase.swift

If `customerCenterActionHandler` is not set, we are not tracking survey answered submitted events

Fix for survey answered event not being tracked when not setting a `customerCenterActionHandler`

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/Previews/PreviewMock.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift

Purchase events callbacks were not being executed
`PaywallsV2View` did not have the preference keys configured

Hooks up purchase handler preference keys for Paywalls V2

---

RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift

We've noticed `trackImpression` gets called multiple times per session. This PR addresses that
`impression` event should be tracked only once per session
The PR adds a simple check like its done in the Android repository, and updates a test to make sure its only tracked once

fix: Track impression in CustomerCenter only once

---

RevenueCatUI/Templates/V2/Components/Root/RootView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
Sources/Paywalls/Components/PaywallStackComponent.swift

We need to allow stacks to have some overflow properties like scroll
Added `overflow` property to stack with values of:
- `none`
- `scroll`

[Paywalls V2] Added `overflow` property to stack 

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Identity/CustomerInfoManager.swift
Tests/UnitTests/Identity/CustomerInfoManagerUIPreviewModeTests.swift

In UI Preview mode, the SDK should not make the requests to obtain the `CustomerInfo`.
When in UI Preview mode, the SDK:
* Avoids caching `CustomerInfo`
* Always returns mocked `CustomerInfo` (if requested either from the cache or from the backend)

UI Preview Mode: mock `CustomerInfo`

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/ComponentsView.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
Sources/Networking/Responses/RevenueCatUI/UIConfig.swift
Sources/Paywalls/Components/Common/PaywallComponentBase.swift
Sources/Paywalls/Components/PaywallCarouselComponent.swift
Sources/Paywalls/Components/PaywallV2CacheWarming.swift

Gotta carousel!
https://github.com/user-attachments/assets/bb996b63-a342-45cb-bf8c-569a5f6c39bb

[Paywalls V2] Carousel component

---

RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift

~This tries to address https://github.com/RevenueCat/purchases-ios/issues/4790~
For some reason, we missed that `AppWarningView` is already embebed in a NavigationStack / NavigationView.

fix: Remove NavigationView/NavigationStack from AppWarningView

---

.swiftlint.yml
RevenueCatUI/CustomerCenter/Views/PurchaseHistory/PurchaseHistoryView.swift

While debugging another thing, I noticed this was in production. This removes the force unwrap

fix: Remove force unwrapping from PurchaseHistoryView

---

Sources/CodableExtensions/PeriodType+Extensions.swift
Sources/Identity/SubscriptionInfo.swift
Sources/Purchasing/EntitlementInfo.swift
Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/EntitlementInfoAPI.swift
Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesAPI.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCEntitlementInfoAPI.m
Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/EntitlementInfoAPI.swift
Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
Tests/InstallationTests/CommonFiles/RevenueCat-Swift.h
Tests/UnitTests/Purchasing/EntitlementInfosTests.swift

Add prepaid as a period type like we have done in [android](https://github.com/RevenueCat/purchases-android/pull/2141#event-16278601110).

Add prepaid as a period type

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Modifiers/ViewExtensions.swift
RevenueCatUI/PaywallView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Configuration.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Constants.swift
Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
scripts/pre-commit.sh

As pointed out by @facumenzella, for consistency with other projects and repos, the `Constants` name should be used instead of `ConfigItem`. `ConfigItem` contains the code that reads the RC API key from the bundle in PaywallsTester (see #4795)
* Renames `ConfigItem` to `Constants`
* Bonus: adds a more detailed explanation to `refreshableDisabled()` modifier introduced in #4793 (again, thanks @facumenzella for pointing this out!)

Config item rename

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift

Generic fonts (`sans-serif`, `serif` and `monospace`) weren't displaying at all.
This was caused by the fact that the font _display_ name was matched against the generic font, instead of the actual font name. 
The fix is to look up the font name using its display name in `ui_config`, like we do for other custom fonts.

[Paywalls V2] Fixes parsing generic fonts.

---

Sources/Error Handling/BackendError.swift
Sources/Error Handling/ErrorUtils.swift
Sources/Identity/IdentityManager.swift
Tests/UnitTests/Identity/IdentityManagerTests.swift

Even though no calls to `logIn` or `logOut` should happen in UI preview mode, it's still appropriate to make sure that the SDK properly controls that scenario.
* With this PR, the SDK implements early returns in the `IdentityManager` for the `logIn` and `logOut` methods, preventing any logic in this scenario (including any log in request to the backend)
* Calling `logIn` using the app user ID reserved for UI preview mode also fails, **even if UI preview mode is not enabled**

UI preview mode: disable log in and log out

---

RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift

The `onRestoreComplete` callback was not being called because were not setting the corresponding `customerInfo` variable.
In Paywalls V1 we used to show an alert message informing of the successful restore. When closed, the paywall was dismissed and the callback invoked.
https://github.com/RevenueCat/purchases-ios/blob/main/RevenueCatUI/Views/FooterView.swift#L237

[Paywalls] Fix onRestoreComplete callback not being called

---

Local.xcconfig.SAMPLE

Greatly improves #4795
Using double quotes for strings is set in stone for us, developers. But the strings in `xcconfig`'s files for Build Settings don't use quotes. This PR tries to break that habit only for the `Local.xcconfig` file.
Add some hints in `Local.xcconfig.SAMPLE` to prevent adding quotes in the Build settings specified in `Local.xcconfig`

Add no quotes hints to build settings in `Local.xcconfig.SAMPLE`

---

Sources/Error Handling/StoreKitErrorHelper.swift
Tests/StoreKitUnitTests/ProductsManagerTests.swift

Noticed that obtaining the store kit error description actually didn't try to get the store kit error when it was nested. I was able to reproduce in an existing test (by adding a new assertion), which gets fixed with the changes in this PR.

[Diagnostics] Fix store kit error description tracking

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerUIPreviewModeTests.swift
Tests/UnitTests/Mocks/MockSystemInfo.swift

In UI Preview mode, the SDK should only make the requests strictly required for the UI Preview mode functionality.
This PR just implements an early return with all `IntroEligibility` statuses set to `unknown`.

UI Preview mode: avoid intro eligibility request

---

RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift

This PR addresses GH issue https://github.com/RevenueCat/purchases-ios/issues/4813. Apple released iOS 18.4 beta 1 and Xcode 16.3, which introduces the [SubscriptionInfo](https://developer.apple.com/documentation/storekit/subscriptioninfo) typealias. This caused a name resolution conflict in `PurchaseInformation.swift` where the extension on `SubscriptionInfo` can't tell if it should resolve to `StoreKit.SubscriptionInfo` or `RevenueCat.SubscriptionInfo`.
This PR makes the extension's reference to `SubscriptionInfo` explicitly reference `RevenueCat.SubscriptionInfo`, which resolves the compilation issue.
Our iOS 18 CI jobs aren't using Xcode 16.3 yet, so just because this PR passes CI doesn't necessarily mean it will work. I've tested and confirmed that `RevenueCatUI` on this branch …

Fix SDK Compilation on Xcode 16.3/iOS 18.4 Beta 1

---

.gitignore

This helps those of us using/experimenting with [xcode-build-server](https://github.com/SolaWing/xcode-build-server). The `buildServer.json` file is machine-specific as it contains absolute paths so it's probably best to exclude it from source control.

Adds `buildServer.json` to `.gitignore`

---

Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh

After the changes in #4795, the CI was not able to set the API key for the PaywallsTester app properly
Fixes the issue
With this change, the CI edits the file `Constants.swift` in PurchasesTester by replacing
```swift
static let apiKey: String = {
Bundle.main.object(forInfoDictionaryKey: "REVENUECAT_API_KEY") as? String ?? ""
}()
```
with 
```swift
static let apiKey: String = {
"paywallstester_app_api_key"
}()
```

Correctly set PaywallsTester app API key by the CI

---

.circleci/config.yml
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

This adds a slack notification to all CircleCI jobs that error out. Currently posts to the #feed-circleci-ios-failures

Post error test results to Slack

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift

We shouldn't show the refund path if the product is within the trial period
Follow up of https://github.com/RevenueCat/purchases-ios/pull/4805

feat: Hide refund for purchases in trial period

---

Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
Tests/UnitTests/Mocks/MockRequestFetcher.swift

Fix crash on iOS 11 and 12 when compiling with Xcode 16 and instantiating an array with type @MainActor lambda
`var foo: [@MainActor @Sendable () -> Void] = []`

v4: Fix crash in iOS 11-12 when using MainActor

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
Sources/Purchasing/ProductsManager.swift
Tests/StoreKitUnitTests/ProductsManagerTests.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift

This adds `requestedProductIdsKey` and `notFoundProductIdsKey` properties to the `appleProductsRequest`. This won't be used by Grafana but will be in the future DW events.

[Diagnostics] Add `requestedProductIds` and `notFoundProductIds` to `appleProductsRequest`

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Logging/Strings/AnalyticsStrings.swift
Sources/Logging/Strings/Strings.swift
Sources/Paywalls/Events/PaywallEventsManager.swift
Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift

This week we realized some events were not being sent to the backend. Even more, when we tried to add it we realized they errored out.
Mimics https://github.com/RevenueCat/purchases-android/pull/2189 
This PR adds a basic test to just make sure nothing's broken Ideally, the list of events should be generated somehow, but for now this is enough IMO.
1. Refactor `PaywallEventsManager` to `EventsManager`
2. Move analytics debug logs from `Strings.paywalls` to `Strings.analytics`

chore: Add integration test for analytics events

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Misc/Codable/AnyEncodable.swift
Sources/Purchasing/ProductsManager.swift
Tests/StoreKitUnitTests/ProductsManagerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/TestHelpers/AnyEncodable+Equatable.swift
Tests/UnitTests/TestHelpers/DiagnosticsEvent+Equatable.swift

Some unit tests were flaky because of the use of `Set`s for Diagnostics events
This PR changes the `Set`s in DIagnostics events to be `Array`s, so that the order is predictable for tests. Note that the event parameters using `Set` were still being sent as `Array`s in the JSON anyways...
Ideally, we should find a way to limit the use of `Set`s in `AnyEncodable`, otherwise we might introduce flaky tests in the future.

Use array instead of sets in diagnostics events

---

Sources/Diagnostics/DiagnosticsFileHandler.swift
Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
Tests/UnitTests/Diagnostics/DiagnosticsFileHandlerTests.swift
Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift

If for any reason, an invalid entry line gets written into the diagnostics cache file, then duplicated events will potentially be sent.
This PR makes sure that the number of lines deleted always matches the number of lines read, even if some lines couldn't be decoded to `DiagnosticsEvent`.

Fix potential wrong count on diagnosis sync

---

RevenueCatUI/PaywallView.swift
RevenueCatUI/UIKit/PaywallViewController.swift
RevenueCatUI/View+PresentPaywall.swift
Sources/Purchasing/Offering.swift
Tests/APITesters/AllAPITests/SwiftAPITester/OfferingAPI.swift
Tests/UnitTests/Networking/Responses/BaseHTTPResponseTest.swift
Tests/UnitTests/Networking/Responses/CustomerInfoDecodingTests.swift
Tests/UnitTests/Networking/Responses/Fixtures/OfferingsWithPaywallComponents.json
Tests/UnitTests/Networking/Responses/GetIntroEligibilityDecodingTests.swift
Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
Tests/UnitTests/Networking/Responses/PaywallComponentsDataTests.swift
Tests/UnitTests/Networking/Responses/PaywallDataDecodingTests.swift
Tests/UnitTests/Networking/Responses/PostOfferDecodingTests.swift
Tests/UnitTests/Networking/Responses/ProductEntitlementMappingDecodingTests.swift
Tests/UnitTests/Networking/Responses/UIConfigDecodingTests.swift
Tests/UnitTests/Paywalls/PaywallDataMultiTierTests.swift
Tests/UnitTests/Paywalls/PaywallDataTests.swift
Tests/UnitTests/Purchasing/OfferingsTests.swift

Checking whether an `Offering` has a paywall can be confusing now that we have v1 and v2 paywalls.
* This PR adds the `hasPaywall` getter to `Offering` to make it easier to know whether an `Offering` has a paywall or not
* Related to this, I also used this PR to update the documentation of `PaywallView` (and related) that was implying `PaywallData` to mean "paywall", which is not true anymore since v2 paywalls.

`Offering` `hasPaywall` getter

---

RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
RevenueCatUI/Templates/V2/ViewHelpers/ProgressViewModifier.swift

Paywalls V2 "Restore Purchases" behavior didn't have any type of activity or progress indicator
- If purchase...
- Purchase buttons are disabled and show activity indicator
- Restore buttons are just disabled (and 0.35 opacity)
- If restore...
- Restore buttons are disabled and show activity indicator
- Purchase buttons are just disabled (and 0.35 opacity)
https://github.com/user-attachments/assets/1ef9b08a-4b80-4ba6-9354-20cd0a6519f5

Add activity indicator to restore purchases button behavior

---

.circleci/config.yml

- Run `all-tests` workflow on `main` and notify Slack if failures
- Cleaned up some duplicated jobs in between `all-tests` and `build-test`
- Invoked a job that we were not calling

Run `all-tests` on `main` and notify Slack

---

RevenueCatUI/CustomerCenter/ButtonStyles.swift
RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterNavigationOptions.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift

While working on kmp support for CustomerCenter, I realised there's no way to close programmatically the view. The close button does not work because it works with the environment dismiss
I'll need to update hybrid commons after this, and then kmp 🚀 
The PR adds `onCloseHandler` that overrides the environment dismiss behavior.
- Update `NavigationOptions`
- Update docs

feat: Add onClose handler support for CustomerCenter

---

Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json
Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithFailedVerificationResponse.1.json
Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithVerifiedResponse.1.json
Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift

The snapshot tests were using a different JSON encoding strategy than the SDK, in particular, for dates.
As an example, the `CustomerInfo` snapshot tests were mapping dates differently to what the SDK does (which maps them to its ISO8601 format) E.g. 
```JSON
"purchase_date" : -326323164
```
vs
```JSON
"purchase_date" : "1990-08-30T02:40:36Z"
```
These tests should encode objects with a format as similar as possible to the actual encoding format used in the SDK.
With this PR:
* The snapshots now use the ISO8601 date format
* Encoding objects in unit tests now uses a `JSONEncoder` that copies the properties from the SDK's `JSONEncoder.prettyPrinted`

Have snapshot tests use same encoding as SDK

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json

This PR fixes the Diagnostics JSON field name for the `eTagHit` parameter. 
It was being sent as `e_tag_hit`, whereas it should be `etag_hit`.

fix: diagnostics parameter key name

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/PurchasesDelegateHandler.swift
Examples/MagicWeatherSwiftUI/Shared/Sources/ViewModels/UserViewModel.swift

Now that we are going to allow users to download the SwiftUI sample app from Onboarding, we should make sure that it uses the most up-to-date APIs.
One area for improvement that we noticed was updating the `CustomerInfo` object from an `AsyncStream` instead of the delegate.

Update `customerInfo` from an `AsyncStream` instead of the `PurchasesDelegate` in the SwiftUI sample app

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift

This PR implements the `max_diagnostics_sync_retries_reached` diagnostics event

[Diagnostics] add `max_diagnostics_sync_retries_reached` event

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Diagnostics/Networking/DiagnosticsSynchronizer.swift
Tests/UnitTests/Diagnostics/DiagnosticsSynchronizerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift

This PR implements the `clearing_diagnostics_after_failed_sync` diagnostics event

[Diagnostics] add `clearing_diagnostics_after_failed_sync` event

---

Sources/Networking/Responses/CustomerInfoResponse.swift
Sources/Purchasing/VirtualCurrencyInfo.swift
Tests/UnitTests/Purchasing/CustomerInfoTests.swift

We recently changed the key that the backend returns containing the virtual currency balance in CustomerInfo from `amount` to `balance`. This PR switches the SDK from looking for `amount` to `balance`. This update is purely internal and doesn't affect the public API.
```
// CustomerInfo
{
// ...
"subscriber": {
// ...
"virtual_currencies": {
"WIL": {
"amount": 100
}
}
}
}
```
```
// CustomerInfo
{
// ...
"subscriber": {
// ...
"virtual_currencies": {
"WIL": {
"balance": 100
}
}
}
}
```
For testing, I've:
- Updated the automated CustomerInfo parsing tests
- Tested the change manually

Change Parsing of VirtualCurrencyInfo.balance from amount to balance

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/Mocks/MockOfflineCustomerInfoCreator.swift
Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift
Tests/UnitTests/OfflineEntitlements/OfflineCustomerInfoCreatorTests.swift

This PR implements the `entered_offline_entitlements_mode` diagnostics event

[Diagnostics] add `entered_offline_entitlements_mode` event

---

BackendIntegrationTests/BackendIntegrationTests-All-CI.xctestplan
BackendIntegrationTests/BackendIntegrationTests-All.xctestplan
BackendIntegrationTests/BackendIntegrationTests-CustomEntitlements.xctestplan
BackendIntegrationTests/BackendIntegrationTests-Offline.xctestplan
BackendIntegrationTests/BackendIntegrationTests-Other.xctestplan
BackendIntegrationTests/BackendIntegrationTests-SK1.xctestplan
BackendIntegrationTests/BackendIntegrationTests-SK2.xctestplan
BackendIntegrationTests/BackendIntegrationTests-Shedder.xctestplan
Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift
Tests/UnitTests/TestHelpers/TestLogHandler.swift

We need to be sure events are working as expected =)
I've tweaked the test to just call Purchases api. The only caveat is that the tracking for customer center async, and the one for paywalls is not, so I had to add an arbitrary sleep. Once this is merged, I can go with https://github.com/RevenueCat/purchases-ios/pull/4837
This will enable further refactors for PaywallEventsManager, like renaming it to support `FeatureEvent`
Test is only ignored in the offline test plan

chore: `EventsManagerIntegrationTests` working as expected

---

fastlane/Fastfile

Pushing the new pod is quite flaky, so we've introduced a new custom action that retries gracefully. It has already been tested https://github.com/RevenueCat/purchases-hybrid-common/pull/1081

feat: Use pod_push_with_error_handling instead of pod_push for pushing Pods

---

RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift

We need to keep up-to-date customer center after a successful restore
This PR just reloads the Customer Center after the restore works. I think we should not leave the screen in an inconsistent state, so if the restore works, but the load screen fails it will error out.
> There's room for a better UI effect, but this does the trick for now

feat: Refresh customer center and purchases after restore

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift

This PR:
- Adds the `sync_purchases_started` and `sync_purchases_result` events to `DiagnosticsTracker` (currently unused, will be in a follow-up PR).
- Refactors the code inside the `DiagnosticsTracker` to avoid some repetition

[Diagnostics] Add sync purchases tracking (part 1)

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Sources/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift
Tests/StoreKitUnitTests/PurchasesOrchestratorCommonTests.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift

This PR implements the apple_purchase_intent_received` diagnostics events

[Diagnostics] add `apple_purchase_intent_received` event

---

Sources/Purchasing/OfferingsManager.swift
Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

We were not doing `weak self` in the completion blocks for diagnostics. This fixes that. The chances of a leak here are small, considering these classes are usually singletons (unless the SDK is configured multiple times), but better to do it correctly.

Fix possible memory leaks with diagnostics completion blocks

---

Tests/UnitTests/Purchasing/Purchases/PurchasesDiagnosticsTrackingTests.swift

Unit tests were failing in targets that are not iOS due to the unit test for `presentCodeRedemptionSheet()` added in #4893. 
This PR fixes the issue by making the unit test for `presentCodeRedemptionSheet()` only run on iOS

Fix unit tests: make `presentCodeRedemptionSheet()` test only run on iOS

---

Sources/Diagnostics/DiagnosticsEvent.swift
Sources/Diagnostics/DiagnosticsTracker.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
Tests/UnitTests/Mocks/MockStoreKit1Wrapper.swift
Tests/UnitTests/Purchasing/StoreKit1WrapperTests.swift

This PR implements the `apple_transaction_queue_received` diagnostics events

[Diagnostics] add `apple_transaction_queue_received` event

---

Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift

New diagnostics tests added in #4894 were failing in iOS 15 because `isStoreKit2Available` returns `false` in iOS 15
This PR skips the new tests in iOS 15

Skip `TrialOrIntroPriceEligibilityCheckerSK2Tests` in iOS 15

---

RevenueCatUI/Templates/V2/PaywallsV2View.swift
RevenueCatUI/Templates/V2/ViewHelpers/BackgroundStyle.swift
RevenueCatUI/Templates/V2/ViewHelpers/DisplayableColor.swift
RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
Sources/Paywalls/Components/Common/Background.swift

Fit mode was not being recognized on background image property
- Pass fit mode into the background view modifier and apply it
- Add optional alignment property for root paywall background to align background to top
| Fit | Fill |
| <img width="303" alt="Screenshot 2025-03-19 at 3 37 41 PM" src="https://github.com/user-attachments/assets/5d81e36e-7bbd-4658-8ba1-dc5a59c10700" /> | <img width="297" alt="Screenshot 2025-03-19 at 3 38 08 PM" src="https://github.com/user-attachments/assets/3bbb2df1-8895-4709-b3c6-b2f0601e2b90" /> |

Fixing fit mode on background property

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift

I wanted to try and cover errors with `VerificationResult` similar to the conflict solved in #4814. But it looks like not only it's not needed but also it breaks compilation in iOS 15.
This PR removes the `RevenueCat` from `RevenueCat.VerificationInfo`

fix build issue in iOS 15

---

RevenueCat.xcodeproj/project.pbxproj
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterActionWrapperTests.swift

We've recently added preference keys to customer center without coverage.
This PR adds a basic check to verify that the preference keys + view modifier are working as expected.
Since https://github.com/RevenueCat/purchases-ios/pull/4882 needs SwiftTesting and Swift 6, we'll keep it in the XCTest world for now.

chore: Test action wrapper for customer center

---

RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
RevenueCatUI/Templates/V2/Components/Icon/IconComponentView.swift
RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift
RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift

Affected components: Carousel, Image, Icon and Stack.
Additionally, this PR fixes an issue with image padding which was being applied *after* the border, causing it to act as if it was additional margin.

[Paywalls] Extend the padding by border.width amount in components that support both

---

Sources/Diagnostics/DiagnosticsEvent.swift
Tests/UnitTests/Networking/Requests/DiagnosticsEventEncodingTests.swift
Tests/UnitTests/Networking/Requests/__Snapshots__/DiagnosticsEventEncodingTests/testEncoding.1.json

We were naming the key for the cache fetch policy as `cache_fetch_policy`, but we expected `fetch_policy`. This fixes the property name moving forward

[Diagnostics] Fix cache fetch policy key not matching specs

---

RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift

https://github.com/RevenueCat/purchases-ios/issues/4935
Allows feedback survey title to go to two lines

fix: Allow two lines for feedback survey title

---

Sources/Networking/Responses/CustomerInfoResponse.swift
Sources/Purchasing/VirtualCurrencyInfo.swift

We recently decided to limit the maximum value of a virtual currency's balance to be a 32-bit signed integer. With this new limitation in mind, there's no need to use an Int64 for `balance`, so this PR change this to be a generic Swift `Int` instead. This simplifies the API a bit since developers are generally more familiar with `Int`s than they are with `Int64`s.
Swift's `Int` is a 32-bit signed integer on 32-bit devices, and is a 64-bit signed integer on 64-bit devices [source](https://developer.apple.com/documentation/swift/int).
This is technically a breaking change, but since the virtual currency feature is still in beta, this is okay. 👍
NOTE: No changes to the API testers were required 👍

Use Swift Int for VirtualCurrencyInfo.balance

---

RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift

#4922 broke watchOS tests because we were building the previews on wathOS

Only preview `RestorePurchasesAlert` on iOS

---

Sources/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift

Addresses this issue: https://github.com/RevenueCat/purchases-ios/issues/4963
This PR removes `StoreKit2PurchaseIntentListenerType`'s `Identifiable` conformance to prevent crashes on iOS 16 & 17 when a purchase intent is received.

Remove Identifiable conformance from StoreKit2PurchaseIntentListenerType

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift

The `TextViewComponent` component could end up using localized values in the developer's app
Have the `TextViewComponent` use the `Text(verbatim:)` constructor so it doesn't attempt to localize anything
(This was _intended_ when developing this but was not done correctly)
| Before | After (with fix) |
| ![Simulator Screenshot - iPhone 16 Pro Max - 2025-04-09 at 09 47 34](https://github.com/user-attachments/assets/b46dba30-17e1-41fe-9f46-cb86a157b78f) | ![Simulator Screenshot - iPhone 16 Pro Max - 2025-04-09 at 09 47 01](https://github.com/user-attachments/assets/b9f72e75-adce-4286-bc1a-bbcecc70332b) |

Make Paywalls v2 Text use verbatim

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift

Fixes #4986
- Manually attempts to parse text with `AttributedString(markdown:)` and sets that into `Text`
- This prevents attempting to look up localized strings from bundle
- Falls back to using `Text(verbatim:)`
- If markdown failed to parse, probably more important to not localize
| Markdown | Invalid Markdown |
| <img width="631" alt="Screenshot 2025-04-14 at 11 51 27 AM" src="https://github.com/user-attachments/assets/0d0f9e5f-a8c3-4453-895b-12ba0f70b988" /> | <img width="635" alt="Screenshot 2025-04-14 at 11 51 34 AM" src="https://github.com/user-attachments/assets/9a0cf197-8694-4d12-8d20-6bd136a40f80" /> |

Fix Paywalls v2 Text component to not localized from bundle but support markdown

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Data/LoadPromotionalOfferUseCase.swift
RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+ActiveTransaction.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift

We've noticed that we have two different logics to find the active transaction. 
Entitlements are optional, so we shouldn't rely on those to find it. 
The correct way was in CustomerCenterViewModel, so I've extracted that into an extension.

fix: Unify finding active transaction for customer center

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift

Recent paywalls text component changes did not compile on iOS 15 with Xcode 14 (from #4990)
Added API and Swift version checks

Fix paywalls text component compilation for iOS 15

---

Sources/Paywalls/Components/PaywallTabsComponent.swift

Decoding the `TabControlType` gave errors such as
```
Paywall V2 Error: [
"componentsConfig": RevenueCat.PaywallComponentsData.EquatableError(
description: "typeMismatch(
Swift.Dictionary<Swift.String, Any>, 
Swift.DecodingError.Context(
codingPath: [
CodingKeys(stringValue: \"offerings\", intValue: nil), 
_CodingKey(stringValue: \"Index 45\", intValue: 45), 
CodingKeys(stringValue: \"paywallComponents\", intValue: nil), 
CodingKeys(stringValue: \"componentsConfig\", intValue: nil), 
CodingKeys(stringValue: \"base\", intValue: nil), 
CodingKeys(stringValue: \"stack\", intValue: nil), 
CodingKeys(stringValue: \"components\", intValue: nil), 
_CodingKey(stringValue: \"Index 2\", intValue: 2), 
CodingKeys(stringValue: \"control\", intValue: nil), 
CodingKeys(stringValue: \"type\", intValue: …
```

[Paywalls v2] Fixes decoding `TabControlType`

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift

The Magic Weather SwiftUI example app has a compilation error.
The extension on `SubscriptionPeriod` is ambiguous due to a name clash between `StoreKit.SubscriptionPeriod` and `RevenueCatSubscriptionPeriod`.
Applying these changes will specify the namespace, therefore fix the issue.

Fix Magic Weather SwiftUI compilation error

---

Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift

The Magic Weather SwiftUI example app has a compilation error.
The extension on `SubscriptionPeriod` is ambiguous due to a name clash between `StoreKit.SubscriptionPeriod` and `RevenueCatSubscriptionPeriod`.
Applying these changes will specify the namespace, therefore fix the issue.
Contributed by @pattogato at #4987

Fix Magic Weather SwiftUI compilation error by @pattogato at #4987

---

RevenueCatUI/CustomerCenter/ViewModels/RestorePurchasesAlertViewModel.swift
RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift

Injects the `CustomerCenterPurchasesType` into `RestorePurchasesAlertViewModel`, which was still missing after #4957

[Customer center] missing inject of Purchases provider

---

RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
Sources/Paywalls/Components/Common/PaywallComponentLocalization.swift

This code would produce a runtime crash when getting a `nil` url
```
func urlFromLid(_ urlLid: String) throws -> URL {
let urlString = try string(key: urlLid)
let url = URL(string: urlString)
if url == nil {
Logger.error(Strings.paywall_invalid_url(urlLid))
}
return url! // <-- Crash here
}
```

[Paywalls v2] fixes crash when getting invalid URL from paywall components localization

---

Sources/Support/DebugUI/ProductStatus+Icon.swift
Sources/Support/DebugUI/SDKHealthCheckStatus+Icon.swift
Sources/Support/DebugUI/SDKHealthStatus+Icon.swift
Sources/Support/HealthReport+Validate.swift

The builds are failing on CI when using Xcode 14. This is due to some code recently added that uses some newer features of Swift that are not available in Xcode 14.

fix compilation issues in older versions of Xcode

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Support/DebugUI/DebugContentViews.swift
Sources/Support/DebugUI/DebugViewModel.swift
Sources/Support/DebugUI/ProductStatus+Icon.swift
Sources/Support/DebugUI/SDKHealthCheckStatus+Icon.swift
Sources/Support/DebugUI/SDKHealthStatus+Icon.swift
Sources/Support/HealthReport+Validate.swift
Sources/Support/PurchasesDiagnostics.swift
Sources/Support/SDKHealthError+CustomNSError.swift
Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift

We recently introduced breaking changes to the `PurchasesDiagnostics` API through the `testSDKHealthCheck` method. We have decided to instead make the changes backwards compatible and instead deprecate the existing method.

Fix Backwards compatibility errors introduced by new `testSDKHealthCheck` implementation

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift

We're getting this warning:
```
\CustomerCenterViewModel.manageSubscriptionsSheet is isolated to the main actor. Accessing it via Binding from a different actor will cause undefined behaviors, and potential data races; This warning will become a runtime crash in a future version of SwiftUI.
Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.
Publishing changes from background threads is not allowed; make sure to publish values from the main thread (via operators like receive(on:)) on model updates.
```
I missed that the SwiftUI extension is marked as `non isolated`, and it's causing this warning when displaying the manage subscriptions view.  This wraps the binding that comes from …

fix: Wrap viewmodel binding into another binding

---

RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift

Quick follow-up to #4990 which seems to have resulted in ignoring blank lines.
Blank lines are ignored.
`AttributedString` seems to ignore `\n\n`, or even `  \n  \n`. 
Using `InterpretedSyntax.inlineOnly`. I tried `InterpretedSyntax.inlineOnlyPreservingWhitespace` as well, and both seem to fix it. I went with the former as that seemed closer to what we had, but would be totally fine with the latter as well.

[Paywalls v2] Fixes blank lines not showing up

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Helpers/StoreProductDiscount+Extensions.swift
Sources/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
Sources/Purchasing/StoreKitAbstractions/Test Data/TestStoreProductDiscount.swift
Tests/RevenueCatUITests/CustomerCenter/FeedbackSurveyViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/Mocks/MockStoreProductDiscount.swift
Tests/UnitTests/Mocks/MockStoreProductDiscount.swift
Tests/UnitTests/Purchasing/ProductRequestDataExtensions.swift

While working on the new billing information for Customer Center subscriptions, I realised I need this protocol in `RevenueCatUI`
Internally expose `StoreProductDiscountType` using `@_spi`

chore: Make StoreProductDiscountType @__spi public

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
RevenueCatUI/Templates/V2/Components/Button/ButtonSheetView.swift

This PR adds a bottom sheet view that can be used as a modifier on a view (like a button) to show a sheet.
https://github.com/user-attachments/assets/1c46b2df-a7a1-4264-8d78-5a57f57a82b4
You can display the sheet with the following view modifier:
```swift
.bottomSheet(isPresented: $isPresented) {
// Content
VStack(spacing: 20) {
Text("Sheet Content")
.font(.title)
Text("This is a simple sheet preview")
}
.padding()
}
```
You can also customize the sheet's appearance and behavior with by providing a `BottomSheetConfig` object:
```swift
.bottomSheet(
isPresented: $isPresented,
config: BottomSheetConfig(
backgroundColor: Color.blue,
screenHeightPercentage: 0.5,
tapOutsideToDismiss: false
)
) {
VStack(spacing: 20) {
Text("Sheet Content")
.font(.title)
Text("This is a simple sheet preview")
} …
```

Add Bottom Sheet View

---

RevenueCatUI/Templates/V2/Components/Carousel/CarouselComponentView.swift
Sources/Paywalls/Components/PaywallCarouselComponent.swift

We want to add support for these type of animations. 
In order to not break previous implementations, we're adding a few if / else here and there.
We can't use modern `withAnimation:complete` API so we had to go the old way. We animate the opacity, and simply don't animate the offset if the fade transition is turned on.
https://github.com/user-attachments/assets/04125683-beb3-4415-bb7b-de0693a7cbb2
Excellent team work @ajpallares @hiddevdploeg @polpielladev 🚀

feat: Introduce fade transition for loop animated CarouselView

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Data/Transaction.swift
RevenueCatUI/CustomerCenter/Utilities/IdentifiableURL.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift

After reverting the subscription list, I'm re-applying it in pieces to cleanup and track down the issue.
Add `managementURL` to `PurchaseInformation` for non appstore transactions.
Cancel subscription will open the URL if available.

Add management URL to PurchaseInformation

---

RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+ActiveTransaction.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

After https://github.com/RevenueCat/purchases-ios/pull/5078, I am bringing back the subscription list.
Add `expirationDate` and `renewalDate` to `PurchaseInformation`. This will be used as part of the new billing information label for each subscription.

Add expirationDate and renewalDate to PurchaseInformation

---

RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift

Follow-up of https://github.com/RevenueCat/purchases-ios/pull/5085
Use the instance dateFormatter instead of default one.

Use dateFormatter inside PurchaseInformation

---

RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift

We want to show the whole list of active subscriptions, instead of just one purchase with the earliest expiry date.
Compute array of active subscriptions as it was done [here](https://github.com/RevenueCat/purchases-ios/pull/5050) before reverting the whole feature.
In order to not break the functionality, I've computed the array and left the code for the active subscription still there. I'll remove that part once I introduce the views.
Note that purchases that are not subscriptions are not in the `activeSubscriptions` array.
Introduce views, and integrate with CustomerCenter

Compute active subscriptions for CustomerCenter

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift

We want to show the whole list of active subscriptions, instead of just one purchase with the earliest expiry date.
Introduce PurchaseInformationCardView as a new preview for a subscription. Note that this view is not used yet, as it will be used in the new subscription list view
Introduce views, and integrate with CustomerCenter

Introduce PurchaseInformationCardView

---

Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift

Flaky tests
This PR fixes the flakiness of 2 unit tests that fail regularly:
1. `StoreKit2TransactionListenerDiagnosticsTests`'s `testTracksDiagnosticsForRenewals()`: which was expecting exactly 1 transaction diagnostics event, but due to the `testSession.timeRate` being set to `.oneRenewalEveryTwoSeconds`, more than one renewal can happen during the test. I've relaxed the condition to expect at least 1 transaction diagnostics event with the expected parameters.
2. `PurchasesConfiguringTests`'s `testOfflineCustomerInfoDisabledForCustomEntitlementsComputation()` was crashing due sometimes due to the SDK being configured for Customer Entitlements Computation without an App User ID (see these lines https://github.com/RevenueCat/purchases-ios/blob/fd893d2a34460525c6c48891018fe76797acef89/Sourc …

Fix some flaky tests

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift

We want to display a list of active subscriptions in Customer Center. 
To avoid opening a huge PR, I'm splitting it into smaller pieces. This PR contains:
- `BaseManageSubscriptionViewModel` that's pretty much the existing `ManageSubscriptionViewModel`
- `SubscriptionDetailViewModel` that will be the new subscription detail screen
- `SubscriptionListViewModel` to handle the list, that will also inherit `BaseManageSubscriptionViewModel`
> I've duplicated the tests from `ManageSubscriptionViewModel` to `BaseManageSubscriptionViewModel` to make sure the logic works. Once finished, I'll delete the old code in one PR

Introduce SubscriptionDetailViewModel & BaseManageSubscriptionViewModel

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Views/ScrollViewWithOSBackground.swift

We want to move out from Lists and start using ScrollViews in CustomerCenter.
Introducing a ScrollView with the background already set to the OS style. See https://github.com/RevenueCat/purchases-ios/pull/5101 how it's used

Introduce ScrollViewWithOSBackground to reuse in Customer Center Views

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
RevenueCatUI/CustomerCenter/Mocks/MockCustomerCenterStoreKitUtilities.swift
RevenueCatUI/CustomerCenter/Mocks/MockLoadPromotionalOfferUseCase.swift
RevenueCatUI/CustomerCenter/Mocks/PurchaseInformationFixtures.swift

Its not possible to mock `CustomerCenterPurchasesType` for previews, because the mock is in the test target.
This PR moves the code around from the test target to the main target, so we can mock previews.

Move RevenueCatUI CustomerCenter mocks from test target to RevenueCatUI

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentViewModel.swift
RevenueCatUI/Templates/V2/Localizations/LocalizationDictionaryExtensions.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/ButtonWithFooterPreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/PurchaseButtonInPackagePreview.swift
RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/Template1Preview.swift
RevenueCatUI/Templates/V2/ViewHelpers/NavigatetoURL.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
Sources/Paywalls/Components/Common/PaywallComponentLocalization.swift
Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
Tests/UnitTests/Paywalls/Components/PurchaseButtonComponentTests.swift

Allow custom url on paywalls v2 purchase button for web checkout
`PurchaseButtonComponent` needed a more complex structure than the `action: Action?` enum to work better with web checkout and custom web checkout url
- New `method: Method?` property added as a successor to `action: Action?` (essentially deprecated)
- `inAppCheckout`
- `webCheckout(WebCheckout)`
- `autoDimiss: Bool?`
- `openMethod: URLMethod?` 
- `webProductSelection(WebCheckout)`
- `autoDimiss: Bool?`
- `openMethod: URLMethod?`
- `customWebCheckout(CustomWebCheckout)`
- `autoDimiss: Bool?`
- `openMethod: URLMethod?`
- `customUrl: CustomerURL`
- `url: LocalizationKey`
- `packageParam: String?`
- Added support for open method (external or in-app browser)
- Added unit tests for deserializing `PurchaseButtonComponent`
- Added …

Allow custom url on purchase button

---

RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift

When merging main into the `virtual-currency-dev` branch, we accidentally broke a few of the `ManageSubscriptionView` previews that show the virtual currency balances. This PR fixes the previews by modifying the mocked customer center config to set `displayVirtualCurrencies` to true.

Fix ManageSubscriptionView Virtual Currency Previews in Customer Center

---

Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesDiagnosticsAPI.swift

We recently realised that, while we deprecated a method in `PurchasesDiagnostics`, we never added API Tests for the API that replaces it.
This PR adds API tests to make sure that backwards compatibility is preserved on that method going forward.

[DX-404] Adds API Tests for SDK Health Report

---

Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesDiagnosticsAPI.swift

Some of the new APIs for the new check SDK health APIs are `DEBUG` only. This is causing the API tests added in #5117 to fail because the `DEBUG` check is missing when testing these new APIs.
This PR adds the `#if DEBUG` check to the corresponding API tests.

Add DEBUG check to SDK Health API tests

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionButtonsView.swift
RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionsListView.swift
RevenueCatUI/CustomerCenter/Views/CompatibilityLabeledContent.swift
RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift

We're using `List` instead of `ScrollView`, and we want to do the opposite. 
Create a duplicate ButtonsView inspired in `ManageSubscriptionsButtonsView` so I can keep this PR as small as possible. 
After merging this, I can go with https://github.com/RevenueCat/purchases-ios/pull/5121 and use `PurchaseInformationCardView` in the same way its used in `ActiveSubscriptionsListView` (inside a scrollview)
I'll delete the old `ManageSubscriptionsButtonsView` once this is places everywhere.

Introduce ActiveSubscriptionButtonsView to use it inside a scrollview

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift

We need to show the list if there's at least more than one purchase. 
The old code checks only for subscription. This fix now takes into account both, and adds tests for it.

Show list if all purchases together are more than one

---

RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift

Before showing different kind of purchases, we weren't showing restore purchases. Now we do, so we need support for the overlay feedback.
- Bring back the overlay

Add restore overlay to RelevantPurchasesListView

---

RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift

After re-designing `ActiveSubscriptionButtonsView` I missed updating the UI for contact support button.
This PR matches that, and now both buttons look neat 💅

Fix contact support button UI to match ButtonsView

---

RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift

While testing non-consumables for CustomerCenter, I realized change plans path makes no sense for lifetime.
Add filter for it, and basic test.

Filter changePlans path for lifetime purchases in CustomerCenter

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Extensions/CustomerInfo+SeeAllPurchases.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseHistoryViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift

In the old and new version, the see all purchases was being shown even if there was no more new data. This tweaks that, and takes into account what's being shown.
Add extension to `CustomerInfo` to decide if the button should be shown.

Dont show `see all purchases` button if there's nothing else to show

---

RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Data/Transaction.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift

The long term goal is to delete `PurchaseInfo` from `PurchaseHistory`, in favor of using `PurchaseInformation`. This info is not available for PurchaseInformation right now.
- Add `ownershipType` to `PurchaseInformation`

Add ownership type to PurchaseInformation

---

RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesListSection.swift
RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesScrollViewWithOSBackgroundSection.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift

In the current implementation of the virtual currency feature in the Customer Center, SwiftUI logs the following warning in the console when the `VirtualCurrenciesListSection` and `VirtualCurrenciesScrollViewWithOSBackgroundSection` is displayed:
```
Do not put a navigation destination modifier inside a "lazy” container, like 
`List` or `LazyVStack`. These containers create child views only when 
needed to render on screen. Add the navigation destination modifier 
outside these containers so that the navigation stack can always see 
the destination. There's a misplaced 
`navigationDestination(isPresented:destination:)` modifier presenting 
`VirtualCurrencyBalancesScreen`. It will be ignored in a future release.
```
This is because the navigationDestination is inside the section view, …

Fix Customer Center VC Navigation Warnings

---

Tests/UnitTests/Misc/TimingUtilTests.swift

Continues the work of #5104
[These](https://circleci.com/gh/RevenueCat/purchases-ios/326466) flaky tests
Fixes some flaky tests in `TimingUtilAsyncTests`, where the tests were checking that no messages were being logged and sometimes some logs from other tests were causing the tests to fail.
Now, the tests only fail if the logs contain the specific message that is expected not to be logged.

Fix some flaky tests (Part 3)

---

RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift

We did a round of testing with Kike, and this came out.
- Filter .missingPurchase only if the detail is not the root. If the detail is the second screen, then don't show it.
- Add icon in the additionalInfo HStack
- Fix section titles for RelevantList
- Dont show consumable price next to the chevron (only below the title)

Minor UI tweaks for CustomerCenter 2.0

---

RevenueCatUI/CustomerCenter/ButtonStyles.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift

"See all button" is not correctly highlighted when tapping on it. This adds a button style that takes into account the pressed state.
- Use button style for both buttons that are inside the scrollview 💅 
- Apply tint to feedback survey

Introduce CustomerCenterButtonStyle to highlight CustomerCenter buttons

---

.circleci/config.yml

Each Circle CI job that needs to install Ruby 3.2.0 (that is most of the jobs) takes ~2 minutes to install Ruby
This PR adds the Ruby installation folder in the cache of bundle dependencies so that the Install Ruby 3.2.0 step does not really need to do anything, saving the ~2 minutes for (almost) every Circle CI job
You can see this working in [this past workflow](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/27647/workflows/32495c87-cf7b-45b4-a562-31d2c694b77a)

CircleCI: save Ruby 3.2.0 installation in cache

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift

With @ajpallares we noticed that the buttons were reloading on selection. This addressed it
While the detail computes it for every purchase selected, the list now just passes `nil` to it.
https://github.com/user-attachments/assets/36bb4194-2e41-4559-a58f-2eefe40324f2

fix: Do not reload actions when selecting purchase

---

Examples/rc-maestro/Tuist/Package.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift

While doing the last testing round, I noticed the detail wasn't reloading properly:
- The view uses it's own published property that needs to be reloaded
1. Reposition where we update customer info in CustomerCenterViewModel
2. Use combine to subscribe to updates
3. publisher method in customer center view model
https://github.com/user-attachments/assets/945d1873-2b63-44cf-a858-003dadb0df2e
I think the ultimate solution would be what we've discussed, and have a CustomerInfoViewModel that only handles:
- active subs
- other purchases
- selected purchase
With that, we can remove the `purchaseInformation` published property from any other StateObject, and rely only on `CustomerInfoViewModel` to handle refreshing

reload customer center after re-syncing customer info

---

Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfiguration.storekit
Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/FallbackNoSubscriptionsView.swift

We're moving away from lists, and every screen should follow the same structure. 
- Use scrollview as other screens
- Remove the use of configuration, since this screen is a fallback
- Renamed screen to reflect the correct use of it + comment

Refactor NoSubscriptionsView in CustomerCenter

---

RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift

Cleanup after the release
- Delete unused `durationTitle` from `PurchaseInformation`

Remove unused durationTitle from PurchaseInformation

---

Package.swift
RevenueCat.podspec
RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI.podspec
Sources/Identity/CustomerInfo.swift
Sources/Networking/Responses/CustomerInfoResponse.swift
Sources/Purchasing/VirtualCurrencyInfo.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCCustomerInfoAPI.m
Tests/APITesters/AllAPITests/ObjcAPITester/RCVirtualCurrencyInfoAPI.h
Tests/APITesters/AllAPITests/ObjcAPITester/RCVirtualCurrencyInfoAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/CustomerInfoAPI.swift
Tests/APITesters/AllAPITests/SwiftAPITester/VirtualCurrencyInfoAPI.swift
Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncoding.1.json
Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithFailedVerificationResponse.1.json
Tests/UnitTests/Networking/Responses/__Snapshots__/CustomerInfoDecodingTests/testEncodingWithVerifiedResponse.1.json
Tests/UnitTests/Purchasing/CustomerInfoTests.swift

The ENABLE_VIRTUAL_CURRENCIES compiler flag was getting in the way of RevenueCatUI tests in CI, so this PR removes them

remove vc compiler flag

---

Sources/Support/SDKHealthError+CustomNSError.swift
Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift

This PR introduces some improvements to the descriptions that we associated with SDK Health errors.
These changes inspired by [Wix's When life gives you lemos write better error messages article](https://wix-ux.com/when-life-gives-you-lemons-write-better-error-messages-46c5223e1a2f).

Improve descriptions for SDK Health errors

---

RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift

Ignoring all safe areas was causing the top safe area to not be respected when presenting a paywall in full screen.

[Paywalls] do not ignore all safe areas when applying the zstack in bottom sheet

---

Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Mocks/MockDateProvider.swift
Tests/UnitTests/Mocks/MockDeviceCache.swift
Tests/UnitTests/Mocks/MockFileReader.swift
Tests/UnitTests/Mocks/MockInMemoryCachedOfferings.swift
Tests/UnitTests/Mocks/MockReceiptFetcher.swift
Tests/UnitTests/Mocks/MockStoreKit2TransactionListenerDelegate.swift
Tests/UnitTests/Mocks/MockStoreProductDiscount.swift
Tests/UnitTests/Mocks/MockSubscriberAttributesManager.swift
Tests/UnitTests/Mocks/MockSystemInfo.swift

I don't have all the context on why these are missing, but here they are.
Add missing imports

add missing import Foundation in Tests

---

RevenueCat.xcodeproj/project.pbxproj
Tests/UnitTests/Misc/StoreKitVersionTests.swift

While trying to fix tests for the workspace, I noticed this is not compiling.
- Use ` effectiveVersion.debugDescription` instead of `versionString` that does not exist.
- Add test to `UnitTests` testplan

Use effectiveVersion.debugDescription in StoreKitVersionTests

---

RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift

https://github.com/RevenueCat/purchases-ios/issues/5219
Use environment `openURL` instead of SFSafariVC to open the mailto URL

Use env openURL instead of SFSafariVC to open mailto

---

Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
Tests/UnitTests/Misc/StoreKitVersionTests.swift

We found in https://github.com/RevenueCat/purchases-ios/pull/5213 that `StoreKitVersionTests` weren't being run. They're now failing in main for iOS 15 only. They're failing because we treat StoreKit 2 as being unavailable on iOS 15. 
I believe that what happened is that the `StoreKitVersionTests` file was excluded from the `UnitTests` test plan before we made StoreKit 2 exclusive to iOS 16+, we didn't update these tests, and didn't notice that they were broken because the tests weren't being run.
This PR updates the tests in `StoreKitVersionTests` to reflect that we treat StoreKit 1 as unavailable on iOS 15.

Fix StoreKitVersionTests on iOS 15

---

Sources/DocCDocumentation/DocCDocumentation.docc/CEC_V5_API_Migration_guide.md
Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md

Some links in our v4 -> v5 migration guides are broken. This PR fixes those broken links.

Fix broken URLs in 4 -> 5 Migration Guides

---

RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift

https://github.com/RevenueCat/purchases-ios/issues/5223
As the alert is showed using an overlay, we need to make sure the state is reset before showing it again.

Reset alertType state for RestorePurchasesAlertViewModel before dismissing

---

RevenueCatUI/Purchasing/MockPurchases.swift
RevenueCatUI/Purchasing/PaywallPurchasesType.swift
RevenueCatUI/Purchasing/PurchaseHandler.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewHelpers/DisplayableColor.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
RevenueCatUI/Views/LoadingPaywallView.swift
Sources/Logging/Strings/PaywallsStrings.swift
Sources/Networking/Responses/RevenueCatUI/UIConfig.swift
Sources/Paywalls/PaywallCacheWarming.swift
Sources/Paywalls/PaywallFontManagerType.swift
Sources/Purchasing/Purchases/Purchases.swift

When a paywall fails to load a custom font, the font should be tried to be downloaded when applicable
When a paywall fails to load, `Purchases` gets notified and triggers the font download

Trigger download of font that failed to load in a paywall

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/ViewModelHelpers/UIConfigProvider.swift
Sources/Logging/Strings/PaywallsStrings.swift
Sources/Networking/Responses/RevenueCatUI/UIConfig.swift
Sources/Paywalls/Components/PaywallTextComponent.swift
Sources/Paywalls/PaywallCacheWarming.swift
Sources/Paywalls/PaywallFontManagerType.swift
Tests/UnitTests/Networking/Responses/UIConfigDecodingTests.swift
Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift

Support new (backwards-compatible) JSON Format for `UIConfig.FontInfo`. Example:
```json
"font_id": {
"android": {
"family": "Good Sans",
"hash": "1234567890qwertyuiop",
"style": "normal",
"type": "name",
"url": "https://fonts.pawwalls.com/font_file.otf",
"value": "GoodSans-Light",
"weight": "300"
},
"ios": {
"family": "Good Sans",
"hash": "1234567890qwertyuiop",
"style": "normal",
"type": "name",
"url": "https://fonts.pawwalls.com/font_file.otf",
"value": "GoodSans-Light",
"weight": "300"
},
"web": {
"family": "Good Sans",
"hash": "1234567890qwertyuiop",
"style": "normal",
"type": "name",
"url": "https://fonts.pawwalls.com/font_file.otf",
"weight": "300"
}
},
```

New schema for `UIConfig.FontInfo`

---

RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift

While writing tests to verify the state of the card after a successful / unsuccessful promo offer, I need an id to validate multiple subs.
- Add identifier to card

Add accessibility identifier to PurchaseCardView

---

.circleci/config.yml
.gitmodules

We added a submodule to a private repo in order to perform validation of paywalls. However, this breaks SPM, which tries to clone all submodules, even if devs don't have access to it. This just removes the submodules temporarily, and makes jobs that use it fail

Remove submodules temporarily to fix SPM

---

.gitmodules
Dangerfile

Preventing adding git submodules in the future (which cause SPM not to be able to allow the dependency when the submodule is private)
Adds a danger rule that fails if it detects a submodule in the repository

Add Danger rule to avoid submodules

---

Sources/Purchasing/StoreKit2/StoreKit2PurchaseIntentListener.swift

Xcode 26 Beta 1 changed the minimum versions where `StoreKit.PurchaseIntent` `id` property is available.
* In Xcode 16, it was available in iOS 16.4+, macOS 14.4+
* In Xcode 26, it was available in iOS 18.0+, macOS 15.0+
Conditionally require `id` in `StoreKit.PurchaseIntent` depending on the compiler version

Fix Xcode 16 compilation error

---

.circleci/config.yml

CI for `run-test-ios-14` was failing when installing Mint
> error: 'mint-0.18.0': package 'mint-0.18.0' is using Swift tools version 5.9.0 but the installed version is 5.7.1
> Error: You are using macOS 12.
> We (and Apple) do not provide support for this old version.
Mint 0.17.5 is used in this CI job as newer versions of Mint don't support macOS 12

Use Mint 0.17.5 for `run-test-ios-14` CI job

---

Tests/UnitTests/OfflineEntitlements/CustomerInfoResponseHandlerTests.swift

Follow-up of https://github.com/RevenueCat/purchases-ios/pull/5199
Update sample CustomerInfo for tests to make sure decoding is_sandbox works.

Update CustomerInfo sample with is_sandbox to make sure it works

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/PromotionalOfferViewModel.swift
RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
Tests/RevenueCatUITests/CustomerCenter/PromotionalOfferViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Tests/RevenueCatUITests/Mocks/MockTransaction.swift

While working on removing internal use of preference keys, I noticed this was not being triggered.
- Move action wrapper call to `PromotionalOfferViewModel`
- delete unused `BaseManageSubscriptionViewModel.handleDismissPromotionalOfferView`
- add missing test

Trigger promotional offer callback from `PromotionalOfferViewModel`

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift

We got a report of markdown in paywalls not being rendered correctly in iOS 15
This PR enables markdown in `TextComponentView` for iOS 15 and watchOS 8.

Enable markdown in paywalls in iOS 15 and watchOS 8

---

RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/ViewModels/PurchaseHistory/PurchaseInformation+History.swift
RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift

We're working on refining `PurchaseInformation`
`isActive` does not make much sense for non subscriptions, so we're renaming it to `isExpired` instead.

Renamed isActive to isExpired in PurchaseInformation

---

Tests/BackendIntegrationTests/EventsManagerIntegrationTests.swift

Some backend tests were failing after many APIs were made `@_spi` in #5270 
This PR adds the missing `@_spi` mark to an import to fix compilation of backend tests

Add missing `@_spi` to import in backend tests

---

RevenueCatUI/Templates/V2/Components/Image/ImageComponentView.swift

Sometimes the size of the parent view can change after the initial layout. This can happen more often when using [PaywallViewController](https://github.com/RevenueCat/purchases-ios/blob/main/RevenueCatUI/UIKit/PaywallViewController.swift) because the `UIHostingController` can change size after being added to the parent VC and having its AutoLayout constrains set.
With this change, we still only show the image after we've received an initial max width, but we update it when it changes.
Should fix https://github.com/RevenueCat/purchases-ios/issues/5285

[Paywalls] Update ImageComponent max width after initial layout if it changes.

---

RevenueCatUI/Templates/V2/Localizations/LocaleFinder.swift
Tests/RevenueCatUITests/PaywallsV2/LocaleFinderTests.swift

Found a bug where displaying a paywall with the only Spanish localization being `"es_MX"` would not show some localization strings (device region: Spain, preferred languages: es, en_US)
In this case, the server's `ui_config.localization` contains `"es_419"` (UN M.49 standard for the Latin America and the Caribbean region) but no `"es_MX"`. With the existing implementation, the SDK was not able to match `"es_MX"` with `"es_419"`.
This PR adds an extra step when trying to find the matching locale from `UIConfig.localizations`. As a last resort, it tries to find a key in `ui_config.localization` with matching language and script.

Fix paywall locale receiving UN M.49 standard localization

---

Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
Sources/Misc/Concurrency/Purchases+async.swift
Sources/Purchasing/Purchases/Purchases.swift
Tests/APITesters/AllAPITests/CustomEntitlementComputationSwiftAPITester/PurchasesAPI.swift

This PR exposes the following functions to the SDK's Custom Entitlements Computation Mode:
```swift
func checkTrialOrIntroDiscountEligibility(productIdentifiers: [String], completion: @escaping ([String: IntroEligibility]) -> Void)
func checkTrialOrIntroDiscountEligibility(productIdentifiers: [String]) async -> [String: IntroEligibility]
func checkTrialOrIntroDiscountEligibility(packages: [Package]) async -> [Package: IntroEligibility]
func checkTrialOrIntroDiscountEligibility(product: StoreProduct, completion: @escaping (IntroEligibilityStatus) -> Void)
func checkTrialOrIntroDiscountEligibility(product: StoreProduct) async -> IntroEligibilityStatus
```
It also adds those functions to the CEC API tester, and adds a button to the CEC example app to test the functionality.
These changes …

Add Intro Eligibility Functions to CEC Mode

---

Sources/Purchasing/Purchases/Purchases.swift

While working on enabling custom entitlements for tuist, I had this compilation error.
Use `NewErrorUtils` instead of `RevenueCat.ErrorUtils`
Apparently this was already a thing:
```swift
/// Necessary because `ErrorUtils` inside of `Purchases` finds the obsoleted type.
private typealias NewErrorUtils = ErrorUtils
```

Use NewErrorUtils instead of RevenueCat.ErrorUtils

---

Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Sources/Virtual Currencies/VirtualCurrencyManager.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCPurchasesAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/PurchasesAPI.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Mocks/MockVirtualCurrencyManager.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesVirtualCurrenciesTests.swift
Tests/UnitTests/Virtual Currencies/VirtualCurrencyManagerTests.swift

Adds `Purchases.cachedVirtualCurrencies` as a computed property to allow developers to access the cached virtual currencies if they're present, regardless of whether the cache is stale or not.

Add Purchases.cachedVirtualCurrencies

---

RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/RelevantPurchasesListViewModel.swift
RevenueCatUI/CustomerCenter/ViewModels/SubscriptionDetailViewModel.swift
RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/SubscriptionDetailViewModelTests.swift

After a discussion in the https://github.com/RevenueCat/purchases-ios/pull/5108's review, we decided to revert the change of making the view models in `RelevantPurchasesListView` and `SubscriptionDetailView` from `StateObject` to `ObservedObject`. This PR accomplishes this by using the `VirtualCurrencies` object in the `CustomerCenterViewModel` in each of those views instead of injecting it directly in the views' constructors.
**Changes:**
- Makes `RelevantPurchasesListView.viewModel` a `@StateObject` again
- Makes `SubscriptionDetailView.viewModel` a `@StateObject` again
- In both `RelevantPurchasesListView` and `SubscriptionDetailView`, reference the virtual currencies in the `CustomerCenterViewModel`
- Updated automated tests
- Manually tested each screen that the virtual currencies …

Use VCs in CustomerCenterViewModel

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Networking/Backend.swift
Sources/Networking/HTTPClient/HTTPRequestPath.swift
Sources/Networking/InternalAPI.swift
Sources/Networking/Operations/HealthReportAvailabilityOperation.swift
Sources/Networking/Operations/HealthReportOperation.swift
Sources/Networking/Responses/HealthReportAvailabilityResponse.swift
Sources/Networking/Responses/HealthReportResponse.swift
Sources/Purchasing/Configuration.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Sources/Support/DebugUI/DebugViewModel.swift
Sources/Support/HealthReport+Validate.swift
Sources/Support/PaymentAuthorizationProvider.swift
Sources/Support/PurchasesDiagnostics.swift
Sources/Support/SDKHealthError+CustomNSError.swift
Sources/Support/SDKHealthManager.swift
Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
Tests/UnitTests/Misc/SDKHealthManagerTests.swift
Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

In another effort to reduce the amount of 'Empty Offerings' reports that we get, we want to let users know of configuration issues whenever they run a `DEBUG` build.
For this reason, we would like to run the SDK Health Check on debug builds. This is controlled with a configuration value, that is `false` by default, and can be turned on by the user at any time.
**✅ Successful configuration (No Warnings)**
**✅ Successful configuration (Warnings)**
**❌ Failed configuration**

[DX-457] Log the SDK configuration report on every `#DEBUG` run

---

Sources/Purchasing/Purchases/Purchases.swift

Some tests were failing due to the `runHealthCheckIfInForeground` retaining the `Purchases` instance until the health check was completed.
This PR prevents the `runHealthCheckIfInForeground` from retaining the `Purchases` instance

fix `Purchases` temporary leak when running SDK health check

---

RevenueCat.xcodeproj/project.pbxproj
Sources/Networking/Backend.swift
Sources/Networking/HTTPClient/HTTPRequestPath.swift
Sources/Networking/InternalAPI.swift
Sources/Networking/Operations/HealthReportAvailabilityOperation.swift
Sources/Networking/Responses/HealthReportAvailabilityResponse.swift
Sources/Networking/Responses/HealthReportResponse.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Sources/Support/DebugUI/DebugViewModel.swift
Sources/Support/HealthReport+Validate.swift
Sources/Support/PaymentAuthorizationProvider.swift
Sources/Support/PurchasesDiagnostics.swift
Sources/Support/SDKHealthError+CustomNSError.swift
Sources/Support/SDKHealthManager.swift
Tests/UnitTests/Misc/PurchasesDiagnosticsTests.swift
Tests/UnitTests/Misc/SDKHealthManagerTests.swift
Tests/UnitTests/Mocks/MockBackend.swift
Tests/UnitTests/Mocks/MockPurchases.swift
Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift

We recently had to revert the changes as we noticed some signature verification warnings and some increased flakiness in the Backend Integration tests.
These issues have now been addressed:
- Changed the signature verification from the `health_report_availability` endpoint: https://github.com/RevenueCat/khepri/pull/13783
- The unit test flakiness was not caused by the Health SDK, but they were aggravated by introducing more asynchronous behaviour. @ajpallares recently fixed the flakiness for the existing unit test: https://github.com/RevenueCat/purchases-ios/pull/5356

[DX-457] Re-apply Health SDK logging on app launch

---

Sources/Networking/Backend.swift
Sources/Networking/InternalAPI.swift
Sources/Networking/Operations/HealthReportAvailabilityOperation.swift
Sources/Networking/Operations/HealthReportOperation.swift
Sources/Networking/Responses/HealthReportResponse.swift
Sources/Purchasing/Purchases/Purchases.swift
Sources/Purchasing/Purchases/PurchasesType.swift
Sources/Support/HealthReport+Validate.swift
Sources/Support/PurchasesDiagnostics.swift
Sources/Support/SDKHealthManager.swift

@fire-at-will realized that we made some breaking changes to the public API by mistake when adding health report logging.
The reason was that we had already shipped the new `PurchasesDiagnostics` APIs just under the `#if DEBUG` directive, so we ca not make it more restrictive now without breaking the public API.
The rest of changes (logging the health report on configure) remain under `DEBUG` and `CEC`.
This PR fixes these issues while keeping the new logging changes out of the CEC mode.

Fixes API tests after changes to public API

---

Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift

The existing mechanism for presenting an alert will not work on macOS.
Switch from using UIKit to present an alert, to using SwiftUI.
Follow-up on https://github.com/RevenueCat/purchases-ios/pull/5238
I haven't actually been able to test this, because I cannot figure out how to get this deep link testing code to activate. I tried creating a deep link button in the Paywalls web interface, and it didn't seem to like that. @joshdholtz any advice on how to test this?
Here's the error I got:
```
Failed to open URL myscheme://deeplinktest: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=279, _LSFunction=-[_LSDOpenClient openURL:fileHandle:options:completionHandler:]}
ERROR: Failed to open URL as deep link: myscheme://deeplinktest
```

Use SwiftUI instead of UIKit to present an alert in Paywall Tester app

---

Sources/Virtual Currencies/VirtualCurrencies.swift
Sources/Virtual Currencies/VirtualCurrency.swift
Tests/UnitTests/Caching/DeviceCacheTests.swift
Tests/UnitTests/Mocks/MockVirtualCurrencyManager.swift
Tests/UnitTests/Purchasing/Purchases/PurchasesVirtualCurrenciesTests.swift
Tests/UnitTests/Virtual Currencies/VirtualCurrenciesTests.swift
Tests/UnitTests/Virtual Currencies/VirtualCurrencyManagerTests.swift
Tests/UnitTests/Virtual Currencies/VirtualCurrencyTests.swift

Required in UI preview mode
Add `@_spi(internal) public` marker to initializers of `VirtualCurrencies` and  `VirtualCurrency`

Add `@_spi` to initializers of virtual currencies APIs

---

Tests/BackendIntegrationTests/OfflineStoreKitIntegrationTests.swift

The test `testCallToGetCustomerInfoWithPendingTransactionsPostsReceiptOnlyOnce()` is [randomly failing](https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/29215/workflows/1f5c7b7a-8e15-4ee5-9554-957269d20b08/jobs/356434/tests). This PR attempts to fix it.
<details><summary>More details</summary>
<p>
The test is sometimes failing with this error:
```
OfflineStoreKitIntegrationTests.swift:262: Entitlement is not active: <EntitlementInfo: "
identifier=premium,
isActive=false,
willRenew=true,
periodType=PeriodType(rawValue: 1),
latestPurchaseDate=Optional(2025-07-17 15:45:36 +0000),
originalPurchaseDate=Optional(2025-07-17 15:45:36 +0000),
expirationDate=Optional(2025-07-17 15:45:36 +0000),
...
>
```
The error shows that the entitlement is not active while it should be active. …

Potential fix for flaky test

---

Tests/BackendIntegrationTests/Helpers/BaseStoreKitIntegrationTests+Verification.swift

Adds the current date to the failure messages of the entitlements verification checks in unit tests.
This should help us identify issues that cause flakiness in some unit tests (e.g. #5382, #5395)

Add date to failure messages of entitlement verification in tests

---

Tuist/ProjectDescriptionHelpers/Settings.swift

This PR adds the `VISION_OS` compiler flag to the tuist-generated projects for RevenueCat and RevenueCatUI, fixing the compilation in visionOS.
1. We still cannot use `#if os(visionOS)` since we're executing tests in older versions of Xcode that don't recognize `visionOS` (see #2989)
2. I tried using `.swiftActiveCompilationConditions`, but it looks like it doesn't support applying the conditions conditionally per platform (as we need the `VISION_OS` flag only in visionOS)

Tuist: fix compilation of RevenueCat and RevenueCatUI projects in visionOS

---

Sources/Logging/Strings/VirtualCurrencyStrings.swift

iOS equivalent of https://github.com/RevenueCat/purchases-android/pull/2552
This PR updates the `VirtualCurrencyStrings.no_cached_virtual_currencies` log message from `"No cached VirtualCurrencies, fetching from network."` to `"There are no cached VirtualCurrencies."`.
The previous message implied a network fetch would occur, which isn't always the case.
There are two scenarios where this log may appear:
-  When fetching virtual currencies and the cache is not stale but contains no virtual currencies object (an edge case that shouldn't occur with normal usage).
- When accessing the cache directly using `Purchases.cachedVirtualCurrencies` and it's empty - in this case, the SDK returns nil without initiating a network fetch.
The updated message is more descriptive of what actually happens …

Update VC Caching Log Message

---

RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift

After discussing with @vegaro, we've realized that `isLifetimeSubscription` made no sense.
- Replace `isLifetimeSubscription` with `isLifetime`, which is true only for `nonConsumable` store products

Replace isLifetimeSubscription for isLifetime

---

Examples/rc-maestro/rc-maestro/Resources/StoreKit/StoreKitConfiguration.storekit
Examples/rc-maestro/rc-maestro/Sources/rc-maestro/ContentView.swift
RevenueCatUI/CustomerCenter/Abstractions/CustomerCenterPurchasesType.swift
RevenueCatUI/CustomerCenter/Extensions/PurchaseInformation+Creation.swift
RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift

While debugging change plans, I've noticed there were some issues.
1. Add fallback to find the correct change plan to use
2. Limit productIDs to `>=2`
3. Only pick selected ones

Add fallback for change plans id and only display selected

---

RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift

We should allow `customURL` for empty screens in customer center. The dashboard allows it.
- Allow custom URL when there's no purchase information

Allow custom URL for empty screen in customer center

---

RevenueCatUI/CustomerCenter/Actions/CustomerCenterConfigData.HelpPath+PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation+Mock.swift
RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
RevenueCatUI/CustomerCenter/Data/Transaction.swift
Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
Tests/RevenueCatUITests/CustomerCenter/PurchaseInformationTests.swift
Tests/RevenueCatUITests/Mocks/MockTransaction.swift

We've got a zendesk report for a non-renewable appstore transaction. We were showing CANCEL, even though it's not cancellable. This also applies for change plans.
- Store productType only for appstore products
- Update PATH logic

fix non-renewable appstore PATHs for customer center

---

RevenueCat.xcodeproj/project.pbxproj
RevenueCatUI/Data/PaywallViewConfiguration.swift
RevenueCatUI/PaywallView.swift
RevenueCatUI/UIKit/PaywallFooterViewController.swift
RevenueCatUI/UIKit/PaywallViewController.swift
Sources/Purchasing/Offering.swift
Tests/APITesters/AllAPITests/RevenueCatUISwiftAPITester/PaywallViewControllerAPI.swift
Tests/StoreKitUnitTests/OfferingTests.swift

Based on PR [#2610](https://github.com/RevenueCat/purchases-android/pull/2610) for Android, adds similar internal APIs for the hybrid SDKs for iOS. Allows the hybrid SDKs to pass `PresentedOfferingContext` when launching paywalls by passing a specific offering
This PR implements the internal APIs, and uses the given `PresentedOfferingContext` when passing an `offeringIdentifier` from the hybrid SDKs to enrich the freshly fetched `Offering` with the given presentation context.

Added APIs for hybrid SDKs to set presentedOfferingContext

---

RevenueCatUI/CustomerCenter/Views/NoSubscriptionsCardView.swift
Sources/CustomerCenter/CustomerCenterConfigData.swift
Sources/Networking/Responses/CustomerCenterConfigResponse.swift

We want to be more explicit on how to edit the button text for the ScreenOffering.
- Add button text to ScreenOffering
> This comes already translated. For backwards compatibility, we default to the key used right now.

Add button_text to ScreenOffering

---

.circleci/config.yml
Sources/Purchasing/Purchases/Purchases.swift

Backend integration tests were failing because I missed to pass the new parameter added in #5504. This just adds a default value so we don't need to pass it in for the tests.

Fix backend integration tests

---

Examples/testCustomEntitlementsComputation/Project.swift
Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation.xcodeproj/project.pbxproj
Tuist/ProjectDescriptionHelpers/Settings.swift

While going through the tuist set up once again, I noticed that `testCustomEntitlementsComputation` a project to test `RevenueCat_CustomEntitlementComputation` didn't have the settings.
- Extend `appTarget` to receive extra settingsDictionary
- Tweak `testCustomEntitlementsComputation` to include it for the only target it has

Extend appTarget settings to pass custom settings

---

Sources/Purchasing/Purchases/TransactionPoster.swift
Sources/Purchasing/SimulatedStore/SimulatedStorePurchaseHandler.swift
Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
Tests/UnitTests/SimulatedStore/SimulatedStorePurchaseHandlerTests.swift

When making a purchase in the Test Store (Simulated Store), the `fetch_token` for the POST receipt request now contains the string `test_$PURCHASETIME_$UUID`.

Post receipt in for purchases in Test Store

---

RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift

Markdown bold text in paywalls was only being applied when the text had a regular font weight. For example, setting the font weight of a text to Extra light would not apply markdown bold. This is a bug
This PR fixes the behavior for markdown bold text in paywalls so that it works as intended:
* If the font weight of the text is <= Bold, markdown bold should be Bold
* If the font weight of the text is > Bold, markdown bold should be the same as the whole text (no difference)
Related fix on Android: https://github.com/RevenueCat/purchases-android/pull/2421
Also added a Preview (also for snapshot tests) using bold markdown in a text with extra light font weight:
| Before  | After |
| -------- | ------- |
| <img width="109" height="120" alt="image" …

Fix markdown bold text in paywalls

---

RevenueCatUI/CustomerCenter/ButtonStyles.swift
RevenueCatUI/CustomerCenter/Views/ActiveSubscriptionButtonsView.swift
RevenueCatUI/CustomerCenter/Views/NoSubscriptionsCardView.swift
RevenueCatUI/CustomerCenter/Views/PurchaseCardView.swift
RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift

After the changes in #5519, there are some compilation errors in RevenueCatUI when using Xcode 14.
This PR fixes compilation of RevenueCatUI in Xcode 14.
This PR adds some `#if compiler(>=5.9)` checks, disabling code not available in Xcode 14. It only affects code in RevenueCatUI and functionally this should be seamless (as Xcode 14 is not supported for App Store distribution anymore).

Fix compilation of RevenueCatUI in Xcode 14

---

Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
Tests/UnitTests/SimulatedStore/PurchasesOrchestratorSimulatedStoreTests.swift

The `PurchasesOrchestrator` was returning the `CustomerInfo` in the case of simulated failure of a purchase in the Test Store. This was causing the simulated failure case not throw an error in the SDK's `purchase` method. 
This was inconsistent with the behavior of the SDK for failures for the real App Store.
The `PurchasesOrchestrator` now returns a `nil` `CustomerInfo` in the simulated failure of a purchase in the Test Store. This means that an error is thrown from the `purchase` methods in the SDK.

Fix simulated failed purchase in Test Store

---

.gitignore
Workspace.swift

Currently, the tuist-generated Xcode workspace is named `RevenueCat-Workspace.xcworkspace`. This can lead to confusion with the existing `RevenueCat.xcworkspace`, making it not clear which one is which.
This PR renames the tuist-generated Xcode workspace to `RevenueCat-Tuist.xcworkspace` to make it clearer.

Tuist: rename generated Xcode workspace to RevenueCat-Tuist.xcworkspace

---

RevenueCatUI/CustomerCenter/ViewModels/BaseManageSubscriptionViewModel.swift
RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift

We've noticed this has not been working after a [report](https://github.com/RevenueCat/purchases-ios/issues/5568).
Promotionals can be attached to any path, not only to feedback survey
- Open promo offers from detail screen

Open promotional offers from CustomerCenter Detail screen

---

Sources/Misc/Obsoletions.swift

This PR fixes #5585, where archiving an app that integrates the SDK via XCFramework results in compiler errors.
The fixes are very similar to those done in https://github.com/RevenueCat/purchases-ios/pull/5542:
> Solution
The async raising the errors are all part of obsoleted APIs. These APIs should never be used as their implementation just do fatalError().
The solution has been to remove the async from the methods' signatures. This is a soft breaking change in the sense that callers of these methods will get a warning saying the await is not necessary. In addition, as developers shouldn't be using these APIs anyway, this should be the least disruptive solution.

Fix compilation error with XCFramework in Xcode 26

---

.circleci/config.yml
RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift

This snapshot has been constantly changing back and forth
I found out that, sometimes, the `GeometryReader` in `BadgeModifier` was reporting a width of 60, whereas the actual preview would be wider.
https://github.com/RevenueCat/purchases-ios/blob/fc15bc67aebee66da0dc605e348b1bb8f717cb39/RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift#L307-L333
As a result, an incorrect radius was being calculated in https://github.com/RevenueCat/purchases-ios/blob/fc15bc67aebee66da0dc605e348b1bb8f717cb39/RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift#L331
The reason seems to be that `onAppear`, which is only called once, was sometimes being called before the preview had its final size set, resulting in a premature size being used from the `GeometryReader`.
With the use of …

Fix flaky snapshot test

---

RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift

We've noticed that we were not showing the latest expired subscription if there are no subscriptions available.
- Remove early exit
- Show latest expired if no subs available
- Update tests

Show latest expired if no active subscriptions

---

Gemfile.lock

Update to [9179e55962ad83664eb76cf3e066bbcddd3ca93e](https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/commit/9179e55962ad83664eb76cf3e066bbcddd3ca93e) to re-introduce retries on rate limits

Updates fastlane-plugin-revenuecat_internal

---

Sources/Identity/SubscriptionInfo.swift
Tests/APITesters/AllAPITests/ObjcAPITester/RCSubscriptionInfoAPI.m
Tests/APITesters/AllAPITests/SwiftAPITester/SubscriptionInfoAPI.swift

We've been asked to make this one public, and figured that there's no reason to not have it public
- Make it public
- Update API tests

Make managementURL public in SubscriptionInfo

---

RevenueCatUI/Data/TestData.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
RevenueCatUI/Templates/V2/Variables/VariableHandlerV2.swift
Tests/RevenueCatUITests/PaywallsV2/VariableHandlerV2Tests.swift

Paywalls with promotional offers are not properly displaying the text related to that promotional offer.
This passes in the cached promotional offer to the existing text field introductory offer parsing logic to resolve that issue.

MON-1374: Handle Promotional offer text in paywalls

---

Sources/Support/SDKHealthManager.swift
Tests/UnitTests/Misc/SDKHealthManagerTests.swift

We recently got some reports of 500 responses from the health_report endpoint from some of our users with a large number of products.
We currently show that as an unknown error, which causes confusion. To mitigate this, let's only really show the error if it is an actual valid response.

[DX-520] Do not log unknown errors from health report endpoint
