RevenueCat/purchases-ios

- Purchases.xcodeproj/project.pbxproj
- Purchases/Classes/Public/RCPurchaserInfo.m
- Purchases/Classes/Public/RCPurchases.m
- Purchases/Classes/RCBackend.h
- Purchases/Classes/RCBackend.m
- Purchases/Classes/RCHTTPClient.h
- Purchases/Classes/RCHTTPClient.m
- Purchases/Classes/RCProductFetcher.h
- Purchases/Classes/RCProductFetcher.m
- Purchases/Classes/RCPurchases+Protected.h
- Purchases/Classes/RCStoreKitRequestFetcher.h
- Purchases/Classes/RCStoreKitRequestFetcher.m
- Purchases/Classes/RCStoreKitWrapper.h
- Purchases/Classes/RCStoreKitWrapper.m
- PurchasesTests/BackendTests.swift
- PurchasesTests/HTTPClientTests.swift
- PurchasesTests/ProductFetcherTests.swift
- PurchasesTests/PurchasesTests-Bridging-Header.h
- PurchasesTests/PurchasesTests.swift
- PurchasesTests/StoreKitRequestFetcherTests.swift
- PurchasesTests/SubscriberInfoTests.swift
1. Adds correct handling for when to finish a transaction and not.
2. Handles the case where the receipt data is nil.
3. Adds a timer to not over aggressively fetch a subscribers info.
> [FINAL] Improve Error Handling

- Purchases/Classes/Public/RCPurchases.m
- Purchases/Classes/RCBackend.h
- Purchases/Classes/RCBackend.m
- PurchasesTests/BackendTests.swift
- PurchasesTests/PurchasesTests.swift
- PurchasesTests/StoreKitRequestFetcherTests.swift
Adds conditional support for iOS 11.2 introductory prices.
> [FINAL] Support for Introductory Prices

- CHANGELOG.md
- Purchases/Classes/Public/RCPurchaserInfo.h
- Purchases/Classes/Public/RCPurchaserInfo.m
- Purchases/Classes/Public/RCPurchases.h
- Purchases/Classes/Public/RCPurchases.m
- PurchasesTests/PurchaserInfoTests.swift
- PurchasesTests/PurchasesTests.swift
Add support for original application versions.
> [FINAL] Original Application Version

- CHANGELOG.md
- Purchases/Classes/RCBackend.m
- PurchasesTests/BackendTests.swift
- Fix cache preventing prices from being posted
> [FIX] Price Cache Invalidation

- Purchases.xcodeproj/project.pbxproj
- Purchases/Classes/Public/RCEntitlement.h
- Purchases/Classes/Public/RCEntitlement.m
- Purchases/Classes/Public/RCOffering.h
- Purchases/Classes/Public/RCOffering.m
- Purchases/Classes/Public/RCPurchaserInfo.h
- Purchases/Classes/Public/RCPurchaserInfo.m
- Purchases/Classes/Public/RCPurchases.h
- Purchases/Classes/Public/RCPurchases.m
- Purchases/Classes/Public/Umbrella/Purchases.h
- Purchases/Classes/RCBackend.h
- Purchases/Classes/RCBackend.m
- Purchases/Classes/RCEntitlement+Protected.h
- Purchases/Classes/RCOffering+Protected.h
- PurchasesTests/BackendTests.swift
- PurchasesTests/PurchaserInfoTests.swift
- PurchasesTests/PurchasesTests-Bridging-Header.h
- PurchasesTests/PurchasesTests.swift
Entitlements are the new way to easily organize your in-app products.
Will be available for RevenueCat 🔜.
> [FINAL] Entitlements

- Purchases/Classes/Public/RCPurchaserInfo.h
- Purchases/Classes/Public/RCPurchaserInfo.m
- Purchases/Classes/Public/RCPurchases.h
- Purchases/Classes/Public/RCPurchases.m
- Purchases/Classes/Public/Umbrella/Purchases.h
- Purchases/Classes/Public/Umbrella/Purchases_macOS.h
- Purchases/Classes/RCBackend.h
- Purchases/Classes/RCBackend.m
- Purchases/Classes/RCHTTPClient.h
- Purchases/Classes/RCHTTPClient.m
- Purchases/Classes/RCPurchaserInfo+Protected.h
- Purchases/Classes/RCPurchases+Protected.h
- Purchases/Classes/RCStoreKitRequestFetcher.h
- Purchases/Classes/RCStoreKitRequestFetcher.m
- Purchases/Classes/RCStoreKitWrapper.h
- Purchases/Classes/RCStoreKitWrapper.m
- Purchases/Classes/RCUtils.h
- Purchases/Classes/RCUtils.m
- PurchasesTests/BackendTests.swift
- PurchasesTests/HTTPClientTests.swift
- PurchasesTests/PurchaserInfoTests.swift
- PurchasesTests/PurchasesTests.swift
- PurchasesTests/StoreKitRequestFetcherTests.swift
- PurchasesTests/StoreKitWrapperTests.swift
> [FINAL] Docs

- Purchases/Classes/Public/RCPurchaserInfo.m
- Purchases/Classes/Public/RCPurchases.h
- Purchases/Classes/Public/RCPurchases.m
- PurchasesTests/PurchasesTests.swift
1. Fix a couple Github issues
2. Expose the force refresh of `purchaserInfo`
3. Dispatch delegate communication async to the main thread.
> [FINAL] Fixes and Improvements

- Purchases/Classes/Public/RCPurchases.h
- Purchases/Classes/Public/RCPurchases.m
This removes the need to unwrap in Swift, which is nice.
> [FINAL] Make Init Non-Null

- Purchases/Classes/RCBackend.h
- Purchases/Classes/RCBackend.m
> Add iOS 11.2 availability annotations

- .jazzy.yaml
- Purchases.xcodeproj/project.pbxproj
- Purchases/Public/Purchases.h
- Purchases/Public/RCEntitlement.h
- Purchases/Public/RCIntroEligibility.h
- Purchases/Public/RCOffering.h
- Purchases/Public/RCPurchases.h
- Purchases/RCBackend.m
- Purchases/RCIntroEligibility+Protected.h
- PurchasesTests/PurchasesTests-Bridging-Header.h
- Had to change the imports in the umbrella header from <> to "" because jazzy couldn't find them
- Added jazzy config
- Completed documentation to 100%
- Deployed documentation to http://purchases-docs.s3.amazonaws.com/ios/index.html
> Adds Jazzy and missing documentation

- Purchases/Public/RCEntitlement.h
- Purchases/Public/RCOffering.h
- Purchases/Public/RCPurchases.h
Adds some missing docs. I deployed the docs to https://sdk.revenuecat.com/ios/v2/index.html
> Completed 2.0.0 docs

- Purchases/Public/RCPurchases.h
- Purchases/Public/RCPurchases.m
I added a class method to check whether the user is allowed to make payments. It's basically an abstraction of https://developer.apple.com/documentation/storekit/skpaymentqueue/1506139-canmakepayments?language=objc
> Add canMakePayment class method

- README.md
clarified macOS support + min versions
> macOS support

- Examples/SwiftExample/Podfile.lock
- Purchases/RCBackend.m
- Purchases/RCHTTPClient.m
- PurchasesTests/BackendTests.swift
- PurchasesTests/HTTPClientTests.swift
- Changes authorization header to Bearer
- Adds version name to the headers
> Headers updates

- README.md
> README version

- Purchases/RCCrossPlatformSupport.h
Adds check for the new UIKitForMac preprocessor and sends a new platform `uikitformac` to our backend that will be treated as MacOS
> UIKitForMac support

- Purchases/Public/RCPurchases.h
Adds a new AttributionNetwork for Facebook
> Adds Facebook AttributionNetwork

- Purchases/Public/RCEntitlementInfo.h
- Purchases/Public/RCEntitlementInfo.m
- PurchasesTests/EntitlementInfosTests.swift
- PurchasesTests/PurchaserInfoTests.swift
> Removes nullability of originalPurchaseDate

- Examples/SwiftExample/SwiftExample/Base.lproj/LaunchScreen.storyboard
- Examples/SwiftExample/SwiftExample/Base.lproj/Main.storyboard
- Update label colors and background colors on the initial and cat view controllers
- Use large activity indicator style which automatically adapts to user interface style
- Update background color of launch storyboard
> Update sample project with dark mode

- CHANGELOG.md
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Public/RCPurchases.m
- PurchasesTests/Info.plist
bumped the version number to 3.0.2 using fastlane
> [final] bump version to 3.0.2

- README.md
- RELEASING.md
- bin/release_version.sh
* Adds the "Carthage Compatible" tag to the readme. Because why not ¯\\_(ツ)_/¯ (I just found out about its existence)
* Replaces the manual building and zipping steps for Carthage with `carthage build --archive`
> [final] Feature/carthage improvements

- .circleci/config.yml
- fastlane/Fastfile
I think this command got removed on this commit https://github.com/RevenueCat/purchases-ios/commit/285e4a006d20ffaf635cd7c6e42eff2539091861#diff-56c5021ef06ac6cea807ae53269b6f4fL44
> Adds missing sed command on RCPurchases.m

- .circleci/config.yml
- .jazzy.yaml
- Gemfile
- bin/release_version.sh
- fastlane/Fastfile
- Added a job that requires approval to CircleCI
- Improved Jazzy configuration
- Added a step in the fastlane bump lane to automatically modify the versions in the jazzy config
- Fixed a bug in the release process. The releases tag were prefixed by a "v", and we don't use the "v" prefix
> Adds deployment of docs to CircleCI

- Purchases/Caching/RCInMemoryCachedObject.m
was about to release when I caught this typo.
> [final] fix: typo in init

- .jazzy.yaml
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Public/RCPurchases.m
- PurchasesTests/Info.plist
- bin/release_version.sh
- bumped version number to 3.1.0-SNAPSHOT
> [Final] bump: 3.1.0-SNAPSHOT

- Examples/SwiftExample/Podfile.lock
- Examples/SwiftExample/SwiftExample.xcodeproj/project.pbxproj
- Examples/SwiftExample/SwiftExample/AppDelegate.swift
- Examples/SwiftExample/SwiftExample/SwiftExample.entitlements
This adds examples to the sample app of how to use subscriber attributes.
> [final] Subscriber attributes part 6: sample

- Purchases/SubscriberAttributes/RCSubscriberAttribute.h
- Purchases/SubscriberAttributes/RCSubscriberAttribute.m
- PurchasesTests/Caching/InMemoryCachedObjectTests.swift
fix a couple of build warnings
> [final] fix a couple of build warnings

- .jazzy.yaml
- CHANGELOG.md
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Public/RCPurchases.m
- PurchasesTests/Info.plist
Includes a fix by @Timac for
https://github.com/RevenueCat/purchases-ios/issues/215
> Version 3.2.2

- Purchases/Public/RCPurchases.h
added attribution option for mParticle
> add mParticle attribution as an option

- Purchases/ProtectedExtensions/RCPurchaserInfo+Protected.h
- Purchases/Public/RCPurchaserInfo.h
- Purchases/Public/RCPurchaserInfo.m
- PurchasesTests/Purchasing/PurchaserInfoTests.swift
Adds managementURL to purchaserInfo. 
Does a bit of refactoring of stuff in purchaserInfo.
> Management url

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Bug Report template:
There are certain project specific issues that are commonly misinterpreted as bugs.
- [Offerings, products, or available packages are empty](https://support.revenuecat.com/hc/en-us/articles/360041793174)
- [Invalid Play Store credentials errors](https://support.revenuecat.com/hc/en-us/articles/360046398913)
- [Unable to connect to the App Store (STORE_PROBLEM) errors](https://support.revenuecat.com/hc/en-us/articles/360046399333)
For support I'd recommend our [online community](https://spectrum.chat/revenuecat), [StackOverflow](https://stackoverflow.com/tags/revenuecat/) and/or [Help Center](https://support.revenuecat.com/hc/en-us) 👍
If you have a clearly defined bug (with a [Minimal, Complete, and Reproducible …
> Adds issue templates

- .jazzy.yaml
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Misc/RCSystemInfo.m
- PurchasesTests/Info.plist
> Preparing for next version

- .jazzy.yaml
- CHANGELOG.md
- Purchases.podspec
- Purchases.xcodeproj/project.pbxproj
- Purchases/Info.plist
- Purchases/Misc/RCCrossPlatformSupport.h
- Purchases/Misc/RCSystemInfo.h
- Purchases/Misc/RCSystemInfo.m
- Purchases/Public/RCPurchases.m
- PurchasesTests/Info.plist
- PurchasesTests/Mocks/MockSystemInfo.swift
- PurchasesTests/Purchasing/PurchasesTests.swift
Feature/defer cache updates if woken from push notification (#288)
> Hotfix Release 3.5.2

- .jazzy.yaml
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Misc/RCSystemInfo.m
- PurchasesCoreSwift.podspec
- PurchasesCoreSwift/Info.plist
- PurchasesCoreSwiftTests/Info.plist
- PurchasesTests/Info.plist
bumped version number back to 3.6.0
> prepare for next version: 3.6.0

- Examples/SwiftExample/SwiftExample.xcodeproj/xcshareddata/xcschemes/SwiftExample - StoreKit Config Files (Xcode 12+).xcscheme
- Examples/SwiftExample/SwiftExample.xcodeproj/xcshareddata/xcschemes/WatchExample - StoreKit Config Files (Xcode 12+).xcscheme
| :-: | :-: |
| <img width="359" alt="Screen Shot 2020-09-02 at 8 20 44 PM" src="https://user-images.githubusercontent.com/3922667/92046988-4fce9680-ed5a-11ea-9294-c34cd70749aa.png"> | <img width="367" alt="Screen Shot 2020-09-02 at 8 21 23 PM" src="https://user-images.githubusercontent.com/3922667/92046984-4ba27900-ed5a-11ea-9796-6d34d82a2d49.png"> |
I'm hoping that the new name will make it clearer for devs to understand their intent.
> Rename storekitconfig schemes

- .jazzy.yaml
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Misc/RCSystemInfo.m
- PurchasesCoreSwift.podspec
- PurchasesCoreSwift/Info.plist
- PurchasesCoreSwiftTests/Info.plist
- PurchasesTests/Info.plist
> Preparing for next version: 3.7.0

- .jazzy.yaml
- Purchases.podspec
- Purchases/Info.plist
- Purchases/Misc/RCSystemInfo.m
- PurchasesCoreSwift.podspec
- PurchasesCoreSwift/Info.plist
- PurchasesCoreSwiftTests/Info.plist
- PurchasesTests/Info.plist
> Preparing for next version: 3.8.0

- Purchases/Public/RCPurchasesErrorUtils.m
This is the fix for issue #350
> Fix macCatalyst Build

- Purchases/Networking/RCHTTPRequest.h
- Purchases/Networking/RCHTTPRequest.m
- Purchases/Public/RCPurchasesErrorUtils.m
updated nullability in copyWithZone to fix build issues, and updated catalyst build condition
> fix build warnings and update catalyst build condition

- carthage.sh
added more info to the carthage.sh script. 
Should have done this initially, but it only occurred to me today ¯\_(ツ)_/¯
> add more info to the carthage.sh script

- Purchases/Public/RCPurchases.h
Noticed a small typo in the documentation.
> Fix tiny typo

- PurchasesCoreSwift/Logging/Logger.swift
removes logging v2 feature flag
> remove logging v2 feature flag

- fastlane/Fastfile
I began a rename of the lane but didn't commit all of the related files 🤦
> fixed a typo in xcframework lane

- Purchases.xcodeproj/project.pbxproj
This PR fixes tests, which were failing because a couple of files hadn't been added to the project file.
> Fix tests for custom logger

- .github/ISSUE_TEMPLATE/bug_report.md
- CONTRIBUTING.md
- Examples/MagicWeather/README.md
- Examples/MagicWeatherSwiftUI/README.md
- IntegrationTests/SPMIntegration/SPMIntegration.xcodeproj/project.pbxproj
- IntegrationTests/SPMIntegration/fastlane/Fastfile
- fastlane/Fastfile
Switch over to using `main` branch.
> Use main branch for all the things instead of develop

- CONTRIBUTING.md
- Package.swift
- Purchases.xcodeproj/project.pbxproj
- fastlane/Fastfile
- fastlane/README.md
- scripts/pre-commit.sh
- scripts/swiftlint.sh
Add fastlane lane for setup_dev
Add pre-commit hook script that lints files
Link pre-commit during setup_dev lane
Add SwiftLint to new build phase step in project so people can see issues before commit.
Update documentation
> Add setup_dev fastlane lane

- .github/ISSUE_TEMPLATE/migration_task
- .github/ISSUE_TEMPLATE/migration_task.md
For use for the Swift migration related milestones and project board. It will make creating and linking stories easier 🚀
> Create migration_task template

- CONTRIBUTING.md
Make it more clear how folks can help out with the migration.
Resolves #586
> Update CONTRIBUTING.md to Swift migration

- .gitignore
- docs/SwiftMigration.md
> Make project plan public

- PublicSDKAPITester/RCEntitlementInfosAPI.h
- PublicSDKAPITester/RCEntitlementInfosAPI.m
- PublicSDKAPITester/main.m
- Purchases.xcodeproj/project.pbxproj
> Add RCEntitlementInfos API tests

- PurchasesCoreSwift/Public/EntitlementInfos.swift
> RCEntitlementInfos update

- PurchasesCoreSwift/Misc/SystemInfo.swift
> Address comments

- .circleci/config.yml
- .swiftlint.yml
- Purchases.xcodeproj/project.pbxproj
- PurchasesCoreSwift/Purchasing/ProductInfo.swift
- PurchasesCoreSwift/Purchasing/PromotionalOffer.swift
- PurchasesCoreSwift/Purchasing/RCReceiptFetcher.swift
- PurchasesTests/Mocks/MockReceiptFetcher.swift
- fastlane/Fastfile
- fastlane/README.md
And fix a couple missing `available` checks for tv 
Fixes #630
> Build TV and Watch targets in CI

- .swiftlint.yml
- CONTRIBUTING.md
- Purchases.xcodeproj/project.pbxproj
- SwiftStyleGuide.swift
added a sample swift file that I figured might be a useful reference for folks who aren't used to swift. 
The file isn't attached to any target and is just there in case anyone needs to double-check something.
> Sample swift file

- Purchases.xcodeproj/xcshareddata/xcschemes/Purchases.xcscheme
- Purchases.xcodeproj/xcshareddata/xcschemes/PurchasesCoreSwift.xcscheme
- Purchases.xcodeproj/xcshareddata/xcschemes/StoreKitTests.xcscheme
- Purchases.xcodeproj/xcshareddata/xcschemes/Unit Tests.xcscheme
enables random execution order for all test schemes.
> enable random execution order for all test schemes

- Purchases.xcodeproj/xcshareddata/IDETemplateMacros.plist
Add default RevenueCat header template for new files.
> Header template for new files

- Purchases.xcodeproj/project.pbxproj
- PurchasesCoreSwift/Public/Error Handling/BackendErrorCode.swift
- PurchasesCoreSwift/Public/Error Handling/ErrorCode.swift
- PurchasesCoreSwift/Public/Error Handling/ErrorDetails.swift
- PurchasesTests/FoundationExtensions/NSError+RCExtensionsTests.swift
- PurchasesTests/Identity/IdentityManagerTests.swift
- PurchasesTests/Networking/BackendTests.swift
- PurchasesTests/Networking/HTTPClientTests.swift
- PurchasesTests/Purchasing/PurchasesTests.swift
- PurchasesTests/SubscriberAttributes/BackendSubscriberAttributesTests.swift
- PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Fix for https://github.com/RevenueCat/purchases-ios/pull/645#discussion_r672356979
> Updating for style and comments

- Purchases.xcodeproj/project.pbxproj
We have a couple of build warnings from duplicate files in the compilation phase, looks like merge issues. I just removed the duplicates.
> removed duplicate files in compilation phase

- Purchases/Public/RCPurchases.m
added a few comments to provide guidance on how to split `RCPurchases.m` into multiple classes.
> guidance on splitting `RCPurchases`

- PurchasesCoreSwift/Caching/DeviceCache.swift
- PurchasesCoreSwift/Caching/InMemoryCachedObject.swift
- PurchasesTests/Caching/DeviceCacheTests.swift
- PurchasesTests/Caching/InMemoryCachedObjectTests.swift
- PurchasesTests/Mocks/MockDeviceCache.swift
- PurchasesTests/Mocks/MockInMemoryCachedOfferings.swift
- PurchasesTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift
Address comments from original PR #https://github.com/RevenueCat/purchases-ios/pull/658
> Migrate caching things followup

- .github/stale.yml
- .github/workflows/lock.yml
should address https://github.com/RevenueCat/purchases-ios/issues/696, as well as https://github.com/RevenueCat/purchases-ios/issues/654
> Exclude swift migration in issue bot

- IntegrationTests/PurchaseTester/Podfile.lock
- IntegrationTests/PurchaseTester/PurchaseTester/CatsViewController.swift
- IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift
Updated usage of Purchases types in PurchaseTester
> updated usage of `Purchases.PurchaserInfo` -> `PurchaserInfo` in purchaseTester

- PurchasesCoreSwift/Public/Purchases.swift
> Log in api fix

- PublicSDKAPITester/RCEntitlementInfoAPI.m
- PublicSDKAPITester/RCEntitlementInfosAPI.m
- PublicSDKAPITester/RCIntroEligibilityAPI.m
- PublicSDKAPITester/RCOfferingsAPI.m
- PublicSDKAPITester/RCPackageAPI.m
- PublicSDKAPITester/RCPurchasesAPI.m
- Purchases.xcodeproj/project.pbxproj
- Purchases.xcodeproj/xcshareddata/xcschemes/APITester.xcscheme
- Purchases.xcodeproj/xcshareddata/xcschemes/Purchases.xcscheme
- Purchases.xcodeproj/xcshareddata/xcschemes/StoreKitTests.xcscheme
- Purchases/Public/EntitlementInfo.swift
- Purchases/Public/EntitlementInfos.swift
- Purchases/Public/IntroEligibility.swift
- Purchases/Public/Offering.swift
- Purchases/Public/Offerings.swift
- Purchases/Public/Package.swift
- Purchases/Public/Purchases.swift
> Make inits private for public classes

- Purchases/Identity/IdentityManager.swift
- Purchases/Logging/Strings/ConfigureStrings.swift
- Purchases/Logging/Strings/IdentityStrings.swift
- Purchases/Misc/SystemInfo.swift
- Purchases/Networking/Backend.swift
- Purchases/Public/Purchases.swift
Follow-up on https://github.com/RevenueCat/purchases-ios/pull/816 with changes on ConfigureStrings and IdentityStrings
~Blocked by https://github.com/RevenueCat/purchases-ios/pull/816~
> Improve strings formatting: ConfigureStrings and IdentityStrings

- Purchases/CodableExtensions/PurchaseOwnershipType+Extensions.swift
- Purchases/FoundationExtensions/JSONDecoder+Extensions.swift
- Purchases/Logging/LogIntent.swift
- Purchases/Logging/Logger.swift
- Purchases/Logging/Strings/AttributionStrings.swift
- Purchases/Logging/Strings/CodableStrings.swift
- Purchases/SubscriberAttributes/SubscriberAttributesManager.swift
I started this on Friday but didn't get time to open up the PR. 
Updates the `CodableStrings` to use enum cases, see more on the motivation in #816
> Improve strings formatting: `Codable` strings

- Purchases/Identity/IdentityManager.swift
- Purchases/Logging/Strings/ConfigureStrings.swift
- Purchases/Logging/Strings/IdentityStrings.swift
- Purchases/Misc/SystemInfo.swift
- Purchases/Networking/Backend.swift
- Purchases/Public/Purchases.swift
This PR adds updates `main` with changes from swift_migration. More specifically, changes introduced by #817. We want to remove swift_migration.
This code has already been reviewed in #817
> Adds #817 to main. Preparing to delete swift_migration branch

- Purchases/LocalReceiptParsing/ReceiptParser.swift
- Purchases/Logging/Strings/ReceiptStrings.swift
- Purchases/Public/Purchases.swift
- Purchases/Purchasing/ReceiptFetcher.swift
Follow-up to https://github.com/RevenueCat/purchases-ios/pull/816, updates the format in `ReceiptStrings`.
> Improve strings formatting: `ReceiptStrings`

- .circleci/config.yml
Fixed the s3 docs upload circleci task removing an unused option
> Fix s3 docs upload task

- Purchases/Identity/PurchaserInfoManager.swift
- Purchases/Logging/Strings/PurchaseStrings.swift
- Purchases/Logging/Strings/PurchaserInfoStrings.swift
- Purchases/Public/Purchases.swift
- Purchases/Purchasing/IntroEligibilityCalculator.swift
- Purchases/Purchasing/PurchasesOrchestrator.swift
- Purchases/Purchasing/StoreKitWrapper.swift
Follow-up on #816 updates the format `PurchaserInfoStrings` and `PurchaseStrings`
> Improve strings formatting PurchaserInfoStrings and PurchaseStrings

- Package.swift
Incorrect exclude path updated to correct path now.
> Fix SPM warning

- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
> Updates community links

- APITesters/APITesters.xcworkspace/xcshareddata/swiftpm/Package.resolved
- APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
- APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
Fix CI since SPM is pointing at a now deleted branch
> update APITesters to main

- docs/V4_API_Updates.md
- [ ✅ ] A description about what and why you are contributing, even if it's trivial.
This PR fixes a typo in the API V4 docs where the new type name for `Purchases.Offering` is listed.
- [✅ ] The issue number(s) or PR number(s) in the description if you are contributing in response to those.
N/A
- [ ✅ ] If applicable, unit tests.
N/A
> Fixes API V4 Changes Doc Purchases.Offering typo

- .circleci/config.yml
Fixes deployment issue for docs
> Backport fix for deploy docs task

- IntegrationTests/PurchaseTester/Podfile.lock
- IntegrationTests/PurchaseTester/PurchaseTester/CatsViewController.swift
- IntegrationTests/PurchaseTester/PurchaseTester/InitialViewController.swift
- IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift
- IntegrationTests/PurchaseTester/WatchPurchaseTester Extension/InterfaceController.swift
Update purchase tester for the new api
> Update for getCustomerInfo/getOfferings api

- Purchases/Public/CustomerInfo.swift
- PurchasesTests/Purchasing/CustomerInfoTests.swift
> SubscriberData can now throw errors on init

- IntegrationTests/PurchaseTester/PurchaseTester.xcodeproj/project.pbxproj
- IntegrationTests/PurchaseTester/PurchaseTester/AppDelegate.swift
- IntegrationTests/PurchaseTester/PurchaseTester/Constants.swift
- IntegrationTests/PurchaseTester/WatchPurchaseTester Extension/ExtensionDelegate.swift
This simplifies the error when initially compiling the project and points to a single file to fix it.
> PurchaseTester: defined APIKey in a common file

- Purchases/Misc/Lock.swift
- Purchases/Networking/ETagManager.swift
- PurchasesTests/Mocks/MockETagManager.swift
- RevenueCat.xcodeproj/project.pbxproj
Fixes #945.
I really like https://github.com/ReactiveCocoa/ReactiveSwift/blob/master/Sources/Atomic.swift, but I think this is a good solution for now.
> MockETagManager is now thread safe

- Purchases/Public/Offering.swift
> Log when duplicate subscription time lengths exist during Offering init

- Purchases/Attribution/AttributionPoster.swift
- Purchases/Caching/DeviceCache.swift
- Purchases/Networking/Backend.swift
- Purchases/Networking/HTTPClient.swift
- Purchases/Public/Purchases.swift
- Purchases/Purchasing/PromotionalOffer.swift
- Purchases/SubscriberAttributes/AttributionDataMigrator.swift
> Clean-up: using swiftlint:disable:next instead of manually re-enabling rules

- Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcodeproj/project.pbxproj
This was making the app not run on device.
I missed this on #946.
> Magic Weather SwiftUI: copy RevenueCat.framework

- Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/PurchasesDelegateHandler.swift
- Examples/MagicWeatherSwiftUI/Shared/Sources/ViewModels/UserViewModel.swift
- Purchases/Public/CustomerInfo.swift
- Purchases/Public/EntitlementInfo.swift
> Updated all uses of "Note" in docs to enhanced format

- Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift
- Purchases/Error Handling/ErrorUtils.swift
- Purchases/FoundationExtensions/JSONDecoder+Extensions.swift
- Purchases/Public/IntroEligibility.swift
- Purchases/Purchasing/ProductInfo.swift
I like to take some credit in this https://twitter.com/NachoSoto/status/943880484978769921?s=20
> Using `@unknown default` to ensure we handle future cases

- APITesters/APITesters.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fix build for the api testers on main
> Update for customerInfo vs getCustomerInfo changes

- RevenueCat.xcodeproj/project.pbxproj
The actual file is still in there.
> Fixed invalid project reference

- Purchases/Logging/Strings/OfferingStrings.swift
- Purchases/Purchasing/ProductDetails.swift
> ProductDetails: log warning when product title is empty

- Purchases/Caching/DeviceCache.swift
- Purchases/Public/Purchases.swift
- PurchasesTests/Attribution/AttributionPosterTests.swift
- PurchasesTests/Caching/DeviceCacheTests.swift
- PurchasesTests/Identity/CustomerInfoManagerTests.swift
- PurchasesTests/Identity/IdentityManagerTests.swift
- PurchasesTests/Mocks/MockIdentityManager.swift
- PurchasesTests/Mocks/MockSystemInfo.swift
- PurchasesTests/Purchasing/OfferingsManagerTests.swift
- PurchasesTests/Purchasing/PurchasesTests.swift
- PurchasesTests/SubscriberAttributes/DeviceCacheSubscriberAttributesTests.swift
- PurchasesTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
- PurchasesTests/SubscriberAttributes/SubscriberAttributesManagerTests.swift
- PurchasesTests/Support/BeginRefundRequestHelperTests.swift
- PurchasesTests/Support/ManageSubscriptionsModalHelperTests.swift
- StoreKitUnitTests/PurchasesOrchestratorTests.swift
> DeviceCache: reduced cache duration on sandbox

- BackendIntegrationTests/BackendIntegrationTests.swift
- Purchases/Identity/CustomerInfoManager.swift
- Purchases/Logging/Strings/CustomerInfoStrings.swift
- Purchases/Support/ManageSubscriptionsModalHelper.swift
- StoreKitUnitTests/PurchasesOrchestratorTests.swift
> Changed several PurchaserInfo to ConsumerInfo

- BackendIntegrationTests/BackendIntegrationTests.swift
- Purchases/Identity/CustomerInfoManager.swift
- Purchases/Logging/Strings/CustomerInfoStrings.swift
- Purchases/Support/ManageSubscriptionsModalHelper.swift
- StoreKitUnitTests/PurchasesOrchestratorTests.swift
Follow up to #1007.
Didn't realize I've been reading this wrong in my head the whole time, until I saw this:
> Fixed consumer -> customer

- IntegrationTests/CommonFiles/IntegrationTests.swift
- IntegrationTests/PurchaseTester/PurchaseTester/Base.lproj/Main.storyboard
- IntegrationTests/PurchaseTester/PurchaseTester/CatsViewController.swift
Adds buttons for manually testing manage subscription modal and begin refund
> Add sk2 purchase tester

- .swiftlint.yml
- Purchases/Caching/DeviceCache.swift
- Purchases/FoundationExtensions/String+Extensions.swift
- Purchases/Logging/Logger.swift
- Purchases/Misc/FatalErrorUtil.swift
See https://realm.github.io/SwiftLint/convenience_type.html
> Added convenience_type SwiftLint rule

- Purchases/Public/Purchases.swift
I was updating my app to use Version 4 and realized these had no docstrings.
> Added docstrings for Purchases.shared and Purchases.isConfigured

- APITesters/SwiftAPITester/SwiftAPITester/AttributionNetworkAPI.swift
- APITesters/SwiftAPITester/SwiftAPITester/IntroEligibilityAPI.swift
- APITesters/SwiftAPITester/SwiftAPITester/RefundRequestStatusAPI.swift
> SwiftAPITester: fixed 3 warnings for unknown cases

- Purchases/Attribution/AttributionFetcher.swift
- Purchases/Misc/SystemInfo.swift
The implementation was duplicated and incomplete.
> `AttributionFetcher.identifierForVendor`: use `SystemInfo.identifierForVendor`

- Purchases/SubscriberAttributes/SubscriberAttributesManager.swift
This could have lead to a deadlock.
> `SubscriberAttributesManager`: using `Lock` to avoid leaving `NSRecursiveLock` locked

- IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift
Fixes [sc-11623].
Depends on #1047.
Includes #1048 (I put that as a separate PR for easier review).
> Updated `PurchaseTester` to use all V4 methods

- Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
This is a test app, so I think it makes sense to have it use the latest APIs.
> MagicWeatherSwiftUI: use StoreKit 2

- IntegrationTests/PurchaseTester/PurchaseTester/AppDelegate.swift
> PurchaseTester: use StoreKit 2 if available

- Purchases/Identity/CustomerInfoManager.swift
I noticed that there was a single `.unlock` call. I decided to refactor it by using the new `Lock`.
This class could use some more love to make sure the whole thing is thread-safe, but for now this should fix issues with the lock getting unlocked.
> `CustomerInfoManager`: fixed `Lock` usage

- Purchases/Networking/HTTPClient.swift
> HTTPClient: added `X-StoreKit2-Enabled` header

- Purchases/Public/CustomerInfo.swift
`CustomerInfo` is meant to be immutable.
> `CustomerInfo`: don't expose `allPurchasedProductIdentifiers` setter

- APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
- APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductDiscountAPI.h
- APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductDiscountAPI.m
- APITesters/ObjCAPITester/ObjCAPITester/main.m
- APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
- APITesters/SwiftAPITester/SwiftAPITester/StoreProductDiscountAPI.swift
- APITesters/SwiftAPITester/SwiftAPITester/main.swift
- Purchases/Purchasing/StoreProductDiscount.swift
This also showed that the members weren't exposed with `@objc`!
Depends on #1134
> Added `StoreProductDiscount` to `APITester`s

- APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
- APITesters/ObjCAPITester/ObjCAPITester/RCSubscriptionPeriodAPI.h
- APITesters/ObjCAPITester/ObjCAPITester/RCSubscriptionPeriodAPI.m
- APITesters/ObjCAPITester/ObjCAPITester/main.m
- APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
- APITesters/SwiftAPITester/SwiftAPITester/SubscriptionPeriodAPI.swift
- APITesters/SwiftAPITester/SwiftAPITester/main.swift
- Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
Also added missing fields for `@objc`.
> Added `SubscriptionPeriod` to `APITester`s

- Purchases/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
- PurchasesTests/Mocks/MockTransaction.swift
- RevenueCat.xcodeproj/project.pbxproj
- StoreKitUnitTests/StoreTransactionTests.swift
> Added tests for `StoreTransaction`

- StoreKitUnitTests/StoreTransactionTests.swift
> `StoreTransactionTests`: don't skip SK1 test

- Examples/MagicWeather/MagicWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/MagicWeather/MagicWeather/Sources/Controllers/PaywallViewController.swift
- Examples/MagicWeather/MagicWeather/Sources/Controllers/UserViewController.swift
- Examples/MagicWeather/MagicWeather/Sources/Lifecycle/AppDelegate.swift
- Purchases/Public/Package.swift
MagicWeather had some dated API calls, updated them to the latest syntax
> update MagicWeather API calls to latest syntax

- Examples/MagicWeatherSwiftUI/Shared/Sources/Helpers/Extensions.swift
- Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
- Examples/MagicWeatherSwiftUI/Shared/Sources/Views/UserView.swift
Follow-up to #1189, same idea: update API calls to latest syntax
> updated API calls in MagicWeatherSwiftUI

- Purchases/Misc/OperationDispatcher.swift
- Purchases/Networking/Backend.swift
- Purchases/Public/Purchases.swift
Also, remove the param from the convenience init in Backend.swift.
> Remove unused OperationDispatcher method

- Documentation.docc/Documentation.md
Added a note to point folks to the v3 SDK if needed.
> Add note to point to v3 docs

- Purchases/Purchasing/ProductRequestData.swift
- Purchases/Purchasing/Purchases.swift
- Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
Fixed a few symbol links in docs
> fix a few symbol links

- .swiftlint.yml
- Purchases/CodableExtensions/PeriodType+Extensions.swift
- Purchases/CodableExtensions/PurchaseOwnershipType+Extensions.swift
- Purchases/CodableExtensions/Store+Extensions.swift
- Purchases/Error Handling/ErrorCode.swift
- Purchases/LocalReceiptParsing/ReceiptParsingError.swift
- Purchases/Logging/Logger.swift
- Purchases/Misc/Obsoletions.swift
- Purchases/Networking/DNSChecker.swift
- Purchases/Purchasing/EntitlementInfos.swift
- Purchases/Purchasing/Offering.swift
- Purchases/Purchasing/Offerings.swift
- Purchases/Purchasing/Package.swift
- Purchases/Purchasing/ProductRequestData.swift
- Purchases/Purchasing/PurchaseOwnershipType.swift
- Purchases/Purchasing/Purchases.swift
- Purchases/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
- Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
- Purchases/Purchasing/StoreKitAbstractions/StoreProductDiscount.swift
- Purchases/Purchasing/StoreKitAbstractions/StoreTransaction.swift
- Purchases/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
- PurchasesTests/.swiftlint.yml
- StoreKitUnitTests/.swiftlint.yml
See https://realm.github.io/SwiftLint/missing_docs.html.
Depends on #1230.
> `SwiftLint`: more inclusive `missing_docs` rule, and added all missing docs

- APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
- APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
- Examples/MagicWeather/MagicWeather/Sources/Lifecycle/AppDelegate.swift
- Examples/MagicWeatherSwiftUI/Shared/Sources/Lifecycle/MagicWeatherApp.swift
- IntegrationTests/PurchaseTester/PurchaseTester/AppDelegate.swift
- Purchases/Purchasing/Purchases.swift
> Re-enabled SK2

- Purchases/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
- PurchasesTests/Purchasing/OfferingsTests.swift
> Removed the last usages of "maybe"

- Purchases/Networking/Caching/CallbackCache.swift
- Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
- Purchases/Networking/Operations/NetworkOperation.swift
From https://github.com/RevenueCat/purchases-ios/pull/975
> Addressing Nacho's comments

- Purchases/Purchasing/IntroEligibility.swift
> Added note about `IntroEligibility` purpose

- Documentation.docc/V4_API_Migration_guide.md
Opening paragraph clarity, listing broad changes, and a mention of updated class parents (based on testing feedback).
> Updates migration guide

- APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
- APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
- Purchases/Misc/DangerousSettings.swift
- Purchases/Misc/SystemInfo.swift
- Purchases/Purchasing/Purchases.swift
- PurchasesTests/Mocks/MockBackend.swift
- PurchasesTests/Mocks/MockIdentityManager.swift
- PurchasesTests/Purchasing/PurchasesTests.swift
- RevenueCat.xcodeproj/project.pbxproj
Equivalent of https://github.com/RevenueCat/purchases-ios/pull/1219
> Adds DangerousSetting to disable auto syncing purchases (against v4)

- Purchases/Misc/Lock.swift
Just for debugging purposes, doesn't hurt to have this.
> `Lock`: added name to `NSRecursiveLock`

- IntegrationTests/PurchaseTester/Podfile.lock
- IntegrationTests/PurchaseTester/PurchaseTester/AppDelegate.swift
- IntegrationTests/PurchaseTester/PurchaseTester/SwiftPaywall.swift
Fixed a couple of outdated references in the purchaseTester sample app
> fix some outdated references in sample app

- BackendIntegrationTests/BackendIntegrationTests.swift
- No more `expect(completed).toEventually(beTrue())`.
- No more `expect(error).to(beNil())`. Using `try` and `throws` tests.
- No more `expect(result).toNot(beNil())` or `XCTUnwrap`. The new APIs already return non-optional data when not failed.
- No more `toEventually`s + polling. Tests run serially now without busy waiting, which will make them faster.
- No more completion block trees, tests are linear now.
- Removed empty optional `purchases(_:, shouldPurchasePromoProduct:, defermentBlock:)`.
- Using modern `==` Nimble methods.
- Removed redundant `syncPurchases` call when purchasing.
> `IntegrationTests`: simplified tests using `async` APIs

- Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
> Make StoreProduct initializers public

- APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
- APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
- Purchases/Purchasing/StoreKitAbstractions/StoreProduct.swift
> `StoreProduct`: added new public constructors to `APITester`s

- BackendIntegrationTests/BackendIntegrationTests.swift
> `IntegrationTests`: added test to verify `Purchases.simulatesAskToBuyInSandbox`

- Purchases/Networking/Operations/GetIntroEligibilityOperation.swift
- Purchases/Networking/Operations/LogInOperation.swift
- Purchases/Networking/Operations/PostOfferForSigningOperation.swift
Inspired by this: https://twitter.com/nunovieira_dev/status/1487265828227764225, but simpler without relying on a `defer` hack.
I recommend reviewing this without whitespaces.
> `Operation`s: refactored response handling to ensure completion handlers are only called once

- Documentation.docc/V4_API_Migration_guide.md
This reverts commit 083f706e295545a50792ae96bbab2b6fdb979dcb.
> Revert "Update V4_API_Migration_guide.md image links (#1344)"

- Purchases/Purchasing/TrialOrIntroPriceEligibilityChecker.swift
- StoreKitUnitTests/PurchasesOrchestratorTests.swift
- StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
- StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
Fixes [CF-288]
[CF-288]: https://revenuecats.atlassian.net/browse/CF-288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Using `StoreKitTestHelpers` to simplify tests

- .swiftlint.yml
> .swiftlint.yml: cleaned old folders

- Purchases/Misc/Obsoletions.swift
> Added obsoletion for `invalidatePurchaserInfoCache`

- Documentation.docc/V4_API_Migration_guide.md
Fixes https://github.com/RevenueCat/purchases-ios/issues/1355
> add instructions to fix Workspace Integrity error from SPM

- PurchasesTests/Purchasing/ProductsFetcherSK1Tests.swift
Fast tests FTW
The default timeout of the `ProductsFetcherSK1` was 5 seconds, which is fine for tests that just check correct results. However, these 3 tests were relaying on the timeout to expire, waiting for such long times.
> `ProductsFetcherSK1Tests`: fixed artificial delays to speed up tests from 7 seconds to 1s

- TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
- Tests/BackendIntegrationTests/BackendIntegrationTests.swift
> `IntegrationTests`: added tests for `PromotionalOffer`s

- Sources/Networking/ETagManager.swift
Also removed the unused `queue`.
> `ETagManager`: simplified implementation using `SynchronizedUserDefaults`

- Sources/Logging/Strings/AttributionStrings.swift
- Sources/Logging/Strings/NetworkStrings.swift
I was debugging something and noticed these 2 logs were missing spaces.
> Fixed a couple of `Strings`

- Sources/Purchasing/OfferingsManager.swift
This will become the response type used everywhere by `OfferingsManager` in #1435.
> `OfferingsManager`: replaced manual decoding with `Decodable`

- Tests/UnitTests/LocalReceiptParsing/Builders/ASN1ContainerBuilderTests.swift
Follow-up to #1452, adds a couple of unit tests to ensure that we're getting the value correctly
> length calculation tests

- Development/RELEASING.md
Added more details for how to compile a release
> Add more details for how to make a release

- Development/RELEASING.md
Small clarification regarding which github token to use when preparing a release
> Clarify GitHub token in RELEASING.md

- README.md
This removes the image on the left.
> `README`: removed reference to `Purchases` / v3.x

- scripts/docs/index.html
Fixed an outdated link from a bad rebase in index.html
> fix outdated link in index.html

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
- Sources/Purchasing/StoreKitAbstractions/SK1Storefront.swift
- Sources/Purchasing/StoreKitAbstractions/SK2Storefront.swift
- Sources/Purchasing/StoreKitAbstractions/Storefront.swift
- Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStorefrontAPI.h
- Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStorefrontAPI.m
- Tests/APITesters/ObjCAPITester/ObjCAPITester/main.m
- Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/SwiftAPITester/SwiftAPITester/StorefrontAPI.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/main.swift
> Introduced `Storefront` to abstract SK1 `SKStorefront` and SK2 `StoreKit.Storefront`

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Purchasing/StoreKit2/ProductsFetcherSK2.swift
- Sources/Purchasing/StoreKitAbstractions/Storefront.swift
- Tests/StoreKitUnitTests/StorefrontTests.swift
- Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Follow up to #1500. Depends on #1501.
> Added `Storefront.currentStorefront`

- Sources/Networking/HTTPClient.swift
> `HTTPClient`: refactored `NetworkError` creation

- .github/ISSUE_TEMPLATE/bug_report.md
Contributing.md link was outdated
> fix contributing link

- Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PromotionalOfferAPI.swift
I had missed a few comments in https://github.com/RevenueCat/purchases-ios/pull/1523, it looks like they happened after the PR was merged 😅 
Anyway, better late than never!
> address comments from signed data PR

- Tests/APITesters/SwiftAPITester/SwiftAPITester/PromotionalOfferAPI.swift
> Fix bad merge

- Sources/Purchasing/EntitlementInfo.swift
These were all duplicated for some reason.
> Simplified `EntitlementInfo.isEqual`

- Tests/APITesters/SwiftAPITester/SwiftAPITester/CustomerInfoAPI.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/EntitlementInfoAPI.swift
> Added `RawDataContainer` conformances to APITesters

- RevenueCat.xcodeproj/project.pbxproj
Only alphabetizing `Sources` folder in project
> alphabetize Sources folder and subfolders

- Sources/CodableExtensions/PeriodType+Extensions.swift
- Sources/CodableExtensions/PurchaseOwnershipType+Extensions.swift
- Sources/CodableExtensions/Store+Extensions.swift
These will be used in an upcoming PR.
> `PeriodType`/`PurchaseOwnershipType`/`Store`: conform to `Encodable`

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Logging/Strings/ConfigureStrings.swift
- Sources/Purchasing/Configuration.swift
- Tests/UnitTests/Purchasing/ConfigurationTests.swift
iOS part of [CF-53].
[CF-53]: https://revenuecats.atlassian.net/browse/CF-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Validate API key

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
- RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
- Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
- Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
> Updated project and schemes for Xcode 13.4

- .circleci/config.yml
- fastlane/Fastfile
Another issue when trying to generate changelog 🙈
Also, the 15.2 simulator install was really slow so using the 15.4 simulator which is already installed on CircleCI.
> Fix fastlane changelog_path error and use 15.4 sim on CircleCI

- Sources/DocCDocumentation/DocCDocumentation.docc/Purchases.md
- Sources/DocCDocumentation/DocCDocumentation.docc/RevenueCat.md
- Sources/Purchasing/Purchases.swift
| :-: | :-: |
| <img width="1030" alt="Screen Shot 2022-05-26 at 6 46 07 PM" src="https://user-images.githubusercontent.com/3922667/170585397-e85ef4fa-e46e-4e8f-9cb8-cd5e83f9081d.png"> | <img width="1013" alt="Screen Shot 2022-05-26 at 6 46 57 PM" src="https://user-images.githubusercontent.com/3922667/170585455-3399022f-3ca5-422d-9b65-251cd2c145ed.png"> |
Also added an example:
> cleaned up docs for the configure method

- RevenueCat.xcodeproj/project.pbxproj
- Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift
> Split `PurchasesTests` step 5: extracted `PurchasesGetOfferingsTests`

- Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
The project now builds with no warnings 🎉
> Removed all deprecation warnings in tests / SwiftAPITester

- RevenueCat.xcodeproj/project.pbxproj
- Tests/UnitTests/Purchasing/Purchases/PurchasesGetProductsTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesTests.swift
> Split `PurchasesTests` step 10: extracted `PurchasesGetProductsTests`

- .spi.yml
> Add Swift Package Index manifest file

- Sources/Purchasing/ProductsManager.swift
- Sources/Support/BeginRefundRequestHelper.swift
Fixes #1660 and [SDKONCALL-24].
This is the same approach used in #1596.
[SDKONCALL-24]: https://revenuecats.atlassian.net/browse/SDKONCALL-24?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed Xcode 14 compilation: avoid `@available` properties

- Sources/Purchasing/PurchasesOrchestrator.swift
Comparing only error codes can lead to collisions with a completely different error.
Also refactored this check into an existing extension.
> `PurchasesOrchestrator.handleDeferredTransaction`: check `NSError.domain` too

- RevenueCat.xcodeproj/project.pbxproj
Sorted sources before adding more
> Sort Sources in project

- RevenueCat.xcodeproj/project.pbxproj
Looks like the file was moved by #1677.
> Fixed `SwiftStyleGuide` reference in project

- Tests/StoreKitUnitTests/BeginRefundRequestHelperTests.swift
- Tests/UnitTests/Mocks/MockSK1Product.swift
Equivalent to #1661 but for tests.
> Fixed test compilation with Xcode 14: avoid `@available` properties

- Tests/UnitTests/Purchasing/Purchases/PurchasesPurchasingTests.swift
For [CSDK-113].
The test now checks that when a purchase is cancelled, we never return `CustomerInfo`.
[CSDK-113]: https://revenuecats.atlassian.net/browse/CSDK-113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> `PurchasesPurchasingTests`: improved SK1 purchase cancelled test

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Identity/IdentityManager.swift
- Sources/Networking/Backend.swift
- Tests/UnitTests/Identity/IdentityManagerTests.swift
- Tests/UnitTests/Mocks/MockBackend.swift
- Tests/UnitTests/Mocks/MockIdentityAPI.swift
- Tests/UnitTests/Networking/Backend/BackendLoginTests.swift
- Tests/UnitTests/Networking/Backend/BaseBackendTest.swift
resolves [CSDK-251]
[CSDK-251]: https://revenuecats.atlassian.net/browse/CSDK-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Create and plumb MockIdentityAPI

- Tests/BackendIntegrationTests/SubscriberAttributesManagerIntegrationTests.swift
> Integration tests: fixed deprecation warnings

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Attribution/AttributionNetwork.swift
- Sources/Attribution/AttributionPoster.swift
- Sources/Purchasing/Purchases/Attribution.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Tests/UnitTests/Attribution/AttributionPosterTests.swift
- Tests/UnitTests/Networking/Backend/BackendPostAttributionDataTests.swift
- Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostAttributionDataTests/iOS13-testPostAttributesPutsDataInDataKey.1.json
- Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostAttributionDataTests/iOS14-testPostAttributesPutsDataInDataKey.1.json
- Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostAttributionDataTests/iOS15-testPostAttributesPutsDataInDataKey.1.json
- Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostAttributionDataTests/iOS16-testPostAttributesPutsDataInDataKey.1.json
- Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesAttributionDataTests.swift
- Tests/UnitTests/Purchasing/PurchasesDeprecation.swift
- Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
> Handled all deprecations warnings related to iAd

- .circleci/config.yml
- Tests/StoreKitUnitTests/PriceFormatterProviderTests.swift
- Tests/StoreKitUnitTests/StoreProductTests.swift
- Tests/StoreKitUnitTests/TestHelpers/StoreKitTestHelpers.swift
Fixes [CSDK-260].
- #1698
- #1699
- #1700
- #1701
[CSDK-260]: https://revenuecats.atlassian.net/browse/CSDK-260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CircleCI: added job for iOS 16 tests

- Sources/Logging/Strings/PurchaseStrings.swift
Fixes [CSDK-259].
[CSDK-259]: https://revenuecats.atlassian.net/browse/CSDK-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> `SKPaymentTransaction`: added more context to warnings about missing properties

- Examples/MagicWeather/MagicWeather/Constants.swift
- Examples/MagicWeatherSwiftUI/Shared/Constants.swift
- scripts/pre-commit.sh
Fixes [CSDK-273].
[CSDK-273]: https://revenuecats.atlassian.net/browse/CSDK-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Added pre-commit hook to ensure API keys aren't committed

- Sources/Purchasing/Purchases/Purchases.swift
There's a broken link in `getProducts`
> fix getProducts docs broken link

- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json
See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/7535/workflows/3c2dc5ac-372c-4861-9bb0-506ce01eabd7/jobs/32015
These were wrong in #1778.
> Fixed snapshots for iOS 12 and 13

- Sources/Purchasing/Purchases/Purchases.swift
This helps with the transition to `Sendable` (see [CSDK-379]).
This also ensures that we don't leave the `NSLock` locked.
> `Purchases.shared` and `Purchases.isConfigured` are now thread-safe

- README.md
added a link to the SDK reference to the readme
> link to sdk reference

- Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
For [CSDK-394].
[CSDK-394]: https://revenuecats.atlassian.net/browse/CSDK-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> `PurchasesLogInTests`: added test to verify `logIn` updates offerings cache

- Contributing/RELEASING.md
Added a section to clarify how a hotfix should be done
> Adds hotfixes section to RELEASING doc

- Examples/MagicWeather/MagicWeather.xcodeproj/project.pbxproj
- Examples/MagicWeather/MagicWeather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/MagicWeather/README.md
pull in up to next major, fix build issue
> Build fix- Update package requirements for MagicWeather

- Sources/Purchasing/StoreKitAbstractions/SK1StoreTransaction.swift
not exactly the most complex PR I've ever made 😂 but I saw it and figured it's better to open it before I forget
> fix typo in comment

- .circleci/config.yml
- Gemfile.lock
https://github.com/RevenueCat/purchases-ios/pull/1862#issuecomment-1226835780
> Update fastlane-plugin-revenuecat_internal and fix release-train job

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Misc/StoreKit2Setting.swift
- Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
- Tests/UnitTests/Misc/StoreKit2SettingTests.swift
A couple of helpers that can be useful, for #1882 for example.
> Added `StoreKit2Setting.shouldOnlyUseStoreKit2`

- Sources/FoundationExtensions/Error+Extensions.swift
- Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
NFC. Just cleaning up the long `PurchasesOrchestrator` file.
> Refactored `Error.isCancelledError` into `Error+Extensions`

- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesPassesCustomerInfoIfStatusCodeIsSuccess.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesReturnsBadJson.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithSubscriberAttributesSendsThemCorrectly.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS12-testPostReceiptWithoutSubscriberAttributesSkipsThem.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesPassesCustomerInfoIfStatusCodeIsSuccess.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesPassesErrorIfStatusCodeIsNotSuccess.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesReturnsBadJson.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithSubscriberAttributesSendsThemCorrectly.1.json
- Tests/UnitTests/SubscriberAttributes/__Snapshots__/BackendSubscriberAttributesTests/iOS13-testPostReceiptWithoutSubscriberAttributesSkipsThem.1.json
> Fixed iOS 12/13 test snapshots

- Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
We had no test coverage for [`OfferingsManager`'s ability to ignore products that aren't found](https://github.com/RevenueCat/purchases-ios/blob/4.13.1/Sources/Purchasing/OfferingsManager.swift#L134-L140).
Added this before expanding this behavior in #1976.
> `OfferingsManager`: added missing test for ignoring missing products

- Sources/Error Handling/ErrorUtils.swift
Fixes [CSDK-491].
#1973 introduced an iOS-12 only regression:
For some reason the Swift runtime on iOS 12 fails to get the value from the `Error` existential, and gets a null pointer instead.
This workaround works, and it's equivalent on later iOS versions, just a bit redundant.
[CSDK-491]: https://revenuecats.atlassian.net/browse/CSDK-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed `ErrorUtils.purchasesError(withUntypedError:)` on iOS 12

- Sources/Identity/IdentityManager.swift
- Sources/Misc/OperationDispatcher.swift
- Sources/Networking/CustomerAPI.swift
- Sources/Purchasing/OfferingsManager.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
- Sources/Support/ManageSubscriptionsHelper.swift
Fixes [SDKONCALL-156].
This will be covered by #1990.
[SDKONCALL-156]: https://revenuecats.atlassian.net/browse/SDKONCALL-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fixed Xcode 13.2.x / Swift 5.5 compatibility

- .circleci/config.yml
To cover [SDKONCALL-156].
[SDKONCALL-156]: https://revenuecats.atlassian.net/browse/SDKONCALL-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CI: added job to test compilation with `Xcode 13.2.1` / `Swift 5.5`

- Sources/Attribution/AttributionPoster.swift
Hello.
Just deleted `Array()` where it is not necessary.
> Less Array()

- Sources/FoundationExtensions/Set+Extensions.swift
- Tests/UnitTests/FoundationExtensions/SetExtensionsTests.swift
Will be used in an upcoming PR.
> Added `Set + Set` and `Set += Set` operators

- Sources/DocCDocumentation/DocCDocumentation.docc/V4_API_Migration_guide.md
> Documentation: Fixed references in `V4_API_Migration_guide.md`

- Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
As exposed by #2038, weekly subscriptions were leading to false negatives because they were always expired by the time the purchase was made (using `TimeRate.monthlyRenewalEveryThirtySeconds`), instead of lasting 10 seconds as documented. This is reported as `FB11767559`.
The advantage of using weekly subscriptions was to also work around `FB11767679`, which means that we have to manually _wait_ for the subscription to expire, as `SKTestSession.expireSubscription(productIdentifier:)` doesn't actually change the receipt.
Because we had to wait, using weekly subscriptions was faster, since we only needed to wait 10 seconds.
This does mean that expirations in these tests now have to wait 30 seconds instead of 10, but now they're no longer flaky :tada:
Looks like tests right now pass in CI in …
> `Integration Tests`: changed weekly to monthly subscriptions to work around 0-second subscriptions

- .circleci/config.yml
See https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/8823/workflows/f2a47d52-4978-4361-bad6-c7b86a9d7dd1/jobs/43671
> `CI`: fixed `push-pods` job

- .circleci/config.yml
Equivalent to https://github.com/RevenueCat/purchases-android/pull/621
> `CircleCI`: added ability to create a release manually

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
- RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
- Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
- Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
This cleans up a few warnings.
> Updated schemes and project for Xcode 14.1

- Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
Just a documentation header typo :)
`ccurrency` -> `currency`
> Fix documentation typo

- .github/ISSUE_TEMPLATE/bug_report.md
Link was broken in the bug report template.
Updated the link to CONTRIBUTING.md
> update CONTRIBUTING.md link in bug report template

- Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
Follow up to #2104 and #2105. This ensures that `Purchases` is re-created for each test.
This will probably uncover the cause for [CSDK-517].
> `Integration Tests`: verify `Purchases` does not leak across tests

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Logging/Logger.swift
- Sources/Logging/LoggerType.swift
This will be used to inject a logger into `ReceiptParser` ([CSDK-17]).
[CSDK-17]: https://revenuecats.atlassian.net/browse/CSDK-17?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Extracted `LoggerType`

- Sources/Networking/Caching/CallbackCache.swift
This was a conflict between #2136 and #2137.
> `CallbackCache`: fixed reference

- Sources/Logging/Strings/StoreKitStrings.swift
- Sources/Purchasing/StoreKit1/StoreKitRequestFetcher.swift
This would have given more visibility into the need for #2146.
> `StoreKitRequestFetcher`: added log when starting/ending requests

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Misc/Clock.swift
- Tests/UnitTests/Mocks/TestClock.swift
This will be used in an upcoming PR, and can also be used to better test `TimingUtil.measureAndLogIfTooSlow` uses.
> Created `ClockType` and `TestClock` to be able to mock time

- Examples/MagicWeatherSwiftUI/README.md
Fixes #2141 and [SDKONCALL-190].
Also updated the minimum Xcode and deployment targets.
[SDKONCALL-190]: https://revenuecats.atlassian.net/browse/SDKONCALL-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> `MagicWeatherSwiftUI`: updated `README` to point to workspace

- Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
- Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
See #2071, #2144, and #2168.
Also refactored the test setup.
> `TrialOrIntroPriceEligibilityCheckerSK1Tests`: use `waitUntilValue`

- Tests/UnitTests/Networking/HTTPClientTests.swift
See also #2071 and #2144.
I broke these tests recently, and because we're using `toEventually` they each take over 1 second to fail, instead of failing immediately after the request finishes.
> `HTTPClientTests`: refactored to use `waitUntil`

- .circleci/config.yml
See https://discuss.circleci.com/t/xcode-14-2-released-breaking-changes/46303
> `CircleCI`: use Xcode 14.2.0

- Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Extensions/Package+Extensions.swift
- Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerInfoView.swift
- Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/CustomerView.swift
- Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/EntitlementsView.swift
- Tests/TestingApps/PurchaseTesterSwiftUI/Shared/Views/Customer/TransactionsView.swift
For [CSDK-626].
[CSDK-626]: https://revenuecats.atlassian.net/browse/CSDK-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> `PurchaseTester`: small refactor to simplify `Date` formatting

- fastlane/Fastfile
> `PurchaseTester`: added contents of `CHANGELOG.latest.md` to `TestFlight` changelog

- Sources/Identity/CustomerInfoManager.swift
Likely fixes #1877.
Thread-safety was done through a `Lock`, but nothing ensured that we didn't access the underlying data without locking.
This is done now using `Atomic<Data>` to guarantee that all reads and writes go through this lock.
> `CustomerInfoManager`: improved thread-safety

- Sources/Misc/Signing.swift
- Tests/UnitTests/Misc/SigningTests.swift
Based on #2216. Deals with [CSDK-630](https://revenuecats.atlassian.net/browse/CSDK-630).
This PR updates the `verify` method logic to match the latest changes from the backend. This has not been tested end-to-end yet.
[CSDK-630]: https://revenuecats.atlassian.net/browse/CSDK-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update response signature verification logic using backend structure of signature

- Sources/Misc/Deprecations.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Follow up to #2293.
Also fixed a couple of lint issues.
> SK2-config deprecation: fixed tests

- CHANGELOG.latest.md
- CHANGELOG.md
> Release 4.17.7 changelog

- Sources/Logging/Strings/StoreKitStrings.swift
Here's a simple logging typo fix.
> Remove Logging Typo

- Sources/FoundationExtensions/Array+Extensions.swift
- Sources/Misc/StoreKit2Setting.swift
Follow up to https://github.com/RevenueCat/purchases-ios/pull/2300, replace `iff` with the more explicit `if and only if`
> replace `iff` with `if and only if`

- Sources/Logging/Strings/ConfigureStrings.swift
- Sources/Purchasing/Purchases/Purchases.swift
CSDK-258
Adds additional logging during init:
- System/OS version
- Environment (is/is not simulator)
> Add additional logging on init

- Sources/Purchasing/Configuration.swift
Same as https://github.com/RevenueCat/purchases-android/pull/870
> `Configuration.Builder.with(entitlementVerificationMode:)`: improved documentation

- Tests/UnitTests/Networking/ETagManagerTests.swift
#2347 was not compatible with iOS 12. Those tests don't make sense there because signature verification can't be enabled, so this skips tests now.
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/10273/workflows/f6b756e0-3f24-4129-8da5-e26ce08d3a5a/jobs/58501
> `ETagManagerTests`: fixed tests on iOS 12

- Sources/Networking/HTTPClient/NetworkError.swift
- Tests/UnitTests/Networking/HTTPClientTests.swift
- Tests/UnitTests/Networking/NetworkErrorTests.swift
This will be used to handle offline entitlements.
> Implemented `NetworkError.isServerDown`

- Sources/Purchasing/OfferingsManager.swift
Fixes https://circleci.com/gh/RevenueCat/purchases-ios/59451.
This was broken in #2363.
> `OfferingsManager`: fixed Xcode 13.x build

- README.md
> Fix migration guide link

- RevenueCat.xcodeproj/project.pbxproj
- Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
- Tests/BackendIntegrationTests/Constants.swift
- Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
- Tests/TestingApps/PurchaseTester/RevenueCat_IntegrationPurchaseTesterConfiguration.storekit
- fastlane/Fastfile
~~- [x] [Detect redirects](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1411626-urlsession) and log. Verify this is happening using `TestLogger`.~~
> `Offline Entitlements`: created `LoadShedderIntegrationTests`

- .circleci/config.yml
- RevenueCat.xcodeproj/project.pbxproj
- RevenueCat.xcodeproj/xcshareddata/xcschemes/BackendIntegrationTests.xcscheme
- RevenueCat.xcodeproj/xcshareddata/xcschemes/ReceiptParser.xcscheme
- RevenueCat.xcodeproj/xcshareddata/xcschemes/RevenueCat.xcscheme
- Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/ObjCAPITester/ObjCAPITester.xcodeproj/xcshareddata/xcschemes/ObjCAPITester.xcscheme
- Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/ReceiptParserAPITester/ReceiptParserAPITester.xcodeproj/xcshareddata/xcschemes/ReceiptParserAPITester.xcscheme
- Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/project.pbxproj
- Tests/APITesters/SwiftAPITester/SwiftAPITester.xcodeproj/xcshareddata/xcschemes/SwiftAPITester.xcscheme
- Tests/v3LoadShedderIntegration/v3LoadShedderIntegration.xcodeproj/xcshareddata/xcschemes/v3LoadShedderIntegration.xcscheme
See https://discuss.circleci.com/t/xcode-14-3-rc-released-macos-ventura/47541
> `CircleCI`: use `Xcode 14.3.0`

- .swiftlint.yml
- Tests/v3LoadShedderIntegration/v3LoadShedderIntegrationTests/V3LoadShedderIntegrationTests.swift
clean up from PR comments in https://github.com/RevenueCat/purchases-ios/pull/2387
> clean up v3 load shedder integration tests

- Sources/Logging/Strings/PurchaseStrings.swift
- Sources/Purchasing/StoreKit1/StoreKit1Wrapper.swift
> `StoreKit1Wrapper`: added log when adding payment to queue

- Sources/Logging/Strings/ConfigureStrings.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Adds tests for customEntitlementsComputation. 
Based on #2416
> `customEntitlementComputation` part 3: tests

- Sources/Purchasing/Purchases/PurchasesType.swift
- No code changes
Updated the docs for async functions. These were missed probably because they were copied from their completion-handler based counterparts.
> Fixed docs

- Examples/testCustomEntitlementsComputation/README.md
- Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
Updated the copy in the sample app to explain the new usage
> `customEntitlementsComputation`: update the copy in the sample app to explain the new usage

- Examples/testCustomEntitlementsComputation/testCustomEntitlementsComputation/ContentView.swift
fixes resubscribes to customerInfoStream in the CustomEntitlementsComputation sample app
> CustomEntitlementsComputation sample app: fix resubscribes to customerInfoStream

- Sources/Caching/DeviceCache.swift
Just a small refactor to make user-dependent keys require it at the type level instead of having concatenation of the keys everywhere.
This still could use much more refactoring to make the code more maintainable, but this is just a small change to make it easier to add new keys.
> `DeviceCache`: refactored cache keys

- Sources/Networking/HTTPClient/ETagManager.swift
- Tests/UnitTests/Networking/ETagManagerTests.swift
This is not desirable behavior: it will lead to the backend assuming that the contents are very fresh, when they might be super old. This will in turn lead to bad prioritization of requests. 
If we don't have a validation date for an eTag, we should just not send it.
> `ETagManager`: don't send validation time if not present

- Sources/FoundationExtensions/AsyncExtensions.swift
- Tests/UnitTests/FoundationExtensions/AsyncExtensionsTests.swift
- Tests/UnitTests/Mocks/MockAsyncSequence.swift
- Tests/UnitTests/TestHelpers/AsyncTestHelpers.swift
I'm using this for an upcoming PR, so I'm moving it to `AsyncExtensions` and added tests for it.
> Extracted and tested `AsyncSequence.extractValues`

- Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
I broke this when doing Android metadata 😇 
Updated the snapshot response with new metadata field 🤷‍♂️
> Fix load shedder integration tests

- CHANGELOG.md
> Release notes for `4.19.1`

- Sources/Logging/Strings/CustomerInfoStrings.swift
> `Offline Entitlements`: improved computation log

- Sources/Support/DebugUI/DebugContentViews.swift
> `debugRevenueCatOverlay`: added ability to display new `SubscriptionStoreView`

- Sources/Error Handling/ErrorCode.swift
> `ErrorCode.networkError`: improved description

- Examples/MagicWeatherSwiftUI/Magic Weather SwiftUI.xcodeproj/project.pbxproj
- Examples/MagicWeatherSwiftUI/Shared/PrivacyInfo.xcprivacy
- Package.swift
- RevenueCat.xcodeproj/project.pbxproj
- Sources/PrivacyInfo.xcprivacy
- Tests/TestingApps/PurchaseTesterSwiftUI/PrivacyInfo.xcprivacy
- Tests/TestingApps/PurchaseTesterSwiftUI/PurchaseTester.xcodeproj/project.pbxproj
> Added `.xcprivacy` for Xcode 15

- Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
It can now return signatures 🎉
> `LoadShedderIntegrationTests`: enable signature verification

- Sources/FoundationExtensions/Array+Extensions.swift
- Tests/UnitTests/FoundationExtensions/ArrayExtensionsTests.swift
This will be used in an upcoming PR.
> Add `Sequence<AdditiveArithmetic>.sum()`

- Sources/Misc/SystemInfo.swift
- Tests/UnitTests/Misc/SystemInfoTests.swift
- Tests/UnitTests/Networking/HTTPClientTests.swift
Working on #2722 I noticed we didn't have test coverage for this.
> `SystemInfo.identifierForVendor`: add tests

- Tests/TestingApps/SimpleApp/SimpleApp.xcodeproj/project.pbxproj
This matches the ID in the dashboard.
> `SimpleApp`: changed bundle identifier

- Tests/BackendIntegrationTests/BaseBackendIntegrationTests.swift
- Tests/BackendIntegrationTests/CustomEntitlementsComputationIntegrationTests.swift
- Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
- Tests/BackendIntegrationTests/SignatureVerificationIntegrationTests.swift
- Tests/BackendIntegrationTests/StoreKitIntegrationTests.swift
Depends on https://github.com/RevenueCat/khepri/pull/6121
> `Integration Tests`: re-enable signature verification tests

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Purchasing/PackageType.swift
- Tests/UnitTests/Purchasing/PackageTypeTests.swift
This will be used for decoding it inside of `PaywallData`.
> `PackageType: Codable` implementation

- Sources/Paywalls/PaywallData.swift
- Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_and_default_locale.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json
These now match how the frontend is configuring them.
> `Paywalls`: updated `PaywallData` field names

- RevenueCatUI/Views/DebugErrorView.swift
Tiny PR so I can feel like I'm contributing 😅 
Also helps me catch up with current status
| :-: | :-: |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-07-24 at 19 06 03](https://github.com/RevenueCat/purchases-ios/assets/3922667/2d6be10f-891a-48da-8c3f-0b0728438130) | ![Simulator Screenshot - iPhone 14 Pro - 2023-07-24 at 19 05 26](https://github.com/RevenueCat/purchases-ios/assets/3922667/8b65c898-df9e-4fcd-bd0e-fc738652330d) |
> `Paywalls`: clean up the error view

- RevenueCatUI/Data/Localization.swift
- RevenueCatUI/Data/Variables.swift
- RevenueCatUI/Helpers/Package+VariableDataProvider.swift
- RevenueCatUI/Resources/en.lproj/Localizable.strings
- RevenueCatUI/Resources/es.lproj/Localizable.strings
- Tests/RevenueCatUITests/Data/VariablesTests.swift
- Tests/RevenueCatUITests/LocalizationTests.swift
This represents the localized `PackageType`.
> `Paywalls`: new `{{ period }}` variable

- RevenueCatUI/Data/TestData.swift
- RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
- RevenueCatUI/Helpers/PaywallData+Default.swift
- RevenueCatUI/Templates/MultiPackageTemplate.swift
- RevenueCatUI/Views/FooterView.swift
- Sources/Paywalls/PaywallColor.swift
- Sources/Paywalls/PaywallData.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
- Tests/RevenueCatUITests/PaywallViewLocalizationTests.swift
- Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_and_default_locale.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json
- Tests/UnitTests/Paywalls/PaywallDataTests.swift
Also updated the second template with them:
> `Paywalls`: added accent colors

- Tests/TestingApps/SimpleApp/SimpleApp.xcodeproj/project.pbxproj
- Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Views/AppContentView.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
> `Paywalls`: added sample paywalls to `SimpleApp`

- RevenueCatUI/Templates/MultiPackageBoldTemplate.swift
- Tests/TestingApps/SimpleApp/SimpleApp.xcodeproj/project.pbxproj
- Tests/TestingApps/SimpleApp/SimpleApp/Views/AppContentView.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Views/OfferingsList.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Views/SamplePaywallsList.swift
> `Paywalls`: added `OfferingsList` to preview all paywalls

- RevenueCatUI/PaywallView.swift
Turns out that this:
```swift
NavigationStack {
PaywallView()
}
```
Exposed `FB12674350` (https://twitter.com/nachosoto/status/1681447887077801989?s=61&t=gy8vpJJPeGJzezleoRlJiw). Except this also reproduced on simulator AND device.
Notice how it's the same thing: an `if` statement changing branches after a `@State` change. Luckily the same workaround works.
> `Paywalls`: work around SwiftUI bug to allow embedding `PaywallView` inside `NavigationStack`

- RevenueCatUI/Data/Strings.swift
- RevenueCatUI/Data/TemplateViewConfiguration.swift
- RevenueCatUI/Data/Variables.swift
- RevenueCatUI/Helpers/Logger.swift
- RevenueCatUI/View+PresentPaywall.swift
Also improved logging by using `verboseLogHandler` and a new `Strings` enum.
> `Paywalls`: added a few more logs

- RevenueCatUI/Templates/MultiPackageBoldTemplate.swift
- RevenueCatUI/Views/TemplateBackgroundImageView.swift
To be used by future templates.
> `Paywalls`: extracted `TemplateBackgroundImageView`

- RevenueCatUI/Data/Errors/TemplateError.swift
- RevenueCatUI/Data/Strings.swift
- RevenueCatUI/Data/TemplateViewConfiguration.swift
- RevenueCatUI/Data/TestData.swift
- RevenueCatUI/Helpers/PaywallData+Default.swift
- Sources/Paywalls/PaywallData.swift
- Sources/Purchasing/Package.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPackageAPI.m
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PackageAPI.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
- Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
- Tests/RevenueCatUITests/Templates/PaywallViewLocalizationTests.swift
- Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift
- Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
- Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
- Tests/UnitTests/Paywalls/PaywallDataTests.swift
- Tests/UnitTests/Purchasing/OfferingsTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesGetOfferingsTests.swift
> `Paywalls`: added support for `PackageType.custom`

- Sources/Paywalls/PaywallColor.swift
- Sources/Paywalls/PaywallData.swift
- Sources/Support/DebugUI/DebugContentViews.swift
> `Paywalls`: added JSON debug screen to `debugRevenueCatOverlay`

- RevenueCatUI/Helpers/PaywallData+Default.swift
- RevenueCatUI/PaywallView.swift
- RevenueCatUI/Templates/Template2View.swift
- Sources/Paywalls/PaywallColor.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Assets.xcassets/AccentColor.colorset/Contents.json
> `Paywalls`: improved default template

- RevenueCatUI/Data/TestData.swift
- RevenueCatUI/Templates/Template3View.swift
- Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift
Thanks to @joshdholtz for finding this.
> `Paywalls`: fixed color in template 3

- RevenueCatUI/Templates/Template2View.swift
> `Paywalls`: improved template 2 unselected packages

- RevenueCatUI/Data/Strings.swift
- RevenueCatUI/Data/Variables.swift
Also added a link to the new docs.
> `Paywalls`: improved variable warning

- RevenueCatUI/Templates/TemplateViewType.swift
This is a start of some basic documentation for some basic principles to follow when implementing new templates.
> `Paywalls`: internal documentation for implementing templates

- Sources/Support/PaywallExtensions.swift
This became a requirement with #3032.
> `StoreKit 2`: added warning to paywall constructors

- RevenueCatUI/Data/PaywallViewMode+Extensions.swift
- RevenueCatUI/Data/TemplateViewConfiguration+Images.swift
- RevenueCatUI/Templates/Template2View.swift
- RevenueCatUI/Views/TemplateBackgroundImageView.swift
> `Paywalls`: improved unselected package background color

- Sources/Misc/Concurrency/Purchases+async.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
> `CustomEntitlementComputation`: enable `restorePurchases` in public API

- RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
- RevenueCatUI/Views/PurchaseButton.swift
- Sources/Paywalls/PaywallData.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
- Tests/UnitTests/Paywalls/PaywallDataTests.swift
> `Paywalls`: add support for CTA button gradients

- Sources/Support/DebugUI/DebugContentViews.swift
> `Debug`: add `Offering` metadata to debug screen

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Diagnostics/FileHandler.swift
- Sources/Paywalls/Events/PaywallEventSerializer.swift
- Sources/Paywalls/Events/PaywallEventStore.swift
- Sources/Paywalls/Events/PaywallStoredEvent.swift
- Tests/UnitTests/Mocks/MockFileHandler.swift
- Tests/UnitTests/Paywalls/Events/PaywallEventSerializerTests.swift
- Tests/UnitTests/Paywalls/Events/PaywallEventStoreTests.swift
- New `PaywallEventStore` using `FileHandler` (#2673)
- `MockFileHandler`
- `PaywallStoredEvent`: this contains the necessary information to store an event: `PaywallEvent` + user ID
- Created `PaywallEventSerializer`
> `Paywalls`: created `PaywallEventStore`

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Logging/Strings/PaywallsStrings.swift
- Sources/Paywalls/Events/PaywallEventsManager.swift
- Tests/UnitTests/Mocks/MockPaywallEventsManager.swift
- Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
This combines the types created in prior PRs (#3157, #3158) to store and post events.
> `Paywalls`: created `PaywallEventsManager`

- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
key in the sample json was wrong
> `Paywalls`: update `blurred_background_image` key in `PaywallData` test fixture

- Sources/Paywalls/Events/Networking/PaywallEventsRequest.swift
> `Paywalls`: send event timestamps in ms

- Tests/TestingApps/SimpleApp/SimpleApp/SamplePaywalls.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Views/AppContentView.swift
- Tests/TestingApps/SimpleApp/SimpleApp/Views/CustomPaywall.swift
We're currently making debug builds for it, but this fixes the release build in case we want to do that (like for profiling).
> `Paywalls`: fixed SimpleApp release build

- Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
Simplified this into a single line.
> `PurchasedProductsFetcher`: refactored `fetchTransactions`

- RevenueCatUI/Helpers/PaywallData+Default.swift
Noticed this property can be private
> Make revisionID private in PaywallData+Default

- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
This one is a total pet peeve, but it was annoying to me that every time you open the PaywallsTester it opens up the modal, since most of the time I'm not actually testing the default paywall. 
This replaces that behavior with an explicit button for it, but it otherwise retains the rest of the behavior. 
Happy to close this one out if others preferred the default paywall opening up by itself every time.
> PaywallsTester: replace opening default paywall automatically with button

- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/PaywallViewMode+Extensions.swift
Just a few small things I noticed in #3254.
> `Paywalls`: small PaywallsTester refactor

- Sources/Misc/Concurrency/Purchases+nonasync.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
- Sources/Purchasing/Purchases/PurchasesType.swift
- Sources/Support/StoreMessageType.swift
- Sources/Support/StoreMessagesHelper.swift
- Tests/APITesters/ObjCAPITester/ObjCAPITester/RCPurchasesAPI.m
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
- Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
- Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
- Tests/StoreKitUnitTests/TestHelpers/AvailabilityChecks.swift
- Tests/UnitTests/Mocks/MockPurchases.swift
- Tests/UnitTests/Mocks/MockStoreMessagesHelper.swift
- Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
- Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
> Refactored `StoreMessagesHelper`

- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
> `Paywalls Tester`: group live paywalls by template

- .circleci/config.yml
- RevenueCatUI/PaywallFontProvider.swift
- RevenueCatUI/Templates/Template4View.swift
- RevenueCatUI/Views/FooterView.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/SamplePaywallsList.swift
- fastlane/Fastfile
> `Paywalls`: `visionOS` support

- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/OfferingsList.swift
We're currently deploying a `DEBUG` build, but this fixes compilation of the release builds too.
> `Paywalls Tester`: fix release build

- RevenueCatUI/View+PresentPaywall.swift
- Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewAPI.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/UpsellView.swift
Without this there is no way to know when the paywall was dismissed.
> `Paywalls`: new `onDismiss` parameter for `presentPaywallIfNeeded`

- Sources/Purchasing/StoreKitAbstractions/StoreProduct.swift
- Sources/Purchasing/StoreKitAbstractions/SubscriptionPeriod.swift
- Tests/APITesters/ObjCAPITester/ObjCAPITester/RCStoreProductAPI.m
- Tests/APITesters/SwiftAPITester/SwiftAPITester/StoreProductAPI.swift
- Tests/UnitTests/Purchasing/StoreKitAbstractions/SubscriptionPeriodTests.swift
This will be used to offer a new paywalls variable.
> Add `StoreProduct.pricePerWeek`

- RevenueCatUI/Resources/tr.lproj/Localizable.strings
I updated translation of `Restore purchases`.
> `Paywalls`: fix Turkish translation

- RevenueCatUI/UIKit/PaywallViewController.swift
- Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
See #3359.
This brings support for that parameter to the `UIKit` type.
> `Paywalls`: add `displayCloseButton` to `PaywallViewController`

- Purchases/Misc/RCSystemInfo.h
- Purchases/Misc/RCSystemInfo.m
- PurchasesTests/Misc/SystemInfoTests.swift
This brings #2276 and #2176 to v3.x.
> `RCSystemInfo.isSandbox`: improve implementation

- Sources/Paywalls/PaywallData.swift
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall-watchOS.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedIconsGeneratesDefaultPaywall.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall-watchOS.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedTemplateNameGeneratesDefaultPaywall.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall-watchOS.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableGeneratesDefaultPaywall.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall-watchOS.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testUnrecognizedVariableInFeaturesGeneratesDefaultPaywall.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall-watchOS.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywall.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization-watchOS.1.json
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateMissingPaywallWithSpanishLocalization.1.json
- Tests/UnitTests/Networking/Responses/Fixtures/Offerings.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-Sample1.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-empty_images.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_current_locale.json
- Tests/UnitTests/Networking/Responses/Fixtures/PaywallData-missing_localization.json
- Tests/UnitTests/Networking/Responses/OfferingsDecodingTests.swift
- Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
- Tests/UnitTests/Paywalls/PaywallDataTests.swift
This is a performance optimization.
> `Paywalls`: use `HEIC` images

- .circleci/config.yml
- RevenueCatUI/Modifiers/ViewExtensions.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/16723/workflows/5cfced30-b183-4bc0-8a5d-64c318d20cdc/jobs/152589
Also adds test coverage to catch these issues with the same CI job.
> `Paywalls`: fix compilation on Xcode < 14.3

- Tests/UnitTests/Networking/Backend/__Snapshots__/BackendPostReceiptDataTests/iOS12-testPostsSK2XcodeReceiptWithProductDataCorrectly.1.json
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/16776/workflows/1893d295-966c-4a9d-8332-e2928f7f88d7/jobs/153671/tests
> `Tests`: fix iOS 12 snapshot

- RevenueCatUI/UIKit/PaywallFooterViewController.swift
- RevenueCatUI/UIKit/PaywallViewController.swift
- Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Views/AppContentView.swift
This adds a new `PaywallFooterViewController`. This VC will be used to render the footer view in the hybrids.
> `Paywalls`: add `PaywallFooterViewController`

- RevenueCatUI/UIKit/PaywallFooterViewController.swift
- RevenueCatUI/UIKit/PaywallViewController.swift
Improves support for FooterView by adding layout constraints so that the footer can automatically size itself, and adding a clear background for the cutout to show properly
> Paywalls: improve footer view UIKit support for hybrid SDKs

- Sources/Purchasing/Purchases/Attribution.swift
- Tests/UnitTests/Paywalls/Events/PaywallEventsManagerTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesGetCustomerInfoTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesLogInTests.swift
- Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
Attempting to fix some test flakiness. 
Not the cleanest fixes, but flaky tests are dangerous. 
My methodology was to run tests over and over and fix the ones that would occasionally fail.
> Tests: improve test flakiness

- RevenueCatUI/UIKit/PaywallFooterViewController.swift
- RevenueCatUI/UIKit/PaywallViewController.swift
- Tests/APITesters/RevenueCatUIAPITester/SwiftAPITester/PaywallViewControllerAPI.swift
This allows creating a paywall through the UIKit API and provide a custom font provider.
> `PaywallViewController`: add `PaywallFontProvider` parameter

- .circleci/config.yml
See https://discuss.circleci.com/t/xcode-15-2-released/50197
> `CI`: update to Xcode 15.2

- Sources/Logging/Strings/ConfigureStrings.swift
- Sources/Misc/Obsoletions.swift
- Sources/Purchasing/Configuration.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Sources/Purchasing/Purchases/PurchasesType.swift
- Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
- Tests/APITesters/ObjCAPITester/ObjCAPITester/RCConfigurationAPI.m
- Tests/APITesters/SwiftAPITester/SwiftAPITester/ConfigurationAPI.swift
- Tests/TestingApps/PurchaseTesterSwiftUI/Core/ConfiguredPurchases.swift
- Tests/UnitTests/Purchasing/ConfigurationTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesConfiguringTests.swift
Default to StoreKit 1 when enabling observer mode.
> [SK2] Set StoreKit version when enabling observer mode

- Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
Fixes https://app.circleci.com/pipelines/github/RevenueCat/purchases-ios/17429/workflows/7c44f871-14f4-4eaf-82b1-ed891eda7400/jobs/170500
> `Tests`: fix iOS 15 test crash

- RevenueCatUI/Data/TemplateViewConfiguration.swift
- RevenueCatUI/TemplatePackageSetting.swift
- RevenueCatUI/Templates/TemplateViewType.swift
This will be used for multi-tier paywalls.
> `Paywalls`: extract `TemplatePackageSetting` and add `TemplateTierSetting`

- .circleci/config.yml
This will run the load shedder integration tests on release branches.
> Run load shedder integration tests on release branches

- RevenueCatUI/Helpers/ColorInformation+MultiScheme.swift
- Sources/Paywalls/PaywallData.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
- Tests/UnitTests/Paywalls/PaywallDataTests.swift
This will allow the implementation of _color overrides_ by tier for the upcoming multi-tier paywall.
> `PaywallData`: change all `Color`s to be optional

- RevenueCatUI/Data/Constants.swift
- RevenueCatUI/Views/TierSelectorView.swift
https://github.com/RevenueCat/purchases-ios/assets/685609/352e6a0e-c701-44c1-bd9a-241031eae125
> `Paywalls`: add `TierSelectorView`

- Sources/Paywalls/PaywallCacheWarming.swift
- Tests/UnitTests/Paywalls/PaywallCacheWarmingTests.swift
> `Paywalls`: add support for image overrides in `PaywallCacheWarming`

- RevenueCatUI/Data/Errors/TemplateError.swift
- RevenueCatUI/Data/IntroEligibility/IntroEligibilityViewModel.swift
- RevenueCatUI/Data/PaywallData+Validation.swift
- RevenueCatUI/Data/TemplateViewConfiguration.swift
- RevenueCatUI/Data/TestData.swift
- RevenueCatUI/TemplatePackageSetting.swift
- RevenueCatUI/Templates/TemplateViewType.swift
- Sources/Paywalls/PaywallData+Localization.swift
- Sources/Paywalls/PaywallData.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PaywallAPI.swift
- Tests/RevenueCatUITests/Data/TemplateViewConfigurationTests.swift
- Tests/RevenueCatUITests/Helpers/DataExtensions.swift
- Tests/UnitTests/Paywalls/PaywallDataMultiTierTests.swift
- Tests/UnitTests/Paywalls/PaywallDataTests.swift
This adds `TemplatePackageSetting.multiTier` and `TemplateViewConfiguration.PackageConfiguration.multiTier`.
> `Paywalls`: processing multi-tier `TemplateViewConfiguration`

- RevenueCatUI/Data/TemplateViewConfiguration.swift
- RevenueCatUI/Templates/Other platforms/WatchTemplateView.swift
> `Paywalls`: `watchOS` support for multi-tier paywalls

- RevenueCatUI/Data/TemplateViewConfiguration+Images.swift
- RevenueCatUI/Data/TestData.swift
- RevenueCatUI/Templates/Template7View.swift
- Sources/Paywalls/PaywallData.swift
- Tests/RevenueCatUITests/Data/__Snapshots__/PaywallDataValidationTests/testValidateValidMultiTierPaywall.1.json
- Tests/RevenueCatUITests/Helpers/DataExtensions.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/SamplePaywalls.swift
https://github.com/RevenueCat/purchases-ios/assets/685609/2d761ce1-cd06-44ac-999b-5d4d78087ce6
> `Paywalls`: template 7 allows image overrides by tier

- fastlane/Fastfile
> Commit all docs files

- fastlane/Fastfile
> Do not update the documentation index.html file if version is prerelease

- Sources/Purchasing/CachingTrialOrIntroPriceEligibilityChecker.swift
Making the comments as clean as possible. 
Single word spelling error fix
> Spelling typo fix to comment

- RevenueCatUI/UIKit/PaywallViewController.swift
Add function to be used from the hybrids (https://github.com/RevenueCat/react-native-purchases/pull/913)
> Paywalls: add `updateWithDisplayCloseButton` to `PaywallViewController`

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Diagnostics/Networking/DiagnosticsHTTPRequestPath.swift
- Sources/Networking/HTTPClient/HTTPRequest.swift
- Sources/Networking/HTTPClient/HTTPRequestPath.swift
Create DiagnosticsHTTPRequestPath for Diagnostics
Depends on #3790 which adds the name
> Add HTTPRequest.DiagnosticsPath

- Sources/Security/VerificationResult.swift
> Add name to VerificationResult

- Sources/Networking/HTTPClient/HTTPRequestPath.swift
- Sources/Paywalls/Events/Networking/PaywallHTTPRequestPath.swift
This will be used for diagnostics
> Add name property to HTTPRequestPath

- Sources/Networking/HTTPClient/ETagManager.swift
- Sources/Networking/HTTPClient/HTTPResponse.swift
This is needed for Diagnostics
> Add origin to HTTPResponseType

- Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
- Tests/TestingApps/PaywallsTester/PaywallsTester/Data/ApplicationData.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Mocks/MockData.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Networking/HTTPClient.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsTester.entitlements
- Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/OfferingsResponse.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Responses/PaywallsResponse.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/SimpleApp.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/AsyncButton.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Utility Views/ErrorDisplay.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppContentView.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/AppList.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginScreen.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/Login/LoginWall.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingsList.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Adds authentication logic, and a login wall to the All Paywalls tab.
The app does not do anything with the logged in status at this point.
> 2. Paywalls Tester: Authentication Logic + Log in wall

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Logging/Strings/DiagnosticsStrings.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Sources/Purchasing/Purchases/PurchasesOrchestrator.swift
- Tests/StoreKitUnitTests/PurchasesOrchestratorTests.swift
- Tests/UnitTests/Mocks/MockDiagnosticsSynchronizer.swift
Adds a call to syncDiagnosticsIfNeeded on initialization
> Syncs diagnostics on initialization

- .circleci/config.yml
Previously the sync with SPM occurred before the release PR had been merged. This PR should correct that.
> Push to SPM after release has been made

- .circleci/config.yml
SPM repo did not get updated for 4.41.2, this will hopefully fix the issue.
> Update config.yml for SPM repo copy

- Gemfile.lock
- scripts/docs/index.html
This gets the latest version of the plugin with some fixes for the index.html automation update and makes the index.html point to the latest stable version.
> Update fastlane plugin and fix docs index path

- Tests/TestingApps/PaywallsTester/PaywallsTester/Configuration.swift
- Tests/TestingApps/PaywallsTester/ci_scripts/ci_pre_xcodebuild.sh
Use key defined in Xcode Cloud.
> Paywalls Tester: Use key defined in CI

- .circleci/config.yml
- .swiftlint.yml
- Sources/Networking/HTTPClient/HTTPClient.swift
- Sources/Purchasing/StoreKitAbstractions/PromotionalOffer.swift
- Sources/Purchasing/StoreKitAbstractions/SK2StoreProduct.swift
- Tests/APITesters/CustomEntitlementComputationSwiftAPITester/SwiftAPITester/PurchasesAPI.swift
- Tests/APITesters/SwiftAPITester/SwiftAPITester/PurchasesAPI.swift
Reverts RevenueCat/purchases-ios#3909
Going to implement a different solution into `main`
> Revert "Fix lint and CI with latest `swiftlint` version (0.55.1)"

- Sources/Misc/Obsoletions.swift
This PR fixes some obsoletion messages related to observer mode.
> Fix observer mode obsoletion messages

- .circleci/config.yml
- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/LocalConfigItems.swift
Ignore this PR, I'm just testing whether the release branch triggers from #4025 work correctly
> Test: release branch triggers

- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
As the title says. There's a new section called "Customer Center".
> [Customer Center] Adds the Customer Center to PaywallsTester

- .circleci/config.yml
- .github/workflows/trigger_all_tests.yml
fixes the parameters passed in when triggering tests from a github comment
> [CI]: fix CI test trigger parameters

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigTestData.swift
- RevenueCatUI/CustomerCenter/Data/CustomerCenterEnvironment.swift
- RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
- RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
- RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
- RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
- RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
- RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
- RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
- RevenueCatUI/CustomerCenter/Views/TintedProgressView.swift
- Sources/CustomerCenter/CustomerCenterConfigData.swift
- Sources/Networking/Responses/CustomerCenterConfigResponse.swift
- Tests/UnitTests/CustomerCenter/CustomerCenterConfigDataTests.swift
- Tests/UnitTests/Networking/Backend/BackendGetCustomerCenterConfigTests.swift
Builds buttons from the Appearance object in the JSON
> [Customer Center] Add colors support

- .github/workflows/trigger_all_tests.yml
Small cleanup from comments in #4084
> Cleanup `trigger_all_tests` github workflow

- .circleci/config.yml
I spent a little longer than I'd like to admit trying to figure out how to trigger all of the CI tests manually on a branch in CircleCI, so I clarified the comments a little 😅
I'll look for a way to document this in a more visible location in our documentation soon!
> Clarify Instructions to Run All Manual Tests

- RevenueCat.xcodeproj/project.pbxproj
I think this comes from a bad merge, because this project doesn't touch that file. Xcode is automatically cleaning it up
> [Customer Center] Fix project.pbxproj

- RevenueCatUI/CustomerCenter/ViewModels/FeedbackSurveyViewModel.swift
- RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptionsViewModel.swift
- Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
We were not checking if the user is eligible for the promotional offer before trying to load it
> [Customer Center] Fix checking eligibility

- RevenueCatUI/CustomerCenter/ManageSubscriptionsButtonStyle.swift
- RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
- RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
- RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
- RevenueCatUI/CustomerCenter/Views/PromotionalOfferView.swift
The subscription details view could take advantage of more available space
- expands details view
- increases font sizes
- wraps in a scrollview for smaller screen sizes
- softens shadow
- have buttons fill available space, limit width via container views
| New           | Old           |
|:-------------:|:-------------:|
| ![New Version](https://github.com/user-attachments/assets/27c4a7fd-60be-4536-b88c-b2c9c6141c8f) | ![Old Version](https://github.com/user-attachments/assets/9bd80877-4fa6-4c7e-a813-5e7a3c1bbcc2) |
> [Customer Center] Improve subscription details view

- RevenueCatUI/Data/PaywallTemplate.swift
- RevenueCatUI/Data/TemplateViewConfiguration.swift
- RevenueCatUI/Templates/Components/ImageComponentView.swift
- RevenueCatUI/Templates/Components/SpacerComponentView.swift
- RevenueCatUI/Templates/Components/TemplateComponentsView.swift
- RevenueCatUI/Templates/Components/TextComponentView.swift
- RevenueCatUI/Templates/Components/TiersComponentView.swift
- RevenueCatUI/Templates/TemplateViewType.swift
- RevenueCatUI/Views/TemplatePackageSetting.swift
- Sources/Paywalls/Components/PaywallComponentBases.swift
- Sources/Paywalls/Components/PaywallImageComponent.swift
- Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
- Sources/Paywalls/Components/PaywallSpacerComponent.swift
- Sources/Paywalls/Components/PaywallTextComopnent.swift
- Sources/Paywalls/Components/PaywallTiersComponent.swift
- Sources/Paywalls/PaywallData.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Adds a feature flag that allows us to merge the paywalls component to main but keep it out of any compiled packages. Avoids the pains of a long-running feature branch.
> Adds Paywalls Components Compiler Feature Flag

- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Should fix the Xcode cloud failure.
> Add missing `#if PAYWALL_COMPONENTS`

- Tests/UnitTests/TestHelpers/SnapshotTesting+Extensions.swift
As the title says. At least, that's the idea.
> Fixes SwiftLint violation of rule optional_data_string_conversion

- Sources/DocCDocumentation/DocCDocumentation.docc/V5_API_Migration_guide.md
> Add warnings and clarifications to v5 migration docs

- RevenueCatUI/Templates/Components/Image/ImageComponentView.swift
- RevenueCatUI/Templates/Components/Image/ImageComponentViewModel.swift
- RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentView.swift
- RevenueCatUI/Templates/Components/LinkButton/LinkButtonComponentViewModel.swift
- RevenueCatUI/Templates/Components/Package/PackageComponentView.swift
- RevenueCatUI/Templates/Components/Package/PackageComponentViewModel.swift
- RevenueCatUI/Templates/Components/PurchaseButton/PurchaseButtonComponentView.swift
- RevenueCatUI/Templates/Components/PurchaseButton/PurchaseButtonComponentViewModel.swift
- RevenueCatUI/Templates/Components/Spacer/SpacerComponentViewModel.swift
- RevenueCatUI/Templates/Components/Stack/StackComponentView.swift
- RevenueCatUI/Templates/Components/Stack/StackComponentViewModel.swift
- RevenueCatUI/Templates/Components/Text/TextComponentView.swift
- RevenueCatUI/Templates/Components/Text/TextComponentViewModel.swift
- Sources/Paywalls/Components/PaywallImageComponent.swift
- Sources/Paywalls/Components/PaywallLinkButtonComponent.swift
- Sources/Paywalls/Components/PaywallPackageComponent.swift
- Sources/Paywalls/Components/PaywallPackagesComponent.swift
- Sources/Paywalls/Components/PaywallPurchaseButtonComponent.swift
- Sources/Paywalls/Components/PaywallSpacerComponent.swift
- Sources/Paywalls/Components/PaywallStackComponent.swift
- Sources/Paywalls/Components/PaywallTextComopnent.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
> [POC] Components have selected version of themselves

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
Removes custom background from `FeedbackSurveyView`, since we only want to apply this in the promo offer view
> Remove background from FeedbackSurveyView

- Sources/Diagnostics/DiagnosticsEvent.swift
- Sources/Diagnostics/DiagnosticsTracker.swift
- Sources/Diagnostics/Networking/DiagnosticsEventsRequest.swift
- Sources/Purchasing/ProductsManager.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Tests/StoreKitUnitTests/BasePurchasesOrchestratorTests.swift
- Tests/StoreKitUnitTests/CachingProductsManagerTests.swift
- Tests/StoreKitUnitTests/OfferingsManagerStoreKitTests.swift
- Tests/StoreKitUnitTests/ProductsManagerTests.swift
- Tests/StoreKitUnitTests/StoreKit2/StoreKit2CachingProductsManagerTests.swift
- Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK1Tests.swift
- Tests/StoreKitUnitTests/TrialOrIntroPriceEligibilityCheckerSK2Tests.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/Configuration.swift
- Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
- Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
- Tests/UnitTests/Mocks/MockTrialOrIntroPriceEligibilityChecker.swift
- Tests/UnitTests/Purchasing/CachingProductsManagerTests.swift
- Tests/UnitTests/Purchasing/IntroEligibilityCalculatorTests.swift
- Tests/UnitTests/Purchasing/OfferingsManagerTests.swift
- Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
- Tests/UnitTests/Purchasing/Purchases/TransactionPosterTests.swift
- Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
This adds a new diagnostics event `apple_products_request` that tracks the results when fetching products from Apple.
> [Diagnostics] Add `apple_products_request` event

- Sources/Support/StoreMessagesHelper.swift
- Tests/StoreKitUnitTests/StoreMessagesHelperTests.swift
> Don't remove all messages with the same reason

- RevenueCatUI/Templates/Components/Button/ButtonComponentView.swift
> ButtonComponent can show the Customer Center

- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/SamplePaywalls.swift
There was a missing check for `PAYWALL_COMPONENTS` flag
> Fix `PaywallsTester` compilation

- Sources/Purchasing/Purchases/PurchaseParams.swift
This PR updates the code sample in the `PurchaseParams` class-level DocC to accurately reflect the purchasing interface.
> Update PurchaseParam code sample

- RevenueCatUI/Templates/V2/Components/Text/TextComponentView.swift
- RevenueCatUI/Templates/V2/Components/Text/TextComponentViewModel.swift
- RevenueCatUI/Templates/V2/ViewHelpers/SizeModifier.swift
> [Paywalls] Use .frame(alignment:) to fix alignment in non-multiline text components

- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
In order to make it faster to iterate when designing a paywall, this PR introduces a button in the `Sandbox Paywalls` which refreshes the offering list.
Additionally, the `shift + r` shortcut will refresh the offerings, and if a paywall is already presented, it will be reopened with the latest changes.
Limitation: because it's using `syncAttributesAndOfferingsIfNeeded` to force refresh the offerings, it is limited to 5 refreshes every 60 seconds.
> [Paywalls] Add button and shortcut to refresh the presented live paywall

- fastlane/Fastfile
Adding missing field to complete GitHub integration with Emerge uploads
> Add repo name

- RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
- RevenueCatUI/Views/IconView.swift
> [Paywalls] Add previews for different combinations of vertical/horizontal alignment and flex distributions

- RevenueCat.xcodeproj/project.pbxproj
- Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/project.pbxproj
- Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - Live Config.xcscheme
- Tests/TestingApps/PaywallsTester/PaywallsTester.xcodeproj/xcshareddata/xcschemes/PaywallsTester - SK config.xcscheme
Had to remove PaywallsTesterTests for https://github.com/RevenueCat/purchases-ios/pull/4545 so this brings it back
> Revert "Remove PaywallsTesterTests"

- Tests/TestingApps/PaywallsTester/PaywallsTester.xcworkspace/xcshareddata/swiftpm/Package.resolved
> [Paywals] Update paywalls tester Package.resolved

- RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
- RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
We were hardcoding the title in `WrongPlatformView`
> Fix hardcoded title in WrongPlatformView

- RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
This PR calculates the whether or not the restore purchases was successful or not based on the presence of purchases instead of entitlements
> Calculate restore results based on presence of purchases

- RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
While testing this afternoon, I learned the SwiftUI's `ConfirmationDialog` has an undocumented behavior where it will log the following message to the console if a ConfirmationDialog is presented without any actions:
> A confirmation dialog was created without any actions. Confirmation dialogs should always provide users with an actionable choice. Consider using an alert if there is no action that can be taken in response to your presentation.
I wasn't sure why this was being logged at first because all of the ConfirmationDialogs in the RestorePurchasesAlert contained actions. Then, I realized that some of them only contain buttons with the `.cancel` role, and that SwiftUI likely treats these as not actions.
This PR addresses the issue described in the log by modifying the …
> Address ConfirmationDialog SwiftUI error log message

- RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
- Sources/CustomerCenter/CustomerCenterPresentationMode.swift
Remove some extra docs indicating it's in beta
> Remove extra beta Customer Center docs

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FallbackComponentPreview.swift
- Sources/Paywalls/Components/Common/PaywallComponentBase.swift
- Tests/UnitTests/Paywalls/Components/ButtonComponentTests.swift
- Tests/UnitTests/Paywalls/Components/FallbackComponentTests.swift
- Tests/UnitTests/Paywalls/Components/PartialComponentTests.swift
If the type is unknown, try to parse/render a fallback component
If the `type` is unknown for a component, look at `fallback`.
This should be a component a basic component that is known in initial release that all SDKs can render.
> [Paywalls V2] Added fallback components

- Package.swift
- RevenueCat.xcodeproj/project.pbxproj
- Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/ConfigItem.swift
- Tests/UnitTests/Paywalls/Components/Properties/MaskShapeComponentTests.swift
- Tests/UnitTests/Paywalls/Components/Properties/ShapeComponentTests.swift
- Tests/UnitTests/Paywalls/Components/StackComponentTests.swift
Decode rectangle corners as optional
Using `decodeIfPresent` and explicit optional typing to make things valid
> [Paywalls V2] Decode rectangle corners as optional

- RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
Build error on paywalls tester
Need to fix
> [Paywalls V2] Fix compilation errors

- Sources/Purchasing/Purchases/PurchasesType.swift
- Tests/UnitTests/Mocks/MockPurchases.swift
Adds purchaseWithParams to PurchasesType's deprecations
> Add purchaseWithParams to PurchasesType

- scripts/pre-commit.sh
While working on something else I noticed that the `pre-commit` hook is broken, and tries to lint deleted files. This fixes that by checking if the file was deleted
```bash
status=$(git status --porcelain "$file" | cut -c1-2)
```
It also adds another validation checking if the variables exist before using them, to prevent another error:
```bash
.git/hooks/pre-commit: line 52: [: =: unary operator expected
.git/hooks/pre-commit: line 52: [: =: unary operator expected
.git/hooks/pre-commit: line 52: [: =: unary operator expected
.git/hooks/pre-commit: line 52: [: =: unary operator expected
.git/hooks/pre-commit: line 52: [: =: unary operator expected
``
> fix: Do not lint deleted files

- RevenueCatUI/Templates/V2/ViewModelHelpers/PaywallComponentTypeTransformers.swift
- Sources/Paywalls/PaywallColor.swift
> [Paywalls] Fix hex colors with alpha component

- RevenueCatUI/Templates/V2/ViewHelpers/Fill.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester.xcworkspace/xcshareddata/swiftpm/Package.resolved
This PR fixes PaywallTester dependencies, as a follow-up of https://github.com/RevenueCat/purchases-ios/pull/4669
> fix: PaywalTester successful archive 

- RevenueCatUI/Templates/V2/ViewModelHelpers/ViewModelFactory.swift
> [Paywalls] Do not embed the badge in an extra stack

- Tests/TestingApps/PaywallsTester/PaywallsTester/Config/ConfigItem.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/Data/OfferingsPaywallsViewModel.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/APIKeyDashboardList.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingButton.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/OfferingList/OfferingsList.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallPresenter.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/PaywallViewMode+Extensions.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Changes here were made to test https://github.com/RevenueCat/purchases-ios/pull/4744
Make a separate full screen for:
- Full cover
- Sheet
https://github.com/user-attachments/assets/f5b06e0b-051d-45d2-ac8c-302ba24d317d
> [Paywalls V2] Add full cover option to Paywalls Tester

- RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
> [Paywalls] Fix ZStack alignment

- RevenueCatUI/Templates/V2/Components/Root/RootView.swift
- RevenueCatUI/Templates/V2/PaywallsV2View.swift
Fixes some margin and padding issues in the sticky footer
- Removed a `Spacer()` that was causing some margin on the bottom to show
- Fixed internal padding by applying padding of the bottom safe area inset
| ![image](https://github.com/user-attachments/assets/aa040f55-af1f-4353-a7d2-1cbdd073cc4e) | ![Simulator Screenshot - iPhone 16 - 2025-01-29 at 20 57 34](https://github.com/user-attachments/assets/efb2d68d-d1ca-407e-9d49-496b27aa0ad1) |
> [Paywalls V2] Fix footer positioning and bottom padding

- RevenueCatUI/Views/GradientView.swift
> [Paywalls] Add extra gradient previews

- RevenueCat.xcodeproj/project.pbxproj
- Sources/LocalReceiptParsing/DataConverters/Codable+Extensions.swift
- Tests/UnitTests/CustomerCenter/Events/CustomerCenterAnswerSubmittedEventTests.swift
- Tests/UnitTests/CustomerCenter/Events/CustomerCenterEventCreationDataDefault.swift
- Tests/UnitTests/CustomerCenter/Events/CustomerCenterEventTests.swift
This PR adds encoding tests for existing events.
> feat: Add tests for customer center events encoding

- RevenueCatUI/Templates/V2/Components/Stack/StackComponentView.swift
A fix to scrolling stacks for background, border, and padding
I forgot to commit this with the previous PR (#4767) 🤦‍♂️
> [Paywalls V2] Scroll fix for background/padding/border

- RevenueCatUI/CustomerCenter/Views/AppUpdateWarningView.swift
While working on some padding, I went one step further  and aligned the buttons to the bottom.
> fix: [AppUpdateWarningView] Tweak buttons bottom alignment and padding

- CHANGELOG.md
> Update changelog with 4.43.3 and 4.43.4

- RevenueCatUI/CustomerCenter/Data/PurchaseInformation.swift
Fixed a compilation issue I was getting on main:
> Fix compilation issues in Xcode 16.3 beta

- BackendIntegrationTests/BackendIntegrationTests-All-CI.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-All.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-CustomEntitlements.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-Offline.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-Other.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-SK1.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-SK2.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-Shedder.xctestplan
This is blocking the release, so I'll disable till I have time to work on it.
PS: Glad this is running now :)
> chore: Disable EventsManagerIntegrationTests till fixed

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/CustomerCenter/CustomerCenterView+Actions.swift
- RevenueCatUI/CustomerCenter/Data/CustomerCenterActionViewModifier.swift
- RevenueCatUI/CustomerCenter/Data/CustomerCenterActionWrapper.swift
- RevenueCatUI/CustomerCenter/Data/CustomerCenterManagementOption.swift
- RevenueCatUI/CustomerCenter/View+PresentCustomerCenter.swift
- RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
- Tests/TestingApps/PaywallsTester/PaywallsTester/UI/Views/SamplePaywallsList.swift
Add `onCustomerCenterManagementOptionSelected` modifier
```swift
CustomerCenterView()
.onCustomerCenterManagementOptionSelected { action in
switch action {
case is CustomerCenterManagementOption.Cancel:
print("Cancel action triggered")
case let customUrl as CustomerCenterManagementOption.CustomUrl:
print("Opening URL: \(customUrl.url)")
default:
print("Unknown action")
}
}
```
> Add `onCustomerCenterManagementOptionSelected` modifier

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Diagnostics/DiagnosticsEvent.swift
- Sources/Diagnostics/DiagnosticsTracker.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
- Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
- Tests/UnitTests/Purchasing/Purchases/BasePurchasesTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesDiagnosticsTrackingTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesRestoreTests.swift
- Tests/UnitTests/Purchasing/Purchases/PurchasesSyncPurchasesTests.swift
- Tests/UnitTests/SubscriberAttributes/PurchasesSubscriberAttributesTests.swift
This PR implements the `apple_present_code_redemption_sheet_request` diagnostics event
> [Diagnostics] add `apple_present_code_redemption_sheet_request` event

- RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
Addresses [MON-927](https://linear.app/revenuecat/issue/MON-927) for iOS. Android PR is here: https://github.com/RevenueCat/purchases-android/pull/2266.
> [Paywalls V2] Fixes badges not being overriden

- Sources/Purchasing/StoreKit2/StoreKit2TransactionListener.swift
- Tests/StoreKitUnitTests/PurchasesOrchestratorCommonTests.swift
- Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionListenerTests.swift
The SDK is not building in Xcode 14 and some tests are failing in Xcode 15
This PR fixes these issues
> Fix build issues and tests in older versions of Xcode

- Tests/BackendIntegrationTests/LoadShedderIntegrationTests.swift
- Tests/BackendIntegrationTests/__Snapshots__/LoadShedderIntegrationTests/testCanGetOfferings.1.json
Update integration tests after changes to the load shedder integration test project.
> Fix load shedder integration tests after project changes

- RevenueCatUI/Views/GradientView.swift
> [Paywalls] Fix gradients in angles around 135º

- Sources/Diagnostics/DiagnosticsEvent.swift
- Sources/Diagnostics/DiagnosticsTracker.swift
- Sources/OfflineEntitlements/OfflineCustomerInfoCreator.swift
- Sources/OfflineEntitlements/PurchasedProductsFetcher.swift
- Sources/Purchasing/Purchases/Purchases.swift
- Sources/Purchasing/StoreKit2/StoreKit2TransactionFetcher.swift
- Tests/StoreKitUnitTests/OfflineEntitlements/PurchasedProductsFetcherTests.swift
- Tests/StoreKitUnitTests/StoreKit2/StoreKit2TransactionFetcherTests.swift
- Tests/UnitTests/Diagnostics/DiagnosticsTrackerTests.swift
- Tests/UnitTests/Mocks/MockDiagnosticsTracker.swift
> Add diagnostics event when AppTransaction fails to be fetched

- RevenueCatUI/CustomerCenter/ViewModels/ManageSubscriptions/ManageSubscriptionsViewModel.swift
- RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsButtonsView.swift
- RevenueCatUI/Data/Strings.swift
We want to give some feedback on why a promo offer is not shown. 
Add a log that indicates that's not eligible.
> feat: Add log for promo offer eligibility

- RevenueCatUI/CustomerCenter/Views/UIKit Compatibility/CustomerCenterViewController.swift
`CustomerCenterViewController` was actually showing 2 `CustomerCenterView`s
This PR fixes it.
> Fix `CustomerCenterViewController` view

- CHANGELOG.md
As the title says. 
Related: https://github.com/RevenueCat/purchases-ios/pull/4978
> Updates the changelog for hotfix 4.43.5.

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/Templates/V2/Components/Packages/PurchaseButton/PurchaseButtonComponentView.swift
- RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/PurchaseButtonInPackage.swift
Need a way to to show that purchase button works inside of a package
- Added a SwiftUI example that tests a purchase button inside of a package
> Added purchase button in package SwiftUI Preview example

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
- RevenueCatUI/Templates/V2/ViewHelpers/Shape.swift
- Sources/Paywalls/Components/Common/Dimension.swift
- Sources/Paywalls/Components/Common/PaywallComponentPropertyTypes.swift
- Sources/Paywalls/Components/PaywallButtonComponent.swift
- Sources/Paywalls/Components/PaywallCarouselComponent.swift
- Sources/Paywalls/Components/PaywallStackComponent.swift
- Sources/Paywalls/Components/PaywallTimelineComponent.swift
- Tests/UnitTests/Paywalls/Components/Properties/DefaultEnumTests.swift
Add default values for enum values for more backwards compatibility
- Added sensible defaults to a bunch of enums when being decoded
- If no sensible value, defaults to a `unknown` which is then handled in the code
> [Paywalls V2] Add default values for enums

- Gemfile.lock
- fastlane/Pluginfile
Uses updated logic in fastlane plugin to not detect failures in junit file if the test was retried successfully
> Update internal fastlane plugin to not try new scan run when retried tests eventually passed

- Tests/RevenueCatUITests/PaywallViewEventsTests.swift
Fix flaky tests in `PaywallViewEventsTests`
- Remove randomness with scheme
- Wait after adding to heirarchy
- Wait more for close event
> Maybe fix some flaky PaywallViewEventsTests in CI

- RevenueCatUI/Data/Strings.swift
- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
This helps debugging URL-opening issues. Based on feedback from a customer.
> [Paywalls v2] Adds logs to indicate whether URLs are opened successfully

- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentViewModel.swift
- Sources/Paywalls/Components/PaywallButtonComponent.swift
> [Paywalls] Add new button component action for web paywall links

- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
> [Paywalls] Remove url manipulation and alert from web paywall links

- RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
- RevenueCatUI/Templates/V2/Components/Button/ButtonComponentView.swift
- RevenueCatUI/Templates/V2/Components/Root/RootView.swift
- RevenueCatUI/Templates/V2/EnvironmentObjects/OpenSheet.swift
This PR adjusts the sheet view to present from the root of the paywall view so the sheet always takes up the full size of the screen.
All credit to @MarkVillacampa !
https://github.com/user-attachments/assets/0ac6b39d-d2fa-40d5-a0a1-a87697f02fc7
> Make sheet take up full screen

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Networking/Caching/WebProductsCallback.swift
- Sources/Networking/HTTPClient/HTTPRequest.swift
- Sources/Networking/HTTPClient/HTTPRequestPath.swift
- Sources/Networking/OfferingsAPI.swift
- Sources/Networking/Operations/GetWebProductsOperation.swift
- Sources/Networking/Responses/WebProductsResponse.swift
- Sources/Networking/WebBillingHTTPRequestPath.swift
- Tests/UnitTests/Mocks/MockHTTPClient.swift
- Tests/UnitTests/Mocks/MockOfferingsAPI.swift
Add endpoint to fetch web billing product information. Currently unused, to be used in future PRs.
> Add endpoint for fetching web billing products

- .circleci/config.yml
> use m2pro.large for all jobs

- .circleci/config.yml
> Revert CircleCI machine type to medium

- RevenueCatUI/Templates/V2/Components/Button/BottomSheetView.swift
> Fix sheet view in v2 paywall not covering bottom safe area

- RevenueCat.xcodeproj/project.pbxproj
- RevenueCatUI/CustomerCenter/ButtonStyles.swift
- RevenueCatUI/CustomerCenter/Data/CustomerCenterConfigData+Mock.swift
- RevenueCatUI/CustomerCenter/Views/CustomerCenterView.swift
- RevenueCatUI/CustomerCenter/Views/FeedbackSurveyView.swift
- RevenueCatUI/CustomerCenter/Views/ManageSubscriptionsView.swift
- RevenueCatUI/CustomerCenter/Views/NoSubscriptionsView.swift
- RevenueCatUI/CustomerCenter/Views/RestorePurchasesAlert.swift
- RevenueCatUI/CustomerCenter/Views/SubscriptionDetailsView.swift
- RevenueCatUI/CustomerCenter/Views/WrongPlatformView.swift
- Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
- Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
- Tests/RevenueCatUITests/CustomerCenter/Mocks/MockCustomerCenterPurchases.swift
After reverting the subscription list, I'm re-applying it in pieces to cleanup and track down the issue.
Improve CustomerCenterConfigData mocking interface
> Improve mock interface for CustomerCenterConfigData

- RevenueCatUI/CustomerCenter/Data/DiscountsHandler.swift
- Tests/RevenueCatUITests/CustomerCenter/DiscountsHandlerTests.swift
#5031 broke some watchOS tests
> Fix watchOS tests

- Tests/RevenueCatUITests/CustomerCenter/BaseManageSubscriptionViewModelTests.swift
- Tests/RevenueCatUITests/CustomerCenter/ContactSupportUtilitiesTests.swift
- Tests/RevenueCatUITests/CustomerCenter/ManageSubscriptionsViewModelTests.swift
> Fix vc tests

- .circleci/config.yml
- fastlane/Fastfile
Sends a Slack message with the results of the load shedder v3 daily tests
> Send slack message for load shedder v3 tests report

- RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrenciesListSection.swift
- RevenueCatUI/CustomerCenter/Views/Virtual Currencies/VirtualCurrencyBalanceListRow.swift
This PR:
- Re-adds the section header to the `VirtualCurrenciesListSection`
- Adds a preview name for the `VirtualCurrencyBalanceListRow` preview
> VC Customer Center Minor Design Tweaks

- Examples/rc-maestro/README.md
Add README with basics to run the app
> Add README to Maestro app

- RevenueCatUI/CustomerCenter/Views/RelevantPurchasesListView.swift
The title should say subscriptions instead of actions.
- Use the correct title for the section
> Use correct title for section

- RevenueCatUI/CustomerCenter/Views/ScrollViewWithOSBackground.swift
Noticed we have this helper for `scrollBounceBehaviorBasedOnSize`
- Add `scrollBounceBehaviorBasedOnSize` to CustomerCenter scrollviews
> Use scrollBounceBehaviorBasedOnSize for CustomerCenter scrollview

- Examples/rc-maestro/maestro/config.yaml
- Examples/rc-maestro/maestro/customer_center/change_plans/customer_center_change_plans.yaml
- Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_empty.yaml
- Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_restore_purchases.yaml
- Examples/rc-maestro/maestro/customer_center/manage_subscriptions/customer_center_manage_subscriptions_see_all_purchases.yaml
- Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_accept_promo_offer.yaml
- Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_multiple_subs_accept_promo_offer.yaml
- Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_multiple_subs_reject_promo_offer.yaml
- Examples/rc-maestro/maestro/customer_center/promo_offer/customer_center_reject_promo_offer.yaml
- Examples/rc-maestro/maestro/utils/buy_product.yaml
- Examples/rc-maestro/maestro/utils/cancel_subscription_group.yaml
- Examples/rc-maestro/maestro/utils/promo_offer_accept.yaml
- Examples/rc-maestro/maestro/utils/promo_offer_group_reject.yaml
- Examples/rc-maestro/maestro/utils/promo_offer_reject.yaml
- RevenueCatUI/CustomerCenter/ButtonStyles.swift
Now that we've added a new design, I'm extending the tests to support the new UI.
- Add tests for multiple active subscriptions
- Remove fixed order for tests that don't require it
> Add new test cases for maestro + customer center

- RevenueCatUI/Templates/V2/Components/Tabs/TabControlButtonComponentView.swift
- RevenueCatUI/Templates/V2/Components/Tabs/TabControlToggleComponentView.swift
- RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentView.swift
- RevenueCatUI/Templates/V2/Components/Tabs/TabsComponentViewModel.swift
- RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/FamilySharingTogglePreview.swift
- RevenueCatUI/Templates/V2/Previews/TemplateComponentsViewPreviews/MultiTierPreview.swift
- Sources/Paywalls/Components/PaywallTabsComponent.swift
> [Paywalls] Use tab id instead of tab index to select tab

- RevenueCat.xcodeproj/project.pbxproj
- Sources/Logging/Strings/Strings.swift
- Sources/Logging/Strings/VirtualCurrencyStrings.swift
- Sources/Virtual Currencies/VirtualCurrencyManager.swift
- Tests/UnitTests/Virtual Currencies/VirtualCurrencyManagerTests.swift
This PR adds several log messages to the `VirtualCurrencyManager` and adds tests to ensure the logs are logged properly.
> Add logs to VirtualCurrencyManager

- .github/workflows/issue-notifications.yml
Bump action wasn't correct in v10
Bump action to v11
> Bump ack action to v11

- RevenueCatUI/CustomerCenter/Views/SubscriptionDetailView.swift
Make loading animation smoother
https://github.com/user-attachments/assets/54384406-bd22-45ca-9364-1d1ff1dad243
> Add smoother loading animation to SubscriptionDetailView

- BackendIntegrationTests/BackendIntegrationTests-Offline.xctestplan
- BackendIntegrationTests/BackendIntegrationTests-Other.xctestplan
- RevenueCat.xcodeproj/project.pbxproj
- Tests/BackendIntegrationTests/OtherIntegrationTests.swift
- Tests/BackendIntegrationTests/VirtualCurrencyIntegrationTests.swift
Adds full end-to-end integration tests that:
- Check that VC balance + metadata from the backend
- Make a purchase with SK1 & SK2 and verify that VCs were granted to the user correctly
> VC Integration Tests

- RevenueCatUI/CustomerCenter/ViewModels/CustomerCenterViewModel.swift
- Tests/RevenueCatUITests/CustomerCenter/CustomerCenterViewModelTests.swift
We got a report where some google products were not being shown in the customer center list.
- Ignore base plan to grab the subscription
- Add test to cover the issue
I'll go through the existing tests one by one because we cannot trust them anymore 😿
> Fix google products display for customer center

- Tests/TestingApps/PaywallsTester/PaywallsTester/PaywallsPreview.swift
Needed a way to visually test deep links
Shows an alert when `scheme://deeplinktest` is detected for the URL
https://github.com/user-attachments/assets/d20fb758-3c1e-4c00-a417-080e8e94e5f2
> Adding deep link for testing in Paywalls Tester

- RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
Show account id only on DEBUG builds
> Show account id only debug for customer center

- RevenueCatUI/CustomerCenter/Views/ScrollViewSection.swift
Follow-up of https://github.com/RevenueCat/purchases-ios/pull/5466/files
- Add `CardStyleModifier` for customer center
> Add private CardStyleModifier

- Sources/Caching/FileRepository.swift
- Sources/Caching/KeyedDeferredValueStore.swift
- Sources/Caching/LargeItemCacheType.swift
- Sources/Logging/Strings/FileRepositoryStrings.swift
- Tests/UnitTests/Caching/FileRepositoryTests.swift
- Tests/UnitTests/Mocks/MockSimpleNetworkService.swift
I broke things in the CI pipeline and I need to fix it
> Fix the tests and implicit returns that broke our CI on main

- .github/CODEOWNERS
Adds Monetization team as CODEOWNER for paywalls-related code
> Add Monetization as CODEOWNER

- RevenueCatUI/Templates/V2/Components/Stack/StackComponentViewModel.swift
- RevenueCatUI/Templates/V2/ViewHelpers/BadgeModifier.swift
Borders were not correct for badges in iOS
> MON-1231 - Fix badge border

- RevenueCat.xcodeproj/project.pbxproj
Just noticed this file does not exist anymore
> fix broken RevenueCat.xcworkspace

- .circleci/config.yml
- Gemfile.lock
Fix circular dependency issue https://github.com/RevenueCat/fastlane-plugin-revenuecat_internal/pull/91
> Update `fastlane-plugin-revenuecat_internal` 
